### ISSUE TITLE
Bot login 后丢失 nick

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai#1019]
Bot 在 login 后丢失了 nick

`@since 2.4-RC`, 与好友列表缓存的修改有关

```
2021-02-12 16:36:23 E/console: kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized
kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized
        at net.mamoe.mirai.internal.QQAndroidBot.getNick(QQAndroidBot.kt:121)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:176)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand$handle$1.invokeSuspend(BuiltInCommands.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by sandtechnology** [comment]
其实可以考虑直接从缓存载入nick?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
