### ISSUE TITLE
正则相关MessageDSL错误

### ISSUE THREAD

**Issue by ryoii** [mamoe/mirai#103]
测试代码
```kotlin
suspend fun main() {
    val bot = Bot(**********, "*************")

    bot.subscribeGroupMessages {
        matching(Regex("^测试([0-9]+)$")) {
            reply(it.groupValues[1])
        }

        matching(Regex("猴子")) {
            reply("香蕉")
        }
    }

    bot.login()
    bot.join()
}
```

错误栈
```
Bot(3402393995) 22:06:49 : An exception was thrown under a coroutine of Bot
java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.message.MessageReceipt (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.message.MessageReceipt are in unnamed module of loader 'app')
	at net.mamoe.mirai.qqandroid.TestKt$$special$$inlined$matching$2.invokeSuspend(subscribeMessages.kt:763)
	at net.mamoe.mirai.qqandroid.TestKt$$special$$inlined$matching$2.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.qqandroid.TestKt$main$$inlined$subscribeGroupMessages$1$1.invokeSuspend(subscribeMessages.kt:133)
	at net.mamoe.mirai.qqandroid.TestKt$main$$inlined$subscribeGroupMessages$1$1.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.qqandroid.TestKt$main$$inlined$subscribeGroupMessages$1$2.invokeSuspend(subscriber.kt:212)
	at net.mamoe.mirai.qqandroid.TestKt$main$$inlined$subscribeGroupMessages$1$2.invoke(subscriber.kt)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:58)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:58)
	at net.mamoe.mirai.event.internal.InternalEventListenersKt$callAndRemoveIfRequired$$inlined$forEachNode$lambda$1.invokeSuspend(InternalEventListeners.kt:164)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Network(3402393995) 22:06:49 : Send: MessageSvc.PbSendMsg
Network(3402393995) 22:06:49 : Exception in NetworkHandler
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[DefaultDispatcher, Continuation at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$6.invokeSuspend(QQAndroidBotNetworkHandler.kt:537)@b1dbe8c]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:93)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:64)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Caused by: java.lang.IllegalStateException: Job UndispatchedCoroutine{Cancelled}@611e7a02 is already complete or completing, but is being completed with CompletedExceptionally[kotlinx.coroutines.JobCancellationException: Parent job is Cancelled; job=UndispatchedCoroutine{Cancelled}@611e7a02]
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:827)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(Builders.common.kt:207)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	... 4 more
Caused by: kotlinx.coroutines.JobCancellationException: Parent job is Cancelled; job=UndispatchedCoroutine{Cancelled}@611e7a02
Caused by: java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.message.MessageReceipt (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.message.MessageReceipt are in unnamed module of loader 'app')
	at net.mamoe.mirai.qqandroid.TestKt$$special$$inlined$matching$2.invokeSuspend(subscribeMessages.kt:763)
	at net.mamoe.mirai.qqandroid.TestKt$$special$$inlined$matching$2.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.qqandroid.TestKt$main$$inlined$subscribeGroupMessages$1$1.invokeSuspend(subscribeMessages.kt:133)
	at net.mamoe.mirai.qqandroid.TestKt$main$$inlined$subscribeGroupMessages$1$1.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.qqandroid.TestKt$main$$inlined$subscribeGroupMessages$1$2.invokeSuspend(subscriber.kt:212)
	at net.mamoe.mirai.qqandroid.TestKt$main$$inlined$subscribeGroupMessages$1$2.invoke(subscriber.kt)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:58)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:58)
	at net.mamoe.mirai.event.internal.InternalEventListenersKt$callAndRemoveIfRequired$$inlined$forEachNode$lambda$1.invokeSuspend(InternalEventListeners.kt:164)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Network(3402393995) 22:06:49 : Received: MessageSvc.PbSendMsg.Response.SUCCESS
```

**Comment by Him188** [comment]
kotlin编译错了

**Comment by Him188** [comment]
经测试无法复现. 应该为偶然的 Kotlin 编译错误?
