### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by CodeMzt** [mamoe/mirai#1034]
Login failed: 在 Bot login 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new    调试信息: kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized
2021-02-20 08:18:14 E/console: java.lang.IllegalStateException: 在 Bot login 时遇到了意料之中的问题. 请完整复制此日志提 交给 mirai: https://github.com/mamoe/mirai/issues/new    调试信息: kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized
java.lang.IllegalStateException: 在 Bot login 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new    调试信息: kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:23)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:21)
        at net.mamoe.mirai.internal.AbstractBot$Login.doLogin(AbstractBot.kt:297)
        at net.mamoe.mirai.internal.AbstractBot$Login$doLogin$1.invokeSuspend(AbstractBot.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized
        at net.mamoe.mirai.internal.QQAndroidBot.getNick(QQAndroidBot.kt:121)
        at net.mamoe.mirai.internal.AbstractBot$Login.doLogin(AbstractBot.kt:295)
        ... 10 more

**Comment by Karlatemp** [comment]
#1023
