### ISSUE TITLE
BotFactory.INSTANCE.newBot出错 ClassNotFoundException: net.mamoe.mirai.internal.MiraiImpl

### ISSUE THREAD

**Issue by xingchenxuup** [mamoe/mirai#1054]
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.internal.MiraiImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18)
	at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt:37)
	at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt)
	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:115)
	at net.mamoe.mirai.BotFactory.newBot(BotFactory.kt:62)
	at com.rabbit.robot.star.RobotStar.<clinit>(RobotStar.java:31)
	... 1 more

**Comment by Him188** [comment]
https://github.com/mamoe/mirai/blob/dev/docs/ConfiguringProjects.md

**Comment by Him188** [comment]
mirai 运行时需要 net.mamoe:mirai-core
