### ISSUE TITLE
无法在群中找到 Bot 本身

### ISSUE THREAD

**Issue by PeratX** [mamoe/mirai#106]
```Java
java.util.NoSuchElementException: member Bot的QQ not found in group xxxx
        at net.mamoe.mirai.qqandroid.GroupImpl.get(ContactImpl.kt:557)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$ReqPush$decode$packets$1$$special$$inlined$read$lambda$1.invoke(OnlinePush.kt:356)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$ReqPush$decode$packets$1$$special$$inlined$read$lambda$1.invoke(OnlinePush.kt:185)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:278)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:265)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:602)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:251)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:219)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:382)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:377)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:366)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

使用 mirai-core 0.24.1 bintary 版本。

**Comment by Him188** [comment]
感动, 这么多层inline, kotlin居然报对了行号
