### ISSUE TITLE
使用 mirai 2.4.1 和 Kotlin 1.4.30 时发生 java.lang.NoSuchMethodError: kotlin.time.Duration$Companion.getZERO()D

### ISSUE THREAD

**Issue by xggz** [mamoe/mirai#1066]
#### 问题描述
使用java开发的程序，maven依赖**mirai-core-jvm 2.4.1**和**kotlin-stdlib 1.4.21**，机器人登录时会出现如下异常日志，每次登录都会复现，但是暂未发现此错误引起的其它问题；
另外参照文档，使用**kotlin-stdlib-jdk8 1.4.21**或**kotlin-stdlib-jdk8 1.4.31**都无法启动机器人，使用**kotlin-stdlib**可以。

#### 日志
```
2021-03-02 15:29:17 I/Bot 647891941: Logging in...
2021-03-02 15:29:17 V/Net 647891941: Loading BdhSession from cache file
2021-03-02 15:29:17 V/Net 647891941: No server list cached.
2021-03-02 15:29:17 I/Net 647891941: Connected to server 203.205.255.221:8080
2021-03-02 15:29:17 V/Net 647891941: Send: wtlogin.login
2021-03-02 15:29:18 V/Net 647891941: Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
2021-03-02 15:29:18 V/Net 647891941: Send: wtlogin.login
2021-03-02 15:29:18 V/Net 647891941: Recv: LoginPacketResponse.Success
2021-03-02 15:29:18 I/Net 647891941: Login successful
2021-03-02 15:29:18 V/Net 647891941: Send: StatSvc.register
2021-03-02 15:29:19 V/Net 647891941: Recv: Response(StatSvc.register)
2021-03-02 15:29:19 I/Net 647891941: Scheduled key refresh in 5h 55min 0.0s.
2021-03-02 15:29:19 V/Net 647891941: Send: StatSvc.register
2021-03-02 15:29:19 E/Net 647891941: Exception in NetworkHandler
java.lang.NoSuchMethodError: kotlin.time.Duration$Companion.getZERO()D
	at kotlinx.coroutines.DelayKt.toDelayMillis-LRDsOJo(Delay.kt:101)
	at kotlinx.coroutines.DelayKt.delay-p9JZ4hM(Delay.kt:90)
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$11.invokeSuspend(QQAndroidBotNetworkHandler.kt:275)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-03-02 15:29:19 V/Net 647891941: Recv: Response(StatSvc.register)
2021-03-02 15:29:19 I/Net 647891941: Awaiting ConfigPushSvc.PushReq.
2021-03-02 15:29:19 I/Net 647891941: Syncing friend message history...
2021-03-02 15:29:19 I/Net 647891941: Start loading friend list...
2021-03-02 15:29:19 I/Net 647891941: Start loading stranger list...
2021-03-02 15:29:19 V/Net 647891941: Send: StatSvc.GetDevLoginInfo
2021-03-02 15:29:19 V/Net 647891941: Send: MessageSvc.PbGetMsg
2021-03-02 15:29:19 V/Net 647891941: Send: OidbSvc.0x496
2021-03-02 15:29:19 V/Net 647891941: Send: OidbSvc.0x5d2_0
2021-03-02 15:29:19 V/Net 647891941: Send: friendlist.getFriendGroupList
2021-03-02 15:29:19 V/Net 647891941: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=2)
```

**Comment by Him188** [comment]
Kotlin 在 1.4.30 做了一些 inline class ABI 变更

现在可以尝试 mirai 2.5-M1 + Kotlin 1.4.30
