### ISSUE TITLE
group.uploadFileAndSend()构造消息失败

### ISSUE THREAD

**Issue by xszqxszq** [mamoe/mirai#1098]
~~调用group.filesRoot.uploadAndSend()时出现了Exception。经测试无论是upload()还是uploadAndSend()，以及File/ExternalResource，均会上传失败（但错误日志有所不同）。上传前调用File.exists()确认文件的确存在。~~
调用group.uploadFileAndSend()出现异常，错误日志在下一条回复中。

```
2021-03-15 00:21:10 V/Net 2262349573: Send: OidbSvc.0x6d8_1
2021-03-15 00:21:10 V/Net 2262349573: Recv: CommonOidbResponse.Success
2021-03-15 00:21:10 V/Net 2262349573: Send: OidbSvc.0x6d8_1
2021-03-15 00:21:10 V/Net 2262349573: Send: OnlinePush.RespPush
2021-03-15 00:21:10 V/Net 2262349573: Send: OnlinePush.RespPush
2021-03-15 00:21:10 V/Net 2262349573: Recv: CommonOidbResponse.Success
2021-03-15 00:21:10 V/Net 2262349573: Send: OidbSvc.0x6d6_2
2021-03-15 00:21:10 V/Net 2262349573: Recv: CommonOidbResponse.Success
2021-03-15 00:21:11 V/Net 2262349573: Send: MessageSvc.PbSendMsg
2021-03-15 00:21:11 V/Net 2262349573: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-03-15 00:21:11 V/Bot 2262349573: Group(******) <- [mirai:quote:[****],[-******]]正在处理中，请稍等片刻……
java.lang.VerifyError: JVMVRFY038 无效目标上的 invokespecial 类=net/mamoe/mirai/utils/RemoteFile$uploadAndSend$2，方法=invokeSuspend(Ljava/lang/Object;)Ljava/lang/Object;，pc=22
Exception Details:
  Location:
    net/mamoe/mirai/utils/RemoteFile$uploadAndSend$2.invokeSuspend(Ljava/lang/Object;)Ljava/lang/Object; @22: JBinvokespecial
  Reason:
    The method invoked via invokespecial is invalid.
	at net.mamoe.mirai.utils.RemoteFile.uploadAndSend(RemoteFile.kt)
	at tk.xszq.otomadbot.OtomadBotKt$doInitSubscribe$19$1$1.invokeSuspend(OtomadBot.kt:1430)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 复现

~~1. 在eventChannel.subscribeGroupMessages中调用group.filesRoot.uploadAndSend()上传一个小体积音频文件
2. 运行代码，待代码被触发后即可看到报错~~

#### 版本
- mirai-core: `2.5-M2`

**Comment by xszqxszq** [comment]
发现如果使用group.upload()或group.uploadFileAndSend()会出现成功上传但有构造消息错误：
```
java.lang.IllegalStateException: Failed to create FileMessage.
	at net.mamoe.mirai.utils.RemoteFile$Companion.uploadFile(RemoteFile.kt:370)
	at net.mamoe.mirai.utils.RemoteFile$Companion$uploadFile$1.invokeSuspend(RemoteFile.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
使用filesRoot.resolveSibling("/path/to/file").upload()能正常上传，toMessage()依然返回null。

**Comment by Karlatemp** [comment]
道理我都懂，但是你为什么要给一个目录写数据

**Comment by xszqxszq** [comment]
> 道理我都懂，但是你为什么要给一个目录写数据

现在暂时没文档，比较懵……
看我后面补充的，改成了resolve一个文件再上传或者用group.uploadFileAndSend()，但是只能上传不能成功得到FileMessage用于发出

**Comment by xszqxszq** [comment]
发现bot上传后好像resolve不到刚传的文件，群文件列表刷新一下倒会有出现上传的文件，不知道是什么机制

**Comment by Him188** [comment]
> 发现bot上传后好像resolve不到刚传的文件，群文件列表刷新一下倒会有出现上传的文件，不知道是什么机制

QQ 允许文件重名，因此 resolve 总是会是一个新文件。需要通过 id 来解决重名
