### ISSUE TITLE
在 SvcReqMSFLoginNotify (OtherClient online) 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by zwpride** [mamoe/mirai#1109]
2021-03-21 17:16:47 V/Net XXXX（机器人QQ）: Loading BdhSession from cache file
2021-03-21 17:16:47 V/Net XXXX（机器人QQ）: Loading server list from cache.
2021-03-21 17:16:47 I/Net XXXX（机器人QQ）: Connected to server 180.102.110.55:443
2021-03-21 17:16:47 V/Net XXXX（机器人QQ）: Send: wtlogin.login
2021-03-21 17:16:48 V/Net XXXX（机器人QQ）: Recv: LoginPacketResponse.Success
2021-03-21 17:16:48 I/Net XXXX（机器人QQ）: Login successful
2021-03-21 17:16:48 V/Net XXXX（机器人QQ）: Send: StatSvc.register
2021-03-21 17:16:48 V/Net XXXX（机器人QQ）: Recv: Response(StatSvc.register)
2021-03-21 17:16:48 I/Net XXXX（机器人QQ）: Scheduled key refresh in 5h 55min 0.0s.
2021-03-21 17:16:48 V/Net XXXX（机器人QQ）: Send: StatSvc.register
2021-03-21 17:16:48 V/Net XXXX（机器人QQ）: Recv: Response(StatSvc.register)
2021-03-21 17:16:48 I/Net XXXX（机器人QQ）: Awaiting ConfigPushSvc.PushReq.
2021-03-21 17:16:48 I/Net XXXX（机器人QQ）: Syncing friend message history...
2021-03-21 17:16:48 I/Net XXXX（机器人QQ）: Start loading friend list...
2021-03-21 17:16:48 I/Net XXXX（机器人QQ）: Start loading stranger list...
2021-03-21 17:16:48 V/Net XXXX（机器人QQ）: Send: MessageSvc.PbGetMsg
2021-03-21 17:16:48 V/Net XXXX（机器人QQ）: Send: StatSvc.GetDevLoginInfo
2021-03-21 17:16:48 V/Net XXXX（机器人QQ）: Send: friendlist.getFriendGroupList
2021-03-21 17:16:48 V/Net XXXX（机器人QQ）: Send: OidbSvc.0x496
2021-03-21 17:16:48 V/Net XXXX（机器人QQ）: Send: OidbSvc.0x5d2_0
2021-03-21 17:16:48 I/Net XXXX（机器人QQ）: Syncing friend message history: Success.
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=2)
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Recv: StrangerList.GetStrangerList.Response(result=0)
2021-03-21 17:16:49 I/Bot XXXX（机器人QQ）: Online OtherClients: mirai(IOS)
2021-03-21 17:16:49 I/Net XXXX（机器人QQ）: Successfully loaded stranger list: 1 in total
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Recv: TroopManagement.GetTroopConfig.Response(true)
2021-03-21 17:16:49 I/Net XXXX（机器人QQ）: Start loading group list...
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Send: friendlist.GetTroopListReqV2
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Recv: FriendList.GetFriendGroupList.Response
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Loading friend list: 4/4
2021-03-21 17:16:49 I/Net XXXX（机器人QQ）: Successfully loaded friend list: 4 in total
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Recv: FriendList.GetFriendGroupList.Response
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Send: friendlist.GetTroopMemberListReq
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Send: friendlist.GetTroopMemberListReq
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Recv: FriendList.GetTroopMemberList.Response
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Recv: FriendList.GetTroopMemberList.Response
2021-03-21 17:16:49 I/Net XXXX（机器人QQ）: Successfully loaded group list: 2 in total.
2021-03-21 17:16:49 V/Bot XXXX（机器人QQ）: Event: OtherClientOfflineEvent(client=OtherClient(bot=XXXX（机器人QQ）,deviceName=mirai,platform=IOS))
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Send: StatSvc.GetDevLoginInfo
2021-03-21 17:16:49 V/Net XXXX（机器人QQ）: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=1)
2021-03-21 17:16:51 V/Net XXXX（机器人QQ）: Recv: ConfigPushSvc.PushReq.PushReqResponse.ServerListPush
2021-03-21 17:16:51 I/Net XXXX（机器人QQ）: Server list updated.
2021-03-21 17:16:51 I/Bot XXXX（机器人QQ）: Server list: 36.155.228.120:14000, 120.232.22.118:14000, 120.232.18.126:8080, 111.30.181.201:80, 36.155.229.147:14000, 120.232.22.94:443, 111.30.169.91:80, 36.155.249.120:80, msfwifi.3g.qq.com:8080, 111.30.179.153:80.
2021-03-21 17:16:51 V/Net XXXX（机器人QQ）: Saving bdh session to cache
2021-03-21 17:16:51 V/Net XXXX（机器人QQ）: Saving server list to cache
2021-03-21 17:16:51 V/Net XXXX（机器人QQ）: Send: ConfigPushSvc.PushResp
2021-03-21 17:16:51 I/Net XXXX（机器人QQ）: ConfigPushSvc.PushReq: Server updated.
2021-03-21 17:16:51 D/Net XXXX（机器人QQ）: Received unknown commandName: ConfigPushSvc.PushDomain
2021-03-21 17:16:51 V/Net XXXX（机器人QQ）: Recv: ConfigPushSvc.PushReq.PushReqResponse.ConfigPush
2021-03-21 17:16:51 V/Net XXXX（机器人QQ）: Saving bdh session to cache
2021-03-21 17:16:51 V/Net XXXX（机器人QQ）: Send: ConfigPushSvc.PushResp
2021-03-21 17:16:51 V/Net XXXX（机器人QQ）: Send: StatSvc.GetDevLoginInfo
2021-03-21 17:16:52 V/Net XXXX（机器人QQ）: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=1)
2021-03-21 17:16:52 E/Net XXXX（机器人QQ）: Exception on processing pendingIncomingPackets.
java.lang.IllegalStateException: 在 SvcReqMSFLoginNotify (OtherClient online) 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   Failed to find corresponding instanceInfo. 调试信息: SvcReqMSFLoginNotifyData(iAppId=537062409, status=1, tablet=1, iPlatform=109, title=上线通知, info=你的帐号在平板电脑上登录了, iProductType=0, iClientType=65805, vecInstanceList=[InstanceInfo(iAppId=537062409, tablet=1, iPlatform=109, iProductType=0, iClientType=65805)])
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:23)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:21)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$SvcReqMSFLoginNotify.decode(StatSvc.kt:276)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$SvcReqMSFLoginNotify$decode$1.invokeSuspend(StatSvc.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at me.zwpride.future.WithConfiguration.main(WithConfiguration.kt:30)

2021-03-21 17:16:52 V/Net XXXX（机器人QQ）: Send: StatSvc.GetDevLoginInfo
2021-03-21 17:16:52 V/Net XXXX（机器人QQ）: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=1)

**Comment by zwpride** [comment]
开发使用安卓PHONE协议，另外机器人在服务器使用PAD协议登录中...
