### ISSUE TITLE
mcl1.0.3或1.0.5+mirai-console1.0.0+mirai-console-terminal1.0.0+mirai-core-all1.3.3无法登录

### ISSUE THREAD

**Issue by RiotGamesU** [mamoe/mirai#1122]
以前同样的设备与版本登录过,现在却登陆不上了

```

C:\Users\xxxx\Desktop\mirai>.\mcl --disable-script updater
 14:57:56 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 14:57:56 [INFO] https://github.com/iTXTech/mirai-console-loader
 14:57:56 [INFO] This program is licensed under GNU AGPL v3
 14:57:56 [INFO] Script "updater" has been disabled.

C:\Users\xxxx\Desktop\mirai>.\mcl
 14:58:26 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 14:58:26 [INFO] https://github.com/iTXTech/mirai-console-loader
 14:58:26 [INFO] This program is licensed under GNU AGPL v3
 14:58:26 [DEBUG] Loading script: announcement.js
 14:58:26 [DEBUG] Loading script: boot.js
 14:58:26 [DEBUG] Loading script: config.js
 14:58:26 [DEBUG] Loading script: oraclejdk.js
 14:58:26 [INFO] OracleJDK is detected. MCL will download BouncyCastle automatically.
 14:58:26 [DEBUG] Loading script: repo.js
 14:58:27 [INFO] Fetching Mirai Console Loader Announcement...
 14:58:28 [INFO] Mirai Console Loader Announcement:
 14:58:28 [ERROR] Failed to fetch announcement.
2021-03-28 14:58:30 I/main: Starting mirai-console...
2021-03-28 14:58:30 I/main: Backend: version 1.0.0, built on 2020-11-20 11:45:09.
2021-03-28 14:58:30 I/main: Frontend Terminal: version 1.0.0, provided by Mamoe Technologies
2021-03-28 14:58:30 I/plugin: Successfully loaded plugin MiraiApiHttp
2021-03-28 14:58:31 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-03-28 14:58:31 I/MiraiApiHttp: Starting Mirai HTTP Server in 0.0.0.0:8080
2021-03-28 14:58:31 I/Mirai HTTP API: Http api server is running with authKey: abaabaabaaba
2021-03-28 14:58:31 I/MiraiApiHttp: 心跳模块启用状态: false
2021-03-28 14:58:31 I/MiraiApiHttp: 上报模块启用状态: false
2021-03-28 14:58:31 I/main: 1 plugin(s) enabled.
2021-03-28 14:58:31 I/main: Auto-login xxxxxxxxxx
2021-03-28 14:58:32 I/Bot xxxxxxxxxx: Logging in...
2021-03-28 14:58:32 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.network.WrongPasswordException: Error(title=��ܰ��ʾ, message=��ǰ�汾���ͣ���������QQ� ��°汾��, errorInfo=)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:223)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:201)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)

2021-03-28 14:58:37 I/MiraiApiHttp: 心跳模块已禁用
2021-03-28 14:58:37 I/MiraiApiHttp: 上报模块已禁用
2021-03-28 14:58:37 I/Bot xxxxxxxxxx: Bot cancelled: Job was cancelled
```

ps:
net.mamoe.mirai.network.WrongPasswordException: Error(title=��ܰ��ʾ, message=��ǰ�汾���ͣ���������QQ� ��°汾��, errorInfo=)
这一句本身打印出来就是乱码

#### 复现

和以前一样正常通过mcl启动mirai
.\mcl --disable-update

#### 版本

- mcl:`1.0.3或1.0.5`
- mirai-console:`1.0.0`
- mirai-console-terminal:`1.0.0`
- mirai-core-all:`1.3.3`

**Comment by Him188** [comment]
请更新版本到 2.0 及以上, 可参考 https://github.com/mamoe/mirai/blob/dev/docs/MigrationFrom1x.md

**Comment by RiotGamesU** [comment]
> 请更新版本到 2.0 及以上, 可参考 https://github.com/mamoe/mirai/blob/dev/docs/MigrationFrom1x.md

我用的python sdk, graia:https://github.com/GraiaProject/Application ,所以我想问一下mcl的config.json里mirai-console,mirai-console-terminal和mirai-core-all用什么版本配合起来比较好,谢谢

**Comment by Him188** [comment]
> > 请更新版本到 2.0 及以上, 可参考 https://github.com/mamoe/mirai/blob/dev/docs/MigrationFrom1x.md
> 
> 我用的python sdk, graia:https://github.com/GraiaProject/Application ,所以我想问一下mcl的config.json里mirai-console,mirai-console-terminal和mirai-core-all用什么版本配合起来比较好,谢谢

使用 mirai-core 和 -console 的 2.5.0，配合 mirai-api-http 1.10.0

最近会更新一下这方面文档

**Comment by RiotGamesU** [comment]
> > > 请更新版本到 2.0 及以上, 可参考 https://github.com/mamoe/mirai/blob/dev/docs/MigrationFrom1x.md
> > 
> > 
> > 我用的python sdk, graia:https://github.com/GraiaProject/Application ,所以我想问一下mcl的config.json里mirai-console,mirai-console-terminal和mirai-core-all用什么版本配合起来比较好,谢谢
> 
> 使用 mirai-core 和 -console 的 2.5.0，配合 mirai-api-http 1.10.0
> 
> 最近会更新一下这方面文档

可以了,谢谢

**Comment by Him188** [comment]
更新了文档
