### ISSUE TITLE
NoSuchMethodError: kotlin.jvm.internal.MutablePropertyReference1Impl

### ISSUE THREAD

**Issue by xggz** [mamoe/mirai#1126]
按照文档提示，使用mirai-core-jvm:2.5.0和kotlin-stdlib-jdk8:1.4.31，无法启动机器人：
```
Exception in thread "QQ机器人服务运行线程" java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:234)
	at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:17)
	at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt:37)
	at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt)
	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:115)
	at xxx.framework.RobotServerStarter.start(RobotServerStarter.java:64)
	at xxx.RobotController.lambda$start$0(RobotController.java:58)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
	at io.ktor.client.HttpClientConfig.<clinit>(HttpClientConfig.kt)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41)
	at net.mamoe.mirai.internal.MiraiImpl.<init>(MiraiImpl.kt:121)
	at net.mamoe.mirai.internal.MiraiImpl$INSTANCE.<init>(MiraiImpl.kt:59)
	at net.mamoe.mirai.internal.MiraiImpl$INSTANCE.<init>(MiraiImpl.kt:59)
	at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 12 more
```

使用mirai-core-jvm:2.5.0和kotlin-stdlib:1.4.31可以正常启动机器人，但是运行机器人还是存在以前出现过的错误信息，参考以前的issue：https://github.com/mamoe/mirai/issues/1066#issue-819740562

**Comment by Him188** [comment]
需要 kotlin-stdlib 1.4.30, ktor-client-core 1.5.2

**Comment by Him188** [comment]
这可能是因为你正在使用的其他库覆盖了 mirai 依赖的库. 如果正在使用 Maven, 可以尝试 Gradle.

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/112778438-23bc8f00-9077-11eb-9bcb-e2158cbf38ef.png)

**Comment by xggz** [comment]
如果是其它库覆盖了的话，那我再排查一下

**Comment by Him188** [comment]
For mamoe: 这说明还是需要 #1084 来避免依赖被覆盖

**Comment by xggz** [comment]
maven以下依赖不会报错，且能正常运行：

<dependency>
    <groupId>net.mamoe</groupId>
    <artifactId>mirai-core-jvm</artifactId>
    <version>2.5.1</version>
</dependency>
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib</artifactId>
    <version>1.4.31</version>
</dependency>
<dependency>
    <groupId>io.ktor</groupId>
    <artifactId>ktor-client-core</artifactId>
    <version>1.5.2</version>
</dependency>

**Comment by yuany3721** [comment]
spring boot 2.4.5打包的ktor依赖版本为1.5.1，dependency内加入：
```
<dependency>
    <groupId>io.ktor</groupId>
    <artifactId>ktor-client-core</artifactId>
    <version>1.5.2</version>
</dependency>
```
即可避免此问题。（个人解决方案，仅供参考）
