### ISSUE TITLE
[NETWORK ERROR]: java.lang.IllegalArgumentException: Self-suppression not permitted

### ISSUE THREAD

**Issue by zhzRedstone** [mamoe/mirai#116]
[NETWORK]: Received: MultiPacketBySequence
[NETWORK]: Send: OnlinePush.RespPush
[NETWORK]: Send: Heartbeat.Alive
[NETWORK]: Send: Heartbeat.Alive
[NETWORK]: Send: Heartbeat.Alive
[BOT 3173857429]: Connection dropped by server or lost, retrying login
[NETWORK]: Cannot do fast relogin. Trying slow relogin
[NETWORK]: Send: wtlogin.login
[NETWORK]: Send: StatSvc.register
[NETWORK]: Cannot do fast relogin. Trying slow relogin
[NETWORK]: Send: wtlogin.login
[BOT 3173857429]: An exception was thrown under a coroutine of Bot
[NETWORK ERROR]: java.lang.IllegalArgumentException: Self-suppression not permitted
java.lang.IllegalArgumentException: Self-suppression not permitted
        at java.lang.Throwable.addSuppressed(Throwable.java:1072)
        at net.mamoe.mirai.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:206)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(Builders.common.kt:207)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Caused by: java.util.concurrent.CancellationException: NetworkHandler closed
        at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
        at net.mamoe.mirai.network.BotNetworkHandler.close(BotNetworkHandler.kt:96)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.close(QQAndroidBotNetworkHandler.kt:597)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$startHeartbeatJobOrKill$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:96)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        ... 5 more
Caused by: java.lang.IllegalStateException: timeout when receiving response of Heartbeat.Alive
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:570)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        ... 4 more

**Comment by zhzRedstone** [comment]
不知道是不是我网络有问题。

**Comment by zhzRedstone** [comment]
没有装任何插件。使用的是mirai-console-wrapper-0.0.1-all.jar Perl

**Comment by Him188** [comment]
Fixed in `0.25.0`
