### ISSUE TITLE
`whileSelectMessages`时`quoteReply`报错

### ISSUE THREAD

**Issue by xszqxszq** [mamoe/mirai#1160]
在`whileSelectMessages`的`default`中调用`quoteReply(String)`出现Exception。

```
2021-04-04 09:13:53 E/Net 2262349573: Exception in NetworkHandler
java.lang.ClassCastException: net.mamoe.mirai.event.events.GroupMessageEvent incompatible with net.mamoe.mirai.event.MessageSubscribersBuilder$ListeningFilter
	at tk.xszq.otomadbot.OtomadBotKt$doInitSubscribe$12$2$1$1$invokeSuspend$$inlined$whileSelectMessages$1$lambda$1.invokeSuspend(OtomadBot.kt:575)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 复现

1. 在`subscribeGroupMessages`中使用`whileSelectMessages`；
2. 在`whileSelectMessages`的`default`中使用`quoteReply("任意字符串")`
3. 运行程序后在群聊中触发default情形，得到Exception in NetworkHandler

#### 版本
- mirai-core: `2.5.1` 
- kotlin: `1.4.32`

**Comment by xszqxszq** [comment]
如果使用`reply("任意字符串")`则会出现错误：
```
e: C:\path\to\file\filename.kt: (575, 33): Overload resolution ambiguity: 
public open infix fun String.reply(reply: String): Listener<GroupMessageEvent> defined in net.mamoe.mirai.event.MessageSubscribersBuilder
public open infix fun MessageSubscribersBuilder<GroupMessageEvent, Listener<GroupMessageEvent>, Unit, Unit>.ListeningFilter.reply(toReply: String): Listener<GroupMessageEvent> defined in net.mamoe.mirai.event.MessageSubscribersBuilder
```

**Comment by xszqxszq** [comment]
另外想请教一下`subscribeGroupMessages`里任意@MessageDsl里面，`whileSelectMessages`调用`default{}`时的`this`到底是什么，IDEA显示是`GroupMessageEvent`但调用`this.group`和`this.message`都会报错：
```
Nested class '<ERROR CLASS: group>' accessed via instance reference
Classifier '<ERROR CLASS: group>' does not have a companion object, and thus must be initialized here
```
然后在`default{}`里可以调用我自己定义的`MessageEvent.customFunction1()`但却无法调用自己定义的`GroupMessageEvent.customFunction2()`，提示Unresolved reference，感觉有点麻烦

**Comment by Him188** [comment]
@xszqxszq 这是 Kotlin 的 bug，多半是

**Comment by Him188** [comment]
> 如果使用`reply("任意字符串")`则会出现错误：
> 
> ```
> e: C:\path\to\file\filename.kt: (575, 33): Overload resolution ambiguity: 
> public open infix fun String.reply(reply: String): Listener<GroupMessageEvent> defined in net.mamoe.mirai.event.MessageSubscribersBuilder
> public open infix fun MessageSubscribersBuilder<GroupMessageEvent, Listener<GroupMessageEvent>, Unit, Unit>.ListeningFilter.reply(toReply: String): Listener<GroupMessageEvent> defined in net.mamoe.mirai.event.MessageSubscribersBuilder
> ```

请提供相关使用时的代码

**Comment by xszqxszq** [comment]
> > 如果使用`reply("任意字符串")`则会出现错误：
> > ```
> > e: C:\path\to\file\filename.kt: (575, 33): Overload resolution ambiguity: 
> > public open infix fun String.reply(reply: String): Listener<GroupMessageEvent> defined in net.mamoe.mirai.event.MessageSubscribersBuilder
> > public open infix fun MessageSubscribersBuilder<GroupMessageEvent, Listener<GroupMessageEvent>, Unit, Unit>.ListeningFilter.reply(toReply: String): Listener<GroupMessageEvent> defined in net.mamoe.mirai.event.MessageSubscribersBuilder
> > ```
> 
> 请提供相关使用时的代码

```
    GlobalEventChannel.subscribeGroupMessages {
        "test" {
            whileSelectMessages {
                default {
                    reply("test1")
                    true
                }
                "test0" {
                    reply("test2")
                    false
                }
                timeout(10000) { false }
            }
        }
    }
```
这两个`reply`都被IDEA报了上面的错误，而`quoteReply`不报错但在运行中抛出上面的Exception

**Comment by Him188** [comment]
> > > 如果使用`reply("任意字符串")`则会出现错误：
> > > ```
> > > e: C:\path\to\file\filename.kt: (575, 33): Overload resolution ambiguity: 
> > > public open infix fun String.reply(reply: String): Listener<GroupMessageEvent> defined in net.mamoe.mirai.event.MessageSubscribersBuilder
> > > public open infix fun MessageSubscribersBuilder<GroupMessageEvent, Listener<GroupMessageEvent>, Unit, Unit>.ListeningFilter.reply(toReply: String): Listener<GroupMessageEvent> defined in net.mamoe.mirai.event.MessageSubscribersBuilder
> > > ```
> > 
> > 
> > 请提供相关使用时的代码
> 
> ```
>     GlobalEventChannel.subscribeGroupMessages {
>         "test" {
>             whileSelectMessages {
>                 default {
>                     reply("test1")
>                     true
>                 }
>                 "test0" {
>                     reply("test2")
>                     false
>                 }
>                 timeout(10000) { false }
>             }
>         }
>     }
> ```
> 
> 这两个`reply`都被IDEA报了上面的错误，而`quoteReply`不报错但在运行中抛出上面的Exception

现在 `GroupMessageEvent` 没有 `reply` 扩展了, `reply` 调用的实际上是 `MessageSelectBuilder.reply`

**Comment by Him188** [comment]
请提供使用 `quoteReply` 的示例代码

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/113499777-376e6680-954b-11eb-8ec0-7aadd3d27924.png)

经测试是可以调用的, 确保使用 Kotlin IDE 插件 1.4.32

**Comment by xszqxszq** [comment]
> 请提供使用 `quoteReply` 的示例代码

```
    val groupMessages=GlobalEventChannel.filter { it is GroupEvent }
        .exceptionHandler { exception ->
            exception.printStackTrace()
        }
    groupMessages.subscribeGroupMessages {
        "test" {
            whileSelectMessages {
                default {
                    quoteReply("not 1")
                    true
                }
                "1" {
                    quoteReply("is 1")
                    false
                }
                timeout(10000) {
                    quotedReply("1")
                    false
                }
            }
        }
    }
```

```
2021-04-04 15:16:03 E/Net 2262349573: Exception in NetworkHandler
java.lang.ClassCastException: net.mamoe.mirai.event.events.GroupMessageEvent incompatible with net.mamoe.mirai.event.MessageSubscribersBuilder$ListeningFilter
	at tk.xszq.otomadbot.OtomadBotKt$doInitSubscribe$4$14$invokeSuspend$$inlined$whileSelectMessages$1$lambda$1.invokeSuspend(OtomadBot.kt:213)
	at tk.xszq.otomadbot.OtomadBotKt$doInitSubscribe$4$14$invokeSuspend$$inlined$whileSelectMessages$1$lambda$1.invoke(OtomadBot.kt)
	at tk.xszq.otomadbot.OtomadBotKt$doInitSubscribe$4$14$invokeSuspend$$inlined$whileSelectMessages$1$4.invokeSuspend(select.kt:693)
	at tk.xszq.otomadbot.OtomadBotKt$doInitSubscribe$4$14$invokeSuspend$$inlined$whileSelectMessages$1$4.invoke(select.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:431)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:49)
	at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:49)
	at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$3$invokeSuspend$$inlined$forEach0$lambda$1.invokeSuspend(InternalEventListeners.kt:148)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by xszqxszq** [comment]
> ![image](https://user-images.githubusercontent.com/12100985/113499777-376e6680-954b-11eb-8ec0-7aadd3d27924.png)
> 
> 经测试是可以调用的, 确保使用 Kotlin IDE 插件 1.4.32

这个可能确实是之前IDEA的bug，现在没问题了，但default里this作为GroupMessageEvent（IDEA显示的）依然无法访问group、message等成员，错误信息在上面第二条回复那里

**Comment by Him188** [comment]
`quoteReply` 一样, 在 mirai 2.0 就被删除了. `quoteReply` 调用的实际上是 `MessageSelectBuilder.quoteReply`

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/113501780-76f07f00-955a-11eb-8340-b01de8ccd062.png)

**Comment by xszqxszq** [comment]
> `quoteReply` 一样, 在 mirai 2.0 就被删除了. `quoteReply` 调用的实际上是 `MessageSelectBuilder.quoteReply`

我是照着[文档](https://github.com/mamoe/mirai/blob/dev/docs/Events.md#%E5%BE%AA%E7%8E%AF%E6%9D%A1%E4%BB%B6%E9%80%89%E6%8B%A9whileselectmessages)写的，那文档是不是要更新一下了……

**Comment by xszqxszq** [comment]
> `quoteReply` 一样, 在 mirai 2.0 就被删除了. `quoteReply` 调用的实际上是 `MessageSelectBuilder.quoteReply`

那最后还剩一个问题，`default{}`的this无法调用`this.group`和`this.message`是bug吗，如果不是那`whileSelectMessages`如何获取该条消息事件GroupMessageEvent的group和message呢

**Comment by xszqxszq** [comment]
> > `quoteReply` 一样, 在 mirai 2.0 就被删除了. `quoteReply` 调用的实际上是 `MessageSelectBuilder.quoteReply`
> 
> 我是照着[文档](https://github.com/mamoe/mirai/blob/dev/docs/Events.md#%E5%BE%AA%E7%8E%AF%E6%9D%A1%E4%BB%B6%E9%80%89%E6%8B%A9whileselectmessages)写的，那文档是不是要更新一下了……

上面的selectMessages也有quoteReply

**Comment by Him188** [comment]
> 那最后还剩一个问题，`default{}`的this无法调用`this.group`和`this.message`是bug吗，如果不是那`whileSelectMessages`如何获取该条消息事件GroupMessageEvent的group和message呢

![image](https://user-images.githubusercontent.com/12100985/113503259-452fe600-9563-11eb-9eb2-2e7a44b078fd.png)

似乎可以?

**Comment by xszqxszq** [comment]
> > 那最后还剩一个问题，`default{}`的this无法调用`this.group`和`this.message`是bug吗，如果不是那`whileSelectMessages`如何获取该条消息事件GroupMessageEvent的group和message呢
> 
> ![image](https://user-images.githubusercontent.com/12100985/113503259-452fe600-9563-11eb-9eb2-2e7a44b078fd.png)
> 
> 似乎可以?

测试发现这样获取到的message和group是`subscribeGroupMessages`的@MessageDsl的（比如在always里调用的那么就是this@always），不是default对应的GroupMessageEvent的。
如果使用`whileSelectMessages(filterContext=false)`的话获取不到this.subject或者this.group会无法判断消息是哪里来的

**Comment by xszqxszq** [comment]
> > 那最后还剩一个问题，`default{}`的this无法调用`this.group`和`this.message`是bug吗，如果不是那`whileSelectMessages`如何获取该条消息事件GroupMessageEvent的group和message呢
> 
> ![image](https://user-images.githubusercontent.com/12100985/113503259-452fe600-9563-11eb-9eb2-2e7a44b078fd.png)
> 
> 似乎可以?

试一下this.subject this.group this.message

**Comment by xszqxszq** [comment]
> > > 那最后还剩一个问题，`default{}`的this无法调用`this.group`和`this.message`是bug吗，如果不是那`whileSelectMessages`如何获取该条消息事件GroupMessageEvent的group和message呢
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/12100985/113503259-452fe600-9563-11eb-9eb2-2e7a44b078fd.png)
> > 似乎可以?
> 
> 测试发现这样获取到的message和group是`subscribeGroupMessages`的@MessageDsl的（比如在always里调用的那么就是this@always），不是default对应的GroupMessageEvent的。
> 如果使用`whileSelectMessages(filterContext=false)`的话获取不到this.subject或者this.group会无法判断消息是哪里来的

怪事，如果用`this as GroupMessageEvent`就好了，可能真是kotlin的bug……
