### ISSUE TITLE
使用 Ktor 时必发 NoSuchMethodError

### ISSUE THREAD

**Issue by StarWishsama** [mamoe/mirai#1165]
在项目中使用 Ktor 时必发 NoSuchMethodError

```
21/4/05 21:45:42 ERROR/E(i.g.s.c.CustomLogRedirecter#error0:79) CometNet -> MiraiNet (1773854903) Exception in NetworkHandler

java.lang.NoSuchMethodError: 'java.lang.Object kotlinx.coroutines.DelayKt.delay-p9JZ4hM(double, kotlin.coroutines.Continuation)'
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$8$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:228)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


21/4/05 21:45:42 ERROR/E(i.g.s.c.CustomLogRedirecter#error0:79) CometNet -> MiraiNet (1773854903) Exception in NetworkHandler

java.lang.NoSuchMethodError: 'java.lang.Object kotlinx.coroutines.DelayKt.delay-p9JZ4hM(double, kotlin.coroutines.Continuation)'
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$8$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:213)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 复现

1. 在项目 Gradle 中 compile Ktor 1.5.3
2. 运行 mirai-core

#### 版本
- mirai-core: `2.6-M2`

**Comment by Him188** [comment]
使用 Kotlin 1.4.30 编译器(Gradle插件)?

**Comment by AdoptOSS** [comment]
这是Kotlin v1.4.30对Inline Classes的Breaking Change导致的
Mirai默认引用Kotlinx Coroutines v1.4.2，使用Ktor后由于Ktor引用v1.4.3，Gradle在处理依赖关系时将其提升到v1.4.3
而Mirai无法在v1.4.3的Kotlinx Coroutines下正确调用delay函数
另见Kotlin官方讨论 Kotlin/kotlinx.coroutines#2565

此问题与 #1066 类似， mamoe/mirai@cedb239fc32357dafdf7232eda1ff2666d928aae 理应修复，但不知为何被Revert了（ mamoe/mirai@2b6eddd0d7ec9501da33c1f9819a7c8cd514af36）

**Comment by AdoptOSS** [comment]
另外，如果Mirai在编译时使用Kotlinx Coroutines v1.4.3，则该问题也将得到解决
https://github.com/mamoe/mirai/blob/b227f719a27344caa8e2c669ceb558c76f96baec/buildSrc/src/main/kotlin/Versions.kt#L25

**Comment by Him188** [comment]
> 这是Kotlin v1.4.30对Inline Classes的Breaking Change导致的
> Mirai默认引用Kotlinx Coroutines v1.4.2，使用Ktor后由于Ktor引用v1.4.3，Gradle在处理依赖关系时将其提升到v1.4.3
> 而Mirai无法在v1.4.3的Kotlinx Coroutines下正确调用delay函数
> 另见Kotlin官方讨论 [Kotlin/kotlinx.coroutines#2565](https://github.com/Kotlin/kotlinx.coroutines/issues/2565)
> 
> 此问题与 #1066 类似， [cedb239](https://github.com/mamoe/mirai/commit/cedb239fc32357dafdf7232eda1ff2666d928aae) 理应修复，但不知为何被Revert了（ [2b6eddd](https://github.com/mamoe/mirai/commit/2b6eddd0d7ec9501da33c1f9819a7c8cd514af36)）

这个是因为 `toLongMilliseconds()` 仍然会有 BC, 所以这个修复没有必要. 后来我在另一个 commit 去除了 `Duration` 的使用

其实我也不太记得我有没有推这个去除了...

**Comment by Him188** [comment]
> 另外，如果Mirai在编译时使用Kotlinx Coroutines v1.4.3，则该问题也将得到解决
> https://github.com/mamoe/mirai/blob/b227f719a27344caa8e2c669ceb558c76f96baec/buildSrc/src/main/kotlin/Versions.kt#L25

一个最好的解决办法是把所有依赖都relocate 加上 `net.mamoe.mirai.internal` 的包名, 这样就不会被覆盖了 #1084

**Comment by AdoptOSS** [comment]
> 一个最好的解决办法是把所有依赖都relocate 加上 `net.mamoe.mirai.internal` 的包名, 这样就不会被覆盖了 #1084

但这可能会使用户最终打包的文件大很多（ktor什么的带了两份）

**Comment by AdoptOSS** [comment]
> * 在项目 Gradle 中 compile Ktor 1.5.3

@StarWishsama 
可以先考虑降级到 Ktor v1.5.2

**Comment by Him188** [comment]
> > 一个最好的解决办法是把所有依赖都relocate 加上 `net.mamoe.mirai.internal` 的包名, 这样就不会被覆盖了 #1084
> 
> 但这可能会使用户最终打包的文件大很多（ktor什么的带了两份）

提供两个模块就可以了, 一个是原版, 一个是安全版. 在体积不太重要的时候可以使用安全版这样不需要考虑依赖冲突问题

**Comment by StarWishsama** [comment]
> 使用 Kotlin 1.4.30 编译器(Gradle插件)?

Kotlin 1.4.32

**Comment by xszqxszq** [comment]
> > * 在项目 Gradle 中 compile Ktor 1.5.3
> 
> @StarWishsama
> 可以先考虑降级到 Ktor v1.5.2

Ktor 1.5.2也有此问题，降级还是解决不了
