### ISSUE TITLE
解析 NewContact.SystemMsgNewGroup 时遇到了意料之中的问题，提交日志

### ISSUE THREAD

**Issue by AdorableParker** [mamoe/mirai#1171]
**经查证 Bot 并未被踢出群**
日志内容：
```
2021-04-06 16:52:29 E/Bot.2951899724: java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=6 时遇到了意料之中的问题. 请完整
复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#679314397 {
            actionUin=0x0000000092219BA3(2451676067)
            actionUinNick=艾莉丝（求大建毕业）
            actionUinQqNick=唐云
            actions=[]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x0000000032C9ADB7(852078007)
            groupExtFlag=0x40A10440(1084294208)
            groupFlagext3=0x00008000(32768)
            groupInfo=GroupInfo#109039304 {
                    appPrivilegeFlag=0x140980D0(336167120)
                    msgOtherAdminDone=其他管理员
            }
            groupMsgType=0x00000006(6)
            groupName=🇨🇳爱丽丝航线-自由鸢尾
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%action_uin%
            msgDescribe=已将 %req_uin% 移出群
            msgTitle=退群消息
            reqUinAge=0x00000014(20)
            reqUinFaceid=0x0000B502(46338)
            reqUinGender=0x00000001(1)
            reqUinNick=\　⃢　—　⃢　/夜魔
            subType=0x00000005(5)
    }
java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=6 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#679314397 {
            actionUin=0x0000000092219BA3(2451676067)
            actionUinNick=艾莉丝（求大建毕业）
            actionUinQqNick=唐云
            actions=[]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x0000000032C9ADB7(852078007)
            groupExtFlag=0x40A10440(1084294208)
            groupFlagext3=0x00008000(32768)
            groupInfo=GroupInfo#109039304 {
                    appPrivilegeFlag=0x140980D0(336167120)
                    msgOtherAdminDone=其他管理员
            }
            groupMsgType=0x00000006(6)
            groupName=🇨🇳爱丽丝航线-自由鸢尾
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%action_uin%
            msgDescribe=已将 %req_uin% 移出群
            msgTitle=退群消息
            reqUinAge=0x00000014(20)
            reqUinFaceid=0x0000B502(46338)
            reqUinGender=0x00000001(1)
            reqUinNick=\　⃢　—　⃢　/夜魔
            subType=0x00000005(5)
    }
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:23)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup$decode$2.invoke(NewContact.kt:233)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:265)
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:525)
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:247)
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:578)
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:573)
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:555)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by sandtechnology** [comment]
该类型我处理过但是没PR 直接添加子类型后忽略即可

**Comment by Him188** [comment]
@sandtechnology 确认直接忽略? 也可以处理一下这个消息: 
```kotlin
handleLeave(data.reqUin, 3, actionUin, group.id)
```
如果成员已被踢出则不会发生任何事情, 但不确定 `data.reqUin` 是否正确 (issue 日志没有记录)

该消息也有可能是在同步历史消息, 因此处理它就有可能导致错误 (群成员被踢出后又加入, 随后处理这个事件群成员又被从 group 删除)

**Comment by sandtechnology** [comment]
这是历史的群系统消息，实际上可以直接进行忽略，其实只是因为缺失了忽略的处理而已
