### ISSUE TITLE
MessageSource在连续序列化几次后出错

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#1176]
MessageSource在连续序列化几次后出错
大概每次都在第四次

日志1:
```
2021-04-08 08:12:09 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@2429ea24)
2021-04-08 08:12:09 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-08 08:12:09 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-08 08:12:09 V/Bot 6********: ea(1) -> c
2021-04-08 08:12:09 I/Bot 6********: Send message for(1) is ea
2021-04-08 08:12:09 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-08 08:12:09 V/Net 6********: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-04-08 08:12:09 V/Bot 6********: Friend(1) <- ea
2021-04-08 08:12:09 I/Bot 6********: Source:"{"kind":"FRIEND","botId":6********,"ids":[22912],"internalIds":[1297219536],"time":1617840729,"fromId":6********,"targetId":1,"originalMessage":[{"type":"PlainText","content":"ea"}]}"
2021-04-08 08:12:12 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@28e70d2f)
2021-04-08 08:12:12 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-08 08:12:12 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-08 08:12:12 V/Bot 6********: ea(1) -> c
2021-04-08 08:12:12 I/Bot 6********: Send message for(1) is ea
2021-04-08 08:12:12 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-08 08:12:13 V/Net 6********: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-04-08 08:12:13 V/Bot 6********: Friend(1) <- ea
2021-04-08 08:12:13 I/Bot 6********: Source:"{"kind":"FRIEND","botId":6********,"ids":[22913],"internalIds":[726078477],"time":1617840732,"fromId":6********,"targetId":1********,"originalMessage":[{"type":"PlainText","content":"ea"}]}"
2021-04-08 08:12:15 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@2cedc5a1)
2021-04-08 08:12:15 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-08 08:12:15 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-08 08:12:15 V/Bot 6********: ea(1********) -> c
2021-04-08 08:12:15 I/Bot 6********: Send message for(1********) is ea
2021-04-08 08:12:15 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-08 08:12:20 V/Bot 6********: Friend(1********) <- ea
2021-04-08 08:12:20 W/Bot 6********: 异常:kotlin返回空字符串
2021-04-08 08:12:20 E/Bot 6********: MiraiCP内部无法预料的错误:JSON reader error,位置:C-MessageSource
```
日志2:
```
2021-04-08 08:27:54 D/Net 6********: Received unknown commandName: ConfigPushSvc.PushDomain
2021-04-08 08:27:54 V/Net 6********: Recv: ConfigPushSvc.PushReq.PushReqResponse.ConfigPush
2021-04-08 08:27:54 V/Net 6********: Saving bdh session to cache
2021-04-08 08:27:54 V/Net 6********: Send: ConfigPushSvc.PushResp
2021-04-08 08:27:54 I/Net 6********: ConfigPushSvc.PushReq: Config updated.
2021-04-08 08:27:59 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@1c311a9f)
2021-04-08 08:27:59 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-08 08:27:59 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-08 08:27:59 V/Bot 6********: ea(1********) -> a
2021-04-08 08:27:59 I/Bot 6********: Send message for(1********) is a
2021-04-08 08:27:59 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-08 08:27:59 V/Net 6********: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-04-08 08:27:59 V/Bot 6********: Friend(1********) <- a
2021-04-08 08:27:59 I/Bot 6********: Source:"{"kind":"FRIEND","botId":6********,"ids":[22912],"internalIds":[1654609308],"time":1617841679,"fromId":6********,"targetId":1********,"originalMessage":[{"type":"PlainText","content":"a"}]}"
2021-04-08 08:27:59 I/Bot 6********: C-Source:"{"kind":"FRIEND","botId":6********,"ids":[22912],"internalIds":[1654609308],"time":1617841679,"fromId":6********,"targetId":1********,"originalMessage":[{"type":"PlainText","content":"a"}]}"
2021-04-08 08:28:01 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@241a51b3)
2021-04-08 08:28:01 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-08 08:28:01 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-08 08:28:01 V/Bot 6********: ea(1********) -> c
2021-04-08 08:28:01 I/Bot 6********: Send message for(1********) is c
2021-04-08 08:28:01 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-08 08:28:02 V/Net 6********: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-04-08 08:28:02 V/Bot 6********: Friend(1********) <- c
2021-04-08 08:28:02 I/Bot 6********: Source:"{"kind":"FRIEND","botId":6********,"ids":[22913],"internalIds":[2010856371],"time":1617841681,"fromId":6********,"targetId":1********,"originalMessage":[{"type":"PlainText","content":"c"}]}"
2021-04-08 08:28:02 I/Bot 6********: C-Source:"{"kind":"FRIEND","botId":6********,"ids":[22913],"internalIds":[2010856371],"time":1617841681,"fromId":6********,"targetId":1********,"originalMessage":[{"type":"PlainText","content":"c"}]}"
2021-04-08 08:28:02 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@667010be)
2021-04-08 08:28:03 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-08 08:28:03 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-08 08:28:03 V/Bot 6********: ea(1********) -> d
2021-04-08 08:28:03 I/Bot 6********: Send message for(1********) is d
2021-04-08 08:28:03 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-08 08:28:03 V/Net 6********: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-04-08 08:28:03 V/Bot 6********: Friend(1********) <- d
2021-04-08 08:28:03 I/Bot 6********: Source:"{"kind":"FRIEND","botId":6********,"ids":[22914],"internalIds":[539854946],"time":1617841683,"fromId":6********,"targetId":1********,"originalMessage":[{"type":"PlainText","content":"d"}]}"
2021-04-08 08:28:03 I/Bot 6********: C-Source:"{"kind":"FRIEND","botId":6********,"ids":[22914],"internalIds":[539854946],"time":1617841683,"fromId":6********,"targetId":1********,"originalMessage":[{"type":"PlainText","content":"d"}]}"
2021-04-08 08:28:04 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@63fa76f1)
2021-04-08 08:28:04 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-08 08:28:04 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-08 08:28:04 V/Bot 6********: ea(1********) -> g
2021-04-08 08:28:04 I/Bot 6********: Send message for(1********) is g
2021-04-08 08:28:04 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-08 08:28:09 V/Bot 6********: Friend(1********) <- g
2021-04-08 08:28:09 W/Bot 6********: 异常:kotlin返回空字符串
2021-04-08 08:28:09 I/Bot 6********: C-Source:""
```
日志3:
```
2021-04-08 08:24:00 V/Net 6********: Recv: ConfigPushSvc.PushReq.PushReqResponse.ConfigPush
2021-04-08 08:24:00 D/Net 6********: Received unknown commandName: ConfigPushSvc.PushDomain
2021-04-08 08:24:00 V/Net 6********: Saving bdh session to cache
2021-04-08 08:24:00 V/Net 6********: Saving server list to cache
2021-04-08 08:24:00 V/Net 6********: Send: ConfigPushSvc.PushResp
2021-04-08 08:24:00 I/Net 6********: ConfigPushSvc.PushReq: Server updated.
2021-04-08 08:24:00 V/Net 6********: Saving bdh session to cache
2021-04-08 08:24:00 V/Net 6********: Send: ConfigPushSvc.PushResp
2021-04-08 08:24:03 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@5612215e)
2021-04-08 08:24:03 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-08 08:24:03 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-08 08:24:03 V/Bot 6********: ea(1********) -> [mirai:face:187]
2021-04-08 08:24:03 I/Bot 6********: Send message for(1********) is [mirai:face:187]
2021-04-08 08:24:03 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-08 08:24:04 V/Net 6********: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-04-08 08:24:04 V/Bot 6********: Friend(1********) <- [mirai:face:187]
2021-04-08 08:24:04 I/Bot 6********: Source:"{"kind":"FRIEND","botId":6********,"ids":[22916],"internalIds":[441756862],"time":1617841443,"fromId":6********,"targetId":1********,"originalMessage":[{"type":"PlainText","content":"[mirai:face:187]"}]}"
2021-04-08 08:24:06 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@2cc69c44)
2021-04-08 08:24:06 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-08 08:24:06 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-08 08:24:06 V/Bot 6********: ea(1********) -> [mirai:image:{2E6B1728-62E3-486E-1DD0-EE260D80B975}.jpg]
2021-04-08 08:24:06 I/Bot 6********: Send message for(1********) is [mirai:image:{2E6B1728-62E3-486E-1DD0-EE260D80B975}.jpg]
2021-04-08 08:24:06 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-08 08:24:07 V/Net 6********: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-04-08 08:24:07 V/Bot 6********: Friend(1********) <- [mirai:image:{2E6B1728-62E3-486E-1DD0-EE260D80B975}.jpg]
2021-04-08 08:24:07 I/Bot 6********: Source:"{"kind":"FRIEND","botId":6********,"ids":[22917],"internalIds":[1246339598],"time":1617841446,"fromId":6********,"targetId":1********,"originalMessage":[{"type":"PlainText","content":"[mirai:image:{2E6B1728-62E3-486E-1DD0-EE260D80B975}.jpg]"}]}"
2021-04-08 08:24:09 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@3c20ac60)
2021-04-08 08:24:09 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-08 08:24:09 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-08 08:24:09 V/Bot 6********: ea(1********) -> [mirai:image:{45809C88-AFC6-580D-234B-9D519319D64F}.jpg]
2021-04-08 08:24:09 I/Bot 6********: Send message for(1********) is [mirai:image:{45809C88-AFC6-580D-234B-9D519319D64F}.jpg]
2021-04-08 08:24:09 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-08 08:24:10 V/Net 6********: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-04-08 08:24:10 V/Bot 6********: Friend(1********) <- [mirai:image:{45809C88-AFC6-580D-234B-9D519319D64F}.jpg]
2021-04-08 08:24:10 I/Bot 6********: Source:"{"kind":"FRIEND","botId":6********,"ids":[22918],"internalIds":[125759945],"time":1617841449,"fromId":6********,"targetId":1********,"originalMessage":[{"type":"PlainText","content":"[mirai:image:{45809C88-AFC6-580D-234B-9D519319D64F}.jpg]"}]}"
2021-04-08 08:24:12 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@232c9277)
2021-04-08 08:24:12 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-08 08:24:12 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-08 08:24:12 V/Bot 6********: ea(1********) -> [mirai:face:178]
2021-04-08 08:24:12 I/Bot 6********: Send message for(1********) is [mirai:face:178]
2021-04-08 08:24:12 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-08 08:24:17 V/Bot 6********: Friend(1********) <- [mirai:face:178]
2021-04-08 08:24:17 W/Bot 6********: 异常:kotlin返回空字符串
```
代码:
```kotlin
suspend fun SendM(message: String, id: Long) :String{
        //反向调用
        logger.info("Send message for($id) is $message")
        val f = AIbot.getFriend(id) ?: let {
            logger.error("发送消息找不到好友，位置:K-Send()，id:$id")
            return "E1"
        }
        val a = json.encodeToString(MessageSource.Serializer, f.sendMessage(message).source)
        logger.info("Source:\"$a\"")
        return a
    }
```

#### 复现

日志1是在私聊中输出对方的nick，日志2和3是复读

#### 版本
- mirai-core: `2.5.0`

**Comment by Him188** [comment]
> 异常:kotlin返回空字符串

这是在哪打印的

**Comment by Him188** [comment]
看了日志，发生问题的时候都还没有收到 `PbSendMsg` 的返回，请提供完整日志和完整相关代码

**Comment by Nambers** [comment]
> 看了日志，发生问题的时候都还没有收到 `PbSendMsg` 的返回，请提供完整日志和完整相关代码

稍等，我晚点给个最小纯kt复现代码因为我上面这个是在C++和kt混合调用出的错

**Comment by Nambers** [comment]
> 看了日志，发生问题的时候都还没有收到 `PbSendMsg` 的返回，请提供完整日志和完整相关代码

用纯kt试了下没问题，不过用miraicp还是有问题在这一步，我加断点调试好像是返回null
![image](https://user-images.githubusercontent.com/35139537/113966284-634a5e80-9861-11eb-803d-e74d9890e15b.png)

**Comment by Him188** [comment]
> > 看了日志，发生问题的时候都还没有收到 `PbSendMsg` 的返回，请提供完整日志和完整相关代码
> 
> 用纯kt试了下没问题，不过用miraicp还是有问题在这一步，我加断点调试好像是返回null
> ![image](https://user-images.githubusercontent.com/35139537/113966284-634a5e80-9861-11eb-803d-e74d9890e15b.png)

有没有简单的复现方法? 我进去项目里看看

**Comment by Him188** [comment]
你是不是用native调用这个SendM? `suspend fun` 会在编译期处理并加上一个参数

可以参考 https://github.com/him188/kotlin-jvm-blocking-bridge 获知处理方案

**Comment by Nambers** [comment]
> 你是不是用native调用这个SendM? `suspend fun` 会在编译期处理并加上一个参数
> 
> 可以参考 https://github.com/him188/kotlin-jvm-blocking-bridge 获知处理方案

native先调用CPP_lib.kt里的`SendPrivateMSGM()`然后用`runblock{}`调用`SendM()`然后理论上应该可以避免你上面的问题，native调用的函数是static而且没suspend的，我去看看，然后复现文件如果要的话我待会发你邮箱

**Comment by Nambers** [comment]
@Him188 你有什么看法吗(突然想起来还有这个问题没解决)，是不是CPP多线程导致kt的协程爆了？我这报错好像是协程超时
```
2021-04-28 22:46:40 V/Net 6********: Recv: RequestPushNotify(uin=6********, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=166, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@75e36447)
2021-04-28 22:46:40 V/Net 6********: Send: MessageSvc.PbGetMsg
2021-04-28 22:46:40 V/Net 6********: Send: MessageSvc.PbDeleteMsg
2021-04-28 22:46:40 V/Bot 6********: ea(1*********) -> y
2021-04-28 22:46:40 I/Bot 6********: Send message for(1*********) is hi
2021-04-28 22:46:40 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-28 22:46:45 V/Bot 6********: Friend(1*********) <- hi
2021-04-28 22:46:45 W/Bot 6********: 异常:kotlin返回空字符串
2021-04-28 22:46:45 I/Bot 6********: C-Source:""
2021-04-28 22:46:45 E/Bot 6********: MiraiCP内部无法预料的错误:JSON reader error,位置:C-MessageSource
Exception in thread "Thread-17" kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
        at java.base/java.lang.Thread.run(Thread.java:832)
2021-04-28 22:46:45 I/Bot 6********: Send message for(1*********) is y
2021-04-28 22:46:45 V/Net 6********: Send: MessageSvc.PbSendMsg
2021-04-28 22:46:50 V/Bot 6********: Friend(1*********) <- y
2021-04-28 22:46:50 W/Bot 6********: 异常:kotlin返回空字符串
2021-04-28 22:46:50 I/Bot 6********: C-Source:""
2021-04-28 22:46:50 E/Bot 6********: MiraiCP内部无法预料的错误:JSON reader error,位置:C-MessageSource
```

**Comment by Him188** [comment]
@Nambers 没

**Comment by Nambers** [comment]
草 终于解决了
果然是CPP的问题
