### ISSUE TITLE
帐号掉线重连后, 几率性出现可以发送消息但不能接收消息, 帐号状态是离线且无法检测

### ISSUE THREAD

**Issue by kuresaru** [mamoe/mirai#1190]
在服务器上每过8-17分钟  看日志 帐号肯定会发生掉线情况 (现在怀疑掉线是网络问题,非程序问题)
掉线后 看日志在重新登录 有时候登录成功 有时候登录失败  失败了过一会也会出现重试登录成功的日志
在**掉线重新登录**后 **有几率**出现**帐号无法接收消息** 但是**可以发送消息**的情况, QQ中显示**帐号是离线状态**
**isBotAlive()返回true**

#### 最后一次成功接收消息时附近的掉线重连日志
```
2021-04-05 02:34:26.413 [DefaultDispatcher-worker-2] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: Heartbeat.Alive
2021-04-05 02:34:26.440 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: Heartbeat.Alive.Response
2021-04-05 02:37:40.988 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Channel closed.
2021-04-05 02:37:40.988 [DefaultDispatcher-worker-1] INFO  [top.scraft.robitgw.MiraiLogger] - Mirai/Connection lost, retrying login (java.io.EOFException
: Premature end of stream: was read 0 bytes of 1)
2021-04-05 02:37:40.989 [DefaultDispatcher-worker-1] INFO  [top.scraft.robitgw.MiraiLogger] - Mirai/Logging in...
2021-04-05 02:37:40.989 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Loading BdhSession from cache file
2021-04-05 02:37:41.035 [DefaultDispatcher-worker-1] INFO  [top.scraft.robitgw.MiraiLogger] - Network/Connected to server 42.81.170.17:80
2021-04-05 02:37:41.035 [DefaultDispatcher-worker-2] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: wtlogin.login
2021-04-05 02:37:41.285 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: WtLogin.Login.LoginPacketResponse.DeviceLockL
ogin
2021-04-05 02:37:41.285 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: wtlogin.login
2021-04-05 02:37:41.417 [DefaultDispatcher-worker-2] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: LoginPacketResponse.Success
2021-04-05 02:37:41.417 [DefaultDispatcher-worker-2] INFO  [top.scraft.robitgw.MiraiLogger] - Network/Login successful
```

#### 问题发生后就只剩下了心跳日志  偶尔有失败提示  
```
2021-04-06 03:34:38.547 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: Heartbeat.Alive
2021-04-06 03:34:38.574 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: Heartbeat.Alive.Response
2021-04-06 03:39:08.595 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: Heartbeat.Alive
2021-04-06 03:39:08.618 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: Heartbeat.Alive.Response
2021-04-06 03:41:29.586 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: wtlogin.exchange_emp
2021-04-06 03:41:29.624 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: Error(title=登录失败, message=服务连接中，请
稍后再试。(0x9), errorInfo=)
2021-04-06 03:41:29.625 [DefaultDispatcher-worker-3] INFO  [top.scraft.robitgw.MiraiLogger] - Network/Scheduled key refresh in about 6 hours.
2021-04-06 03:43:38.638 [DefaultDispatcher-worker-2] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: Heartbeat.Alive
2021-04-06 03:43:38.659 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: Heartbeat.Alive.Response
2021-04-06 03:48:08.660 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: Heartbeat.Alive
2021-04-06 03:48:08.684 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: Heartbeat.Alive.Response
```

### **但问题发生后还是能正常发送群图片消息**
```
2021-04-06 12:57:11.986 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: Heartbeat.Alive
2021-04-06 12:57:12.011 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: Heartbeat.Alive.Response
2021-04-06 13:00:03.733 [DefaultDispatcher-worker-2] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: ImgStore.GroupPicUp
2021-04-06 13:00:03.853 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: RequireUpload(fileId=2536840798, uKey=[67, !!此处省略key!!, 74])
2021-04-06 13:00:03.872 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/[Highway] Uploading group image to 180.109.171.53:80, size=592.5 KiB
2021-04-06 13:00:06.095 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/[Highway] Uploading group image: succeed at 267 KiB/s
2021-04-06 13:00:06.159 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: MessageSvc.PbSendMsg
2021-04-06 13:00:06.272 [DefaultDispatcher-worker-4] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-04-06 13:00:09.168 [DefaultDispatcher-worker-4] TRACE [top.scraft.robitgw.MiraiLogger] - Mirai/Group(367341477) <- [mirai:image:{65AFA070-46CD-F771-34FD-D333CACFA9EC}.png]
2021-04-06 13:01:42.012 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: Heartbeat.Alive
2021-04-06 13:01:42.039 [DefaultDispatcher-worker-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: Heartbeat.Alive.Response

```

#### 复现

随机性  在我的环境里大约每天掉线130次  但是发生这个问题的频率大约是20天一次

#### 版本
- mirai-core: `2.4.2`
- 其它依赖包
```
dependencies {
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-data-redis-reactive")
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
	implementation("org.springframework.cloud:spring-cloud-starter-oauth2")
	implementation("mysql:mysql-connector-java")
	implementation("com.huaban:jieba-analysis:1.0.3-SNAPSHOT") // https://github.com/GlassyWing/better-jieba
	implementation("net.mamoe:mirai-core-jvm:2.4.2") {
		exclude("net.mamoe","mirai-core-api")
		exclude("net.mamoe","mirai-core-utils")
	}
	implementation("net.mamoe:mirai-core-api-jvm:2.4.2") {
		exclude("net.mamoe", "mirai-core-utils")
	}
	implementation("net.mamoe:mirai-core-utils-jvm:2.4.2")
	implementation("org.jsoup:jsoup:1.13.1")
	implementation("com.google.code.gson:gson:2.8.6")
	testImplementation("org.springframework.boot:spring-boot-starter-test") {
		exclude(group = "org.junit.vintage", module = "junit-vintage-engine")
	}
	testImplementation("io.projectreactor:reactor-test")
}
```

**Comment by sandtechnology** [comment]
在2.6-RC中此问题已被修复，请更新后再试

**Comment by kuresaru** [comment]
> 在2.6-RC中此问题已被修复，请更新后再试

请问这个是2.6-rc的"特性"嘛
还是说我kotlin版本又有问题了 :D

```
2021-04-14 16:48:48.510 [DefaultDispatcher-worker-3] ERROR [top.scraft.robitgw.MiraiLogger] - Network/Exception in NetworkHandler
java.lang.NoSuchMethodError: 'double kotlin.time.Duration$Companion.getZERO()'
	at kotlinx.coroutines.DelayKt.toDelayMillis-LRDsOJo(Delay.kt:101)
	at kotlinx.coroutines.DelayKt.delay-p9JZ4hM(Delay.kt:90)
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$8$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:232)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by sandtechnology** [comment]
见https://github.com/mamoe/mirai/issues/1165

**Comment by sandtechnology** [comment]
另外我发现你的依赖方式有问题，请参照最新的文档进行依赖：https://github.com/mamoe/mirai/blob/dev/docs/ConfiguringProjects.md

**Comment by kuresaru** [comment]
> 另外我发现你的依赖方式有问题，请参照最新的文档进行依赖：https://github.com/mamoe/mirai/blob/dev/docs/ConfiguringProjects.md

记得当时这么写有问题 最后才在一个issue里找到的我现在这个操作:d

**Comment by Him188** [comment]
> > 另外我发现你的依赖方式有问题，请参照最新的文档进行依赖：https://github.com/mamoe/mirai/blob/dev/docs/ConfiguringProjects.md
> 
> 记得当时这么写有问题 最后才在一个issue里找到的我现在这个操作:d

那个是适用于 Android

**Comment by xszqxszq** [comment]
> 另外我发现你的依赖方式有问题，请参照最新的文档进行依赖：https://github.com/mamoe/mirai/blob/dev/docs/ConfiguringProjects.md

这个api的写法是不是groovy用不了，我换kts才成功

**Comment by Him188** [comment]
在 2.6.0 修复
