### ISSUE TITLE
支持发起陌生人会话

### ISSUE THREAD

**Issue by NekoWs** [mamoe/mirai#1200]
在 Mirai-Core 使用
```
Bot.getStrangerOrFail(id)
```
时抛出错误 `NoSuchElementException`

```
java.util.NoSuchElementException: stranger xxxxxxxxxx
        at net.mamoe.mirai.Bot.getStrangerOrFail(Bot.kt:117)
        at com.windowx.miraibot.EventListener.getAvatarId(EventListener.java:378)
        at com.windowx.miraibot.EventListener.replacePlaceholder(EventListener.java:351)
        at com.windowx.miraibot.EventListener.onGroupMessage(EventListener.java:232)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$14$1.invoke(JvmMethodListenersInternal.kt:140)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$14$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 复现

1. `bot.getStrangerOrFail(id)`
2. 把`id`改为任意QQ号
3. 运行即可

#### 版本
- Mirai-Core: `2.6.1` 

#### 补充信息

完全不能获取任何用户，包括好友

**Comment by sandtechnology** [comment]
https://github.com/mamoe/mirai/blob/a5e85f443e450a13b24c955823ab783fd36aa602/mirai-core-api/src/commonMain/kotlin/contact/Stranger.kt#L25-L41

**Comment by NekoWs** [comment]
> https://github.com/mamoe/mirai/blob/a5e85f443e450a13b24c955823ab783fd36aa602/mirai-core-api/src/commonMain/kotlin/contact/Stranger.kt#L25-L41

>`   * 陌生人的来源：当将添加好友设置为 `
>`   * ‘任何人可添加为好友’或‘需要回答对验证问题时’ `
>`   * 且被他人成功添加时此人会成为陌生人`

我 无法通过`[Bot.getStranger]`获取一个 Stranger 对象

而且`[Bot.getStranger]`的作用与`[Bot.getStrangerOrFail]`的作用区别也就在于抛出一个错误而已

**Comment by sandtechnology** [comment]
> 
> 
> > https://github.com/mamoe/mirai/blob/a5e85f443e450a13b24c955823ab783fd36aa602/mirai-core-api/src/commonMain/kotlin/contact/Stranger.kt#L25-L41
> 
> > `  * 陌生人的来源：当将添加好友设置为`
> > `  * ‘任何人可添加为好友’或‘需要回答对验证问题时’`
> > `   * 且被他人成功添加时此人会成为陌生人`
> 
> 我 无法通过`[Bot.getStranger]`获取一个 Stranger 对象
> 
> 而且`[Bot.getStranger]`的作用与`[Bot.getStrangerOrFail]`的作用区别也就在于抛出一个错误而已

```
* 陌生人的来源：当将添加好友设置为 
  * ‘任何人可添加为好友’或‘需要回答对验证问题时’ 
  * 且被他人成功添加时此人会成为陌生人 
  * 
  * 陌生人需要主动添加好友才能构成好友关系 
  * 但 Mirai 将不会提供此功能 
  * 请手动在其他客户端添加好友 ```

**Comment by Him188** [comment]
mirai 不支持与一个人建立陌生人关系, 只能由对方向 bot 发送消息后, bot 才能通过 `getStranger` 获取

**Comment by NekoWs** [comment]
> mirai 不支持与一个人建立陌生人关系, 只能由对方向 bot 发送消息后, bot 才能通过 `getStranger` 获取

那好吧，可是我需要这个功能，请求加上😭

**Comment by sandtechnology** [comment]
这是敏感操作 理应不应该进行支持
