### ISSUE TITLE
同一个QQ,本地和服务器来回切换,提示下线通知,必须删除cache文件夹和device.json文件才行

### ISSUE THREAD

**Issue by wangzheooo** [mamoe/mirai#1205]
用的ANDROID_WATCH协议

1.首先本地idea运行,提示进连接,手机QQ扫码辅助登录,木有问题,然后关闭项目

2.打包后放到linux上运行,提示

```
title=下线通知, message=你的帐号于15:56在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。)
2021-04-21 16:01:36 W/Bot ***: Init failed. Retrying in 3s... (rootCause=java.lang.IllegalStateException: network is dead therefore can't init.)
2021-04-21 16:01:39 W/Bot ***: Init failed. Retrying in 3s... (rootCause=java.lang.IllegalStateException: network is dead therefore can't init.)
2021-04-21 16:01:42 W/Bot ***: Init failed. Retrying in 3s... (rootCause=java.lang.IllegalStateException: network is dead therefore can't init.)
```

再运行也是这样的问题

3.删除linux服务器里的cache文件夹,删除device.json文件,重新运行
控制台一直循环报这个问题(里面的关键信息加了***)

```
2021-04-21 16:07:10 I/Bot ***: Logging in...
2021-04-21 16:07:11 I/Bot ***: [UnsafeLogin] 当前登录环境不安全，服务器要求账户认证。请在 QQ 浏览器打开 https://ti.qq.com/safe/verify?_wv=2&_wwv=128&uin=***&sig=uruZ6uk0XhbLSS01y9zWqmR7WcCoO5Xi0ej217%2B2uV9TN789NUubknqKjYMyr9hdahI%2FaYdv%2BGgsc00rpIl4x6kthIPGJYZh03rW4Kb0***%2FNQffR2I6dyb2Gj 并完成验证后输入任意字符。
2021-04-21 16:07:11 I/Bot ***: [UnsafeLogin] Account verification required by the server. Please open https://ti.qq.com/safe/verify?_wv=2&_wwv=128&uin=***&sig=uruZ6uk0***WqmR7WcCoO5Xi0ej217%2B2uV9TN789NUubknqKjYMyr9hdahI%2FaYdv%2BGgsc00rpIl4x6kthIPGJYZh03rW4Kb0Qyar4QI%2F5%2F***2I6dyb2Gj in QQ browser and complete challenge, then type anything here to submit.
2021-04-21 16:07:11 W/Bot ***: java.io.IOException: 错误的文件描述符
java.io.IOException: 错误的文件描述符
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at kotlin.io.LineReader.readLine(Console.kt:173)
	at kotlin.io.ConsoleKt.readLine(Console.kt:148)
	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$1.invokeSuspend(LoginSolver.jvm.kt:126)
	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$1.invoke(LoginSolver.jvm.kt)
	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$input$1$1.invokeSuspend(LoginSolver.jvm.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-04-21 16:07:12 I/Bot ***: [UnsafeLogin] 当前登录环境不安全，服务器要求账户认证。请在 QQ 浏览器打开 https://ti.qq.com/safe/verify?_wv=2&_wwv=128&uin=***&sig=IC4HyoqYUUtve8wqeaT3jpmqzG***Yh5ZfTnLhtyu4S8%2FNSKomTMA6O4Ne6xS9N2iGVSbWn9r%2FoGJodvKK%2B5Y7jMp%2FaHFt1h%2FqvjZWuO%2Bk***axhyfN1yoPVGAYXG 并完成验证后输入任意字符。
2021-04-21 16:07:12 I/Bot ***: [UnsafeLogin] Account verification required by the server. Please open https://ti.qq.com/safe/verify?_wv=2&_wwv=128&uin=***&sig=IC4HyoqYUUtve8w***3jpmqzGabbqYh5ZfTnLhtyu4S8%2FNSKomTMA6O4Ne6xS9N2iGVSbWn9r%2FoGJodvKK%2B5Y7jMp%2FaHFt1h%2FqvjZWuO%2BkdIjh***yfN1yoPVGAYXG in QQ browser and complete challenge, then type anything here to submit.
2021-04-21 16:07:12 W/Bot ***: java.io.IOException: 错误的文件描述符
java.io.IOException: 错误的文件描述符
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at kotlin.io.LineReader.readLine(Console.kt:173)
	at kotlin.io.ConsoleKt.readLine(Console.kt:148)
	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$1.invokeSuspend(LoginSolver.jvm.kt:126)
	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$1.invoke(LoginSolver.jvm.kt)
	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$input$1$1.invokeSuspend(LoginSolver.jvm.kt:138)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-04-21 16:07:13 I/Bot ***: [UnsafeLogin] 当前登录环境不安全，服务器要求账户认证。请在 QQ 浏览器打开 https://ti.qq.com/safe/verify?_wv=2&_wwv=128&uin=***&sig=pt4yJHgZBcnzGBQ***nKCTD2cFj7eBMSWOYNnxJflloa8IyRDj8c1qXmcOTupx8VXk3u8vEQE2N%2FBEMyUB8ABNd3vRLNQgdJc%2B5***wSwWroQ%2FyDol6x2h%2F 并完成验证后输入任意字符。
2021-04-21 16:07:13 I/Bot ***: [UnsafeLogin] Account verification required by the server. Please open https://ti.qq.com/safe/verify?_wv=2&_wwv=128&uin=***&sig=pt4yJHgZBcnzGBQIGnCYbA0wnKCTD2cFj7***nxJflloa8IyRDj8c1qXmcOTupx8VXk3u8vEQE2N%2FBEMyUB8ABNd3vRLNQgdJc%2B5***2FwSwWroQ%2FyDol6x2h%2F in QQ browser and complete challenge, then type anything here to submit.
2021-04-21 16:07:13 W/Bot ***: java.io.IOException: 错误的文件描述符
java.io.IOException: 错误的文件描述符
	at java.io.FileInputStream.readBytes(Native Method)
```

4.这个时候只能kill掉这个进程,然后找到控制台最后那个链接,用QQ辅助扫一扫登录,才会登录成功

5.这个时候kill掉服务器的项目,重新用idea本地运行
控制台就会报下线通知

```
2021-04-21 16:13:51 I/Bot ***: Loaded account secrets from local cache.
2021-04-21 16:13:53 I/Bot ***: Logging in...
2021-04-21 16:13:53 V/Bot ***: Event: Force(bot=Bot(***), title=下线通知, message=你的帐号于16:13在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。)
2021-04-21 16:13:53 I/Bot ***: Connection occupied by another android device: 你的帐号于16:13在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。
2021-04-21 16:13:53 W/Bot ***: Init failed. Retrying in 3s... (rootCause=net.mamoe.mirai.network.ForceOfflineException: Connection occupied by another android device: 你的帐号于16:13在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。)
2021-04-21 16:13:56 W/Bot ***: Init failed. Retrying in 3s... (rootCause=java.lang.IllegalStateException: network is dead therefore can't init.)
2021-04-21 16:13:59 W/Bot ***: Init failed. Retrying in 3s... (rootCause=java.lang.IllegalStateException: network is dead therefore can't init.)
2021-04-21 16:14:02 W/Bot ***: Init failed. Retrying in 3s... (rootCause=java.lang.IllegalStateException: network is dead therefore can't init.)
2021-04-21 16:14:05 E/Bot ***: Cannot init. some features may be affected
2021-04-21 16:14:05.492  INFO 34208 --- [  restartedMain] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-04-21 16:14:05.605 ERROR 34208 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) [spring-boot-2.4.5.jar:2.4.5]
```

6.只能再删掉cache文件夹,删除device.json文件,如此循环往复,可不可以不用删除文件,就能登录

**Comment by wangzheooo** [comment]
我开了登录保护,把登录保护关了,删除本地和服务器的cache文件夹和device.json文件,再往后就没问题了,不过还是有机器人发消息,电脑收不到,但是手机能收到的问题

**Comment by Him188** [comment]
确认关闭本地项目后 bot 进程结束了？

**Comment by wangzheooo** [comment]
> 确认关闭本地项目后bot进度结束了？

不确认,那是不是可以从手机上让QQ下线

**Comment by Him188** [comment]
你使用的版本是? 已知 2.6.0 和 2.6.1 有 #1199 这个问题. 在 2.6.2 修复(刚刚发布), 可以试试

**Comment by wangzheooo** [comment]
> 你使用的版本是? 已知 2.6.0 和 2.6.1 有 #1199 这个问题. 在 2.6.2 修复(刚刚发布), 可以试试

用的2.6.1,我试一下2.6.2

**Comment by wangzheooo** [comment]
> 你使用的版本是? 已知 2.6.0 和 2.6.1 有 #1199 这个问题. 在 2.6.2 修复(刚刚发布), 可以试试

还是报这个

```
2021-04-22 09:37:46 I/Bot ***: Loaded account secrets from local cache.
2021-04-22 09:37:48 I/Bot ***: Logging in...
2021-04-22 09:37:48 V/Bot ***: Event: Force(bot=Bot(***), title=下线通知, message=你的帐号于09:37在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。)
2021-04-22 09:37:48 I/Bot ***: Connection occupied by another android device: 你的帐号于09:37在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。
2021-04-22 09:37:48 W/Bot ***: Init failed. Retrying in 3s... (rootCause=net.mamoe.mirai.network.ForceOfflineException: Connection occupied by another android device: 你的帐号于09:37在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。)
2021-04-22 09:37:51 W/Bot ***: Init failed. Retrying in 3s... (rootCause=java.lang.IllegalStateException: network is dead therefore can't init.)
2021-04-22 09:37:54 W/Bot ***: Init failed. Retrying in 3s... (rootCause=java.lang.IllegalStateException: network is dead therefore can't init.)
2021-04-22 09:37:57 W/Bot ***: Init failed. Retrying in 3s... (rootCause=java.lang.IllegalStateException: network is dead therefore can't init.)
2021-04-22 09:38:00 E/Bot ***: Cannot init. some features may be affected
```

得手动删account.secrets文件再重启项目

**Comment by Him188** [comment]
这可能比较难修复, 将最晚在 #1191 处理

**Comment by openshell** [comment]
@Him188 
我这边也遇到类似问题。步骤如下：
1. 服务器上登陆QQ
2. 个人手机上登陆该QQ，马上再退出登录
3. 再重新到服务器上登陆QQ，会一直报
```
2021-04-27 14:18:04 V/Bot.***: Event: Force(bot=Bot(***), title=下线通知, message=你的帐号于2021年4月26日23:46在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。)
2021-04-27 14:18:04 I/Bot.***: Connection occupied by another android device: 你的帐号于2021年4月26日23:46在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。
2021-04-27 14:18:04 I/Bot.***: Reconnecting...
2021-04-27 14:18:04 I/Bot.***: Connection lost, retrying login (Force(bot=Bot(***), title=下线通知, message=你的帐号于2021年4月26日23:46在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。))

```
特别地：即使第一步登录后，马上下线，再执行后续步骤，仍然会报上述错误。
昨天我用笨办法更改QQ密码才能重新登上，今天看到这个issue，删除`account.secrets`文件后即可正常登录。

**Comment by sandtechnology** [comment]
我觉得直接在快速登录中删除`account.secrets`文件就可以破解这个死循环了（在登录失败后），因为核心原因是token已经被更换了

**Comment by Him188** [comment]
对旧网络层 (2.7 以前)的修复将包含在 2.6.4

**Comment by Him188** [comment]
已经在 2.7-M1 修复
