### ISSUE TITLE
更新到0.26.1后无法登陆

### ISSUE THREAD

**Issue by zhzRedstone** [mamoe/mirai#121]
[root@localhost qqbot]# java -jar mirai-console-wrapper-0.1.1.jar
You are running Mirai-Console-Wrapper under /home/app/qqbot
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Fetching Newest Console Version of Pure
Local Core Version: 0.26.1 | Newest Core Version: 0.26.1
Local Console-Pure Version: 0.3.2 | Newest Console-Pure Version: 0.3.2
Version check complete, starting Mirai
Core    :/home/app/qqbot/content/mirai-core-jvm-0.26.1.jar
Protocol:/home/app/qqbot/content/mirai-core-qqandroid-jvm-0.26.1.jar
Console :/home/app/qqbot/content/mirai-console-0.3.2.jar
Root    :/home/app/qqbot/
[Mirai 0.3.2 Pkmon]: Mirai-console now running under /home/app/qqbot
[Mirai 0.3.2 Pkmon]: Get news in github: https://github.com/mamoe/mirai
[Mirai 0.3.2 Pkmon]: Mirai为开源项目，请自觉遵守开源项目协议
[Mirai 0.3.2 Pkmon]: Powered by Mamoe Technologies and contributors
[Plugin Manager]: 开始加载/home/app/qqbot/plugins/下的插件
[Plugin Manager]: loading plugin MiraiAPIHTTP
[Plugin Manager]: successfully loaded plugin MiraiAPIHTTP version v1.1.1 by ryoii
[Plugin Manager]: Mirai HTTP API Server Plugin
[MiraiAPIHTTP]: Starting Mirai HTTP Server in 0.0.0.0:5710
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Mirai HTTP API 20:46:21 : Http api server is running with authKey: INITKEYzzh9KJYy
[Plugin Manager]: 加载了1个插件
[Mirai 0.3.2 Pkmon]: Mirai-console 启动完成
[Mirai 0.3.2 Pkmon]: "/login qqnumber qqpassword " to login a bot
[Mirai 0.3.2 Pkmon]: "/login qq号 qq密码 " 来登录一个BOT
login account password
[Bot Login]: login...
[BOT 3173857429]: Logging in...
[BOT 3173857429]: Initializing BotNetworkHandler
[NETWORK]: Connected to server 113.96.13.208:8080
Exception in thread "DefaultDispatcher-worker-2" java.lang.NoSuchFieldError: Default
        at net.mamoe.mirai.utils.DeviceInfo.generateDeviceInfoData(DeviceInfo.kt:62)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.login.WtLogin$Login$SubCommand9$invoke$$inlined$buildLoginOutgoingPacket$lambda$2.invoke(WtLogin.kt:179)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.login.WtLogin$Login$SubCommand9$invoke$$inlined$buildLoginOutgoingPacket$lambda$2.invoke(WtLogin.kt:126)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.EncryptMethodECDH$DefaultImpls.makeBody(EncryptMethod.kt:121)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.EncryptMethodECDH7.makeBody-impl(EncryptMethod.kt:61)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.EncryptMethodECDH7.makeBody(EncryptMethod.kt:1)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.OutgoingPacketAndroidKt.writeOicqRequestPacket(OutgoingPacketAndroid.kt:243)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.login.WtLogin$Login$SubCommand9.invoke(WtLogin.kt:135)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.relogin(QQAndroidBotNetworkHandler.kt:127)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$relogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)

**Comment by zhzRedstone** [comment]
等console更新。。。
