### ISSUE TITLE
Quote消息包含图片时出现异常

### ISSUE THREAD

**Issue by ryoii** [mamoe/mirai#122]
测试代码
```
bot.subscribeMessages{
        has<Image> {
            quoteReply(message.quote() + "引用一张图片")
        }
}
```

堆栈异常
```
Bot(3402393995) 15:36:47 : An exception was thrown under a coroutine of Bot
java.lang.IllegalStateException: send message failed: MessageSvc.PbSendMsg.Response.Failed(resultType=34, errorCode=0, errorMessage=)
	at net.mamoe.mirai.qqandroid.GroupImpl.sendMessage(ContactImpl.kt:603)
	at net.mamoe.mirai.qqandroid.GroupImpl$sendMessage$1.invokeSuspend(ContactImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Him188** [comment]
原因为消息过长, 需要分包发送, #90
