### ISSUE TITLE
Subscriber DSL 的 has<*> 不能正常捕获消息

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#1223]
MessageEventSubscribersBuilder DSL 的
 `public inline fun <reified N : Message> has(noinline onEvent: @MessageDsl suspend M.(N) -> R): Ret` 
不能正常捕获消息

```
2021-04-29 08:12:19 E/main: Exception in coroutine <unnamed>
java.lang.ClassCastException: class net.mamoe.mirai.internal.message.OnlineMessageSourceFromFriendImpl cannot be cast to class net.mamoe.mirai.message.data.QuoteReply (net.mamoe.mirai.internal.message.OnlineMessageSourceFromFriendImpl and net.mamoe.mirai.message.data.QuoteReply are in unnamed module of loader 'app')
        at mirai.RunMirai$setCustomize$1$4$2.invoke(RunMirai.kt)
        at mirai.RunMirai$setCustomize$1$4$$special$$inlined$has$3.invokeSuspend(MessageSubscribersBuilder.kt:327)
        at mirai.RunMirai$setCustomize$1$4$$special$$inlined$has$3.invoke(MessageSubscribersBuilder.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeFriendMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:226)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeFriendMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:431)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:49)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:49)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$3$invokeSuspend$$inlined$forEach0$lambda$1.invokeSuspend(InternalEventListeners.kt:154)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 复现

```
subscribeMessages {
    has<Image> {
        println(it.imageId)
    }
}
```

#### 版本
- mirai-core: `2.6.2`

**Comment by Him188** [comment]
```kotlin
    @MessageDsl
    public inline fun <reified N : Message> has(noinline onEvent: @MessageDsl suspend M.(N) -> R): Ret =
        content { message.any { it is N } }.invoke { onEvent.invoke(this, message.firstIsInstance()) }
```

代码没有问题 (我以前也写过 issue 中的示例代码并且正常运行), 看起来是编译器在某个版本引入了这个泛型推断问题 (使用了 `Message` 作为 `firstIsInstance<T>()` 参数 `T` 而没有使用 `N`)

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/117281459-3f952b00-ae96-11eb-8d1a-c02b10336b95.png)

![image](https://user-images.githubusercontent.com/12100985/117281361-268c7a00-ae96-11eb-958b-8861a37b482e.png)

没有复现问题

**Comment by cssxsh** [comment]
```
fun MiraiConsoleImplementation.setCustomize(): Unit = globalEventChannel().run {
        subscribeMessages {
            has<Image> {
                println(it.imageId)
            }
        }
}
```

> ![image](https://user-images.githubusercontent.com/12100985/117281459-3f952b00-ae96-11eb-8d1a-c02b10336b95.png)
> 
> ![image](https://user-images.githubusercontent.com/12100985/117281361-268c7a00-ae96-11eb-958b-8861a37b482e.png)
> 
> 没有复现问题

我是对MiraiConsoleImplementation或者MiraiConsole进行监听
jdk版本为openjdk version "11" 2018-09-25
```
fun MiraiConsoleImplementation.setCustomize(): Unit = globalEventChannel().run {
        subscribeMessages {
            has<Image> {
                println(it.imageId)
            }
        }
}
```
`mirai 2.6.4` 还是有一样的报错
```
2021-05-10 11:47:47 E/main: Exception in coroutine <unnamed>
java.lang.ClassCastException: class net.mamoe.mirai.internal.message.OnlineMessageSourceFromGroupImpl cannot be cast to class net.mamoe.mirai.message.data.Image (net.mamoe.mirai.internal.message.OnlineMessageSourceFromGroupImpl and net.mamoe.mirai.message.data.Image are in unnamed module of loader 'app')
        at mirai.RunMirai$setCustomize$1$1$1.invoke(RunMirai.kt)
        at mirai.RunMirai$setCustomize$1$1$$special$$inlined$has$2.invokeSuspend(MessageSubscribersBuilder.kt:327)
        at mirai.RunMirai$setCustomize$1$1$$special$$inlined$has$2.invoke(MessageSubscribersBuilder.kt)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
        at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invokeSuspend(subscribeMessages.kt:226)
        at net.mamoe.mirai.event.SubscribeMessagesKt__SubscribeMessagesKt$subscribeMessages$$inlined$createBuilder$SubscribeMessagesKt__SubscribeMessagesKt$1$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:49)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:49)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$3$invokeSuspend$$inlined$forEach0$lambda$1.invokeSuspend(InternalEventListeners.kt:154)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Him188** [comment]
是否正在使用 Kotlin 1.4.30 编译器?

**Comment by cssxsh** [comment]
> 是否正在使用 Kotlin 1.4.30 编译器?

是的

**Comment by Him188** [comment]
已成功复现, 应该是 Kotlin 类型推断问题, 它只能在一些特定情况才能复现, 可能是外部有 `run` 或者有多层 implicit receiver
