### ISSUE TITLE
撤回好友消息

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#123]

**Comment by zhzRedstone** [comment]
我在测试HTTP API的时候有以下日志，

``` 
20:24:21 [INFO] [ConsoleAddition] [NETWORK] Received: MultiPacketBySequence
 20:24:21 [INFO] [ConsoleAddition] [NETWORK] Send: OnlinePush.RespPush
 20:24:21 [INFO] [ConsoleAddition] [NETWORK] Received: Failed(result=3, errorMessage=)
 20:24:21 [ERROR] [MiraiAPIHTTP] java.lang.IllegalStateException: Failed to recall message #1228883919: Failed(result=3, errorMessage=)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.recall$suspendImpl(QQAndroidBot.common.kt:264)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase$recall$1.invokeSuspend(QQAndroidBot.common.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

```
POST /recall HTTP/1.1
Content-Length: 58
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:5710
{
    "sessionKey": "urGaPTZT",
    "target": 1034514596
}

HTTP/1.1 500 Internal Server Error
Date: Sun, 05 Apr 2020 12:32:50 GMT
Server: Application/debug ktor/debug
Content-Length: 69
Content-Type: text/plain; charset=UTF-8
Connection: keep-alive
Failed to recall message #1034514596: Failed(result=3, errorMessage=)
```

**Comment by Him188** [comment]
目前直接没有支持这个功能，因此会报错。
考虑在1.0发布后再支持
