### ISSUE TITLE
当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试

### ISSUE THREAD

**Issue by TihPct** [mamoe/mirai#1235]
版本:2.6.2
平台:java
  <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.6.2</version>
 </dependency>
问题:更换新的账号无法登录

**Comment by TihPct** [comment]
设备锁均已开启(tips=若频繁出现, 请尝试开启设备锁)

**Comment by Him188** [comment]
原因未知, 建议尝试:
- 关闭设备锁
- 在 PC 客户端登录一次
- 修改密码

**Comment by dragon0629** [comment]
同样遇到这个问题，已做以下尝试：
1.关闭/开启设备锁
2.PC端登录
3.修改密码
均无效

MIRAI相关模块版本如下：

mirai-console-2.6.4-all
mirai-console-terminal-2.6.4-all
mirai-core-all-2.6.4-all
mirai-login-solver-selenium-1.0-dev-17-all

原因不明，不知道是否能将手机信任过的设备信息导出，或者用PC登陆过QQ的环境来生成这个device.json

目前依旧是只能从登陆过的MIRAI老版本拷bots文件夹过来才能登录

**Comment by dragon0629** [comment]
2021-05-18 16:17:12 W/stderr: ����: Unable to find version of CDP to use for . You may need to include a dependency on a specific version of the CDP using something similar to `org.seleniumhq.selenium:selenium-devtools-v86:4.0.0-alpha-7` where the version ("v86") matches the version of the chromium-based browser you're using and the version number of the artifact is the same as Selenium's.
2021-05-18 16:17:12 W/stderr:
2021-05-18 16:17:17 W/stderr:
2021-05-18 16:17:18 W/stderr:
2021-05-18 16:17:18 I/Bot.2841294938: Bot cancelled: Job was cancelled
Login failed: Error(bot=Bot(2841294938), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备 上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
2021-05-18 16:17:18 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2841294938), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2841294938), code=237, title=禁止登录, message=当前上网环 境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.doSlowLogin(QQAndroidBotNetworkHandler.kt:335)
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$doSlowLogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by dragon0629** [comment]
具体就是过掉验证滑块之后，没有正常弹出解锁设备锁的界面，而是窗口直接报禁止登录的提示。
原因不明，或者不知道是否能将手机信任过的设备信息导出，或者用PC登陆过QQ的环境来生成这个device.json ，提供这么一个备选方案  0_0

**Comment by Him188** [comment]
最近新账号确实是不能登录 mirai，在官方客户端养一段时间试试

**Comment by Karlatemp** [comment]
已经更新相关资料

**Comment by TihPct** [comment]
> 最近新账号确实是不能登录 mirai，在官方客户端养一段时间试试

养 蛊
