### ISSUE TITLE
MCL自动更新到2.6.4后，机器人启动失败

### ISSUE THREAD

**Issue by Zqysl** [mamoe/mirai#1251]
刚刚例行重启机器人，执行了：
```
stop
./mcl
```
MCL自动更新2.6.4后启动失败

```
> root@ubuntu-pro-18-2cpu-8g-128g-5:~/Desktop/Mirai# ./mcl
 16:03:54 [INFO] iTXTech Mirai Console Loader version 1.0.5-9b6cf6d
 16:03:54 [INFO] https://github.com/iTXTech/mirai-console-loader
 16:03:54 [INFO] This program is licensed under GNU AGPL v3
 16:03:54 [DEBUG] Loading script: oraclejdk.js
 16:03:54 [DEBUG] Loading script: repo.js
 16:03:54 [DEBUG] Loading script: updater.js
 16:03:54 [DEBUG] Loading script: announcement.js
 16:03:54 [DEBUG] Loading script: boot.js
 16:03:54 [DEBUG] Loading script: config.js
 16:03:54 [INFO] Verifying "net.mamoe:mirai-console" version 2.6.3
 Downloading mirai-console-2.6.4.jar [==============================] 1.40 MB                         
 Downloading mirai-console-2.6.4.sha1 [==============================] 40 B                  
 16:04:01 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.6.3
 Downloading mirai-console-terminal-2.6.4.jar [==============================] 72.17 KB                       
 Downloading mirai-console-terminal-2.6.4.sha1 [==============================] 40 B                  
 16:04:03 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.6.3
 Downloading mirai-core-all-2.6.4.jar [==============================] 261 B                   
 Downloading mirai-core-all-2.6.4.sha1 [==============================] 40 B                  
 16:04:08 [INFO] Fetching Mirai Console Loader Announcement...
 16:04:08 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

[mirai-console] 最近, 项目组发现了权限系统可能会被错误的提前加载导致的3rd权限系统无法正确加载

于是决定, 于 2.6 起, 超前访问权限系统将得到一个错误并中断插件加载, 请各开发者及时检查

影响范围: https://github.com/mamoe/mirai-console/pull/307


Exception in thread "main" java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutineScope
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
	at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.base/java.lang.Class.getMethodsRecursive(Unknown Source)
	at java.base/java.lang.Class.getMethod0(Unknown Source)
	at java.base/java.lang.Class.getMethod(Unknown Source)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy4.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
	at org.itxtech.mcl.Loader.start(Loader.java:129)
	at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.CoroutineScope
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 49 more

```

#### 复现
运行2.6.3版本MCL

#### 版本
2.6.3  (升级后2.6.4)

**Comment by Him188** [comment]
多重启几次试试？看起来是网络不好

**Comment by sandtechnology** [comment]
@Him188 会不会是jar没传上去 看样子下载的文件大小不正常

**Comment by Him188** [comment]
@sandtechnology 不会， jcenter 返回 success 了，除非是 jcenter 现在就关了

**Comment by Zqysl** [comment]
@Him188 多次重启无效，删掉libs后启动才恢复正常

**Comment by Zqysl** [comment]
@Him188 我可能恰巧在你上传的时候重启了机器人，00:00分左右。所以出现了这么匪夷所思的问题

**Comment by Him188** [comment]
> @Him188 我可能恰巧在你上传的时候重启了机器人，00:00分左右。所以出现了这么匪夷所思的问题

应该确实是的，我就是在刚刚上传的..
