### ISSUE TITLE
当前版本过低，请升级到QQ最新版本

### ISSUE THREAD

**Issue by nanxia990105** [mamoe/mirai#1262]
有的QQ 登录提示QQ版本过低 也不是全部 这怎么升级啊

```
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(806652030), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.doSlowLogin(QQAndroidBotNetworkHandler.kt:332) ~[mirai-core-jvm-2.6.2.jar:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$doSlowLogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt) ~[mirai-core-jvm-2.6.2.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.4.32.jar:1.4.32-release-371 (1.4.32)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.4.32.jar:1.4.32-release-371 (1.4.32)]
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:396) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:388) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:293) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1408) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:803) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$PacketListener.complete(QQAndroidBotNetworkHandler.kt) ~[mirai-core-jvm-2.6.2.jar:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.handlePacket(QQAndroidBotNetworkHandler.kt:623) ~[mirai-core-jvm-2.6.2.jar:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:591) ~[mirai-core-jvm-2.6.2.jar:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt) ~[mirai-core-jvm-2.6.2.jar:na]
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseOicqResponse(PacketFactory.kt:439) ~[mirai-core-jvm-2.6.2.jar:na]
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:294) ~[mirai-core-jvm-2.6.2.jar:na]
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:246) ~[mirai-core-jvm-2.6.2.jar:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:582) ~[mirai-core-jvm-2.6.2.jar:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:577) ~[mirai-core-jvm-2.6.2.jar:na]
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:559) ~[mirai-core-jvm-2.6.2.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.4.32.jar:1.4.32-release-371 (1.4.32)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[kotlinx-coroutines-core-jvm-1.4.2.jar:na]
```

#### 复现

--------------------------------------------------------------------

#### 版本
- mirai-core: `2.6.2` 

#### 补充信息

目前3个QQ号只有一个 会这样需要验证码和报错版本过低

**Comment by Him188** [comment]
可能是 QQ 号的等级太低了, 建议先使用一段时间

**Comment by nanxia990105** [comment]
22级了 其他26级的也可以登陆上去 都是大于一个太阳的

**Comment by nanxia990105** [comment]
这个是属于我这边无法解决的问题吗

**Comment by nanxia990105** [comment]
> 可能是 QQ 号的等级太低了, 建议先使用一段时间

22级了 其他26级的也可以登陆上去 都是大于一个太阳的 .这个是属于我这边无法解决的问题吗

**Comment by Him188** [comment]
> > 可能是 QQ 号的等级太低了, 建议先使用一段时间
> 
> 22级了 其他26级的也可以登陆上去 都是大于一个太阳的 .这个是属于我这边无法解决的问题吗

不知道

**Comment by nanxia990105** [comment]
> > > 可能是 QQ 号的等级太低了, 建议先使用一段时间
> > 
> > 
> > 22级了 其他26级的也可以登陆上去 都是大于一个太阳的 .这个是属于我这边无法解决的问题吗
> 
> 不知道

好吧

**Comment by nanxia990105** [comment]
> > > 可能是 QQ 号的等级太低了, 建议先使用一段时间
> > 
> > 
> > 22级了 其他26级的也可以登陆上去 都是大于一个太阳的 .这个是属于我这边无法解决的问题吗
> 
> 不知道

对了 请问框架有这个QQ版本的配置吗

**Comment by sandtechnology** [comment]
你的协议类型是？推荐使用PHONE协议

**Comment by nanxia990105** [comment]
> 你的协议类型是？推荐使用PHONE协议

phone要滑动验证 不可以

**Comment by sandtechnology** [comment]
> 
> 
> > 你的协议类型是？推荐使用PHONE协议
> 
> phone要滑动验证 不可以

你的协议类型是？
关于滑动验证，请看https://github.com/project-mirai/mirai-login-solver-selenium

**Comment by mjysci** [comment]
碰到类似的报错。  
该QQ号是基于mirai写的群机器人，未做他用，稳定运行快一年了。  
用手机QQ登录后提示帐号被冻结，然后发短信解封，还需要人脸识别验证，通过后即可正常登录使用。  
仅作参考。

**Comment by nanxia990105** [comment]
> > > 你的协议类型是？推荐使用PHONE协议
> > 
> > 
> > phone要滑动验证 不可以
> 
> 你的协议类型是？
> 关于滑动验证，请看https://github.com/project-mirai/mirai-login-solver-selenium

嗯好的 多谢 多谢

**Comment by nanxia990105** [comment]
> 碰到类似的报错。
> 该QQ号是基于mirai写的群机器人，未做他用，稳定运行快一年了。
> 用手机QQ登录后提示帐号被冻结，然后发短信解封，还需要人脸识别验证，通过后即可正常登录使用。
> 仅作参考。

我想问下 换设备登陆碰到的 那些需要输入验证码 或者滑动验证 有办法监控嘛

**Comment by mjysci** [comment]
> > 碰到类似的报错。
> > 该QQ号是基于mirai写的群机器人，未做他用，稳定运行快一年了。
> > 用手机QQ登录后提示帐号被冻结，然后发短信解封，还需要人脸识别验证，通过后即可正常登录使用。
> > 仅作参考。
> 
> 我想问下 换设备登陆碰到的 那些需要输入验证码 或者滑动验证 有办法监控嘛

我是用无头服务器跑的程序，验证码直接通过终端打印，把窗口开大些就能看得清楚。  
理论上换设备带上`device.json`就能直接登录，你可以试试在本地跑程序，通过验证后把生成的`device.json`拷到目标机的运行目录。不过我没试过，我是直接在服务器验证后就没换过设备。

**Comment by kaixinsoft** [comment]
> > > 你的协议类型是？推荐使用PHONE协议
> > 
> > 
> > phone要滑动验证 不可以
> 
> 你的协议类型是？
> 关于滑动验证，请看https://github.com/project-mirai/mirai-login-solver-selenium

这个滑块现在也不好用了吧？

**Comment by nanxia990105** [comment]
> > > > 你的协议类型是？推荐使用PHONE协议
> > > 
> > > 
> > > phone要滑动验证 不可以
> > 
> > 
> > 你的协议类型是？
> > 关于滑动验证，请看https://github.com/project-mirai/mirai-login-solver-selenium
> 
> 这个滑块现在也不好用了吧？

还好吧 能登陆
