### ISSUE TITLE
NewContact.SystemMsgNewGroup, subType=5, groupMsgType=6

### ISSUE THREAD

**Issue by woolsen** [mamoe/mirai#1263]
运行时报错

```
java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=6 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#190694508 {
            actionUin=0x00000000B1716863(2976999523)
            actionUinNick=[打码]
            actionUinQqNick=[打码]
            actions=[]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x0000000021A8129C(564662940)
            groupExtFlag=0x002504C0(2426048)
            groupFlagext3=0x60002000(1610620928)
            groupInfo=GroupInfo#1110308179 {
                    appPrivilegeFlag=0x140880C3(336101571)
                    msgOtherAdminDone=其他管理员
            }
            groupMsgType=0x00000006(6)
            groupName=[打码]
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%action_uin%
            msgDescribe=已将 %req_uin% 移出群
            msgTitle=退群消息
            reqUinAge=0x00000014(20)
            reqUinFaceid=0x00000D02(3330)
            reqUinNick=[打码]
            subType=0x00000005(5)
    }
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:23) ~[mirai-core-jvm-2.6.4.jar!/:na]
        at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup$decode$2.invoke(NewContact.kt:233) ~[mirai-core-jvm-2.6.4.jar!/:na]
        at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:265) ~[mirai-core-jvm-2.6.4.jar!/:na]
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:526) ~[mirai-core-jvm-2.6.4.jar!/:na]
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:247) ~[mirai-core-jvm-2.6.4.jar!/:na]
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:595) ~[mirai-core-jvm-2.6.4.jar!/:na]
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:590) ~[mirai-core-jvm-2.6.4.jar!/:na]
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:572) ~[mirai-core-jvm-2.6.4.jar!/:na]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.4.32.jar!/:1.4.32-release-371 (1.4.32)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.4.2.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[kotlinx-coroutines-core-jvm-1.4.2.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.4.2.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[kotlinx-coroutines-core-jvm-1.4.2.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[kotlinx-coroutines-core-jvm-1.4.2.jar!/:na]
```

#### 复现

运行时报错

#### 版本
- mirai-core: `2.6.4`

**Comment by Him188** [comment]
看日志是有收到其他管理员移除成员的通知, 当时是否接收到 `BotLeaveEvent` 或 `MemberLeaveEvent` 或其他事件?

**Comment by Him188** [comment]
经测试, 

- bot 为群主, 管理员踢出群员
- bot 为管理员, 群主踢出群员

这两个情况都能成功解析, 该 issue 应该不影响使用

**Comment by sandtechnology** [comment]
> 
> 
> 经测试,
> 
>     * bot 为群主, 管理员踢出群员
> 
>     * bot 为管理员, 群主踢出群员
> 
> 
> 这两个情况都能成功解析, 该 issue 应该不影响使用

应该过滤掉该消息？

**Comment by Him188** [comment]
与 #1171 重复
