### ISSUE TITLE
反序列化 ForwardMessage 的时候出现了 SerializationException

### ISSUE THREAD

**Issue by Coloryr** [mamoe/mirai#1264]
`由 mirai 码字符串取得 MessageChain 实例`
能否支持mirai:origin:FORWARD

`ForwardMessage`也不能转成json
我在序列化反序列化`ForwardMessage`的时候出现了问题

**Comment by Karlatemp** [comment]
> 我在序列化反序列化`ForwardMessage`的时候出现了问题

具体报错是?

**Comment by Coloryr** [comment]
```
[31m2021-05-13 22:09:11 E/Net 1092415357: An exception was thrown under a coroutine of Bot
net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$14$1.invoke(JvmMethodListenersInternal.kt:147)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$14$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$14$1.invoke(JvmMethodListenersInternal.kt:140)
	... 7 more
Caused by: kotlinx.serialization.SerializationException: Class 'ForwardMessageInternal' is not registered for polymorphic serialization in the scope of 'SingleMessage'.
Mark the base class as 'sealed' or register the serializer explicitly.
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:103)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:113)
	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:96)
	at kotlinx.serialization.json.internal.PolymorphicKt.findActualSerializer(Polymorphic.kt:29)
	at kotlinx.serialization.json.internal.PolymorphicKt.access$findActualSerializer(Polymorphic.kt:1)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:273)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
	at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:69)
	at net.mamoe.mirai.message.data.MessageChain$Serializer.serialize(MessageChain.kt:262)
	at net.mamoe.mirai.message.data.MessageChain$Serializer.serialize(MessageChain.kt:257)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:270)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData.write$Self(MessageSerializersImpl.kt)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData$$serializer.serialize(MessageSerializersImpl.kt)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData$$serializer.serialize(MessageSerializersImpl.kt:46)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$$special$$inlined$map$1.serialize(MessageSerializersImpl.kt:230)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl.serialize(MessageSerializersImpl.kt)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl.serialize(MessageSerializersImpl.kt:32)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:275)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
	at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:69)
	at net.mamoe.mirai.message.data.MessageChain$Serializer.serialize(MessageChain.kt:262)
	at net.mamoe.mirai.message.data.MessageChain$Serializer.serialize(MessageChain.kt:257)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:270)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:73)
	at net.mamoe.mirai.message.data.MessageChain$Companion.serializeToJsonString(MessageChain.kt:314)
	at net.mamoe.mirai.message.data.MessageChain$Companion.serializeToJsonString$default(MessageChain.kt:313)
	at net.mamoe.mirai.message.data.MessageChain.serializeToJsonString(MessageChain.kt)
	at Color_yr.ColorMirai.Pack.ToPlugin.GroupMessageEventPack.<init>(GroupMessageEventPack.java:35)
	at Color_yr.ColorMirai.Robot.BotEvent.onGroupMessageEvent(BotEvent.java:713)
	... 12 more
```

**Comment by Him188** [comment]
使用的版本是 2.6.4？

**Comment by Coloryr** [comment]
对的

**Comment by Him188** [comment]
问题原因是 #1267
