### ISSUE TITLE
maven项目启动报错Exception in NetworkHandler java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by xingchenxuup** [mamoe/mirai#1271]
<kotlin.version>1.4.32</kotlin.version>

 <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.6.4</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlin.version}</version>
        </dependency>

报错信息
java.lang.NoSuchMethodError: kotlinx.coroutines.DelayKt.delay-p9JZ4hM(DLkotlin/coroutines/Continuation;)Ljava/lang/Object;
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$8$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:235)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by sandtechnology** [comment]
https://github.com/mamoe/mirai/issues/1126
