### ISSUE TITLE
Bot login 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by xiao-nie** [mamoe/mirai#1272]
调试信息: kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:23)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:21)
	at net.mamoe.mirai.internal.AbstractBot$Login.doLogin(AbstractBot.kt:297)
	at net.mamoe.mirai.internal.AbstractBot$Login$doLogin$1.invokeSuspend(AbstractBot.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at love.forte.simbot.component.mirai.MiraiBotVerifier.verity(MiraiBotVerifier.kt:71)
	... 14 more
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized
	at net.mamoe.mirai.internal.QQAndroidBot.getNick(QQAndroidBot.kt:121)
	at net.mamoe.mirai.internal.AbstractBot$Login.doLogin(AbstractBot.kt:295)
	... 27 more

**Comment by Karlatemp** [comment]
版本号是？新版本已经对此问题进行过修复

**Comment by xiao-nie** [comment]
这个是2.0.1，更换2.0.5之后解决了
