### ISSUE TITLE
反序列化图片的MessageSource失败

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#1273]
使用代码:
`val source = json.decodeFromString(MessageSource.Serializer,a)`
反序列化MessageSource, 当MessageSource是图片时失败，报错
```
2021-05-21 22:32:49 E/Bot 111: Encountered unknown key 'type'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
Current input: {"type":"Image","imageId":"{47B45B11-1491-3E85-E816-467029444C3F}.jpg"}
kotlinx.serialization.json.internal.JsonDecodingException: Encountered unknown key 'type'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
Current input: {"type":"Image","imageId":"{47B45B11-1491-3E85-E816-467029444C3F}.jpg"}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.UnknownKeyException(JsonExceptions.kt:62)
	at kotlinx.serialization.json.internal.JsonTreeDecoder.endStructure(TreeJsonDecoder.kt:230)
	at net.mamoe.mirai.message.data.Image$FallbackSerializer$Delegate$$serializer.deserialize(Image.kt)
	at net.mamoe.mirai.message.data.Image$FallbackSerializer$Delegate$$serializer.deserialize(Image.kt:107)
	at net.mamoe.mirai.message.data.Image$FallbackSerializer$$special$$inlined$map$1.deserialize(MessageSerializersImpl.kt:229)
	at net.mamoe.mirai.message.data.Image$FallbackSerializer.deserialize(Image.kt)
	at net.mamoe.mirai.message.data.Image$Serializer.deserialize(Image.kt)
	at net.mamoe.mirai.message.data.Image$Serializer.deserialize(Image.kt:97)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readPolymorphicJson(TreeJsonDecoder.kt:32)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:73)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:536)
	at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at net.mamoe.mirai.message.data.MessageChain$Serializer.deserialize(MessageChain.kt:261)
	at net.mamoe.mirai.message.data.MessageChain$Serializer.deserialize(MessageChain.kt:257)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData$$serializer.deserialize(MessageSerializersImpl.kt)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData$$serializer.deserialize(MessageSerializersImpl.kt:46)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$$special$$inlined$map$1.deserialize(MessageSerializersImpl.kt:229)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl.deserialize(MessageSerializersImpl.kt)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl.deserialize(MessageSerializersImpl.kt:32)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:32)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
	at tech.eritquearcus.miraicp.KotlinMain.recallMsg(KotlinMain.kt:253)
```
测试的序列化后MessageSource
```
{"kind":"GROUP","botId":692928873,"ids":[44],"internalIds":[-933057735],"time":1621607925,"fromId":1930893235,"targetId":1067474509,"originalMessage":[{"type":"Image","imageId":"{47B45B11-1491-3E85-E816-467029444C3F}.jpg"}]}
```
然后我也确认了，用
`val tmp = json.encodeToString(MessageSource.Serializer, this.message[MessageSource]!!)`
生成的序列化结果也是这个构造
```
{"kind":"GROUP","botId":692928873,"ids":[44],"internalIds":[-933057735],"time":1621607925,"fromId":1930893235,"targetId":1067474509,"originalMessage":[{"type":"Image","imageId":"{47B45B11-1491-3E85-E816-467029444C3F}.jpg"}]}
```

#### 版本
- mirai-core: `2.6.4`

**Comment by Him188** [comment]
可以临时添加
```kotlin
Json {
    // ...
    ignoreUnknownKeys = true
}
```

----

看起来是 kotlinx.serialization 的问题, 将用于指定多态类型的 "type" 字段传递给了 `Image` 的 serializer.

**Comment by Nambers** [comment]
> 可以临时添加
> 
> ```kotlin
> Json {
>     // ...
>     ignoreUnknownKeys = true
> }
> ```
> 
> 看起来是 kotlinx.serialization 的问题, 将用于指定多态类型的 "type" 字段传递给了 `Image` 的 serializer.

ok 可以用
