### ISSUE TITLE
序列化ForwardMessages返回的MessageSource出错

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#1289]
代码:
```kotlin
        val re = a.build().sendTo(c1).source
        logger.info("re: $re")
        try {
            val ree = json.encodeToString(MessageSource.Serializer, re)
            logger.info("ree: $ree")
        }catch(e:Exception){
            logger.error(e.message)
            e.printStackTrace()
        }
```

```
2021-05-31 11:22:03 I/Bot 692928873: re: [mirai:source:[2532],[1510910870]]
2021-05-31 11:22:03 E/Bot 692928873: Class 'ForwardMessageInternal' is not registered for polymorphic serialization in the scope of 'SingleMessage'.
Mark the base class as 'sealed' or register the serializer explicitly.
kotlinx.serialization.SerializationException: Class 'ForwardMessageInternal' is not registered for polymorphic serialization in the scope of 'SingleMessage'.
Mark the base class as 'sealed' or register the serializer explicitly.
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:103)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:113)
	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:96)
	at kotlinx.serialization.json.internal.PolymorphicKt.findActualSerializer(Polymorphic.kt:29)
	at kotlinx.serialization.json.internal.PolymorphicKt.access$findActualSerializer(Polymorphic.kt:1)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:273)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
	at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:69)
	at net.mamoe.mirai.message.data.MessageChain$Serializer.serialize(MessageChain.kt:262)
	at net.mamoe.mirai.message.data.MessageChain$Serializer.serialize(MessageChain.kt:257)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:270)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData.write$Self(MessageSerializersImpl.kt)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData$$serializer.serialize(MessageSerializersImpl.kt)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$SerialData$$serializer.serialize(MessageSerializersImpl.kt:46)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl$$special$$inlined$map$1.serialize(MessageSerializersImpl.kt:230)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl.serialize(MessageSerializersImpl.kt)
	at net.mamoe.mirai.internal.message.MessageSourceSerializerImpl.serialize(MessageSerializersImpl.kt:32)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:270)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:73)
	at tech.eritquearcus.miraicp.KotlinMain.buildforwardMsg(KotlinMain.kt:494)
	at tech.eritquearcus.miraicp.KotlinMain$buildforwardMsg$1.invokeSuspend(KotlinMain.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at tech.eritquearcus.miraicp.CPP_lib$Companion.KBuildforward(CPP_lib.kt:157)
```

#### 版本
- mirai-core: `2.6.4`

**Comment by Him188** [comment]
与 #1267 原因相同

**Comment by Nambers** [comment]
> 与 #1267 原因相同

指在2.7-M1修复? ok
