### ISSUE TITLE
启动时报错 Caused by: java.nio.channels.UnresolvedAddressException

### ISSUE THREAD

**Issue by shenjackyuanjie** [mamoe/mirai#1294]
进行启动之后直接报错

```
D:\githubs\QQbot>.\mcl
 05:34:47 [INFO] iTXTech Mirai Console Loader version 1.0.5-9b6cf6d
 05:34:47 [INFO] https://github.com/iTXTech/mirai-console-loader
 05:34:47 [INFO] This program is licensed under GNU AGPL v3
 05:34:47 [DEBUG] Loading script: announcement.js
 05:34:47 [DEBUG] Loading script: boot.js
 05:34:47 [DEBUG] Loading script: config.js
 05:34:47 [DEBUG] Loading script: oraclejdk.js
 05:34:47 [INFO] OracleJDK is detected. MCL will download BouncyCastle automatically.
 05:34:47 [DEBUG] Loading script: repo.js
 05:34:47 [DEBUG] Loading script: updater.js
 05:34:47 [INFO] Fetching Mirai Console Loader Announcement...
 05:34:47 [ERROR] Failed to fetch announcement.
 05:34:47 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" version 1.64
 05:34:47 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.net.ConnectException (updater.js#57)
        at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at script.check(updater.js:57)
        at script(updater.js:38)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at jdk.proxy1/jdk.proxy1.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseLoad(ScriptManager.java:93)
        at org.itxtech.mcl.Loader.start(Loader.java:126)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.net.ConnectException
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:555)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119)
        at org.itxtech.mcl.component.Repository.httpGet(Repository.java:124)
        at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:68)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        ... 18 more
Caused by: java.net.ConnectException
        at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1038)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:197)
        at java.net.http/jdk.internal.net.http.AsyncSSLConnection.connectAsync(AsyncSSLConnection.java:56)
        at java.net.http/jdk.internal.net.http.Http2Connection.createAsync(Http2Connection.java:379)
        at java.net.http/jdk.internal.net.http.Http2ClientImpl.getConnectionFor(Http2ClientImpl.java:128)
        at java.net.http/jdk.internal.net.http.ExchangeImpl.get(ExchangeImpl.java:93)
        at java.net.http/jdk.internal.net.http.Exchange.establishExchange(Exchange.java:342)
        at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:474)
        at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:379)
        at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:371)
        at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:407)
        at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:448)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)
        at java.base/java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946)
        at java.base/java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2336)
        at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:438)
        at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:340)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769)
        at java.net.http/jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:155)
        at java.base/java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2669)
        at java.net.http/jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:293)
        at java.net.http/jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:635)
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:534)
        ... 26 more
Caused by: java.nio.channels.UnresolvedAddressException
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:149)
        at java.base/sun.nio.ch.Net.checkAddress(Net.java:157)
        at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:815)
        at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:837)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:182)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:184)
        ... 49 more
```

#### 复现

正在配置账号密码时尝试启动
就这个样子了

#### 版本
- mirai-core: `1.3.0` 
![image](https://user-images.githubusercontent.com/54507071/120244251-531c9180-c29c-11eb-9b51-4e4793fbd103.png)
所有插件

**Comment by Him188** [comment]
网络不好? 试试多重启几次 mirai

**Comment by shenjackyuanjie** [comment]
> 网络不好? 试试多重启几次 mirai

确实，多次尝试之后就没问题了
但是总是这样很烦 
rua！

**Comment by shenjackyuanjie** [comment]
另外补充一下
发现如果在启动mcl之后log蹦的非常快
那么一定（几十次的结果）会崩溃（如上文）
如果在加载的时候log蹦的速度相对正常（主要指的是
![image](https://user-images.githubusercontent.com/54507071/120358505-1eaae300-c339-11eb-84dc-092ce0baab96.png)
这一块，这四条日志不是一块蹦出来的，而是明显有一个停顿）
也许能提供信息？

**Comment by shenjackyuanjie** [comment]
如果蹦的太快，就说明会蹦
反之则不会

**Comment by AdoptOSS** [comment]
> 如果蹦的太快，就说明会蹦
> 反之则不会

****One possible explanation****
这些verify都是需要网络的，当网络不可用时，这些检测极快完成（java抛出exception，这些检测内部catch了错误后直接忽略错误继续运行）。但网络正常时，由于连接repo需要一定的时间，故相对较慢
这个现象应该只是指示网络的正常与否，无法说明潜在成因
