### ISSUE TITLE
使用selectMessages  条件has判断包含提示类型无法转换

### ISSUE THREAD

**Issue by Xiaolangs** [mamoe/mirai#1348]
有问题的代码
 subject.sendMessage("输入链接")
 val image: String = selectMessages {
        has<PlainText> { "" }
}
subject.sendMessage(message.quote() )

这样写没有问题
 subject.sendMessage("输入链接")
 val image: String = selectMessages {
        "aaaa" { "" }
}
 subject.sendMessage(message.quote() )

```
ava.lang.ClassCastException: class net.mamoe.mirai.internal.message.OnlineMessageSourceFromGroupImpl cannot be cast to class net.mamoe.mirai.message.data.Image (net.mamoe.mirai.internal.message.OnlineMessageSourceFromGroupImpl and net.mamoe.mirai.message.data.Image are in unnamed module of loader 'app')
	at com.xiaolang.mirai.MenuTest$monitorMessageEvent$1$image$1$1.invoke(MenuTest.kt)
	at com.xiaolang.mirai.MenuTest$monitorMessageEvent$1$invokeSuspend$lambda-0$$inlined$has$2.invokeSuspend(MessageSubscribersBuilder.kt:327)
	at com.xiaolang.mirai.MenuTest$monitorMessageEvent$1$invokeSuspend$lambda-0$$inlined$has$2.invoke(MessageSubscribersBuilder.kt)
	at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invokeSuspend(messageSubscribersInternal.kt:27)
	at net.mamoe.mirai.internal.event.MessageSubscribersInternalKt$content$1.invoke(messageSubscribersInternal.kt)
	at com.xiaolang.mirai.MenuTest$monitorMessageEvent$1$invokeSuspend$$inlined$selectMessages$default$1$6.invokeSuspend(select.kt:603)
	at com.xiaolang.mirai.MenuTest$monitorMessageEvent$1$invokeSuspend$$inlined$selectMessages$default$1$6.invoke(select.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:431)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:49)
	at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:49)
	at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$3$invokeSuspend$$inlined$forEach0$lambda$1.invokeSuspend(InternalEventListeners.kt:148)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 版本
- mirai-core: `2.6.7`

**Comment by Him188** [comment]
与 #1223 相同，2.7-M1 即将发布
