### ISSUE TITLE
首次登录时报错 Exception in attached job "BotInitProcessor.init"

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1358]
报错信息
Exception in attached job "BotInitProcessor.init"
版本 Mirai 2.7-M1
注意——

1.不确定该错误是否来自mirai，但无法从错误信息看出是来自本项目(只有一人成功复现而且是鸿蒙系统)，所以先放上来看看。

2.据该用户反馈，三个新号三次尝试皆有此错误，但这个错误【只出现一次】

堆栈信息:
![69399b8fbcd61145](https://user-images.githubusercontent.com/63996691/122961052-9d35f600-d3b6-11eb-88ab-03d1cf8b1773.jpg)

**Comment by zhaodice** [comment]
Note: 错误产生时，登陆协议为phone

**Comment by zhaodice** [comment]
Note: 用户重新操作(卸载软件重装)后仍然重现了这个错误，但我并没有把mirai的缓存设为app的私有目录，这个也许是巧合，有待保留

**Comment by zhaodice** [comment]
Note: 当我要求用户从PHONE协议改成选择WATCH协议时，对方经过了一套复现流程后告诉我是正常的。

**Comment by zhaodice** [comment]
我更感兴趣的是，这是个没有捕获到的异常(正常情况下错误应该输出到控制台而不是直接让app闪退弹这种错误报告)

**Comment by Him188** [comment]
stacktrace 看不出来什么, 需要使用 `-Dkotlinx.coroutines.debug=on` 才能获得完整的 stacktrace (大幅损失性能)

**Comment by Him188** [comment]
提供一下网络日志

**Comment by zhaodice** [comment]
我已经在newBot下使用
redirectNetworkLogToFile(File(AppContext.zhaoDice + "/.MiraiCache_$protocol/LoginNetwork.log"))
并在程序初始化时使用了
System.setProperty("kotlinx.coroutines.debug","on")
接下来我重新复现一下试试

**Comment by zhaodice** [comment]
System.setProperty("kotlinx.coroutines.debug","on")
之后的stacktrace ：
![log](https://user-images.githubusercontent.com/63996691/123023025-46a5d780-d409-11eb-8371-5495f8dd6c59.jpg)

**Comment by zhaodice** [comment]
网络日志：

[0m2021-06-23 09:53:30 V/Net 1104287903: [BotSessionSyncer] Loading server list from cache.[0m
[92m2021-06-23 09:53:30 I/Net 1104287903: [ServerList] Server list: 36.155.229.147:8080, 111.30.181.201:14000, msfwifi.3g.qq.com:8080, 36.155.228.114:14000, 36.155.240.38:443, 120.232.19.197:80, 183.232.95.151:443, 111.30.178.182:80, 120.232.22.118:80, 111.30.181.249:80.[0m
[0m2021-06-23 09:53:30 V/Net 1104287903: Send: wtlogin.exchange_emp[0m
[0m2021-06-23 09:53:30 V/Net 1104287903: Recv: wtlogin.exchange_emp[0m
[0m2021-06-23 09:53:30 V/Net 1104287903: Send: StatSvc.register(online)[0m
[0m2021-06-23 09:53:30 V/Net 1104287903: Recv: StatSvc.register[0m
[92m2021-06-23 09:53:30 I/Net 1104287903: [MessageSvcSyncer] Syncing friend message history...[0m
[0m2021-06-23 09:53:30 V/Net 1104287903: [BotSessionSyncer] Loading BdhSession from cache file[0m
[92m2021-06-23 09:53:30 I/Net 1104287903: [ContactUpdater] Start loading friend list...[0m
[92m2021-06-23 09:53:30 I/Net 1104287903: [ContactUpdater] Start loading stranger list...[0m
[0m2021-06-23 09:53:30 V/Net 1104287903: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2021-06-23 09:53:30 V/Net 1104287903: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2021-06-23 09:53:30 V/Net 1104287903: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2021-06-23 09:53:30 V/Net 1104287903: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[0m2021-06-23 09:53:30 V/Net 1104287903: Recv: MessageSvc.PushForceOffline[0m
[91m2021-06-23 09:53:30 W/Net 1104287903: [BotInitProcessor] An exception was thrown during initialization process of Bot 1104287903. Trying to ignore the error and continue logging in...
java.util.concurrent.CancellationException: NetworkHandler closed
	at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
	at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:608)
	at kotlinx.coroutines.JobKt.cancel(Unknown Source:1)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.close(NetworkHandlerSupport.kt:56)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:41)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:79)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPushForceOffline.handle(MessageSvc.PushForceOffline.kt:35)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPushForceOffline.handle(MessageSvc.PushForceOffline.kt:25)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:108)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:40)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$1.invokeSuspend(NetworkHandlerSupport.kt:87)
	at (Coroutine boundary.()
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.sendAndExpect(NetworkHandlerSupport.kt:104)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect(SelectorNetworkHandler.kt:74)
	at net.mamoe.mirai.internal.MiraiImpl.getOnlineOtherClientsList$suspendImpl(MiraiImpl.kt:247)
	at net.mamoe.mirai.internal.network.components.OtherClientUpdaterImpl.update(OtherClientUpdater.kt:45)
	at net.mamoe.mirai.internal.network.components.BotInitProcessorImpl$init$2$2$1.invokeSuspend(BotInitProcessor.kt:83)
Caused by: java.util.concurrent.CancellationException: NetworkHandler closed
	at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
	at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:608)
	at kotlinx.coroutines.JobKt.cancel(Unknown Source:1)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.close(NetworkHandlerSupport.kt:56)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:41)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:79)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPushForceOffline.handle(MessageSvc.PushForceOffline.kt:35)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPushForceOffline.handle(MessageSvc.PushForceOffline.kt:25)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:108)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:40)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$1.invokeSuspend(NetworkHandlerSupport.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: net.mamoe.mirai.internal.network.impl.netty.ForceOfflineException: Closed by MessageSvc.PushForceOffline: net.mamoe.mirai.internal.network.protocol.data.jce.RequestPushForceOffline@3df8880
	... 11 more
[0m
[91m2021-06-23 09:53:30 W/Net 1104287903: [BotInitProcessor] An exception was thrown during initialization process of Bot 1104287903. Trying to ignore the error and continue logging in...
java.util.concurrent.CancellationException: NetworkHandler closed
	at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
	at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:608)
	at kotlinx.coroutines.JobKt.cancel(Unknown Source:1)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.close(NetworkHandlerSupport.kt:56)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:41)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:79)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPushForceOffline.handle(MessageSvc.PushForceOffline.kt:35)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPushForceOffline.handle(MessageSvc.PushForceOffline.kt:25)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:108)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:40)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$1.invokeSuspend(NetworkHandlerSupport.kt:87)
	at (Coroutine boundary.()
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.loadAll(ContactUpdater.kt:87)
	at net.mamoe.mirai.internal.network.components.BotInitProcessorImpl$init$2$2$2.invokeSuspend(BotInitProcessor.kt:84)
Caused by: java.util.concurrent.CancellationException: NetworkHandler closed
	at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
	at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:608)
	at kotlinx.coroutines.JobKt.cancel(Unknown Source:1)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.close(NetworkHandlerSupport.kt:56)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:41)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:79)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPushForceOffline.handle(MessageSvc.PushForceOffline.kt:35)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPushForceOffline.handle(MessageSvc.PushForceOffline.kt:25)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:108)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:40)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$1.invokeSuspend(NetworkHandlerSupport.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: net.mamoe.mirai.internal.network.impl.netty.ForceOfflineException: Closed by MessageSvc.PushForceOffline: net.mamoe.mirai.internal.network.protocol.data.jce.RequestPushForceOffline@3df8880
	... 11 more
[0m

**Comment by Him188** [comment]
> �[0m2021-06-23 09:53:30 V/Net 1104287903: Recv: MessageSvc.PushForceOffline�[0m

看日志发现是有被挤下线，应该是正常行为。有可能是 2.7-M1 在被挤下线时没有清空 session 缓存而无法重连，已经在 2.7-M2 修复
