### ISSUE TITLE
无穷滑动验证码

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1359]
简而言之，就是完成了滑动验证码后，我已经提供了正确的ticket，但就像取消了滑动验证码一样反复弹出验证

解决器相关代码：
override suspend fun onSolveSliderCaptcha(bot: Bot, url: String): String {
      if(context==null){
          bot.cancel()
          return ""
      }
      verificationResult = CompletableDeferred()
      this.url = url
      sendVerifyNotification()
      val ticket = verificationResult.await()
      Log.d("onSolveSliderCaptcha","URL=$url ticket=$ticket")
      return ticket
}
Log.d日志：
D/onSolveSliderCaptcha: URL=https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=484546762&sid=7578391734385810931&cap_cd=YSbSthiT1Tc_9H7xbOMkMQ8DZB-lpWCL_Ohi0RJ6BEkDo22twQTzGw**&clientype=1&apptype=2 ticket=t038AbktBycvxHZlJ8-0VssIJRxXgY_QPbYWPjIKr35UEKJXcYD55npN9xCyeM0nHtGeRAhKdJZ8oNDyEj5Ngw_qD4wdGKATyAPcyD2uwud4aw9fzoGgHdh8rM5oFLs0pZH

**Comment by zhaodice** [comment]
网络日志：

[0m2021-06-23 10:35:33 V/Net 484546762: [BotSessionSyncer] No server list cached.[0m
[0m2021-06-23 10:35:33 V/Net 484546762: Send: wtlogin.login[0m
[0m2021-06-23 10:35:33 V/Net 484546762: Recv: wtlogin.login[0m
[0m2021-06-23 10:35:45 V/Net 484546762: Send: wtlogin.login[0m
[0m2021-06-23 10:35:45 V/Net 484546762: Recv: wtlogin.login[0m
[91m2021-06-23 10:35:45 W/Net 484546762: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(484546762), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(484546762), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:247)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
[0m2021-06-23 10:35:45 V/Net 484546762: [BotSessionSyncer] No server list cached.[0m
[0m2021-06-23 10:35:45 V/Net 484546762: Send: wtlogin.login[0m
[0m2021-06-23 10:35:46 V/Net 484546762: Recv: wtlogin.login[0m

**Comment by zhaodice** [comment]
猜测是因为”WrongPasswordException“仍然继续尝试登陆对吧？
但WrongPasswordException包含”当前上网环境异常“这种情况
导致你不断重试登陆，就会无穷的滑块验证码，无法终止，周而复始生生不息（？

**Comment by zhaodice** [comment]
是否考虑将 ”当前上网环境异常“列为其他的Exception？比如DistrustedNetworkException

**Comment by Karlatemp** [comment]
#1352

**Comment by zhaodice** [comment]
> 
> 
> #1352

但这边的测试是，无穷地弹出验证码，滑动了一次又一次，根本停不下来X

**Comment by Karlatemp** [comment]
很有可能是你没有严格按照滑动验证码的手册来解决，或者你尝试在服务器上解决验证码

**Comment by zhaodice** [comment]
> 
> 
> 很有可能是你没有严格按照滑动验证码的手册来解决，或者你尝试在服务器上解决验证码

经过换包测试，以前的版本（Mirai2.6.6）是没问题的，这个问题是升级到（Mirai2.7-M1）才遇到的，是滑动验证码手册有变化了吗？

**Comment by zhaodice** [comment]
测试结果 

Mirai 2.6.6 ：滑动验证码之后，会被”当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。“中断
Mirai 2.7-M1：无穷无尽的滑动验证码

**Comment by Karlatemp** [comment]
Caused by #1352

**Comment by Karlatemp** [comment]
`2.7-M2-dev-1`
