### ISSUE TITLE
QQ 其他用户拉群登陆的机器人QQ进群报错，机器人也无法收到此群消息

### ISSUE THREAD

**Issue by JackMyCode** [mamoe/mirai#1360]
项目使用 java11 +  mirai-core-jvm （2.7-M1-dev-5） 

2021-06-23 16:27:59 E/Net 1429984992: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 10000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
	at java.base/java.lang.Thread.run(Thread.java:834)

2021-06-23 16:27:59 E/Net 1429984992: ExceptionInPacketHandlerException(packetHandler=CallPacketFactoryPacketHandler, cause=java.lang.NullPointerException)
ExceptionInPacketHandlerException(packetHandler=CallPacketFactoryPacketHandler, cause=java.lang.NullPointerException)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:41)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$1.invokeSuspend(NetworkHandlerSupport.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NullPointerException
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg.handle(MessageSvc.PbGetMsg.kt:201)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg.handle(MessageSvc.PbGetMsg.kt:69)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:104)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:39)
	... 7 more

2021-06-23 16:27:59 V/Net 1429984992: Send: ProfileService.Pb.ReqSystemMsgNew.Group
2021-06-23 16:27:59 V/Net 1429984992: Recv: friendlist.GetTroopListReqV2
2021-06-23 16:27:59 V/Net 1429984992: Recv: friendlist.GetTroopListReqV2
2021-06-23 16:28:00 V/Net 1429984992: Recv: friendlist.GetTroopListReqV2
2021-06-23 16:28:00 E/Bot 1429984992: java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=0, groupMsgType=8 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并尽量描述此时机器人是否正被邀请加入群, 或者是有有新群员加入此群 调试信息: SystemMsg#1319368091 {
            actionUin=0x0000000000000000(0)
            actionUinQqNick=雷鸣
            actions=[]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x000000002E5FFF1C(778043164)
            groupExtFlag=0x40230440(1076036672)
            groupInfo=GroupInfo#1232671744 {
                    groupAuthType=0x00007F77(32631)
            }
            groupMsgType=0x00000008(8)
            groupName=这一年、雷鸣
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%req_uin%
            msgDescribe=已被群主解散
            msgTitle=验证消息
            reqUinAge=0x0000001C(28)
            reqUinNick=雷鸣
    }
java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=0, groupMsgType=8 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并尽量描述此时机器人是否正被邀请加入群, 或者是有有新群员加入此群 调试信息: SystemMsg#1319368091 {
            actionUin=0x0000000000000000(0)
            actionUinQqNick=雷鸣
            actions=[]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x000000002E5FFF1C(778043164)
            groupExtFlag=0x40230440(1076036672)
            groupInfo=GroupInfo#1232671744 {
                    groupAuthType=0x00007F77(32631)
            }
            groupMsgType=0x00000008(8)
            groupName=这一年、雷鸣
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%req_uin%
            msgDescribe=已被群主解散
            msgTitle=验证消息
            reqUinAge=0x0000001C(28)
            reqUinNick=雷鸣
    }
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:23)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:21)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup$decode$2.invoke(NewContact.kt:242)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:265)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:361)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:135)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:62)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl(Channels.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Him188** [comment]
确认是邀请入群？日志里是解散

**Comment by JackMyCode** [comment]
确认是邀请用户入群，前面显示的日志消息是
2021-06-24 08:34:52 V/Net 1429984992: Recv: MessageSvc.PushNotify
2021-06-24 08:34:52 V/Net 1429984992: Recv: MessageSvc.PushNotify
2021-06-24 08:34:52 V/Net 1429984992: Send: friendlist.GetTroopListReqV2
2021-06-24 08:35:02 V/Net 1429984992: Send: friendlist.GetTroopListReqV2
2021-06-24 08:35:02 V/Net 1429984992: Send: friendlist.GetTroopListReqV2
2021-06-24 08:35:02 V/Net 1429984992: Send: friendlist.GetTroopListReqV2
2021-06-24 08:35:02 V/Net 1429984992: Send: friendlist.GetTroopListReqV2
然后就是类似下面那个日志了

**Comment by JackMyCode** [comment]
我这边通过切换 mirai-core-jvm 版本 2.7-M1-dev-5 -> 2.6.7  可以了
