### ISSUE TITLE
`unwrap` 在 Android 导致 OOM

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1404]
```
I/art: Background partial concurrent mark sweep GC freed 31320(1485KB) AllocSpace objects, 1(20KB) LOS objects, 9% free, 39MB/43MB, paused 3.043ms total 155.060ms
I/art: Background sticky concurrent mark sweep GC freed 19860(885KB) AllocSpace objects, 0(0B) LOS objects, 1% free, 43MB/43MB, paused 6.498ms total 63.320ms
I/art: Background sticky concurrent mark sweep GC freed 7305(325KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 43MB/43MB, paused 5.839ms total 42.702ms
I/art: Background partial concurrent mark sweep GC freed 70134(2MB) AllocSpace objects, 0(0B) LOS objects, 8% free, 43MB/47MB, paused 8.756ms total 201.277ms
I/art: Background sticky concurrent mark sweep GC freed 20176(902KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/47MB, paused 5.974ms total 67.212ms
I/art: Background sticky concurrent mark sweep GC freed 6931(309KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 47MB/47MB, paused 5.699ms total 47.034ms
I/art: Background partial concurrent mark sweep GC freed 191286(6MB) AllocSpace objects, 0(0B) LOS objects, 8% free, 44MB/48MB, paused 7.109ms total 219.448ms
I/art: WaitForGcToComplete blocked for 29.086ms for cause HeapTrim
D/MiraiConsole: [AccountSecretsManager] Loaded account secrets from local cache.
I/art: Note: end time exceeds epoch: 
D/MiraiConsole: [CDS][DNS] getAllByNameImpl netId = 0
D/libc-netbsd: [getaddrinfo]: hostname=203.205.255.221; servname=(null); cache_mode=(null), netid=0; mark=0
    [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
D/MiraiConsole: [CDS]connect[/203.205.255.221:8080]
D/Posix: [Posix_connect Debug]Process org.mirai.zhao.dice :8080 
D/MiraiConsole: [CDS]close[0]
    close [socket][/0.0.0.0:-1]
D/MiraiConsole: Bot cancelled: Bot closed
I/art: Background partial concurrent mark sweep GC freed 225414(28MB) AllocSpace objects, 6(30MB) LOS objects, 4% free, 88MB/92MB, paused 5.608ms total 200.185ms
I/art: Background sticky concurrent mark sweep GC freed 21847(10MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 86MB/88MB, paused 6.222ms total 30.097ms
I/art: Background sticky concurrent mark sweep GC freed 8337(5MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 85MB/87MB, paused 6.804ms total 27.529ms
I/art: Background sticky concurrent mark sweep GC freed 6824(4MB) AllocSpace objects, 0(0B) LOS objects, 1% free, 85MB/87MB, paused 6.919ms total 29.714ms
W/art: No such thread id for suspend: 76
W/art: No such thread id for suspend: 80
I/art: Background sticky concurrent mark sweep GC freed 6761(3MB) AllocSpace objects, 0(0B) LOS objects, 0% free, 122MB/122MB, paused 7.081ms total 59.228ms
I/art: Background partial concurrent mark sweep GC freed 78735(36MB) AllocSpace objects, 2(41MB) LOS objects, 2% free, 147MB/151MB, paused 8.935ms total 221.209ms
I/art: Background sticky concurrent mark sweep GC freed 20927(14MB) AllocSpace objects, 0(0B) LOS objects, 0% free, 223MB/223MB, paused 9.569ms total 106.246ms
I/art: Background partial concurrent mark sweep GC freed 35708(33MB) AllocSpace objects, 2(92MB) LOS objects, 2% free, 129MB/133MB, paused 10.985ms total 202.846ms
I/art: WaitForGcToComplete blocked for 126.940ms for cause Alloc
I/art: WaitForGcToComplete blocked for 74.158ms for cause Alloc
I/art: WaitForGcToComplete blocked for 74.190ms for cause Alloc
I/art: WaitForGcToComplete blocked for 74.193ms for cause Alloc
I/art: WaitForGcToComplete blocked for 74.276ms for cause Alloc
I/art: WaitForGcToComplete blocked for 74.283ms for cause Alloc
I/art: WaitForGcToComplete blocked for 73.962ms for cause Alloc
I/art: WaitForGcToComplete blocked for 74.032ms for cause Alloc
I/art: WaitForGcToComplete blocked for 73.523ms for cause Alloc
I/art: WaitForGcToComplete blocked for 73.117ms for cause Alloc
I/art: WaitForGcToComplete blocked for 63.824ms for cause Alloc
I/art: WaitForGcToComplete blocked for 63.858ms for cause Alloc
I/art: WaitForGcToComplete blocked for 63.876ms for cause Alloc
I/art: WaitForGcToComplete blocked for 63.892ms for cause Alloc
I/art: WaitForGcToComplete blocked for 63.850ms for cause Alloc
I/art: WaitForGcToComplete blocked for 63.877ms for cause Alloc
I/art: WaitForGcToComplete blocked for 63.896ms for cause Alloc
I/art: Background sticky concurrent mark sweep GC freed 4294(5MB) AllocSpace objects, 0(0B) LOS objects, 1% free, 131MB/133MB, paused 11.273ms total 40.716ms
I/art: Background partial concurrent mark sweep GC freed 11374(13MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 131MB/135MB, paused 11.344ms total 174.109ms
I/art: WaitForGcToComplete blocked for 126.147ms for cause Alloc
I/art: Background sticky concurrent mark sweep GC freed 197(123KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 255MB/255MB, paused 11.422ms total 144.374ms
I/art: WaitForGcToComplete blocked for 26.669ms for cause Alloc
I/art: Background partial concurrent mark sweep GC freed 288(133KB) AllocSpace objects, 1(83MB) LOS objects, 2% free, 172MB/176MB, paused 11.479ms total 184.244ms
I/art: WaitForGcToComplete blocked for 184.117ms for cause Alloc
I/art: WaitForGcToComplete blocked for 49.144ms for cause Alloc
I/art: WaitForGcToComplete blocked for 49.173ms for cause Alloc
I/art: WaitForGcToComplete blocked for 49.346ms for cause Alloc
I/art: WaitForGcToComplete blocked for 49.383ms for cause Alloc
I/art: Background sticky concurrent mark sweep GC freed 4089(4MB) AllocSpace objects, 0(0B) LOS objects, 1% free, 174MB/176MB, paused 11.697ms total 41.921ms
I/art: Background partial concurrent mark sweep GC freed 32550(39MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 181MB/185MB, paused 12.894ms total 209.280ms
I/art: Background sticky concurrent mark sweep GC freed 8846(10MB) AllocSpace objects, 0(0B) LOS objects, 1% free, 177MB/179MB, paused 13.096ms total 51.276ms
I/art: Background sticky concurrent mark sweep GC freed 4129(5MB) AllocSpace objects, 0(0B) LOS objects, 1% free, 177MB/179MB, paused 13.376ms total 47.497ms
I/art: Background partial concurrent mark sweep GC freed 13691(16MB) AllocSpace objects, 0(0B) LOS objects, 2% free, 176MB/180MB, paused 13.714ms total 185.850ms
I/art: WaitForGcToComplete blocked for 118.175ms for cause Alloc
I/art: Alloc sticky concurrent mark sweep GC freed 387(14KB) AllocSpace objects, 0(0B) LOS objects, 1% free, 176MB/178MB, paused 13.852ms total 45.139ms
I/art: Alloc partial concurrent mark sweep GC freed 919(426KB) AllocSpace objects, 0(0B) LOS objects, 2% free, 176MB/180MB, paused 13.481ms total 171.556ms
I/art: Alloc concurrent mark sweep GC freed 23(13KB) AllocSpace objects, 0(0B) LOS objects, 2% free, 176MB/180MB, paused 13.543ms total 185.690ms
    Forcing collection of SoftReferences for 187MB allocation
I/art: Alloc concurrent mark sweep GC freed 13(416B) AllocSpace objects, 0(0B) LOS objects, 2% free, 176MB/180MB, paused 13.420ms total 184.373ms
E/art: Throwing OutOfMemoryError "Failed to allocate a 196358710 byte allocation with 4194208 free bytes and 79MB until OOM"
I/art: Alloc sticky concurrent mark sweep GC freed 4(24KB) AllocSpace objects, 1(24KB) LOS objects, 1% free, 176MB/178MB, paused 13.584ms total 44.735ms
I/art: Alloc partial concurrent mark sweep GC freed 10(256B) AllocSpace objects, 0(0B) LOS objects, 2% free, 176MB/180MB, paused 14.368ms total 172.610ms
I/art: Alloc concurrent mark sweep GC freed 30(928B) AllocSpace objects, 0(0B) LOS objects, 2% free, 176MB/180MB, paused 13.816ms total 188.433ms
    Forcing collection of SoftReferences for 187MB allocation
I/art: Alloc concurrent mark sweep GC freed 14(432B) AllocSpace objects, 0(0B) LOS objects, 2% free, 176MB/180MB, paused 13.815ms total 185.686ms
E/art: Throwing OutOfMemoryError "Failed to allocate a 196358710 byte allocation with 4194304 free bytes and 79MB until OOM"
E/CustomActivityOnCrash: App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
    java.lang.OutOfMemoryError: Failed to allocate a 196358710 byte allocation with 4194304 free bytes and 79MB until OOM
        at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
        at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:125)
        at java.lang.StringBuffer.append(StringBuffer.java:278)
        at java.io.StringWriter.write(StringWriter.java:123)
        at java.io.PrintWriter.doWrite(PrintWriter.java:623)
        at java.io.PrintWriter.write(PrintWriter.java:601)
        at java.io.PrintWriter.write(PrintWriter.java:579)
        at java.io.PrintWriter.write(PrintWriter.java:660)
        at java.io.PrintWriter.append(PrintWriter.java:722)
        at java.io.PrintWriter.append(PrintWriter.java:691)
        at java.io.PrintWriter.append(PrintWriter.java:31)
        at java.lang.Throwable.printStackTrace(Throwable.java:322)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
        at java.lang.Throwable.printStackTrace(Throwable.java:341)
        at java.lang.Throwable.printStackTrace(Throwable.java:349)
    	at java.lang.Throwable.printStackTrace(Th
I/Process: Sending signal. PID: 29549 SIG: 9
```

我不确定是不是我的问题，因为这个堆栈爆的太严重了，我没办法看最后面是什么样子...
所以目前来说暂不以BUG形式反馈，就当一个开发问题来问一下，来求助这个最有可能是什么原因。

**Comment by zhaodice** [comment]
注意到只在
```
at java.lang.Throwable.printStackTrace(Throwable.java:341)
at java.lang.Throwable.printStackTrace(Throwable.java:349)
```
这两个语句之间来回踢皮球，到底发生了什么，不太清楚...

**Comment by zhaodice** [comment]
```
try {
    bot.login()
} catch (e: Throwable) {
    e.stackTraceToString() //似乎根源在这里，只要在断网情况下catch了bot的登陆异常并stackTraceToString() 就会无穷循环堆栈
}
```

**Comment by zhaodice** [comment]
![1](https://user-images.githubusercontent.com/63996691/124919301-a5359d00-e028-11eb-87dc-83a3a22e4fb2.PNG)
![2](https://user-images.githubusercontent.com/63996691/124919315-a8c92400-e028-11eb-9917-0f9863e04023.PNG)
![3](https://user-images.githubusercontent.com/63996691/124919367-be3e4e00-e028-11eb-92d9-aa6d1a3efa3a.PNG)
DEBUG 调试情况

**Comment by sandtechnology** [comment]
我觉得你应该看看这个异常是什么 应该是打印异常时出现了一个异常 如此循环导致的

**Comment by zhaodice** [comment]
> 
> 
> 我觉得你应该看看这个异常是什么 应该是打印异常时出现了一个异常 如此循环导致的

```
try {
bot.login()
} catch (e: Throwable) {
}
```
其中e这个异常是：
`Attempt to invoke virtual method 'java.lang.Object java.lang.StackTraceElement[].clone()' on a null object reference`

当我试图`e.stackTraceToString()`（反正统一就这样了），就直接爆内存了...

**Comment by zhaodice** [comment]
我经过调试，确认是进了 `bot.login()` catch出来的 e，然后 `e.stackTraceToString()` 之后再也出不来了

**Comment by sandtechnology** [comment]
那就是异常本身的StackTrace是null 导致死循环打印异常 不知道什么原因导致的

**Comment by zhaodice** [comment]
> 
> 
> 那就是异常本身的StackTrace是null 导致死循环打印异常 不知道什么原因导致的

这个异常是手机断网的情况下进行 bot.login() 时抛的

**Comment by zhaodice** [comment]
```
detailMessage = "Attempt to invoke virtual method 'java.lang.Object java.lang.StackTraceElement[].clone()' on a null object reference"
cause = {NullPointerException@9620} "java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.StackTraceElement[].clone()' on a null object reference"
stackState = null
stackTrace = {StackTraceElement[15]@9622} 
 0 = {StackTraceElement@10434} "net.mamoe.mirai.utils.ExceptionCollector.hash(ExceptionCollector.kt:50)"
 1 = {StackTraceElement@10435} "net.mamoe.mirai.utils.ExceptionCollector.collect(ExceptionCollector.kt:41)"
 2 = {StackTraceElement@10436} "net.mamoe.mirai.utils.ExceptionCollector.collectException(ExceptionCollector.kt:68)"
 3 = {StackTraceElement@10437} "net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector$AwaitResumeInstance.runImpl(AbstractKeepAliveNetworkHandlerSelector.kt:132)"
 4 = {StackTraceElement@10438} "net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector$AwaitResumeInstance.access$runImpl(AbstractKeepAliveNetworkHandlerSelector.kt:63)"
 5 = {StackTraceElement@10439} "net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector$AwaitResumeInstance$runImpl$1.invokeSuspend(AbstractKeepAliveNetworkHandlerSelector.kt)"
 6 = {StackTraceElement@10440} "kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)"
 7 = {StackTraceElement@10441} "kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)"
 8 = {StackTraceElement@10442} "kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)"
 9 = {StackTraceElement@10443} "kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)"
 10 = {StackTraceElement@10444} "kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)"
 11 = {StackTraceElement@10445} "kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)"
 12 = {StackTraceElement@10446} "kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)"
 13 = {StackTraceElement@10447} "kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)"
 14 = {StackTraceElement@10448} "zhao.dice.plugin.MiraiPluginLoader$onEnable$1$1.run(MiraiPluginLoader.kt:235)"
```

这是我拷贝的内存信息

**Comment by zhaodice** [comment]
我觉得，mirai在bot.login()的时候抛出 `java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.StackTraceElement[].clone()' on a null object reference` ，不管出于什么原因，这不是正常的异常。

**Comment by zhaodice** [comment]
问题可能出在 ExceptionCollector.kt:50
```
private fun hash(e: Throwable): Long {
        return e.stackTrace.fold(0L) { acc, stackTraceElement ->
            acc * 31 + hash(stackTraceElement).toLongUnsigned()
        }
    }
```
在处理这个异常的时候又抛出了异常。

**Comment by Him188** [comment]
问题应该是 Android 的 `printStacktrace` 没有处理循环引用情况，无限递归申请内存。解决方案是把 `Throwable.unwrap` 改为 MPP 实现并在 Android 目标避免 `addSuppressed`
