### ISSUE TITLE
群聊中群主或者管理员踢人时，Bot会报错

### ISSUE THREAD

**Issue by BigfootACA** [mamoe/mirai#1406]
群主或者管理员踢人时，Bot会报错
（环境：1500人左右的群，Bot同为管理员）

```
2021-07-10 11:07:43 V/Bot 3242583877: Event: MemberCardChangeEvent(origin=, new=寒芒, member=NormalMember(924941499))
2021-07-10 11:07:43 V/Bot 3242583877: [Renegade-Project_OffTopic(697666196)] 寒芒(924941499) -> 教兄弟们免费领取4Q币，有时间的可以得到更多，下载app【一淘】，进入APP搜索dnf找便宜的Q币买，有两张优惠券，有空填写一下我的邀请码是ZNAIG，谢谢大家，不懂操作的私信我
2021-07-10 11:07:43 V/Net 3242583877: Send: MessageSvc.PbSendMsg
2021-07-10 11:07:44 V/Net 3242583877: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-07-10 11:07:44 V/Bot 3242583877: Group(697666196) <- [mirai:at:924941499] 请根据昵称+机型修改名片
2021-07-10 11:07:57 V/Bot 3242583877: [Renegade-Project_OffTopic(697666196)] 寒芒(924941499) -> [mirai:image:{ED18E29A-EBFB-1BCA-3F44-739FB97B7B41}.jpg]
2021-07-10 11:07:57 I/Bot 3242583877: saved image {ED18E29A-EBFB-1BCA-3F44-739FB97B7B41}.jpg(image/jpeg) length 162145 wrote 162145
2021-07-10 11:07:58 V/Bot 3242583877: [Renegade-Project_OffTopic(697666196)] 寒芒(924941499) -> [mirai:image:{14447E26-7B25-6AA6-7941-0134D30FD050}.jpg]
2021-07-10 11:07:58 I/Bot 3242583877: saved image {14447E26-7B25-6AA6-7941-0134D30FD050}.jpg(image/jpeg) length 101121 wrote 101121
2021-07-10 11:08:01 V/Bot 3242583877: [Renegade-Project_OffTopic(697666196)] 寒芒(924941499) -> 好的
2021-07-10 11:08:04 V/Bot 3242583877: [Renegade-Project_OffTopic(697666196)] MRCX lgg7-950xl-隔壁树莓派(396477694) -> 能显示，但是效果比较差
2021-07-10 11:08:06 V/Bot 3242583877: [Renegade-Project_OffTopic(697666196)] 1+6t-如青桑(1666633887) -> 爬
2021-07-10 11:08:19 V/Bot 3242583877: Event: MemberLeaveEvent.Kick(member=924941499, operator=859220819)
2021-07-10 11:08:19 V/Net 3242583877: Send: OnlinePush.RespPush
2021-07-10 11:08:28 V/Net 3242583877: Send: OnlinePush.RespPush
2021-07-10 11:08:29 V/Net 3242583877: Send: OnlinePush.RespPush
2021-07-10 11:08:30 V/Bot 3242583877: [Renegade-Project_OffTopic(697666196)] MRCX lgg7-950xl-隔壁树莓派(396477694) -> 分辨率和刷新率受限，而且需要驱动
2021-07-10 11:08:33 V/Net 3242583877: Send: OnlinePush.RespPush
2021-07-10 11:08:34 V/Net 3242583877: Send: Heartbeat.Alive
2021-07-10 11:08:34 V/Net 3242583877: Recv: Heartbeat.Alive.Response
2021-07-10 11:08:37 V/Net 3242583877: Send: OnlinePush.RespPush
2021-07-10 11:08:38 V/Net 3242583877: Send: OnlinePush.RespPush
2021-07-10 11:08:41 V/Net 3242583877: Send: OnlinePush.RespPush
2021-07-10 11:08:45 V/Net 3242583877: Send: OnlinePush.RespPush
2021-07-10 11:09:02 V/Net 3242583877: Send: OnlinePush.RespPush
2021-07-10 11:09:02 V/Net 3242583877: Recv: RequestPushNotify(uin=3242583877, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=33, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@4d750fe)
2021-07-10 11:09:02 V/Net 3242583877: Send: MessageSvc.PbGetMsg
2021-07-10 11:09:02 V/Net 3242583877: Send: MessageSvc.PbDeleteMsg
2021-07-10 11:09:02 V/Net 3242583877: Send: MessageSvc.PbGetMsg
2021-07-10 11:09:02 V/Net 3242583877: Send: MessageSvc.PbDeleteMsg
2021-07-10 11:09:02 V/Bot 3242583877: Event: MemberJoinEvent.Active(member=2270057439)
2021-07-10 11:09:02 I/Bot 3242583877: found 火花(2270057439) join
2021-07-10 11:09:02 V/Net 3242583877: Send: MessageSvc.PbSendMsg
2021-07-10 11:09:02 V/Net 3242583877: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-07-10 11:09:02 V/Bot 3242583877: Group(697666196) <- [mirai:at:2270057439]\n欢迎入群，入群后请及时修改名片，也可以问我问题\n常见问题解答：https://forum.renegade-project.org/t/topic/62
2021-07-10 11:09:02 V/Net 3242583877: Send: MessageSvc.PbGetMsg
2021-07-10 11:09:02 V/Net 3242583877: Send: MessageSvc.PbDeleteMsg
2021-07-10 11:09:02 V/Net 3242583877: Send: MessageSvc.PbGetMsg
2021-07-10 11:09:02 V/Net 3242583877: Send: MessageSvc.PbDeleteMsg
2021-07-10 11:09:10 V/Net 3242583877: Send: OnlinePush.RespPush
2021-07-10 11:09:22 V/Net 3242583877: Recv: RequestPushNotify(uin=3242583877, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=84, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@221693e0)
2021-07-10 11:09:22 V/Net 3242583877: Send: MessageSvc.PbGetMsg
2021-07-10 11:09:22 V/Net 3242583877: Send: MessageSvc.PbDeleteMsg
2021-07-10 11:09:22 V/Net 3242583877: Send: MessageSvc.PbGetMsg
2021-07-10 11:09:22 V/Net 3242583877: Send: MessageSvc.PbDeleteMsg
2021-07-10 11:09:22 V/Net 3242583877: Send: ProfileService.Pb.ReqSystemMsgNew.Group
2021-07-10 11:09:22 V/Net 3242583877: Send: MessageSvc.PbGetMsg
2021-07-10 11:09:22 V/Net 3242583877: Send: MessageSvc.PbDeleteMsg
2021-07-10 11:09:22 V/Net 3242583877: Send: MessageSvc.PbGetMsg
2021-07-10 11:09:23 V/Net 3242583877: Send: MessageSvc.PbDeleteMsg
2021-07-10 11:09:23 V/Bot 3242583877: Event: MemberJoinRequestEvent(bot=Bot(3242583877), eventId=1625886562470685, message=问题：UEFI英文全称是?\n答案：unified extensible firmware interface, fromId=2428275894, groupId=697666196, groupName=Renegade-Project_OffTopic, fromNick=明, invitorId=null)
2021-07-10 11:09:23 I/Bot 3242583877: 明(2428275894) success because (none)
2021-07-10 11:09:23 V/Net 3242583877: Send: ProfileService.Pb.ReqSystemMsgAction.Group
2021-07-10 11:09:23 E/Bot 3242583877: java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=6 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#2097727138 {
            actionUin=0x000000003336AB53(859220819)
            actionUinNick=小太阳
            actionUinQqNick=小太阳ACA
            actionUinRemark=小太阳
            actions=[]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x0000000029958A94(697666196)
            groupExtFlag=0x002500E0(2425056)
            groupFlagext3=0x60002080(1610621056)
            groupInfo=GroupInfo#1704199624 {
                    appPrivilegeFlag=0x000980D1(622801)
                    msgOtherAdminDone=其他管理员
            }
            groupMsgType=0x00000006(6)
            groupName=Renegade-Project_OffTopic
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%action_uin%
            msgDescribe=已将 %req_uin% 移出群
            msgTitle=退群消息
            reqUinAge=0x0000001B(27)
            reqUinFaceid=0x00005B02(23298)
            reqUinNick=寒芒
            subType=0x00000005(5)
    }
java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=6 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#2097727138 {
            actionUin=0x000000003336AB53(859220819)
            actionUinNick=小太阳
            actionUinQqNick=小太阳ACA
            actionUinRemark=小太阳
            actions=[]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x0000000029958A94(697666196)
            groupExtFlag=0x002500E0(2425056)
            groupFlagext3=0x60002080(1610621056)
            groupInfo=GroupInfo#1704199624 {
                    appPrivilegeFlag=0x000980D1(622801)
                    msgOtherAdminDone=其他管理员
            }
            groupMsgType=0x00000006(6)
            groupName=Renegade-Project_OffTopic
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%action_uin%
            msgDescribe=已将 %req_uin% 移出群
            msgTitle=退群消息
            reqUinAge=0x0000001B(27)
            reqUinFaceid=0x00005B02(23298)
            reqUinNick=寒芒
            subType=0x00000005(5)
    }
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:23)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup$decode$2.invoke(NewContact.kt:233)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:265)
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:526)
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:247)
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:593)
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:588)
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:570)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-07-10 11:09:23 V/Net 3242583877: Recv: MultiPacketByIterable
2021-07-10 11:09:23 V/Net 3242583877: Send: OnlinePush.RespPush
2021-07-10 11:09:23 D/Net 3242583877: Received unknown commandName: ProfileService.Pb.ReqSystemMsgAction.Group
2021-07-10 11:09:23 V/Net 3242583877: Recv: RequestPushNotify(uin=3242583877, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=33, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@5d1f10e9)
2021-07-10 11:09:23 V/Net 3242583877: Send: MessageSvc.PbGetMsg
2021-07-10 11:09:23 V/Net 3242583877: Send: MessageSvc.PbDeleteMsg
2021-07-10 11:09:23 V/Net 3242583877: Send: MessageSvc.PbGetMsg
2021-07-10 11:09:23 V/Net 3242583877: Send: MessageSvc.PbDeleteMsg
2021-07-10 11:09:23 V/Bot 3242583877: Event: MemberJoinEvent.Active(member=2428275894)
2021-07-10 11:09:23 I/Bot 3242583877: found 明(2428275894) join
2021-07-10 11:09:23 V/Net 3242583877: Send: MessageSvc.PbSendMsg
2021-07-10 11:09:23 V/Net 3242583877: Recv: MessageSvcPbSendMsg.Response.SUCCESS
2021-07-10 11:09:23 V/Bot 3242583877: Group(697666196) <- [mirai:at:2428275894]\n欢迎入群，入群后请及时修改名片，也可以问我问题\n常见问题解答：https://forum.renegade-project.org/t/topic/62

```

#### 复现

QQ群踢人

#### 版本及相关选项选择

- mirai-core: `2.6.7` 
- bot-protocol: `ANDROID_PHONE`

**Comment by BigfootACA** [comment]
测试了一下，取消管理员也会出现类似问题
```
2021-07-11 17:33:35 V/Net 3242583877: Send: ProfileService.Pb.ReqSystemMsgAction.Group
2021-07-11 17:33:35 E/Bot 3242583877: java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=15 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#1225934900 {
            actionUin=0x000000003C699E8D(1013554829)
            actionUinNick=Sophon
            actionUinQqNick=Sophon
            actions=[]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x000000002DA9294E(766060878)
            groupExtFlag=0x002504E0(2426080)
            groupInfo=GroupInfo#993998036 {
                    appPrivilegeFlag=0x000980D0(622800)
            }
            groupMsgType=0x0000000F(15)
            groupName=NEXET&Renegade Unfuckable Server
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%action_uin%
            msgDescribe=已取消你的管理员身份
            msgTitle=管理员设置
            reqUinAge=0x00000016(22)
            reqUinFaceid=0x00000A02(2562)
            reqUinNick=BigfootBot
            subType=0x00000005(5)
    }
java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=15 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#1225934900 {
            actionUin=0x000000003C699E8D(1013554829)
            actionUinNick=Sophon
            actionUinQqNick=Sophon
            actions=[]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x000000002DA9294E(766060878)
            groupExtFlag=0x002504E0(2426080)
            groupInfo=GroupInfo#993998036 {
                    appPrivilegeFlag=0x000980D0(622800)
            }
            groupMsgType=0x0000000F(15)
            groupName=NEXET&Renegade Unfuckable Server
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%action_uin%
            msgDescribe=已取消你的管理员身份
            msgTitle=管理员设置
            reqUinAge=0x00000016(22)
            reqUinFaceid=0x00000A02(2562)
            reqUinNick=BigfootBot
            subType=0x00000005(5)
    }
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:23)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup$decode$2.invoke(NewContact.kt:233)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:265)
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:526)
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:247)
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:593)
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:588)
	at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:570)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-07-11 17:33:35 V/Net 3242583877: Recv: MultiPacketByIterable
2021-07-11 17:33:35 V/Net 3242583877: Recv: RequestPushNotify(uin=3242583877, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=33, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@3cc6b2e7)
2021-07-11 17:33:35 V/Net 3242583877: Send: MessageSvc.PbGetMsg
```

**Comment by Him188** [comment]
与 #1171 重复
