### ISSUE TITLE
On Android: java.io.FileNotFoundException: /proc/sys/kernel/random/boot_id (Permission denied)

### ISSUE THREAD

**Issue by Freedom0925** [mamoe/mirai#141]
java.io.FileNotFoundException: /proc/sys/kernel/random/boot_id (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at net.mamoe.mirai.utils.SystemDeviceInfo.getBootId(SystemDeviceInfo.kt:160)
        at net.mamoe.mirai.utils.DeviceInfo.generateDeviceInfoData(DeviceInfo.kt:81)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.login.WtLogin$Login$SubCommand9$invoke$$inlined$buildLoginOutgoingPacket$lambda$2.invoke(WtLogin.kt:179)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.login.WtLogin$Login$SubCommand9$invoke$$inlined$buildLoginOutgoingPacket$lambda$2.invoke(WtLogin.kt:126)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.EncryptMethodECDH$DefaultImpls.makeBody(EncryptMethod.kt:103)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.EncryptMethodECDH135.makeBody-impl(EncryptMethod.kt:56)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.EncryptMethodECDH135.makeBody(EncryptMethod.kt:1)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.OutgoingPacketAndroidKt.writeOicqRequestPacket(OutgoingPacketAndroid.kt:243)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.login.WtLogin$Login$SubCommand9.invoke(WtLogin.kt:135)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.relogin(QQAndroidBotNetworkHandler.kt:127)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$relogin$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Him188** [comment]
需要在 `SystemDeviceInfo` 里面catch

**Comment by tghjnjvg** [comment]
一般登陆需要写验证码 有写登陆获取验证码的相关代码吗

**Comment by Him188** [comment]
有，看`BotConfiguration`
