### ISSUE TITLE
发送有图片的群消息时，sendMessage()函数返回后立刻获取sourceId将导致IllegalStateException

### ISSUE THREAD

**Issue by kenvix** [mamoe/mirai#142]
## 问题
发送有图片的群消息时，sendMessage()函数返回后立刻获取sourceId将导致IllegalStateException

代码：
```kotlin
runBlocking {
.....
val msg =bot.getGroup(chatId).sendMessage(chainBuilder.asMessageChain())
val id = msg.sourceId //执行此处将抛出IllegalStateException: This job has not completed yet
}
```

异常：
```
java.lang.IllegalStateException: This job has not completed yet
	at kotlinx.coroutines.JobSupport.getCompletedInternal$kotlinx_coroutines_core(JobSupport.kt:1198)
	at kotlinx.coroutines.DeferredCoroutine.getCompleted(Builders.common.kt:98)
	at net.mamoe.mirai.qqandroid.message.MessageSourceFromSendGroup.getId(MessageSourceImpl.kt:261)
	at com.kenvix.moecraftbot.ng.bot.provider.mirai.MiraiMessager$sendMessageImpl$1$id$1.invokeSuspend(MiraiMessager.kt:348)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.kenvix.moecraftbot.ng.bot.provider.mirai.MiraiMessager$sendMessageImpl$1.invokeSuspend(MiraiMessager.kt:109)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.kenvix.moecraftbot.ng.bot.provider.mirai.MiraiMessager.sendMessageImpl(MiraiMessager.kt:98)
	at com.kenvix.moecraftbot.ng.bot.provider.mirai.MiraiMessager.sendMessage(MiraiMessager.kt:88)
	at com.kenvix.moecraftbot.ng.bot.provider.mirai.MiraiBot.sendMessage(MiraiBot.kt:62)
	at com.kenvix.moecraftbot.ng.lib.middleware.messagepush.BotMessagePusher.onPushRequest(BotMessagePusher.kt:77)
	at com.kenvix.moecraftbot.ng.lib.middleware.messagepush.BotMessagePusher.access$onPushRequest(BotMessagePusher.kt:23)
	at com.kenvix.moecraftbot.ng.lib.middleware.messagepush.BotMessagePusher$onEnable$1$1.handle(BotMessagePusher.kt:33)
	at io.javalin.core.security.SecurityUtil.noopAccessManager(SecurityUtil.kt:23)
	at io.javalin.http.JavalinServlet$addHandler$protectedHandler$1.handle(JavalinServlet.kt:119)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:45)
	at io.javalin.http.JavalinServlet$service$2$1.invoke(JavalinServlet.kt:24)
	at io.javalin.http.JavalinServlet$service$1.invoke(JavalinServlet.kt:126)
	at io.javalin.http.JavalinServlet$service$2.invoke(JavalinServlet.kt:40)
	at io.javalin.http.JavalinServlet.service(JavalinServlet.kt:78)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at io.javalin.core.JavalinServer$start$httpHandler$1.doHandle(JavalinServer.kt:54)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)
```

## 如何复现

发送带有图片的群消息，sendMessage()函数返回后立刻获取sourceId

**Comment by Him188** [comment]
在这之前调用 `MessageSource.ensureSequenceIdAvailable()`

`MessageSource`可以从`MessageReceipt.source` 获取

**Comment by Him188** [comment]
正计划重写 `MessageSource` 以改进这种处理。
