### ISSUE TITLE
账户于 QQ on Windows 登录后 Bot 无法接收群消息

### ISSUE THREAD

**Issue by mrhso** [mamoe/mirai#1420]
```
2021-07-18 18:49:01 I/main: Auto-login *********
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2021-07-18 18:49:01 I/Bot.*********: [AccountSecretsManager] Loaded account secrets from local cache.
2021-07-18 18:49:02 I/Bot.*********: [AccountSecretsManager] Saved account secrets to local cache for fast login.
2021-07-18 18:49:02 I/Bot.*********: Login successful.
2021-07-18 18:49:10 V/Bot.*********: Event: BotOnlineEvent(bot=Bot(*********))
2021-07-18 18:49:10 I/MiraiNative: Mirai Native 正启用所有插件。
2021-07-18 18:49:10 I/Bot.*********: Bot login successful.
2021-07-18 18:49:10 I/main: mirai-console started successfully.
2021-07-18 18:49:11 I/MiraiNative: [CoolQ Socket API (Node.js) APIClient] Client added: 54382.
2021-07-18 18:49:19 V/Bot.*********: [**********(*********)] Ishisashi(1145759243) -> [mirai:at:*********] ·
2021-07-18 18:49:20 V/Bot.*********: Event: BeforeImageUploadEvent(target=Group(*********), source=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@e2974b)
2021-07-18 18:49:21 V/Bot.*********: Event: Succeed(target=Group(*********), source=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@e2974b, image=[mirai:image:{83CCAC6F-8464-E25F-996D-B2C5CBA8BBF3}.png])
2021-07-18 18:49:21 V/Bot.*********: Event: GroupMessagePreSendEvent(target=Group(*********), message=[mirai:at:1145759243] IDS: ·
Normalised IDS: ·
[mirai:image:{83CCAC6F-8464-E25F-996D-B2C5CBA8BBF3}.png])
2021-07-18 18:49:22 V/Bot.*********: Group(*********) <- [mirai:at:1145759243] IDS: ·\nNormalised IDS: ·\n[mirai:image:{83CCAC6F-8464-E25F-996D-B2C5CBA8BBF3}.png]
2021-07-18 18:49:22 V/Bot.*********: Event: GroupMessagePostSendEvent(target=Group(*********), message=[mirai:at:1145759243] IDS: ·
Normalised IDS: ·
[mirai:image:{83CCAC6F-8464-E25F-996D-B2C5CBA8BBF3}.png], exception=null, receipt=net.mamoe.mirai.message.MessageReceipt@1f2880a)
2021-07-18 18:49:33 V/Bot.*********: Event: OtherClientOfflineEvent(client=OtherClient(bot=*********,deviceName=***************,platform=WINDOWS))
2021-07-18 18:49:37 V/Bot.*********: Event: OtherClientOnlineEvent(client=OtherClient(bot=*********,deviceName=***************,platform=WINDOWS), kind=MOBILE_PC_QQ)
2021-07-18 18:49:46 V/Bot.*********: [**********(*********)] Ishisashi(1145759243) -> [mirai:at:*********] ·
2021-07-18 18:49:47 V/Bot.*********: Event: BeforeImageUploadEvent(target=Group(*********), source=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@1f571fc)
2021-07-18 18:49:47 V/Bot.*********: Event: Succeed(target=Group(*********), source=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@1f571fc, image=[mirai:image:{83CCAC6F-8464-E25F-996D-B2C5CBA8BBF3}.png])
2021-07-18 18:49:47 V/Bot.*********: Event: GroupMessagePreSendEvent(target=Group(*********), message=[mirai:at:1145759243] IDS: ·
Normalised IDS: ·
[mirai:image:{83CCAC6F-8464-E25F-996D-B2C5CBA8BBF3}.png])
2021-07-18 18:49:50 V/Bot.*********: Group(*********) <- [mirai:at:1145759243] IDS: ·\nNormalised IDS: ·\n[mirai:image:{83CCAC6F-8464-E25F-996D-B2C5CBA8BBF3}.png]
2021-07-18 18:49:50 V/Bot.*********: Event: GroupMessagePostSendEvent(target=Group(*********), message=[mirai:at:1145759243] IDS: ·
Normalised IDS: ·
[mirai:image:{83CCAC6F-8464-E25F-996D-B2C5CBA8BBF3}.png], exception=null, receipt=net.mamoe.mirai.message.MessageReceipt@1482b7a)
2021-07-18 18:49:58 V/Bot.*********: Event: Force(bot=Bot(*********), title=下线通知, message=你的帐号于18:49在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。)
2021-07-18 18:49:58 W/Bot.*********: Connection occupied by another android device: 你的帐号于18:49在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。
2021-07-18 18:50:00 I/Bot.*********: Login successful
2021-07-18 18:50:00 I/Bot.*********: [AccountSecretsManager] Saved account secrets to local cache for fast login.
2021-07-18 18:50:00 I/Bot.*********: Login successful.
2021-07-18 18:50:00 V/Bot.*********: Event: BotOnlineEvent(bot=Bot(*********))
2021-07-18 18:50:00 V/Bot.*********: Event: BotReloginEvent(bot=Bot(*********), cause=null)
2021-07-18 18:50:00 I/Bot.*********: Reconnected successfully in 1.818s.
```

#### 复现

Bot 在线时用 QQ on Windows 登录账户。

#### 版本及相关选项选择

- mirai-core: `2.7-M2` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```
[0m2021-07-18 18:49:01 V/Net *********: [BotSessionSyncer] Loading server list from cache.[0m
[92m2021-07-18 18:49:01 I/Net *********: [ServerList] Server list: 113.96.13.95:8080, 42.81.172.207:443, 180.109.156.246:80, 125.94.60.144:14000, msfwifi.3g.qq.com:8080, 14.215.138.110:14000, 180.102.110.73:8080, 42.81.170.122:80, 114.221.144.89:8080, 42.81.192.198:443.[0m
[92m2021-07-18 18:49:01 I/Net *********: [ECDHInitialPublicKeyUpdater] ECDH key is valid.[0m
[0m2021-07-18 18:49:02 V/Net *********: Send: wtlogin.exchange_emp[0m
[0m2021-07-18 18:49:02 V/Net *********: Recv: wtlogin.exchange_emp[0m
[0m2021-07-18 18:49:02 V/Net *********: Send: StatSvc.register(online)[0m
[0m2021-07-18 18:49:02 V/Net *********: Recv: StatSvc.register[0m
[0m2021-07-18 18:49:02 V/Net *********: [BotSessionSyncer] Loading BdhSession from cache file[0m
[92m2021-07-18 18:49:02 I/Net *********: [MessageSvcSyncer] Syncing friend message history...[0m
[92m2021-07-18 18:49:02 I/Net *********: [ContactUpdater] Start loading stranger list...[0m
[92m2021-07-18 18:49:02 I/Net *********: [ContactUpdater] Start loading friend list...[0m
[0m2021-07-18 18:49:02 V/Net *********: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[0m2021-07-18 18:49:02 V/Net *********: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2021-07-18 18:49:02 V/Net *********: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2021-07-18 18:49:02 V/Net *********: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2021-07-18 18:49:03 V/Net *********: Recv: OidbSvc.0x496[0m
[92m2021-07-18 18:49:03 I/Net *********: [ContactUpdater] Start loading group list...[0m
[0m2021-07-18 18:49:03 V/Net *********: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2021-07-18 18:49:03 V/Net *********: Recv: StatSvc.GetDevLoginInfo[0m
[92m2021-07-18 18:49:03 I/Net *********: [OtherClientUpdater] Online OtherClients: ***************(WINDOWS)[0m
[0m2021-07-18 18:49:03 V/Net *********: Recv: OidbSvc.0x5d2_0[0m
[92m2021-07-18 18:49:03 I/Net *********: [ContactUpdater] Successfully loaded stranger list: 0 in total[0m
[92m2021-07-18 18:49:03 I/Net *********: [MessageSvcSyncer] Syncing friend message history: Success.[0m
[0m2021-07-18 18:49:03 V/Net *********: Recv: friendlist.getFriendGroupList[0m
[0m2021-07-18 18:49:03 V/Net *********: [ContactUpdater] Loading friend list: 28/28[0m
[92m2021-07-18 18:49:03 I/Net *********: [ContactUpdater] Successfully loaded friend list: 28 in total[0m
[0m2021-07-18 18:49:04 V/Net *********: Recv: friendlist.GetTroopListReqV2[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:04 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:05 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:05 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:05 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:05 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:05 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:05 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:05 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:05 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:05 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:05 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:05 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:05 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:05 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:05 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:05 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:05 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:05 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:05 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:05 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:05 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:05 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:05 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:06 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:06 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:06 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:06 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:06 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:06 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:06 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:06 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:06 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:06 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:06 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:06 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:06 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:06 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:06 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:06 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:07 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:07 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:07 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:07 V/Net *********: Recv: ConfigPushSvc.PushReq[0m
[0m2021-07-18 18:49:07 V/Net *********: [BotSessionSyncer] Saving bdh session to cache[0m
[0m2021-07-18 18:49:07 V/Net *********: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2021-07-18 18:49:08 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:08 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:08 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:08 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:08 V/Net *********: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-07-18 18:49:08 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:08 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:09 V/Net *********: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-07-18 18:49:09 V/Net *********: Send: OidbSvc.0x899_9(OidbSvc.0x899_9)[0m
[0m2021-07-18 18:49:09 V/Net *********: Recv: OidbSvc.0x899_9[0m
[0m2021-07-18 18:49:10 V/Net *********: Recv: OidbSvc.0x899_9[0m
[92m2021-07-18 18:49:10 I/Net *********: [ContactUpdater] Successfully loaded group list: 22 in total.[0m
[92m2021-07-18 18:49:10 I/Net *********: [KeyRefreshProcessor] Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2021-07-18 18:49:10 I/Net *********: [KeyRefreshProcessor] Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[0m2021-07-18 18:49:13 V/Net *********: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2021-07-18 18:49:13 V/Net *********: Recv: SummaryCard.ReqSummaryCard[0m
[0m2021-07-18 18:49:19 V/Net *********: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2021-07-18 18:49:20 V/Net *********: Recv: SummaryCard.ReqSummaryCard[0m
[0m2021-07-18 18:49:20 V/Net *********: Send: ImgStore.GroupPicUp(ImgStore.GroupPicUp)[0m
[0m2021-07-18 18:49:21 V/Net *********: Recv: ImgStore.GroupPicUp[0m
[0m2021-07-18 18:49:21 V/Net *********: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-07-18 18:49:22 V/Net *********: Recv: MessageSvc.PbSendMsg[0m
[0m2021-07-18 18:49:33 V/Net *********: Recv: MessageSvc.RequestPushStatus[0m
[0m2021-07-18 18:49:36 V/Net *********: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[0m2021-07-18 18:49:37 V/Net *********: Recv: StatSvc.GetDevLoginInfo[0m
[0m2021-07-18 18:49:37 V/Net *********: Recv: MessageSvc.RequestPushStatus[0m
[0m2021-07-18 18:49:46 V/Net *********: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2021-07-18 18:49:46 V/Net *********: Recv: SummaryCard.ReqSummaryCard[0m
[0m2021-07-18 18:49:47 V/Net *********: Send: ImgStore.GroupPicUp(ImgStore.GroupPicUp)[0m
[0m2021-07-18 18:49:47 V/Net *********: Recv: ImgStore.GroupPicUp[0m
[0m2021-07-18 18:49:47 V/Net *********: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-07-18 18:49:48 V/Net *********: Recv: MessageSvc.PbSendMsg[0m
[0m2021-07-18 18:49:58 V/Net *********: Recv: MessageSvc.PushForceOffline[0m
[91m2021-07-18 18:49:58 W/Net *********: net.mamoe.mirai.internal.network.impl.netty.ForceOfflineException: 你的帐号于18:49在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。
net.mamoe.mirai.internal.network.impl.netty.ForceOfflineException: 你的帐号于18:49在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPushForceOffline.handle(MessageSvc.PushForceOffline.kt:35)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPushForceOffline.handle(MessageSvc.PushForceOffline.kt:25)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:110)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:83)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:81)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:186)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
[0m2021-07-18 18:49:59 V/Net *********: [BotSessionSyncer] Loading server list from cache.[0m
[92m2021-07-18 18:49:59 I/Net *********: [ServerList] Server list: 113.96.13.95:8080, 42.81.172.207:443, 180.109.156.246:80, 125.94.60.144:14000, msfwifi.3g.qq.com:8080, 14.215.138.110:14000, 180.102.110.73:8080, 42.81.170.122:80, 114.221.144.89:8080, 42.81.192.198:443.[0m
[92m2021-07-18 18:49:59 I/Net *********: [ECDHInitialPublicKeyUpdater] ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2021-07-18 18:49:59 I/Net *********: [ECDHInitialPublicKeyUpdater] Successfully fetched ecdh public key from server.[0m
[0m2021-07-18 18:49:59 V/Net *********: Send: wtlogin.login[0m
[0m2021-07-18 18:50:00 V/Net *********: Recv: wtlogin.login[0m
[0m2021-07-18 18:50:00 V/Net *********: Send: StatSvc.register(online)[0m
[0m2021-07-18 18:50:00 V/Net *********: Recv: StatSvc.register[0m
[92m2021-07-18 18:50:00 I/Net *********: [KeyRefreshProcessor] Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2021-07-18 18:50:00 I/Net *********: [KeyRefreshProcessor] Scheduled key refresh in 23h 55min 0.0s.[0m
[0m2021-07-18 18:50:04 V/Net *********: Recv: ConfigPushSvc.PushReq[0m
[0m2021-07-18 18:50:04 V/Net *********: [BotSessionSyncer] Saving bdh session to cache[0m
[0m2021-07-18 18:50:04 V/Net *********: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
```

#### 补充信息

记录日志时的操作为登录 Bot、登录 QQ on Windows、登录 QQ on Android。
「无法发送群消息」的具体表现为发送消息时 Bot 并未报错，但消息无法被接收。
先登录 Bot，再登录 QQ on Windows 会触发问题。
问题发生后，重新登录 Bot 及退出 QQ on Windows 无法恢复。
将账户在 QQ on Android 登录以使 Bot 下线则恢复正常。
私聊未见此问题。
先登录 QQ on Windows 再登录 Bot 未见问题。

**Comment by Karlatemp** [comment]
Please follow the issue template

**Comment by Him188** [comment]
请提供日志

**Comment by mrhso** [comment]
已补充。记录日志时的操作为登录 Bot、登录 QQ on Windows、登录 QQ on Android。

**Comment by Karlatemp** [comment]
请提供完整复现步骤，你问题描述只涉及到 QQwinPC, 但是实际上还涉及到了其他客户端占号

**Comment by Karlatemp** [comment]
以及描述 `无法发送群消息` 时的具体表现（是否有相关日志, 是否看得到信息）

**Comment by mrhso** [comment]
具体步骤及症状描述在「补充信息」。
> 记录日志时的操作为登录 Bot、登录 QQ on Windows、登录 QQ on Android。
「无法发送群消息」的具体表现为发送消息时 Bot 并未报错，但消息无法被接收。
先登录 Bot，再登录 QQ on Windows 会触发问题。
问题发生后，重新登录 Bot 及退出 QQ on Windows 无法恢复。
将账户在 QQ on Android 登录以使 Bot 下线则恢复正常。
私聊未见此问题。
先登录 QQ on Windows 再登录 Bot 未见问题。

**Comment by Karlatemp** [comment]
未能复现请切换账号后测试是否还有此情况出现

**Comment by GreenChennai** [comment]
我应该是一样的情况触发之后机器人CMD内显示出发出消息,而聊天框实际上未出现消息,并且Bot未报错
如下图
我也不知道触发原理,我新下载的框架迁移旧数据之后,能正常一会儿,然后就不能了
或许真是期间登录手机QQ导致的,不过我是登录的Tim
![QQ截图20210718212239](https://user-images.githubusercontent.com/33357929/126087667-0d5805b6-411f-4be8-859c-5d40c835d7d6.png)
![QQ截图20210718212314](https://user-images.githubusercontent.com/33357929/126087672-f11a2386-2a67-4fd2-9e85-de588b17ed09.png)


对了憨憨机器人是另一个机器人,是旧框架,新的那个没发得出信息

**Comment by sandtechnology** [comment]
我觉得是异地登录本身触发了本问题（风控检测），而非其他原因

**Comment by GreenChennai** [comment]
> 我觉得是异地登录本身触发了本问题（风控检测），而非其他原因

不是把?我从新版本换回旧版还是能正常使用的

**Comment by Him188** [comment]
出现问题后在手机端能不能看到 bot 的消息? 有些消息就是 PC 端看不到, 手机端可以看

**Comment by mrhso** [comment]
手机端无法看到 Bot 的消息。
不过今日再测试已无法重现问题，应该是腾讯风控。

**Comment by GreenChennai** [comment]
应该是腾讯的问题
私发信息是没问题的
群发就无法显示
旧版本或许是平板平台的原因没有受到限制
这种情况一般改个密码就能好
