### ISSUE TITLE
机器人管理员权限丢失

### ISSUE THREAD

**Issue by Hetols** [mamoe/mirai#1423]
#### 复现
启动机器人，判断群内权限，无论是否为管理员，都返回MEMBER，且无法操作加群申请。
#### 版本及相关选项选择
- mirai-core: `2.7-M2`
- bot-protocol: `ANDROID_PHONE`
#### 网络日志
2021-07-18 10:58:54 E/Bot QQ: Exception in unnamed coroutine.
net.mamoe.mirai.contact.PermissionDeniedException: Permission denied: required ADMINISTRATOR, got actual MEMBER for Bot(QQ) in group groupID
	at net.mamoe.mirai.internal.MiraiImpl.acceptMemberJoinRequest$suspendImpl(MiraiImpl.kt:1007)
	at net.mamoe.mirai.internal.MiraiImpl.acceptMemberJoinRequest(MiraiImpl.kt)
	at net.mamoe.mirai.event.events.MemberJoinRequestEvent.accept(group.kt:397)
	at net.mamoe.mirai.event.events.MemberJoinRequestEvent$accept$2.invoke(group.kt:65535)
	at net.mamoe.mirai.event.events.MemberJoinRequestEvent$accept$2.invoke(group.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	(Coroutine boundary)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2.invokeSuspend(EventChannel.kt:512)
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invokeSuspend(EventChannel.kt:146)
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invokeSuspend(EventChannel.kt:146)
	at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
	at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
	at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:160)
	at net.mamoe.mirai.internal.event.InternalEventListenersKt.callAndRemoveIfRequired(InternalEventListeners.kt:109)
	at net.mamoe.mirai.event._EventBroadcast.broadcastImpl(Event.kt:174)
	at net.mamoe.mirai.event._EventBroadcast.broadcastPublic$suspendImpl(Event.kt:161)
	at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcast$2.invokeSuspend(EventDispatcher.kt:90)
	at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcast$suspendImpl(EventDispatcher.kt:89)
	at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcastAsync$job$1.invokeSuspend(EventDispatcher.kt:105)
	(Coroutine creation stacktrace)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:184)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcastAsync-kKe4JaQ(EventDispatcher.kt:102)
	at net.mamoe.mirai.internal.network.components.EventDispatcher.broadcastAsync-kKe4JaQ$default(EventDispatcher.kt:35)
	at net.mamoe.mirai.internal.network.components.EventBroadcasterPacketHandler.impl(PacketHandler.kt:87)
	at net.mamoe.mirai.internal.network.components.EventBroadcasterPacketHandler.handlePacket(PacketHandler.kt:73)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:83)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:81)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:186)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: net.mamoe.mirai.contact.PermissionDeniedException: Permission denied: required ADMINISTRATOR, got actual MEMBER for Bot(QQ) in group groupID
	at net.mamoe.mirai.internal.MiraiImpl.acceptMemberJoinRequest$suspendImpl(MiraiImpl.kt:1007)
	at net.mamoe.mirai.internal.MiraiImpl.acceptMemberJoinRequest(MiraiImpl.kt)
	at net.mamoe.mirai.event.events.MemberJoinRequestEvent.accept(group.kt:397)
	at net.mamoe.mirai.event.events.MemberJoinRequestEvent$accept$2.invoke(group.kt:65535)
	at net.mamoe.mirai.event.events.MemberJoinRequestEvent$accept$2.invoke(group.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at net.mamoe.kjbb.internal.RunBlockingKt.$runSuspend$(RunBlocking.kt:18)
	at net.mamoe.mirai.event.events.MemberJoinRequestEvent.accept(group.kt)
	at ink.lavaheart.hintbot.JavaMain.lambda$mainProcess$3(JavaMain.java:200)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:512)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:512)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	... 1 more

**Comment by Karlatemp** [comment]
#1400
