### ISSUE TITLE
LoginSolver 抛出异常后仍然继续登录，没有终止

### ISSUE THREAD

**Issue by DreamVoid** [mamoe/mirai#1427]
我在使用Mirai Core提供的LoginSolver的时候遇到了一个问题，当我尝试在LoginSolver抛出错误后，Mirai没有像预期的那样终止登录过程，而是继续尝试登录

- [LoginSolver的相关解释](https://github.com/mamoe/mirai/blob/2a641415a70db24d74beb6d2159e27126bd5f149/mirai-core-api/src/commonMain/kotlin/utils/LoginSolver.kt#L56)
- [我使用的代码](https://github.com/DreamVoid/MiraiMC/blob/e1a24028ea35c960794f2415e6876da48cf63da5/src/main/java/me/dreamvoid/miraimc/internal/MiraiLoginSolver.java#L64)

```
System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[21:04:12 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[21:04:13 INFO]: Reloading ResourceManager: Default, bukkit
[21:04:14 INFO]: Loaded 7 recipes
[21:04:15 INFO]: Starting minecraft server version 1.17.1
[21:04:15 INFO]: Loading properties
[21:04:15 INFO]: This server is running Purpur version git-Purpur-1261 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 325d6c3 on HEAD)
[21:04:15 INFO]: Debug logging is disabled
[21:04:15 INFO]: Server Ping Player Sample Count: 12
[21:04:15 INFO]: Using 4 threads for Netty based IO
[21:04:15 INFO]: Default game type: SURVIVAL
[21:04:15 INFO]: Generating keypair
[21:04:15 INFO]: Starting Minecraft server on *:25565
[21:04:15 INFO]: Using default channel type
[21:04:16 INFO]: [MiraiMC] Loading MiraiMC v1.2
[21:04:16 INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:04:16 INFO]: Preparing level "world"
[21:04:16 INFO]: Preparing start region for dimension minecraft:overworld
[21:04:17 INFO]: Time elapsed: 186 ms
[21:04:17 INFO]: Preparing start region for dimension minecraft:the_nether
[21:04:17 INFO]: Time elapsed: 63 ms
[21:04:17 INFO]: Preparing start region for dimension minecraft:the_end
[21:04:17 INFO]: Time elapsed: 59 ms
[21:04:17 INFO]: [MiraiMC] Enabling MiraiMC v1.2
[21:04:17 WARN]: [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[21:04:17 WARN]: [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[21:04:17 INFO]: [MiraiMC] Mirai working dir: default
[21:04:17 INFO]: [MiraiMC] Starting bot event listener.
[21:04:17 INFO]: [MiraiMC] Registering commands.
[21:04:17 INFO]: [MiraiMC] Loading auto-login file.
[21:04:17 INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[21:04:17 INFO]: Running delayed init tasks
[21:04:17 INFO]: Done (2.129s)! For help, type "help"
[21:04:17 INFO]: Timings Reset
[21:04:17 INFO]: [MiraiMC] [AutoLogin] Starting auto-bot task.
> mirai login xxx xxx
[21:04:19 INFO]: [MiraiMC] 登录新的机器人账号: xxx, 协议: ANDROID_PHONE
[21:04:19 INFO]: 2021-07-21 21:04:19 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
[21:04:19 INFO]: 2021-07-21 21:04:19 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
[21:04:21 INFO]: [MiraiMC] [ServerList] Server list: 36.155.249.126:14000, msfwifi.3g.qq.com:8080, 120.232.19.169:8080, 111.30.178.34:80, 36.155.228.120:80, 120.232.19.18:443, 120.232.22.118:8080, 111.30.178.75:80, 111.30.179.153:80, 36.155.229.191:8080.
[21:04:22 INFO]: [MiraiMC] [AccountSecretsManager] Loaded account secrets from local cache.
[21:04:22 INFO]: [MiraiMC] [ECDHInitialPublicKeyUpdater] ECDH key is valid.
[21:04:22 WARN]: [MiraiMC] 当前登录的QQ（xxx）需要验证设备锁
[21:04:22 WARN]: [MiraiMC] 请使用手机QQ打开以下链接进行验证
[21:04:22 WARN]: [MiraiMC] https://ti.qq.com/safe/verify?xxx
[21:04:22 WARN]: [MiraiMC] 验证完成后，请输入指令 /miraiverify unsafedevice xxx
[21:04:22 WARN]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify unsafedevicecancel xxx
[21:04:22 WARN]: [MiraiMC] 如需帮助，请参阅: https://github.com/DreamVoid/MiraiMC
> miraiverify unsafedevicecancel xxx
[21:04:24 WARN]: [MiraiMC] null
java.lang.IllegalThreadStateException: 用户终止登录
        at me.dreamvoid.miraimc.internal.MiraiLoginSolver.onSolveUnsafeDeviceLoginVerify(MiraiLoginSolver.java:64) ~[?:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:202) ~[?:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[?:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[?:?]
        Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(xxx), code=16, title=登录失 败, message=你的用户身份已失效，为保证帐号安全，请你重新登录。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:271) ~[?:?]
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[?:?]
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[?:?]
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[?:?]
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[?:?]
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[?:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[?:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[?:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[?:?]
[21:04:24 INFO]: [MiraiMC] [ServerList] Server list: 36.155.249.126:14000, msfwifi.3g.qq.com:8080, 120.232.19.169:8080, 111.30.178.34:80, 36.155.228.120:80, 120.232.19.18:443, 120.232.22.118:8080, 111.30.178.75:80, 111.30.179.153:80, 36.155.229.191:8080.
[21:04:24 INFO]: [MiraiMC] [AccountSecretsManager] Loaded account secrets from local cache.
[21:04:24 INFO]: [MiraiMC] [ECDHInitialPublicKeyUpdater] ECDH key is valid.
[21:04:24 WARN]: [MiraiMC] 当前登录的QQ（xxx）需要验证设备锁
[21:04:24 WARN]: [MiraiMC] 请使用手机QQ打开以下链接进行验证
[21:04:24 WARN]: [MiraiMC] https://ti.qq.com/safe/verify?xxx
[21:04:24 WARN]: [MiraiMC] 验证完成后，请输入指令 /miraiverify unsafedevice xxx
[21:04:24 WARN]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify unsafedevicecancel xxx
[21:04:24 WARN]: [MiraiMC] 如需帮助，请参阅: https://github.com/DreamVoid/MiraiMC
> miraiverify unsafedevicecancel xxx
[21:04:34 INFO]: [MiraiMC] [ServerList] Server list: 36.155.249.126:14000, msfwifi.3g.qq.com:8080, 120.232.19.169:8080, 111.30.178.34:80, 36.155.228.120:80, 120.232.19.18:443, 120.232.22.118:8080, 111.30.178.75:80, 111.30.179.153:80, 36.155.229.191:8080.
[21:04:34 INFO]: [MiraiMC] [AccountSecretsManager] Loaded account secrets from local cache.
[21:04:34 INFO]: [MiraiMC] [ECDHInitialPublicKeyUpdater] ECDH key is valid.
[21:04:35 WARN]: [MiraiMC] 当前登录的QQ（xxx）需要验证设备锁
[21:04:35 WARN]: [MiraiMC] 请使用手机QQ打开以下链接进行验证
[21:04:35 WARN]: [MiraiMC] https://ti.qq.com/safe/verify?xxx
[21:04:35 WARN]: [MiraiMC] 验证完成后，请输入指令 /miraiverify unsafedevice xxx
[21:04:35 WARN]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify unsafedevicecancel xxx
[21:04:35 WARN]: [MiraiMC] 如需帮助，请参阅: https://github.com/DreamVoid/MiraiMC
>
```

#### 复现

1. 在代码中加入throw并加入相关触发机制
2. 调用触发机制

#### 版本及相关选项选择

- mirai-core: `2.7-M2` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```
见上
```

**Comment by Karlatemp** [comment]
请抛出 LoginFailedException 或者其子错误类型，目前设计抛出其他错误是当做 solver 内部错误然后进行重试
