### ISSUE TITLE
机器人在收到群成员邀请其他成员进群消息的时候报错

### ISSUE THREAD

**Issue by mcdoeswhat** [mamoe/mirai#1429]
机器人在收到群成员邀请其他成员进群消息的时候报错
机器人没有被踢出群 mirai是2.6.7

```
[22:33:33 INFO]: 2021-07-22 22:33:33 V/Bot 3528054353: Event: MemberJoinRequestEvent(bot=Bot(3528054353), eventId=1626964413485559, message=来自：群成员Asteropa的邀请, fromId=1013400663, groupId=423558971, groupName=我的世界永恒1.16.4, fromNick=喜悦., invitorId=1713843510)
[22:33:33 INFO]: 2021-07-22 22:33:33 E/Bot 3528054353: java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=6 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#240914314 {
[22:33:33 INFO]:             actionUin=0x00000000001B725C(1798748)
[22:33:33 INFO]:             actionUinNick=Albert
[22:33:33 INFO]:             actionUinQqNick=Albert
[22:33:33 INFO]:             actions=[]
[22:33:33 INFO]:             actorUin=0x0000000000000000(0)
[22:33:33 INFO]:             cloneUin=0x0000000000000000(0)
[22:33:33 INFO]:             discussUin=0x0000000000000000(0)
[22:33:33 INFO]:             eimGroupId=0x0000000000000000(0)
[22:33:33 INFO]:             groupCode=0x00000000193EFF3B(423558971)
[22:33:33 INFO]:             groupExtFlag=0x00210160(2163040)
[22:33:33 INFO]:             groupFlagext3=0x60052000(1610948608)
[22:33:33 INFO]:             groupInfo=GroupInfo#1710520632 {
[22:33:33 INFO]:                     appPrivilegeFlag=0x100180D3(268533971)
[22:33:33 INFO]:                     msgOtherAdminDone=其他管理员
[22:33:33 INFO]:             }
[22:33:33 INFO]:             groupMsgType=0x00000006(6)
[22:33:33 INFO]:             groupName=我的世界永恒1.16.4
[22:33:33 INFO]:             groupOwnerUin=0x0000000000000000(0)
[22:33:33 INFO]:             msgActorDescribe=处理人：%action_uin%
[22:33:33 INFO]:             msgDescribe=已将 %req_uin% 移出群
[22:33:33 INFO]:             msgTitle=退群消息
[22:33:33 INFO]:             reqUinAge=0x0000000C(12)
[22:33:33 INFO]:             reqUinNick=.
[22:33:33 INFO]:             subType=0x00000005(5)
[22:33:33 INFO]:     }
[22:33:33 INFO]: java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=6 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#240914314 {
[22:33:33 INFO]:             actionUin=0x00000000001B725C(1798748)
[22:33:33 INFO]:             actionUinNick=Albert
[22:33:33 INFO]:             actionUinQqNick=Albert
[22:33:33 INFO]:             actions=[]
[22:33:33 INFO]:             actorUin=0x0000000000000000(0)
[22:33:33 INFO]:             cloneUin=0x0000000000000000(0)
[22:33:33 INFO]:             discussUin=0x0000000000000000(0)
[22:33:33 INFO]:             eimGroupId=0x0000000000000000(0)
[22:33:33 INFO]:             groupCode=0x00000000193EFF3B(423558971)
[22:33:33 INFO]:             groupExtFlag=0x00210160(2163040)
[22:33:33 INFO]:             groupFlagext3=0x60052000(1610948608)
[22:33:33 INFO]:             groupInfo=GroupInfo#1710520632 {
[22:33:33 INFO]:                     appPrivilegeFlag=0x100180D3(268533971)
[22:33:33 INFO]:                     msgOtherAdminDone=其他管理员
[22:33:33 INFO]:             }
[22:33:33 INFO]:             groupMsgType=0x00000006(6)
[22:33:33 INFO]:             groupName=我的世界永恒1.16.4
[22:33:33 INFO]:             groupOwnerUin=0x0000000000000000(0)
[22:33:33 INFO]:             msgActorDescribe=处理人：%action_uin%
[22:33:33 INFO]:             msgDescribe=已将 %req_uin% 移出群
[22:33:33 INFO]:             msgTitle=退群消息
[22:33:33 INFO]:             reqUinAge=0x0000000C(12)
[22:33:33 INFO]:             reqUinNick=.
[22:33:33 INFO]:             subType=0x00000005(5)
[22:33:33 INFO]:     }
[22:33:33 INFO]:        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:23)
[22:33:33 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup$decode$2.invoke(NewContact.kt:233)
[22:33:33 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:265)
[22:33:33 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:526)
[22:33:33 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:247)
[22:33:33 INFO]:        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:593)
[22:33:33 INFO]:        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:588)
[22:33:33 INFO]:        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:570)
[22:33:33 INFO]:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[22:33:33 INFO]:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[22:33:33 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[22:33:33 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[22:33:33 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[22:33:33 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[22:33:33 INFO]:
```

#### 版本及相关选项选择

- mirai-core: `2.6.7` 
- bot-protocol: `ANDROID_PAD` 

#### 网络日志

```

```

**Comment by Him188** [comment]
与 #1171 重复
