### ISSUE TITLE
2.7-M2 Java使用maven依赖方式无法启动？

### ISSUE THREAD

**Issue by RrrrLin** [mamoe/mirai#1433]
2.6.7更新框架到2.7-M2后，出现无法启动的情况。

```
java.lang.NoSuchMethodError: kotlinx/coroutines/channels/Channel.trySend-JP2dKIU(Ljava/lang/Object;)Ljava/lang/Object; (loaded from file:/C:/Users/XU/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.4.2/kotlinx-coroutines-core-1.4.2.jar by sun.misc.Launcher$AppClassLoader@cf652c62) called from class net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport (loaded from file:/C:/Users/XU/.m2/repository/net/mamoe/mirai-core-jvm/2.7-M2/mirai-core-jvm-2.7-M2.jar by sun.misc.Launcher$AppClassLoader@cf652c62).
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:262) ~[mirai-core-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateInitialized.resumeConnection0(NettyNetworkHandler.kt:407) ~[mirai-core-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$BaseStateImpl.resumeConnection(NetworkHandlerSupport.kt:171) ~[mirai-core-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.resumeConnection(NetworkHandlerSupport.kt:268) ~[mirai-core-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector$AwaitResumeInstance.runImpl$resumeInstanceCatchingException(AbstractKeepAliveNetworkHandlerSelector.kt:101) ~[mirai-core-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector$AwaitResumeInstance.runImpl(AbstractKeepAliveNetworkHandlerSelector.kt:144) ~[mirai-core-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector$AwaitResumeInstance.run(AbstractKeepAliveNetworkHandlerSelector.kt:79) ~[mirai-core-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.awaitResumeInstance(AbstractKeepAliveNetworkHandlerSelector.kt:61) ~[mirai-core-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.resumeConnection$suspendImpl(SelectorNetworkHandler.kt:106) ~[mirai-core-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.resumeConnection(SelectorNetworkHandler.kt) ~[mirai-core-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:121) ~[mirai-core-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.Bot$login$1.invoke(Bot.kt:65535) ~[mirai-core-api-jvm-2.7-M2.jar:2.7-M2]
	at net.mamoe.mirai.Bot$login$1.invoke(Bot.kt) ~[mirai-core-api-jvm-2.7-M2.jar:2.7-M2]
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205) ~[kotlin-stdlib-1.5.10.jar:1.5.10-release-890 (1.5.10)]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.5.10.jar:1.5.10-release-890 (1.5.10)]
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115) ~[kotlin-stdlib-1.5.10.jar:1.5.10-release-890 (1.5.10)]
	at net.mamoe.kjbb.internal.RunBlockingKt.$runSuspend$(RunBlocking.kt:18) ~[kotlin-jvm-blocking-bridge-jvm-1.10.3.jar:na]
	at net.mamoe.mirai.Bot.login(Bot.kt) ~[mirai-core-api-jvm-2.7-M2.jar:2.7-M2]
	at com.ruolin.robot.bot.RobotStar.star(RobotStar.java:75) ~[classes/:na]
	at com.ruolin.robot.bot.RobotStar$$FastClassBySpringCGLIB$$616b5d75.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.4.jar:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.4.jar:5.3.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.4.jar:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.4.jar:5.3.4]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115) ~[spring-aop-5.3.4.jar:5.3.4]
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$$Lambda$599/0x0000000000000000.call(Unknown Source) [spring-aop-5.3.4.jar:5.3.4]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_282]
	at java.lang.Thread.run(Thread.java:823) [na:1.8.0_282]
```
#### 版本及相关选项选择

- mirai-core: `2.7-M2` 
- bot-protocol: `ANDROID_PAD` 

#### 补充信息

maven相关依赖如下

```
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.7-M2</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core-jvm</artifactId>
            <version>1.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.5.10</version>
        </dependency>
```

**Comment by Karlatemp** [comment]
kt15有ABI破坏性更新，检查运行时依赖

**Comment by RrrrLin** [comment]
> kt15有ABI破坏性更新，检查运行时依赖

请问是什么意思，是指我这的maven依赖有问题么？

**Comment by Him188** [comment]
> > kt15有ABI破坏性更新，检查运行时依赖
> 
> 请问是什么意思，是指我这的maven依赖有问题么？

mirai 2.7-M2 依赖 kotlinx-coroutines-core 1.5.0，而在报错中可看到实际使用的是 kotlinx-coroutines-core-1.4.2.jar 导致不兼容。

我看到你的 pom 配置应该是正确的，请检查运行环境（是否使用 mvn 或 IDE 启动应用）。

**Comment by Lin-XCC** [comment]
> > > kt15有ABI破坏性更新，检查运行时依赖
> > 
> > 
> > 请问是什么意思，是指我这的maven依赖有问题么？
> 
> mirai 2.7-M2 依赖 kotlinx-coroutines-core 1.5.0，而在报错中可看到实际使用的是 kotlinx-coroutines-core-1.4.2.jar 导致不兼容。
> 
> 我看到你的 pom 配置应该是正确的，请检查运行环境（是否使用 mvn 或 IDE 启动应用）。

确实是使用的的idea启动，在重复确认了导入的maven时 发现maven对于1.5.0的依赖貌似存在问题？
![QQ截图20210802085717](https://user-images.githubusercontent.com/52395718/127791284-f0edbde5-6f8f-4eea-b02d-a642e6d0128f.jpg)

**Comment by Lin-XCC** [comment]
另外查看mirai-core-jvm 2.7-M2时 发现mirai内部使用的 kotlinx-coroutines-core 为1.4.2 这个与该问题是否有关联呢？
![QQ截图20210802090753](https://user-images.githubusercontent.com/52395718/127791749-2990a5ca-0be5-4158-8a24-684b24443850.jpg)

**Comment by RrrrLin** [comment]
在2.7-RC发布后经过查证，发现是Maven配置的spring-boot-starter-parent版本过低，导致手动引用的kotlinx-coroutines-core 1.5.0版本无法生效。换用更高版本（2.5.0）及以上可以解决。
```  
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.3</version>
        <relativePath/> <!-- lookup parent from repository -->
</parent>
```
