### ISSUE TITLE
登录时，经常出现 Failed to load account secrets from local cache. Invalidating cache...

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1439]
使用 BotFactory.INSTANCE.newBot(qq, password, botConfiguration); 进行登录的时候，登录多个QQ，经常出现此错误

```
2021-07-28 15:49:00 V/Net 177659902: [BotSessionSyncer] Loading server list from cache.
2021-07-28 15:49:00 I/Net 177659902: [ServerList] Server list: 42.81.169.43:80, 42.81.170.51:443, 42.81.170.40:443, 59.37.96.107:443, 114.221.148.14:8080, msfwifi.3g.qq.com:8080, 125.94.60.146:14000, 180.109.156.68:80, 114.221.148.192:8080, 14.22.5.202:8080.
2021-07-28 15:49:00 E/Bot 177659902: [AccountSecretsManager] Failed to load account secrets from local cache. Invalidating cache...
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
	at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:300)
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:276)
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:296)
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:320)
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:319)
	at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecretsImpl(AccountSecretsManager.kt:96)
	at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecrets(AccountSecretsManager.kt:90)
	at net.mamoe.mirai.internal.network.components.CombinedAccountSecretsManager.getSecrets(AccountSecretsManager.kt:127)
	at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:43)
	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:37)
	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:25)
	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:29)
	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:29)
	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:29)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:81)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:95)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$1.invokeSuspend(NettyNetworkHandler.kt:269)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

- mirai-core: `2.7-M2` 
- bot-protocol: `ANDROID_PHONE`

**Comment by Karlatemp** [comment]
R E A D   D O C   P L Z
https://github.com/mamoe/mirai/blob/dev/docs/Bots.md#%E4%BF%AE%E6%94%B9%E8%BF%90%E8%A1%8C%E7%9B%AE%E5%BD%95
