### ISSUE TITLE
自动重连失效

### ISSUE THREAD

**Issue by Itsusinn** [mamoe/mirai#1450]
较长时间使用mirai时，bot掉线并无法重连

```
[96m2021-07-31 08:20:59 D/: Unknown Transformers528 0x14 template
templId=10036
PermList=[TemplParam#1190441995 {
            name=6D 71 71 5F 75 69 6E
            value=31 37 37 35 37 35 31 38 33 34
    }, TemplParam#1190441995 {
            name=6D 71 71 5F 6E 69 63 6B
            value=E6 A9 98
    }, TemplParam#1190441995 {
            name=75 73 65 72 5F 73 69 67 6E
            value=E4 BB 8A E6 97 A5 E7 AC AC 31 E4 B8 AA E6 89 93 E5 8D A1 20
    }, TemplParam#1190441995 {
            name=72 61 6E 6B 5F 69 6D 67
            value=68 74 74 70 73 3A 2F 2F 71 7A 6F 6E 65 73 74 79 6C 65 2E 67 74 69 6D 67 2E 63 6E 2F 71 7A 6F 6E 65 2F 73 70 61 63 65 5F 69 74 65 6D 2F 6D 61 74 65 72 69 61 6C 2F 51 51 50 75 6E 63 68 49 6E 2F 6F 72 67 2F 34 2F 32 30 36 36 31 32 2F 31 5F 32 78 5F 63 70 79 2E 70 6E 67
    }, TemplParam#1190441995 {
            name=6A 75 6D 70 5F 75 72 6C
            value=6D 71 71 61 70 69 3A 2F 2F 74 72 6F 6F 70 74 6F 67 65 74 68 65 72 2F 6F 70 65 6E 3F 73 72 63 5F 74 79 70 65 3D 69 6E 74 65 72 6E 61 6C 26 61 6D 70 3B 76 65 72 73 69 6F 6E 3D 31
    }, TemplParam#1190441995 {
            name=73 69 67 6E 5F 77 6F 72 64
            value=20 E6 88 91 E4 B9 9F E8 A6 81 E6 89 93 E5 8D A1
    }][0m
[0m2021-07-31 13:10:03 V/: Recv: OnlinePush.PbPushTransMsg[0m
[0m2021-07-31 14:36:35 V/: Send: wtlogin.exchange_emp(wtlogin.exchange_emp)[0m
[31m2021-07-31 14:36:35 E/: Exception in coroutine 'unnamed'
ExceptionInPacketCodecException(cause=java.lang.IllegalArgumentException: data must len % 8 == 0 && len >= 16 but given -1)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.handleExceptionInDecoding(NettyNetworkHandler.kt:63)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:85)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:75)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: data must len % 8 == 0 && len >= 16 but given -1
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:228)
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:296)
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:320)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseOicqResponse(PacketCodec.kt:225)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:109)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:82)
	... 23 more
	Suppressed: net.mamoe.mirai.internal.network.components.OicqDecodingException
	Caused by: [CIRCULAR REFERENCE: java.lang.IllegalArgumentException: data must len % 8 == 0 && len >= 16 but given -1]
[0m
[0m2021-07-31 14:36:35 V/: Recv: StatSvc.ReqMSFOffline[0m
[0m2021-07-31 14:36:35 V/: Send: StatSvc.RspMSFForceOffline(StatSvc.RspMSFForceOffline)[0m
[31m2021-07-31 14:36:35 E/: [KeyRefreshProcessor] Failed to refresh key.
StateSwitchingException(old=StateOK, new=StateClosed, cause=MsfOfflineToken(uin=2069312013, seq=2934146558, const=0))
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:260)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:422)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:90)
	at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.onEvent$closeNetwork(BotOfflineEventMonitor.kt:63)
	at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.onEvent(BotOfflineEventMonitor.kt:88)
	at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.access$onEvent(BotOfflineEventMonitor.kt:48)
	at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl$attachJob$$inlined$subscribeAlways$default$1.invokeSuspend(EventChannelKotlinExtensions.kt:174)
	at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl$attachJob$$inlined$subscribeAlways$default$1.invoke(EventChannelKotlinExtensions.kt)
	at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl$attachJob$$inlined$subscribeAlways$default$1.invoke(EventChannelKotlinExtensions.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:432)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invokeSuspend(EventChannel.kt:146)
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invokeSuspend(EventChannel.kt:146)
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.event.EventChannel$filter$1$intercepted$thisIntercepted$1.invoke(EventChannel.kt)
	at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
	at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
	at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
	at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:154)
	at net.mamoe.mirai.internal.event.InternalEventListenersKt.access$process(InternalEventListeners.kt:1)
	at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$2$1.invokeSuspend(InternalEventListeners.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: MsfOfflineToken(uin=2069312013, seq=2934146558, const=0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:282)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:369)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:183)
	... 6 more
[0m
```

#### 复现

异地登录（？）

#### 版本及相关选项选择

- mirai-core: `2.7-m2` 
- bot-protocol: `ANDROID_PHONE` 

#### 补充信息

用真实设备登录会有这样的提示
![photo_2021-07-31_17-09-08](https://user-images.githubusercontent.com/30529002/127735087-03a63e21-f0c8-488a-9f77-1e1248799dfb.jpg)

**Comment by Karlatemp** [comment]
`data must len % 8 == 0 && len >= 16 but given -1` -> #1408, #1405
`MsfOffline` -> #1424

**Comment by Itsusinn** [comment]
@Karlatemp Thank you so much！！！You're like a wizard.  ：D
