### ISSUE TITLE
关于不同终端RemoteFile得到空指针的问题

### ISSUE THREAD

**Issue by hehenihaoQWQ** [mamoe/mirai#1453]
测试发现当使用手机端发送群文件时，由toRemoteFile方法返回的RemoteFile文件为null，而电脑端发送群文件时返回内容正常。

```
2021-08-01 15:54:54 V/Bot.2977057340: [大佬养成交流(369899060)]群名片(609509194) -> [mirai:file:homework-4-3.zip,c2660c02-f29d-11eb-966e-5452007b8f7d,8035,102]
2021-08-01 15:54:54 V/Bot.2977057340: Group(369899060) <- 接收到了homework-4-3.zip，正在保存文件...
2021-08-01 15:54:55 I/stdout: 以下是file信息
2021-08-01 15:54:55 I/stdout: null
2021-08-01 15:54:56 V/Bot.2977057340: Group(369899060) <- 上传失败，请输入“交作业 作业名称”（不含双引号）申请提交作业
2021-08-01 15:54:56 E/main: Exception in coroutine <unnamed>
java.lang.NullPointerException
	at cn.drenal.mirai.Plugin.lambda$addListener$1(Plugin.java:79)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:511)
	at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:60)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-08-01 15:57:04 V/Bot.2977057340: [大佬养成交流(369899060)] 群名片(609509194) -> [mirai:file:IMG_6947.PNG,/6fdf13ec-c16f-43b7-9c94-bc0b850cb14f,1705587,102]
2021-08-01 15:57:04 V/Bot.2977057340: Group(369899060) <- 接收到了IMG_6947.PNG，正在保存文件...
2021-08-01 15:57:04 I/stdout: 以下是file信息
2021-08-01 15:57:04 I/stdout: /IMG_6947.PNG
2021-08-01 15:57:05 V/Bot.2977057340: Group(369899060) <- 上传失败，请输入“交作业 作业名称”（不含双引号）申请提交作业
```

#### 复现

1.监听GroupMessageEvent，遍历MessageChain，如果当前Message是FileMessage的实例则使用
```Java
RemoteFile file = ((FileMessage) msg).toRemoteFile(event.getGroup());
```
进行RemoteFile的获取

2.使用iOS手机端（Android平台并未进行测试）发送群文件，输出file发现内容为null。
使用Windows电脑端（MacOS平台尚未进行测试）发送群文件，输出file得到正常目录。

#### 版本及相关选项选择

- mirai-core: `2.6.7` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

**Comment by hehenihaoQWQ** [comment]
更新一下，在本人的 MacBook 上 macOS 版本的QQ上传文件也抛空指针异常
