### ISSUE TITLE
2.7-RC-dev2 初始化json报错

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#1458]
代码:
```kotlin
private val json = Json {
        Mirai
        serializersModule = MessageSerializers.serializersModule
        ignoreUnknownKeys = true
    }
```

第二行Mirai报错:
```
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.internal.MiraiImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:377)
	at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18)
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:347)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:43)
	at tech.eritquearcus.miraicp.shared.PublicShared$json$1.invoke(PublicShared.kt:49)
	at tech.eritquearcus.miraicp.shared.PublicShared$json$1.invoke(PublicShared.kt:48)
	at kotlinx.serialization.json.JsonKt.Json(Json.kt:132)
	at kotlinx.serialization.json.JsonKt.Json$default(Json.kt:130)
	at tech.eritquearcus.miraicp.shared.PublicShared.<clinit>(PublicShared.kt:48)
	... 13 more
```
然后去掉Mirai也就是第二行后，报错
```
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.internal.MiraiImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:377)
	at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18)
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:347)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:43)
	at net.mamoe.mirai.internal.message.MessageSerializersImpl.getSerializersModule(MessageSerializersImpl.kt:195)
	at net.mamoe.mirai.message.MessageSerializers$INSTANCE.getSerializersModule(MessageSerializers.kt)
	at tech.eritquearcus.miraicp.shared.PublicShared$json$1.invoke(PublicShared.kt:49)
	at tech.eritquearcus.miraicp.shared.PublicShared$json$1.invoke(PublicShared.kt:48)
	at kotlinx.serialization.json.JsonKt.Json(Json.kt:132)
	at kotlinx.serialization.json.JsonKt.Json$default(Json.kt:130)
	at tech.eritquearcus.miraicp.shared.PublicShared.<clinit>(PublicShared.kt:48)
	... 13 more
```

#### 版本及相关选项选择

- mirai-core: `2.7-RC-dev-2`

**Comment by Nambers** [comment]
很奇怪，我在依赖里把mirai-core回退到dev-1，其他组件如core-api,console还在dev-2就不会报错

**Comment by Nambers** [comment]
全部换成dev-3就莫名其妙解决了
