### ISSUE TITLE
java.lang.IllegalStateException: type mismatch. Expected 10, actual 0

### ISSUE THREAD

**Issue by Genanik** [mamoe/mirai#146]
Network(3025657105) 14:49:53 : Send done: friendlist.getFriendGroupList
java.lang.IllegalStateException: type mismatch. Expected 10, actual 0
        at net.mamoe.mirai.qqandroid.io.serialization.jce.CommonKt.checkType-lytu1pA(common.kt:61)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.JceDecoder.beginStructure(JceDecoder.kt:213)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.JceDecoder$ListReaderImpl.beginStructure(JceDecoder.kt:90)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.FriendInfo$$serializer.deserialize(FriendList.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.FriendInfo$$serializer.deserialize(FriendList.kt:97)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
        at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:87)
        at kotlinx.serialization.internal.ListLikeSerializer.readAll(CollectionSerializers.kt:83)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:31)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:45)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Decoding.kt:231)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:233)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:233)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.GetFriendListResp$$serializer.deserialize(FriendList.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.GetFriendListResp$$serializer.deserialize(FriendList.kt:60)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.Jce.load(JceNew.kt:38)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.readJceStruct(utils.kt:52)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.readJceStruct(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.readJceStruct$default(utils.kt:49)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.readJceStruct$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt$decodeUniPacket$1.invoke(utils.kt:62)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt$decodeUniPacket$1.invoke(utils.kt)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(utils.kt:86)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniPacket(utils.kt:59)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniPacket(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniPacket$default(utils.kt:58)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniPacket$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.list.FriendList$GetFriendGroupList.decode(FriendList.kt:137)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:488)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:231)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:409)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:404)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:389)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Genanik** [comment]
Network(3025657105) 14:52:53 : ?޷????غ????б?
net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$TimeoutException: timeout receiving response of friendlist.getFriendGroupList
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$6.invokeSuspend(QQAndroidBotNetworkHandler.kt:600)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
        Suppressed: net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$TimeoutException: timeout receiving response of friendlist.getFriendGroupList
                ... 7 more
        Suppressed: net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$TimeoutException: timeout receiving response of friendlist.getFriendGroupList
                ... 7 more
Network(3025657105) 14:52:53 : ?Ժ????Լ??غ????б?


而且在多次出现上面的错误后还会出现这个（抱歉。。中文乱码是我自己的问题

**Comment by Him188** [comment]
Same to #145
