### ISSUE TITLE
bot因使用非官方QQ客户端被冻结

### ISSUE THREAD

**Issue by Pika-Lee** [mamoe/mirai#1461]
今天突然bot被冻结了，原因是“因使用非官方QQ客户端”，以前从来没遇到过该问题

![image](https://user-images.githubusercontent.com/23114990/128359538-529f566f-fb7b-42a2-a0b7-034301eb2b9c.png)
![image](https://user-images.githubusercontent.com/23114990/128359597-9f56281b-bd7f-4591-900d-485b50019ced.png)

```

```

#### 复现
第一次出现这个问题，以前从来没因为“非官方QQ客户端”被冻结过

#### 版本及相关选项选择

- mirai-core: 2.2.2
- bot-protocol: `ANDROID_PAD
- mirai-native: 2.0.0.beta1

#### 网络日志

```

[2021-08-05.log](https://github.com/mamoe/mirai/files/6939158/2021-08-05.log)


#### 补充信息
<!--如有必要，你可以在下文继续添加其他信息-->

**Comment by 448808614** [comment]
重新注册一个号

**Comment by Pika-Lee** [comment]
> 重新注册一个号

我这号mirai用了一年多了，一直没问题，今天突然弹出这个给我临时冻结了一次= =

**Comment by 448808614** [comment]
那你申请解冻吧

**Comment by Pika-Lee** [comment]
> 那你申请解冻吧

我只是反馈下出现的情况，看看有没有其它人也遇到过同样的问题。

**Comment by mill413** [comment]
> > 那你申请解冻吧
> 
> 我只是反馈下出现的情况，看看有没有其它人也遇到过同样的问题。

我前段时间也出现了这个问题，现在不敢用了

**Comment by Pika-Lee** [comment]
> > > 那你申请解冻吧
> > 
> > 
> > 我只是反馈下出现的情况，看看有没有其它人也遇到过同样的问题。
> 
> 我前段时间也出现了这个问题，现在不敢用了

我昨天恢复解冻了，目前暂时正常

**Comment by zhaodice** [comment]
我这边也有人遇到了这个问题，而且先驱（电脑端协议机器人）和mirai两个人都遇到了这个情况，而且封号时间非常统一，都在下午的14:02

**Comment by 502milk** [comment]
![1(LWI~OXH O$FT0JTN1OV93](https://user-images.githubusercontent.com/49502047/128631099-97a9130b-2a1c-4ebb-b9df-06f861d6ee04.png)
![E5X59C`W)GQ U3TZZ_V97](https://user-images.githubusercontent.com/49502047/128631102-b3006331-af9b-4f13-b9c6-9165e0abf33d.png)
不幸遇难者+1
（机器上的另外2个到是没有被冻结
mirai-core: 2.7M2
bot-protocol: ANDROID_PHONE
mirai-native: 2.0.0.beta1

（解冻还让我人脸识别了,这tx啥操作

**Comment by dragon0629** [comment]
最近听到多个类似事情了，GO那边说需要升级到最新版本，否则大面积会报，是否有协议更新呢？

**Comment by GreenChennai** [comment]
我也是但旧版本还没有被封
现在不敢用新版本
什么时候更新一下改个QQ版本客户端名称啥的

**Comment by dragon0629** [comment]
亲们还有遇到的嘛，今天我又看到4-5个反映这个问题。

**Comment by GreenChennai** [comment]
> 亲们还有遇到的嘛，今天我又看到4-5个反映这个问题。

有的换回旧版本就没事
或者只是一次警告
我等一波更新

**Comment by Pika-Lee** [comment]
> > 亲们还有遇到的嘛，今天我又看到4-5个反映这个问题。
> 
> 有的换回旧版本就没事
> 或者只是一次警告
> 我等一波更新

目前只是一次警告，暂时没有被二次冻结

**Comment by allofee** [comment]
> 我也是但旧版本还没有被封
> 现在不敢用新版本
> 什么时候更新一下改个QQ版本客户端名称啥的

你的版本有多旧？我自己发现有个２月份的版本躲过了这次冻结，其他版本都被冻了

**Comment by GreenChennai** [comment]
> > 我也是但旧版本还没有被封
> > 现在不敢用新版本
> > 什么时候更新一下改个QQ版本客户端名称啥的
> 
> 你的版本有多旧？我自己发现有个２月份的版本躲过了这次冻结，其他版本都被冻了

现版本是1.0-M4
冻结之后换回的这个版本,占时还能正常使用

**Comment by HHeyJ** [comment]
版本：
mirai-core: 2.6.4

2021-08-16 17:21:14 V/Bot : Event: MsfOffline(bot=Bot(), cause=MsfOfflineToken(uin=, seq=4052940547, const=0))
2021-08-16 17:21:14 V/Net : Send: StatSvc.RspMSFForceOffline
2021-08-16 17:21:14 I/Bot : Connection lost, retrying login (MsfOfflineToken(uin=, seq=4052940547, const=0))
2021-08-16 17:21:14 V/Net : Channel closed.
2021-08-16 17:21:14 I/Bot : Connection lost, retrying login (java.net.SocketException: Socket closed)
2021-08-16 17:21:14 I/Bot : Logging in...
2021-08-16 17:21:14 I/Bot : Logging in...
2021-08-16 17:21:14 V/Net : Loading BdhSession from cache file
2021-08-16 17:21:14 I/Net : Connected to server 183.3.235.162:8080
2021-08-16 17:21:14 V/Net : Send: wtlogin.exchange_emp
2021-08-16 17:21:14 V/Net : Recv: Error(bot=Bot(), code=40, title=安全提醒, message=请确认你输入了正确的帐号。该帐号存在被盗风险，已进入保护模式，请前往安全中心恢复。, errorInfo=)
2021-08-16 17:21:14 I/Bot : Loaded account secrets from local cache.
2021-08-16 17:21:14 V/Net : Send: wtlogin.login
2021-08-16 17:21:14 V/Net : Recv: Error(bot=Bot(), code=40, title=安全提醒, message=该帐号因涉嫌进行业务违规操作被暂时冻结QQ客户端登录，请点击下方按钮了解详情及处理。, errorInfo=)
2021-08-16 17:21:14 I/Bot : Cannot reconnect.
2021-08-16 17:21:14 V/Net : Loading BdhSession from cache file
2021-08-16 17:21:14 I/Net : Connected to server 120.232.65.165:443
2021-08-16 17:21:14 I/Bot : Loaded account secrets from local cache.
2021-08-16 17:21:14 W/Bot : java.util.concurrent.CancellationException: bot is dead therefore can't send wtlogin.login

**Comment by Hato626** [comment]
2.5.0版本没有躲过这次冻结 :(

**Comment by Pika-Lee** [comment]
> 版本：
> mirai-core: 2.6.4
> 
> 2021-08-16 17:21:14 V/Bot : Event: MsfOffline(bot=Bot(), cause=MsfOfflineToken(uin=, seq=4052940547, const=0))
> 2021-08-16 17:21:14 V/Net : Send: StatSvc.RspMSFForceOffline
> 2021-08-16 17:21:14 I/Bot : Connection lost, retrying login (MsfOfflineToken(uin=, seq=4052940547, const=0))
> 2021-08-16 17:21:14 V/Net : Channel closed.
> 2021-08-16 17:21:14 I/Bot : Connection lost, retrying login (java.net.SocketException: Socket closed)
> 2021-08-16 17:21:14 I/Bot : Logging in...
> 2021-08-16 17:21:14 I/Bot : Logging in...
> 2021-08-16 17:21:14 V/Net : Loading BdhSession from cache file
> 2021-08-16 17:21:14 I/Net : Connected to server 183.3.235.162:8080
> 2021-08-16 17:21:14 V/Net : Send: wtlogin.exchange_emp
> 2021-08-16 17:21:14 V/Net : Recv: Error(bot=Bot(), code=40, title=安全提醒, message=请确认你输入了正确的帐号。该帐号存在被盗风险，已进入保护模式，请前往安全中心恢复。, errorInfo=)
> 2021-08-16 17:21:14 I/Bot : Loaded account secrets from local cache.
> 2021-08-16 17:21:14 V/Net : Send: wtlogin.login
> 2021-08-16 17:21:14 V/Net : Recv: Error(bot=Bot(), code=40, title=安全提醒, message=该帐号因涉嫌进行业务违规操作被暂时冻结QQ客户端登录，请点击下方按钮了解详情及处理。, errorInfo=)
> 2021-08-16 17:21:14 I/Bot : Cannot reconnect.
> 2021-08-16 17:21:14 V/Net : Loading BdhSession from cache file
> 2021-08-16 17:21:14 I/Net : Connected to server 120.232.65.165:443
> 2021-08-16 17:21:14 I/Bot : Loaded account secrets from local cache.
> 2021-08-16 17:21:14 W/Bot : java.util.concurrent.CancellationException: bot is dead therefore can't send wtlogin.login

你这个冻结类型是**业务违规**，不是**非官方QQ客户端**。（建议定位一下bot发送的消息，尽量避免出现涉及财务金融、营销推广，大量URL等内容和字样）

**Comment by allofee** [comment]
我用的是mirai随机生成的device信息，不确定是不是这个原因

**Comment by langrenfengzi** [comment]
这两天也遇到了, v2.5.2

**Comment by XSana** [comment]
> 我用的是mirai随机生成的device信息，不确定是不是这个原因

手动抓的手机真实设备信息也被冻了，还两次

**Comment by Taokyla** [comment]
我冻结了2次了，用的2.4.2
不同的是：该帐号因涉嫌进行业务违规操作被暂时冻结QQ客户端登录
目前bot只有个订阅直播的功能，会在群里发送已订阅直播的链接和实时截图

**Comment by GreenChennai** [comment]
今天我又被冻结了
而且还是旧版的mirai
我再观望观望再用把

**Comment by 448808614** [comment]
我的登了好久都没封

**Comment by Hato626** [comment]
被冻结四个号了(

**Comment by Pika-Lee** [comment]
报个状态更新，今天bot被二次冻结了，同样的原因：非官方QQ客户端登陆:(

**Comment by Pika-Lee** [comment]
> > > 亲们还有遇到的嘛，今天我又看到4-5个反映这个问题。
> > 
> > 
> > 有的换回旧版本就没事
> > 或者只是一次警告
> > 我等一波更新
> 
> 目前只是一次警告，暂时没有被二次冻结

报个状态更新，今天bot被二次冻结了，同样的原因：非官方QQ客户端登陆:(

**Comment by allofee** [comment]
> 我用的是mirai随机生成的device信息，不确定是不是这个原因

确认与device信息无关

**Comment by Pika-Lee** [comment]
报个状态，今天9.11第三次被冻结，同样的原因：非官方QQ客户端登陆

**Comment by QingQiz** [comment]
报个状态，今天2022-02-09第一次被冻结，同样的原因：非官方QQ客户端登陆

**Comment by HHeyJ** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在学校读书中，无法亲自回复您的邮件。我将在放假后，尽快给您回复。

**Comment by CauchyDOOM** [comment]
```
[0m2022-06-26 15:25:28 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-06-26 15:25:29 V/: Recv: MessageSvc.PbSendMsg[0m
[96m2022-06-26 15:25:32 D/: Unknown MsgInfo kind 736, data=0C 19 00 05 0A 01 5A 3F 0B 0A 01 5A 40 0B 0A 02 00 00 9C 40 0B 0A 02 00 00 9C 7A 0B 0A 02 00 00 9C 7B 0B[0m
[96m2022-06-26 15:25:32 D/: Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile@3fd115[0m
[0m2022-06-26 15:25:35 V/: Recv: StatSvc.SvcReqMSFLoginNotify[0m
[31m2022-06-26 15:25:39 E/: Exception in coroutine 'unnamed'
ExceptionInPacketCodecException(cause=java.lang.IllegalStateException: returnCode = -10004)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.handleExceptionInDecoding(NettyNetworkHandler.kt:61)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:83)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:73)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: returnCode = -10004
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseSsoFrame(PacketCodec.kt:142)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:97)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:80)
	... 23 more
```
非官方客户端
2.10.4
APad

**Comment by QuBenhao** [comment]
最近被封控了好多次啊，有没有同学知道什么情况吗？

**Comment by HHeyJ** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在学校读书中，无法亲自回复您的邮件。我将在放假后，尽快给您回复。

**Comment by I-linmeng-I** [comment]
解封后登录立马被封了

**Comment by I-linmeng-I** [comment]
2022-09-05 07:15:11 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1722844755), code=40, title=安全提醒, message=该帐号因使用非官方QQ客户端被暂时冻结QQ客户端登录，请点击下方按钮了解详情及处理。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1722844755), code=40, title=安全提醒, message=该帐号因使用非官方QQ客户端被暂时冻结QQ客户端登录，请点击下方按钮了解详情及处理。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: java.util.concurrent.CancellationException: Bot closed
                at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
                at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
                at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:84)
                at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
                at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
                at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
                at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
                at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
                at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
                at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
                at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:245)
                at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
                at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
                at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
                at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                at java.base/java.lang.reflect.Method.invoke(Unknown Source)
                at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
                at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
                at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
                at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
                at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
                at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
                at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
                at org.itxtech.mcl.Loader.start(Loader.java:189)
                at org.itxtech.mcl.Loader.main(Loader.java:79)
        Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1722844755), code=40, title=安全提醒, message=该帐号因使用非官方QQ客户端被暂时冻结QQ客户端登录，请点击下方按钮了解详情及处理。, errorInfo=)]

**Comment by cssxsh** [comment]
> 解封后登录立马被封了

你应该把旧的设备文件清理掉的

**Comment by I-linmeng-I** [comment]
> > 解封后登录立马被封了
> 
> 你应该把旧的设备文件清理掉的

设备文件是bot下的那个device.json吗？

**Comment by cssxsh** [comment]
> > > 解封后登录立马被封了
> > 
> > 
> > 你应该把旧的设备文件清理掉的
> 
> 设备文件是bot下的那个device.json吗？

是的

**Comment by I-linmeng-I** [comment]
> > > > 解封后登录立马被封了
> > > 
> > > 
> > > 你应该把旧的设备文件清理掉的
> > 
> > 
> > 设备文件是bot下的那个device.json吗？
> 
> 是的

我新开了一个号一登陆又是被秒封，删了设备文件了

**Comment by codievilky** [comment]
我有仨号，目前看可能是因为新注册的号要求会比较严格。我使用老的 qq 号目前没有问题。
