### ISSUE TITLE
在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=16 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by gtr3qq** [mamoe/mirai#1467]
```
2021-08-09 21:09:13 E/Bot.3615670142: java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=16 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#24089519 {
            actionUin=0x00000000B398DC1C(3013139484)
            actionUinNick=香脆鱼饼干(群扒手不时拿点东西
            actionUinQqNick=香脆鱼饼干
            actions=[]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x000000002EDDCA59(786287193)
            groupExtFlag=0x402100C0(1075904704)
            groupFlagext3=0x00008080(32896)
            groupInfo=GroupInfo#18933679 {
                    appPrivilegeFlag=0x140800D0(336068816)
            }
            groupMsgType=0x00000010(16)
            groupName=锆石服务器(minecraft我的世界国际版基岩PE纯净生存服务器)
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%action_uin%
            msgDescribe=已取消 %req_uin% 的管理员身份
            msgTitle=管理员设置
            reqUinAge=0x00000013(19)
            reqUinFaceid=0x00000A02(2562)
            reqUinGender=0x00000001(1)
            reqUinNick=kecz.lp
            subType=0x00000005(5)
    }
java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5, groupMsgType=16 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并描述此时机器人是否被踢出群等 调试信息: SystemMsg#24089519 {
            actionUin=0x00000000B398DC1C(3013139484)
            actionUinNick=香脆鱼饼干(群扒手不时拿点东西
            actionUinQqNick=香脆鱼饼干
            actions=[]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x000000002EDDCA59(786287193)
            groupExtFlag=0x402100C0(1075904704)
            groupFlagext3=0x00008080(32896)
            groupInfo=GroupInfo#18933679 {
                    appPrivilegeFlag=0x140800D0(336068816)
            }
            groupMsgType=0x00000010(16)
            groupName=锆石服务器(minecraft我的世界国际版基岩PE纯净生存服务器)
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%action_uin%
            msgDescribe=已取消 %req_uin% 的管理员身份
            msgTitle=管理员设置
            reqUinAge=0x00000013(19)
            reqUinFaceid=0x00000A02(2562)
            reqUinGender=0x00000001(1)
            reqUinNick=kecz.lp
            subType=0x00000005(5)
    }
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:23)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup$decode$2.invoke(NewContact.kt:233)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:265)
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:526)
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:247)
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:593)
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:588)
        at net.mamoe.mirai.internal.network.handler.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:570)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by gtr3qq** [comment]
2021-08-09 21:09:13 V/Bot.3615670142: Event: MemberJoinRequestEvent(bot=Bot(3615670142), eventId=1628514554226209, message=问题：be版在哪些平台上架过\n答案：谷歌商店，taptap, fromId=3432617735, groupId=786287193, groupName=锆石服务器(minecraft我的世界国际版基岩PE纯净生存服务器), fromNick=逸, invitorId=null)
这条记录也应该有关。

**Comment by Him188** [comment]
@sandtechnology 猜测这个也是历史消息? 测试中能正常处理设置/取消管理员的事件

**Comment by sandtechnology** [comment]
> 
> 
> @sandtechnology 猜测这个也是历史消息? 测试中能正常处理设置/取消管理员的事件

是的 从这个通道过来的一般都是不需要处理的消息 因为这些是系统主动通知给管理员的（
