### ISSUE TITLE
无法加载好友列表

### ISSUE THREAD

**Issue by fafa-junhe** [mamoe/mirai#147]
## 问题
```
19:45:38 [NETWORK]: 稍后重试加载好友列表
 19:45:48 [NETWORK]: 开始加载好友信息
 19:45:48 [NETWORK]: Send done: friendlist.getFriendGroupList
 19:45:48 [NETWORK ERROR]: java.lang.IllegalStateException: type mismatch. Expected 10, actual 0
java.lang.IllegalStateException: type mismatch. Expected 10, actual 0
        at net.mamoe.mirai.qqandroid.io.serialization.jce.CommonKt.checkType-lytu1pA(common.kt:61)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.JceDecoder.beginStructure(JceDecoder.kt:213)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.JceDecoder$ListReaderImpl.beginStructure(JceDecoder.kt:90)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.FriendInfo$$serializer.deserialize(FriendList.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.FriendInfo$$serializer.deserialize(FriendList.kt:97)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
        at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:87)
        at kotlinx.serialization.internal.ListLikeSerializer.readAll(CollectionSerializers.kt:83)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:31)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:45)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Decoding.kt:231)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:233)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:233)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.GetFriendListResp$$serializer.deserialize(FriendList.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.GetFriendListResp$$serializer.deserialize(FriendList.kt:60)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.Jce.load(JceNew.kt:38)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.readJceStruct(utils.kt:52)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.readJceStruct(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.readJceStruct$default(utils.kt:49)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.readJceStruct$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt$decodeUniPacket$1.invoke(utils.kt:62)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt$decodeUniPacket$1.invoke(utils.kt)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(utils.kt:86)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniPacket(utils.kt:59)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniPacket(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniPacket$default(utils.kt:58)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniPacket$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.list.FriendList$GetFriendGroupList.decode(FriendList.kt:137)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:488)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:231)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:409)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:404)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:389)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
 19:45:53 [NETWORK]: Send done: friendlist.getFriendGroupList
```

## 如何复现
新建一个帐号，登录后就报错

## 其他
昨晚正常，今天突然报错。
Windows和Linux一样报错。
大号和新号一样报错。
由于无法获取好友列表。
导致无法发送信息给好友。

**Comment by fafa-junhe** [comment]
duplication of #145
