### ISSUE TITLE
bot 运行出现E/: Exception in coroutine 'unnamed'

### ISSUE THREAD

**Issue by vikieow** [mamoe/mirai#1471]
- mirai-core: `2.7.M2` 
- bot-protocol: `ANDROID_PHONE` 

异常 日志 ：

<details>

```

[31m2021-08-11 01:00:50 E/: Exception in coroutine 'unnamed'
ExceptionInPacketCodecException(cause=net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.handleExceptionInDecoding(NettyNetworkHandler.kt:63)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:85)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:75)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
	at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:300)
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:276)
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:296)
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:320)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseOicqResponse(PacketCodec.kt:239)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:109)
	at 
	
```
</details>

[2021-08-11 - 副本.log](https://github.com/mamoe/mirai/files/6965666/2021-08-11.-.log)

同时也存在windows客户端所占内存越来越大的问题

**Comment by JustOneSummer** [comment]
Java调用core这边出现了楼上之外额外的一些内容
测试版本M2和RC版本，安卓协议
JDK版本 java8(换成11也有)
错误日志：

<details>


```
2021-08-11 23:13:37 E/Net 1598683446: Exception in coroutine 'PacketDecodePipeline processor #1'
java.lang.NoSuchMethodError: kotlinx.coroutines.channels.Channel.receiveCatching-JP2dKIU(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-08-11 23:13:37 E/Net 1598683446: Exception in coroutine 'PacketDecodePipeline processor #3'
java.lang.NoSuchMethodError: kotlinx.coroutines.channels.Channel.receiveCatching-JP2dKIU(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-08-11 23:13:37 E/Net 1598683446: Exception in coroutine 'PacketDecodePipeline processor #0'
java.lang.NoSuchMethodError: kotlinx.coroutines.channels.Channel.receiveCatching-JP2dKIU(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-08-11 23:13:37 E/Net 1598683446: Exception in coroutine 'PacketDecodePipeline processor #2'
java.lang.NoSuchMethodError: kotlinx.coroutines.channels.Channel.receiveCatching-JP2dKIU(Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:181)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

23:13:37.597 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
23:13:37.599 [DefaultDispatcher-worker-3] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 48
2021-08-11 23:13:37 I/Bot 1598683446: Detected old account secrets, invalidating...
23:13:37.638 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
23:13:37.638 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
23:13:37.645 [DefaultDispatcher-worker-3] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
23:13:37.645 [DefaultDispatcher-worker-3] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
Exception in thread "main" java.lang.NoSuchMethodError: kotlin.text.CharsKt.digitToInt(CI)I
	at net.mamoe.mirai.utils.MiraiUtils__ConversionsKt.parseFromHexChunk(Conversions.kt:167)
	at net.mamoe.mirai.utils.MiraiUtils.parseFromHexChunk(Unknown Source)
	at net.mamoe.mirai.utils.MiraiUtils__ConversionsKt.hexToBytes(Conversions.kt:153)
	at net.mamoe.mirai.utils.MiraiUtils.hexToBytes(Unknown Source)
	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.<clinit>(ECDH.kt:133)
	at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.AccountSecretsImpl(AccountSecretsManager.kt:146)
	at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:154)
	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36)
	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:24)
	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:97)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.logout(SsoProcessor.kt:138)
	at net.mamoe.mirai.internal.QQAndroidBot$close$1.invokeSuspend(QQAndroidBot.kt:70)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:68)
	at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:126)
	at net.mamoe.mirai.Bot$login$1.invoke(Bot.kt:65535)
	at net.mamoe.mirai.Bot$login$1.invoke(Bot.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at net.mamoe.kjbb.internal.RunBlockingKt.$runSuspend$(RunBlocking.kt:18)
	at net.mamoe.mirai.Bot.login(Bot.kt)
	at com.shinoaki.yuyuko.bot.core.BotCore.login(BotCore.java:80)
	at RunTest.main(RunTest.java:20)
23:13:37.659 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
23:13:37.660 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
23:13:37.660 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
23:13:37.661 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
23:13:37.662 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
23:13:37.662 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
23:13:37.663 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
23:13:37.663 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
23:13:37.663 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
23:13:37.663 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
23:13:37.663 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
23:13:37.664 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\yuyuko\AppData\Local\Temp (java.io.tmpdir)
23:13:37.664 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
23:13:37.665 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 7624720384 bytes
23:13:37.665 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
23:13:37.665 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
23:13:37.665 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
23:13:37.672 [DefaultDispatcher-worker-3] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
Disconnected from the target VM, address: '127.0.0.1:61685', transport: 'socket'

Process finished with exit code 1
```

</details>

**Comment by Karlatemp** [comment]
Reply to @vikieow : 是否有网络波动等网络不佳情况

Reply to @JustOneSummer : The version of Kotlin Runtime not match

**Comment by JustOneSummer** [comment]
> Reply to @vikieow : 是否有网络波动等网络不佳情况
> 
> Reply to @JustOneSummer : The version of Kotlin Runtime not match

感谢 已经解决

**Comment by vikieow** [comment]
> Reply to @vikieow : 是否有网络波动等网络不佳情况
> 
> Reply to @JustOneSummer : The version of Kotlin Runtime not match

网络很稳定的，还有个头疼的是程序运行占用的内存会越来越大
2021-08-12 00:54:47 W/stderr: Exception in thread "nioEventLoopGroup-25-1" java.lang.OutOfMemoryError: Java heap space
2021-08-12 00:54:47 W/Bot.302509852: Connection lost, reconnecting... (NettyChannelException(message=null, cause=java.lang.OutOfMemoryError: Java heap space))

**Comment by Karlatemp** [comment]
2.7RC是否还有相关问题

**Comment by QingQiz** [comment]
也遇到了这个问题

- 环境
  ```
  19:59:25 [INFO] Verifying "net.mamoe:mirai-console" v2.10.0
  19:59:25 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.10.0
  19:59:25 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.0
  19:59:26 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
  19:59:26 [INFO] Verifying "net.mamoe:mirai-api-http" v2.4.0
  ```

-  操作系统情况
   - Windows 10, 32G
   
- `-XX:+HeapDumpOnOutOfMemoryError` 给出的 [dump](https://drive.google.com/file/d/1ZccHmXdF97w3iKkDJL64bmncQK5GLtBk/view?usp=sharing)

- 配置什么的都是默认配置

**Comment by vikieow** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
