### ISSUE TITLE
登录失败报错 java.lang.StackOverflowError: null

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#1498]
我同时登录多个QQ号，每一个QQ都通过异常捕获，如果登录失败则跳过进行下一个QQ登录。但是却报错直接退出程序了

```
java.lang.StackOverflowError: null
	at java.base/java.lang.ReflectiveOperationException.<init>(Unknown Source)
	at java.base/java.lang.reflect.InvocationTargetException.<init>(Unknown Source)
	at java.base/jdk.internal.reflect.GeneratedMethodAccessor108.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:66)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	// !repeat region start
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	// !repeat region end
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
```

- mirai-core: `2.7` 
- bot-protocol: `ANDROID_PHONE` 

-->

```
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3046816470), code=40, title=安全提醒, message=该帐号因涉嫌传播违法违规信息被暂时冻结，请点击下方按钮了解详情及处理。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(3046816470), code=16, title=登录失败, message=你的用户身份已失效，为保证帐号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:287)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		... 9 common frames omitted
10:40:45.957 [DefaultDispatcher-worker-2] WARN  net.mamoe.mirai.Bot - null 
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3046816470), code=40, title=安全提醒, message=该帐号因涉嫌传播违法违规信息被暂时冻结，请点击下方按钮了解详情及处理。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(3046816470), code=16, title=登录失败, message=你的用户身份已失效，为保证帐号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:287)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		... 9 common frames omitted
```

**Comment by Him188** [comment]
问题是有某个错误有过长的 cause 或 circular reference, 而 logback 没有检测.
由于日志中 mirai 的错误正常输出, 所以不太可能是 mirai 问题

**Comment by mckuhei** [comment]
你电脑内存真多（

**Comment by Karlatemp** [comment]
Long time no reply

----

Caused by Logback 未处理 Circular reference
