### ISSUE TITLE
无法收取群消息

### ISSUE THREAD

**Issue by goldimax** [mamoe/mirai#15]
好友消息收发正常，群消息无法正常收取，相关log如下
```
Mirai 17:57:41 : Packet sent:     GroupPacket(00 02)
java.io.EOFException: Only 5 bytes were discarded of 13 requested
        at kotlinx.io.core.InputKt.discardExact(Input.kt:158)
        at kotlinx.io.core.InputKt.discardExact(Input.kt:168)
        at net.mamoe.mirai.network.protocol.tim.packet.action.GroupPacket.decode-MgswzbQ(GroupPacket.kt:186)
        at net.mamoe.mirai.network.protocol.tim.TIMBotNetworkHandler$BotSocketAdapter$processReceive$2.invokeSuspend(TIMBotNetworkHandler.kt:174)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
Mirai 17:57:42 : ByteReadPacket 群消息=01 00 09 01 00 06 66 61 69 6C 65 64 19 00 45 01 00 42 AA 02 3F 08 06 50 02 60 00 68 00 88 01 00 9A 01 31 08 0A 78 00 C8 01 00 F0 01 00 F8 01 00 90 02 00 C8 02 00 98 03 00 A0 03 02 B0 03 00 C0 03 00 D0 03 00 E8 03 02 8A 04 04 08 02 08 01 90 04 80 C8 10 0E 00 0E 01 00 04 00 00 08 E4 07 00 04 00 00 00 01 12 00 1E 02 00 09 E9 85 B1 E9 87 8E E6 98 9F 03 00 01 02 05 00 04 00 00 00 03 08 00 04 00 00 00 04
```

**Comment by yct21** [comment]
遇到了同样的问题，在等待了大约 5 分钟后，群消息就可以正常收取了

**Comment by Him188** [comment]
这个是某一种特殊的群消息. 还不能确定是什么. 但这不影响普通的消息

**Comment by goldimax** [comment]
@yct21 我这里一直不行（

**Comment by Him188** [comment]
> @yct21 我这里一直不行（

能确定这是什么类型的消息么

试试登录完成过3秒后给机器人发全消息，看能不能正常解析
