### ISSUE TITLE
java.util.NoSuchElementException: group

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1505]
复现方式：实际群号是 323956301，往bot发送群临时会话消息时，报错，无法解析
版本号：mirai 2.7.0
日志：
```
D/MiraiConsole: Exception in decoding packet.
D/MiraiConsole: java.util.NoSuchElementException: group 3813956301
        at net.mamoe.mirai.Bot$-CC.$default$getGroupOrFail(Bot.kt:141)
        at net.mamoe.mirai.internal.AbstractBot.getGroupOrFail(AbstractBot.kt)
        at net.mamoe.mirai.internal.message.OnlineMessageSourceFromTempImpl.<init>(incomingSourceImpl.kt:139)
        at net.mamoe.mirai.internal.message.ReceiveMessageTransformer.createMessageSource(ReceiveMessageHandler.kt:111)
        at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChain(ReceiveMessageHandler.kt:85)
        at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline(ReceiveMessageHandler.kt:50)
        at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline$default(ReceiveMessageHandler.kt:44)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvc_PbGetMsgKt.transform(MessageSvc.PbGetMsg.kt:521)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvc_PbGetMsgKt.transform$default(MessageSvc.PbGetMsg.kt:250)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$messages$5.invokeSuspend(MessageSvc.PbGetMsg.kt:186)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$messages$5.invoke(MessageSvc.PbGetMsg.kt)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$messages$5.invoke(MessageSvc.PbGetMsg.kt)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Collect.kt:136)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$$inlined$filter$1$2.emit(Collect.kt:137)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$messages$2$invokeSuspend$$inlined$filter$1$2.emit(Collect.kt:137)
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$messages$2$invokeSuspend$$inlined$filter$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:132)
        at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$lambda-1$$inlined$collect$1.emit(Collect.kt:135)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Collect.kt:136)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$$inlined$filterNot$1$2.emit(Collect.kt:137)
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$$inlined$filterNot$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$$inlined$filter$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__CollectionKt.toCollection(Collection.kt:32)
        at kotlinx.coroutines.flow.FlowKt.toCollection(Unknown Source)
        at kotlinx.coroutines.flow.FlowKt__CollectionKt.toList(Collection.kt:15)
        at kotlinx.coroutines.flow.FlowKt.toList(Unknown Source)
        at kotlinx.coroutines.flow.FlowKt__CollectionKt.toList$default(Collection.kt:15)
        at kotlinx.coroutines.flow.FlowKt.toList$default(Unknown Source)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg.decode(MessageSvc.PbGetMsg.kt:190)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:370)

```

**Comment by zhaodice** [comment]
不是特别明白为什么群号 323956301 变成了 3813956301

**Comment by zhaodice** [comment]
在其他群测试，该问题无法复现，似乎只对群 323956301 有用，初步推测是群号323956301被识别成了3813956301的原因，可能是tx的石山（

**Comment by zhaodice** [comment]
神奇了，这个问题必须用特定的qq号 ，特定的群号，向bot发送群临时会话才能复现，是否可以暂时认为是一个低概率事件

**Comment by Karlatemp** [comment]
Duplicate of #1410

**Comment by mimilewis** [comment]
我也出现这个问题，换了不同的Q号都一个现象，那个群的信用星级扣成了4，不知道会不会影响
