### ISSUE TITLE
Mirai 2.7.0 在 Android 5.1 上仍无法重连

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1506]
相关日志
```
[96m2021-08-29 02:12:57 D/Net 3068437993: Attempt #0: current.state = INITIALIZED[0m
[96m2021-08-29 02:12:57 D/Net 3068437993: Attempt #0: Try resumeConnection[0m
[0m2021-08-29 02:12:57 V/Net 3068437993: Loading server list from cache.[0m
[92m2021-08-29 02:12:57 I/Net 3068437993: Server list: 124.156.216.112:10001, 175.97.166.158:10001, 61.181.203.13:14000, 14.215.138.110:80, 203.205.255.221:8080, 36.155.228.220:443, msfwifi.3g.qq.com:8080.[0m
[92m2021-08-29 02:12:57 I/Net 3068437993: ECDH key is valid.[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Send: wtlogin.exchange_emp[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Recv: wtlogin.exchange_emp[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Send: StatSvc.register(online)[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Recv: StatSvc.register[0m
[92m2021-08-29 02:12:58 I/Net 3068437993: Syncing friend message history...[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Loading BdhSession from cache file[0m
[92m2021-08-29 02:12:58 I/Net 3068437993: Loaded 9 friends from local cache.[0m
[92m2021-08-29 02:12:58 I/Net 3068437993: Start loading stranger list...[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: RETURN[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: RETURN[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Recv: StatSvc.GetDevLoginInfo[0m
[92m2021-08-29 02:12:58 I/Net 3068437993: No OtherClient online.[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Recv: OidbSvc.0x5d2_0[0m
[92m2021-08-29 02:12:58 I/Net 3068437993: Successfully loaded stranger list: 0 in total[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Recv: OidbSvc.0x496[0m
[92m2021-08-29 02:12:58 I/Net 3068437993: Start loading group list...[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2021-08-29 02:12:58 V/Net 3068437993: Recv: friendlist.getFriendGroupList[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: RETURN[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 02:12:58 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 02:12:59 V/Net 3068437993: Recv: friendlist.GetTroopListReqV2[0m
[92m2021-08-29 02:12:59 I/Net 3068437993: Loaded 6 members from local cache for group 赵骰测试 (813663657)[0m
[92m2021-08-29 02:12:59 I/Net 3068437993: Loaded 12 members from local cache for group 猫猫教内乱 (1037471743)[0m
[92m2021-08-29 02:12:59 I/Net 3068437993: Loaded 9 members from local cache for group 忒休斯之口（暑假滴卫星） (446013096)[0m
[96m2021-08-29 02:12:59 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 02:12:59 D/Net 3068437993: Attempt #0: RETURN[0m
[96m2021-08-29 02:12:59 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 02:12:59 D/Net 3068437993: Attempt #0: RETURN[0m
[92m2021-08-29 02:12:59 I/Net 3068437993: Loaded 491 members from local cache for group 赵怡然的跑团窝点 (323956301)[0m
[92m2021-08-29 02:12:59 I/Net 3068437993: Successfully loaded group list: 4 in total.[0m
[92m2021-08-29 02:12:59 I/Net 3068437993: Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2021-08-29 02:12:59 I/Net 3068437993: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[96m2021-08-29 02:12:59 D/Net 3068437993: Attempt #0: current.state = OK[0m
[96m2021-08-29 02:12:59 D/Net 3068437993: Attempt #0: Try resumeConnection[0m
[96m2021-08-29 02:12:59 D/Net 3068437993: Attempt #0: RETURN[0m
[92m2021-08-29 02:12:59 I/Net 3068437993: Syncing friend message history: Success.[0m
[0m2021-08-29 02:13:01 V/Net 3068437993: Recv: ConfigPushSvc.PushReq[0m
[0m2021-08-29 02:13:01 V/Net 3068437993: Saving bdh session to cache[0m
[96m2021-08-29 02:13:01 D/Net 3068437993: Attempt #0: current.state = OK[0m
[96m2021-08-29 02:13:01 D/Net 3068437993: Attempt #0: Try resumeConnection[0m
[96m2021-08-29 02:13:01 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 02:13:01 V/Net 3068437993: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[96m2021-08-29 02:13:03 D/Net 3068437993: Attempt #0: current.state = OK[0m
[96m2021-08-29 02:13:03 D/Net 3068437993: Attempt #0: Try resumeConnection[0m
[96m2021-08-29 02:13:03 D/Net 3068437993: Attempt #0: RETURN[0m

```

#### 复现
同样运行mirai，打开飞行模式，一段时间后输出
Bot is closed manually
恢复网络，然后就死掉了

#### 版本及相关选项选择
安卓5.1
mirai 2.7.0
协议：PHONE

**Comment by zhaodice** [comment]
第二天早上我又试了一下，日志又不一样了
```
[96m2021-08-29 09:43:53 D/Net 3068437993: Attempt #0: current.state = INITIALIZED[0m
[96m2021-08-29 09:43:53 D/Net 3068437993: Attempt #0: Try resumeConnection[0m
[0m2021-08-29 09:43:53 V/Net 3068437993: Loading server list from cache.[0m
[92m2021-08-29 09:43:53 I/Net 3068437993: Server list: 124.156.216.112:10001, 175.97.166.158:10001, 61.181.203.13:14000, 14.215.138.110:80, 203.205.255.221:8080, 36.155.228.220:443, msfwifi.3g.qq.com:8080.[0m
[92m2021-08-29 09:43:53 I/Net 3068437993: ECDH key is valid.[0m
[0m2021-08-29 09:43:53 V/Net 3068437993: Send: wtlogin.exchange_emp[0m
[0m2021-08-29 09:43:53 V/Net 3068437993: Recv: wtlogin.exchange_emp[0m
[0m2021-08-29 09:43:53 V/Net 3068437993: Send: StatSvc.register(online)[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Recv: StatSvc.register[0m
[92m2021-08-29 09:43:54 I/Net 3068437993: Syncing friend message history...[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Loading BdhSession from cache file[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[92m2021-8-29 09:43:54 I/Net 3068437993: Start loading friend list...[0m
[92m2021-08-29 09:43:54 I/Net 3068437993: Start loading stranger list...[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Recv: OidbSvc.0x5d2_0[0m
[92m2021-08-29 09:43:54 I/Net 3068437993: Successfully loaded stranger list: 0 in total[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Recv: StatSvc.GetDevLoginInfo[0m
[92m2021-08-29 09:43:54 I/Net 3068437993: No OtherClient online.[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Recv: OidbSvc.0x496[0m
[92m2021-08-29 09:43:54 I/Net 3068437993: Start loading group list...[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Recv: friendlist.getFriendGroupList[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Loading friend list: 9/9[0m
[92m2021-08-29 09:43:54 I/Net 3068437993: Successfully loaded friend list: 9 in total[0m
[92m2021-08-29 09:43:54 I/Net 3068437993: Saved 9 friends to local cache.[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Recv: friendlist.GetTroopListReqV2[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[96m2021-08-29 0009:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-08-29 09:43:54 V/Net 3068437993: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:54 D/Net 3068437993: Attempt #0: RETURN[0m
[92m2021-08-29 09:43:54 I/Net 3068437993: Syncing friend message history: Success.[0m
[0m2021-08-29 09:43:55 V/Net 3068437993: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-08-29 09:43:55 V/Net 3068437993: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-08-29 09:43:55 V/Net 3068437993: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-08-29 09:43:55 V/Net 3068437993: Recv: friendlist.GetTroopMemberListReq[0m
[96m2021-08-29 09:43:55 D/Net 3068437993: Attempt #0: current.state = LOADING[0m
[96m2021-08-29 09:43:55 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 09:43:55 V/Net 3068437993: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-08-29 09:43:56 V/Net 3068437993: Recv: friendlist.GetTroopMemberListReq[0m
[92m2021-08-29 09:43:56 I/Net 3068437993: Successfully loaded group list: 4 in total.[0m
[92m2021-08-29 09:43:56 I/Net 3068437993: Saved 4 groups to local cache.[0m
[92m2021-08-29 09:43:56 I/Net 3068437993: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2021-08-29 09:43:56 I/Net 3068437993: Scheduled key refresh in 23h 55min 0.0s.[0m
[0m2021-08-29 09:43:56 V/Net 3068437993: Recv: ConfigPushSvc.PushReq[0m
[92m2021-08-29 09:43:56 I/Net 3068437993: Server list: msfwifi.3g.qq.com:8080, 153.3.50.86:80, 221.198.69.46:80, 157.255.13.76:8080, 157.255.13.124:443, 112.65.195.55:443, 60.29.238.126:80, 220.194.118.224:80, 61.181.203.156:8080, 153.3.50.239:14000.[0m
[0m2021-08-29 09:43:56 V/Net 3068437993: Saving bdh session to cache[0m
[0m2021-08-29 09:43:56 V/Net 3068437993: Saving server list to cache[0m
[96m2021-08-29 09:43:57 D/Net 3068437993: Attempt #0: current.state = OK[0m
[96m2021-08-29 09:43:57 D/Net 3068437993: Attempt #0: Try resumeConnection[0m
[0m2021-08-29 09:43:57 V/Net 3068437993: Recv: ConfigPushSvc.PushReq[0m
[96m2021-08-29 09:43:57 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 09:43:57 V/Net 3068437993: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2021-08-29 09:43:57 V/Net 3068437993: Saving bdh session to cache[0m
[96m2021-08-29 09:43:57 D/Net 3068437993: Attempt #0: current.state = OK[0m
[96m2021-08-29 09:43:57 D/Net 3068437993: Attempt #0: Try resumeConnection[0m
[96m2021-08-29 09:43:57 D/Net 3068437993: Attempt #0: RETURN[0m
[0m2021-08-29 09:43:57 V/Net 3068437993: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[96m2021-08-29 09:44:00 D/Net 3068437993: Attempt #0: current.state = OK[0m
[96m2021-08-29 09:44:00 D/Net 3068437993: Attempt #0: Try resumeConnection[0m
[96m2021-08-29 09:44:00 D/Net 3068437993: Attempt #0: RETURN[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #0: current.state = CLOSED[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #0: ... Set current to null.[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #0: ...    Last failure was NettyChannelException(message=null, cause=java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)).[0m
[91m2021-08-29 09:44:11 W/Net 3068437993: NettyChannelException(message=null, cause=java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out))
NettyChannelException(message=null, cause=java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out))
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$handlePipelineException$1.invoke(NettyNetworkHandler.kt:68)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$handlePipelineException$1.invoke(NettyNetworkHandler.kt:68)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:251)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.handlePipelineException(NettyNetworkHandler.kt:422)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$setupChannelPipeline$1.exceptionCaught(NettyNetworkHandler.kt:109)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:177)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:620)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:583)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
	at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:634)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:608)
	at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342)
	at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304)
	at io.netty.buffer.UnpooledHeapByteBuf.setBytes(UnpooledHeapByteBuf.java:282)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	... 8 more
Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:177)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:245)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:605)
	... 14 more
[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #1: current.state = null[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #1: Creating new instance.[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #1: ... Created.[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #1: current.state = INITIALIZED[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #1: Try resumeConnection[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #1: ... failed with io.netty.channel.AbstractChannel$AnnotatedConnectException: failed to connect to /203.205.255.224 (port 8080): connect failed: ENETUNREACH (Network is unreachable): /203.205.255.224:8080[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #1: CLOSING SELECTOR[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #1: ... CLOSED[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #2: current.state = CLOSED[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #2: ... Set current to null.[0m
[96m2021-08-29 09:44:11 D/Net 3068437993: Attempt #2: ...    Last failure was io.netty.channel.AbstractChannel$AnnotatedConnectException: failed to connect to /203.205.255.224 (port 8080): connect failed: ENETUNREACH (Network is unreachable): /203.205.255.224:8080.[0m

```

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/blob/8d1884c98a595d04e136e2a522829a4a72c80102/gradle.properties#L23-L24

mirai android 目前编译目标为 Android 7.0（API 级别 24）
