### ISSUE TITLE
无法收到群成员发送的群临时消息

### ISSUE THREAD

**Issue by zhoudu** [mamoe/mirai#1526]
群成员向群管理员主动发起临时会话，群管理员无法收到群成员发送的临时消息
已经订阅“GroupTempMessageEvent”事件
eventChannel.subscribeAlways(GroupTempMessageEvent.class, t -> {
            //监听陌生人消息
            getLogger().info(t.getMessage().contentToString() + " - GroupTempMessageEvent");
            handleGroupTempMsg(t.getSender(), t.getMessage());
        });
相关日志没有打印

```

```

#### 复现

1.用mirai登录群管理员A的账号
2.群管理员B主动添加新成员C
3.C入群后给群管理员A发文本消息（C与群管理员A不是好友关系），mirai中没有收到文本消息（没打印事件日志）

#### 版本及相关选项选择

- mirai-core: `2.7.0` 
- bot-protocol: `ANDROID_PHONE` 
-mirai-console: `2.7.0`

#### 网络日志

```
[0m2021-09-06 10:13:40 V/Net 2944284735: Loading server list from cache.[0m
[92m2021-09-06 10:13:40 I/Net 2944284735: Server list: 113.96.13.125:14000, 113.96.12.27:80, 42.81.170.40:443, msfwifi.3g.qq.com:8080, 42.81.192.211:80, 113.96.13.79:8080, 42.81.184.69:443, 101.91.43.168:80, 114.221.144.89:14000, 101.91.42.98:8080.[0m
[92m2021-09-06 10:13:44 I/Net 2944284735: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2021-09-06 10:13:47 I/Net 2944284735: Successfully fetched ecdh public key from server.[0m
[0m2021-09-06 10:13:48 V/Net 2944284735: Send: wtlogin.exchange_emp[0m
[0m2021-09-06 10:13:50 V/Net 2944284735: Recv: wtlogin.exchange_emp[0m
[0m2021-09-06 10:13:50 V/Net 2944284735: Send: StatSvc.register(online)[0m
[0m2021-09-06 10:13:50 V/Net 2944284735: Recv: StatSvc.register[0m
[0m2021-09-06 10:13:50 V/Net 2944284735: Loading BdhSession from cache file[0m
[92m2021-09-06 10:13:50 I/Net 2944284735: Syncing friend message history...[0m
[0m2021-09-06 10:13:50 V/Net 2944284735: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[92m2021-09-06 10:13:50 I/Net 2944284735: Start loading stranger list...[0m
[92m2021-09-06 10:13:50 I/Net 2944284735: Start loading friend list...[0m
[0m2021-09-06 10:13:50 V/Net 2944284735: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2021-09-06 10:13:50 V/Net 2944284735: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2021-09-06 10:13:50 V/Net 2944284735: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2021-09-06 10:13:52 V/Net 2944284735: Recv: OidbSvc.0x5d2_0[0m
[92m2021-09-06 10:13:52 I/Net 2944284735: Successfully loaded stranger list: 0 in total[0m
[0m2021-09-06 10:13:52 V/Net 2944284735: Recv: StatSvc.GetDevLoginInfo[0m
[0m2021-09-06 10:13:52 V/Net 2944284735: Recv: OidbSvc.0x496[0m
[92m2021-09-06 10:13:52 I/Net 2944284735: Online OtherClients: ND--20210608TQU(WINDOWS)[0m
[92m2021-09-06 10:13:52 I/Net 2944284735: Start loading group list...[0m
[0m2021-09-06 10:13:52 V/Net 2944284735: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[96m2021-09-06 10:13:52 D/Net 2944284735: unknown PbGetMsg type 528, data=08 EB 01 12 2C 0A 22 08 BF F0 F8 FB 0A 10 BF F0 F8 FB 0A 18 D9 51 20 00 28 00 30 00 38 00 40 00 48 00 50 00 58 90 04 60 76 10 01 18 00 20 00 2A 00[0m
[92m2021-09-06 10:13:52 I/Net 2944284735: Syncing friend message history: Success.[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Recv: friendlist.GetTroopListReqV2[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Recv: ConfigPushSvc.PushReq[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Recv: friendlist.getFriendGroupList[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Loading friend list: 14/14[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[92m2021-09-06 10:13:55 I/Net 2944284735: Server list: 183.36.108.142:14000, 42.81.169.46:443, msfwifi.3g.qq.com:8080, 42.81.172.147:80, 101.91.43.168:443, 183.47.98.25:443, 42.81.169.43:443, 14.215.138.110:8080, 180.102.110.114:80, 180.109.156.44:8080.[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[92m2021-09-06 10:13:55 I/Net 2944284735: Successfully loaded friend list: 14 in total[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Saving bdh session to cache[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Saving server list to cache[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Recv: ConfigPushSvc.PushReq[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Saving bdh session to cache[0m
[0m2021-09-06 10:13:55 V/Net 2944284735: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2021-09-06 10:13:57 V/Net 2944284735: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-09-06 10:13:57 V/Net 2944284735: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-09-06 10:13:57 V/Net 2944284735: Recv: friendlist.GetTroopMemberListReq[0m
[92m2021-09-06 10:13:57 I/Net 2944284735: Successfully loaded group list: 3 in total.[0m
[92m2021-09-06 10:13:57 I/Net 2944284735: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2021-09-06 10:13:57 I/Net 2944284735: Scheduled key refresh in 23h 55min 0.0s.[0m
[96m2021-09-06 10:27:45 D/Net 2944284735: unknown PbGetMsg type 528, data=08 34 12 74 0A 72 08 03 12 11 10 50 1A 0D 72 65 73 2E 77 78 2E 71 71 2E 63 6F 6D 18 01 20 B0 09 28 01 32 00 38 00 42 22 6F 70 65 6E 2F 6C 69 62 73 2F 77 65 75 69 6A 73 2F 31 2E 32 2E 31 2F 77 65 75 69 2E 6D 69 6E 2E 6A 73 48 E8 07 52 1A 00 06 00 01 00 00 00 08 30 00 08 43 61 35 7C 45 0A EE 0D 4D 46 51 0A F1 72 A9 58 01 60 02 72 00 98 01 00 A0 01 00 B8 01 02[0m
[0m2021-09-06 10:27:49 V/Net 2944284735: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-09-06 10:27:50 V/Net 2944284735: Recv: MessageSvc.PbSendMsg[0m
[0m2021-09-06 10:27:54 V/Net 2944284735: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-09-06 10:27:55 V/Net 2944284735: Recv: MessageSvc.PbSendMsg[0m
[31m2021-09-06 10:29:09 E/Net 2944284735: Exception in decoding packet.
java.util.NoSuchElementException: group 4148401563
	at net.mamoe.mirai.Bot.getGroupOrFail(Bot.kt:141)
	at net.mamoe.mirai.internal.message.OnlineMessageSourceFromTempImpl.<init>(incomingSourceImpl.kt:139)
	at net.mamoe.mirai.internal.message.ReceiveMessageTransformer.createMessageSource(ReceiveMessageHandler.kt:111)
	at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChain(ReceiveMessageHandler.kt:85)
	at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline(ReceiveMessageHandler.kt:50)
	at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline$default(ReceiveMessageHandler.kt:44)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvc_PbGetMsgKt.transform(MessageSvc.PbGetMsg.kt:521)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvc_PbGetMsgKt.transform$default(MessageSvc.PbGetMsg.kt:250)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$messages$5.invokeSuspend(MessageSvc.PbGetMsg.kt:186)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$messages$5.invoke(MessageSvc.PbGetMsg.kt)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$messages$5.invoke(MessageSvc.PbGetMsg.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Collect.kt:136)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$$inlined$filter$1$2.emit(Collect.kt:137)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$messages$2$invokeSuspend$$inlined$filter$1$2.emit(Collect.kt:137)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$messages$2$invokeSuspend$$inlined$filter$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:132)
	at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$lambda-1$$inlined$collect$1.emit(Collect.kt:135)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Collect.kt:136)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$$inlined$filterNot$1$2.emit(Collect.kt:137)
	at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$$inlined$filterNot$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$decode$$inlined$filter$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
	at kotlinx.coroutines.flow.FlowKt__CollectionKt.toCollection(Collection.kt:32)
	at kotlinx.coroutines.flow.FlowKt.toCollection(Unknown Source)
	at kotlinx.coroutines.flow.FlowKt__CollectionKt.toList(Collection.kt:15)
	at kotlinx.coroutines.flow.FlowKt.toList(Unknown Source)
	at kotlinx.coroutines.flow.FlowKt__CollectionKt.toList$default(Collection.kt:15)
	at kotlinx.coroutines.flow.FlowKt.toList$default(Unknown Source)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg.decode(MessageSvc.PbGetMsg.kt:190)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:370)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:183)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
[0m2021-09-06 10:30:26 V/Net 2944284735: Send: LongConn.OffPicUp(LongConn.OffPicUp)[0m
[0m2021-09-06 10:30:27 V/Net 2944284735: Recv: LongConn.OffPicUp[0m
[0m2021-09-06 10:30:27 V/Net 2944284735: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-09-06 10:30:28 V/Net 2944284735: Recv: MessageSvc.PbSendMsg[0m
[0m2021-09-06 10:30:31 V/Net 2944284735: Send: LongConn.OffPicUp(LongConn.OffPicUp)[0m
[0m2021-09-06 10:30:31 V/Net 2944284735: [Highway] Uploading private image to 183.3.233.225:443, size=2214.32 KiB[0m
[0m2021-09-06 10:30:31 V/Net 2944284735: Recv: LongConn.OffPicUp[0m
[0m2021-09-06 10:30:35 V/Net 2944284735: [Highway] Uploading private image: succeed at 542 KiB/s[0m
[0m2021-09-06 10:30:35 V/Net 2944284735: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-09-06 10:30:36 V/Net 2944284735: Recv: MessageSvc.PbSendMsg[0m
[96m2021-09-06 10:37:08 D/Net 2944284735: unknown PbGetMsg type 528, data=08 91 02 12 C5 01 08 01 12 C0 01 08 BC CF 88 B0 06 12 05 08 F9 0F 10 14 1A 05 08 F9 0F 10 15 22 15 E6 9D A5 E8 87 AA E7 BE A4 EF BC 9A E9 BB 91 E7 89 9B E7 BE A4 32 09 E5 B0 8F E4 BA 8C E9 83 9E 3A 00 42 00 4A 00 52 00 58 78 62 00 6A 14 73 70 5F 61 6C 67 69 64 3D 37 30 37 26 72 69 64 3D 31 31 33 72 00 78 00 80 01 FF FF 03 8A 01 00 92 01 2C 72 37 62 6C 49 42 58 43 6C 39 59 63 53 6C 54 2F 6A 61 43 7A 4D 69 4D 43 50 62 57 55 79 59 6C 73 53 4C 35 54 31 4C 62 67 51 72 34 3D 9A 01 2A 0A 11 31 20 E4 BD 8D E5 85 B1 E5 90 8C E5 A5 BD E5 8F 8B 12 09 08 FF 01 10 FF 01 18 FF 01 1A 08 08 FF 01 10 C6 01 18 19 20 01[0m
[0m2021-09-06 10:37:11 V/Net 2944284735: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-09-06 10:37:11 V/Net 2944284735: Recv: MessageSvc.PbSendMsg[0m
[0m2021-09-06 10:37:14 V/Net 2944284735: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-09-06 10:37:15 V/Net 2944284735: Recv: MessageSvc.PbSendMsg[0m
[0m2021-09-06 10:37:18 V/Net 2944284735: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-09-06 10:37:18 V/Net 2944284735: Recv: MessageSvc.PbSendMsg[0m
```

**Comment by sandtechnology** [comment]
#1410 已经在2.8-M1快照中修复

**Comment by sandtechnology** [comment]
使用方法：https://github.com/mamoe/mirai/blob/f90320bd2b6e942b92b83b39a8bbd0b2bca01bff/docs/UsingSnapshots.md

**Comment by fwfmiao** [comment]
2.8.0-M1-dev-b451dfaf
我通过Snapshot获取到了最新版本的mirai，还是会报这个错误
9月 11 10:48:16 PLA-SITE java[15763]: 2021-09-11 10:48:16 E/Net xxxxxxxx: Exception in decoding packet.
9月 11 10:48:16 PLA-SITE java[15763]: java.util.NoSuchElementException: group 2156903936
9月 11 10:48:16 PLA-SITE java[15763]:         at net.mamoe.mirai.Bot.getGroupOrFail(Bot.kt:141)
临时好友发消息就是会这样=。=
