### ISSUE TITLE
以 `pad` 协议登录时, 无法获得来自私聊的音频的下载链接

### ISSUE THREAD

**Issue by 4o4E** [mamoe/mirai#1537]
无法获得音频链接
代码
```
for (SingleMessage sm : e.getMessage()) {
    if (sm instanceof OnlineAudio) logger.info("url: {}", ((OnlineAudio) sm).getUrlForDownload());
}
```

#### 日志
```
[18:45:29.371] [net.mamoe.mirai.Bot/ERROR] Exception in unnamed coroutine.
net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:147) ~[BotLibV4.jar:?]
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:1) ~[BotLibV4.jar:?]
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:154) ~[BotLibV4.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[BotLibV4.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[BotLibV4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[BotLibV4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[BotLibV4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[BotLibV4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[BotLibV4.jar:?]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140) ~[BotLibV4.jar:?]
	... 8 more
Caused by: java.lang.UnsupportedOperationException: Could not fetch URL for audio 99034A2E23A9AEBA711ABA06C8AA8ED7.amr
	at net.mamoe.mirai.internal.message.OnlineAudioImpl.getUrlForDownload(OnlineAudioImpl.kt:118) ~[BotLibV4.jar:?]
	at com.author404e.bot.cmd.CommandParser.privateHandler(CommandParser.java:81) ~[BotV4.jar:?]
	at com.author404e.bot.util.EventHandlers.friend(EventHandlers.java:75) ~[BotV4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140) ~[BotLibV4.jar:?]
	... 8 more
```

#### 版本及相关选项选择

- mirai-core: `2.7.0` 
- bot-protocol: `ANDROID_PAD`

**Comment by Karlatemp** [comment]
请问触发的条件是:

- 发送者客户端类型 & 版本号
- 私聊 or 群聊

**Comment by Karlatemp** [comment]
未能复现的环境

- 群聊 & PC QQ
- 群聊 & Android QQ
- 群聊 & 另一个 mirai
- 私聊 & PC QQ
- 私聊 & Android QQ

**Comment by 4o4E** [comment]
> 未能复现的环境
> 
> * 群聊 & PC QQ
> * 群聊 & Android QQ
> * 群聊 & 另一个 mirai
> * 私聊 & PC QQ
> * 私聊 & Android QQ

安卓客户端私聊发送的语音无法获取链接，与bot是好友关系
发送者qq版本8.8.28.6095
bot版本2.7.1-dev-1，协议是pad
