### ISSUE TITLE
Android上运行崩溃

### ISSUE THREAD

**Issue by Freedom0925** [mamoe/mirai#154]
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-8
    Process: com.yiyun6.bot, PID: 29947
    java.lang.ExceptionInInitializerError
        at net.mamoe.mirai.utils.cryptor.ECDHAndroidKt.ECDH(ECDHAndroid.kt:34)
        at net.mamoe.mirai.qqandroid.network.QQAndroidClient.<init>(QQAndroidClient.kt:51)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.<init>(QQAndroidBot.kt:58)
        at net.mamoe.mirai.qqandroid.QQAndroidBot.<init>(QQAndroidBot.kt:33)
        at net.mamoe.mirai.qqandroid.QQAndroid.newBot(QQAndroid.kt:27)
     
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
     Caused by: java.lang.IllegalStateException: cannot init BouncyCastle
        at net.mamoe.mirai.utils.cryptor.ECDH.<clinit>(ECDHAndroid.kt:60)
        at net.mamoe.mirai.utils.cryptor.ECDHAndroidKt.ECDH(ECDHAndroid.kt:34) 
        at net.mamoe.mirai.qqandroid.network.QQAndroidClient.<init>(QQAndroidClient.kt:51) 
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.<init>(QQAndroidBot.kt:58) 
        at net.mamoe.mirai.qqandroid.QQAndroidBot.<init>(QQAndroidBot.kt:33) 
        at net.mamoe.mirai.qqandroid.QQAndroid.newBot(QQAndroid.kt:27) 
    
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) 
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) 
     Caused by: java.lang.NoSuchFieldException: No field PROVIDER_NAME in class Lcom/android/org/bouncycastle/jce/provider/BouncyCastleProvider; (declaration of 'com.android.org.bouncycastle.jce.provider.BouncyCastleProvider' appears in /apex/com.android.runtime/javalib/bouncycastle.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at net.mamoe.mirai.utils.cryptor.ECDH.<clinit>(ECDHAndroid.kt:51)
        at net.mamoe.mirai.utils.cryptor.ECDHAndroidKt.ECDH(ECDHAndroid.kt:34) 
        at net.mamoe.mirai.qqandroid.network.QQAndroidClient.<init>(QQAndroidClient.kt:51) 
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.<init>(QQAndroidBot.kt:58) 
        at net.mamoe.mirai.qqandroid.QQAndroidBot.<init>(QQAndroidBot.kt:33) 
        at net.mamoe.mirai.qqandroid.QQAndroid.newBot(QQAndroid.kt:27)

**Comment by Him188** [comment]
Android版本是多少？尝试换更新的版本试试？

**Comment by Freedom0925** [comment]
compileSdkVersion 29，targetSdkVersion 29.
从日志上看和Android版本没啥关系

**Comment by Freedom0925** [comment]
![image](https://user-images.githubusercontent.com/10308687/77249814-ab123e00-6c7e-11ea-8212-531563604004.png)
反射调用时抛出异常
