### ISSUE TITLE
无法编译 Android Studio  Arctic Fox | 2020.3.1 

### ISSUE THREAD

**Issue by BadDeveloper2022** [mamoe/mirai#1542]
无法编译 Android Studio  Arctic Fox | 2020.3.1 
请问最新版在哪个版本编译比较好

**Comment by BadDeveloper2022** [comment]
warning: default scripting plugin is disabled: The provided plugin org.jetbrains.kotlin.scripting.compiler.plugin.ScriptingCompilerConfigurationComponentRegistrar is not compatible with this version of compiler
error: unable to evaluate script, no scripting plugin loaded

**Comment by Him188** [comment]
`./gradlew build`

**Comment by BadDeveloper2022** [comment]
[92m2021-09-11 16:28:15 I/Net 1309661337: ECDH key is invalid, start to fetch ecdh public key from server.uni:1309661337[0m
[31m2021-09-11 16:28:15 E/Net 1309661337: Failed to fetch ECDH public key from server, using default key instead
java.util.concurrent.CancellationException: Bot closed
        at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt:78)
        at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt)
        at kotlinx.coroutines.JobSupport.invokeOnCompletion(JobSupport.kt:1571)
        at kotlinx.coroutines.Job$DefaultImpls.invokeOnCompletion$default(Job.kt:353)
        at io.ktor.client.engine.HttpClientEngineJvmKt.createCallContext(HttpClientEngineJvm.kt:26)
        at io.ktor.client.engine.HttpClientEngine$DefaultImpls.executeWithinCallContext(HttpClientEngine.kt:77)
        at io.ktor.client.engine.HttpClientEngine$install$1.invokeSuspend(HttpClientEngine.kt:66)
        at io.ktor.client.engine.HttpClientEngine$install$1.invoke(HttpClientEngine.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.client.features.HttpSend$DefaultSender.execute(HttpSend.kt:128)
        at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:92)
        at io.ktor.client.features.HttpSend$Feature$install$1.invoke(HttpSend.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:123)
        at io.ktor.client.features.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:86)
        at io.ktor.client.features.HttpCallValidator$Companion$install$1.invoke(HttpCallValidator.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.client.features.HttpRequestLifecycle$Feature$install$1.invokeSuspend(HttpRequestLifecycle.kt:37)
        at io.ktor.client.features.HttpRequestLifecycle$Feature$install$1.invoke(HttpRequestLifecycle.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:243)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:113)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:133)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
        at io.ktor.client.HttpClient.execute(HttpClient.kt:188)
        at io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:104)
        at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl.refreshInitialPublicKeyAndApplyECDH(EcdhInitialPublicKeyUpdater.kt:140)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:121)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$1.invokeSuspend(NettyNetworkHandler.kt:257)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m

**Comment by BadDeveloper2022** [comment]
Failed to fetch ECDH public key from server
但是这个地址浏览器打开 正常呢

**Comment by BadDeveloper2022** [comment]
![image](https://user-images.githubusercontent.com/7404699/132942213-484d7f5b-54f8-4e27-ad77-ba4b45ca2e80.png)

**Comment by Him188** [comment]
网络波动, 正常. 与该 issue 无关
