### ISSUE TITLE
NoSuchMethodError: kotlinx.coroutines.channels.Channel.trySend-JP2dKIU(Ljava/lang/Object;)Ljava/lang/Object;

### ISSUE THREAD

**Issue by BadDeveloper2022** [mamoe/mirai#1544]
登录报错
  final Bot bot = BotFactory.INSTANCE.newBot(NumberUtil.parseLong(qqnum), QQPWD, new BotConfiguration() {
                {
                    //保存设备信息到文件
                    fileBasedDeviceInfo(qqnum + ".json");

                    // setLoginSolver();
                    // setBotLoggerSupplier();
                }
            });
            bot.getConfiguration().setProtocol(BotConfiguration.MiraiProtocol.ANDROID_PAD);
            bot.login();

错误-----------
2021-09-11 17:08:13 E/Net 1309661337: Exception in coroutine 'unnamed'
kotlinx.coroutines.CompletionHandlerException: Exception in completion handler InvokeOnCompletion[InvokeOnCompletion@17ca5aa8] for DeferredCoroutine{Cancelled}@52b6cb8a
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1536)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NoSuchMethodError: kotlinx.coroutines.channels.Channel.trySend-JP2dKIU(Ljava/lang/Object;)Ljava/lang/Object;
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:263)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$2.invoke(NettyNetworkHandler.kt:395)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$2.invoke(NettyNetworkHandler.kt:259)
	at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1386)
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1531)
	... 12 more

------------------------
版本 
mirai: 最新版
JDK 1.8
<kotlin.version>1.5.30</kotlin.version>
<ktor.version>1.5.3</ktor.version>

**Comment by Him188** [comment]
Caused by: java.lang.NoSuchMethodError: kotlinx.coroutines.channels.Channel.trySend-JP2dKIU(Ljava/lang/Object;)Ljava/lang/Object;

你的依赖有问题，运行时使用了旧版本 kotlinx coroutines
