### ISSUE TITLE
登录提示当前版本过低

### ISSUE THREAD

**Issue by kuresaru** [mamoe/mirai#1554]
之前一直在用2.6-RC 之后因为不能发图原因升级到2.7.1-dev-1  帐号和device.json都没变 现在登录提示当前版本过低

```

```

#### 复现

2.6-RC和2.7.0正常登录, 2.7.1-dev-1无法登录

#### 版本及相关选项选择

- mirai-core: `2.7.1-dev-1` 
- bot-protocol: `ANDROID_PAD` 

- spring-boot: `2.5.4`

#### 网络日志

```
2021-09-14 14:19:18.232 [DefaultDispatcher-worker-2] TRACE [top.scraft.robitgw.MiraiLogger] - Network/No server list cached.
2021-09-14 14:19:19.118 [DefaultDispatcher-worker-2] INFO  [top.scraft.robitgw.MiraiLogger] - Network/ECDH key is invalid, start to fetch ecdh public key from server.
2021-09-14 14:19:19.848 [DefaultDispatcher-worker-2] INFO  [top.scraft.robitgw.MiraiLogger] - Network/Successfully fetched ecdh public key from server.
2021-09-14 14:19:19.978 [DefaultDispatcher-worker-2] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: wtlogin.login
2021-09-14 14:19:20.230 [DefaultDispatcher-worker-2] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: wtlogin.login
2021-09-14 14:19:20.231 [DefaultDispatcher-worker-1] WARN  [top.scraft.robitgw.MiraiLogger] - Network/null
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(906021525), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=^@)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-09-14 14:19:20.262 [DefaultDispatcher-worker-2] INFO  [top.scraft.robitgw.MiraiLogger] - Mirai/Bot cancelled: Bot closed
```

**Comment by Nambers** [comment]
net.mamoe.mirai.network.WrongPasswordException检查下密码
然后看看这里试一下? https://mirai.mamoe.net/topic/220/%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%99%BB%E5%BD%95%E4%B8%8D%E4%BA%86-%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81%E6%B2%A1%E9%94%99/2

**Comment by kuresaru** [comment]
> net.mamoe.mirai.network.WrongPasswordException检查下密码
> 然后看看这里试一下? https://mirai.mamoe.net/topic/220/%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%99%BB%E5%BD%95%E4%B8%8D%E4%BA%86-%E8%B4%A6%E5%8F%B7%E5%AF%86%E7%A0%81%E6%B2%A1%E9%94%99/2

密码是10位, 但是是4种组合
然后还有一些特殊需要我只能用pad协议....

**Comment by kuresaru** [comment]
经过测试，相同程序配置更换B帐号可以登录，A帐号就提示版本过低。
A帐号手机和电脑官方客户端都能正常登录，Mirai的三个协议都不能登录，更换device.json也不行，更换电脑也不行，密码改成和B帐号一样的还是不行。

**Comment by kuresaru** [comment]
2.8.0-M1还是不能用

**Comment by kuresaru** [comment]
疑似是我自己程序的问题 等我试着修复一下。。

**Comment by kuresaru** [comment]
问题已自行解决。
1. 项目架构原因不能使用自带的LoginSolver，自己实现了一个LoginSolver但是没有支持滑动验证码(onSolveSliderCaptcha)
2. 在java启动参数里加上-Dmirai.slider.captcha.supported，标记支持使用滑动验证（之前因为报告不支持所以提示版本低）
3. 实现滑动验证码处理逻辑，拿到验证url，使用滑动验证助手(TxCaptchaHelper)取得ticket并返回。
4. 当时为了方便，--在电脑上用安卓模拟器打开并验证，验证一直不能通过--，但在真实安卓手机上验证可以通过。
5. 开发环境电脑登录成功，把device.json复制到服务器，服务器登录成功。
