### ISSUE TITLE
登陆新的QQ号重复登陆，不能主动发消息

### ISSUE THREAD

**Issue by Andy-shi001** [mamoe/mirai#1563]
登陆新的QQ号重复登陆，不能主动发消息

错误日志信息如下：
```
  10:12:14 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  10:12:14 [INFO] https://github.com/iTXTech/mirai-console-loader
  10:12:14 [INFO] This program is licensed under GNU AGPL v3
  10:12:15 [INFO] Fetching Mirai Console Loader Announcement...
  10:12:16 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

关于 Bot is closed manually
https://mirai.mamoe.net/topic/604/

  10:12:16 [INFO] Verifying "net.mamoe:mirai-console" v2.7.1-dev-1
  10:12:16 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.7.1-dev-1
  10:12:16 [INFO] Verifying "net.mamoe:mirai-core-all" v2.7.1-dev-1
  10:12:16 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
2021-09-18 10:12:18 I/main: Starting mirai-console...
2021-09-18 10:12:18 I/main: Backend: version 2.7.1-dev-1, built on 2021-09-09 18
:29:51.
2021-09-18 10:12:18 I/main: Frontend Terminal: version 2.7.1-dev-1, provided by
Mamoe Technologies
2021-09-18 10:12:18 I/main: Welcome to visit https://mirai.mamoe.net/
2021-09-18 10:12:18 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2021-09-18 10:12:18 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-htt
p v1.12.0
2021-09-18 10:12:19 I/main: Prepared built-in commands: autoLogin, help, login,
permission, status, stop
2021-09-18 10:12:19 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
2021-09-18 10:12:19 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit t
he key
2021-09-18 10:12:19 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 19
2.168.32.220:8063
2021-09-18 10:12:19 I/Mirai HTTP API: Http api server is running with authKey: I
NITKEYypJDKe8L
2021-09-18 10:12:19 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
2021-09-18 10:12:19 I/net.mamoe.mirai-api-http: 上报模块启用状态: false
2021-09-18 10:12:19 I/main: 2 plugin(s) enabled.
2021-09-18 10:12:19 I/main: mirai-console started successfully.
2021-09-18 10:12:23 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框.
 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2021-09-18 10:12:23 I/Mirai: Mirai is using desktop. Captcha will be thrown by w
indow popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-deskto
p) to disable it.
2021-09-18 10:12:24 W/stderr: ERROR StatusLogger Log4j2 could not find a logging
 implementation. Please add log4j-core to the classpath. Using SimpleLogger to l
og to the console...

2021-09-18 10:12:24 I/Bot.1849694938: Loaded account secrets from local cache.
2021-09-18 10:12:24 I/Bot.1849694938: Saved account secrets to local cache for f
ast login.
2021-09-18 10:12:25 I/Bot.1849694938: Login successful.
2021-09-18 10:12:26 I/Bot.1849694938: Saved account secrets to local cache for f
ast login.
2021-09-18 10:12:26 I/Bot.1849694938: Login successful.
2021-09-18 10:12:29 I/Bot.1849694938: Saved account secrets to local cache for f
ast login.
2021-09-18 10:12:29 I/Bot.1849694938: Login successful.
2021-09-18 10:12:34 E/main: Exception in coroutine Bot 1849694938.MessageSvcSync
erImpl
java.lang.IllegalStateException: NetworkHandler is already closed.
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$State
Closed.sendPacketImpl(NettyNetworkHandler.kt:393)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.sendP
acketImpl(NettyNetworkHandler.kt:41)
        at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.sendAn
dExpect(NetworkHandlerSupport.kt:99)
        at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$sendAn
dExpect$1.invokeSuspend(NetworkHandlerSupport.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:
102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:665)
        Suppressed: kotlinx.coroutines.TimeoutCancellationException: Timed out w
aiting for 5000 ms
                at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Tim
eout.kt:186)
                at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
                at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(
EventLoop.common.kt:497)
                at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLo
op.common.kt:274)
                at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)

                at java.base/java.lang.Thread.run(Unknown Source)
```
#### 复现
登陆后一直循环登陆

#### 版本及相关选项选择
10:14:20 [INFO] Verifying "net.mamoe:mirai-console" v2.7.1-dev-1
10:14:20 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.7.1-dev-1
10:14:20 [INFO] Verifying "net.mamoe:mirai-core-all" v2.7.1-dev-1
10:14:21 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2

**Comment by Him188** [comment]
看起来会在 2.11.0-RC 解决

**Comment by Him188** [comment]
应该和 https://github.com/mamoe/mirai/issues/1907 一样
