### ISSUE TITLE
更新后启动老是会报一个错，然后连不上

### ISSUE THREAD

**Issue by aion1998** [mamoe/mirai#1586]
## 错误输出日志
```
2021-09-27 10:56:18 E/Mirai HTTP API: java.lang.NoSuchMethodError: 'double kotli
n.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java
.util.concurrent.TimeUnit)'
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.k
t:48)
        at net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.k
t)
        at io.ktor.features.CORS$Feature.install(CORS.kt:517)
        at io.ktor.features.CORS$Feature.install(CORS.kt:509)
        at io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.k
t:68)
        at net.mamoe.mirai.api.http.route.BaseRouteKt.mirai(BaseRoute.kt:45)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiH
ttpAPIServer.kt:93)
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiH
ttpAPIServer.kt:29)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantia
teAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:303)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApp
lication(ApplicationEngineEnvironmentReloading.kt:138)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(App
licationEngineEnvironmentReloading.kt:270)
        at io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(C
IOApplicationEngine.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:665)

```

## 图例

![image](https://user-images.githubusercontent.com/19725014/134839173-65fa5faa-c286-4786-9c90-baa0a8f7494d.png)

## 问题情况

登录是可以登录的，控制台也会接收消息，但是就是之前通过http调这个的一些程序全都连接不上了，统一连接超时

**Comment by aion1998** [comment]
重新下载安装，也是一样..
是不是 mirai-api-http 插件出了啥问题？

**Comment by Nambers** [comment]
https://github.com/mamoe/mirai/issues/1535
