### ISSUE TITLE
部分图片无法发送，出现Unsupported image type for ExternalResource，considering use gif/png/bmp/jpg format.

### ISSUE THREAD

**Issue by Nekoer** [mamoe/mirai#1593]
java.lang.IllegalArgumentException: Unsupported image type for ExternalResource kotlinx.io.streams.InputStreamAsInput@5f0f3ec3, considering use gif/png/bmp/jpg format.

```
java.lang.IllegalArgumentException: Unsupported image type for ExternalResource kotlinx.io.streams.InputStreamAsInput@5f0f3ec3, considering use gif/png/bmp/jpg format.
        at net.mamoe.mirai.internal.message.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:159)
        at net.mamoe.mirai.internal.contact.GroupImpl$uploadImage$lambda-17$$inlined$runBIO$1.invoke(CoroutineUtils.kt:164)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

#### 复现

图片地址

- https://konachan.com/image/9e84de1edf528ffeaecc63493930260e/Konachan.com%20-%20332026%20animal_ears%20anthropomorphism%20ass%20braids%20breasts%20brown_hair%20kokoa_ninniku%20long_hair%20nipples%20pussy%20sweep_tosho%20swimsuit%20tail%20uncensored.jpg
![image](https://user-images.githubusercontent.com/32485369/135743237-be17e273-5bf8-4063-a2e4-91f1c8170023.png)

- https://files.yande.re/jpeg/037a6c8c7e5a7725a661212315e59652/yande.re%20844094%20anchorage_%28azur_lane%29%20artist_revision%20asamura_hiori%20azur_lane%20breast_grab%20cum%20nipples%20paizuri%20penis%20topless%20uncensored%20wet.jpg
![image](https://user-images.githubusercontent.com/32485369/135743226-edbd3c46-c26b-4895-afd4-441babb04a7c.png)

#### 版本及相关选项选择

- mirai-core: `2.8.0-M1` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```
[0m2021-10-03 14:32:13 V/Net 3123930141: Loading server list from cache.[0m
[92m2021-10-03 14:32:13 I/Net 3123930141: Server list: 36.155.249.100:14000, 36.155.228.147:80, 120.232.19.144:8080, 111.30.179.153:80, 111.30.181.58:80, 36.155.229.203:8080, msfwifi.3g.qq.com:8080, 111.30.169.93:80, 120.232.18.28:443, 111.30.179.153:8080.[0m
[92m2021-10-03 14:32:15 I/Net 3123930141: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2021-10-03 14:32:16 I/Net 3123930141: Successfully fetched ecdh public key from server.[0m
[0m2021-10-03 14:32:16 V/Net 3123930141: Send: wtlogin.login[0m
[0m2021-10-03 14:32:17 V/Net 3123930141: Send: wtlogin.login[0m
[0m2021-10-03 14:32:17 V/Net 3123930141: Recv: wtlogin.login[0m
[0m2021-10-03 14:32:17 V/Net 3123930141: Recv: wtlogin.login[0m
[0m2021-10-03 14:32:17 V/Net 3123930141: Send: StatSvc.register(online)[0m
[92m2021-10-03 14:32:18 I/Net 3123930141: Server time updated, serverTime: 1633242757, diff: 19ms=0.019s[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Recv: StatSvc.register[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Loading BdhSession from cache file[0m
[92m2021-10-03 14:32:18 I/Net 3123930141: Syncing friend message history...[0m
[92m2021-10-03 14:32:18 I/Net 3123930141: Start loading stranger list...[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[92m2021-10-03 14:32:18 I/Net 3123930141: Start loading friend list...[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Recv: StatSvc.GetDevLoginInfo[0m
[92m2021-10-03 14:32:18 I/Net 3123930141: No OtherClient online.[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Recv: OidbSvc.0x5d2_0[0m
[92m2021-10-03 14:32:18 I/Net 3123930141: Successfully loaded stranger list: 12 in total[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Recv: OidbSvc.0x496[0m
[92m2021-10-03 14:32:18 I/Net 3123930141: Start loading group list...[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[92m2021-10-03 14:32:18 I/Net 3123930141: Syncing friend message history: Success.[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Loading friend list: 14/14[0m
[92m2021-10-03 14:32:18 I/Net 3123930141: Successfully loaded friend list: 14 in total[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Recv: friendlist.getFriendGroupList[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Recv: friendlist.GetTroopListReqV2[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:32:18 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:32:19 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:32:19 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:32:19 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:32:19 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:32:19 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:32:19 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:32:19 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:32:19 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:32:19 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:32:19 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:32:20 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:32:20 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[92m2021-10-03 14:32:20 I/Net 3123930141: Successfully loaded group list: 9 in total.[0m
[92m2021-10-03 14:32:20 I/Net 3123930141: Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2021-10-03 14:32:20 I/Net 3123930141: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2021-10-03 14:32:20 I/Net 3123930141: Server list: 221.198.70.152:14000, 203.205.232.58:443, msfwifi.3g.qq.com:8080, 113.96.13.79:80, 203.205.255.218:8080, 36.155.249.126:443, 203.205.255.221:8080.[0m
[0m2021-10-03 14:32:20 V/Net 3123930141: Saving bdh session to cache[0m
[0m2021-10-03 14:32:20 V/Net 3123930141: Saving server list to cache[0m
[0m2021-10-03 14:32:21 V/Net 3123930141: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2021-10-03 14:32:21 V/Net 3123930141: Recv: ConfigPushSvc.PushReq[0m
[0m2021-10-03 14:32:21 V/Net 3123930141: Saving bdh session to cache[0m
[0m2021-10-03 14:32:21 V/Net 3123930141: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2021-10-03 14:32:21 V/Net 3123930141: Recv: ConfigPushSvc.PushReq[0m
[0m2021-10-03 14:32:38 V/Net 3123930141: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-10-03 14:32:39 V/Net 3123930141: Recv: MessageSvc.PbSendMsg[0m
[0m2021-10-03 14:32:49 V/Net 3123930141: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-10-03 14:32:49 V/Net 3123930141: Recv: MessageSvc.PbSendMsg[0m
[0m2021-10-03 14:32:59 V/Net 3123930141: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-10-03 14:32:59 V/Net 3123930141: Recv: MessageSvc.PbSendMsg[0m
[0m2021-10-03 14:33:09 V/Net 3123930141: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-10-03 14:33:09 V/Net 3123930141: Recv: MessageSvc.PbSendMsg[0m
[0m2021-10-03 14:33:17 V/Net 3123930141: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-10-03 14:33:17 V/Net 3123930141: Recv: MessageSvc.PbSendMsg[0m
[0m2021-10-03 14:33:28 V/Net 3123930141: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-10-03 14:33:28 V/Net 3123930141: Recv: MessageSvc.PbSendMsg[0m
[0m2021-10-03 14:38:03 V/Net 3123930141: Send: StatSvc.register(offline)[0m
[0m2021-10-03 14:38:32 V/Net 3123930141: Loading server list from cache.[0m
[92m2021-10-03 14:38:32 I/Net 3123930141: Server list: 221.198.70.152:14000, 203.205.232.58:443, msfwifi.3g.qq.com:8080, 113.96.13.79:80, 203.205.255.218:8080, 36.155.249.126:443, 203.205.255.221:8080.[0m
[92m2021-10-03 14:38:34 I/Net 3123930141: ECDH key is valid.[0m
[0m2021-10-03 14:38:35 V/Net 3123930141: Send: wtlogin.exchange_emp[0m
[0m2021-10-03 14:38:35 V/Net 3123930141: Recv: wtlogin.exchange_emp[0m
[0m2021-10-03 14:38:35 V/Net 3123930141: Send: StatSvc.register(online)[0m
[92m2021-10-03 14:38:35 I/Net 3123930141: Server time updated, serverTime: 1633243134, diff: 19ms=0.019s[0m
[0m2021-10-03 14:38:35 V/Net 3123930141: Recv: StatSvc.register[0m
[0m2021-10-03 14:38:35 V/Net 3123930141: Loading BdhSession from cache file[0m
[92m2021-10-03 14:38:35 I/Net 3123930141: Syncing friend message history...[0m
[0m2021-10-03 14:38:36 V/Net 3123930141: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[92m2021-10-03 14:38:36 I/Net 3123930141: Start loading friend list...[0m
[92m2021-10-03 14:38:36 I/Net 3123930141: Start loading stranger list...[0m
[0m2021-10-03 14:38:36 V/Net 3123930141: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2021-10-03 14:38:36 V/Net 3123930141: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2021-10-03 14:38:36 V/Net 3123930141: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2021-10-03 14:38:36 V/Net 3123930141: Recv: StatSvc.GetDevLoginInfo[0m
[92m2021-10-03 14:38:36 I/Net 3123930141: No OtherClient online.[0m
[0m2021-10-03 14:38:36 V/Net 3123930141: Recv: OidbSvc.0x496[0m
[92m2021-10-03 14:38:36 I/Net 3123930141: Start loading group list...[0m
[0m2021-10-03 14:38:36 V/Net 3123930141: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2021-10-03 14:38:36 V/Net 3123930141: Loading friend list: 14/14[0m
[92m2021-10-03 14:38:36 I/Net 3123930141: Successfully loaded friend list: 14 in total[0m
[0m2021-10-03 14:38:36 V/Net 3123930141: Recv: friendlist.getFriendGroupList[0m
[0m2021-10-03 14:38:36 V/Net 3123930141: Recv: OidbSvc.0x5d2_0[0m
[92m2021-10-03 14:38:36 I/Net 3123930141: Successfully loaded stranger list: 12 in total[0m
[92m2021-10-03 14:38:36 I/Net 3123930141: Syncing friend message history: Success.[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Recv: friendlist.GetTroopListReqV2[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:38:37 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:38:38 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:38:38 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:38:38 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:38:38 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:38:38 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:38:38 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:38:38 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:38:38 V/Net 3123930141: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-03 14:38:38 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-03 14:38:38 V/Net 3123930141: Recv: friendlist.GetTroopMemberListReq[0m
[92m2021-10-03 14:38:38 I/Net 3123930141: Successfully loaded group list: 9 in total.[0m
[92m2021-10-03 14:38:39 I/Net 3123930141: Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2021-10-03 14:38:39 I/Net 3123930141: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[0m2021-10-03 14:38:39 V/Net 3123930141: Saving bdh session to cache[0m
[0m2021-10-03 14:38:39 V/Net 3123930141: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2021-10-03 14:38:39 V/Net 3123930141: Recv: ConfigPushSvc.PushReq[0m
[0m2021-10-03 14:38:47 V/Net 3123930141: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2021-10-03 14:38:47 V/Net 3123930141: Recv: MessageSvc.PbSendMsg[0m

```

**Comment by Karlatemp** [comment]
提供一下发送时使用的代码

**Comment by Nekoer** [comment]
> 提供一下发送时使用的代码
https://github.com/Nekoer/mirai-plugins-pixiv/blob/master/src/main/kotlin/sexy/SexyCenter.kt

```
suspend fun konachan(event: GroupMessageEvent, logger: MiraiLogger) {
        try {
            val list = arrayOf("topless", "nipples", "no_bra")
            val randoms: Int = (0 until (list.size - 1)).random()
            val obj = RequestUtil.requestArray(
                RequestUtil.Companion.Method.GET,
                "https://konachan.com/post.json?limit=500&tags=${list[randoms]}",
                requestBody,
                headers.build(),
                logger
            )
            val num: Int = (0 until (obj!!.size - 1)).random()
            val id = JSONObject.parseObject(obj[num].toString()).getString("id")
            val jpegUrl = JSONObject.parseObject(obj[num].toString()).getString("jpeg_url")
            val toExternalResource = ImageUtil.getImage(jpegUrl).toByteArray().toExternalResource()
            val imageId: String = toExternalResource.uploadAsImage(event.group).imageId
            toExternalResource.closeQuietly()
            val quoteReply: QuoteReply = QuoteReply(event.message)

            if (!StringUtils.isBlank(Config.recall.toString())) {
                event.subject.sendMessage(quoteReply.plus(Image(imageId)).plus("来源:KONACHAN($id)"))
                    .recallIn(Config.recall)
            } else {
                event.subject.sendMessage(quoteReply.plus(Image(imageId)).plus("来源:KONACHAN($id)"))
            }
        } catch (e: Exception) {
            event.subject.sendMessage("发送图片失败")
        }
    }
```

**Comment by Karlatemp** [comment]
```kotlin
ImageUtil.getImage(jpegUrl).toByteArray()
.also { println("Img header: " + it.copyOf(30).toUHexString()) }
.toExternalResource()
```

**Comment by Nekoer** [comment]
> ```kotlin
> ImageUtil.getImage(jpegUrl).toByteArray()
> .also { println("Img header: " + it.copyOf(30).toUHexString()) }
> .toExternalResource()
> ```

我这里没有toUHexString()
![image](https://user-images.githubusercontent.com/32485369/135743925-ed1f0dee-de69-4018-8ea8-b3c41e5103c2.png)

**Comment by Karlatemp** [comment]
@Nekoer 临时添加依赖 `net.mamoe:mirai-core-utils:$LATEST`

**Comment by cssxsh** [comment]
这图是 JFIF JPEG format

**Comment by Karlatemp** [comment]
我下载两张图片后都能通过检测所以很奇怪

**Comment by Karlatemp** [comment]
> > ```kotlin
> > ImageUtil.getImage(jpegUrl).toByteArray()
> > .also { println("Img header: " + it.copyOf(30).toUHexString()) }
> > .toExternalResource()
> > ```
> 
> 我这里没有toUHexString() ![image](https://user-images.githubusercontent.com/32485369/135743925-ed1f0dee-de69-4018-8ea8-b3c41e5103c2.png)

![image](https://user-images.githubusercontent.com/30070303/135744092-643da7ad-a81c-42ee-9d45-807057505cf4.png)
加到这个位置，你加后面都报错了咋执行

**Comment by Karlatemp** [comment]
另外 
![image](https://user-images.githubusercontent.com/30070303/135744128-a2591c21-d080-485f-9c79-dc1adcc26e94.png)

**Comment by Nekoer** [comment]
https://files.yande.re/jpeg/5d004452a9bb590ed4de39e39cecf98d/yande.re%20858157%20animal_ears%20nekomimi%20pantsu%20tagme%20topless.jpg

```
suspend fun yande(event: GroupMessageEvent, logger: MiraiLogger) {
        try {
            val list = arrayOf("topless", "nipples", "no_bra")
            val randoms: Int = (0 until (list.size - 1)).random()
            val obj = RequestUtil.requestArray(
                RequestUtil.Companion.Method.GET,
                "https://yande.re/post.json?limit=500&tags=${list[randoms]}",
                requestBody,
                headers.build(),
                logger
            )
            val num: Int = (0 until (obj!!.size - 1)).random()
            val id = JSONObject.parseObject(obj[num].toString()).getString("id")
            val jpegUrl = JSONObject.parseObject(obj[num].toString()).getString("jpeg_url")
            logger.warning(jpegUrl)
            val toExternalResource = ImageUtil.getImage(jpegUrl).toByteArray().also { println("Img header: " + it.copyOf(30).toUHexString()) }.toExternalResource()
            val imageId: String = toExternalResource.uploadAsImage(event.group).imageId
            toExternalResource.close()
            val quoteReply: QuoteReply = QuoteReply(event.message)
            /**
             * 判断是否配置了撤回时间
             */

            if (!StringUtils.isBlank(Config.recall.toString())) {
                event.subject.sendMessage(quoteReply.plus(Image(imageId)).plus("来源:YANDE($id)")).recallIn(Config.recall)
            } else {
                event.subject.sendMessage(quoteReply.plus(Image(imageId)).plus("来源:YANDE($id)"))
            }
        } catch (e: Exception) {
            logger.warning(e)
            event.subject.sendMessage("发送图片失败")
        }
    }
```
![image](https://user-images.githubusercontent.com/32485369/135744250-7721a36f-c1c8-4f57-9396-9b08d36c60dd.png)

依然还是这样

**Comment by Karlatemp** [comment]
![image](https://user-images.githubusercontent.com/30070303/135744305-524d5de7-09ef-4e19-9653-837937df691e.png)
