### ISSUE TITLE
部分图片上传uploadImage时，报错highway transfer failed, error 83

### ISSUE THREAD

**Issue by MengYan89** [mamoe/mirai#1597]
相同的代码获取p站的不同图片，部分图片会发送如下报错，为什么
```
2021-10-05 16:54:27 V/Bot 738344224: Event: BeforeImageUploadEvent(target=Group(910726832), source=net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@644ecf2a)
2021-10-05 16:54:27 V/Net 738344224: Send: ImgStore.GroupPicUp(ImgStore.GroupPicUp)
2021-10-05 16:54:28 V/Net 738344224: [Highway] Uploading group image to 42.81.193.228:14000, size=667.31 KiB
2021-10-05 16:54:28 V/Net 738344224: Recv: ImgStore.GroupPicUp
2021-10-05 16:54:28 V/Net 738344224: [Highway] Uploading group image to 42.81.193.228:14000, size=667.31 KiB failed: java.lang.IllegalStateException: highway transfer failed, error 83
2021-10-05 16:54:28 V/Net 738344224: [Highway] Uploading group image to 183.47.98.80:8080, size=667.31 KiB
2021-10-05 16:54:29 V/Net 738344224: [Highway] Uploading group image to 183.47.98.80:8080, size=667.31 KiB failed: java.lang.IllegalStateException: highway transfer failed, error 83
2021-10-05 16:54:29 V/Net 738344224: [Highway] Uploading group image to 42.81.184.123:80, size=667.31 KiB
2021-10-05 16:54:29 V/Net 738344224: [Highway] Uploading group image to 42.81.184.123:80, size=667.31 KiB failed: java.lang.IllegalStateException: highway transfer failed, error 83
2021-10-05 16:54:29 V/Net 738344224: [Highway] Uploading group image to 180.110.193.191:443, size=667.31 KiB
2021-10-05 16:54:30 V/Net 738344224: [Highway] Uploading group image to 180.110.193.191:443, size=667.31 KiB failed: java.lang.IllegalStateException: highway transfer failed, error 83
2021-10-05 16:54:30.562 ERROR 1 --- [nio-8085-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.IllegalStateException: cannot upload group image, failed on all servers.] with root cause
java.lang.IllegalStateException: highway transfer failed, error 83
        at net.mamoe.mirai.internal.network.highway.HighwayKt.sendReceiveHighway(Highway.kt:363) ~[mirai-core-jvm-2.7.1.jar!/:2.7.1]
        at net.mamoe.mirai.internal.network.highway.HighwayKt.access$sendReceiveHighway(Highway.kt:1) ~[mirai-core-jvm-2.7.1.jar!/:2.7.1]
        at net.mamoe.mirai.internal.network.highway.HighwayKt$sendReceiveHighway$1.invokeSuspend(Highway.kt) ~[mirai-core-jvm-2.7.1.jar!/:2.7.1]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.5.31.jar!/:1.5.31-release-548(1.5.31)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.5.2.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[kotlinx-coroutines-core-jvm-1.5.2.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.5.2.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[kotlinx-coroutines-core-jvm-1.5.2.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[kotlinx-coroutines-core-jvm-1.5.2.jar!/:na]
        Suppressed: java.lang.IllegalStateException: highway transfer failed, error 83
                ... 9 common frames omitted
                Suppressed: java.lang.IllegalStateException: highway transfer failed, error 83
                        ... 9 common frames omitted
                        Suppressed: java.lang.IllegalStateException: highway transfer failed, error 83
                                ... 9 common frames omitted
2021-10-05 16:54:30 E/Bot 738344224: Exception in unnamed coroutine.
net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:147)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:1)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140)
        ... 8 more
Caused by: feign.FeignException$InternalServerError: [500] during [POST] to [http://10.96.17.243:8001/message/group] [EngineApi#sendGroupMessage(GroupMessageBean)]: [{"timestamp":"2021-10-05T16:54:30.570+00:00","status":500,"error":"Internal Server Error","message":"","path":"/message/group"}]
        at feign.FeignException.serverErrorStatus(FeignException.java:231)
        at feign.FeignException.errorStatus(FeignException.java:180)
        at feign.FeignException.errorStatus(FeignException.java:169)
        at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92)
        at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96)
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
        at jdk.proxy2/jdk.proxy2.$Proxy79.sendGroupMessage(Unknown Source)
        at com.mengyan.robot.listener.GroupMessageListener.onMessage(GroupMessageListener.java:75)
        ... 13 more
```

#### 复现
通过url获取图片
如:https://i.pixiv.cat/img-master/img/2021/08/16/18/51/16/92032971_p2_master1200.jpg
无法成功发送
```
                URL url = new URL(bean.getMsgDate());
                HttpURLConnection httpUrl = null;
                httpUrl = (HttpURLConnection) url.openConnection();
                httpUrl.setRequestProperty("User-Agent", "Mozilla/4.0 (compatible; MSIE 5.0; Windows NT; DigExt)");
                httpUrl.connect();
                InputStream inputStream = httpUrl.getInputStream();
                imageResource = ExternalResource.create(inputStream);
                group.uploadImage(imageResource);
```

#### 版本及相关选项选择
```
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.7.1</version>
        </dependency>
```

**Comment by MengYan89** [comment]
打扰了，这图。。。QQ客户端都发不出去
