### ISSUE TITLE
bot登陆报错 NoStandardInputForCaptchaException，然后closed

### ISSUE THREAD

**Issue by S-TE11A** [mamoe/mirai#1605]
使用Bot登陆报错NoStandardInputForCaptchaException，/login指令登陆正常

```
[root@localhost mcl]# ./mcl
  17:02:41 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  17:02:41 [INFO] https://github.com/iTXTech/mirai-console-loader
  17:02:41 [INFO] This program is licensed under GNU AGPL v3
  17:02:41 [INFO] Fetching Mirai Console Loader Announcement...
  17:02:42 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

  17:02:42 [INFO] Verifying "net.mamoe:mirai-console" v2.8.0-M1
  17:02:42 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.8.0-M1
  17:02:42 [INFO] Verifying "net.mamoe:mirai-core-all" v2.8.0-M1
  17:02:43 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
2021-10-15 17:02:44 I/main: Starting mirai-console...
2021-10-15 17:02:44 I/main: Backend: version 2.8.0-M1, built on 2021-09-22 17:49:01.
2021-10-15 17:02:44 I/main: Frontend Terminal: version 2.8.0-M1, provided by Mamoe Technologies
2021-10-15 17:02:44 I/main: Welcome to visit https://mirai.mamoe.net/
2021-10-15 17:02:44 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2021-10-15 17:02:44 I/plugin: Successfully loaded plugin 插件示例 v0.1.0
2021-10-15 17:02:44 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-10-15 17:02:44 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
2021-10-15 17:02:44 I/插件示例: Plugin loaded
2021-10-15 17:02:45 I/main: 2 plugin(s) enabled.
2021-10-15 17:02:45 I/main: mirai-console started successfully.
2021-10-15 17:02:45 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2021-10-15 17:02:45 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2021-10-15 17:02:45 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2021-10-15 17:02:45 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2021-10-15 17:02:45 I/Net 3341457967: ECDH key is invalid, start to fetch ecdh public key from server.
2021-10-15 17:02:46 I/Net 3341457967: Successfully fetched ecdh public key from server.
2021-10-15 17:02:46 I/Bot 3341457967: [SliderCaptcha] 需要滑动验证码, 请按照以下链接的步骤完成滑动验证码, 然后输入获取到的 ticket
2021-10-15 17:02:46 I/Bot 3341457967: [SliderCaptcha] Slider captcha required. Please solve the captcha with following link. Type ticket here after completion.
2021-10-15 17:02:46 I/Bot 3341457967: [SliderCaptcha] @see https://github.com/project-mirai/mirai-login-solver-selenium
2021-10-15 17:02:46 I/Bot 3341457967: [SliderCaptcha] @see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
2021-10-15 17:02:46 I/Bot 3341457967: [SliderCaptcha] 或者输入 TxCaptchaHelper 来使用 TxCaptchaHelper 完成滑动验证码
2021-10-15 17:02:46 I/Bot 3341457967: [SliderCaptcha] Or type `TxCaptchaHelper` to resolve slider captcha with TxCaptchaHelper.apk
2021-10-15 17:02:46 I/Bot 3341457967: [SliderCaptcha] Captcha link: https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=3341457967&sid=4439825845764834230&cap_cd=Qv0mkoplgUJuW63bjnGzbtZtFlJppKcIkaDv2-MKjxp4vT0aWjuYQw**&clientype=1&apptype=2
2021-10-15 17:02:47 W/Net 3341457967: net.mamoe.mirai.network.NoStandardInputForCaptchaException: no standard input for captcha
net.mamoe.mirai.network.NoStandardInputForCaptchaException: no standard input for captcha
	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$1.invokeSuspend(LoginSolver.jvm.kt:120)
	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$1.invoke(LoginSolver.jvm.kt)
	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$1.invoke(LoginSolver.jvm.kt)
	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$input$1$1.invokeSuspend(LoginSolver.jvm.kt:132)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-10-15 17:02:47 I/Bot 3341457967: Bot cancelled: Bot closed
2021-10-15 17:02:47 W/stderr: Exception in thread "DefaultDispatcher-worker-1" net.mamoe.mirai.network.NoStandardInputForCaptchaException: no standard input for captcha
2021-10-15 17:02:47 W/stderr: 	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$1.invokeSuspend(LoginSolver.jvm.kt:120)
2021-10-15 17:02:47 W/stderr: 	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$1.invoke(LoginSolver.jvm.kt)
2021-10-15 17:02:47 W/stderr: 	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$1.invoke(LoginSolver.jvm.kt)
2021-10-15 17:02:47 W/stderr: 	at net.mamoe.mirai.utils.StandardCharImageLoginSolver$input$1$1.invokeSuspend(LoginSolver.jvm.kt:132)
2021-10-15 17:02:47 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-10-15 17:02:47 W/stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2021-10-15 17:02:47 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2021-10-15 17:02:47 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2021-10-15 17:02:47 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2021-10-15 17:02:47 W/stderr: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-10-15 17:02:47 W/stderr: 	Suppressed: java.util.concurrent.CancellationException: Bot closed
2021-10-15 17:02:47 W/stderr: 		at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
2021-10-15 17:02:47 W/stderr: 		at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
2021-10-15 17:02:47 W/stderr: 		at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:82)
2021-10-15 17:02:47 W/stderr: 		at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
2021-10-15 17:02:47 W/stderr: 		at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
2021-10-15 17:02:47 W/stderr: 		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2021-10-15 17:02:47 W/stderr: 		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
2021-10-15 17:02:47 W/stderr: 		... 4 more
2021-10-15 17:02:47 W/stderr: 	Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.NoStandardInputForCaptchaException: no standard input for captcha]

```

#### 复现

```
val bot = BotFactory.newBot(qq,"password"){
    fileBasedDeviceInfo()
}

GlobalScope.launch {
    bot.login()
}
```
#### 版本及相关选项选择

- mirai-core, mirai-console: `2.8.0-M1` 
- bot-protocol: `ANDROID_PHONE` 
- System: CentOS Linux release 7.7.1908 (Core)

#### 网络日志

```
[91m2021-10-15 15:59:59 W/Net 3341457967: io.netty.channel.ConnectTimeoutException: connection timed out: /183.232.94.44:80
io.netty.channel.ConnectTimeoutException: connection timed out: /183.232.94.44:80
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@261442f0
	Caused by: [CIRCULAR REFERENCE: io.netty.channel.ConnectTimeoutException: connection timed out: /183.232.94.44:80]
	Suppressed: [CIRCULAR REFERENCE: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@261442f0]
[0m
[0m2021-10-15 15:59:59 V/Net 3341457967: No server list cached.[0m
[92m2021-10-15 15:59:59 I/Net 3341457967: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2021-10-15 15:59:59 I/Net 3341457967: Successfully fetched ecdh public key from server.[0m
[0m2021-10-15 15:59:59 V/Net 3341457967: Send: wtlogin.login[0m
[0m2021-10-15 16:00:00 V/Net 3341457967: Recv: wtlogin.login[0m
[0m2021-10-15 16:00:38 V/Net 3341457967: Send: wtlogin.login[0m
[0m2021-10-15 16:00:38 V/Net 3341457967: Recv: wtlogin.login[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Send: wtlogin.login[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Recv: wtlogin.login[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Send: wtlogin.login[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Recv: wtlogin.login[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Send: StatSvc.register(online)[0m
[92m2021-10-15 16:02:02 I/Net 3341457967: Server time updated, serverTime: 1634284922, diff: 0ms=0.0s[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Recv: StatSvc.register[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: No BdhSession cache[0m
[92m2021-10-15 16:02:02 I/Net 3341457967: Start loading stranger list...[0m
[92m2021-10-15 16:02:02 I/Net 3341457967: Syncing friend message history...[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[92m2021-10-15 16:02:02 I/Net 3341457967: Start loading friend list...[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[92m2021-10-15 16:02:02 I/Net 3341457967: Successfully loaded stranger list: 0 in total[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Recv: OidbSvc.0x5d2_0[0m
[92m2021-10-15 16:02:02 I/Net 3341457967: Start loading group list...[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Recv: OidbSvc.0x496[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Recv: StatSvc.GetDevLoginInfo[0m
[92m2021-10-15 16:02:02 I/Net 3341457967: No OtherClient online.[0m
[92m2021-10-15 16:02:02 I/Net 3341457967: Syncing friend message history: Success.[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Recv: friendlist.getFriendGroupList[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Loading friend list: 3/3[0m
[92m2021-10-15 16:02:02 I/Net 3341457967: Successfully loaded friend list: 3 in total[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Recv: friendlist.GetTroopListReqV2[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2021-10-15 16:02:02 V/Net 3341457967: Recv: friendlist.GetTroopMemberListReq[0m
[0m2021-10-15 16:02:03 V/Net 3341457967: Recv: friendlist.GetTroopMemberListReq[0m
[92m2021-10-15 16:02:03 I/Net 3341457967: Successfully loaded group list: 2 in total.[0m
[92m2021-10-15 16:02:03 I/Net 3341457967: Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2021-10-15 16:02:03 I/Net 3341457967: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2021-10-15 16:02:05 I/Net 3341457967: Server list: 42.81.192.211:443, 125.94.60.148:8080, 42.81.169.46:443, 113.96.12.224:8080, 42.81.170.122:80, msfwifi.3g.qq.com:8080, 180.102.110.67:8080, 114.221.148.67:8080, 180.102.111.105:80, 183.47.98.25:14000.[0m
[0m2021-10-15 16:02:05 V/Net 3341457967: No BdhSession to save to cache[0m
[0m2021-10-15 16:02:05 V/Net 3341457967: Saving server list to cache[0m
[0m2021-10-15 16:02:05 V/Net 3341457967: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2021-10-15 16:02:05 V/Net 3341457967: Recv: ConfigPushSvc.PushReq[0m
[0m2021-10-15 16:02:05 V/Net 3341457967: Saving bdh session to cache[0m
[0m2021-10-15 16:02:05 V/Net 3341457967: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2021-10-15 16:02:05 V/Net 3341457967: Recv: ConfigPushSvc.PushReq[0m
[0m2021-10-15 16:02:13 V/Net 3341457967: Send: StatSvc.register(offline)[0m

```

#### 补充信息

已经使用了device.json 表现没有发生变化

**Comment by S-TE11A** [comment]
![image](https://user-images.githubusercontent.com/20638533/137463297-5f233571-fd8c-46f3-9118-741e10a2743d.png)
使用/login指令登陆正常

**Comment by sandtechnology** [comment]
应该是你指定的 device.json 与输入命令的login使用了的 device.json 不一致，触发了安全验证，导致出现此报错。
而这个报错的原因是没有找到可以支持安全验证的标准输入，请自行实现验证接口

**Comment by S-TE11A** [comment]
> 应该是你指定的 device.json 与输入命令的login使用了的 device.json 不一致，触发了安全验证，导致出现此报错。 而这个报错的原因是没有找到可以支持安全验证的标准输入，请自行实现验证接口

能否指定为一致？ 如果不可以的话，是否有现成的支持安全验证的输入，或者如何实现能否请教一下？

**Comment by S-TE11A** [comment]
> 应该是你指定的 device.json 与输入命令的login使用了的 device.json 不一致，触发了安全验证，导致出现此报错。 而这个报错的原因是没有找到可以支持安全验证的标准输入，请自行实现验证接口

另外，该插件在另一台ubuntu上运行良好， 我将ubuntu上的device.json拉过来依旧报这个exception

**Comment by S-TE11A** [comment]
> 应该是你指定的 device.json 与输入命令的login使用了的 device.json 不一致，触发了安全验证，导致出现此报错。 而这个报错的原因是没有找到可以支持安全验证的标准输入，请自行实现验证接口



是我搞错了device.json的位置，替换了根目录下的device.json后解决了该问题，感谢您的解答

**Comment by sakurawald** [comment]
> 

This works.
