### ISSUE TITLE
使用RemoteFile.upload函数报错：Failed RemoteFile.upload, result=-134, msg=upload check_security fail

### ISSUE THREAD

**Issue by LoseSynchronization** [mamoe/mirai#1612]
在Java中调用RemoteFile.upload方法报错：`java.lang.IllegalStateException: Failed RemoteFile.upload, result=-134, msg=upload check_security fail`
登陆的bot在群里面，而且是管理员，UPLOAD_DIR表示目录也存在，zipFile表示的文件也存在。
代码：
```java
File zipFile = ...;
Group noticeGroup = ...;
String UPLOAD_DIR = "/xxx";
return RemoteFile.uploadFile(noticeGroup, UPLOAD_DIR + "/" + zipFile.getName(), zipFile);
```
同时我也试过使用
```java
noticeGroup.getFilesRoot().resolve(UPLOAD_DIR+"/"+ zipFile.getName()).upload(zipFile);
```
进行上传，但是一样报同样的错误。
下面是异常日志：

```
java.lang.IllegalStateException: Failed RemoteFile.upload, result=-134, msg=upload check_security fail
	at net.mamoe.mirai.internal.utils.RemoteFileImpl.upload0(RemoteFileImpl.kt:452)
	at net.mamoe.mirai.internal.utils.RemoteFileImpl.access$upload0(RemoteFileImpl.kt:102)
	at net.mamoe.mirai.internal.utils.RemoteFileImpl$upload0$1.invokeSuspend(RemoteFileImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:398)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:432)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:421)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:329)
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1412)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806)
	at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:78)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:186)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 版本及相关选项选择

- mirai-core: 2.7.1 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```
[INFO ] 2021-10-17 23:40:44,464 net.mamoe.mirai.Bot.info0: Server list: 42.81.169.46:80, 42.81.184.75:14000, 183.47.99.24:8080, msfwifi.3g.qq.com:8080, 120.232.18.27:443, 180.109.192.45:14000, 157.255.13.53:80, 180.102.111.105:14000.
[INFO ] 2021-10-17 23:40:45,530 net.mamoe.mirai.Bot.info0: Loaded account secrets from local cache.
[INFO ] 2021-10-17 23:40:45,537 net.mamoe.mirai.Bot.info0: ECDH key is valid.
[INFO ] 2021-10-17 23:40:45,846 net.mamoe.mirai.Bot.info0: Saved account secrets to local cache for fast login.
[INFO ] 2021-10-17 23:40:45,963 net.mamoe.mirai.Bot.info0: Login successful.
[INFO ] 2021-10-17 23:40:45,969 net.mamoe.mirai.Bot.info0: Syncing friend message history...
[INFO ] 2021-10-17 23:40:45,973 net.mamoe.mirai.Bot.info0: Start loading stranger list...
[INFO ] 2021-10-17 23:40:45,973 net.mamoe.mirai.Bot.info0: Start loading friend list...
[INFO ] 2021-10-17 23:40:46,062 net.mamoe.mirai.Bot.info0: Start loading group list...
[INFO ] 2021-10-17 23:40:46,089 net.mamoe.mirai.Bot.info0: Successfully loaded stranger list: 0 in total
[INFO ] 2021-10-17 23:40:46,091 net.mamoe.mirai.Bot.info0: No OtherClient online.
[INFO ] 2021-10-17 23:40:46,115 net.mamoe.mirai.Bot.info0: Syncing friend message history: Success.
[INFO ] 2021-10-17 23:40:46,161 net.mamoe.mirai.Bot.info0: Successfully loaded friend list: 3 in total
[INFO ] 2021-10-17 23:40:46,470 net.mamoe.mirai.Bot.info0: Successfully loaded group list: 2 in total.
[INFO ] 2021-10-17 23:40:46,477 net.mamoe.mirai.Bot.info0: Bot login successful.
[INFO ] 2021-10-17 23:40:46,479 net.mamoe.mirai.Bot.info0: Scheduled key refresh in 23h 55min 0.0s.
[INFO ] 2021-10-17 23:40:46,479 net.mamoe.mirai.Bot.info0: Scheduled refresh login session in 19d 23h 55min 0.0s.
[WARN ] 2021-10-17 23:40:57,148 net.mamoe.mirai.Bot.warning0: Connection lost, reconnecting... (NettyChannelException(message=null, cause=null))
[WARN ] 2021-10-17 23:40:57,149 net.mamoe.mirai.Bot.warning0: null
NettyChannelException(message=null, cause=null)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.createConnection$lambda-3(NettyNetworkHandler.kt:158)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1186)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:773)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:749)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:105)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:174)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[INFO ] 2021-10-17 23:40:57,188 net.mamoe.mirai.Bot.info0: Server list: 42.81.169.46:80, 42.81.184.75:14000, 183.47.99.24:8080, msfwifi.3g.qq.com:8080, 120.232.18.27:443, 180.109.192.45:14000, 157.255.13.53:80, 180.102.111.105:14000.
[INFO ] 2021-10-17 23:40:57,188 net.mamoe.mirai.Bot.info0: ECDH key is valid.
[INFO ] 2021-10-17 23:40:57,323 net.mamoe.mirai.Bot.info0: Saved account secrets to local cache for fast login.
[INFO ] 2021-10-17 23:40:57,427 net.mamoe.mirai.Bot.info0: Login successful.
[INFO ] 2021-10-17 23:40:57,428 net.mamoe.mirai.Bot.info0: Scheduled key refresh in 23h 55min 0.0s.
[INFO ] 2021-10-17 23:40:57,428 net.mamoe.mirai.Bot.info0: Scheduled refresh login session in 19d 23h 55min 0.0s.
[INFO ] 2021-10-17 23:40:57,428 net.mamoe.mirai.Bot.info0: Reconnected successfully in 0.279s.
java.lang.IllegalStateException: Failed RemoteFile.upload, result=-134, msg=upload check_security fail
	at net.mamoe.mirai.internal.utils.RemoteFileImpl.upload0(RemoteFileImpl.kt:452)
	at net.mamoe.mirai.internal.utils.RemoteFileImpl.access$upload0(RemoteFileImpl.kt:102)
	at net.mamoe.mirai.internal.utils.RemoteFileImpl$upload0$1.invokeSuspend(RemoteFileImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:398)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:432)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:421)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:329)
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1412)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856)
	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806)
	at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:78)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:186)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[WARN ] 2021-10-17 23:41:17,053 net.mamoe.mirai.Bot.warning0: Connection lost, reconnecting... (NettyChannelException(message=null, cause=null))
[WARN ] 2021-10-17 23:41:17,054 net.mamoe.mirai.Bot.warning0: null
NettyChannelException(message=null, cause=null)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.createConnection$lambda-3(NettyNetworkHandler.kt:158)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1186)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:773)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:749)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:105)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:174)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
[INFO ] 2021-10-17 23:41:17,075 net.mamoe.mirai.Bot.info0: Server list: 42.81.169.46:80, 42.81.184.75:14000, 183.47.99.24:8080, msfwifi.3g.qq.com:8080, 120.232.18.27:443, 180.109.192.45:14000, 157.255.13.53:80, 180.102.111.105:14000.
[INFO ] 2021-10-17 23:41:17,076 net.mamoe.mirai.Bot.info0: ECDH key is valid.
[INFO ] 2021-10-17 23:41:17,742 net.mamoe.mirai.Bot.info0: Saved account secrets to local cache for fast login.
[INFO ] 2021-10-17 23:41:18,164 net.mamoe.mirai.Bot.info0: Login successful.
[INFO ] 2021-10-17 23:41:18,166 net.mamoe.mirai.Bot.info0: Reconnected successfully in 1.113s.
[INFO ] 2021-10-17 23:41:18,166 net.mamoe.mirai.Bot.info0: Scheduled key refresh in 23h 55min 0.0s.
[INFO ] 2021-10-17 23:41:18,166 net.mamoe.mirai.Bot.info0: Scheduled refresh login session in 19d 23h 55min 0.0s.
[WARN ] 2021-10-17 23:41:25,899 net.mamoe.mirai.Bot.warning0: Connection lost, reconnecting... (MsfOfflineToken(uin=3151872683, seq=2893559795, const=0))
[WARN ] 2021-10-17 23:41:25,900 net.mamoe.mirai.Bot.warning0: null
MsfOfflineToken(uin=3151872683, seq=2893559795, const=0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:288)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:371)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$2$1.invokeSuspend(NettyNetworkHandler.kt:183)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by sandtechnology** [comment]
这是安全检查失败，是你上传的文件有问题，和mirai无关

**Comment by LoseSynchronization** [comment]
> 这是安全检查失败，是你上传的文件有问题，和mirai无关

原来是这个意思，我手动上传试了一下，确实是没通过安全检查😂😂😂感谢解答！
