### ISSUE TITLE
处理在下载过程中被撤回的嵌套转发消息

### ISSUE THREAD

**Issue by Deficuet** [mamoe/mirai#1614]
接收一个合并转发时，显示下载合并转发消息成功后抛出该异常，并且没有将合并转发的内容打印至日志
verbose级别的日志确认开启
在简单推理之后找到了该消息；该合并转发的结构是一个套着一个套着三个合并转发每个里面有一堆图
当事人已撤回（无内鬼.png

```
2021-10-21 00:16:14 V/Net 152*****: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)
2021-10-21 00:16:15 V/Net 152*****: Recv: MultiMsg.ApplyDown
2021-10-21 00:16:15 V/Net 152*****: [Http] Downloading forward message from https://ssl.htdata.qq.com:443
2021-10-21 00:16:16 V/Net 152*****: [Http] Downloading forward message: succeed
2021-10-21 00:16:16 V/Net 152*****: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)
2021-10-21 00:16:17 V/Net 152*****: Recv: MultiMsg.ApplyDown
2021-10-21 00:16:17 V/Net 152*****: [Http] Downloading forward message from https://ssl.htdata.qq.com:443
2021-10-21 00:16:17 V/Net 152*****: [Http] Downloading forward message: succeed
2021-10-21 00:16:17 V/Net 152*****: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)
2021-10-21 00:16:18 V/Net 152*****: Recv: MultiMsg.ApplyDown
2021-10-21 00:16:18 V/Net 152*****: [Http] Downloading forward message from https://ssl.htdata.qq.com:443
2021-10-21 00:16:18 V/Net 152*****: [Http] Downloading forward message: succeed
2021-10-21 00:16:18 E/Net 152*****: Exception in decoding packet.
java.lang.IllegalStateException: Message download failed, result=196, resId=, msgContent=
        at net.mamoe.mirai.internal.MiraiImpl.downloadMultiMsgTransmit(MiraiImpl.kt:973)
        at net.mamoe.mirai.internal.MiraiImpl.access$downloadMultiMsgTransmit(MiraiImpl.kt:67)
        at net.mamoe.mirai.internal.MiraiImpl$downloadMultiMsgTransmit$1.invokeSuspend(MiraiImpl.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 复现

看起来是偶然事件，至少我目前没有找到如何稳定复现
发生环境是从一个收在群助手里的群接收合并转发。

#### 版本及相关选项选择

- mirai-core: `2.7.1` 
- bot-protocol: `ANDROID_WATCH` 

#### 补充信息

发送者很快便撤回了该消息，无法提供任何关于该消息的信息

**Comment by Deficuet** [comment]
Umm，补充一下，我觉得应该不是“下载过程中被撤回”（或者是不是有我不知道的处理细节）
这个合并转发一被bot收到并开始下载（Net日志显示开始下载）之后马上抛出这个异常并且没有任何后续相关日志
抛出这个异常之后，我去找到了这个合并转发，当时还没有被撤回。所以我可以点进去看这个合并转发的结构和内容
但是随后就被撤回了，我没来得及转发给phone协议的号看，因为这样可能可以正常下载并获知它的resId和nodeList等信息
所以我无法提供关于它的信息。日志里只有报错

**Comment by Him188** [comment]
备注：官方客户端处理普通消息大概比mirai慢1秒，处理合并转发不确定
