### ISSUE TITLE
机器人登录服务器优选bug

### ISSUE THREAD

**Issue by mcdoeswhat** [mamoe/mirai#1619]
机器人登录有时不会优先选择缓存的延迟低的服务器
而是从默认的服务器列表里随机选择
而且根据日志看貌似是尝试连接默认服务器之后再载入缓存的服务器列表
serever.json: https://pastebin.com/XrurseL4
可以看到并不包含183.232.94.44:80这个ip
这个ip是默认服务器列表里面的

```
[16:52:55] [DefaultDispatcher-worker-14/INFO]: [91m2021-10-23 16:52:55 W/Net 3528054353: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /183.232.94.44:80
[16:52:55] [DefaultDispatcher-worker-14/INFO]: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /183.232.94.44:80
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	Suppressed: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelling}@1f034ebf
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	[CIRCULAR REFERENCE:io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: /183.232.94.44:80]
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	[CIRCULAR REFERENCE:kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelling}@1f034ebf]
[16:52:55] [DefaultDispatcher-worker-14/INFO]: Caused by: java.net.ConnectException: Connection timed out: no further information
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:779)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[16:52:55] [DefaultDispatcher-worker-14/INFO]: [0m
[16:53:19] [DefaultDispatcher-worker-17/INFO]: [0m2021-10-23 16:53:19 V/Net 3528054353: Loading server list from cache.[0m
[16:53:19] [DefaultDispatcher-worker-17/INFO]: [92m2021-10-23 16:53:19 I/Net 3528054353: Server list: 113.96.13.208:14000, 42.81.169.100:443, 42.81.184.206:443, 114.221.148.14:80, msfwifi.3g.qq.com:8080, 180.102.111.105:8080, 113.96.12.224:8080, 114.221.148.13:8080, 14.22.5.202:8080, 42.81.172.41:80.[0m
[16:53:19] [DefaultDispatcher-worker-17/INFO]: [92m2021-10-23 16:53:19 I/Bot 3528054353: Loaded account secrets from local cache.[0m
```

#### 复现

重启整个机器人java程序登录,大概十几次会出现一次
我本地电脑测试有时候几乎是百分之50%的几率出现此情况
已经测试过2.8.0-M1 2.7.1 均有此情况
连接超时换服务器倒是还好，但是有时候会连接到延迟高的香港服务器
导致机器人登录缓慢，有时甚至几十分钟都载入不完群列表，导致接收不到聊天信息

#### 版本及相关选项选择

- mirai-core: `2.8.0-M1` 
- bot-protocol: `ANDROID_PAD` 

#### 网络日志

```

```

**Comment by Him188** [comment]
服务器列表由服务器提供, 第一次登录会用以前连接中国大陆服务器时得到的可选服务器列表
