### ISSUE TITLE
修解析修改群组名事件时 java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by RedBeanN** [mamoe/mirai#162]
```
[INFO] [NETWORK ERROR] java.lang.NegativeArraySizeException
        at kotlinx.io.core.StringsKt.readBytesOf(Strings.kt:182)
        at kotlinx.io.core.StringsKt.readBytes(Strings.kt:170)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$ReqPush$decode$packets$1.invoke(On
linePush.kt:429)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$ReqPush$decode$packets$1.invoke(On
linePush.kt:188)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:277)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:265)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroid
BotNetworkHandler.kt:654)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetw
orkHandler.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqand
roid(PacketFactory.kt:275)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:
231)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandle
r.kt:416)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:411)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNe
tworkHandler.kt:396)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Him188** [comment]
Fixed in 0.37.3
