### ISSUE TITLE
启动时出错

### ISSUE THREAD

**Issue by 4o4E** [mamoe/mirai#1628]
启动的时候有很大概率会卡住，然后报一个错
表现：启动的时候日志突然停住，过一段时间之后报错

```
[15:38:27/WARN ] null
 io.netty.channel.ConnectTimeoutException: connection timed out: /14.215.138.110:8080
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[BotLibV5.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[BotLibV5.jar:?]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[BotLibV5.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[BotLibV5.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[BotLibV5.jar:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[BotLibV5.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BotLibV5.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BotLibV5.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[BotLibV5.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
        Suppressed: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling
        Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: /14.215.138.110:8080
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261) ~[BotLibV5.jar:?]
                at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[BotLibV5.jar:?]
                at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[BotLibV5.jar:?]
                at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[BotLibV5.jar:?]
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[BotLibV5.jar:?]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[BotLibV5.jar:?]
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BotLibV5.jar:?]
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BotLibV5.jar:?]
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[BotLibV5.jar:?]
                at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@7095a844
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@1ade62f
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@2ac12364
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@361b4de7
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@6b9104e8
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@5e31b2b
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@261ac2f0
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@4a02c7a1
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@29d73c4d
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@34f0401f
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@440d0933
[15:38:27/TRACE] instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@186ee1dc
```

#### 复现
启动bot

#### 版本及相关选项选择

- mirai-core: `2.8.0-M1` 
- bot-protocol: `ANDROID_PAD` 

#### 网络日志

```
同上
```

**Comment by Karlatemp** [comment]
#1619
