### ISSUE TITLE
收到带引用信息的转发信息报错

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#1641]
收到带引用信息的转发信息报错, 如
![image](https://user-images.githubusercontent.com/35139537/139782262-d56dc52d-a036-45b9-8861-1d685dbdb4a5.png)

```
2021-11-02 11:20:12 V/Net 692928873: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)
2021-11-02 11:20:12 V/Net 692928873: Recv: ConfigPushSvc.PushReq
2021-11-02 11:24:38 V/Net 692928873: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)
2021-11-02 11:24:38 V/Net 692928873: Recv: MultiMsg.ApplyDown
2021-11-02 11:24:38 V/Net 692928873: [Http] Downloading forward message from https://ssl.htdata.qq.com:443
2021-11-02 11:24:39 V/Net 692928873: [Http] Downloading forward message: succeed
2021-11-02 11:24:39 E/Bot 692928873: Exception on parsing packet.
java.lang.IllegalStateException: Exception in net.mamoe.mirai.internal.network.notice.group.GroupMessageProcessor@11f42c49 while processing packet PbPushMsg.
	at net.mamoe.mirai.internal.network.components.NoticeProcessorPipelineImpl.process$suspendImpl(NoticeProcessorPipeline.kt:241)
	at net.mamoe.mirai.internal.network.components.NoticeProcessorPipelineImpl$process$1.invokeSuspend(NoticeProcessorPipeline.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: kotlinx.serialization.MissingFieldException: Fields [msgHead, msgBody] are required for type with serial name 'net.mamoe.mirai.internal.network.protocol.data.proto.MsgComm.Msg', but they were missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at net.mamoe.mirai.internal.network.protocol.data.proto.MsgComm$Msg.<init>(MsgCommon.kt:79)
	at net.mamoe.mirai.internal.network.protocol.data.proto.MsgComm$Msg$$serializer.deserialize(MsgCommon.kt:79)
	at net.mamoe.mirai.internal.network.protocol.data.proto.MsgComm$Msg$$serializer.deserialize(MsgCommon.kt:79)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:224)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:214)
	at kotlinx.serialization.protobuf.ProtoBuf.decodeFromByteArray(ProtoBuf.kt:137)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:168)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs$default(utils.kt:163)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs$default(utils.kt:1)
	at net.mamoe.mirai.internal.message.OfflineSourceImplKt.OfflineMessageSourceImplData(offlineSourceImpl.kt:171)
	at net.mamoe.mirai.internal.message.ReceiveMessageTransformer.decodeSrcMsg(ReceiveMessageHandler.kt:323)
	at net.mamoe.mirai.internal.message.ReceiveMessageTransformer.transformElement(ReceiveMessageHandler.kt:169)
	at net.mamoe.mirai.internal.message.ReceiveMessageTransformer.joinToMessageChain(ReceiveMessageHandler.kt:154)
	at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChain(ReceiveMessageHandler.kt:109)
	at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainNoSource(ReceiveMessageHandler.kt:88)
	at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainNoSource$default(ReceiveMessageHandler.kt:82)
	at net.mamoe.mirai.internal.MiraiImpl.toNode$suspendImpl(MiraiImpl.kt:923)
	at net.mamoe.mirai.internal.MiraiImpl.toNode(MiraiImpl.kt)
	at net.mamoe.mirai.internal.MiraiImpl.toForwardMessageNodes$suspendImpl(MiraiImpl.kt:901)
	at net.mamoe.mirai.internal.MiraiImpl.toForwardMessageNodes$mirai_core(MiraiImpl.kt)
	at net.mamoe.mirai.internal.MiraiImpl.toForwardMessageNodes$suspendImpl(MiraiImpl.kt:911)
	at net.mamoe.mirai.internal.MiraiImpl.toForwardMessageNodes$mirai_core(MiraiImpl.kt)
	at net.mamoe.mirai.internal.MiraiImpl.downloadForwardMessage$suspendImpl(MiraiImpl.kt:894)
	at net.mamoe.mirai.internal.MiraiImpl$downloadForwardMessage$1.invokeSuspend(MiraiImpl.kt)
	... 29 more
```

#### 复现

群聊内合并转发引用信息

#### 版本及相关选项选择

- mirai-core: `2.8.0-M1` + `2.8.0-RC` 
- bot-protocol: `ANDROID_PHONE`

**Comment by Karlatemp** [comment]
使用什么设备发送的转发，在什么环境(私聊 / 群聊)下收到的转发

**Comment by Nambers** [comment]
> 使用什么设备发送的转发，在什么环境(私聊 / 群聊)下收到的转发

QQ PC 多选->合并转发
群聊
刚刚成功复现了

**Comment by Nambers** [comment]
私聊看起来也可以触发
