### ISSUE TITLE
突发未知的登录报错（unknown login result type: 180）

### ISSUE THREAD

**Issue by Pineapple-ZhuGe** [mamoe/mirai#1649]
机器人部署在服务器上一直稳定运行，从昨天下午开始突然报这个错误，没有改动过任何地方。
本地开发环境idea启动正常，服务器上就会出这个问题。
（服务器：WinServer2012，JDK：1.8）

```
[31m2021-11-04 01:50:20 E/Net 16*******2: Exception in decoding packet.
java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {0x00000161(353)=00
 01 01 72 00 18 50 B9 0D 5C 9B 5E 07 01 E2 49 C1 1B C5 3A 36 7E 5C 72 0B CE 43 86 FE 1C}
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:188)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:367)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(Net
tyNetworkHandler.kt:175)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
[0m
```

#### 复现

机器人部署在服务器上一直稳定运行，从昨天下午开始突然报这个错误，没有改动过任何地方。
本地开发环境idea启动正常，服务器上就会出这个问题。
原本使用miraiCore：2.8.0-M1，更换为2.8.0-RC也有同样错误。
本地开发环境与服务器上的device.json一致。
（服务器：WinServer2012，JDK：1.8）

#### 版本及相关选项选择

- mirai-core: `2.8.0-M1` 
- bot-protocol: `ANDROID_PHONE` 

#### 网络日志

```

```

**Comment by sandtechnology** [comment]
尝试删除cache文件夹看看？

**Comment by Pineapple-ZhuGe** [comment]
> 尝试删除cache文件夹看看？

删了，没效果。
我写的逻辑是每次登录前都会先删除cache文件夹。

**Comment by zhaodice** [comment]
可能是一种新的没有被识别的设备锁之类安全验证的数据包...

**Comment by sandtechnology** [comment]
> 
> 
> > 尝试删除cache文件夹看看？
> 
> 删了，没效果。 我写的逻辑是每次登录前都会先删除cache文件夹。

建议尝试在服务器上登录电脑QQ 看看是什么情况

**Comment by Pineapple-ZhuGe** [comment]
> > 
> > 
> > > 尝试删除cache文件夹看看？
> > 
> > 删了，没效果。 我写的逻辑是每次登录前都会先删除cache文件夹。
> 
> 建议尝试在服务器上登录电脑QQ 看看是什么情况

也试了，在服务器上安装了QQ，登陆一切正常。

**Comment by Pineapple-ZhuGe** [comment]
> 可能是一种新的没有被识别的设备锁之类安全验证的数据包...

我猜测也是腾讯新加的什么校验规则。。
因为我的服务器环境什么都没有发生改变。。
而且QQ号使用也一切正常。。

**Comment by Karlatemp** [comment]
能提供完整日志吗? 见 https://github.com/mamoe/mirai/blob/dev/docs/DebuggingNetwork.md

**Comment by mzdluo123** [comment]
我之前也遇到过这个问题，请检查你是否正确输入了账号

**Comment by 2219160052** [comment]
我今天也遇到这个问题，是因为用了oracle JDK，换了open jdk好了

**Comment by 0f-0b** [comment]
2.13.0-RC2 下遇到了类似的报错，但不能复现。IPAD 协议，OpenJDK 19。

<details><summary>网络日志</summary>

```
2022-11-01 01:11:26 V/Net <botId>: Loading server list from cache.
2022-11-01 01:11:26 V/Net <botId>: Server list: 36.155.224.104:80, 36.155.244.59:14000, 111.31.200.220:14000, 111.31.205.243:80, 120.232.31.177:8080, 111.31.205.168:80, 120.232.31.239:443, msfwifi.3g.qq.com:8080, 111.30.187.249:80, 36.155.244.199:8080.
2022-11-01 01:11:26 I/Net <botId>: ECDH key is valid.
2022-11-01 01:11:27 V/Net <botId>: Send: wtlogin.exchange_emp(10:fast-login)
2022-11-01 01:11:27 E/Net <botId>: Exception in decoding packet.
java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {0x00000161(353)=00 01 01 72 00 18 A4 F8 56 B1 EF 1A C8 06 EA F2 17 63 79 40 35 2E 89 98 FA DD 90 64 EE 5C}
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:241)
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$ExchangeEmp.decode(WtLogin.kt:644)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)

2022-11-01 01:11:27 V/Net <botId>: Send: wtlogin.login(9:password-login)
2022-11-01 01:11:27 E/Net <botId>: Exception in decoding packet.
java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {0x00000161(353)=00 01 01 72 00 18 6A DE 02 C8 42 6C 54 CC 48 29 C5 F0 3C 25 89 9B D3 D8 BD 18 6F 50 9D 8C}
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:241)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)

2022-11-01 01:11:27 W/Net <botId>: Exception in resumeConnection.
java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {0x00000161(353)=00 01 01 72 00 18 6A DE 02 C8 42 6C 54 CC 48 29 C5 F0 3C 25 89 9B D3 D8 BD 18 6F 50 9D 8C}
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:241)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
	Suppressed: java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {0x00000161(353)=00 01 01 72 00 18 A4 F8 56 B1 EF 1A C8 06 EA F2 17 63 79 40 35 2E 89 98 FA DD 90 64 EE 5C}
		at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:241)
		at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$ExchangeEmp.decode(WtLogin.kt:644)
		... 23 more

2022-11-01 01:11:27 W/Net <botId>: Network selector received exception, closing bot. (java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {0x00000161(353)=00 01 01 72 00 18 6A DE 02 C8 42 6C 54 CC 48 29 C5 F0 3C 25 89 9B D3 D8 BD 18 6F 50 9D 8C})
2022-11-01 01:11:27 W/Net <botId>: Network selector received exception, closing bot. (java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {0x00000161(353)=00 01 01 72 00 18 6A DE 02 C8 42 6C 54 CC 48 29 C5 F0 3C 25 89 9B D3 D8 BD 18 6F 50 9D 8C})
```

</details>
