### ISSUE TITLE
私聊发送图片时返回 Bad ImageId

### ISSUE THREAD

**Issue by kirainmoe** [mamoe/mirai#165]
- mirai-console-wrapper 0.1.4
- mirar-console 0.3.7
- mirai-core-jvm v0.30.1
- mirar-api-http v1.3.2

框架使用 [node-mirai](https://github.com/RedBeanN/node-mirai/)

## 错误信息

私聊发送图片时，报错 ```java.lang.IllegalArgumentException: Bad imageId, expecting length=37 or 42, got 54```，发送群聊图片时正常。

分别查看私聊和群聊时 uploadImage 返回的信息似乎不同，如下：

### 私聊时

```
{
  imageId: '/000000000-3814297509-BFB7027B9354B8F899A062061D74E206',
  url: 'http://c2cpicdw.qpic.cn/offpic_new/0//000000000-3814297509-BFB7027B9354B8F899A062061D74E206/0'
}
```

 (000000000 表示发送方 QQ)

### 群聊时

```
{
  imageId: '{BB74CC82-XXXX-109E-D1BE-6BD84591469A}.jpg',
  url: 'http://gchat.qpic.cn/gchatpic_new/0/0-0-BB74CC82XXXX109ED1BE6BD84591469A/0'
}
```

具体我不太确定是哪个环节有问题，或是我写的代码的问题（代码实现是用 node-mirai 先调用 /uploadImage ，然后再将返回信息包装进 Image 的 MessageCompoent 发送的）

## 完整错误日志

```
 22:06:37 [ERROR] [MiraiAPIHTTP] java.lang.IllegalArgumentException: Bad imageId, expecting length=37 or 42, got 54
        at net.mamoe.mirai.message.data.MessageUtils__ImageKt.newImage(Image.kt:58)
       at net.mamoe.mirai.message.data.MessageUtils.newImage(Unknown Source)                                         
       at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessage(MessageDTO.kt:158)                             
       at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toMessageChain(MessageDTO.kt:130)                        
       at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$1$1.invok
Suspend(BaseRoute.kt:326)                                                                                            
       at net.mamoe.mirai.api.http.route.MessageRouteModuleKt$messageModule$1$$special$$inlined$miraiVerify$1$1.invok
(BaseRoute.kt)                                                                                                       
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)                                      
       at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)                                   
       at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)                                   
       at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)                                                     
       at io.ktor.routing.Routing.executeResult(Routing.kt:147)                                                      
       at io.ktor.routing.Routing.interceptor(Routing.kt:34)                                                         
       at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)                                     
       at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)                                               
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)                                      
       at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)                                   
       at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)                           
       at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)                                      
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)                                      
       at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)                                   
       at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)                                   
       at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)                                                     
       at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.k
:120)                                                                                                                
       at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)     
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)                                      
       at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)                                   
       at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)                                   
       at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)                                                     
       at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:167
                                                                                                                     
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                     
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)                                                
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)                      
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)             
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)               
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)                     
```

**Comment by ryoii** [comment]
返回长度55（不确定）：/000000000-3814297509-BFB7027B9354B8F899A062061D74E206
> 经过测试，前9位通过不同方式上传图片的结果不同，可能喂QQ号，可能为不确定的数字，下列为通过core中的uploadImage发送图片获取的imageId
/18446744072816978315-2951525641-BB397017508FBDA365B6CE245F2F01C6

但后32位构成形如`/12-8-8-8-12`的id依旧可以发送

**Comment by kirainmoe** [comment]
看起来好像还是有些问题，example 里我测试的 QQ 号是九位数，所以长度是 54，然后我用十位数的 QQ 测试的时候，长度就变成 55 了，仍然报错……
