### ISSUE TITLE
MessageChain: Collection contains no element matching the predicate.

### ISSUE THREAD

**Issue by liujiahua123123** [mamoe/mirai#166]
## 问题
```
Bot() 23:59:45 : An exception was thrown under a coroutine of Bot
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at net.mamoe.mirai.message.data.MessageUtils__MessageChainKt.firstOrNull(MessageChain.kt:463)
	at net.mamoe.mirai.message.data.MessageUtils.firstOrNull(Unknown Source)
	at net.mamoe.mirai.message.data.MessageChain$DefaultImpls.getOrNull(MessageChain.kt:61)
	at net.mamoe.mirai.message.data.MessageChainImplBySequence.getOrNull(MessageChain.kt:426)
	at TestKt$main$2$1.invokeSuspend(Test.kt:39)
	at TestKt$main$2$1.invoke(Test.kt)
	at net.mamoe.mirai.event.SubscribeMessagesKt$subscribeGroupMessages$4$1.invokeSuspend(subscribeMessages.kt:161)
	at net.mamoe.mirai.event.SubscribeMessagesKt$subscribeGroupMessages$4$1.invoke(subscribeMessages.kt)
	at net.mamoe.mirai.event.SubscriberKt$subscribeAlways$3.invokeSuspend(subscriber.kt:246)
	at net.mamoe.mirai.event.SubscriberKt$subscribeAlways$3.invoke(subscriber.kt)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:76)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:76)
	at net.mamoe.mirai.event.internal.InternalEventListenersKt$callAndRemoveIfRequired$$inlined$forEachNode$lambda$1.invokeSuspend(InternalEventListeners.kt:169)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

## 如何复现
任何消息包几率产生

**Comment by Him188** [comment]
这不是 core 问题. 是使用了 message.first() 之类的函数
