### ISSUE TITLE
合并转发内包含的文件消息的name和id等属性偶尔是空字符串

### ISSUE THREAD

**Issue by Deficuet** [mamoe/mirai#1698]
### 问题描述

我看到了之前已经被close的issue[#1687](https://github.com/mamoe/mirai/issues/1687)，不过在2.8.2又出现了另一个？类似的问题
因为文件老出问题所以写了个try-catch把异常都保存下来免得找不到日志，今天看到个这：
![image](https://user-images.githubusercontent.com/36525579/142956261-bc29209b-e1ec-44a2-a960-ea24e24ce638.png)
```
群 大🐦转转🍺(<groupId>) 文件解析失败
java.lang.IllegalArgumentException: path cannot be blank.
    at net.mamoe.mirai.internal.contact.file.AbsoluteFolderImpl.resolveFiles(AbsoluteFolderImpl.kt:383)
    at net.mamoe.mirai.internal.contact.file.AbsoluteFolderImpl.resolveFiles(AbsoluteFolderImpl.kt:387)
    at io.github.deficuet.qqbot.ForwardMessageArchive.serializeToHtml(ForwardMessageArchive.kt:255)
    at io.github.deficuet.qqbot.ForwardMessageArchive.access$serializeToHtml(ForwardMessageArchive.kt:15)
    at io.github.deficuet.qqbot.ForwardMessageArchive$serializeToHtml$4.invokeSuspend(ForwardMessageArchive.kt)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
    at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
贴个相关代码
```
is FileMessage -> {
    ...
    val remote: AbsoluteFile
    try {
        remote = toAbsoluteFile(contact) ?: contact.files.root.resolveFiles("/$name").first()
    } catch (e: Exception) {
        nodeList.add(
            Element("p") {
                attr("class", "errorMsg")
                appendText("群 ${contact.name}(${contact.id}) $name $id 文件解析失败")
                appendElement("br")
                with(e.stackTraceString().trim().split(separator).iterator()) {
                    while (hasNext()) {
                        appendText(next().replace("\t", "//&nbsp;&nbsp;&nbsp;&nbsp;"))
                        if (hasNext()) appendElement("br")
                    }
                }
            }
        )
        return nodeList
    }
    val remoteURL = remote.getUrl()
    ...
}
```
contact是合并转发的来源群；因为转发包含的文件默认会上传到群文件的根目录所以用的`"/$name"`
nodeList是用来装html元素的列表；Element新建一个标签为p的元素；
结合上面的报错和记录可以发现这个FileMessage的name和id都是空字符串

经查，来源群的文件根目录**存在**有一份该文件，所以应该不存在找不到文件的问题。文件大小约1GB

### 复现

猜测是有概率发生，让watch协议的号接收有文件消息的合并转发即可

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_WATCH

### 系统日志

```text
2021-11-22 06:19:48 V/Net 1526905693: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)
2021-11-22 06:19:49 V/Net 1526905693: Recv: MultiMsg.ApplyDown
2021-11-22 06:19:49 V/Net 1526905693: [Http] Downloading forward message from https://ssl.htdata.qq.com:443
2021-11-22 06:19:50 V/Net 1526905693: [Http] Downloading forward message: succeed
2021-11-22 06:19:50 V/deficuet_qqbot: V/1526905693: [大🐦转转🍺(4******)] YT渣渣(296*******) -> [mirai:origin:FORWARD,kcLR4bYTbEpxkFVD10nT87vinwHlBbKMhY7T8/OAvk4F1I44sF1G0roqAtK9ei2r]ForwardMessage(preview=[Sun Faor:[文件][影おじ (隠れエリア)].zip, Sun Faor:是铜, 阿比盖尔·威廉姆斯:好, Sun Faor:[图片]], title=群聊的聊天记录, brief=[聊天记录], source=聊天记录, summary=查看转发消息, nodeList=[Node(senderId=804184769, time=1637571519, senderName=文老板, messageChain=[mirai:file:,,0,0]), Node(senderId=804184769, time=1637571527, senderName=文老板, messageChain=是铜), Node(senderId=596005655, time=1637571533, senderName=不明正体, messageChain=好), Node(senderId=804184769, time=1637571543, senderName=文老板, messageChain=[mirai:image:{73A7E83B-0B81-8EF1-AAD4-08401C940B9E}.mirai]), Node(senderId=804184769, time=1637571552, senderName=文老板, messageChain=[mirai:image:{6020CB94-01AF-855F-3DE9-23FA004ABAFE}.mirai]), Node(senderId=907739643, time=1637571553, senderName=Preserved egg, messageChain=[mirai:quote:[184156],[-374627044]]我冲了), Node(senderId=804184769, time=1637571556, senderName=文老板, messageChain=就是插画集), Node(senderId=1557183350, time=1637571581, senderName=霾, messageChain=来丶预览), Node(senderId=746190271, time=1637571620, senderName=群内鬼, messageChain=[mirai:quote:[184165],[930723741]]@文老板 密码), Node(senderId=804184769, time=1637571640, senderName=文老板, messageChain=没有密码), Node(senderId=804184769, time=1637571645, senderName=文老板, messageChain=有就114514), Node(senderId=804184769, time=1637571685, senderName=文老板, messageChain=[mirai:image:{727D05D9-2226-2BC9-3AD7-AC84DBF0695A}.mirai][mirai:image:{DD012D42-8F57-C1F5-1F8B-29E322439F85}.mirai]), Node(senderId=2900186470, time=1637571689, senderName=      LDS    逆时空, messageChain=好熟悉啊), Node(senderId=1303561671, time=1637571690, senderName=烟花, messageChain=我tm人都傻了)])
```

### 网络日志

```text
无
```

### 补充信息

原封不动地转发让phone协议的号接收，一切正常。几小时后有个火星人在同一个群里又发了一次该合并转发，被watch协议的号接收，一切正常。期间未重启mirai

**Comment by Him188** [comment]
For mamoe:

check: 
```
java.lang.IllegalArgumentException: path cannot be blank.
    at net.mamoe.mirai.internal.contact.file.AbsoluteFolderImpl.resolveFiles(AbsoluteFolderImpl.kt:383)
    at net.mamoe.mirai.internal.contact.file.AbsoluteFolderImpl.resolveFiles(AbsoluteFolderImpl.kt:387)
```
