### ISSUE TITLE
No such group xxx for bot xxx

### ISSUE THREAD

**Issue by RedBeanN** [mamoe/mirai#172]
```
[NETWORK ERROR] java.util.NoSuchElementException: No such group xxx for bot xxx
	at net.mamoe.mirai.Bot.getGroup(Bot.kt:117)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$PbPushGroupMsg.decode(OnlinePush.kt:80)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:474)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:224)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:416)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:411)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:396)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Him188** [comment]
是否是bot加入了一个新群？
报错里的群号是否正确？

**Comment by Him188** [comment]
原因可能类似于 #164

**Comment by RedBeanN** [comment]
> 是否是bot加入了一个新群？
> 报错里的群号是否正确？

是bot加入新群时触发的，群号是正确的
