### ISSUE TITLE
使用Logback + runBlocking登录BOT出错时会导致堆栈溢出

### ISSUE THREAD

**Issue by ForteScarlet** [mamoe/mirai#1722]
### 问题描述

使用Logback作为日志框架，并在`runBlocking { }`代码块中执行 `Bot.login` 的时候，抛出异常并通过logger输出此异常将会导致堆栈溢出。
使用挂起函数执行，或部分其他日志框架无此问题。

### 复现

溢出：
```kotlin
fun main() {
    val logger = LoggerFactory.getLogger("1")

    runCatching {
        runBlocking {
            BotFactory.newBot(1, "1").login() // err
        }

    }.getOrElse {
        logger.error("err", it)
    }
}
```

可行：
```kotlin
suspend fun main() {
    val logger = LoggerFactory.getLogger("1")

    runCatching {
            BotFactory.newBot(1, "1").login() // err
    }.getOrElse {
        logger.error("err", it)
    }
}
```

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/G:/code/apache-maven-3.6.3-bin/apache-maven-3.6.3/lib/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/G:/code/apache-maven-3.6.3-bin/apache-maven-3.6.3/lib/love/forte/common/log/1.0.7/log-1.0.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
2021-12-10 02:08:49 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2021-12-10 02:08:49 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2021-12-10 02:08:50 W/BotConfiguration: 未指定设备信息, 已使用随机设备信息. 请查看 BotConfiguration.deviceInfo 以获取更多信息.
2021-12-10 02:08:50 W/BotConfiguration: Device info isn't specified. Please refer to BotConfiguration.deviceInfo for more information
... 省略部分日志
2021-12-10 02:08:53 V/Net 1: Recv: wtlogin.login
2021-12-10 02:09:05 V/Net 1: Send: wtlogin.login
2021-12-10 02:09:06 V/Net 1: Recv: wtlogin.login
2021-12-10 02:09:06 W/Net 1: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2021-12-10 02:09:06 I/Bot 1: Bot cancelled: Bot closed
Exception in thread "main" java.lang.StackOverflowError
	at sun.reflect.Reflection.quickCheckMemberAccess(Reflection.java:84)
	at java.lang.reflect.Method.invoke(Method.java:489)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:66)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:72)
	at ch.qos.logback.classic.spi.ThrowableProxy.<init>(ThrowableProxy.java:60)
```

### 网络日志

```text
无
```

### 补充信息

此问题在较早版本中不存在。（记不清具体版本了，大概是2.7之前，不包括2.7）

**Comment by Him188** [comment]
> 可行

好像没打出来？

**Comment by ForteScarlet** [comment]
> > 可行
> 
> 好像没打出来？

“可行”下面应该是通过 suspend fun main 来执行的正常逻辑，好像不小心没输上去

**Comment by Him188** [comment]
@ForteScarlet 可以修改，点编辑框右上角三个点

**Comment by ForteScarlet** [comment]
> @ForteScarlet 可以修改，点编辑框右上角三个点

已修改

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/issues/1498#issuecomment-907011286

最根本的解决方法应该是前往logback提交issue
