### ISSUE TITLE
lateinit property botAsMember has not been initialized

### ISSUE THREAD

**Issue by ryoii** [mamoe/mirai#1776]
### 问题描述

无法稳定复现的初始化错误 project-mirai/mirai-api-http#522

### 复现

```
group.botPermission
```

### mirai-core 版本

2.9.0-RC2

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2021-12-22 17:21:17 E/net.mamoe.mirai-api-http: kotlin.UninitializedPropertyAccessException: lateinit property botAsMember has not been initialized
kotlin.UninitializedPropertyAccessException: lateinit property botAsMember has not been initialized
at net.mamoe.mirai.internal.contact.GroupImpl.getBotAsMember(GroupImpl.kt:80)
at net.mamoe.mirai.contact.Group.getBotPermission(Group.kt:78)
at net.mamoe.mirai.api.http.adapter.internal.dto.GroupDTO.(contact.kt:58)
at net.mamoe.mirai.api.http.adapter.internal.action.InfomationKt.onGetGroupList(infomation.kt:31)
at
```

### 网络日志

```text
无
```

**Comment by Him188** [comment]
缺少环境, 无法修复, 2.10.0-RC 添加了日志

**Comment by Him188** [comment]
由 #1977 取代
