### ISSUE TITLE
LockFreeLinkedList: Internal error: trying to get the value of a Tail

### ISSUE THREAD

**Issue by NanamiArihara** [mamoe/mirai#178]
## 问题
今天 mirai-console 自动更更新之后就用不了了。
```
[BOT 1519989615] Received: GroupMessage(group=609600081, senderName=特级厨师, sender=1276571946, permission=ADMINISTRATOR, message=[mirai:{E38508A0-5B07-7664-30E9-0479B848A341}.jpg])[39;49m
[0m 11:04:47 [INFO] [BOT 1519989615] Init failed. Retrying in 3s...[39;49m
[0m 11:04:47 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: type mismatch: 10
        at net.mamoe.mirai.qqandroid.io.serialization.jce.JceInput.readJceShortValue-yMyK8XM(JceInput.kt:201)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.JceDecoder.decodeTaggedShort(JceDecoder.kt:309)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.JceDecoder.decodeTaggedShort(JceDecoder.kt:21)
        at kotlinx.serialization.internal.TaggedDecoder.decodeShort(Tagged.kt:195)
        at kotlinx.serialization.internal.ShortSerializer.deserialize(Primitives.kt:108)
        at kotlinx.serialization.internal.ShortSerializer.deserialize(Primitives.kt:105)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Decoding.kt:231)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:233)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:233)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPacket$$serializer.deserialize(RequestPacket.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPacket$$serializer.deserialize(RequestPacket.kt:20)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.Jce.load(JceNew.kt:38)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.readJceStruct(utils.kt:52)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.readJceStruct(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.readJceStruct$default(utils.kt:49)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.readJceStruct$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(utils.kt:80)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniPacket(utils.kt:59)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniPacket(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniPacket$default(utils.kt:58)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniPacket$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.login.ConfigPushSvc$PushReq.decode(ConfigPushSvc.kt:32)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:474)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:330)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
        Suppressed: java.lang.IllegalStateException: Internal error: trying to get the value of a Tail
                at net.mamoe.mirai.utils.Tail.getNodeValue(LockFreeLinkedList.kt:744)
                at net.mamoe.mirai.utils.Tail.getNodeValue(LockFreeLinkedList.kt:742)
                at net.mamoe.mirai.utils.LockFreeLinkedList.clear(LockFreeLinkedList.kt:319)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:192)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invoke(QQAndroidBotNetworkHandler.kt)
                at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
                at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:177)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.init(QQAndroidBotNetworkHandler.kt:187)
                at net.mamoe.mirai.BotImpl$reinitializeNetworkHandler$3.invokeSuspend(BotImpl.kt:159)
                ... 5 more
```
一般在接收第一条消息之后就会崩溃
第二次崩溃:
```
 [NETWORK ERROR] kotlinx.serialization.MissingFieldException: Field 'iRequestId' is required, but it was missing
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPacket.<init>(RequestPacket.kt:23)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPacket$$serializer.deserialize(RequestPacket.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPacket$$serializer.deserialize(RequestPacket.kt:20)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.Jce.load(JceNew.kt:38)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.readJceStruct(utils.kt:52)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.readJceStruct(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.readJceStruct$default(utils.kt:49)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.readJceStruct$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(utils.kt:80)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniPacket(utils.kt:59)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniPacket(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniPacket$default(utils.kt:58)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniPacket$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.login.ConfigPushSvc$PushReq.decode(ConfigPushSvc.kt:32)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:474)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:330)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
        Suppressed: java.lang.IllegalStateException: Internal error: trying to get the value of a Tail
                at net.mamoe.mirai.utils.Tail.getNodeValue(LockFreeLinkedList.kt:744)
                at net.mamoe.mirai.utils.Tail.getNodeValue(LockFreeLinkedList.kt:742)
                at net.mamoe.mirai.utils.LockFreeLinkedList.clear(LockFreeLinkedList.kt:319)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:192)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invoke(QQAndroidBotNetworkHandler.kt)
                at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
                at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:177)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.init(QQAndroidBotNetworkHandler.kt:187)
                at net.mamoe.mirai.BotImpl$reinitializeNetworkHandler$3.invokeSuspend(BotImpl.kt:159)
                ... 5 more
[39;49m
[0m 11:06:54 [INFO] [BOT 1519989615] cannot init. some features may be affected[39;49m
```

## 如何复现
尝试登陆。

建议：可以手动开启/关掉自动更新

**Comment by kirainmoe** [comment]
same issue here.

提供一份和上面不太一样的错误，不知道是否有用：

```
 11:00:51 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: tag 0 not found when skipping list
        at net.mamoe.mirai.qqandroid.io.serialization.jce.JceInput.skipField(JceInput.kt:148)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.JceDecoder.decodeElementIndex(JceDecoder.kt:281)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPacket$$serializer.deserialize(RequestPacket.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPacket$$serializer.deserialize(RequestPacket.kt:20)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at net.mamoe.mirai.qqandroid.io.serialization.jce.Jce.load(JceNew.kt:38)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.readJceStruct(utils.kt:52)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.readJceStruct(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.readJceStruct$default(utils.kt:49)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.readJceStruct$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(utils.kt:80)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniPacket(utils.kt:59)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniPacket(utils.kt:1)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils__UtilsKt.decodeUniPacket$default(utils.kt:58)
        at net.mamoe.mirai.qqandroid.io.serialization.SerializationUtils.decodeUniPacket$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.login.ConfigPushSvc$PushReq.decode(ConfigPushSvc.kt:32)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:474)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:330)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
        Suppressed: java.lang.IllegalStateException: Internal error: trying to get the value of a Tail
                at net.mamoe.mirai.utils.Tail.getNodeValue(LockFreeLinkedList.kt:744)
                at net.mamoe.mirai.utils.Tail.getNodeValue(LockFreeLinkedList.kt:742)
                at net.mamoe.mirai.utils.LockFreeLinkedList.clear(LockFreeLinkedList.kt:319)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:192)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invoke(QQAndroidBotNetworkHandler.kt)
                at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
                at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:177)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.init(QQAndroidBotNetworkHandler.kt:187)
                at net.mamoe.mirai.BotImpl$reinitializeNetworkHandler$3.invokeSuspend(BotImpl.kt:159)
                ... 5 more
```

**Comment by NanamiArihara** [comment]
（跑题）突发紧急情况：jcenter 炸了
禁用自动更新应该提上日程

**Comment by Chenwe-i-lin** [comment]
> （跑题）突发紧急情况：jcenter 炸了
> 禁用自动更新应该提上日程

该问题应提交至 `mamoe/mirai-console`.

**Comment by Him188** [comment]
这个问题会影响所有版本, 已修复

**Comment by Him188** [comment]
已确定是服务器问题, #52
