### ISSUE TITLE
命令参数支持 vararg 和原生类型数组

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#1799]
无法解析 vararg param: Long

> 复现

```
    suspend fun CommandSenderOnMessage<*>.user(vararg users: Long)  { } 
```

> 日志

```
2021-05-02 19:40:50 E/pixiv-helper: java.lang.IllegalStateException: type must be subtype of Array if vararg. Given kotlin.LongArray.
java.lang.IllegalStateException: type must be subtype of Array if vararg. Given kotlin.LongArray.
        at net.mamoe.mirai.console.command.descriptor.AbstractCommandValueParameter$UserDefinedType.<init>(CommandParameter.kt:237)
        at net.mamoe.mirai.console.internal.command.CommandReflector.toUserDefinedCommandParameter(CommandReflector.kt:316)
        at net.mamoe.mirai.console.internal.command.CommandReflector.access$toUserDefinedCommandParameter(CommandReflector.kt:106)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6.invoke(CommandReflector.kt:260)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6.invoke(CommandReflector.kt:106)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:752)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:782)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:773)
        at net.mamoe.mirai.console.internal.command.CommandReflector.findSubCommands(CommandReflector.kt:296)
        at net.mamoe.mirai.console.command.CompositeCommand$overloads$2.invoke(CompositeCommand.kt:99)
        at net.mamoe.mirai.console.command.CompositeCommand$overloads$2.invoke(CompositeCommand.kt:85)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.console.command.CompositeCommand.getOverloads(CompositeCommand.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImpl.registerCommand(CommandManagerImpl.kt:75)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
        at xyz.cssxsh.mirai.plugin.PixivHelperPlugin.onEnable(PixivHelperPlugin.kt:101)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:208)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:276)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at mirai.RunMirai$main$1.invokeSuspend(RunMirai.kt:45)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at mirai.RunMirai.main(RunMirai.kt:42)
```

> 版本

- mirai-core: 2.6.2

**Comment by Him188** [comment]
就喜欢自己提 issue 自己 PR 解决的
