### ISSUE TITLE
kotlinx.serialization.SerializationException: Serializer for class 'Any' is not found

### ISSUE THREAD

**Issue by Songhan17** [mamoe/mirai#1831]
### 问题描述

 Mirai插件new project时，选择java，其他默认。参考JAutoSavePluginData想对Value<Map<Long, Object>>创建的时候报异常。

```kotlin
// MyPluginData.java
public class BlackList extends JAutoSavePluginData {

    public static final BlackList INSTANCE = new BlackList();

    public final Value<String> string = value("test"); // 默认值 "test"

    public final Value<List<String>> list = typedValue(createKType(List.class, createKType(String.class))); // 无默认值, 自动创建空 List

    public final Value<Map<Long, Object>> custom = typedValue(
            createKType(Map.class, createKType(Long.class), createKType(Object.class)),
            new HashMap<Long, Object>() {{ // 带默认值
                put(123L, "ok");
            }}
    );

    public BlackList() {
        super("blackSettings");
    }
}
```

去掉Value<Map<Long, Object>> custom相关的创建，则可以成功运行。其他配置均为插件自动生成

### 复现

插件创建模版，用java的方式创建JAutoSavePluginData，将注释内容完全拷贝过来，map会报错

### mirai-core 版本

2.9.2

### bot-protocol

MACOS

### 系统日志

```text
2022-01-08 01:05:07 I/main: Starting mirai-console...
2022-01-08 01:05:07 I/main: Backend: version 2.9.2, built on 2022-01-05 00:00:20.
2022-01-08 01:05:07 I/main: Frontend Terminal: version 2.9.2, provided by Mamoe Technologies
2022-01-08 01:05:07 I/main: Welcome to visit https://mirai.mamoe.net/
2022-01-08 01:05:07 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-01-08 01:05:07 I/main: 0 plugin(s) enabled.
2022-01-08 01:05:07 I/main: mirai-console started successfully.
2022-01-08 01:05:07 W/stderr: Exception in thread "main" net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while loading org.example.plugin v1.0-SNAPSHOT
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:148)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:36)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.plugin.PluginManager.loadPlugin(PluginManager.kt:122)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.plugin.PluginManager$INSTANCE.loadPlugin(PluginManager.kt)
2022-01-08 01:05:07 W/stderr: 	at org.example.RunTerminalKt.main(RunTerminal.kt:30)
2022-01-08 01:05:07 W/stderr: 	at org.example.RunTerminalKt$main$2.invoke(RunTerminal.kt)
2022-01-08 01:05:07 W/stderr: 	at org.example.RunTerminalKt$main$2.invoke(RunTerminal.kt)
2022-01-08 01:05:07 W/stderr: 	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
2022-01-08 01:05:07 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-01-08 01:05:07 W/stderr: 	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
2022-01-08 01:05:07 W/stderr: 	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
2022-01-08 01:05:07 W/stderr: 	at org.example.RunTerminalKt.main(RunTerminal.kt)
2022-01-08 01:05:07 W/stderr: Caused by: java.lang.ExceptionInInitializerError
2022-01-08 01:05:07 W/stderr: 	at org.example.Plugin.onLoad(Plugin.java:19)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:196)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:146)
2022-01-08 01:05:07 W/stderr: 	... 12 more
2022-01-08 01:05:07 W/stderr: Caused by: kotlinx.serialization.SerializationException: Serializer for class 'Any' is not found.
2022-01-08 01:05:07 W/stderr: Mark the class as @Serializable or provide the serializer explicitly.
2022-01-08 01:05:07 W/stderr: 	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
2022-01-08 01:05:07 W/stderr: 	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:155)
2022-01-08 01:05:07 W/stderr: 	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.internal.data.SerializerHelperKt.serializerMirai$serializerByKTypeImpl(serializerHelper.kt:51)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.internal.data.SerializerHelperKt.serializerMirai(serializerHelper.kt:87)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.internal.data.SerializerHelperKt.serializerMirai$serializerByKTypeImpl(serializerHelper.kt:54)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.internal.data.SerializerHelperKt.serializerMirai(serializerHelper.kt:87)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.internal.data.ValueFromKTypeImplKt.valueFromKTypeImpl(valueFromKTypeImpl.kt:74)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.data.PluginDataKt.valueFromKType(PluginData.kt:247)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.data.PluginDataKt.valueImpl(PluginData.kt:230)
2022-01-08 01:05:07 W/stderr: 	at net.mamoe.mirai.console.data.java.JAutoSavePluginData.typedValue(JAutoSavePluginData.kt:140)
2022-01-08 01:05:07 W/stderr: 	at org.example.model.BlackList.<init>(BlackList.java:28)
2022-01-08 01:05:07 W/stderr: 	at org.example.model.BlackList.<clinit>(BlackList.java:22)
2022-01-08 01:05:07 W/stderr: 	... 15 more
> 
Process finished with exit code -1
```

### 网络日志

```text
.
```

**Comment by StageGuard** [comment]
为什么要 Map<Long, Object> 而不是 Map<Long, String>

**Comment by Songhan17** [comment]
> 为什么要 Map<Long, Object> 而不是 Map<Long, String>

这个是代码示例里的，我只是照搬过来，我实际想用Map<Long, List<Long>>的，但是不行，就试试注释里的示例，结果还是不行

**Comment by Him188** [comment]
for mamoe: 
可能已经在改 serializersModule 或者在改 JavaAutoSavePluginData 的时候解决了，检查一下
