### ISSUE TITLE
PluginData 数据绑定时类型转换异常导致崩溃

### ISSUE THREAD

**Issue by bin-tenkuu** [mamoe/mirai#1832]
### 问题描述

使用指定类型和初始值的 value 绑定到值，读取或载入时发生报错

### 复现

1. 使用 [模板](https://github.com/project-mirai/mirai-console-plugin-template/blob/master/src/main/kotlin/PluginMain.kt) 创建项目（修改 Gradle 插件版本 2.9.2）
2. PluginMain 中 添加如下代码
```kotlin
	override fun PluginComponentStorage.onLoad() {
		Data.reload()
		Data.value6.add(1)
	}

// 自动保存数据模型
object Data : AutoSavePluginData("data") {
	val value6 by value<ArrayList<Int>>(ArrayList()) // 可按需使用 Mutable 类型
}
```
3. 运行测试： `test.RunMirai.kt`

### mirai-core 版本

2.9.2

### bot-protocol

ANDROID_PHONE

### 其他组件版本

原生kotlin插件

### 系统日志

```text
2022-01-09 13:51:27 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while loading my.ktbot.plugin.binbot v0.1
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:148)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:85)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:141)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:163)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:277)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:156)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:155)
	at org.example.mirai.plugin.RunMiraiKt.main(RunMirai.kt:11)
	at org.example.mirai.plugin.RunMiraiKt$main$2.invoke(RunMirai.kt)
	at org.example.mirai.plugin.RunMiraiKt$main$2.invoke(RunMirai.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at org.example.mirai.plugin.RunMiraiKt.main(RunMirai.kt)
Caused by: java.lang.ClassCastException: class net.mamoe.mirai.console.internal.data.CompositeListValueImpl$special$$inlined$observable$1 cannot be cast to class java.util.ArrayList (net.mamoe.mirai.console.internal.data.CompositeListValueImpl$special$$inlined$observable$1 is in unnamed module of loader 'app'; java.util.ArrayList is in module java.base of loader 'bootstrap')
	at my.ktbot.plugin.Data.getValue6(PluginMain.kt:179)
	at my.ktbot.plugin.PluginMain.onLoad(PluginMain.kt:78)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:196)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:146)
	... 16 more
```

### 网络日志

```text
无bot
```

### 补充信息

(如果不去读取这个 `value6` 那么就不会报错了)但是如果把类型改为 `MutableList` 那么 `reload` 的时候就会报错了，日志如下：
```log 
2022-01-09 14:05:48 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while loading my.ktbot.plugin.binbot v0.1
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:148)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:85)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:141)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:163)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:277)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:156)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:155)
	at org.example.mirai.plugin.RunMiraiKt.main(RunMirai.kt:11)
	at org.example.mirai.plugin.RunMiraiKt$main$2.invoke(RunMirai.kt)
	at org.example.mirai.plugin.RunMiraiKt$main$2.invoke(RunMirai.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at org.example.mirai.plugin.RunMiraiKt.main(RunMirai.kt)
Caused by: java.lang.ExceptionInInitializerError
	at my.ktbot.plugin.PluginMain.onLoad(PluginMain.kt:77)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:196)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:146)
	... 16 more
Caused by: java.lang.ClassCastException: class kotlin.reflect.jvm.internal.KTypeImpl cannot be cast to class kotlin.jvm.internal.TypeReference (kotlin.reflect.jvm.internal.KTypeImpl and kotlin.jvm.internal.TypeReference are in unnamed module of loader 'app')
	at kotlin.jvm.internal.ReflectionFactory.mutableCollectionType(ReflectionFactory.java:107)
	at kotlin.jvm.internal.Reflection.mutableCollectionType(Reflection.java:196)
	at my.ktbot.plugin.Data.<clinit>(PluginMain.kt:180)
	... 19 more

```

**Comment by Him188** [comment]
不支持 ArrayList, 请使用 MutableList

**Comment by bin-tenkuu** [comment]
> 不支持 ArrayList, 请使用 MutableList

但是我改了 MutableList 之后 reload 的时候就报错了啊

**Comment by Samarium150** [comment]
一个猜想，你应该在`onEnable`里`reload`
```kotlin
override fun onEnable() {
    Data.reload()
}
```

**Comment by LaoLittle** [comment]
> 一个猜想，你应该在`onEnable`里`reload`

哈哈哈哈

**Comment by bin-tenkuu** [comment]
依旧报错：
```kotlin
override fun onEnable() {
	Data.reload()
}
object Data : AutoSavePluginData("Data") {
	val value6: MutableMap<Long, MutableSet<Long>> by value()
}
```

```log
2022-01-10 11:50:21 E/my.ktbot.plugin.binbot: java.lang.ExceptionInInitializerError
java.lang.ExceptionInInitializerError
	at my.ktbot.plugin.PluginMain.onEnable(PluginMain.kt:66)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:122)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:214)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:276)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:151)
	at org.example.mirai.plugin.RunMiraiKt.main(RunMirai.kt:11)
	at org.example.mirai.plugin.RunMiraiKt$main$2.invoke(RunMirai.kt)
	at org.example.mirai.plugin.RunMiraiKt$main$2.invoke(RunMirai.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at org.example.mirai.plugin.RunMiraiKt.main(RunMirai.kt)
Caused by: java.lang.ClassCastException: class kotlin.reflect.jvm.internal.KTypeImpl cannot be cast to class kotlin.jvm.internal.TypeReference (kotlin.reflect.jvm.internal.KTypeImpl and kotlin.jvm.internal.TypeReference are in unnamed module of loader 'app')
	at kotlin.jvm.internal.ReflectionFactory.mutableCollectionType(ReflectionFactory.java:107)
	at kotlin.jvm.internal.Reflection.mutableCollectionType(Reflection.java:196)
	at my.ktbot.plugin.Data.(PluginMain.kt:170)
	... 19 more
```

**Comment by Him188** [comment]
是不是没有依赖 kotlin-reflect?

**Comment by bin-tenkuu** [comment]
引了一下 最新的 1.6.10 的反射包，好了
之前用的 1.3.41 的不行（随便找的一个版本，CSDN害人不浅）
