### ISSUE TITLE
管理员更改群名称时后台报错

### ISSUE THREAD

**Issue by mzdluo123** [mamoe/mirai#184]
```
java.lang.NegativeArraySizeException
	at kotlinx.io.core.StringsKt.readBytesOf(Strings.kt:182)
	at kotlinx.io.core.StringsKt.readBytes(Strings.kt:170)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$ReqPush$decode$packets$1.invoke(OnlinePush.kt:463)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$ReqPush$decode$packets$1.invoke(OnlinePush.kt:194)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:277)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:265)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:647)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:268)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:224)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:416)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:411)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:396)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Network(***) 16:28:56 : unknown shtype 528
```

**Comment by Him188** [comment]
解决了？

**Comment by mzdluo123** [comment]
> 解决了？

不是莫名其妙好了吗，没法重现
