### ISSUE TITLE
GroupImpl 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#1848]
### 问题描述

bot是`692*****3`
所有群都不是最近加的或者已经退出
`89*****9`群里bot是管理员

### 复现

启动core项目

### mirai-core 版本

2.10.0-RC

### bot-protocol

ANDROID_PAD

### 系统日志

```text
2022.01.22 16:48:09 [INFO ] mamoe.mirai.Bot - Start loading group list...
2022.01.22 16:48:09 [INFO ] mamoe.mirai.Bot - Successfully loaded friend list: 4 in total
2022.01.22 16:48:10 [ERROR] internal.contact.GroupImpl - null
net.mamoe.mirai.internal.message.ContextualBugReportException: 在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 89*****9
groupUin: 89*****9
membersCount: 3
botId: 692*****3
owner: 481*****3
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26) ~[mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20) ~[mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.contact.GroupImplKt.GroupImpl(GroupImpl.kt:96) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.addGroupToBot(ContactUpdater.kt:212) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.access$addGroupToBot(ContactUpdater.kt:74) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl$addGroupToBot$1.invokeSuspend(ContactUpdater.kt) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
2022.01.22 16:48:10 [ERROR] internal.contact.GroupImpl - null
net.mamoe.mirai.internal.message.ContextualBugReportException: 在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 1067474509
groupUin: 1067*****9
membersCount: 2
botId: 692*****3
owner: 692*****3
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26) ~[mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20) ~[mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.contact.GroupImplKt.GroupImpl(GroupImpl.kt:96) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.addGroupToBot(ContactUpdater.kt:212) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.access$addGroupToBot(ContactUpdater.kt:74) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl$addGroupToBot$1.invokeSuspend(ContactUpdater.kt) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
2022.01.22 16:48:10 [ERROR] internal.contact.GroupImpl - null
net.mamoe.mirai.internal.message.ContextualBugReportException: 在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 78*****5
groupUin: 78*****5
membersCount: 4
botId: 692*****3
owner: 193*****5
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26) ~[mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20) ~[mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.contact.GroupImplKt.GroupImpl(GroupImpl.kt:96) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.addGroupToBot(ContactUpdater.kt:212) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.access$addGroupToBot(ContactUpdater.kt:74) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl$addGroupToBot$1.invokeSuspend(ContactUpdater.kt) [mirai-core-jvm-2.10.0-RC.jar:2.10.0-RC]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
2022.01.22 16:48:10 [INFO ] mamoe.mirai.Bot - Successfully loaded group list: 3 in total.
```

### 网络日志

```text
none
```

**Comment by AdoptOSS** [comment]
Same problem

**Comment by Stardust-minus** [comment]
+1

**Comment by sandtechnology** [comment]
这应该是一个 bug， 引入的commit为：https://github.com/mamoe/mirai/commit/4a32f03797f8fa95292873f3015128bf2b760b0b
https://github.com/mamoe/mirai/blob/4a32f03797f8fa95292873f3015128bf2b760b0b/mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt#L129
此处应该是 `internal val botAsMemberInitialized get()=::botAsMember.isInitialized`

**Comment by Him188** [comment]
这个只会有日志, 不影响实际功能, 2.10.0-RC2 修复
