### ISSUE TITLE
在device.json内填写baseBand项会导致无法登录

### ISSUE THREAD

**Issue by LaoLittle** [mamoe/mirai#1853]
### 问题描述

```
//device.json
...
"baseBand": "msm",
...
```

### 复现

填写device.json内的baseBand项

### mirai-core 版本

2.10.0-RC2

### bot-protocol

IPAD

### 系统日志

```text
2022-01-25 22:09:54 I/Bot.id: Bot cancelled: Job was cancelled
2022-01-25 22:09:54 E/Bot.id: java.lang.IllegalArgumentException: Invalid char 'm' at index 0
java.lang.IllegalArgumentException: Invalid char 'm' at index 0
        at net.mamoe.mirai.utils.MiraiUtils__ConversionsKt.countHexBytes(Conversions.kt:228)
        at net.mamoe.mirai.utils.MiraiUtils.countHexBytes(Unknown Source)
        at net.mamoe.mirai.utils.MiraiUtils__ConversionsKt.hexToBytes(Conversions.kt:151)
        at net.mamoe.mirai.utils.MiraiUtils.hexToBytes(Unknown Source)
        at net.mamoe.mirai.utils.DeviceInfoManager$HexStringSerializer$special$$inlined$map$1.deserialize(Serialization.kt:92)
        at net.mamoe.mirai.utils.DeviceInfoManager$HexStringSerializer.deserialize-XN8iJCc(DeviceInfo.kt)
        at net.mamoe.mirai.utils.DeviceInfoManager$HexStringSerializer.deserialize(DeviceInfo.kt:265)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
        at net.mamoe.mirai.utils.DeviceInfoManager$V2$$serializer.deserialize(DeviceInfo.kt:328)
        at net.mamoe.mirai.utils.DeviceInfoManager$V2$$serializer.deserialize(DeviceInfo.kt:328)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
        at net.mamoe.mirai.utils.DeviceInfoManager$Wrapper$$serializer.deserialize(DeviceInfo.kt:272)
        at net.mamoe.mirai.utils.DeviceInfoManager$Wrapper$$serializer.deserialize(DeviceInfo.kt:272)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
        at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
        at net.mamoe.mirai.utils.DeviceInfoManager.deserialize(DeviceInfo.kt:433)
        at net.mamoe.mirai.utils.DeviceInfo$Companion.from(DeviceInfo.kt:114)
        at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt:87)
        at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt:86)
        at net.mamoe.mirai.internal.network.components.SsoProcessorContextKt.createDeviceInfo(SsoProcessorContext.kt:47)
        at net.mamoe.mirai.internal.network.components.SsoProcessorContextImpl.<init>(SsoProcessorContext.kt:42)
        at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:195)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:163)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:162)
        at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
        at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:162)
        at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:249)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:261)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:254)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:218)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:189)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:45)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:48)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:47)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getScope(SelectorNetworkHandler.kt:47)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:82)
        at net.mamoe.mirai.internal.AbstractBot$coroutineContext$1$1.invoke(AbstractBot.kt:59)
        at net.mamoe.mirai.internal.AbstractBot$coroutineContext$1$1.invoke(AbstractBot.kt:55)
        at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1391)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1519)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
        at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:696)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:667)
        at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)
        at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)
        at kotlinx.coroutines.Job$DefaultImpls.cancel$default(Job.kt:189)
        at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:110)
        at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:80)
        at net.mamoe.mirai.Bot.close(Bot.kt:178)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.doLogin(BuiltInCommands.kt:197)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:224)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:305)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:167)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:191)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Login failed: Invalid char 'm' at index 0
2022-01-25 22:09:54 E/console: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:305)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:167)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:191)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalArgumentException: Invalid char 'm' at index 0
        at net.mamoe.mirai.utils.MiraiUtils__ConversionsKt.countHexBytes(Conversions.kt:228)
        at net.mamoe.mirai.utils.MiraiUtils.countHexBytes(Unknown Source)
        at net.mamoe.mirai.utils.MiraiUtils__ConversionsKt.hexToBytes(Conversions.kt:151)
        at net.mamoe.mirai.utils.MiraiUtils.hexToBytes(Unknown Source)
        at net.mamoe.mirai.utils.DeviceInfoManager$HexStringSerializer$special$$inlined$map$1.deserialize(Serialization.kt:92)
        at net.mamoe.mirai.utils.DeviceInfoManager$HexStringSerializer.deserialize-XN8iJCc(DeviceInfo.kt)
        at net.mamoe.mirai.utils.DeviceInfoManager$HexStringSerializer.deserialize(DeviceInfo.kt:265)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
        at net.mamoe.mirai.utils.DeviceInfoManager$V2$$serializer.deserialize(DeviceInfo.kt:328)
        at net.mamoe.mirai.utils.DeviceInfoManager$V2$$serializer.deserialize(DeviceInfo.kt:328)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
        at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
        at net.mamoe.mirai.utils.DeviceInfoManager$Wrapper$$serializer.deserialize(DeviceInfo.kt:272)
        at net.mamoe.mirai.utils.DeviceInfoManager$Wrapper$$serializer.deserialize(DeviceInfo.kt:272)
        at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)
        at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
        at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
        at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
        at net.mamoe.mirai.utils.DeviceInfoManager.deserialize(DeviceInfo.kt:433)
        at net.mamoe.mirai.utils.DeviceInfo$Companion.from(DeviceInfo.kt:114)
        at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt:87)
        at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt:86)
        at net.mamoe.mirai.internal.network.components.SsoProcessorContextKt.createDeviceInfo(SsoProcessorContext.kt:47)
        at net.mamoe.mirai.internal.network.components.SsoProcessorContextImpl.<init>(SsoProcessorContext.kt:42)
        at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:195)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:163)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:162)
        at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
        at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:162)
        at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:249)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:261)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:254)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:218)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:189)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:45)
        at net.mamoe.mirai.internal.QQAndroidBot.getComponents(QQAndroidBot.kt:160)
        at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:135)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.doLogin(BuiltInCommands.kt:196)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:224)
        ... 24 more
```

### 网络日志

```text
NaN
```

**Comment by LaoLittle** [comment]
已知是hex的问题
