### ISSUE TITLE
显示Login Successful却未登录

### ISSUE THREAD

**Issue by LaoLittle** [mamoe/mirai#1857]
### 问题描述

![image](https://user-images.githubusercontent.com/93422095/151521380-a1e1f000-c705-4055-a2f1-37d2e03e6ff8.png)

使用logout会显示未登录
![image](https://user-images.githubusercontent.com/93422095/151522046-4a4e8dd1-711e-49b1-9d3d-15d67a44562b.png)

同时使用此指令也会找不到Bot
![image](https://user-images.githubusercontent.com/93422095/151522121-186c9cf2-568d-4091-b7ff-1dc54cd71d6c.png)

### 复现

相关代码
```kotlin
bot.close()
logger.info {
    "删除$bot 缓存, 结果为: ${bot.configuration.cacheDir.deleteRecursively()}"
}

with(ConsoleCommandSender) {
    runCatching {
        with(BuiltInCommands.LoginCommand) {
            handle(
                id = bot.id,
                protocol = bot.configuration.protocol
            )
        }
        RiskDetector.logger.info { "${Bot.getInstance(bot.id)} 已自动重新登录" }
    }.onFailure {
        RiskDetector.logger.warning { "$bot 重新登陆失败" }
    }
}
```

### mirai-core 版本

2.10.0-RC2

### bot-protocol

IPAD

### 系统日志

```text
2022-01-28 17:33:13 I/RiskDetector: 删除Bot(2966911364) 缓存, 结果为: true
2022-01-28 17:33:13 I/Bot.2966911364: Bot cancelled: Job was cancelled
2022-01-28 17:33:13 I/Bot.2966911364: Loaded account secrets from local cache.
2022-01-28 17:33:13 I/Bot.2966911364: Saved account secrets to local cache for fast login.
2022-01-28 17:33:13 I/Bot.2966911364: Login successful.
2022-01-28 17:33:13 V/Bot.2966911364: Event: BotOnlineEvent(bot=Bot(2966911364))
2022-01-28 17:33:13 I/Bot.2966911364: Bot login successful.
萝卜鱼子酱 (2966911364) Login successful
2022-01-28 17:33:13 I/RiskDetector: Bot(2966911364) 已自动重新登录
2022-01-28 17:33:15 V/Bot.2966911364: Event: BotOfflineEvent.Dropped(bot=Bot(2966911364), cause=NettyChannelException(message=null, cause=null), reconnect=true)
2022-01-28 17:33:15 W/Bot.2966911364: Connection lost, reconnecting... (NettyChannelException(message=null, cause=null))
2022-01-28 17:33:15 I/Bot.2966911364: Saved account secrets to local cache for fast login.
2022-01-28 17:33:15 I/Bot.2966911364: Login successful.
2022-01-28 17:33:15 V/Bot.2966911364: Event: BotOnlineEvent(bot=Bot(2966911364))
2022-01-28 17:33:15 I/pixiv-helper: abilities: [44879979]
2022-01-28 17:33:15 V/Bot.2966911364: Event: BotReloginEvent(bot=Bot(2966911364), cause=null)
2022-01-28 17:33:15 I/Bot.2966911364: Reconnected successfully in 0.386s.
```

### 网络日志

```text
[0m2022-01-28 17:08:16 V/Net 2966911364: Loading server list from cache.[0m
[92m2022-01-28 17:08:16 I/Net 2966911364: Server list: 183.47.102.213:443, 49.7.253.116:443, 49.7.253.65:80, msfwifi.3g.qq.com:8080, 113.96.12.85:8080, 180.102.110.67:8080, 49.7.253.162:443, 49.7.253.147:443, 101.91.42.98:80, 113.96.18.253:14000.[0m
[92m2022-01-28 17:08:16 I/Net 2966911364: ECDH key is valid.[0m
[0m2022-01-28 17:08:16 V/Net 2966911364: Send: wtlogin.exchange_emp[0m
[0m2022-01-28 17:08:16 V/Net 2966911364: Recv: wtlogin.exchange_emp[0m
[0m2022-01-28 17:08:16 V/Net 2966911364: Send: StatSvc.register(online)[0m
[92m2022-01-28 17:08:16 I/Net 2966911364: Server time updated, serverTime: 1643360896, diff: 0ms=0.0s[0m
[0m2022-01-28 17:08:16 V/Net 2966911364: Recv: StatSvc.register[0m
[92m2022-01-28 17:08:16 I/Net 2966911364: Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2022-01-28 17:08:16 I/Net 2966911364: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2022-01-28 17:08:19 I/Net 2966911364: Server list: 42.81.183.253:443, msfwifi.3g.qq.com:8080, 113.96.18.253:14000, 119.147.190.171:443, 101.91.40.83:8080, 42.81.192.198:443, 183.47.101.153:8080, 42.81.176.211:80, 42.81.170.40:443, 114.222.113.249:80.[0m
[0m2022-01-28 17:08:19 V/Net 2966911364: Saving bdh session to cache[0m
[0m2022-01-28 17:08:19 V/Net 2966911364: Saving server list to cache[0m
[0m2022-01-28 17:08:19 V/Net 2966911364: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2022-01-28 17:08:19 V/Net 2966911364: Recv: ConfigPushSvc.PushReq[0m
[0m2022-01-28 17:08:19 V/Net 2966911364: Saving bdh session to cache[0m
[0m2022-01-28 17:08:19 V/Net 2966911364: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2022-01-28 17:08:19 V/Net 2966911364: Recv: ConfigPushSvc.PushReq[0m
[31m2022-01-28 17:12:40 E/Net 2966911364: Exception in coroutine 'unnamed'
ExceptionInPacketCodecException(cause=java.lang.IllegalStateException: 32)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.handleExceptionInDecoding(NettyNetworkHandler.kt:61)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:83)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:73)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: 32
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseOicqResponse(PacketCodec.kt:197)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:108)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:80)
	... 25 more
	Suppressed: net.mamoe.mirai.internal.network.components.OicqDecodingException
	Caused by: [CIRCULAR REFERENCE: java.lang.IllegalStateException: 32]
[0m
[31m2022-01-28 17:12:40 E/Net 2966911364: Exception in coroutine 'unnamed'
ExceptionInPacketCodecException(cause=java.lang.IllegalStateException: 32)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.handleExceptionInDecoding(NettyNetworkHandler.kt:61)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:83)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:73)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: 32
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseOicqResponse(PacketCodec.kt:197)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:108)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:80)
	... 23 more
	Suppressed: net.mamoe.mirai.internal.network.components.OicqDecodingException
	Caused by: [CIRCULAR REFERENCE: java.lang.IllegalStateException: 32]
[0m
[31m2022-01-28 17:17:10 E/Net 2966911364: Exception in coroutine 'unnamed'
ExceptionInPacketCodecException(cause=java.lang.IllegalStateException: 32)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.handleExceptionInDecoding(NettyNetworkHandler.kt:61)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:83)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:73)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: 32
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseOicqResponse(PacketCodec.kt:197)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:108)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:80)
	... 25 more
	Suppressed: net.mamoe.mirai.internal.network.components.OicqDecodingException
	Caused by: [CIRCULAR REFERENCE: java.lang.IllegalStateException: 32]
[0m
[31m2022-01-28 17:17:10 E/Net 2966911364: Exception in coroutine 'unnamed'
ExceptionInPacketCodecException(cause=java.lang.IllegalStateException: 32)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.handleExceptionInDecoding(NettyNetworkHandler.kt:61)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:83)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:73)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: 32
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseOicqResponse(PacketCodec.kt:197)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:108)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:80)
	... 23 more
	Suppressed: net.mamoe.mirai.internal.network.components.OicqDecodingException
	Caused by: [CIRCULAR REFERENCE: java.lang.IllegalStateException: 32]
[0m
[0m2022-01-28 17:21:27 V/Net 2966911364: Loading server list from cache.[0m
[92m2022-01-28 17:21:27 I/Net 2966911364: Server list: 42.81.183.253:443, msfwifi.3g.qq.com:8080, 113.96.18.253:14000, 119.147.190.171:443, 101.91.40.83:8080, 42.81.192.198:443, 183.47.101.153:8080, 42.81.176.211:80, 42.81.170.40:443, 114.222.113.249:80.[0m
[92m2022-01-28 17:21:27 I/Net 2966911364: ECDH key is valid.[0m
[0m2022-01-28 17:21:27 V/Net 2966911364: Send: wtlogin.exchange_emp[0m
[0m2022-01-28 17:21:27 V/Net 2966911364: Recv: wtlogin.exchange_emp[0m
[0m2022-01-28 17:21:27 V/Net 2966911364: Send: StatSvc.register(online)[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Server time updated, serverTime: 1643361688, diff: 0ms=0.0s[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Recv: StatSvc.register[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Syncing friend message history...[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Loading BdhSession from cache file[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Start loading stranger list...[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Start loading friend list...[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Recv: OidbSvc.0x5d2_0[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Successfully loaded stranger list: 0 in total[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Start loading group list...[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Recv: OidbSvc.0x496[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Syncing friend message history: Success.[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Recv: StatSvc.GetDevLoginInfo[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Online OtherClients: Android手机(MOBILE)[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Recv: friendlist.GetTroopListReqV2[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Loading friend list: 3/3[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Recv: friendlist.getFriendGroupList[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Successfully loaded friend list: 3 in total[0m
[0m2022-01-28 17:21:28 V/Net 2966911364: Recv: friendlist.GetTroopMemberListReq[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Successfully loaded group list: 1 in total.[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2022-01-28 17:21:28 I/Net 2966911364: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[0m2022-01-28 17:21:31 V/Net 2966911364: Saving bdh session to cache[0m
[0m2022-01-28 17:21:31 V/Net 2966911364: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2022-01-28 17:21:31 V/Net 2966911364: Recv: ConfigPushSvc.PushReq[0m
[0m2022-01-28 17:22:54 V/Net 2966911364: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-28 17:22:54 V/Net 2966911364: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Send: StatSvc.register(offline)[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Loading server list from cache.[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Server list: 42.81.183.253:443, msfwifi.3g.qq.com:8080, 113.96.18.253:14000, 119.147.190.171:443, 101.91.40.83:8080, 42.81.192.198:443, 183.47.101.153:8080, 42.81.176.211:80, 42.81.170.40:443, 114.222.113.249:80.[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: ECDH key is valid.[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Send: wtlogin.exchange_emp[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Recv: wtlogin.exchange_emp[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Send: StatSvc.register(online)[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Server time updated, serverTime: 1643361777, diff: 0ms=0.0s[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Recv: StatSvc.register[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Syncing friend message history...[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Loading BdhSession from cache file[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Start loading stranger list...[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Start loading friend list...[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Start loading group list...[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Recv: OidbSvc.0x496[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Successfully loaded stranger list: 0 in total[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Recv: OidbSvc.0x5d2_0[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Recv: StatSvc.GetDevLoginInfo[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Online OtherClients: Android手机(MOBILE)[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Recv: friendlist.GetTroopListReqV2[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Loading friend list: 3/3[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Recv: friendlist.getFriendGroupList[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Successfully loaded friend list: 3 in total[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Syncing friend message history: Success.[0m
[0m2022-01-28 17:22:57 V/Net 2966911364: Recv: friendlist.GetTroopMemberListReq[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Successfully loaded group list: 1 in total.[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2022-01-28 17:22:57 I/Net 2966911364: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[0m2022-01-28 17:23:00 V/Net 2966911364: Saving bdh session to cache[0m
[0m2022-01-28 17:23:00 V/Net 2966911364: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2022-01-28 17:23:00 V/Net 2966911364: Recv: ConfigPushSvc.PushReq[0m
```

**Comment by Him188** [comment]
看起来是登录成功后在执行指令之前离线了

**Comment by Him188** [comment]
#1840
