### ISSUE TITLE
在 MultiMsg.ApplyDown 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by LaoLittle** [mamoe/mirai#1863]
### 问题描述

在 MultiMsg.ApplyDown 时遇到了意料之中的问题

### 复现

NaN

### mirai-core 版本

2.10.0-RC2

### bot-protocol

IPAD

### 系统日志

```text
2022-01-30 22:30:02 E/Bot.id: Exception on parsing packet.
java.lang.IllegalStateException: Exception in net.mamoe.mirai.internal.network.notice.group.GroupMessageProcessor@6fcc57b8 while processing packet PbPushMsg.
        at net.mamoe.mirai.internal.network.components.NoticeProcessorPipelineImpl.process$suspendImpl(NoticeProcessorPipeline.kt:241)
        at net.mamoe.mirai.internal.network.components.NoticeProcessorPipelineImpl$process$1.invokeSuspend(NoticeProcessorPipeline.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Failed to download forward message `825+hun0Tsti/4gqf2OUXvSsLTOZfRe7cU3FB39d7srcG4grqlCPNfprrEYCQ9/m`
        at net.mamoe.mirai.internal.MiraiImpl.downloadForwardMessage$suspendImpl(MiraiImpl.kt:843)
        at net.mamoe.mirai.internal.MiraiImpl$downloadForwardMessage$1.invokeSuspend(MiraiImpl.kt)
        ... 12 more
Caused by: ContextualBugReportException(message=在 MultiMsg.ApplyDown 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   Decode failure result=192 调试信息: net.mamoe.mirai.internal.network.protocol.data.proto.MultiMsg$MultiMsgApplyDownRsp@524a8096, cause=null)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.MultiMsg$ApplyDown.decode(MultiMsg.kt:222)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:368)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        ... 4 more
```

### 网络日志

```text
[0m2022-01-30 22:27:09 V/Net id: [Highway] Uploading forward message to 183.47.102.178:80, size=385 B[0m
[0m2022-01-30 22:27:09 V/Net id: [Highway] Uploading forward message: succeed at 7 KiB/s[0m
[0m2022-01-30 22:27:09 V/Net id: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-30 22:27:09 V/Net id: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-30 22:27:13 V/Net id: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)[0m
[0m2022-01-30 22:27:13 V/Net id: Recv: MultiMsg.ApplyDown[0m
[0m2022-01-30 22:27:13 V/Net id: [Http] Downloading forward message from https://ssl.htdata.qq.com:443[0m
[0m2022-01-30 22:27:13 V/Net id: [Http] Downloading forward message: succeed[0m
[0m2022-01-30 22:27:16 V/Net id: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-30 22:27:16 V/Net id: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-30 22:27:17 V/Net id: Send: OidbSvc.0xed3(OidbSvc.0xed3)[0m
[0m2022-01-30 22:27:17 V/Net id: Recv: OidbSvc.0xed3[0m
[0m2022-01-30 22:27:18 V/Net id: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-30 22:27:18 V/Net id: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-30 22:27:45 V/Net id: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-30 22:27:45 V/Net id: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-30 22:27:56 V/Net id: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-30 22:27:56 V/Net id: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-30 22:28:00 V/Net id: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-30 22:28:01 V/Net id: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-30 22:28:02 V/Net id: Send: OidbSvc.0xed3(OidbSvc.0xed3)[0m
[0m2022-01-30 22:28:02 V/Net id: Recv: OidbSvc.0xed3[0m
[0m2022-01-30 22:28:03 V/Net id: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-30 22:28:03 V/Net id: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-30 22:28:06 V/Net id: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-30 22:28:06 V/Net id: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-30 22:28:07 V/Net id: Send: OidbSvc.0xed3(OidbSvc.0xed3)[0m
[0m2022-01-30 22:28:07 V/Net id: Recv: OidbSvc.0xed3[0m
[0m2022-01-30 22:28:08 V/Net id: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-30 22:28:09 V/Net id: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-30 22:28:20 V/Net id: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-30 22:28:20 V/Net id: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-30 22:28:22 V/Net id: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-01-30 22:28:22 V/Net id: Recv: MessageSvc.PbSendMsg[0m
[0m2022-01-30 22:30:02 V/Net id: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)[0m
[31m2022-01-30 22:30:02 E/Net id: Exception in decoding packet.
ContextualBugReportException(message=在 MultiMsg.ApplyDown 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   Decode failure result=192 调试信息: net.mamoe.mirai.internal.network.protocol.data.proto.MultiMsg$MultiMsgApplyDownRsp@524a8096, cause=null)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.MultiMsg$ApplyDown.decode(MultiMsg.kt:222)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:368)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
[0m
```

**Comment by Him188** [comment]
#1833
