### ISSUE TITLE
调用 `Contact.sendMessage(...)` 时有机率抛出异常 `java.lang.IllegalStateException`

### ISSUE THREAD

**Issue by chuanwise** [mamoe/mirai#1876]
### 问题描述

我使用的是 `Mirai-Core`

### 复现

调用 `Contact.sendMessage(...)` 即有几率复现问题

### mirai-core 版本

2.9.1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

[`XiaoMingHostTerminal-4.6.1`](https://github.com/XiaoMingProject/XiaoMingBot) 

### 系统日志

```text
异常信息：
java.lang.IllegalStateException: NetworkHandler is already closed.
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateClosed.sendPacketImpl(NettyNetworkHandler.kt:381)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.sendPacketImpl(NettyNetworkHandler.kt:39)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.sendAndExpect(NetworkHandlerSupport.kt:99)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect$suspendImpl(SelectorNetworkHandler.kt:74)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect(SelectorNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect(NetworkHandler.kt:173)
	at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect$default(NetworkHandler.kt:169)
	at net.mamoe.mirai.internal.contact.SendMessageHandler.sendMessagePacket(SendMessageHandler.kt:138)
	at net.mamoe.mirai.internal.contact.SendMessageHandlerKt.sendMessageImpl(SendMessageHandler.kt:365)
	at net.mamoe.mirai.internal.contact.SendMessageHandlerKt.sendMessage(SendMessageHandler.kt:336)
	at net.mamoe.mirai.internal.contact.GroupImpl.sendMessage(GroupImpl.kt:168)
	at net.mamoe.mirai.internal.contact.GroupImpl$sendMessage$1.invokeSuspend(GroupImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:283)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
	at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:256)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### 网络日志

```text
无
```

### 补充信息

以下是 `XiaoMingBot` 给出的日志信息

```log
【错误报告】
交互器交互时出现异常

【异常概述】
异常时间：2022-02-10 10:25
触发人：「Minecraft[初之元]服务器（317707503）」柠.com（1370018723）
交互器：onlinePlayers
交互类：cn.chuanwise.xiaoming.minecraft.xiaoming.interactors.StateInteractors
注册方：XiaoMingMinecraft
触发消息：在线玩家
原始消息：在线玩家

【异常信息】
java.lang.IllegalStateException: NetworkHandler is already closed.
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateClosed.sendPacketImpl(NettyNetworkHandler.kt:381)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.sendPacketImpl(NettyNetworkHandler.kt:39)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.sendAndExpect(NetworkHandlerSupport.kt:99)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect$suspendImpl(SelectorNetworkHandler.kt:74)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect(SelectorNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect(NetworkHandler.kt:173)
	at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect$default(NetworkHandler.kt:169)
	at net.mamoe.mirai.internal.contact.SendMessageHandler.sendMessagePacket(SendMessageHandler.kt:138)
	at net.mamoe.mirai.internal.contact.SendMessageHandlerKt.sendMessageImpl(SendMessageHandler.kt:365)
	at net.mamoe.mirai.internal.contact.SendMessageHandlerKt.sendMessage(SendMessageHandler.kt:336)
	at net.mamoe.mirai.internal.contact.GroupImpl.sendMessage(GroupImpl.kt:168)
	at net.mamoe.mirai.internal.contact.GroupImpl$sendMessage$1.invokeSuspend(GroupImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:142)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:283)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
	at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:256)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

【详细信息】
用户标签：all、1370018723
为封禁用户：false
为管理员用户：false
过滤器参数：{}
交互器方法：void cn.chuanwise.xiaoming.minecraft.xiaoming.interactors.StateInteractors.onlinePlayers(cn.chuanwise.xiaoming.user.XiaomingUser) throws java.lang.InterruptedException,java.util.concurrent.TimeoutException
交互器方法参数：[cn.chuanwise.xiaoming.user.GroupXiaomingUserImpl@7879aa6a]

【小明信息】
内核版本：4.6.1
启动时间：2022-02-09 20:22
运行时长：14小时3分钟
插件信息：
1、XiaoMingMinecraft-4.5-SNAPSHOT（已启动）
2、Permission-2.8-SNAPSHOT（已启动）
3、Essentials-1.2.4-dev（已启动）
核心配置：
1、maxMainThreadPoolSize = 10
2、maxRecentMessageBufferSize = 10
3、autoAcceptFriendAddRequest = true
4、enableGroupInteractors = true
5、enableMemberInteractors = true
6、savePeriod = 1800000
7、maxGroupUserQuantityInReceptionist = 10
8、saveFileDirectly = true
9、enableStartLog = false
10、maxIterateTime = 20
11、enableGroupSend = true
12、debug = false
13、sendMessagePeriod = 3000
14、enablePrivateSend = true
15、trimMessage = true
16、maxReceptionistQuantity = 50
17、maxUserAttributeQuantity = 20
18、autoAcceptGroupInvite = false
19、enablePrivateInteractors = true
20、optimizePeriod = 600000
21、maxUserInputTimeout = 600000
22、enableMemberSend = true
23、maxUserPrivateInputTimeout = 600000
24、maxMemberUserQuantityInReceptionist = 3
25、sendMessageTimeout = 120000
26、delayWrite = false
27、maxUserGroupInputTimeout = 600000

【环境信息】
JDK 版本：17.0.2
JVM 名称：Java HotSpot(TM) 64-Bit Server VM
OS 名称：Windows Server 2019
```

**Comment by Him188** [comment]
这个原因是 bot 离线了
