### ISSUE TITLE
在 MultiMsg.ApplyDown 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#1877]
### 问题描述

接收到转发消息报错

### 复现

None

### mirai-core 版本

2.10.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2022-02-10 19:40:02 E/Bot.3337342367: Exception on parsing packet.
java.lang.IllegalStateException: Exception in net.mamoe.mirai.internal.network.notice.group.GroupMessageProcessor@3b0eab9c while processing packet PbPushMsg.
        at net.mamoe.mirai.internal.network.components.NoticeProcessorPipelineImpl.process$suspendImpl(NoticeProcessorPipeline.kt:241)
        at net.mamoe.mirai.internal.network.components.NoticeProcessorPipelineImpl$process$1.invokeSuspend(NoticeProcessorPipeline.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Failed to download forward message `NuRCal9/SvySEe3SymOlJuAUQ+ZIUE5RYiQhH+DoxtuF60iAKPFpjCxLFA2xUWLO`
        at net.mamoe.mirai.internal.MiraiImpl.downloadForwardMessage$suspendImpl(MiraiImpl.kt:843)
        at net.mamoe.mirai.internal.MiraiImpl$downloadForwardMessage$1.invokeSuspend(MiraiImpl.kt)
        ... 12 more
Caused by: ContextualBugReportException(message=在 MultiMsg.ApplyDown 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   Decode failure result=192 调试信息: net.mamoe.mirai.internal.network.protocol.data.proto.MultiMsg$MultiMsgApplyDownRsp@7c94e296, cause=null)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.MultiMsg$ApplyDown.decode(MultiMsg.kt:222)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:368)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        ... 7 more
```

### 网络日志

```text
[0m2022-02-10 19:40:01 V/Net 3337342367: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)[0m
[31m2022-02-10 19:40:02 E/Net 3337342367: Exception in decoding packet.
ContextualBugReportException(message=在 MultiMsg.ApplyDown 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   Decode failure result=192 调试信息: net.mamoe.mirai.internal.network.protocol.data.proto.MultiMsg$MultiMsgApplyDownRsp@7c94e296, cause=null)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.MultiMsg$ApplyDown.decode(MultiMsg.kt:222)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:368)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
[0m
[0m2022-02-10 19:41:56 V/Net 3337342367: Send: ImgStore.GroupPicUp(ImgStore.GroupPicUp)[0m
```

**Comment by Him188** [comment]
#1863

**Comment by remloyal** [comment]
解决了嘛？
