### ISSUE TITLE
无法发送带图片的消息

### ISSUE THREAD

**Issue by skommando** [mamoe/mirai#1882]
### 问题描述

机器人无法发送带图片的消息。

console有日志，但是qq收不到图片和消息。能收到纯文本，但只要带图片就整条都收不到。
![image](https://user-images.githubusercontent.com/22767889/153769505-d9e21bec-85e7-4f0c-802b-b5c3d3de8d39.png)

#### 回复消息实现：
![image](https://user-images.githubusercontent.com/22767889/153769793-361cb63a-3d75-45f1-9a35-3eee90105b18.png)
#### 效果：
带图片的整条消息不显示。

![image](https://user-images.githubusercontent.com/22767889/153769909-4fd3e30c-3055-4525-b673-0bee18f2f1f4.png)
![$Y(62YEWALE H8M}SXV1I%6](https://user-images.githubusercontent.com/22767889/153769919-ee051c7d-3728-4ff8-82c9-d28930228ab3.png)
![image](https://user-images.githubusercontent.com/22767889/153769992-4f01b889-858d-4763-b84b-b9f1127ead0f.png)

### mirai-core 版本

2.7.1-dev-1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

![image](https://user-images.githubusercontent.com/22767889/153769517-0fc690c2-02e7-45d5-908e-b83c7f63cea5.png)
![image](https://user-images.githubusercontent.com/22767889/153769523-fd8c0b13-11e1-4b4d-8b6d-22b7438b04e7.png)
![image](https://user-images.githubusercontent.com/22767889/153769527-42783de3-e437-43c1-ab17-9ba15497d05c.png)
![image](https://user-images.githubusercontent.com/22767889/153769683-a465e90f-e642-49c2-81fc-afb69b84b746.png)

### 系统日志

```text
暂无
```

### 网络日志

```text
暂无
```

### 补充信息
图片消息发送好友是正常的。
![image](https://user-images.githubusercontent.com/22767889/153772171-c02d29a6-df0f-4bbe-9959-4d16bb6e6c32.png)
![image](https://user-images.githubusercontent.com/22767889/153772136-79da674b-3dbf-4990-b477-8bc0297a34da.png)
![image](https://user-images.githubusercontent.com/22767889/153772123-fea0b20c-e2b3-4023-8649-52ac011c8753.png)

**Comment by Him188** [comment]
换几张图发试试

**Comment by Him188** [comment]
不行就试试 2.10.0

**Comment by skommando** [comment]
> 换几张图发试试

换过不同图片，fromlocalfile 和 fromNetworkAddress 都试过，不成功。

**Comment by skommando** [comment]
> 不行就试试 2.10.0

2.10.0 遇到另一个问题，400 bad request，之前是因为这个才换成 2.7.0。
日志：
[2022-02-14 11:27:32,447][INFO]: 3046594859: [test1(471810731)] 你毛(489289314) -> '[mirai:source:2090,1644809252]3'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/graia/broadcast/__init__.py", line 204, in Executor
    result = await run_always_await_safely(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/graia/broadcast/utilles.py", line 30, in run_always_await_safely
    return await callable(*args, **kwargs)
  File "/Users/eric.qiu/codes/git-repos/BFserver-Bot/Group.py", line 108, in pixiv_Group_listener
    await app.sendGroupMessage(group, MessageChain.create([At(member.id), Plain(" BINGO")]), quote=message[Source][0])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/graia/application/__init__.py", line 67, in wrapped_network_action_callable
    return await network_action_callable(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/graia/application/utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/graia/application/__init__.py", line 644, in sendGroupMessage
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('http://localhost:8081/sendGroupMessage')

发任何消息都会报这个问题。

我是从这里得到提示降版本的。
https://mirai.mamoe.net/topic/369/python%E6%80%8E%E6%A0%B7-%E5%85%A8%E4%BD%93%E6%88%90%E5%91%98/8?lang=zh-CN

**Comment by Him188** [comment]
mirai的更新是向下兼容的, mirai-api-http v1.12 基于 2.7 开发但理论上也会支持所有 2.7 及以后的版本. @ryoii any ideas?

**Comment by ryoii** [comment]
只有有限情况下会返回 http 400 的状态码，而且这个时候 response body 应该是有数据的。两个方面去调试，试下能否从你使用的SDK内取到报错返回的数据，确定是什么地方导致了请求错误。第二，尝试使用原生的 http 接口发送请求

**Comment by Karlatemp** [comment]
群图片发送问题早已在 [2.8.0-M1](https://github.com/mamoe/mirai/releases/tag/v2.8.0-M1), [2.9.1](https://github.com/mamoe/mirai/releases/tag/v2.9.1) 修复，请更新,
关于 http 400 的问题请开启 mirai-api-http 的 debug log 并报告至 mirai-api-http
