### ISSUE TITLE
ContextualBugReportException

### ISSUE THREAD

**Issue by moxisuki** [mamoe/mirai#1886]
14:29:25 [INFO] Verifying "net.mamoe:mirai-console" v2.10.0
  14:29:26 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.10.0
  14:29:26 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.0
  14:29:26 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
2022-02-15 14:29:28 I/main: Starting mirai-console...
2022-02-15 14:29:28 I/main: Backend: version 2.10.0, built on 2022-02-01 00:02:35.
2022-02-15 14:29:28 I/main: Frontend Terminal: version 2.10.0, provided by Mamoe Technologies
2022-02-15 14:29:28 I/main: Welcome to visit https://mirai.mamoe.net/
2022-02-15 14:29:29 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2022-02-15 14:29:29 I/plugin: Successfully loaded plugin SkikoMirai v1.0
2022-02-15 14:29:29 I/plugin: Successfully loaded plugin WordCloudPlugin v0.0.5
2022-02-15 14:29:30 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-02-15 14:29:30 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
2022-02-15 14:29:30 I/SkikoMirai: Plugin loaded
2022-02-15 14:29:30 I/WordCloudPlugin: WordCloudPlugin Plugin loaded
2022-02-15 14:29:30 I/main: 3 plugin(s) enabled.
2022-02-15 14:29:30 I/main: Auto-login 2289475646
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2022-02-15 14:29:33 I/Bot.2289475646: Loaded account secrets from local cache.
2022-02-15 14:29:33 I/Bot.2289475646: Saved account secrets to local cache for fast login.
2022-02-15 14:29:33 I/Bot.2289475646: Login successful.
2022-02-15 14:29:35 E/Group: ContextualBugReportException(message=在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志
提交给 mirai: https://github.com/mamoe/mirai/issues/new   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个 群 调试信息: groupId: 546585046
groupUin: 546585046
membersCount: 0
botId: 2289475646
owner: null, cause=null)
ContextualBugReportException(message=在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 546585046
groupUin: 546585046
membersCount: 0
botId: 2289475646
owner: null, cause=null)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
        at net.mamoe.mirai.internal.contact.GroupImplKt.GroupImpl(GroupImpl.kt:96)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.addGroupToBot(ContactUpdater.kt:212)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.access$addGroupToBot(ContactUpdater.kt:74)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl$addGroupToBot$1.invokeSuspend(ContactUpdater.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2022-02-15 14:29:35 V/Bot.2289475646: Event: BotOnlineEvent(bot=Bot(2289475646))
2022-02-15 14:29:35 I/Bot.2289475646: Bot login successful.
2022-02-15 14:29:35 I/main: mirai-console started successfully.

**Comment by Him188** [comment]
请使用 issue 模板并根据报错提示内容提供相关信息（“并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群”）
