### ISSUE TITLE
登录错误：type mismatch. Expected SIMPLE_LIST or LIST, got TarsHead(tag=1, type=8(Map)) instead

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1899]
登录时刷出来的错误,详细日志
```
[18:56:30] [INFO] Starting mirai-console... 
[18:56:30] [INFO] Backend: version 2.10.0, built on 2021-04-16 10:35:28. 
[18:56:30] [INFO] Welcome to visit https://mirai.mamoe.net/ 
[18:56:30] [INFO] Successfully loaded plugin ZhaoDice 
[18:56:31] [INFO] Prepared built-in commands: autoLogin, help, login, permission, status, stop 
[18:56:31] [INFO] AccountsCloudDevices registered 
[18:56:31] [INFO] Loaded account secrets from local cache. 
[18:56:31] [INFO] ECDH key is valid. 
[18:56:31] [INFO] Saved account secrets to local cache for fast login. 
[18:56:31] [INFO] Login successful. 
[18:56:31] [INFO] Server time updated, serverTime: 1645613791, diff: 0ms=0.0s 
[18:56:31] [ERROR] Exception in decoding packet. 
[18:56:31] [ERROR] java.lang.IllegalStateException: type mismatch. Expected SIMPLE_LIST or LIST, got TarsHead(tag=1, type=8(Map)) instead
	at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.beginStructure(Unknown Source:282)
	at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder$MapReaderImpl.beginStructure(Unknown Source:146)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(Unknown Source:27)
	at kotlinx.serialization.internal.PrimitiveArraySerializer.deserialize(Unknown Source:6)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Unknown Source:10)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(Unknown Source:0)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(Unknown Source:5)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(Unknown Source:10)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Unknown Source:7)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(Unknown Source:113)
	at kotlinx.serialization.internal.MapLikeSerializer.readAll(Unknown Source:53)
	at kotlinx.serialization.internal.MapLikeSerializer.readAll(Unknown Source:2)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(Unknown Source:41)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(Unknown Source:6)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Unknown Source:10)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Unknown Source:0)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Unknown Source:5)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Unknown Source:6)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Unknown Source:3)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Unknown Source:19)
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestDataVersion3$$serializer.deserialize(Unknown Source:58)
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestDataVersion3$$serializer.deserialize(Unknown Source:0)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Unknown Source:10)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Unknown Source:0)
	at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load(Unknown Source:26)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(Unknown Source:33)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(Unknown Source:0)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(Unknown Source:130)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(Unknown Source:0)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket(Unknown Source:15)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readUniPacket(Unknown Source:0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.decode(Unknown Source:8)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(Unknown Source:157)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(Unknown Source:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:13)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(Unknown Source:0)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Unknown Source:28)
	at io.netty.channel.nio.NioEventLoop.run(Unknown Source:155)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source:41)
	at io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source:8)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:929)

[18:56:31] [INFO] Syncing friend message history... 
[18:56:31] [INFO] Start loading friend list... 
[18:56:31] [INFO] Start loading stranger list... 
[18:56:32] [INFO] Successfully loaded stranger list: 0 in total 
[18:56:32] [INFO] Start loading group list... 
[18:56:32] [INFO] No OtherClient online. 
[18:56:32] [INFO] Successfully loaded friend list: 11 in total 
[18:56:32] [INFO] Saved 11 friends to local cache. 
[18:56:32] [INFO] Syncing friend message history: Success. 
[18:56:34] [INFO] Successfully loaded group list: 7 in total. 
[18:56:34] [INFO] Saved 7 groups to local cache. 
[18:56:34] [INFO] Scheduled key refresh in 23h 55min 0.0s. 
[18:56:34] [INFO] Scheduled refresh login session in 19d 23h 55min 0.0s. 
[18:56:35] [INFO] Bot login successful. 
[18:56:35] [INFO] ->>Login Operation finished.<<- 
[18:56:37] [INFO] selected ZhaoDiceServer: https://s03.trpgbot.com 
[18:56:37] [INFO] online reporter during updated to 1800000 
[18:57:31] [WARNING] Missing ConfigPush. Switching server... 
[18:57:31] [WARNING] Connection lost, reconnecting... (java.lang.IllegalStateException: Timeout waiting for ConfigPush.) 
```

发消息也是抛出这个错误：`Timeout waiting for ConfigPush`

**Comment by zhaodice** [comment]
协议有变化？

**Comment by sandtechnology** [comment]
无法重现此问题，请求msfwifi.3g.qq.com在环境内的解析ip（通过ping获得)

**Comment by zhaodice** [comment]
我这边的错误是手机APP的用户所产生，并不是本人开发者的环境，因此可能网络环境并不一定能复现，先艾特一下这个人看看能否提供更多的情况 @Cnzw  
(PS: 你好，请问方便能提供一下你机器环境下的 ping msfwifi.3g.qq.com 信息吗，如果可以将不胜感激)

**Comment by zhaodice** [comment]
我这边也将默认打开 msfwifi.3g.qq.com 的IP信息，如果可以复现将在下一次提供

**Comment by Cnzw** [comment]
> 我这边的错误是手机APP的用户所产生，并不是本人开发者的环境，因此可能网络环境并不一定能复现，先艾特一下这个人看看能否提供更多的情况 @Cnzw (PS: 你好，请问方便能提供一下你机器环境下的 ping msfwifi.3g.qq.com 信息吗，如果可以将不胜感激)

我这边 Mirai 自错误出现后，自2月27日启动至今（3月2日）没有复现该错误 ~~摸不着头脑~~

以下是 msfwifi.3g.qq.com ping

```
$ ping msfwifi.3g.qq.com
PING msfwifi.3g.qq.com (49.7.253.214) 56(84) bytes of data.
64 bytes from 49.7.253.214: icmp_seq=1 ttl=48 time=26.1 ms
64 bytes from 49.7.253.214: icmp_seq=2 ttl=48 time=26.2 ms
64 bytes from 49.7.253.214: icmp_seq=3 ttl=48 time=26.1 ms
64 bytes from 49.7.253.214: icmp_seq=4 ttl=48 time=25.8 ms
64 bytes from 49.7.253.214: icmp_seq=5 ttl=48 time=26.1 ms
64 bytes from 49.7.253.214: icmp_seq=6 ttl=48 time=27.3 ms
64 bytes from 49.7.253.214: icmp_seq=7 ttl=48 time=25.8 ms
64 bytes from 49.7.253.214: icmp_seq=8 ttl=48 time=25.9 ms
64 bytes from 49.7.253.214: icmp_seq=9 ttl=48 time=25.9 ms
64 bytes from 49.7.253.214: icmp_seq=10 ttl=48 time=26.9 ms
64 bytes from 49.7.253.214: icmp_seq=11 ttl=48 time=26.2 ms
64 bytes from 49.7.253.214: icmp_seq=12 ttl=48 time=26.1 ms
64 bytes from 49.7.253.214: icmp_seq=13 ttl=48 time=26.1 ms
64 bytes from 49.7.253.214: icmp_seq=14 ttl=48 time=26.1 ms
64 bytes from 49.7.253.214: icmp_seq=15 ttl=48 time=26.1 ms
64 bytes from 49.7.253.214: icmp_seq=16 ttl=48 time=26.3 ms
64 bytes from 49.7.253.214: icmp_seq=17 ttl=48 time=25.9 ms
64 bytes from 49.7.253.214: icmp_seq=18 ttl=48 time=25.9 ms
64 bytes from 49.7.253.214: icmp_seq=19 ttl=48 time=26.1 ms
64 bytes from 49.7.253.214: icmp_seq=20 ttl=48 time=25.9 ms
^C
--- msfwifi.3g.qq.com ping statistics ---
20 packets transmitted, 20 received, 0% packet loss, time 28058ms
rtt min/avg/max/mdev = 25.887/26.191/27.346/0.397 ms
```

**Comment by Him188** [comment]
如果有人也遇到这个问题，点这个评论下的👀

**Comment by Nambers** [comment]
我也出现了这个, 目前是每次登录mirai-core 2.11.0-M1 都会出现, 协议: android_pad, 我把我日志也贴过来
日志(有一点小不同):
```
2022.03.23 19:31:14 [INFO ] mamoe.mirai.Bot - ECDH key is valid.
2022.03.23 19:31:14 [INFO ] mamoe.mirai.Bot - Saved account secrets to local cache for fast login.
2022.03.23 19:25:19 [ERROR] mamoe.mirai.Bot - Exception in decoding packet.
java.lang.IllegalStateException: type mismatch. Expected SIMPLE_LIST or LIST, got TarsHead(tag=1, type=8(Map)) instead
	at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.beginStructure(TarsDecoder.kt:260) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder$MapReaderImpl.beginStructure(TarsDecoder.kt:149) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.PrimitiveArraySerializer.deserialize(CollectionSerializers.kt:179) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.MapLikeSerializer.readAll(CollectionSerializers.kt:96) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.MapLikeSerializer.readAll(CollectionSerializers.kt:84) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:31) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:177) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestDataVersion3$$serializer.deserialize(RequestPacket.kt:33) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestDataVersion3$$serializer.deserialize(RequestPacket.kt:33) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:177) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load(Tars.kt:42) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:42) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(utils.kt:121) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(utils.kt:1) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket(utils.kt:85) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readUniPacket(utils.kt:1) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.decode(ConfigPushSvc.kt:78) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:369) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175) [mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2022.03.23 19:31:14 [INFO ] mamoe.mirai.Bot - Login successful.
```
ping:
```
Pinging msfwifi.3g.qq.com [113.96.18.253] with 32 bytes of data:
Reply from 113.96.18.253: bytes=32 time=14ms TTL=55
Reply from 113.96.18.253: bytes=32 time=9ms TTL=55
Reply from 113.96.18.253: bytes=32 time=10ms TTL=55
Reply from 113.96.18.253: bytes=32 time=8ms TTL=55

Ping statistics for 113.96.18.253:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 8ms, Maximum = 14ms, Average = 10ms
```

**Comment by Him188** [comment]
请参考 https://github.com/mamoe/mirai/blob/dev/docs/UsingSnapshots.md, 使用 `2.11.0-dev-ad5132e1`, 并添加 JVM 启动参数: `-Dmirai.jce.deserializer.debug=true`, 复现问题, 并提交相关日志

**Comment by zhaodice** [comment]
发在了 #1991

**Comment by Him188** [comment]
与 #1899 是一样的问题
