### ISSUE TITLE
Core 0.32.0 无法加载任何插件

### ISSUE THREAD

**Issue by zhzRedstone** [mamoe/mirai#193]
日志如下
$ java -Xmx512M -jar mirai-console-wrapper-0.2.0-all.jar
You are running Mirai-Console-Wrapper under /home/app/qqbot
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Fetching Newest Console Version of Pure
Local Console-Pure Version: 0.4.2 | Newest Console-Pure Version: 0.4.2
Local Core Version: 0.32.0 | Newest Core Version: 0.32.0
Version check complete, starting Mirai
shadow-Protocol:/home/app/qqbot/content/mirai-core-qqandroid-jvm-0.32.0.jar
Console :/home/app/qqbot/content/mirai-console-0.4.2.jar
Root :/home/app/qqbot/
10:04:11 [INFO] [Mirai 0.4.2 Pkmon] Mirai-console now running under /home/app/qqbot
10:04:11 [INFO] [Mirai 0.4.2 Pkmon] Get news in github: https://github.com/mamoe/mirai
10:04:11 [INFO] [Mirai 0.4.2 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
10:04:11 [INFO] [Mirai 0.4.2 Pkmon] Powered by Mamoe Technologies and contributors
10:04:11 [INFO] [Plugin Manager] 开始加载/home/app/qqbot/plugins/下的插件
Exception in thread "main" java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.mamoe.mirai.console.wrapper.WrapperMain.start(WrapperMain.kt:150)
at net.mamoe.mirai.console.wrapper.WrapperMain.preStartInNonNative(WrapperMain.kt:133)
at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:89)
Caused by: java.lang.NoClassDefFoundError: org/yaml/snakeyaml/Yaml
at net.mamoe.mirai.console.plugins.YamlConfig.deserialize(ConfigSection.kt:527)
at net.mamoe.mirai.console.plugins.FileConfigImpl$content$2.invoke(ConfigSection.kt:443)
at net.mamoe.mirai.console.plugins.FileConfigImpl$content$2.invoke(ConfigSection.kt:428)
at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
at net.mamoe.mirai.console.plugins.FileConfigImpl.getContent(ConfigSection.kt)
at net.mamoe.mirai.console.plugins.FileConfigImpl.get(ConfigSection.kt:476)
at net.mamoe.mirai.console.plugins.ConfigSection$DefaultImpls.getString(ConfigSection.kt:288)
at net.mamoe.mirai.console.plugins.FileConfigImpl.getString(ConfigSection.kt:428)
at net.mamoe.mirai.console.plugins.PluginDescription$Companion.readFromContent(PluginBase.kt:152)
at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins(PluginManager.kt:91)
at net.mamoe.mirai.console.MiraiConsole.start(MiraiConsole.kt:85)
at net.mamoe.mirai.console.pure.MiraiConsolePureLoader$Companion.load(MiraiConsolePureLoader.kt:22)
at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.load(MiraiConsolePureLoader.kt)
... 7 more
Caused by: java.lang.ClassNotFoundException: org.yaml.snakeyaml.Yaml
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
... 20 more

## 复现
把插件放进plugins文件夹 重启
出现问题

**Comment by Him188** [comment]
关闭 console，删除 contents 文件夹，启动 console
