### ISSUE TITLE
启动提示版本过低

### ISSUE THREAD

**Issue by Zake-arias** [mamoe/mirai#1932]
### 问题描述

主要内容：`2022-03-14 17:33:24 W/stderr: 	Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3094108953), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )]`

全文：
```2022-03-14 17:33:24 W/stderr: 	Suppressed: java.util.concurrent.CancellationException: Bot closed
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
2022-03-14 17:33:24 W/stderr: 		at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
2022-03-14 17:33:24 W/stderr: 		at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:80)
2022-03-14 17:33:24 W/stderr: 		at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
2022-03-14 17:33:24 W/stderr: 		at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
2022-03-14 17:33:24 W/stderr: 		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1408)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1519)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
2022-03-14 17:33:24 W/stderr: 		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
2022-03-14 17:33:24 W/stderr: 		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2022-03-14 17:33:24 W/stderr: 		... 8 more
2022-03-14 17:33:24 W/stderr: 	Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3094108953), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )]
> ```

### 复现

正常登录

### mirai-core 版本

2.10.1

### bot-protocol

MACOS

### 其他组件版本

_No response_

### 系统日志

```text
[0m2022-03-14 17:32:03 V/Net 3094108953: No server list cached.[0m
[92m2022-03-14 17:32:03 I/Net 3094108953: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2022-03-14 17:32:04 I/Net 3094108953: Successfully fetched ecdh public key from server.[0m
[0m2022-03-14 17:32:04 V/Net 3094108953: Send: wtlogin.login[0m
[0m2022-03-14 17:32:04 V/Net 3094108953: Recv: wtlogin.login[0m
[0m2022-03-14 17:32:32 V/Net 3094108953: Send: wtlogin.login[0m
[0m2022-03-14 17:32:32 V/Net 3094108953: Recv: wtlogin.login[0m
[91m2022-03-14 17:32:32 W/Net 3094108953: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3094108953), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3094108953), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
[0m2022-03-14 17:33:06 V/Net 3094108953: No server list cached.[0m
[92m2022-03-14 17:33:06 I/Net 3094108953: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2022-03-14 17:33:07 I/Net 3094108953: Successfully fetched ecdh public key from server.[0m
[0m2022-03-14 17:33:07 V/Net 3094108953: Send: wtlogin.login[0m
[0m2022-03-14 17:33:07 V/Net 3094108953: Recv: wtlogin.login[0m
[0m2022-03-14 17:33:24 V/Net 3094108953: Send: wtlogin.login[0m
[0m2022-03-14 17:33:24 V/Net 3094108953: Recv: wtlogin.login[0m
[91m2022-03-14 17:33:24 W/Net 3094108953: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3094108953), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3094108953), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
```

**Comment by Him188** [comment]
密码错了

**Comment by PikPikLiu** [comment]
作者您好，我这个密码毫无问题，然后过滑块之后就显示版本问题，但是我小号密码和大号一样，我改了账号，密码没动，登录小号，毫无问题，请您帮忙看看这是什么问题
C:\Users\14740\Desktop\mcl-1.2.2 (1)>.\mcl
  23:09:06 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  23:09:06 [INFO] https://github.com/iTXTech/mirai-console-loader
  23:09:06 [INFO] This program is licensed under GNU AGPL v3
  23:09:06 [INFO] Fetching Mirai Console Loader Announcement...
  23:09:07 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

  23:09:07 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
  23:09:07 [INFO] Verifying "net.mamoe:mirai-console" v2.11.0-M1
  23:09:07 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.11.0-M1
  23:09:08 [INFO] Verifying "net.mamoe:mirai-core-all" v2.11.0-M1
  23:09:08 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
  23:09:08 [INFO] Verifying "net.mamoe:mirai-api-http" v1.10.0
  23:09:08 [WARN] Package "net.mamoe:mirai-api-http" has newer version "2.4.0"
  23:09:08 [INFO] Verifying "io.github.gnuf0rce:mirai-content-censor" v1.2.2
  23:09:08 [WARN] Run ./mcl -u to update packages.
  23:09:08 [WARN] Package "net.mamoe:mirai-api-http" requires "net.mamoe:mirai-console" version 2.5.0. Current version is 2.11.0-M1
2022-03-22 23:09:09 I/main: Starting mirai-console...
2022-03-22 23:09:10 I/main: Backend: version 2.11.0-M1, built on 2022-03-08 20:34:54.
2022-03-22 23:09:10 I/main: Frontend Terminal: version 2.11.0-M1, provided by Mamoe Technologies
2022-03-22 23:09:10 I/main: Welcome to visit https://mirai.mamoe.net/
2022-03-22 23:09:10 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-03-22 23:09:10 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-03-22 23:09:10 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-03-22 23:09:10 I/plugin: Successfully loaded plugin p_0-Author-HRS-LSys-Loaded v0.2.9
2022-03-22 23:09:10 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-03-22 23:09:10 I/plugin: Successfully loaded plugin dada.douDiZhu v1.0-SNAPSHOT
2022-03-22 23:09:10 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2022-03-22 23:09:10 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v1.10.0
2022-03-22 23:09:10 I/plugin: Successfully loaded plugin content-censor v1.2.2
2022-03-22 23:09:10 I/plugin: Successfully loaded plugin 点歌插件 v1.1.7
2022-03-22 23:09:10 W/p_7 Author - HRS LSys sco1 Loaded: Linked class cn.kloping.lsys.Resource in a1-miraiLSys.jar but plugin not depend on it.
2022-03-22 23:09:10 W/p_7 Author - HRS LSys sco1 Loaded: Class loading logic may change in feature.
2022-03-22 23:09:10 I/plugin: Successfully loaded plugin p_7 Author - HRS LSys sco1 Loaded v0.1
2022-03-22 23:09:10 W/p_8 Author-HRS-LSys-sco2-Loaded: Linked class cn.kloping.lsys.Resource in a1-miraiLSys.jar but plugin not depend on it.
2022-03-22 23:09:10 W/p_8 Author-HRS-LSys-sco2-Loaded: Class loading logic may change in feature.
2022-03-22 23:09:10 I/plugin: Successfully loaded plugin p_8 Author-HRS-LSys-sco2-Loaded v0.1.2
2022-03-22 23:09:10 W/plugin_9 Author - HRS LSys idiom Loaded: Linked class cn.kloping.lsys.entitys.User in a1-miraiLSys.jar but plugin not depend on it.
2022-03-22 23:09:10 W/plugin_9 Author - HRS LSys idiom Loaded: Class loading logic may change in feature.
2022-03-22 23:09:10 I/plugin: Successfully loaded plugin plugin_9 Author - HRS LSys idiom Loaded v0.1
2022-03-22 23:09:10 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-03-22 23:09:10 I/p_0-Author-HRS-LSys-Loaded: HRS's LSys Plugin loaded! @作者:qq-3474006766
2022-03-22 23:09:11 I/dada.douDiZhu: Plugin loaded
2022-03-22 23:09:11 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
2022-03-22 23:09:11 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2022-03-22 23:09:11 I/net.mamoe.mirai-api-http: Starting Mirai HTTP Server in 0.0.0.0:8080
2022-03-22 23:09:11 I/Mirai HTTP API: Http api server is running with authKey: INITKEYUj5PgCJm
2022-03-22 23:09:11 I/net.mamoe.mirai-api-http: 心跳模块启用状态: false
2022-03-22 23:09:11 I/net.mamoe.mirai-api-http: 上报模块启用状态: false
2022-03-22 23:09:11 E/Mirai HTTP API: java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
java.lang.NoSuchMethodError: 'double kotlin.time.DurationKt.toDuration(int, java.util.concurrent.TimeUnit)'
        at mirai-api-http-1.10.0.jar//net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt:48)
        at mirai-api-http-1.10.0.jar//net.mamoe.mirai.api.http.route.BaseRouteKt$mirai$2.invoke(BaseRoute.kt)
        at mirai-api-http-1.10.0.jar//io.ktor.features.CORS$Feature.install(CORS.kt:517)
        at mirai-api-http-1.10.0.jar//io.ktor.features.CORS$Feature.install(CORS.kt:509)
        at mirai-api-http-1.10.0.jar//io.ktor.application.ApplicationFeatureKt.install(ApplicationFeature.kt:68)
        at mirai-api-http-1.10.0.jar//net.mamoe.mirai.api.http.route.BaseRouteKt.mirai(BaseRoute.kt:45)
        at mirai-api-http-1.10.0.jar//net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:93)
        at mirai-api-http-1.10.0.jar//net.mamoe.mirai.api.http.MiraiHttpAPIServer$start$2$1$1.invoke(MiraiHttpAPIServer.kt:29)
        at mirai-api-http-1.10.0.jar//io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:303)
        at mirai-api-http-1.10.0.jar//io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:138)
        at mirai-api-http-1.10.0.jar//io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:270)
        at mirai-api-http-1.10.0.jar//io.ktor.server.cio.CIOApplicationEngine$serverJob$1$1.invokeSuspend(CIOApplicationEngine.kt:53)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2022-03-22 23:09:11 I/content-censor: 关闭审查请赋予权限 io.github.gnuf0rce.content-censor:no-censor 于用户
2022-03-22 23:09:11 W/content-censor: 未安装 mirai-administrator
ffmpeg version 2022-03-17-git-242c07982a-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.2.0 (Rev7, Built by MSYS2 project)
configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
libavutil      57. 24.101 / 57. 24.101
libavcodec     59. 25.100 / 59. 25.100
libavformat    59. 20.100 / 59. 20.100
libavdevice    59.  6.100 / 59.  6.100
libavfilter     8. 29.100 /  8. 29.100
libswscale      6.  6.100 /  6.  6.100
libswresample   4.  6.100 /  4.  6.100
libpostproc    56.  5.100 / 56.  5.100
2022-03-22 23:09:11 I/点歌插件: 当前配置项：宽域AMR:true AMR自动大小:false
2022-03-22 23:09:11 I/点歌插件: 插件加载完毕!
2022-03-22 23:09:11 I/p_7 Author - HRS LSys sco1 Loaded:
2022-03-22 23:09:11 I/p_8 Author-HRS-LSys-sco2-Loaded:
2022-03-22 23:09:11 I/plugin_9 Author - HRS LSys idiom Loaded:
2022-03-22 23:09:11 I/main: 10 plugin(s) enabled.
2022-03-22 23:09:11 I/main: mirai-console started successfully.
> login 1474058663 (xxxxxxxxxxx这里我隐藏了，这是我的密码)
2022-03-22 23:09:23 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2022-03-22 23:09:23 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2022-03-22 23:09:23 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2022-03-22 23:09:46 I/Bot.1474058663: Bot cancelled: Bot closed
Login failed: Error(bot=Bot(1474058663), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=)
2022-03-22 23:09:46 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1474058663), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1474058663), code=235, title=温馨提示, message=当前版本过 低，请升级到QQ最新版本。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
        Suppressed: java.util.concurrent.CancellationException: Bot closed
                at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
                at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
                at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:80)
                at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
                at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                ... 4 more
        Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1474058663), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo=)]

**Comment by Him188** [comment]
尝试开启或关闭设备锁

**Comment by PikPikLiu** [comment]
作者您好！我现在开启了设备锁，今天早上登录的时候，弹出了那个窗口，但是没有滑块认证了，就是一个设备锁验证和一个URL，点击设备锁验证之后，我用那个过滑块软件扫码，手机界面直接显示版本过低，不支持登录，让我更新版本，我此手机的qq是最新版，所以我预计您的这个软件不是截取的手机qq版本，是内嵌写好的版本，我估计昨天的这个过了滑块之后出现的这个版本过低的情况也是因为这个过滑块的软件，估计是软件里面写的qq版本过低，我自己想的逻辑应该是这样，不知道您怎么看

**Comment by Him188** [comment]
有些账号就是没法用账号密码登录，因为mirai不支持手机号登录所以可能服务器会返回版本过低。最好的解决办法还是支持验证码登录。 #717

**Comment by zhangzhiyu321** [comment]
那怎么验证码登陆呢?

**Comment by Him188** [comment]
#2570
