### ISSUE TITLE
mirai-core 登录时报错 [duplicate to #1899]

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#1947]
### 问题描述

登录时报错, 但看起来不影响启动

### 复现

用mirai-core登录

### mirai-core 版本

2.11.0-M1

### bot-protocol

ANDROID_PAD

### 系统日志

```text
2022.03.23 19:31:14 [INFO ] mamoe.mirai.Bot - ECDH key is valid.
2022.03.23 19:31:14 [INFO ] mamoe.mirai.Bot - Saved account secrets to local cache for fast login.
2022.03.23 19:25:19 [ERROR] mamoe.mirai.Bot - Exception in decoding packet.
java.lang.IllegalStateException: type mismatch. Expected SIMPLE_LIST or LIST, got TarsHead(tag=1, type=8(Map)) instead
	at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.beginStructure(TarsDecoder.kt:260) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder$MapReaderImpl.beginStructure(TarsDecoder.kt:149) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.PrimitiveArraySerializer.deserialize(CollectionSerializers.kt:179) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.MapLikeSerializer.readAll(CollectionSerializers.kt:96) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.MapLikeSerializer.readAll(CollectionSerializers.kt:84) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:31) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:177) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestDataVersion3$$serializer.deserialize(RequestPacket.kt:33) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestDataVersion3$$serializer.deserialize(RequestPacket.kt:33) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:177) ~[kotlinx-serialization-core-jvm-1.2.2.jar:1.2.2]
	at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load(Tars.kt:42) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:42) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(utils.kt:121) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(utils.kt:1) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket(utils.kt:85) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readUniPacket(utils.kt:1) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.decode(ConfigPushSvc.kt:78) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:369) ~[mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175) [mirai-core-jvm-2.11.0-M1.jar:2.11.0-M1]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.6.0.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.63.Final.jar:4.1.63.Final]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2022.03.23 19:31:14 [INFO ] mamoe.mirai.Bot - Login successful.
```

**Comment by NoMathExpectation** [comment]
这是 #1899 啊

**Comment by Nambers** [comment]
> 这是#1899啊

ok
