### ISSUE TITLE
login日志提示`NettyChannelException`且长时间不结束

### ISSUE THREAD

**Issue by imldy** [mamoe/mirai#1963]
### 问题描述

bot.login长时间不结束，报错`NettyChannelException`也不结束。
是否考虑给login设置抛出异常？毕竟确实登录不上了。

### 复现

清空缓存，并登录。（不确定一定能复现）

### mirai-core 版本

2.10.1

### bot-protocol

ANDROID_WATCH

### 系统日志

```text
日志中可注意到有些日志没有Net或者Bot标志，也没有QQ号，这就是程序输出的原文，但因为我多个QQ都将日志输出到此文件，所以暂时不确定是不是这个QQ号的日志。（但以下出现的“QQ号”三个字代表的是同一个QQ号）
2022-04-02 11:01:04 V/Net QQ号: No server list cached.
2022-04-02 11:01:04 I/Net QQ号: ECDH key is invalid, start to fetch ecdh public key from server.
2022-04-02 11:01:04 I/Net QQ号: Successfully fetched ecdh public key from server.
2022-04-02 11:01:04 V/Net QQ号: Send: wtlogin.login
2022-04-02 11:01:05 V/Net QQ号: Recv: wtlogin.login
2022-04-02 11:05:13 V/: Send: wtlogin.login
2022-04-02 11:05:16 V/: No server list cached.
2022-04-02 11:05:16 I/: ECDH key is invalid, start to fetch ecdh public key from server.
2022-04-02 11:05:16 I/: Successfully fetched ecdh public key from server.
2022-04-02 11:05:16 V/: Send: wtlogin.login
2022-04-02 11:05:16 V/: Recv: wtlogin.login
2022-04-02 11:16:05 V/Net QQ号: Send: wtlogin.login
2022-04-02 11:16:05 W/Net QQ号: NettyChannelException(message=null, cause=java.io.IOException: Connection reset by peer)
NettyChannelException(message=null, cause=java.io.IOException: Connection reset by peer)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$handlePipelineException$1.invoke(NettyNetworkHandler.kt:66)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$handlePipelineException$1.invoke(NettyNetworkHandler.kt:66)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:251)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.handlePipelineException(NettyNetworkHandler.kt:406)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$setupChannelPipeline$1.exceptionCaught(NettyNetworkHandler.kt:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:177)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.IOUtil.read(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	... 8 more

2022-04-02 11:16:05 V/Net QQ号: No server list cached.
2022-04-02 11:16:05 I/Net QQ号: ECDH key is valid.
2022-04-02 11:16:05 V/Net QQ号: Send: wtlogin.login
2022-04-02 11:16:05 V/Net QQ号: Recv: wtlogin.login
2022-04-02 11:20:16 V/: Send: wtlogin.login
2022-04-02 11:20:19 V/: No server list cached.
2022-04-02 11:20:19 I/: ECDH key is valid.
2022-04-02 11:20:19 V/: Send: wtlogin.login
2022-04-02 11:20:20 V/: Recv: wtlogin.login
2022-04-02 11:31:05 V/Net QQ号: Send: wtlogin.login
2022-04-02 11:31:08 V/Net QQ号: No server list cached.
2022-04-02 11:31:08 I/Net QQ号: ECDH key is valid.
2022-04-02 11:31:08 V/Net QQ号: Send: wtlogin.login
2022-04-02 11:31:08 V/Net QQ号: Recv: wtlogin.login
2022-04-02 11:35:20 V/: Send: wtlogin.login
2022-04-02 11:35:23 V/: No server list cached.
2022-04-02 11:35:23 I/: ECDH key is valid.
2022-04-02 11:35:23 V/: Send: wtlogin.login
2022-04-02 11:35:23 V/: Recv: wtlogin.login
2022-04-02 11:46:08 V/Net QQ号: Send: wtlogin.login
2022-04-02 11:46:11 V/Net QQ号: No server list cached.
2022-04-02 11:46:11 I/Net QQ号: ECDH key is valid.
2022-04-02 11:46:11 V/Net QQ号: Send: wtlogin.login
2022-04-02 11:46:11 V/Net QQ号: Recv: wtlogin.login
2022-04-02 11:50:23 V/: Send: wtlogin.login
2022-04-02 11:50:26 V/: No server list cached.
2022-04-02 11:50:26 I/: ECDH key is valid.
2022-04-02 11:50:26 V/: Send: wtlogin.login
2022-04-02 11:50:26 V/: Recv: wtlogin.login
2022-04-02 12:01:11 V/Net QQ号: Send: wtlogin.login
2022-04-02 12:01:14 V/Net QQ号: No server list cached.
2022-04-02 12:01:14 I/Net QQ号: ECDH key is valid.
2022-04-02 12:01:14 V/Net QQ号: Send: wtlogin.login
2022-04-02 12:01:14 V/Net QQ号: Recv: wtlogin.login
2022-04-02 12:05:26 V/: Send: wtlogin.login
2022-04-02 12:05:29 V/: No server list cached.
2022-04-02 12:05:29 I/: ECDH key is valid.
2022-04-02 12:05:29 V/: Send: wtlogin.login
2022-04-02 12:05:29 V/: Recv: wtlogin.login
2022-04-02 12:16:14 V/Net QQ号: Send: wtlogin.login
2022-04-02 12:16:17 V/Net QQ号: No server list cached.
2022-04-02 12:16:17 I/Net QQ号: ECDH key is valid.
2022-04-02 12:16:17 V/Net QQ号: Send: wtlogin.login
2022-04-02 12:16:18 V/Net QQ号: Recv: wtlogin.login
2022-04-02 12:20:29 V/: Send: wtlogin.login
2022-04-02 12:20:32 V/: No server list cached.
2022-04-02 12:20:32 I/: ECDH key is valid.
2022-04-02 12:20:32 V/: Send: wtlogin.login
2022-04-02 12:20:32 V/: Recv: wtlogin.login
2022-04-02 12:31:18 V/Net QQ号: Send: wtlogin.login
2022-04-02 12:31:21 V/Net QQ号: No server list cached.
2022-04-02 12:31:21 I/Net QQ号: ECDH key is valid.
2022-04-02 12:31:21 V/Net QQ号: Send: wtlogin.login
2022-04-02 12:31:21 V/Net QQ号: Recv: wtlogin.login
2022-04-02 12:35:32 V/: Send: wtlogin.login
2022-04-02 12:35:35 V/: No server list cached.
2022-04-02 12:35:35 I/: ECDH key is valid.
2022-04-02 12:35:35 V/: Send: wtlogin.login
2022-04-02 12:35:36 V/: Recv: wtlogin.login
2022-04-02 12:46:21 V/Net QQ号: Send: wtlogin.login
2022-04-02 12:46:24 V/Net QQ号: No server list cached.
2022-04-02 12:46:24 I/Net QQ号: ECDH key is valid.
2022-04-02 12:46:24 V/Net QQ号: Send: wtlogin.login
2022-04-02 12:46:24 V/Net QQ号: Recv: wtlogin.login
2022-04-02 12:50:36 V/: Send: wtlogin.login
2022-04-02 12:50:39 V/: No server list cached.
2022-04-02 12:50:39 I/: ECDH key is valid.
2022-04-02 12:50:39 V/: Send: wtlogin.login
2022-04-02 12:50:39 V/: Recv: wtlogin.login
2022-04-02 13:01:24 V/Net QQ号: Send: wtlogin.login
2022-04-02 13:01:27 V/Net QQ号: No server list cached.
2022-04-02 13:01:27 I/Net QQ号: ECDH key is valid.
2022-04-02 13:01:27 V/Net QQ号: Send: wtlogin.login
2022-04-02 13:01:27 V/Net QQ号: Recv: wtlogin.login
2022-04-02 13:05:39 V/: Send: wtlogin.login
2022-04-02 13:05:42 V/: No server list cached.
2022-04-02 13:05:42 I/: ECDH key is valid.
2022-04-02 13:05:42 V/: Send: wtlogin.login
2022-04-02 13:05:42 V/: Recv: wtlogin.login
2022-04-02 13:16:27 V/Net QQ号: Send: wtlogin.login
2022-04-02 13:16:30 V/Net QQ号: No server list cached.
2022-04-02 13:16:30 I/Net QQ号: ECDH key is valid.
2022-04-02 13:16:30 V/Net QQ号: Send: wtlogin.login
2022-04-02 13:16:30 V/Net QQ号: Recv: wtlogin.login
2022-04-02 13:20:42 V/: Send: wtlogin.login
2022-04-02 13:20:45 V/: No server list cached.
2022-04-02 13:20:45 I/: ECDH key is valid.
2022-04-02 13:20:45 V/: Send: wtlogin.login
2022-04-02 13:20:45 V/: Recv: wtlogin.login
2022-04-02 13:31:30 V/Net QQ号: Send: wtlogin.login
2022-04-02 13:31:34 V/Net QQ号: No server list cached.
2022-04-02 13:31:34 I/Net QQ号: ECDH key is valid.
2022-04-02 13:31:34 V/Net QQ号: Send: wtlogin.login
2022-04-02 13:31:34 V/Net QQ号: Recv: wtlogin.login
2022-04-02 13:35:45 V/: Send: wtlogin.login
2022-04-02 13:35:48 V/: No server list cached.
2022-04-02 13:35:48 I/: ECDH key is valid.
2022-04-02 13:35:48 V/: Send: wtlogin.login
2022-04-02 13:35:48 V/: Recv: wtlogin.login
2022-04-02 13:46:34 V/Net QQ号: Send: wtlogin.login
2022-04-02 13:46:37 V/Net QQ号: No server list cached.
2022-04-02 13:46:37 I/Net QQ号: ECDH key is valid.
2022-04-02 13:46:37 V/Net QQ号: Send: wtlogin.login
2022-04-02 13:46:37 V/Net QQ号: Recv: wtlogin.login
2022-04-02 13:50:48 V/: Send: wtlogin.login
2022-04-02 13:50:51 V/: No server list cached.
2022-04-02 13:50:51 I/: ECDH key is valid.
2022-04-02 13:50:51 V/: Send: wtlogin.login
2022-04-02 13:50:52 V/: Recv: wtlogin.login
2022-04-02 14:01:37 V/Net QQ号: Send: wtlogin.login
2022-04-02 14:01:40 V/Net QQ号: No server list cached.
2022-04-02 14:01:40 I/Net QQ号: ECDH key is valid.
2022-04-02 14:01:40 V/Net QQ号: Send: wtlogin.login
2022-04-02 14:01:40 V/Net QQ号: Recv: wtlogin.login
2022-04-02 14:05:52 V/: Send: wtlogin.login
2022-04-02 14:05:55 V/: No server list cached.
2022-04-02 14:05:55 I/: ECDH key is valid.
2022-04-02 14:05:55 V/: Send: wtlogin.login
2022-04-02 14:05:55 V/: Recv: wtlogin.login
2022-04-02 14:16:40 V/Net QQ号: Send: wtlogin.login
2022-04-02 14:16:43 V/Net QQ号: No server list cached.
2022-04-02 14:16:43 I/Net QQ号: ECDH key is valid.
2022-04-02 14:16:43 V/Net QQ号: Send: wtlogin.login
2022-04-02 14:16:43 V/Net QQ号: Recv: wtlogin.login
2022-04-02 14:20:55 V/: Send: wtlogin.login
2022-04-02 14:20:58 V/: No server list cached.
2022-04-02 14:20:58 I/: ECDH key is valid.
2022-04-02 14:20:58 V/: Send: wtlogin.login
2022-04-02 14:20:58 V/: Recv: wtlogin.login
2022-04-02 14:31:43 V/Net QQ号: Send: wtlogin.login
2022-04-02 14:31:46 V/Net QQ号: No server list cached.
2022-04-02 14:31:46 I/Net QQ号: ECDH key is valid.
2022-04-02 14:31:46 V/Net QQ号: Send: wtlogin.login
2022-04-02 14:31:47 V/Net QQ号: Recv: wtlogin.login
2022-04-02 14:35:58 V/: Send: wtlogin.login
2022-04-02 14:36:01 V/: No server list cached.
2022-04-02 14:36:01 I/: ECDH key is valid.
2022-04-02 14:36:01 V/: Send: wtlogin.login
2022-04-02 14:36:01 V/: Recv: wtlogin.login
2022-04-02 14:46:47 V/Net QQ号: Send: wtlogin.login
2022-04-02 14:46:50 V/Net QQ号: No server list cached.
2022-04-02 14:46:50 I/Net QQ号: ECDH key is valid.
2022-04-02 14:46:50 V/Net QQ号: Send: wtlogin.login
2022-04-02 14:46:50 V/Net QQ号: Recv: wtlogin.login
2022-04-02 14:51:01 V/: Send: wtlogin.login
2022-04-02 14:51:04 V/: No server list cached.
2022-04-02 14:51:04 I/: ECDH key is valid.
2022-04-02 14:51:04 V/: Send: wtlogin.login
2022-04-02 14:51:04 V/: Recv: wtlogin.login
2022-04-02 15:01:50 V/Net QQ号: Send: wtlogin.login
2022-04-02 15:01:53 V/Net QQ号: No server list cached.
2022-04-02 15:01:53 I/Net QQ号: ECDH key is valid.
2022-04-02 15:01:53 V/Net QQ号: Send: wtlogin.login
2022-04-02 15:01:53 V/Net QQ号: Recv: wtlogin.login
2022-04-02 15:06:04 V/: Send: wtlogin.login
2022-04-02 15:06:08 V/: No server list cached.
2022-04-02 15:06:08 I/: ECDH key is valid.
2022-04-02 15:06:08 V/: Send: wtlogin.login
……后边一直这样
```

**Comment by Him188** [comment]
现在的行为是在 login 时遇到网络错误则尝试重连, 遇到其他错误时终止并传递, 相关测试:
net.mamoe.mirai.internal.network.impl.netty.NettyBotNormalLoginTest#test network broken
```kotlin
    @Test
    fun `test network broken`() = runBlockingUnit {
        var retryCounter = 0
        setSsoProcessor {
            eventDispatcher.joinBroadcast()
            if (retryCounter++ >= 15) {
                return@setSsoProcessor
            }
            channel.pipeline().fireExceptionCaught(IOException("TestNetworkBroken"))
            awaitCancellation() // receive exception from "network"
        }
        bot.login()
    }
```
默认的重试次数好像是无上限的, 因此会导致你的这个问题. 

经过考虑, 初次登录确实应该在遇到错误时终止并传递错误.
