### ISSUE TITLE
mirai登陆失败：当前版本过低，请升级到QQ最新版本

### ISSUE THREAD

**Issue by Pika-Lee** [mamoe/mirai#1972]
### 问题描述

今天bot被冻结了一次，秒解冻之后再次登陆，就出现了下图所示报错（100%复现）
![QQ图片20220411120440](https://user-images.githubusercontent.com/23114990/162663486-a7ad1bd6-42d1-47f4-b909-a9a50a10efe9.png)
我尝试在当前版本（2.10.0）删除device.json文件夹内的所有文件，重新登陆后依然出现上图报错。
有趣的是，当我使用相同版本的mirai（2.10.0），登陆另外一个QQ时，却可以正常登陆。
我又尝试用这个问题QQ登陆旧版mirai（2.9.0），也能正常登陆。
使用相同版本的mirai（2.10.0），将协议切换成pad或者watch，也可以正常登录

### 复现

1.登陆问题bot QQ
2.提示“当前版本过低，请升级到QQ最新版本”的登陆失败消息
3.重新登陆后问题依然存在
4.删除device.json所在目录的全部文件后重新登陆，问题依然存在
5.切换协议至pad/watch，使用其它版本（旧版）mirai登陆问题QQ，或使用当前版本登陆其它QQ，则没有问题

### mirai-core 版本

2.10.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-native 2.0.0-beta.1 

### 系统日志

[0m
[0m2022-04-13 21:05:03 V/Net 31368882: Send: wtlogin.login[0m
[91m2022-04-13 21:05:04 W/Net 31368882: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(31368882), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(31368882), code=235, title=温馨提示, message=当前版本过低，请升级到QQ最新版本。, errorInfo= )
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
[0m2022-04-13 21:05:04 V/Net 31368882: Recv: wtlogin.login[0m

**Comment by Him188** [comment]
尝试删除 account.secrets 再试试

**Comment by Pika-Lee** [comment]
> 尝试删除 account.secrets 再试试

试了一下还是不行，问题依旧（换其它QQ用phone协议就没问题）

**Comment by Mantou1233** [comment]
這种情况就是你号suspend了

**Comment by Pika-Lee** [comment]
> 這种情况就是你号suspend了

是的，最近连加好友功能都被限制了，主动添加别人好友都不行，应该是这个号的问题

**Comment by hc5-github** [comment]
把bots文件夹连根拔起就行了
