### ISSUE TITLE
console下载依赖时试图下载并不存在jar

### ISSUE THREAD

**Issue by hundun000** [mamoe/mirai#1975]
### 问题描述

[浏览Maven Central Repository可看到，`com.fasterxml.jackson:jackson-bom`中并不存在jar文件](https://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-bom/2.12.4/)（应该是设计如此），阿里云maven也是如此（阿里云检索结果展示无法排序，看得不太方便）。

当2.11.0-M2打包出的插件依赖`com.fasterxml.jackson:jackson-bom`，console启动下载所有依赖时，会试图下载其jar，导致报错并进程结束。

> Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.fasterxml.jackson:jackson-bom:jar:2.12.4 in  (https://maven.aliyun.com/repository/public)

### 复现

2.11.0-M2打包出的插件依赖`com.fasterxml.jackson:jackson-bom`，放入console运行

```
dependencies {
        ……
        implementation 'com.fasterxml.jackson:jackson-bom:2.12.4'
}
```

### mirai-core 版本

2.11.0-M2

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2022-04-10 21:53:23 I/plugin: Cannot load plugin hundun.fleet.music v0.1.0
2022-04-10 21:53:23 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while loading hundun.fleet.music v0.1.0
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:248)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:96)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:152)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:175)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:444)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:159)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:158)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:103)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:106)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:178)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:147)
        at org.itxtech.mcl.Loader.start(Loader.java:178)
        at org.itxtech.mcl.Loader.main(Loader.java:70)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact com.fasterxml.jackson:jackson-bom:jar:2.12.4 in  (https://maven.aliyun.com/repository/public)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:374)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginDependencyDownloader.resolveDependencies(JvmPluginDependencyDownload.kt:216)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.linkLibraries(JvmPluginClassLoader.kt:181)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.linkPluginPrivateLibraries$mirai_console(JvmPluginClassLoader.kt:176)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:240)
        ... 42 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact com.fasterxml.jackson:jackson-bom:jar:2.12.4 in  (https://maven.aliyun.com/repository/public)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:431)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:235)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:357)
        ... 46 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact com.fasterxml.jackson:jackson-bom:jar:2.12.4 in  (https://maven.aliyun.com/repository/public)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:408)
        ... 48 more
```

**Comment by hundun000** [comment]
换到RC后尝试，直接依赖 'com.fasterxml.jackson:jackson-bom:2.12.4'问题已修复，但是直接依赖"com.fasterxml.jackson.core:jackson-annotations:2.12.4"，其间接依赖jackson-bom，则依然报错。

```
+--- com.fasterxml.jackson.core:jackson-annotations:2.12.4
 |    \--- com.fasterxml.jackson:jackson-bom:2.12.4
|         +--- com.fasterxml.jackson.core:jackson-annotations:2.12.4 (c)
 |         +--- com.fasterxml.jackson.core:jackson-core:2.12.4 (c)
|         +--- com.fasterxml.jackson.core:jackson-databind:2.12.4 (c)
|         \--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.4 (c)
```

### 复现
dependencies {
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.12.4")
}

或mirai-console/tools/gradle-plugin/src/integTest/kotlin/TestBuildPlugin.kt里@Test fun `can build with bom dependencies`()修改为implementation platform("com.fasterxml.jackson.core:jackson-annotations:2.12.4")后运行测试。

**Comment by Him188** [comment]
换 2.12.0-dev-78d0cdd1 试试（参考文档-配置项目-使用测试版）
