### ISSUE TITLE
NoSuchMethodError when Mirai plugin with Ktor client 2.0.0 is executed 

### ISSUE THREAD

**Issue by Stexxe** [mamoe/mirai#1981]
### 问题描述

The following error occurs when [Ktor client](https://ktor.io/docs/create-client.html) of version 2.0.0 with any installed [plugin](https://ktor.io/docs/http-client-plugins.html) is used. The Ktor 2.0.0 depends on Kotlin 1.6.20 so most likely there is a problem in a module that reflectively executes a command.

```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1$invokeSuspend$$inlined$runBIO$1.invoke(CoroutineUtils.kt:194)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.NoSuchMethodError: 'void io.ktor.client.HttpClientConfig.install$default(io.ktor.client.HttpClientConfig, io.ktor.client.plugins.HttpClientPlugin, kotlin.jvm.functions.Function1, int, java.lang.Object)'
	at NoMathExpectation.ktorInstallTest.InstallTest$onEnable$2$handle$1$1.invoke(InstallTest.kt:27)
	at NoMathExpectation.ktorInstallTest.InstallTest$onEnable$2$handle$1$1.invoke(InstallTest.kt:26)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41)
	at NoMathExpectation.ktorInstallTest.InstallTest$onEnable$2.handle(InstallTest.kt:26)
	... 21 more
```

[Here](https://youtrack.jetbrains.com/issue/KTOR-4170) is the related issue in the Ktor's bug tracker.

### 复现

To reproduce build the Mirai plugin from [ktorInstallTest-main (1).zip](https://github.com/mamoe/mirai/files/8511530/ktorInstallTest-main.1.zip) and run it in the Mirai console.

### mirai-core 版本

2.10.1

### bot-protocol

ANDROID_PHONE

**Comment by Him188** [comment]
Mirai Console uses Kotlin 1.6.0 and for some reasons forces all plugins to use the same version of Kotlin, causing this problem. We plan to update to 1.6.20 by Mirai 2.11.0.

**Comment by NoMathExpectation** [comment]
This bug was not fixed. @Him188 

```
> test
2022-05-20 18:12:06 E/console: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1$invokeSuspend$$inlined$runBIO$1.invoke(CoroutineUtils.kt:194)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.NoSuchMethodError: 'void io.ktor.client.HttpClientConfig.install$default(io.ktor.client.HttpClientConfig, io.ktor.client.plugins.HttpClientPlugin, kotlin.jvm.functions.Function1, int, java.lang.Object)'
        at installTest-1.0-SNAPSHOT.mirai.jar//NoMathExpectation.ktorInstallTest.InstallTest$onEnable$2$handle$1$1.invoke(InstallTest.kt:27)
        at installTest-1.0-SNAPSHOT.mirai.jar//NoMathExpectation.ktorInstallTest.InstallTest$onEnable$2$handle$1$1.invoke(InstallTest.kt:26)
        at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41)
        at installTest-1.0-SNAPSHOT.mirai.jar//NoMathExpectation.ktorInstallTest.InstallTest$onEnable$2.handle(InstallTest.kt:26)
        ... 21 more
```

**Comment by NoMathExpectation** [comment]
```
> status
Running MiraiConsole v2.11.0, built on 2022-05-19 22:08:40.
Frontend Terminal: version 2.11.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: Chat Command v0.5.0, NoMathExpectation.ktorInstallTest v1.0-SNAPSHOT, MCL Addon v1.2.2, messageSender v1.0, net.mamoe.mirai-api-http v1.10.0, mirai-device-generator v1.0.1, NMEBoot v1.2.3-20220512001

Object Pending Finalization Count: 0
                 committed |  init   |  used   |   max
    Heap Memory:  105.2MB  | 16.0MB  | 81.03MB | 247.5MB
Non-Heap Memory:  41.08MB  | 160.0KB | 40.31MB |   -1
```

**Comment by Karlatemp** [comment]
@NoMathExpectation Open a new issue instead of replying here
