### ISSUE TITLE
MCL 网络连接错误 丢失网络

### ISSUE THREAD

**Issue by Amekoi67** [mamoe/mirai#1989]
### 问题描述

【使用MCL启动群聊机器人，正常启动后1分钟内就会自动丢失网络连接，内容为：Connection lost, reconnecting... (java.lang.IllegalStateException: Timeout waiting for ConfigPush.)】
【之后就会出现一张段红色错误】请教各位大佬该如何解决这个？

### 复现

重新启动软件1分钟内就会出现，试了其他的版本也都是这个情况。不知道如何解决

### mirai-core 版本

2.0.0

### bot-protocol

ANDROID_WATCH

### 其他组件版本

链接错误

### 系统日志

```text
2022-04-25 17:28:16 E/MAH Access: java.util.concurrent.CancellationException: java.lang.IllegalStateException: Timeout waiting for ConfigPush.
java.util.concurrent.CancellationException: java.lang.IllegalStateException: Timeout waiting for ConfigPush.
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect$suspendImpl(SelectorNetworkHandler.kt:108)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.sendAndExpect(SelectorNetworkHandler.kt)
        at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect(NetworkHandler.kt:173)
        at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect$default(NetworkHandler.kt:169)
        at net.mamoe.mirai.internal.contact.SendMessageHandler.sendMessagePacket(SendMessageHandler.kt:138)
        at net.mamoe.mirai.internal.contact.SendMessageHandlerKt.sendMessageImpl(SendMessageHandler.kt:365)
        at net.mamoe.mirai.internal.contact.SendMessageHandlerKt.sendMessage(SendMessageHandler.kt:336)
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:255)
        at net.mamoe.mirai.internal.contact.FriendImpl.sendMessage(FriendImpl.kt:84)
        at net.mamoe.mirai.api.http.adapter.internal.action.MessageKt.sendMessage(message.kt:67)
        at net.mamoe.mirai.api.http.adapter.internal.action.MessageKt.onSendFriendMessage(message.kt:88)
        at net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$$special$$inlined$respondDTOStrategy$2.invokeSuspend(dsl.kt:205)
        at net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$$special$$inlined$respondDTOStrategy$2.invoke(dsl.kt)
        at net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$$special$$inlined$httpAuthedPost$1$1.invokeSuspend(dsl.kt:214)
        at net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$$special$$inlined$httpAuthedPost$1$1.invoke(dsl.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
        at io.ktor.routing.Routing.executeResult(Routing.kt:155)
        at io.ktor.routing.Routing.interceptor(Routing.kt:39)
        at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
        at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invokeSuspend(Authorization.kt:41)
        at net.mamoe.mirai.api.http.adapter.http.feature.auth.Authorization$install$1.invoke(Authorization.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler.intercept(HttpRouterAccessHandler.kt:36)
        at net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler.access$intercept(HttpRouterAccessHandler.kt:25)
        at net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invokeSuspend(HttpRouterAccessHandler.kt:91)
        at net.mamoe.mirai.api.http.adapter.http.feature.handler.HttpRouterAccessHandler$Feature$install$1.invoke(HttpRouterAccessHandler.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
        at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:248)
        at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
        at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
        at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:78)
        at io.ktor.server.cio.CIOApplicationEngine$handleRequest$2.invokeSuspend(CIOApplicationEngine.kt:192)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.IllegalStateException: Timeout waiting for ConfigPush.
        at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl.syncConfigPush(ConfigPushProcessor.kt:36)
        at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl$syncConfigPush$1.invokeSuspend(ConfigPushProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        ... 4 more
```

### 网络日志

```text
链接错误
```

### 补充信息

链接错误

**Comment by zhaodice** [comment]
我这边也有大量用户出现了这个问题，首先是登录出现 #1899 ,然后虽然可以正常收消息但发消息出现
java.lang.IllegalStateException: Timeout waiting for ConfigPush.

**Comment by Amekoi67** [comment]
> 我这边也有大量用户出现了这个问题，首先是登录出现 #1899 ,然后虽然可以正常收消息但发消息出现 java.lang.IllegalStateException: Timeout waiting for ConfigPush.
.
.
.
我看下有个帖子说是bot的问题，我把bot删了后重启虽然会好几秒钟 但是几秒钟后还是丢失链接了，首先设置和版本我试了好多 都是这个情况，http代理我也取消了，网络设置重置了，还是会出现 有点头疼了

**Comment by Him188** [comment]
这应该是协议有更新，参考 https://github.com/mamoe/mirai/issues/1899#issuecomment-1086610929 并提供日志。
我无法复现这个问题，必须拿到日志才能解决。

**Comment by zhaodice** [comment]
> 这应该是协议有更新，参考 [#1899 (comment)](https://github.com/mamoe/mirai/issues/1899#issuecomment-1086610929) 并提供日志。 我无法复现这个问题，必须拿到日志才能解决。

日志来咯 #1991

**Comment by Him188** [comment]
#1991

**Comment by zhaodice** [comment]
我又找人试了一下，虽然登录没有错误了，但还是有问题
