### ISSUE TITLE
在解析net.mamoe.mirai.internal.network.protocol.data.jce.RequestDataVersion3时遇到了意料之中的问题

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#1991]
### 问题描述

```
[19:50:16] [ERROR] Exception in decoding packet. 
[19:50:16] [ERROR] ContextualBugReportException(message=在 解析 net.mamoe.mirai.internal.network.protocol.data.jce.RequestPacket 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose 调试信息: 
Data: 
00 00 03 E4 10 02 2C 3C 4C 56 23 51 51 53 65 72 76 69 63 65 2E 43 6F 6E 66 69 67 50 75 73 68 53 76 63 2E 4D 61 69 6E 53 65 72 76 61 6E 74 66 07 50 75 73 68 52 65 71 7D 00 01 03 A3 08 00 01 06 07 50 75 73 68 52 65 71 18 00 01 06 12 43 6F 6E 66 69 67 50 75 73 68 2E 50 75 73 68 52 65 71 1D 00 01 03 7B 0A 10 01 2D 00 01 03 6D 19 00 07 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 34 37 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 32 34 34 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 39 2E 32 34 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 33 2E 34 37 2E 31 30 32 2E 31 34 35 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 33 2E 34 37 2E 31 30 32 2E 31 36 35 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0D 34 32 2E 38 31 2E 31 37 36 2E 32 31 31 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 39 00 07 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 34 37 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 32 34 34 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 39 2E 32 34 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 33 2E 34 37 2E 31 30 32 2E 31 34 35 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 33 2E 34 37 2E 31 30 32 2E 31 36 35 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0D 34 32 2E 38 31 2E 31 37 36 2E 32 31 31 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 4C 5C 6C 70 01 89 00 04 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 99 00 04 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B A9 0C B9 0C C9 0C D9 0C EC FC 0F F6 10 00 FC 11 32 00 29 18 59 0B 8C 98 0C A8 0C
Trace:

beginStructure: net.mamoe.mirai.internal.network.protocol.data.jce.RequestPacket, CLASS
decodeElementIndex: TarsHead(tag=0, type=0(Byte))
skipping Byte
next! TarsHead(tag=0, type=3(Long))
skipping Long
next! TarsHead(tag=5, type=1(Short))
name=servantName
, cause=java.lang.IllegalStateException: type mismatch: TarsHead(tag=5, type=1(Short)), expecting 6 or 7 (for string))
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(Unknown Source:50)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(Unknown Source:11)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readJceStruct(Unknown Source:580)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readJceStruct(Unknown Source:0)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readJceStruct$default(Unknown Source:9)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readJceStruct$default(Unknown Source:0)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(Unknown Source:19)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(Unknown Source:0)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket(Unknown Source:15)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readUniPacket(Unknown Source:0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.decode(Unknown Source:8)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(Unknown Source:157)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(Unknown Source:73)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:13)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:88)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(Unknown Source:0)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Unknown Source:28)
	at io.netty.channel.nio.NioEventLoop.run(Unknown Source:155)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(Unknown Source:41)
	at io.netty.util.internal.ThreadExecutorMap$2.run(Unknown Source:8)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: type mismatch: TarsHead(tag=5, type=1(Short)), expecting 6 or 7 (for string)
	at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.readTarsStringValue(Unknown Source:105)
	at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.decodeTaggedString(Unknown Source:23)
	at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.decodeTaggedString(Unknown Source:2)
	at kotlinx.serialization.internal.TaggedDecoder.decodeStringElement(Unknown Source:9)
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestPacket$$serializer.deserialize(Unknown Source:192)
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestPacket$$serializer.deserialize(Unknown Source:0)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Unknown Source:10)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Unknown Source:0)
	at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load(Unknown Source:34)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readJceStruct(Unknown Source:423)
	... 19 more
	Suppressed: java.lang.IllegalStateException: type mismatch: TarsHead(tag=5, type=1(Short)), expecting 6 or 7 (for string)
		at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.readTarsStringValue(Unknown Source:105)
		at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.decodeTaggedString(Unknown Source:23)
		at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.decodeTaggedString(Unknown Source:2)
		at kotlinx.serialization.internal.TaggedDecoder.decodeStringElement(Unknown Source:9)
		at net.mamoe.mirai.internal.network.protocol.data.jce.RequestPacket$$serializer.deserialize(Unknown Source:192)
		at net.mamoe.mirai.internal.network.protocol.data.jce.RequestPacket$$serializer.deserialize(Unknown Source:0)
		at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Unknown Source:10)
		at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Unknown Source:0)
		at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load(Unknown Source:34)
		at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load$default(Unknown Source:5)
		at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readJceStruct(Unknown Source:339)
		... 19 more
```
关联问题
#1899 

### 复现

不知道怎么复现的，据用户说直接登录过程就出现了

### mirai-core 版本

2.11.0-dev-ad5132e1

### bot-protocol

ANDROID_PHONE

**Comment by zhaodice** [comment]
因为错误不一样，这个错误日志是
`type mismatch: TarsHead(tag=5, type=1(Short)), expecting 6 or 7 (for string)`
而上次是
`type mismatch. Expected SIMPLE_LIST or LIST, got TarsHead(tag=1, type=8(Map)) instead`
故本次单独开了issue

**Comment by Him188** [comment]
为什么 stacktrace 是 Unknown Source:...

**Comment by zhaodice** [comment]
> 为什么 stacktrace 是 Unknown Source:...

可能是安卓系统的proguard优化在搞怪吧，我这边很奇怪，不敢关proguard，关了desugering就缺class闪退，很怪

**Comment by Him188** [comment]
问题是这东西多了个长度... 00 00 03 E4 是后文长度...

**Comment by Him188** [comment]
与 #1899 是一样的问题
