### ISSUE TITLE
[BUG] 启动时发生异常

### ISSUE THREAD

**Issue by Alceatraz** [mamoe/mirai#2007]
### 问题描述

启动时报错，但是不影响接受消息，具体影响未知

```text
2022-05-03 21:09:29 V/Net 3477852529: Recv: friendlist.getFriendGroupList
2022-05-03 21:09:29 E/Net 3477852529: ExceptionInPacketHandlerException(packetHandler=CallPacketFactoryPacketHandler, incomingPacket=IncomingPacket(cmd=MessageSvc.PbGetMsg, seq=20434, SUCCESS, r=MessageSvcPbGetMsg.Response(flag=CONTINUE)), cause=java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response are in unnamed module of loader 'app'))
ExceptionInPacketHandlerException(packetHandler=CallPacketFactoryPacketHandler, incomingPacket=IncomingPacket(cmd=MessageSvc.PbGetMsg, seq=20434, SUCCESS, r=MessageSvcPbGetMsg.Response(flag=CONTINUE)), cause=java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response are in unnamed module of loader 'app'))
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:45)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:84)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:82)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:193)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response are in unnamed module of loader 'app')
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg.handle(MessageSvc.PbGetMsg.kt:189)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg.handle(MessageSvc.PbGetMsg.kt:42)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:110)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	... 21 more

2022-05-03 21:09:29 I/Net 3477852529: Syncing friend message history: Success.
2022-05-03 21:09:29 E/Net 3477852529: Exception in coroutine 'unnamed'
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[Dispatchers.Default, Continuation at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$sendAndExpect$3$1$1.invokeSuspend(NetworkHandlerSupport.kt:102)@6a68cc14]){Completed}@2e3815d3. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: Job "coroutine#29":StandaloneCoroutine{Completed}@52eca72d is already complete or completing, but is being completed with kotlin.Unit
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:831)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 4 more

2022-05-03 21:09:29 V/Net 3477852529: Recv: friendlist.GetTroopListReqV2
```

- Zulu OpenJDK 17
- Mirai 2.11-RC 

### 复现

```java
        BotConfiguration configuration = new BotConfiguration();
        File cacheFolder = new File("XXXXXX\\cache");
        configuration.setCacheDir(cacheFolder);
        configuration.enableContactCache();
        configuration.setProtocol(BotConfiguration.MiraiProtocol.ANDROID_WATCH);
        configuration.fileBasedDeviceInfo("XXXXX\\device.json");
        Bot bot = BotFactory.INSTANCE.newBot(XXXXX, "XXXX", configuration);
        bot.login();
        bot.join();
```

### mirai-core 版本

2.11-RC

### bot-protocol

ANDROID_WATCH

**Comment by Alceatraz** [comment]
PAD协议也会爆一样的错误，看来和协议类型无关。

**Comment by Him188** [comment]
很有意思的错误

**Comment by zhaodice** [comment]
emmmmm,这不就是我发的问题#2006 吗

**Comment by zhaodice** [comment]
他的`ExceptionInPacketHandlerException(packetHandler=CallPacketFactoryPacketHandler, incomingPacket=IncomingPacket(cmd=MessageSvc.PbGetMsg, seq=20434, SUCCESS, r=MessageSvcPbGetMsg.Response(flag=CONTINUE)), cause=java.lang.ClassCastException: class`应该是一个新的错误，也可以研究一下
