### ISSUE TITLE
() -> kotlin.String不断打印

### ISSUE THREAD

**Issue by FlyRenxing** [mamoe/mirai#2012]
### 问题描述

更新了最新的2.10.2core版本，出现了以下错误，请查看系统日志。
() -> kotlin.String  #这一行在登陆机器人时不断循环，必现
其他错误，偶现我也不知道咋回事..

### 复现

目前正使用JDK17+Springboot3.0.0-M2

### mirai-core 版本

2.10.2

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
() -> kotlin.String  #这一行在登陆机器人时不断循环
[31m2022-05-05 20:14:22 E/Net 2816669521: ExceptionInPacketHandlerException(packetHandler=CallPacketFactoryPacketHandler, incomingPacket=IncomingPacket(cmd=ConfigPushSvc.PushReq, seq=-513796596, SUCCESS, r=ConfigPushSvc.PushReq.PushReqResponse.ServerListPush), cause=ContextualBugReportException(message=在 ConfigPush.ReqPush type=1 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    调试信息: 19 00 08 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 32 30 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 31 39 32 2E 34 35 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 39 2E 32 34 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0B 34 39 2E 37 2E 32 35 33 2E 38 38 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 32 2E 31 39 31 2E 39 37 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 32 30 2E 32 33 32 2E 36 39 2E 32 32 36 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 30 38 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 39 00 08 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 32 30 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 31 39 32 2E 34 35 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 39 2E 32 34 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0B 34 39 2E 37 2E 32 35 33 2E 38 38 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 32 2E 31 39 31 2E 39 37 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 32 30 2E 32 33 32 2E 36 39 2E 32 32 36 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 30 38 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 4C 5C 6C 70 01 89 00 05 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B 99 00 05 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B A9 0C B9 0C C9 0C D9 0C E0 01 FC 0F F6 10 14 51 44 49 41 4F 5F 50 4F 4C 49 43 59 5F 44 45 46 41 55 4C 54 F0 11 01, cause=null))
ExceptionInPacketHandlerException(packetHandler=CallPacketFactoryPacketHandler, incomingPacket=IncomingPacket(cmd=ConfigPushSvc.PushReq, seq=-513796596, SUCCESS, r=ConfigPushSvc.PushReq.PushReqResponse.ServerListPush), cause=ContextualBugReportException(message=在 ConfigPush.ReqPush type=1 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    调试信息: 19 00 08 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 32 30 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 31 39 32 2E 34 35 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 39 2E 32 34 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0B 34 39 2E 37 2E 32 35 33 2E 38 38 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 32 2E 31 39 31 2E 39 37 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 32 30 2E 32 33 32 2E 36 39 2E 32 32 36 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 30 38 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 39 00 08 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 32 30 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 31 39 32 2E 34 35 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 39 2E 32 34 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0B 34 39 2E 37 2E 32 35 33 2E 38 38 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 32 2E 31 39 31 2E 39 37 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 32 30 2E 32 33 32 2E 36 39 2E 32 32 36 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 30 38 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 4C 5C 6C 70 01 89 00 05 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B 99 00 05 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B A9 0C B9 0C C9 0C D9 0C E0 01 FC 0F F6 10 14 51 44 49 41 4F 5F 50 4F 4C 49 43 59 5F 44 45 46 41 55 4C 54 F0 11 01, cause=null))
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:45)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:84)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:82)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:178)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: ContextualBugReportException(message=在 ConfigPush.ReqPush type=1 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    调试信息: 19 00 08 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 32 30 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 31 39 32 2E 34 35 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 39 2E 32 34 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0B 34 39 2E 37 2E 32 35 33 2E 38 38 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 32 2E 31 39 31 2E 39 37 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 32 30 2E 32 33 32 2E 36 39 2E 32 32 36 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 30 38 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 39 00 08 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 32 30 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 31 39 32 2E 34 35 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 39 2E 32 34 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0B 34 39 2E 37 2E 32 35 33 2E 38 38 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 32 2E 31 39 31 2E 39 37 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 32 30 2E 32 33 32 2E 36 39 2E 32 32 36 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 30 38 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 4C 5C 6C 70 01 89 00 05 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B 99 00 05 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B A9 0C B9 0C C9 0C D9 0C E0 01 FC 0F F6 10 14 51 44 49 41 4F 5F 50 4F 4C 49 43 59 5F 44 45 46 41 55 4C 54 F0 11 01, cause=null)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle$handleServerListPush(ConfigPushSvc.kt:138)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle(ConfigPushSvc.kt:168)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle(ConfigPushSvc.kt:40)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	... 21 more
```

**Comment by Samarium150** [comment]
#1955

**Comment by Him188** [comment]
可能是 pick 的时候忘了 pick fix
