### ISSUE TITLE
Transformers528 0x27L相关事件可能与业务违规相关

### ISSUE THREAD

**Issue by CauchyDOOM** [mamoe/mirai#2027]
近期多次业务违规类封禁都伴随着Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile出现，并非个例，已经在多个bot上发生类似的事件。

以下是部分例子：
```
[0m2022-05-11 20:56:16 V/: Recv: MessageSvc.PbSendMsg[0m
[96m2022-05-11 20:56:18 D/: Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile@7c7b20[0m
[0m2022-05-11 20:56:21 V/: Send: StatSvc.RspMSFForceOffline(StatSvc.RspMSFForceOffline)[0m
[0m2022-05-11 20:56:21 V/: Recv: StatSvc.ReqMSFOffline[0m
[91m2022-05-11 20:56:21 W/: MsfOfflineToken(uin=2914377162, seq=2427137409, const=0)
MsfOfflineToken(uin=2914377162, seq=2427137409, const=0)
	at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:295)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:369)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: java.util.concurrent.CancellationException: NetworkHandler closed
		at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
		at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:602)
		at kotlinx.coroutines.JobKt.cancel(Unknown Source)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.close(NetworkHandlerSupport.kt:55)
		at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:191)
		at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:79)
		at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:322)
		at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:277)
		at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
		at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:84)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
		at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
		at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
		at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
		at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:82)
		at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:178)
		... 9 more
	Caused by: [CIRCULAR REFERENCE: MsfOfflineToken(uin=2914377162, seq=2427137409, const=0)]
[0m
[0m2022-05-11 20:56:21 V/: Loading server list from cache.[0m
[92m2022-05-11 20:56:21 I/: Server list: 183.2.144.33:443, 49.7.253.184:443, 180.109.192.45:8080, 42.81.183.253:80, 183.47.102.254:8080, msfwifi.3g.qq.com:8080, 49.7.253.116:443, 114.222.112.229:80, 180.102.111.213:8080, 183.47.102.165:14000.[0m
[92m2022-05-11 20:56:21 I/: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2022-05-11 20:56:21 I/: Successfully fetched ecdh public key from server.[0m
[0m2022-05-11 20:56:21 V/: Send: wtlogin.exchange_emp[0m
[0m2022-05-11 20:56:21 V/: Recv: wtlogin.exchange_emp[0m
[0m2022-05-11 20:56:21 V/: Send: wtlogin.login[0m
[0m2022-05-11 20:56:21 V/: Recv: wtlogin.login[0m
[91m2022-05-11 20:56:21 W/: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2914377162), code=40, title=安全提醒, message=该帐号因涉嫌进行业务违规操作被暂时冻结，请点击下方按钮了解详情及处理。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2914377162), code=40, title=安全提醒, message=该帐号因涉嫌进行业务违规操作被暂时冻结，请点击下方按钮了解详情及处理。, errorInfo=)
```

除此之外多次在不同bot上试验后发现：多次调用queryProfile接口会导致封禁，在插件层屏蔽queryProfile接口封禁概率有显著的降低。（不确定queryProfile是否与bot.getfriend乃至上述FriendNickChangedEvent相关。）

**Comment by Him188** [comment]
getFriend与queryProfile无关，与event待确定

**Comment by zhaodice** [comment]
频繁queryProfile可能被tx当爬虫处理了

**Comment by CauchyDOOM** [comment]
目前是同步登录pc端与mirai-apad端解决了0x27L事件问题。(持续4日正常)
<前提是插件端屏蔽queryprofile尽可能减少调用>
queryprofile大规模使用仍存在问题

**Comment by CauchyDOOM** [comment]
补充：
```
[96m2022-05-18 15:07:52 D/Net 2914377162: Unknown MsgInfo kind 736, data=0C 19 00 05 0A 01 5A 3F 0B 0A 01 5A 40 0B 0A 02 00 00 9C 40 0B 0A 02 00 00 9C 7A 0B 0A 02 00 00 9C 7B 0B[0m
[96m2022-05-18 15:07:52 D/Net 2914377162: Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile@127f4f2[0m
[0m2022-05-18 15:07:54 V/Net 2914377162: Send: StatSvc.RspMSFForceOffline(StatSvc.RspMSFForceOffline)[0m
[0m2022-05-18 15:07:54 V/Net 2914377162: Recv: StatSvc.ReqMSFOffline[0m
[91m2022-05-18 15:07:54 W/Net 2914377162: MsfOfflineToken(uin=2914377162, seq=2424241777, const=0)
```
大部分情况是业务封禁，可直接解冻，需要人脸识别和身份证验证

**Comment by CauchyDOOM** [comment]
与上次情况类似
已排查插件问题（即停用所有交互插件后仍然再上报0x27L）Debug模式中控制台发现无任何明显关联消息。
并且，另外机器人好友人数群聊数与0x27L上报次数成正相关，
```
[96m2022-05-24 15:36:45 D/Net 2500980912: Unknown MsgInfo kind 736, data=0C 19 00 05 0A 01 5A 3F 0B 0A 01 5A 40 0B 0A 02 00 00 9C 40 0B 0A 02 00 00 9C 7A 0B 0A 02 00 00 9C 7B 0B[0m
[96m2022-05-24 15:36:45 D/Net 2500980912: Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile@3bde6d[0m
[0m2022-05-24 15:36:48 V/Net 2500980912: Recv: StatSvc.SvcReqMSFLoginNotify[0m
[31m2022-05-24 15:36:53 E/Net 2500980912: Exception in coroutine 'unnamed'
ExceptionInPacketCodecException(cause=java.lang.IllegalStateException: returnCode = -10004)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.handleExceptionInDecoding(NettyNetworkHandler.kt:61)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:83)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$ByteBufToIncomingPacketDecoder.channelRead0(NettyNetworkHandler.kt:73)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
```

**Comment by Him188** [comment]
应该只是巧合，mirai 目前也正常处理了被封禁时的通知

**Comment by CauchyDOOM** [comment]
> 应该只是巧合，mirai 目前也正常处理了被封禁时的通知

有办法主动屏蔽这个功能吗，主要是缓存群头像，但基本上很难用到Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile，再次被封
