### ISSUE TITLE
在解析....network.protocol.data.jce.OnlinePushPack.SvcReqPushMsg 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by Deficuet** [mamoe/mirai#2029]
### 问题描述

在发生#2028 后未重启过
连续打印两次该异常，略读一遍似乎没什么差别。第二段见补充信息折叠

### 复现

略

### mirai-core 版本

2.10.3

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2022-05-11 21:33:54 E/Net 1526****: Exception in decoding packet.
ContextualBugReportException(message=在 解析 net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack.SvcReqPushMsg 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    调试信息:
Data:
02 5B 02 BB 5D 12 62 7C 80 22 29 00 01 0A 02 5B 02 BB 5D 1C 21 02 10 31 49 45 46 00 52 62 7C 80 22 6D 00 01 00 D5 00 26 1A 0C 1C 2C 3C 4C 5D 00 0C 6D 00 0C 7D 00 0C 8D 00 0C 9C AC BC CC DD 00 0C EC FC 0F 0B 2A 0C 1C 2C 3C 4C 5C 6C 0B 3A 0C 1C 2C 3C 4C 5C 6C 7C 8D 00 0C 9D 00 0C AC BD 00 0C CD 00 0C DC ED 00 0C FC 0F FC 10 0B 4A 0C 1C 2C 3C 4C 5C 6C 7C 8C 96 00 0B 5A 0C 1C 2C 3C 4C 5C 6C 7C 8C 9D 00 0C 0B 6A 0C 1A 0C 1C 26 00 0B 2A 0C 0B 3A 0C 16 00 0B 4A 09 0C 0B 5A 09 0C 0B 0B 7A 0C 1C 2C 36 00 0B 8A 0C 1C 2C 36 00 0B 9A 09 0C 0B AD 00 00 44 08 01 12 40 0A 06 08 F4 EF BB 8F 04 10 C1 E9 FD 97 03 18 01 22 2C 10 01 1A 1A 18 B0 8B AB A8 08 20 C1 E9 FD 97 03 28 08 30 02 A2 01 04 08 DC D5 03 A8 01 02 20 00 28 00 32 08 18 01 20 B6 80 F2 93 06 28 00 7C 8D 00 00 13 08 90 04 10 90 84 88 83 80 80 80 80 02 18 00 20 DF 86 03 9D 00 0C A3 02 00 00 00 00 62 02 10 B0 01 C9 0C DA 06 00 16 00 26 00 36 00 0B EC FD 0F 00 0C F6 10 00 F6 11 00 F9 12 0C 0B 32 BE E0 87 0B 4D 00 0C 59 0C 68 0C 70 01 8D 00 0C 9A 0C 1C 2C 3C 4C 0B AA 0C 1C 2C 3C 4C 0B BA 06 00 16 00 26 00 0B C0 01
Trace:

beginStructure: net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack.SvcReqPushMsg, CLASS
    decodeElementIndex: TarsHead(tag=0, type=2(Int))
    name=uin
    decodeElementIndex: TarsHead(tag=1, type=2(Int))
    name=uMsgTime
    decodeElementIndex: TarsHead(tag=2, type=9(List))
    name=vMsgInfos

    beginStructure: kotlin.collections.ArrayList, LIST

        beginStructure: net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo, CLASS
            decodeElementIndex: TarsHead(tag=0, type=2(Int))
            name=lFromUin
            decodeElementIndex: TarsHead(tag=1, type=12(Zero))
            name=uMsgTime
            decodeElementIndex: TarsHead(tag=2, type=1(Short))
            name=shMsgType
            decodeElementIndex: TarsHead(tag=3, type=1(Short))
            name=shMsgSeq
            decodeElementIndex: TarsHead(tag=4, type=6(String1))
            name=strMsg
            decodeElementIndex: TarsHead(tag=5, type=2(Int))
            name=uRealMsgTime
            decodeElementIndex: TarsHead(tag=6, type=13(SimpleList))
            name=vMsg

            beginStructure: kotlin.ByteArray, LIST
                SimpleByteArrayReader.decodeCollectionSize: 213
            endStructure: kotlin.ByteArray, TarsTagCommon(id=6), TarsHead(tag=0, type=1(Short))
            endStructure: prepareNextHead() called
            decodeElementIndex: TarsHead(tag=7, type=12(Zero))
            name=uAppShareID
            decodeElementIndex: TarsHead(tag=8, type=13(SimpleList))
            name=vMsgCookies

            beginStructure: kotlin.ByteArray, LIST
                SimpleByteArrayReader.decodeCollectionSize: 19
            endStructure: kotlin.ByteArray, TarsTagCommon(id=8), TarsHead(tag=0, type=0(Byte))
            endStructure: prepareNextHead() called
            decodeElementIndex: TarsHead(tag=9, type=13(SimpleList))
            name=vAppShareCookie

            beginStructure: kotlin.ByteArray, LIST
                SimpleByteArrayReader.decodeCollectionSize: 0
            endStructure: kotlin.ByteArray, TarsTagCommon(id=9), TarsHead(tag=0, type=12(Zero))
            endStructure: prepareNextHead() called
            decodeElementIndex: TarsHead(tag=10, type=3(Long))
            name=lMsgUid
            decodeElementIndex: TarsHead(tag=11, type=0(Byte))
            name=lLastChangeTime
            decodeElementIndex: TarsHead(tag=12, type=9(List))
            name=vCPicInfo

            beginStructure: kotlin.collections.ArrayList, LIST
            endStructure: kotlin.collections.ArrayList, TarsTagCommon(id=12), TarsHead(tag=13, type=10(StructBegin))
            decodeElementIndex: TarsHead(tag=13, type=10(StructBegin))
            name=stShareData

            beginStructure: net.mamoe.mirai.internal.network.protocol.data.jce.ShareData, CLASS
                decodeElementIndex: TarsHead(tag=0, type=6(String1))
                name=pkgname
                decodeElementIndex: TarsHead(tag=1, type=6(String1))
                name=msgtail
                decodeElementIndex: TarsHead(tag=2, type=6(String1))
                name=picurl
                decodeElementIndex: TarsHead(tag=3, type=6(String1))
                name=url
                decodeElementIndex: TarsHead(tag=0, type=11(StructEnd))
                decodeElementIndex: TarsHead(tag=0, type=11(StructEnd))
            endStructure: net.mamoe.mirai.internal.network.protocol.data.jce.ShareData, TarsTagCommon(id=0), TarsHead(tag=0, type=11(StructEnd))
            decodeElementIndex: TarsHead(tag=14, type=12(Zero))
            name=lFromInstId
            decodeElementIndex: TarsHead(tag=15, type=13(SimpleList))
            name=vRemarkOfSender

            beginStructure: kotlin.ByteArray, LIST
                SimpleByteArrayReader.decodeCollectionSize: 0
            endStructure: kotlin.ByteArray, TarsTagCommon(id=15), TarsHead(tag=0, type=12(Zero))
            endStructure: prepareNextHead() called
            decodeElementIndex: TarsHead(tag=16, type=6(String1))
            name=strFromMobile
            decodeElementIndex: TarsHead(tag=17, type=6(String1))
            name=strFromName
            decodeElementIndex: TarsHead(tag=18, type=9(List))
            name=vNickName

            beginStructure: kotlin.collections.ArrayList, LIST
            endStructure: kotlin.collections.ArrayList, TarsTagCommon(id=18), TarsHead(tag=0, type=11(StructEnd))
            decodeElementIndex: TarsHead(tag=0, type=11(StructEnd))
            decodeElementIndex: TarsHead(tag=0, type=11(StructEnd))
        endStructure: net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo, TarsTagCommon(id=0), TarsHead(tag=0, type=11(StructEnd))
    endStructure: kotlin.collections.ArrayList, TarsTagCommon(id=0), TarsHead(tag=3, type=2(Int))
    decodeElementIndex: TarsHead(tag=3, type=2(Int))
    name=svrip
    decodeElementIndex: TarsHead(tag=4, type=13(SimpleList))
    name=vSyncCookie

    beginStructure: kotlin.ByteArray, LIST
        SimpleByteArrayReader.decodeCollectionSize: 0
    endStructure: kotlin.ByteArray, TarsTagCommon(id=4), TarsHead(tag=0, type=12(Zero))
    endStructure: prepareNextHead() called
    decodeElementIndex: TarsHead(tag=5, type=9(List))
    name=vUinPairMsg

    beginStructure: kotlin.collections.ArrayList, LIST
    endStructure: kotlin.collections.ArrayList, TarsTagCommon(id=5), TarsHead(tag=6, type=8(Map))
    decodeElementIndex: TarsHead(tag=6, type=8(Map))
    name=mPreviews

    beginStructure: kotlin.collections.LinkedHashMap, MAP
        decodeCollectionSize in MapReader: kotlin.collections.LinkedHashMap
        decodeCollectionSize = 0
        MapReader.endStructure: TarsHead(tag=7, type=0(Byte))
    endStructure: kotlin.collections.LinkedHashMap, TarsTagCommon(id=1), TarsHead(tag=7, type=0(Byte))
    decodeElementIndex: TarsHead(tag=7, type=0(Byte))
    skipping Byte
    next! TarsHead(tag=8, type=13(SimpleList))
    skipping SimpleList
    next! TarsHead(tag=9, type=10(StructBegin))
    skipping StructBegin
        skipping Zero
        skipping Zero
        skipping Zero
        skipping Zero
        skipping Zero
    skipping StructEnd
    next! TarsHead(tag=10, type=10(StructBegin))
    skipping StructBegin
        skipping Zero
        skipping Zero
        skipping Zero
        skipping Zero
        skipping Zero
    skipping StructEnd
    next! TarsHead(tag=11, type=10(StructBegin))
    skipping StructBegin
        skipping String1
        skipping String1
        skipping String1
    skipping StructEnd
    next! TarsHead(tag=12, type=0(Byte))
    skipping Byte
, cause=java.io.EOFException: One more byte required but reached end of input)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.doLoadAs$SerializationUtils__UtilsKt(utils.kt:97)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:63)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readJceStruct(utils.kt:118)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readJceStruct(utils.kt:1)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt:150)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt:147)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(utils.kt:175)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(utils.kt:1)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket(utils.kt:147)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readUniPacket(utils.kt:1)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.OnlinePushReqPush.decode(OnlinePush.ReqPush.kt:29)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:369)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: One more byte required but reached end of input
        at kotlinx.io.core.ByteReadPacketBase.readByteSlow(Packet.kt:186)
        at kotlinx.io.core.ByteReadPacketBase.readByteSlow2(Packet.kt:181)
        at kotlinx.io.core.ByteReadPacketBase.readByte(Packet.kt:170)
        at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.readNextHeadButDoNotAssignTo_Head(TarsInput.kt:301)
        at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.readNextHeadButDoNotAssignTo_Head$default(TarsInput.kt:68)
        at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.prepareNextHead(TarsInput.kt:52)
        at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.decodeElementIndex(TarsDecoder.kt:321)
        at net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack$SvcReqPushMsg$$serializer.deserialize(OnlinePushPack.kt:66)
        at net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack$SvcReqPushMsg$$serializer.deserialize(OnlinePushPack.kt:66)
        at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:177)
        at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load(Tars.kt:44)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.doLoadAs$SerializationUtils__UtilsKt(utils.kt:84)
        ... 22 more
        Suppressed: java.io.EOFException: One more byte required but reached end of input
                at kotlinx.io.core.ByteReadPacketBase.readByteSlow(Packet.kt:186)
                at kotlinx.io.core.ByteReadPacketBase.readByteSlow2(Packet.kt:181)
                at kotlinx.io.core.ByteReadPacketBase.readByte(Packet.kt:170)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.readNextHeadButDoNotAssignTo_Head(TarsInput.kt:301)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.readNextHeadButDoNotAssignTo_Head$default(TarsInput.kt:68)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.prepareNextHead(TarsInput.kt:52)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.decodeElementIndex(TarsDecoder.kt:321)
                at net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack$SvcReqPushMsg$$serializer.deserialize(OnlinePushPack.kt:66)
                at net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack$SvcReqPushMsg$$serializer.deserialize(OnlinePushPack.kt:66)
                at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260)
                at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:177)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load(Tars.kt:44)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load$default(Tars.kt:42)
                at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.doLoadAs$SerializationUtils__UtilsKt(utils.kt:73)
                ... 22 more
```

### 补充信息

<details>
<summary>另一段报错</summary>
2022-05-11 21:34:03 E/Net 1526****: Exception in decoding packet.
ContextualBugReportException(message=在 解析 net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack.SvcReqPushMsg 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    调试信息:
Data:
02 5B 02 BB 5D 12 62 7C 80 22 29 00 01 0A 02 5B 02 BB 5D 1C 21 02 10 31 49 45 46 00 52 62 7C 80 22 6D 00 01 00 D5 00 26 1A 0C 1C 2C 3C 4C 5D 00 0C 6D 00 0C 7D 00 0C 8D 00 0C 9C AC BC CC DD 00 0C EC FC 0F 0B 2A 0C 1C 2C 3C 4C 5C 6C 0B 3A 0C 1C 2C 3C 4C 5C 6C 7C 8D 00 0C 9D 00 0C AC BD 00 0C CD 00 0C DC ED 00 0C FC 0F FC 10 0B 4A 0C 1C 2C 3C 4C 5C 6C 7C 8C 96 00 0B 5A 0C 1C 2C 3C 4C 5C 6C 7C 8C 9D 00 0C 0B 6A 0C 1A 0C 1C 26 00 0B 2A 0C 0B 3A 0C 16 00 0B 4A 09 0C 0B 5A 09 0C 0B 0B 7A 0C 1C 2C 36 00 0B 8A 0C 1C 2C 36 00 0B 9A 09 0C 0B AD 00 00 44 08 01 12 40 0A 06 08 F4 EF BB 8F 04 10 C1 E9 FD 97 03 18 01 22 2C 10 01 1A 1A 18 B0 8B AB A8 08 20 C1 E9 FD 97 03 28 08 30 02 A2 01 04 08 DC D5 03 A8 01 02 20 00 28 00 32 08 18 01 20 B6 80 F2 93 06 28 00 7C 8D 00 00 13 08 90 04 10 90 84 88 83 80 80 80 80 02 18 00 20 DF 86 03 9D 00 0C A3 02 00 00 00 00 62 02 10 B0 01 C9 0C DA 06 00 16 00 26 00 36 00 0B EC FD 0F 00 0C F6 10 00 F6 11 00 F9 12 0C 0B 32 BE E0 87 0B 4D 00 0C 59 0C 68 0C 70 01 8D 00 0C 9A 0C 1C 2C 3C 4C 0B AA 0C 1C 2C 3C 4C 0B BA 06 00 16 00 26 00 0B C0 01
Trace:

beginStructure: net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack.SvcReqPushMsg, CLASS
    decodeElementIndex: TarsHead(tag=0, type=2(Int))
    name=uin
    decodeElementIndex: TarsHead(tag=1, type=2(Int))
    name=uMsgTime
    decodeElementIndex: TarsHead(tag=2, type=9(List))
    name=vMsgInfos

    beginStructure: kotlin.collections.ArrayList, LIST

        beginStructure: net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo, CLASS
            decodeElementIndex: TarsHead(tag=0, type=2(Int))
            name=lFromUin
            decodeElementIndex: TarsHead(tag=1, type=12(Zero))
            name=uMsgTime
            decodeElementIndex: TarsHead(tag=2, type=1(Short))
            name=shMsgType
            decodeElementIndex: TarsHead(tag=3, type=1(Short))
            name=shMsgSeq
            decodeElementIndex: TarsHead(tag=4, type=6(String1))
            name=strMsg
            decodeElementIndex: TarsHead(tag=5, type=2(Int))
            name=uRealMsgTime
            decodeElementIndex: TarsHead(tag=6, type=13(SimpleList))
            name=vMsg

            beginStructure: kotlin.ByteArray, LIST
                SimpleByteArrayReader.decodeCollectionSize: 213
            endStructure: kotlin.ByteArray, TarsTagCommon(id=6), TarsHead(tag=0, type=1(Short))
            endStructure: prepareNextHead() called
            decodeElementIndex: TarsHead(tag=7, type=12(Zero))
            name=uAppShareID
            decodeElementIndex: TarsHead(tag=8, type=13(SimpleList))
            name=vMsgCookies

            beginStructure: kotlin.ByteArray, LIST
                SimpleByteArrayReader.decodeCollectionSize: 19
            endStructure: kotlin.ByteArray, TarsTagCommon(id=8), TarsHead(tag=0, type=0(Byte))
            endStructure: prepareNextHead() called
            decodeElementIndex: TarsHead(tag=9, type=13(SimpleList))
            name=vAppShareCookie

            beginStructure: kotlin.ByteArray, LIST
                SimpleByteArrayReader.decodeCollectionSize: 0
            endStructure: kotlin.ByteArray, TarsTagCommon(id=9), TarsHead(tag=0, type=12(Zero))
            endStructure: prepareNextHead() called
            decodeElementIndex: TarsHead(tag=10, type=3(Long))
            name=lMsgUid
            decodeElementIndex: TarsHead(tag=11, type=0(Byte))
            name=lLastChangeTime
            decodeElementIndex: TarsHead(tag=12, type=9(List))
            name=vCPicInfo

            beginStructure: kotlin.collections.ArrayList, LIST
            endStructure: kotlin.collections.ArrayList, TarsTagCommon(id=12), TarsHead(tag=13, type=10(StructBegin))
            decodeElementIndex: TarsHead(tag=13, type=10(StructBegin))
            name=stShareData

            beginStructure: net.mamoe.mirai.internal.network.protocol.data.jce.ShareData, CLASS
                decodeElementIndex: TarsHead(tag=0, type=6(String1))
                name=pkgname
                decodeElementIndex: TarsHead(tag=1, type=6(String1))
                name=msgtail
                decodeElementIndex: TarsHead(tag=2, type=6(String1))
                name=picurl
                decodeElementIndex: TarsHead(tag=3, type=6(String1))
                name=url
                decodeElementIndex: TarsHead(tag=0, type=11(StructEnd))
                decodeElementIndex: TarsHead(tag=0, type=11(StructEnd))
            endStructure: net.mamoe.mirai.internal.network.protocol.data.jce.ShareData, TarsTagCommon(id=0), TarsHead(tag=0, type=11(StructEnd))
            decodeElementIndex: TarsHead(tag=14, type=12(Zero))
            name=lFromInstId
            decodeElementIndex: TarsHead(tag=15, type=13(SimpleList))
            name=vRemarkOfSender

            beginStructure: kotlin.ByteArray, LIST
                SimpleByteArrayReader.decodeCollectionSize: 0
            endStructure: kotlin.ByteArray, TarsTagCommon(id=15), TarsHead(tag=0, type=12(Zero))
            endStructure: prepareNextHead() called
            decodeElementIndex: TarsHead(tag=16, type=6(String1))
            name=strFromMobile
            decodeElementIndex: TarsHead(tag=17, type=6(String1))
            name=strFromName
            decodeElementIndex: TarsHead(tag=18, type=9(List))
            name=vNickName

            beginStructure: kotlin.collections.ArrayList, LIST
            endStructure: kotlin.collections.ArrayList, TarsTagCommon(id=18), TarsHead(tag=0, type=11(StructEnd))
            decodeElementIndex: TarsHead(tag=0, type=11(StructEnd))
            decodeElementIndex: TarsHead(tag=0, type=11(StructEnd))
        endStructure: net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo, TarsTagCommon(id=0), TarsHead(tag=0, type=11(StructEnd))
    endStructure: kotlin.collections.ArrayList, TarsTagCommon(id=0), TarsHead(tag=3, type=2(Int))
    decodeElementIndex: TarsHead(tag=3, type=2(Int))
    name=svrip
    decodeElementIndex: TarsHead(tag=4, type=13(SimpleList))
    name=vSyncCookie

    beginStructure: kotlin.ByteArray, LIST
        SimpleByteArrayReader.decodeCollectionSize: 0
    endStructure: kotlin.ByteArray, TarsTagCommon(id=4), TarsHead(tag=0, type=12(Zero))
    endStructure: prepareNextHead() called
    decodeElementIndex: TarsHead(tag=5, type=9(List))
    name=vUinPairMsg

    beginStructure: kotlin.collections.ArrayList, LIST
    endStructure: kotlin.collections.ArrayList, TarsTagCommon(id=5), TarsHead(tag=6, type=8(Map))
    decodeElementIndex: TarsHead(tag=6, type=8(Map))
    name=mPreviews

    beginStructure: kotlin.collections.LinkedHashMap, MAP
        decodeCollectionSize in MapReader: kotlin.collections.LinkedHashMap
        decodeCollectionSize = 0
        MapReader.endStructure: TarsHead(tag=7, type=0(Byte))
    endStructure: kotlin.collections.LinkedHashMap, TarsTagCommon(id=1), TarsHead(tag=7, type=0(Byte))
    decodeElementIndex: TarsHead(tag=7, type=0(Byte))
    skipping Byte
    next! TarsHead(tag=8, type=13(SimpleList))
    skipping SimpleList
    next! TarsHead(tag=9, type=10(StructBegin))
    skipping StructBegin
        skipping Zero
        skipping Zero
        skipping Zero
        skipping Zero
        skipping Zero
    skipping StructEnd
    next! TarsHead(tag=10, type=10(StructBegin))
    skipping StructBegin
        skipping Zero
        skipping Zero
        skipping Zero
        skipping Zero
        skipping Zero
    skipping StructEnd
    next! TarsHead(tag=11, type=10(StructBegin))
    skipping StructBegin
        skipping String1
        skipping String1
        skipping String1
    skipping StructEnd
    next! TarsHead(tag=12, type=0(Byte))
    skipping Byte
, cause=java.io.EOFException: One more byte required but reached end of input)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.doLoadAs$SerializationUtils__UtilsKt(utils.kt:97)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:63)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readJceStruct(utils.kt:118)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readJceStruct(utils.kt:1)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt:150)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt:147)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize(utils.kt:175)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.decodeUniRequestPacketAndDeserialize(utils.kt:1)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket(utils.kt:147)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readUniPacket(utils.kt:1)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.OnlinePushReqPush.decode(OnlinePush.ReqPush.kt:29)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:369)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.EOFException: One more byte required but reached end of input
        at kotlinx.io.core.ByteReadPacketBase.readByteSlow(Packet.kt:186)
        at kotlinx.io.core.ByteReadPacketBase.readByteSlow2(Packet.kt:181)
        at kotlinx.io.core.ByteReadPacketBase.readByte(Packet.kt:170)
        at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.readNextHeadButDoNotAssignTo_Head(TarsInput.kt:301)
        at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.readNextHeadButDoNotAssignTo_Head$default(TarsInput.kt:68)
        at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.prepareNextHead(TarsInput.kt:52)
        at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.decodeElementIndex(TarsDecoder.kt:321)
        at net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack$SvcReqPushMsg$$serializer.deserialize(OnlinePushPack.kt:66)
        at net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack$SvcReqPushMsg$$serializer.deserialize(OnlinePushPack.kt:66)
        at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:177)
        at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load(Tars.kt:44)
        at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.doLoadAs$SerializationUtils__UtilsKt(utils.kt:84)
        ... 22 more
        Suppressed: java.io.EOFException: One more byte required but reached end of input
                at kotlinx.io.core.ByteReadPacketBase.readByteSlow(Packet.kt:186)
                at kotlinx.io.core.ByteReadPacketBase.readByteSlow2(Packet.kt:181)
                at kotlinx.io.core.ByteReadPacketBase.readByte(Packet.kt:170)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.readNextHeadButDoNotAssignTo_Head(TarsInput.kt:301)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.readNextHeadButDoNotAssignTo_Head$default(TarsInput.kt:68)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsInput.prepareNextHead(TarsInput.kt:52)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.internal.TarsDecoder.decodeElementIndex(TarsDecoder.kt:321)
                at net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack$SvcReqPushMsg$$serializer.deserialize(OnlinePushPack.kt:66)
                at net.mamoe.mirai.internal.network.protocol.data.jce.OnlinePushPack$SvcReqPushMsg$$serializer.deserialize(OnlinePushPack.kt:66)
                at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:260)
                at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:177)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load(Tars.kt:44)
                at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load$default(Tars.kt:42)
                at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.doLoadAs$SerializationUtils__UtilsKt(utils.kt:73)
                ... 22 more

</details>

**Comment by Him188** [comment]
测试在 2.12.0-dev-70c8255b 可以正常解析
