### ISSUE TITLE
Quote类型NoSuchElementException错误

### ISSUE THREAD

**Issue by samsamlausam** [mamoe/mirai#203]
## 问题
RT，附送trace
```
`17:51:27 [INFO] [NETWORK ERROR] java.util.NoSuchElementException: Message type net.mamoe.mirai.message.data.MessageSource$Key@11c552d not found in chain Quote报错，我提issue
        at net.mamoe.mirai.message.data.MessageChain$DefaultImpls.get(MessageChain.kt:541)
        at net.mamoe.mirai.message.data.MessageChainImplByCollection.get(MessageChain.kt:484)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toDTO(MessageDTO.kt:238)
        at net.mamoe.mirai.api.http.data.common.MessageDTOKt.toDTO(MessageDTO.kt:214)
        at net.mamoe.mirai.api.http.route.WebSocketRouteModuleKt$websocketRouteModule$1$$special$$inlined$miraiWebsocket$1$lambda$1$1.invokeSuspend(WebSocketRouteModule.kt:39)
        at net.mamoe.mirai.api.http.route.WebSocketRouteModuleKt$websocketRouteModule$1$$special$$inlined$miraiWebsocket$1$lambda$1$1.invoke(WebSocketRouteModule.kt)
        at net.mamoe.mirai.event.SubscribeMessagesKt$subscribeMessages$4$1.invokeSuspend(subscribeMessages.kt:136)
        at net.mamoe.mirai.event.SubscribeMessagesKt$subscribeMessages$4$1.invoke(subscribeMessages.kt)
        at net.mamoe.mirai.event.SubscriberKt$subscribeAlways$3.invokeSuspend(subscriber.kt:246)
        at net.mamoe.mirai.event.SubscriberKt$subscribeAlways$3.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:76)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:76)
        at net.mamoe.mirai.event.internal.InternalEventListenersKt$callAndRemoveIfRequired$$inlined$forEachNode$lambda$1.invokeSuspend(InternalEventListeners.kt:167)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`
```

## 如何复现

Quote一个消息就有了

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/78618342-d2871e80-78ac-11ea-99e5-0d1ada0c4616.png)
[XXX(7725XX)] XXXXX(1040XXXX) -> [mirai:source:1156175627][mirai:at:1994701021] [mirai:quote:1454727684] [mirai:face:107]
经测试 0.34.0 正常
