### ISSUE TITLE
后台可以接收消息但无法发送消息java.lang.reflect.InvocationTargetException: 'void kotlinx.serialization.PolymorphicSerializer.<init>(kotlin.reflect.KClass, java.lang.annotation.Annotation[])'

### ISSUE THREAD

**Issue by Tritoce** [mamoe/mirai#2031]
### 问题描述

mira接受消息后在发送消息时产生
```
2022-05-14 17:12:27 W/stderr: Exception in thread "DefaultDispatcher-worker-4" java.lang.reflect.InvocationTargetException: 'void kotlinx.serialization.PolymorphicSerializer.<init>(kotlin.reflect.KClass, java.lang.annotation.Annotation[])'
2022-05-14 17:12:27 W/stderr:   at kotlinx.serialization.internal.PlatformKt.invokeSerializerOnCompanion(Platform.kt:106)
2022-05-14 17:12:27 W/stderr:   at kotlinx.serialization.internal.PlatformKt.constructSerializerForGivenTypeArgs(Platform.kt:41)
2022-05-14 17:12:27 W/stderr:   at kotlinx.serialization.internal.PlatformKt.compiledSerializerImpl(Platform.kt:23)
2022-05-14 17:12:27 W/stderr:   at kotlinx.serialization.SerializersKt__SerializersKt.serializerOrNull(Serializers.kt:178)
2022-05-14 17:12:27 W/stderr:   at kotlinx.serialization.SerializersKt.serializerOrNull(Unknown Source)
2022-05-14 17:12:27 W/stderr:   at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:155)
2022-05-14 17:12:27 W/stderr:   at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
2022-05-14 17:12:27 W/stderr:   at net.mamoe.mirai.api.http.adapter.internal.serializer.BuiltinJsonSerializer.encodeElement(BuiltinJson.kt:68)
2022-05-14 17:12:27 W/stderr:   at net.mamoe.mirai.api.http.adapter.ws.WebsocketAdapter.offerChannel(WebsocketAdapter.kt:98)
2022-05-14 17:12:27 W/stderr:   at net.mamoe.mirai.api.http.adapter.ws.WebsocketAdapter.onReceiveBotEvent(WebsocketAdapter.kt:53)
2022-05-14 17:12:27 W/stderr:   at net.mamoe.mirai.api.http.context.MahContext$handleBotEvent$1$1.invokeSuspend(MahContext.kt:116)
2022-05-14 17:12:27 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-05-14 17:12:27 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-05-14 17:12:27 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-05-14 17:12:27 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-05-14 17:12:27 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-05-14 17:12:27 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-05-14 17:12:27 W/stderr: Caused by: java.lang.NoSuchMethodError: 'void kotlinx.serialization.PolymorphicSerializer.<init>(kotlin.reflect.KClass, java.lang.annotation.Annotation[])'
2022-05-14 17:12:27 W/stderr:   at net.mamoe.mirai.api.http.adapter.internal.dto.EventDTO$Companion$$cachedSerializer$delegate$1.invoke(base.kt:16)
2022-05-14 17:12:27 W/stderr:   at net.mamoe.mirai.api.http.adapter.internal.dto.EventDTO$Companion$$cachedSerializer$delegate$1.invoke(base.kt:16)
2022-05-14 17:12:27 W/stderr:   at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
2022-05-14 17:12:27 W/stderr:   at net.mamoe.mirai.api.http.adapter.internal.dto.EventDTO$Companion.serializer(base.kt:16)
2022-05-14 17:12:27 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-05-14 17:12:27 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-05-14 17:12:27 W/stderr:   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-05-14 17:12:27 W/stderr:   at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-05-14 17:12:27 W/stderr:   at kotlinx.serialization.internal.PlatformKt.invokeSerializerOnCompanion(Platform.kt:101)
2022-05-14 17:12:27 W/stderr:   ... 16 more
```

无法发送消息

### 复现

使用mclinstaller安装mira后，安装mirai-api-http，配置好config私聊发送消息后启动文档demo后发生上述问题

### mirai-core 版本

2.10.3

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mcl-addon-2.0.2.jar
mirai-api-http-2.5.0.jar

**Comment by Him188** [comment]
@ryoii Are you a magician?

**Comment by ryoii** [comment]
project-mirai/mirai-api-http#568

使用 2.4 版本的 mah 或者 2.11 版本的 core

**Comment by Tritoce** [comment]
感谢 已经可以正常使用

> [project-mirai/mirai-api-http#568](https://github.com/project-mirai/mirai-api-http/issues/568)
> 
> 使用 2.4 版本的 mah 或者 2.11 版本的 core
