### ISSUE TITLE
加载时得到了无法理解的版本错误：`version >=1.0.3 while the resolved is 1.0.8`

### ISSUE THREAD

**Issue by minoism** [mamoe/mirai#2039]
### 问题描述

![image](https://user-images.githubusercontent.com/58068445/168874774-c7ce0522-8fde-463e-bf64-740de90cb507.png)

### 复现

只是安装了 https://github.com/LaoLittle/SkikoMirai/ 和 https://github.com/LaoLittle/DrawMeme/

### mirai-core 版本

2.10.3

### bot-protocol

ANDROID_PHONE

### 其他组件版本

```shell
[root@VM-8-15-centos mirai]# ./mcl

  01:29:50 [INFO] iTXTech Mirai Console Loader version 2.0.1-b5303b5
  01:29:50 [INFO] https://github.com/iTXTech/mirai-console-loader
  01:29:50 [INFO] This program is licensed under GNU AGPL v3
  01:29:51 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
 
如果无法获取Mirai-Repo信息, 例如启动时出现JSON解析错误
请升级到MCL 2.0 Beta并将 config.json 中的 Mirai-Repo 更改为 https://repo.itxtech.org

  01:29:51 [INFO] Verifying "net.mamoe:mirai-console" v2.10.3
  01:29:51 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.10.3
  01:29:51 [INFO] Verifying "net.mamoe:mirai-core-all" v2.10.3
  01:29:51 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2
  01:29:51 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
2022-05-18 01:29:52 I/main: Starting mirai-console...
2022-05-18 01:29:52 I/main: Backend: version 2.10.3, built on 2022-05-08 17:33:45.
2022-05-18 01:29:52 I/main: Frontend Terminal: version 2.10.3, provided by Mamoe Technologies
2022-05-18 01:29:52 I/main: Welcome to visit https://mirai.mamoe.net/
2022-05-18 01:29:53 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.plugin.loader.PluginLoadException: Plugin 'org.laolittle.plugin.draw.DrawMeme' ('org.laolittle.plugin.draw.DrawMeme') requires 'org.laolittle.plugin.SkikoMirai' with version >=1.0.3 while the resolved is 1.0.8
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImplKt.checkSatisfies(PluginManagerImpl.kt:261)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.sortByDependencies$canBeLoad(PluginManagerImpl.kt:204)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.sortByDependencies$consumeLoadable(PluginManagerImpl.kt:210)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.sortByDependencies$doSort(PluginManagerImpl.kt:222)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.sortByDependencies$doSort(PluginManagerImpl.kt:230)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.sortByDependencies(PluginManagerImpl.kt:233)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:192)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:135)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:145)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:151)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:401)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:156)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:155)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:189)
        at org.itxtech.mcl.Loader.main(Loader.java:79)
```

**Comment by Karlatemp** [comment]
#1859
