### ISSUE TITLE
错误信息

### ISSUE THREAD

**Issue by dongbao66** [mamoe/mirai#2040]
### 问题描述

设置自动登录之后

### 复现

1.打开cmd运行几步就闪退

### mirai-core 版本

2.10.3

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
[0m2022-05-18 02:06:56 V/Net 357795897: No server list cached.[0m
[92m2022-05-18 02:06:58 I/Net 357795897: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2022-05-18 02:06:58 I/Net 357795897: Successfully fetched ecdh public key from server.[0m
[0m2022-05-18 02:06:58 V/Net 357795897: Send: wtlogin.login[0m
[0m2022-05-18 02:06:58 V/Net 357795897: Recv: wtlogin.login[0m
[0m2022-05-18 02:07:34 V/Net 357795897: No server list cached.[0m
[92m2022-05-18 02:07:35 I/Net 357795897: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2022-05-18 02:07:36 I/Net 357795897: Successfully fetched ecdh public key from server.[0m
[0m2022-05-18 02:07:36 V/Net 357795897: Send: wtlogin.login[0m
[0m2022-05-18 02:07:36 V/Net 357795897: Recv: wtlogin.login[0m
[0m2022-05-18 02:07:36 V/Net 357795897: Send: wtlogin.login[0m
[0m2022-05-18 02:07:36 V/Net 357795897: Recv: wtlogin.login[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Send: StatSvc.register(online)[0m
[92m2022-05-18 02:07:37 I/Net 357795897: Server time updated, serverTime: 1652810858, diff: 1ms=0.001s[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Recv: StatSvc.register[0m
[0m2022-05-18 02:07:37 V/Net 357795897: No BdhSession cache[0m
[92m2022-05-18 02:07:37 I/Net 357795897: Start loading stranger list...[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[92m2022-05-18 02:07:37 I/Net 357795897: Syncing friend message history...[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[92m2022-05-18 02:07:37 I/Net 357795897: Start loading friend list...[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Recv: OidbSvc.0x5d2_0[0m
[92m2022-05-18 02:07:37 I/Net 357795897: Successfully loaded stranger list: 0 in total[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Recv: StatSvc.GetDevLoginInfo[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Recv: OidbSvc.0x496[0m
[92m2022-05-18 02:07:37 I/Net 357795897: No OtherClient online.[0m
[92m2022-05-18 02:07:37 I/Net 357795897: Start loading group list...[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Recv: friendlist.getFriendGroupList[0m
[92m2022-05-18 02:07:37 I/Net 357795897: Syncing friend message history: Success.[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Loading friend list: 3/3[0m
[92m2022-05-18 02:07:37 I/Net 357795897: Successfully loaded friend list: 3 in total[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Recv: friendlist.GetTroopListReqV2[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-05-18 02:07:37 V/Net 357795897: Recv: friendlist.GetTroopMemberListReq[0m
[92m2022-05-18 02:07:37 I/Net 357795897: Successfully loaded group list: 1 in total.[0m
[92m2022-05-18 02:07:37 I/Net 357795897: Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2022-05-18 02:07:37 I/Net 357795897: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[31m2022-05-18 02:07:40 E/Net 357795897: ExceptionInPacketHandlerException(packetHandler=CallPacketFactoryPacketHandler, incomingPacket=IncomingPacket(cmd=ConfigPushSvc.PushReq, seq=-1722709212, SUCCESS, r=ConfigPushSvc.PushReq.PushReqResponse.ServerListPush), cause=ContextualBugReportException(message=在 ConfigPush.ReqPush type=1 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    调试信息: 19 00 08 0A 16 0E 31 30 39 2E 32 34 34 2E 31 35 32 2E 32 34 20 50 30 01 4C 5C 60 08 70 01 86 02 73 68 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0D 31 32 30 2E 35 33 2E 36 34 2E 32 34 39 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 38 2E 37 37 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 34 37 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 35 32 2E 32 30 35 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 39 36 2E 31 35 31 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 32 35 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 39 00 08 0A 16 0E 31 30 39 2E 32 34 34 2E 31 35 32 2E 32 34 20 50 30 01 4C 5C 60 08 70 01 86 02 73 68 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0D 31 32 30 2E 35 33 2E 36 34 2E 32 34 39 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 38 2E 37 37 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 34 37 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 35 32 2E 32 30 35 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 39 36 2E 31 35 31 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 32 35 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 4C 5C 6C 70 01 89 00 05 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B 99 00 05 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B A9 0C B9 0C C9 0C D9 0C E0 01 FC 0F F6 10 14 51 44 49 41 4F 5F 50 4F 4C 49 43 59 5F 44 45 46 41 55 4C 54 F0 11 01, cause=null))
ExceptionInPacketHandlerException(packetHandler=CallPacketFactoryPacketHandler, incomingPacket=IncomingPacket(cmd=ConfigPushSvc.PushReq, seq=-1722709212, SUCCESS, r=ConfigPushSvc.PushReq.PushReqResponse.ServerListPush), cause=ContextualBugReportException(message=在 ConfigPush.ReqPush type=1 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    调试信息: 19 00 08 0A 16 0E 31 30 39 2E 32 34 34 2E 31 35 32 2E 32 34 20 50 30 01 4C 5C 60 08 70 01 86 02 73 68 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0D 31 32 30 2E 35 33 2E 36 34 2E 32 34 39 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 38 2E 37 37 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 34 37 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 35 32 2E 32 30 35 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 39 36 2E 31 35 31 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 32 35 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 39 00 08 0A 16 0E 31 30 39 2E 32 34 34 2E 31 35 32 2E 32 34 20 50 30 01 4C 5C 60 08 70 01 86 02 73 68 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0D 31 32 30 2E 35 33 2E 36 34 2E 32 34 39 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 38 2E 37 37 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 34 37 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 35 32 2E 32 30 35 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 39 36 2E 31 35 31 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 32 35 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 4C 5C 6C 70 01 89 00 05 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B 99 00 05 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B A9 0C B9 0C C9 0C D9 0C E0 01 FC 0F F6 10 14 51 44 49 41 4F 5F 50 4F 4C 49 43 59 5F 44 45 46 41 55 4C 54 F0 11 01, cause=null))
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:45)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:84)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:82)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:178)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: ContextualBugReportException(message=在 ConfigPush.ReqPush type=1 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    调试信息: 19 00 08 0A 16 0E 31 30 39 2E 32 34 34 2E 31 35 32 2E 32 34 20 50 30 01 4C 5C 60 08 70 01 86 02 73 68 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0D 31 32 30 2E 35 33 2E 36 34 2E 32 34 39 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 38 2E 37 37 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 34 37 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 35 32 2E 32 30 35 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 39 36 2E 31 35 31 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 32 35 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 39 00 08 0A 16 0E 31 30 39 2E 32 34 34 2E 31 35 32 2E 32 34 20 50 30 01 4C 5C 60 08 70 01 86 02 73 68 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0D 31 32 30 2E 35 33 2E 36 34 2E 32 34 39 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 06 6F 74 68 65 72 73 AC 0B 0A 16 0C 31 38 33 2E 34 37 2E 39 38 2E 37 37 21 1F 90 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0C 34 39 2E 37 2E 32 35 33 2E 31 34 37 20 50 30 01 4C 5C 60 08 70 01 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0E 31 38 30 2E 31 30 39 2E 35 32 2E 32 30 35 21 36 B0 30 01 4C 5C 60 08 70 01 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 39 36 2E 31 35 31 21 01 BB 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 36 33 2E 31 37 37 2E 33 30 2E 32 32 35 20 50 30 01 4C 5C 60 08 70 01 86 02 73 7A 96 03 75 6E 69 AC 0B 0A 16 11 6D 73 66 77 69 66 69 2E 33 67 2E 71 71 2E 63 6F 6D 21 1F 90 30 01 4C 5C 60 08 7C 86 06 6F 74 68 65 72 73 96 06 6F 74 68 65 72 73 AC 0B 4C 5C 6C 70 01 89 00 05 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B 99 00 05 0A 16 0E 31 31 39 2E 31 34 37 2E 31 39 30 2E 33 37 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 74 65 6C AC 0B 0A 16 0D 34 32 2E 38 31 2E 31 39 33 2E 32 34 32 20 50 30 01 4C 50 03 60 08 7C 86 02 74 6A 96 03 74 65 6C AC 0B 0A 16 0D 31 38 30 2E 31 30 32 2E 35 39 2E 35 30 20 50 30 01 4C 50 03 60 08 7C 86 02 73 68 96 03 74 65 6C AC 0B 0A 16 0F 31 32 30 2E 32 33 32 2E 31 33 30 2E 31 30 32 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 02 63 6D AC 0B 0A 16 0E 31 35 37 2E 31 34 38 2E 34 32 2E 31 39 38 20 50 30 01 4C 50 03 60 08 7C 86 02 73 7A 96 03 75 6E 69 AC 0B A9 0C B9 0C C9 0C D9 0C E0 01 FC 0F F6 10 14 51 44 49 41 4F 5F 50 4F 4C 49 43 59 5F 44 45 46 41 55 4C 54 F0 11 01, cause=null)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle$handleServerListPush(ConfigPushSvc.kt:138)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle(ConfigPushSvc.kt:168)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle(ConfigPushSvc.kt:40)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	... 21 more
[0m
[0m2022-05-18 02:07:40 V/Net 357795897: Saving bdh session to cache[0m
[0m2022-05-18 02:07:40 V/Net 357795897: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2022-05-18 02:07:40 V/Net 357795897: Recv: ConfigPushSvc.PushReq[0m
[0m2022-05-18 02:10:06 V/Net 357795897: No server list cached.[0m
[92m2022-05-18 02:10:08 I/Net 357795897: ECDH key is valid.[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Send: wtlogin.exchange_emp[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Recv: wtlogin.exchange_emp[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Send: StatSvc.register(online)[0m
[92m2022-05-18 02:10:08 I/Net 357795897: Server time updated, serverTime: 1652811009, diff: 1ms=0.001s[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Recv: StatSvc.register[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Loading BdhSession from cache file[0m
[92m2022-05-18 02:10:08 I/Net 357795897: Syncing friend message history...[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[92m2022-05-18 02:10:08 I/Net 357795897: Start loading friend list...[0m
[92m2022-05-18 02:10:08 I/Net 357795897: Start loading stranger list...[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[92m2022-05-18 02:10:08 I/Net 357795897: Syncing friend message history: Success.[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Recv: OidbSvc.0x5d2_0[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Recv: StatSvc.GetDevLoginInfo[0m
[92m2022-05-18 02:10:08 I/Net 357795897: Successfully loaded stranger list: 0 in total[0m
[92m2022-05-18 02:10:08 I/Net 357795897: No OtherClient online.[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Recv: OidbSvc.0x496[0m
[92m2022-05-18 02:10:08 I/Net 357795897: Start loading group list...[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Recv: friendlist.getFriendGroupList[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Loading friend list: 3/3[0m
[92m2022-05-18 02:10:08 I/Net 357795897: Successfully loaded friend list: 3 in total[0m
[0m2022-05-18 02:10:08 V/Net 357795897: Recv: friendlist.GetTroopListReqV2[0m
[0m2022-05-18 02:10:09 V/Net 357795897: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-05-18 02:10:09 V/Net 357795897: Recv: friendlist.GetTroopMemberListReq[0m
[92m2022-05-18 02:10:09 I/Net 357795897: Successfully loaded group list: 1 in total.[0m
[92m2022-05-18 02:10:09 I/Net 357795897: Scheduled key refresh in 23h 55min 0.0s.[0m
[92m2022-05-18 02:10:09 I/Net 357795897: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[0m2022-05-18 02:10:11 V/Net 357795897: Saving bdh session to cache[0m
[0m2022-05-18 02:10:11 V/Net 357795897: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2022-05-18 02:10:11 V/Net 357795897: Recv: ConfigPushSvc.PushReq[0m
```

**Comment by Him188** [comment]
与 #2029 可能有关

**Comment by dongbao66** [comment]
你好，我最近忙碌中，无法亲自回复你的邮件。我看到后会尽快给你回复。

**Comment by Him188** [comment]
测试在 2.12.0-dev-70c8255b 正常

**Comment by dongbao66** [comment]
你好，我最近忙碌中，无法亲自回复你的邮件。我看到后会尽快给你回复。
