### ISSUE TITLE
自行注册插件加载器后启用插件报错

### ISSUE THREAD

**Issue by LaoLittle** [mamoe/mirai#2052]
### 问题描述

```
2022-05-21 21:06:39 E/main: Failed to init MiraiConsole.
java.lang.IllegalStateException: Plugin is unloaded
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.getPluginDescription(PluginManagerImpl.kt:82)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:197)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.scanPluginsUsingPluginLoadersIncludingThoseFromPluginLoaderProvider$mirai_console(PluginManagerImpl.kt:175)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:184)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:444)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:159)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:158)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
	at org.itxtech.mcl.Loader.start(Loader.java:189)
	at org.itxtech.mcl.Loader.main(Loader.java:79)
```

### 复现

```kotlin
override fun PluginComponentStorage.onLoad() {
        contributePluginLoader { RustPluginLoader }

        RustPluginManager.loadPlugins()
    }

    override fun onEnable() {
        logger.info { "Plugin loaded" }
        EventHandler.start()
        RustPluginManager.enablePlugins()
    }
```

```kotlin
object RustPluginLoader : PluginLoader<RustPlugin, RustPluginDescription> {
    override fun enable(plugin: RustPlugin) {
        enablePlugin(plugin.pluginPointer)
        plugin.enabled = true
    }

    override fun disable(plugin: RustPlugin) {
        disablePlugin(plugin.pluginPointer)
        plugin.enabled = false
    }

    override fun getPluginDescription(plugin: RustPlugin): RustPluginDescription {
        return plugin.description
    }

    override fun listPlugins(): List<RustPlugin> {
        return RustPluginManager.plugins
    }

    override fun load(plugin: RustPlugin) {
        loadPlugin(plugin.absolutePath)
    }

    fun loadLibrary(libName: String): RustPlugin {
        return load(RustPluginManager.pluginsPath.resolve(System.mapLibraryName(libName)))
    }

    fun load(path: Path): RustPlugin {
        val pluginPointer = loadPlugin(path.absolutePathString())

        val (id, name, author, version) = getPluginDescription(pluginPointer)

        val loaded = RustPlugin(path, pluginPointer) {
            this.id = id
            this.name = name
            this.author = author
            this.setVersion(version)
        }

        RustPluginManager.plugins.add(loaded)
        return loaded
    }

    private external fun loadPlugin(path: String): RawPointer

    /** Will close the library of this plugin */
    private external fun unloadPlugin(pluginPointer: RawPointer)

    private external fun getPluginDescription(pluginPointer: RawPointer): Array<String>

    private external fun enablePlugin(pluginPointer: RawPointer)

    private external fun disablePlugin(pluginPointer: RawPointer)

    init {
        RustPluginManager.loadManagerLib()
    }
}
```

### mirai-core 版本

2.11.0

关于这方面的文档也比较少，是我使用有误么

**Comment by Him188** [comment]
是 console 的 bug

**Comment by Him188** [comment]
Closed by 26c3bca4731d9aff87dd2f0c82e7c92143c1e548
