### ISSUE TITLE
2.11.0 新打包方式，插件在引用了相同的库时，在某些的情况下会产生冲突

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#2054]
### 问题描述

2.11.0 新打包方式，插件在引用了相同的库时，在某些的情况下会产生冲突，导致 `NoClassDefFoundError` 异常

### 复现

在尝试实现最小复现，目前先提供依赖列表

pixiv-helper-1.10.0-M1.mirai2
```
com.squareup.okhttp3:okhttp-dnsoverhttps:4.9.2
com.squareup:gifencoder:0.10.1
io.ktor:ktor-client-auth-jvm:1.6.7
io.ktor:ktor-client-auth:1.6.7
io.ktor:ktor-client-encoding-jvm:1.6.7
io.ktor:ktor-client-encoding:1.6.7
io.ktor:ktor-client-json-jvm:1.6.7
io.ktor:ktor-client-json:1.6.7
io.ktor:ktor-client-serialization-jvm:1.6.7
io.ktor:ktor-client-serialization:1.6.7
org.jetbrains.kotlin:kotlin-stdlib-common:1.6.21
org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21
org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21
org.jetbrains.kotlin:kotlin-stdlib:1.6.21
org.jetbrains:annotations:13.0
org.jsoup:jsoup:1.14.3
xyz.cssxsh.pixiv:pixiv-client:1.0.2
```

netdisk-filesync-plugin-1.3.1.mirai2
```
io.ktor:ktor-client-encoding-jvm:1.6.7
io.ktor:ktor-client-encoding:1.6.7
io.ktor:ktor-client-json-jvm:1.6.7
io.ktor:ktor-client-json:1.6.7
io.ktor:ktor-client-serialization-jvm:1.6.7
io.ktor:ktor-client-serialization:1.6.7
org.jetbrains.kotlin:kotlin-stdlib-common:1.6.21
org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21
org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21
org.jetbrains.kotlin:kotlin-stdlib:1.6.21
org.jetbrains:annotations:13.0
xyz.cssxsh.baidu:baidu-netdisk:2.0.8
xyz.cssxsh.baidu:baidu-oauth:2.0.8
```

### mirai-core 版本

2.11.0

### bot-protocol

ANDROID_PAD

### 系统日志

```text
2022-05-22 22:42:42 E/pixiv-helper: Exception in coroutine Plugin xyz.cssxsh.mirai.plugin.pixiv-helper of pixiv-helper
java.lang.NoClassDefFoundError: io/ktor/client/features/json/JsonFeatureKt
        at xyz.cssxsh.pixiv.PixivAuthClient$client$1.invoke(PixivAuthClient.kt:35)
        at xyz.cssxsh.pixiv.PixivAuthClient$client$1.invoke(PixivAuthClient.kt:34)
        at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41)
        at xyz.cssxsh.pixiv.PixivAuthClient.client(PixivAuthClient.kt:34)
        at xyz.cssxsh.pixiv.PixivAuthClient$clients$2.invoke(PixivAuthClient.kt:91)
        at xyz.cssxsh.pixiv.PixivAuthClient$clients$2.invoke(PixivAuthClient.kt:91)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at xyz.cssxsh.pixiv.PixivAuthClient.getClients(PixivAuthClient.kt:91)
        at xyz.cssxsh.pixiv.PixivAuthClient$useHttpClient$2.invokeSuspend(PixivAuthClient.kt:100)
        at xyz.cssxsh.pixiv.PixivAuthClient$useHttpClient$2.invoke(PixivAuthClient.kt)
        at xyz.cssxsh.pixiv.PixivAuthClient$useHttpClient$2.invoke(PixivAuthClient.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.SupervisorKt.supervisorScope(Supervisor.kt:61)
        at xyz.cssxsh.pixiv.PixivAuthClient.useHttpClient$suspendImpl(PixivAuthClient.kt:97)
        at xyz.cssxsh.pixiv.PixivAuthClient.useHttpClient(PixivAuthClient.kt)
        at xyz.cssxsh.pixiv.auth.OauthApiKt.refresh(OauthApi.kt:54)
        at xyz.cssxsh.pixiv.PixivAuthClient.info$suspendImpl(PixivAuthClient.kt:118)
        at xyz.cssxsh.pixiv.PixivAuthClient.info(PixivAuthClient.kt)
        at pixiv-helper-1.10.0-M1.mirai2.jar//xyz.cssxsh.mirai.pixiv.PixivHelperListener$subscribe$1$2.invokeSuspend(PixivHelperListener.kt:57)
        at pixiv-helper-1.10.0-M1.mirai2.jar//xyz.cssxsh.mirai.pixiv.PixivHelperListener$subscribe$1$2.invoke(PixivHelperListener.kt)
        at pixiv-helper-1.10.0-M1.mirai2.jar//xyz.cssxsh.mirai.pixiv.PixivHelperListener$subscribe$1$2.invoke(PixivHelperListener.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:455)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:50)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.process(InternalEventListeners.kt:166)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt.callAndRemoveIfRequired(InternalEventListeners.kt:115)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$1.invokeSuspend(InternalEventListeners.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:202)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassNotFoundException: io.ktor.client.features.json.JsonFeatureKt
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at net.mamoe.mirai.console.internal.plugin.DynLibClassLoader.loadClass(JvmPluginClassLoader.kt:138)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 43 more
```

**Comment by Karlatemp** [comment]
尝试最新 dev 版本, 可能已经修了

**Comment by Karlatemp** [comment]
Try 2.12.0-dev-167a29e0 / https://github.com/mamoe/mirai/actions/runs/2377078109
