### ISSUE TITLE
将MiraiCore集成于Compose Desktop时Bot的初始化产生大量报错

### ISSUE THREAD

**Issue by Longtianmu** [mamoe/mirai#2059]
### 问题描述

在Compose Desktop应用中引入Mirai core，
登陆bot时产生数以千计的如下log
![A8C4D24F-4E19-429A-9B80-791C68EE6313](https://user-images.githubusercontent.com/60567448/170091947-b69ff087-9d61-4146-b7b9-37a25f307739.png)

### 复现

新建Compose Desktop项目，并引入Mirai core 2.11.0 JDK选择17

### mirai-core 版本

2.11.0

### bot-protocol

MACOS

### 系统日志

```
[31m2022-05-24 23:52:33 E/Net 342750819: ExceptionInPacketHandlerException(packetHandler=CallPacketFactoryPacketHandler, incomingPacket=IncomingPacket(cmd=MessageSvc.PbGetMsg, seq=40502, SUCCESS, r=MessageSvcPbGetMsg.Response(flag=CONTINUE)), cause=java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response are in unnamed module of loader 'app'))
ExceptionInPacketHandlerException(packetHandler=CallPacketFactoryPacketHandler, incomingPacket=IncomingPacket(cmd=MessageSvc.PbGetMsg, seq=40502, SUCCESS, r=MessageSvcPbGetMsg.Response(flag=CONTINUE)), cause=java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response are in unnamed module of loader 'app'))
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:45)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:84)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:82)
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:193)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg$Response are in unnamed module of loader 'app')
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg.handle(MessageSvc.PbGetMsg.kt:189)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg.handle(MessageSvc.PbGetMsg.kt:42)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:110)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	... 21 more
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[Dispatchers.Default, Continuation at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$sendAndExpect$3$1$1.invokeSuspend(NetworkHandlerSupport.kt:102)@14a0110]){Completed}@55a31349. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: Job StandaloneCoroutine{Completed}@142fddb7 is already complete or completing, but is being completed with kotlin.Unit
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:831)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 4 more
```

**Comment by Him188** [comment]
#2049
