### ISSUE TITLE
安装VexMirai-0.1.0插件后，mirai无法正常启动。

### ISSUE THREAD

**Issue by xiaowanggua** [mamoe/mirai#206]
我使用/install 指令安装VexMirai-0.1.0插件后，重启后机器人无法正常启动，并且关闭窗口后，依然在后台运作，只能用任务管理器关闭。
控制台输出
[0m 16:49:35 [INFO] [Plugin Manager] loading plugin BiliBiliLinker[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] successfully loaded plugin BiliBiliLinker version 1.0.3 by Karlatemp[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] BBL is coming.[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] loading plugin ConsoleAddition[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] successfully loaded plugin ConsoleAddition version V0.2.2 by ryoii[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] Mirai-console的增强插件，添加若干常用的命令[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] loading plugin DrawLots[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] successfully loaded plugin DrawLots version V0.1.1 by Sincky[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] 玄学的群抽签插件[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] loading plugin hsoPro[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] successfully loaded plugin hsoPro version V0.0.1 by unknown[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] hso plugin Pro[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] loading plugin PingMyMCServer[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] successfully loaded plugin PingMyMCServer version 0.0.1 by NaturalHG[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] 在qq查询mc插件, javademo[39;49m
[0m 16:49:35 [INFO] [Plugin Manager] loading plugin VexMirai[39;49m
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.mamoe.mirai.console.wrapper.WrapperMain.start(WrapperMain.kt:150)
        at net.mamoe.mirai.console.wrapper.WrapperMain.preStartInNonNative(WrapperMain.kt:133)
        at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:89)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at net.mamoe.mirai.console.plugins.PluginManager$loadPlugins$4.invoke(PluginManager.kt:183)
        at net.mamoe.mirai.console.plugins.PluginManager.loadPlugins(PluginManager.kt:206)
        at net.mamoe.mirai.console.MiraiConsole.start(MiraiConsole.kt:85)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader$Companion.load(MiraiConsolePureLoader.kt:22)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.load(MiraiConsolePureLoader.kt)
        ... 7 more
Caused by: java.lang.NullPointerException
        at com.github.icebear67.MessageHandler.<init>(MessageHandler.java:20)
        at com.github.icebear67.Vex.<init>(Vex.java:23)
        ... 16 more

**Comment by Him188** [comment]
此为Vex插件问题：
```
at com.github.icebear67.Vex.(Vex.java:23)
```
