### ISSUE TITLE
登录验证过不去

### ISSUE THREAD

**Issue by a16797** [mamoe/mirai#2074]
### 问题描述

老qq安全性太高，用新手机号申请了一个新的qq，还是过不去验证

### 复现

![image](https://user-images.githubusercontent.com/16302217/171092673-6518779c-b5dc-4632-b98b-1783bc35d76d.png)
![image](https://user-images.githubusercontent.com/16302217/171092796-0c21264a-b4a7-49eb-b260-3d29e5d7989a.png)

![image](https://user-images.githubusercontent.com/16302217/171092854-8971505b-1884-4447-93e6-771b15703607.png)
![image](https://user-images.githubusercontent.com/16302217/171092873-025bc00b-37e9-4be8-aa7c-2a38264d8745.png)

### mirai-core 版本

2.11.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
[92m2022-05-31 12:26:04 I/main: Starting mirai-console...[0m[m
[92m2022-05-31 12:26:04 I/main: Backend: version 2.11.0, built on 2022-05-19 22:08:40.[0m[m
[92m2022-05-31 12:26:04 I/main: Frontend Terminal: version 2.11.0, provided by Mamoe Technologies[0m[m
[92m2022-05-31 12:26:04 I/main: Welcome to visit https://mirai.mamoe.net/[0m[m
[91m2022-05-31 12:26:05 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[0m[m
[91m2022-05-31 12:26:05 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
[0m[m
[91m2022-05-31 12:26:05 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[0m[m
[92m2022-05-31 12:26:05 I/plugin: Successfully loaded plugin blhx-wiki v0.3.12[0m[m
[92m2022-05-31 12:26:05 I/plugin: Successfully loaded plugin MCL Addon v2.0.2[0m[m
[92m2022-05-31 12:26:05 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop[0m[m
[92m2022-05-31 12:26:05 I/MCL Addon: iTXTech MCL Version: 2.1.0-71ec418[0m[m
[91m2022-05-31 12:26:05 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用[0m[m
[92m2022-05-31 12:26:05 I/main: 2 plugin(s) enabled.[0m[m
[92m2022-05-31 12:26:05 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.[0m[m
[92m2022-05-31 12:26:05 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.[0m[m
[92m2022-05-31 12:26:05 I/main: Auto-login 3598853267[0m[m
[91m2022-05-31 12:26:05 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
[0m[m
[92m2022-05-31 12:26:54 I/Bot.3598853267: Bot cancelled: Bot closed[0m[m
[31m2022-05-31 12:26:54 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3598853267), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3598853267), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:282)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: java.util.concurrent.CancellationException: Bot closed
		at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
		at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
		at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:80)
		at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
		at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
		at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
		at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
		at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
		at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
		at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:241)
		at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:444)
		at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:159)
		at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:158)
		at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:46)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.base/java.lang.reflect.Method.invoke(Unknown Source)
		at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
		at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
		at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
		at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
		at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
		at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
		at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
		at org.itxtech.mcl.Loader.start(Loader.java:189)
		at org.itxtech.mcl.Loader.main(Loader.java:79)
	Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3598853267), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)]
[0m[m
[92m2022-05-31 12:26:54 I/main: mirai-console started successfully.[0m[m
```

**Comment by Him188** [comment]
@mzdluo123

**Comment by Karlatemp** [comment]
https://mirai.mamoe.net/topic/223/ 的第一句话

> **DON'T** trying installing apks on **android emulator** or trying solving captcha on **android emulator**

**Comment by LaoLittle** [comment]
> https://mirai.mamoe.net/topic/223/ 的第一句话

Windows subsystem for Android 亲测有效）

**Comment by a16797** [comment]
> 

没看到这句话= =     换手机验证  可以了

**Comment by 250king** [comment]
我这边也出现了情况
![image](https://user-images.githubusercontent.com/61256966/174510008-f2b27c08-4abb-41f6-b168-b6841142ed03.png)
