### ISSUE TITLE
撤回好友消息报错

### ISSUE THREAD

**Issue by zhzRedstone** [mamoe/mirai#208]
```
 22:27:05 [INFO] [ConsoleAddition] [NETWORK] Event: MultiPacketBySequence
 22:27:05 [INFO] [ConsoleAddition] [NETWORK] Send: OnlinePush.RespPush
 22:27:05 [INFO] [ConsoleAddition] [NETWORK] Event: Failed(result=3, errorMessage=)
 22:27:05 [ERROR] [MiraiAPIHTTP] java.lang.IllegalStateException: Failed to recall message #855086461: Failed(result=3, errorMessage=)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.recall$suspendImpl(QQAndroidBot.common.kt:266)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase$recall$1.invokeSuspend(QQAndroidBot.common.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

```
POST /recall HTTP/1.1
Content-Length: 57
Content-Type: application/json;charset=UTF-8
Host: 127.0.0.1:5710
{
    "sessionKey": "l1k858U5",
    "target": 855086461
}

HTTP/1.1 500 Internal Server Error
connection: keep-alive
content-length: 68
content-type: text/plain; charset=UTF-8
date: Tue, 07 Apr 2020 14:27:05 GMT
server: Application/debug ktor/debug
Failed to recall message #855086461: Failed(result=3, errorMessage=)
```

|插件|版本|
|-|-|
|Core|0.34.0|
|Console|0.4.6|
| MiraiAPIHTTP|1.5.1|
|ConsoleAddition|0.2.3|

**Comment by Him188** [comment]
目前不支持撤回好友消息，见 #123
