### ISSUE TITLE
在SubCommand中使用sendTo方法时出现异常

### ISSUE THREAD

**Issue by 4o4E** [mamoe/mirai#2087]
### 问题描述

![1](https://user-images.githubusercontent.com/58851040/173181311-91f62cd5-bd52-43ef-9678-ebbc2e191bd3.png)

这样写会报错

![2](https://user-images.githubusercontent.com/58851040/173181322-25407a5e-0e6d-40d3-8b00-5a539ee25436.png)

这样不会

相关报错：https://pastebin.com/NFG0mtvw

### 复现

在subCommand中调用sendTo方法

### mirai-core 版本

2.11.1

### bot-protocol

IPAD

### 其他组件版本

mirai-console 2.11.1

### 系统日志

```
2022-06-11 16:41:51 W/GuessGroupFriends: Exception in executing command `[mirai:source:[3360],[1265913587]]/猜群友 测试 [mirai:at:3125685561]`
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:329)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:86)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:69)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.message.MessageReceipt (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.message.MessageReceipt are in unnamed module of loader 'app')
        at GuessGroupFriends-1.0.0.mirai2.jar//org.fenglin.Command.test(Command.kt:281)
        ... 27 more

2022-06-11 16:41:51 W/GuessGroupFriends: Exception in executing command `[mirai:source:[3360],[1265913587]]/猜群友 测试 [mirai:at:3125685561]`
java.lang.IllegalStateException: cannot upload forward message, failed on all servers.
        at net.mamoe.mirai.internal.network.highway.Highway.uploadResourceBdh(Highway.kt:453)
        at net.mamoe.mirai.internal.network.highway.Highway$uploadResourceBdh$1.invokeSuspend(Highway.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: kotlinx.coroutines.JobCancellationException: Parent job is Completed; job=StandaloneCoroutine{Completed}@5cf08b5e
        Suppressed: kotlinx.coroutines.JobCancellationException: Parent job is Completed; job=StandaloneCoroutine{Completed}@5cf08b5e
                Suppressed: kotlinx.coroutines.JobCancellationException: Parent job is Completed; job=StandaloneCoroutine{Completed}@5cf08b5e
                        Suppressed: kotlinx.coroutines.JobCancellationException: Parent job is Completed; job=StandaloneCoroutine{Completed}@5cf08b5e

2022-06-11 16:41:51 E/Chat Command: Exception in coroutine Plugin net.mamoe.mirai.console.chat-command of Chat Command
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.Default, Continuation at net.mamoe.mirai.internal.network.highway.Highway$uploadResourceBdh$$inlined$tryServersUpload$1.invokeSuspend(Highway.kt:85)@4b9243f]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
        at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader 'app')
        at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:147)
        at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        ... 4 more
```

**Comment by Him188** [comment]
确定能复现？

**Comment by 4o4E** [comment]
> 确定能复现？

能，我反复改了好几次代码，只要最后用的sendTo，就会出现这种情况，kotlin版本`1.6.21`

**Comment by 4o4E** [comment]
![image](https://user-images.githubusercontent.com/58851040/173189699-085ae99b-1a8d-4cf5-b229-06945421e806.png)
这样的代码不会报错
![image](https://user-images.githubusercontent.com/58851040/173189722-6f520700-5a2a-41fc-ae33-ea33bd96a1d6.png)
这样的代码会报错

会出错的代码:
```kotlin
@SubCommand("测试")
@Description("测试线索")
suspend fun CommandSender.test(target: User) {
    if (this !is MemberCommandSender) {
        sendMessage("仅可在群聊中使用")
        return
    }
    this as CommandSenderOnMessage<*>
    if (!hasPermission(GuessGroupFriends.testPerm)) {
        sendMessage(fromEvent.source.quote().plus("无权限"))
        return
    }
    val game = Game(group, target as NormalMember, user)
    buildForwardMessage(group) {
        runBlocking(Dispatchers.IO) {
            game.hint.forEach { func ->
                launch { add(bot, func.invoke()) }
            }
        }
    }.sendTo(group)
}
```

完整代码(会导致出错的代码并没有提交上去)

https://github.com/4o4E/GuessGroupFriends/blob/main/src/main/kotlin/Command.kt

**Comment by Him188** [comment]
`sendTo` 定义：
```kotlin
/**
 * 将 [this] 发送给指定联系人
 */
@JvmSynthetic
@Suppress("UNCHECKED_CAST")
public suspend inline fun <C : Contact> Message.sendTo(contact: C): MessageReceipt<C> =
    contact.sendMessage(this) as MessageReceipt<C>

```

所以它不可能出现你所描述的问题，估计是你每次换 sendTo 的时候正好因为其他原因无法上传合并转发

**Comment by Him188** [comment]
```

2022-06-11 16:41:51 E/Chat Command: Exception in coroutine Plugin net.mamoe.mirai.console.chat-command of Chat Command
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[Dispatchers.Default, Continuation at net.mamoe.mirai.internal.network.highway.Highway$uploadResourceBdh$$inlined$tryServersUpload$1.invokeSuspend(Highway.kt:85)@4b9243f]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
        at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader 'app')
        at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:147)
        at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        ... 4 more

```

```
Caused by: java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.message.MessageReceipt (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.message.MessageReceipt are in unnamed module of loader 'app')
        at GuessGroupFriends-1.0.0.mirai2.jar//org.fenglin.Command.test(Command.kt:281)
        ... 27 more
```

感觉还是 Kotlin 协程库的问题

**Comment by Karlatemp** [comment]
```kotlin
Caused by: java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.message.MessageReceipt (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.message.MessageReceipt are in unnamed module of loader 'app')
        at GuessGroupFriends-1.0.0.mirai2.jar//org.fenglin.Command.test(Command.kt:281)
        ... 27 more
```
这应该是 kt 编译器的问题. inline suspend fun 被错误处理了. 你可以尝试将 kt 插件版本更换至 `1.6.21` 试试

**Comment by 4o4E** [comment]
> ```kotlin
> Caused by: java.lang.ClassCastException: class kotlin.coroutines.intrinsics.CoroutineSingletons cannot be cast to class net.mamoe.mirai.message.MessageReceipt (kotlin.coroutines.intrinsics.CoroutineSingletons and net.mamoe.mirai.message.MessageReceipt are in unnamed module of loader 'app')
>         at GuessGroupFriends-1.0.0.mirai2.jar//org.fenglin.Command.test(Command.kt:281)
>         ... 27 more
> ```
> 
> 这应该是 kt 编译器的问题. inline suspend fun 被错误处理了. 你可以尝试将 kt 插件版本更换至 `1.6.21` 试试

build.gradle.kts中设置的kotlin插件版本就是1.6.21

https://github.com/4o4E/GuessGroupFriends/blob/5fb180f921b50b226d3e953a3ab4323c2053a31b/build.gradle.kts#L2

**Comment by Him188** [comment]
也有可能是协程库问题，它总之应该不是 sendTo 或 mirai 的问题
