### ISSUE TITLE
加载群成员失败

### ISSUE THREAD

**Issue by redjs** [mamoe/mirai#209]
1.5.1，如题，没加任何插件，在bot加入了一个新群聊便开始报这个错。
重复Send done: friendlist . GetTroopMemberL istReq
提示拉取失败，原因是加载太频繁，尝试热加载
能够给好友发消息，但无法给加入的新群聊发消息以及无法监听新群聊的消息，提示不存在该群。
会一直尝试重复加载群成员，然后报错。
以下是报错:
13:41:20 [INFO] [Bot Login] login...
 13:41:37 [INFO] [BOT 2790882554] Logging in...
 13:41:37 [INFO] [NETWORK] Connected to server 114.221.144.22:8080
 13:41:38 [INFO] [NETWORK] Send done: wtlogin.login
 13:41:38 [INFO] [NETWORK] Event: LoginPacketResponse.Success
 13:41:38 [INFO] [NETWORK] Login successful
 13:41:39 [INFO] [NETWORK] Send done: StatSvc.register
 13:41:39 [INFO] [NETWORK] Event: Response(StatSvc.register)
 13:41:39 [INFO] [NETWORK] 开始加载好友信息
 13:41:39 [INFO] [NETWORK] 开始加载群组列表与群成员列表
 13:41:40 [INFO] [NETWORK] Send done: friendlist.getFriendGroupList
 13:41:40 [INFO] [NETWORK] Send done: friendlist.GetTroopListReqV2
 13:41:40 [INFO] [NETWORK] Event: FriendList.GetFriendGroupList.Response
 13:41:40 [INFO] [NETWORK] 群组列表与群成员加载完成, 共 2个
 13:41:40 [INFO] [NETWORK] Event: FriendList.GetFriendGroupList.Response
 13:41:40 [INFO] [NETWORK] 正在加载好友列表 3/3
 13:41:40 [INFO] [NETWORK] 好友列表加载完成, 共 3个
 13:41:40 [INFO] [NETWORK] Send done: OidbSvc.0x88d_7
 13:41:40 [INFO] [NETWORK] Send done: OidbSvc.0x88d_7
 13:41:40 [INFO] [NETWORK] Event: net.mamoe.mirai.qqandroid.network.protocol.packet.chat.GroupInfoImpl@14856fb
 13:41:40 [INFO] [NETWORK] Event: net.mamoe.mirai.qqandroid.network.protocol.packet.chat.GroupInfoImpl@1ac8344
 13:41:40 [INFO] [NETWORK] Send done: friendlist.GetTroopMemberListReq
 13:41:40 [INFO] [NETWORK] Send done: friendlist.GetTroopMemberListReq
 13:41:41 [INFO] [NETWORK] Event: FriendList.GetTroopMemberList.Response
 13:41:42 [INFO] [NETWORK] Received commandName: ConfigPushSvc.PushDomain
 13:41:43 [INFO] [NETWORK] Send done: friendlist.GetTroopMemberListReq
 13:41:47 [INFO] [NETWORK] Send done: OidbSvc.0x88d_7
 13:41:47 [INFO] [NETWORK] Event: net.mamoe.mirai.qqandroid.network.protocol.packet.chat.GroupInfoImpl@86e254
 13:41:47 [INFO] [NETWORK] Send done: friendlist.GetTroopMemberListReq
 13:41:48 [INFO] [NETWORK] Event: FriendList.GetTroopMemberList.Response
 13:41:50 [INFO] [NETWORK] Send done: friendlist.GetTroopMemberListReq
 13:41:51 [INFO] [NETWORK] Event: FriendList.GetTroopMemberList.Response
 13:41:53 [INFO] [NETWORK] Send done: OidbSvc.0x88d_7
 13:41:53 [INFO] [NETWORK] Event: net.mamoe.mirai.qqandroid.network.protocol.packet.chat.GroupInfoImpl@1cf554d
 13:41:53 [INFO] [NETWORK] Send done: friendlist.GetTroopMemberListReq
 13:41:54 [INFO] [NETWORK] Event: FriendList.GetTroopMemberList.Response
 13:41:56 [INFO] [NETWORK] Send done: friendlist.GetTroopMemberListReq
 13:41:58 [INFO] [NETWORK] Event: FriendList.GetTroopMemberList.Response
 13:41:59 [INFO] [NETWORK] 群781446257的列表拉取失败, 一段时间后将会重试
 13:41:59 [INFO] [NETWORK ERROR] net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$TimeoutException: timeout receiving response of friendlist.GetTroopMemberListReq
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$6.invokeSuspend(QQAndroidBotNetworkHandler.kt:617)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

 13:41:59 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 13:42:00 [INFO] [NETWORK] Event: MessageSvc.PbGetMsg.GetMsgSuccess(messages=<Iterable>))
 13:42:01 [INFO] [NETWORK] Event: FriendList.GetTroopMemberList.Response
 13:42:03 [INFO] [BOT 2790882554] Init failed. Retrying in 3s...
 13:42:03 [INFO] [NETWORK] 开始加载好友信息
 13:42:03 [INFO] [NETWORK] 无法加载好友列表
 13:42:03 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: bot is dead therefore can't send any packet
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:595)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2$4$1$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:220)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2$4$1$1.invoke(QQAndroidBotNetworkHandler.kt)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2$4$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:258)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

 13:42:03 [INFO] [NETWORK] 稍后重试加载好友列表
 13:42:03 [INFO] [NETWORK] 开始加载群组列表与群成员列表
 13:42:03 [INFO] [NETWORK] 加载组信息失败|一般这是由于加载过于频繁导致/将以热加载方式加 载群列表
 13:42:03 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: bot is dead therefore can't send any packet
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:595)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.sendAndExpect$default(QQAndroidBotNetworkHandler.kt:591)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2$4$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:265)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

 13:42:03 [INFO] [NETWORK ERROR] java.util.NoSuchElementException: No such group 781446257 for bot 2790882554
        at net.mamoe.mirai.Bot.getGroup(Bot.kt:117)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$PbPushGroupMsg.decode(OnlinePush.kt:80)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:468)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:341)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        Suppressed: java.lang.IllegalStateException: bot is dead therefore can't send any packet
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.sendWithoutExpect(QQAndroidBotNetworkHandler.kt:576)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2$5.invokeSuspend(QQAndroidBotNetworkHandler.kt:333)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2$5.invoke(QQAndroidBotNetworkHandler.kt)
                at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
                at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:111)
                at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:74)
                at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:325)
                ... 5 more

 13:42:03 [INFO] [BOT 2790882554] cannot init. some features may be affected
 13:42:03 [INFO] [BOT 2790882554] Login successful
 13:42:03 [INFO] [Command] 2790882554 login successes
 13:42:04 [INFO] [NETWORK] Event: FriendList.GetTroopMemberList.Response
 13:42:04 [INFO] [NETWORK ERROR] java.util.concurrent.CancellationException: re-init
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:194)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$init$2.invoke(QQAndroidBotNetworkHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:177)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.init(QQAndroidBotNetworkHandler.kt:190)
        at net.mamoe.mirai.BotImpl$reinitializeNetworkHandler$3.invokeSuspend(BotImpl.kt:156)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Him188** [comment]
原因是速度太快，服务器拒绝处理。
已增加重试和分块处理
