### ISSUE TITLE
通过maven引入mirai但是ktor从1.5.4升级到ktor2.0.2后出现错误

### ISSUE THREAD

**Issue by 2237099022** [mamoe/mirai#2096]
### 问题描述

在ktor中通过maven引入mirai
但是ktor从1.5.4升级到ktor2.0.2后出现错误

### 复现

在ktor中通过maven引入mirai
但是ktor从1.5.4升级到ktor2.0.2后出现错误

### mirai-core 版本

2.11.1

### bot-protocol

ANDROID_PAD

### 其他组件版本

<ktor_version>2.0.2</ktor_version>
<kotlin.code.style>official</kotlin.code.style>
<kotlin_version>1.7.0</kotlin_version>
<logback_version>1.2.3</logback_version>

<jvmTarget>1.8</jvmTarget>

### 系统日志

```text
D:\Tools\Java11\jdk-11.0.11\bin\java.exe -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:57660,suspend=y,server=n -javaagent:D:/Tools/maven-repository/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.6.1/kotlinx-coroutines-core-jvm-1.6.1.jar -javaagent:D:\Download\01\ideaIU_2021.2.3_64bit_Portable\ideaIU_2021.2.3_64bit_Portable\plugins\java\lib\rt\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath D:\Project\demo\ktor-sample4\target\classes;D:\Tools\maven-repository\io\ktor\ktor-server-core-jvm\2.0.2\ktor-server-core-jvm-2.0.2.jar;D:\Tools\maven-repository\io\ktor\ktor-utils-jvm\2.0.2\ktor-utils-jvm-2.0.2.jar;D:\Tools\maven-repository\io\ktor\ktor-io-jvm\2.0.2\ktor-io-jvm-2.0.2.jar;D:\Tools\maven-repository\io\ktor\ktor-http-jvm\2.0.2\ktor-http-jvm-2.0.2.jar;D:\Tools\maven-repository\io\ktor\ktor-serialization-jvm\2.0.2\ktor-serialization-jvm-2.0.2.jar;D:\Tools\maven-repository\io\ktor\ktor-websockets-jvm\2.0.2\ktor-websockets-jvm-2.0.2.jar;D:\Tools\maven-repository\io\ktor\ktor-events-jvm\2.0.2\ktor-events-jvm-2.0.2.jar;D:\Tools\maven-repository\org\jetbrains\kotlin\kotlin-reflect\1.6.21\kotlin-reflect-1.6.21.jar;D:\Tools\maven-repository\org\jetbrains\kotlin\kotlin-stdlib\1.6.21\kotlin-stdlib-1.6.21.jar;D:\Tools\maven-repository\org\jetbrains\kotlin\kotlin-stdlib-jdk7\1.6.21\kotlin-stdlib-jdk7-1.6.21.jar;D:\Tools\maven-repository\org\jetbrains\kotlin\kotlin-stdlib-jdk8\1.6.21\kotlin-stdlib-jdk8-1.6.21.jar;D:\Tools\maven-repository\org\jetbrains\kotlinx\kotlinx-coroutines-jdk8\1.6.1\kotlinx-coroutines-jdk8-1.6.1.jar;D:\Tools\maven-repository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;D:\Tools\maven-repository\com\typesafe\config\1.4.1\config-1.4.1.jar;D:\Tools\maven-repository\org\jetbrains\kotlinx\kotlinx-coroutines-core-jvm\1.6.1\kotlinx-coroutines-core-jvm-1.6.1.jar;D:\Tools\maven-repository\org\jetbrains\kotlin\kotlin-stdlib-common\1.6.21\kotlin-stdlib-common-1.6.21.jar;D:\Tools\maven-repository\org\fusesource\jansi\jansi\2.4.0\jansi-2.4.0.jar;D:\Tools\maven-repository\io\ktor\ktor-server-tomcat-jvm\2.0.2\ktor-server-tomcat-jvm-2.0.2.jar;D:\Tools\maven-repository\io\ktor\ktor-server-host-common-jvm\2.0.2\ktor-server-host-common-jvm-2.0.2.jar;D:\Tools\maven-repository\io\ktor\ktor-http-cio-jvm\2.0.2\ktor-http-cio-jvm-2.0.2.jar;D:\Tools\maven-repository\io\ktor\ktor-network-jvm\2.0.2\ktor-network-jvm-2.0.2.jar;D:\Tools\maven-repository\io\ktor\ktor-server-servlet-jvm\2.0.2\ktor-server-servlet-jvm-2.0.2.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-catalina\9.0.62\tomcat-catalina-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-servlet-api\9.0.62\tomcat-servlet-api-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-jsp-api\9.0.62\tomcat-jsp-api-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-el-api\9.0.62\tomcat-el-api-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-juli\9.0.62\tomcat-juli-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-annotations-api\9.0.62\tomcat-annotations-api-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-api\9.0.62\tomcat-api-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-jni\9.0.62\tomcat-jni-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-coyote\9.0.62\tomcat-coyote-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-util\9.0.62\tomcat-util-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-util-scan\9.0.62\tomcat-util-scan-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\tomcat-jaspic-api\9.0.62\tomcat-jaspic-api-9.0.62.jar;D:\Tools\maven-repository\org\apache\tomcat\embed\tomcat-embed-core\9.0.62\tomcat-embed-core-9.0.62.jar;D:\Tools\maven-repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;D:\Tools\maven-repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;D:\Tools\maven-repository\org\jetbrains\kotlinx\kotlinx-coroutines-slf4j\1.6.1\kotlinx-coroutines-slf4j-1.6.1.jar;D:\Tools\maven-repository\io\ktor\ktor-websocket-serialization-jvm\2.0.2\ktor-websocket-serialization-jvm-2.0.2.jar;D:\Tools\maven-repository\io\ktor\ktor-client-core-jvm\2.0.2\ktor-client-core-jvm-2.0.2.jar;D:\Tools\maven-repository\net\mamoe\mirai-core-jvm\2.11.1\mirai-core-jvm-2.11.1.jar;D:\Tools\maven-repository\net\mamoe\mirai-core-api-jvm\2.11.1\mirai-core-api-jvm-2.11.1.jar;D:\Tools\maven-repository\io\ktor\ktor-client-okhttp\1.6.7\ktor-client-okhttp-1.6.7.jar;D:\Tools\maven-repository\com\squareup\okhttp3\okhttp\4.9.2\okhttp-4.9.2.jar;D:\Tools\maven-repository\com\squareup\okio\okio\2.8.0\okio-2.8.0.jar;D:\Tools\maven-repository\net\mamoe\mirai-console-compiler-annotations-jvm\2.11.1\mirai-console-compiler-annotations-jvm-2.11.1.jar;D:\Tools\maven-repository\org\jetbrains\annotations\19.0.0\annotations-19.0.0.jar;D:\Tools\maven-repository\org\jetbrains\kotlinx\kotlinx-serialization-core-jvm\1.3.2\kotlinx-serialization-core-jvm-1.3.2.jar;D:\Tools\maven-repository\org\jetbrains\kotlinx\kotlinx-serialization-json-jvm\1.3.2\kotlinx-serialization-json-jvm-1.3.2.jar;D:\Tools\maven-repository\me\him188\kotlin-jvm-blocking-bridge-runtime-jvm\2.0.0-162.1\kotlin-jvm-blocking-bridge-runtime-jvm-2.0.0-162.1.jar;D:\Tools\maven-repository\net\mamoe\mirai-core-utils-jvm\2.11.1\mirai-core-utils-jvm-2.11.1.jar;D:\Tools\maven-repository\org\jetbrains\kotlinx\kotlinx-serialization-protobuf-jvm\1.3.2\kotlinx-serialization-protobuf-jvm-1.3.2.jar;D:\Tools\maven-repository\org\jetbrains\kotlinx\atomicfu-jvm\0.17.2\atomicfu-jvm-0.17.2.jar;D:\Tools\maven-repository\io\netty\netty-all\4.1.63.Final\netty-all-4.1.63.Final.jar;D:\Tools\maven-repository\org\apache\logging\log4j\log4j-api\2.17.2\log4j-api-2.17.2.jar;D:\Tools\maven-repository\org\bouncycastle\bcprov-jdk15on\1.64\bcprov-jdk15on-1.64.jar;D:\Tools\maven-repository\org\jetbrains\kotlinx\kotlinx-io-jvm\0.1.16\kotlinx-io-jvm-0.1.16.jar;D:\Tools\maven-repository\org\jetbrains\kotlinx\kotlinx-io\0.1.16\kotlinx-io-0.1.16.jar;D:\Download\01\ideaIU_2021.2.3_64bit_Portable\ideaIU_2021.2.3_64bit_Portable\lib\idea_rt.jar com.example.ApplicationKt
已连接到目标 VM, 地址: ''127.0.0.1:57660'，传输: '套接字''
2022-06-14 15:36:55.715 [main] INFO  ktor.application - Autoreload is disabled because the development mode is off.
2022-06-14 15:36:55.764 [main] INFO  ktor.application - Application started in 0.803 seconds.
6月 14, 2022 3:36:56 下午 org.apache.coyote.AbstractProtocol init
信息: Initializing ProtocolHandler ["http-nio-8080"]
6月 14, 2022 3:36:56 下午 org.apache.catalina.core.StandardService startInternal
信息: Starting service [Tomcat]
6月 14, 2022 3:36:56 下午 org.apache.catalina.core.StandardEngine startInternal
信息: Starting Servlet engine: [Apache Tomcat/9.0.62]
6月 14, 2022 3:36:56 下午 org.apache.catalina.util.SessionIdGeneratorBase createSecureRandom
警告: Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [458] milliseconds.
6月 14, 2022 3:36:56 下午 org.apache.coyote.AbstractProtocol start
信息: Starting ProtocolHandler ["http-nio-8080"]
2022-06-14 15:36:56.907 [DefaultDispatcher-worker-1] INFO  ktor.application - Responding at http://0.0.0.0:8080
2022-06-14 15:37:00 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2022-06-14 15:37:00 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2022-06-14 15:37:00.810 [DefaultDispatcher-worker-1] ERROR ktor.application - Unhandled: GET - /loginbot
java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:270)
	at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:360)
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:354)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:42)
	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:115)
	at net.mamoe.mirai.BotFactory.newBot(BotFactory.kt:67)
	at com.example.qbot.LoginBotKt$botRouting$1$1.invokeSuspend(LoginBot.kt:29)
	at com.example.qbot.LoginBotKt$botRouting$1$1.invoke(LoginBot.kt)
	at com.example.qbot.LoginBotKt$botRouting$1$1.invoke(LoginBot.kt)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
	at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:101)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt$initContextInDebugMode$2.invokeSuspend(ContextUtils.kt:20)
	at io.ktor.util.debug.ContextUtilsKt$initContextInDebugMode$2.invoke(ContextUtils.kt)
	at io.ktor.util.debug.ContextUtilsKt$initContextInDebugMode$2.invoke(ContextUtils.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:20)
	at io.ktor.server.routing.Routing.executeResult(Routing.kt:174)
	at io.ktor.server.routing.Routing.interceptor(Routing.kt:49)
	at io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:124)
	at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
	at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:122)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
	at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:101)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt$initContextInDebugMode$2.invokeSuspend(ContextUtils.kt:20)
	at io.ktor.util.debug.ContextUtilsKt$initContextInDebugMode$2.invoke(ContextUtils.kt)
	at io.ktor.util.debug.ContextUtilsKt$initContextInDebugMode$2.invoke(ContextUtils.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:20)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:118)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:101)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at io.ktor.server.servlet.KtorServlet$asyncService$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
	at io.ktor.server.servlet.KtorServlet$asyncService$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.server.servlet.KtorServlet$asyncService$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
	at io.ktor.util.debug.ContextUtilsKt$initContextInDebugMode$2.invokeSuspend(ContextUtils.kt:20)
	at io.ktor.util.debug.ContextUtilsKt$initContextInDebugMode$2.invoke(ContextUtils.kt)
	at io.ktor.util.debug.ContextUtilsKt$initContextInDebugMode$2.invoke(ContextUtils.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:20)
	at io.ktor.server.servlet.KtorServlet$asyncService$1.invokeSuspend(KtorServlet.kt:156)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:270)
	at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:360)
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:354)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:42)
	at net.mamoe.mirai.internal.message.MessageSerializersImpl.getSerializersModule(MessageSerializersImpl.kt:196)
	at net.mamoe.mirai.internal.message.MessageSerializersImpl.registerSerializer(MessageSerializersImpl.kt:202)
	at net.mamoe.mirai.message.MessageSerializers$INSTANCE.registerSerializer(MessageSerializers.kt)
	at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt:73)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
	... 78 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/ktor/client/features/HttpTimeout
	at net.mamoe.mirai.internal.MiraiImpl$Http$1.invoke(MiraiImpl.kt:145)
	at net.mamoe.mirai.internal.MiraiImpl$Http$1.invoke(MiraiImpl.kt:144)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:40)
	at net.mamoe.mirai.internal.MiraiImpl.<init>(MiraiImpl.kt:144)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
	... 93 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.ktor.client.features.HttpTimeout
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 102 common frames omitted
```

**Comment by cssxsh** [comment]
mirai-core 的 ktor 版本是 1.6.7
ktor1.0 到 ktor2.0 有很多 abi 变动

**Comment by Him188** [comment]
@Karlatemp 是不是应该已经修复了？

**Comment by cssxsh** [comment]
> @Karlatemp 是不是应该已经修复了？

看这个样子，他是 mirai-core 项目吧

**Comment by 2237099022** [comment]
> > @Karlatemp 是不是应该已经修复了？
> 
> 看这个样子，他是 mirai-core 项目吧

我用的这个
<groupId>net.mamoe</groupId>
<artifactId>mirai-core-jvm</artifactId>
<version>2.11.1</version>

**Comment by Him188** [comment]
mirai使用 1.6.7，你目前只能使用这个版本。将在2.13支持使用不同版本

**Comment by 2237099022** [comment]
> mirai使用 1.6.7，你目前只能使用这个版本。将在2.13支持使用不同版本

好的 , 我已经完全明白了 , 谢谢大佬们

**Comment by Him188** [comment]
请等待问题解决后我们会关闭 issue

**Comment by 2237099022** [comment]
> 请等待问题解决后我们会关闭 issue

ok
