### ISSUE TITLE
当前登录存在安全风险，请使用常用设备或通过手机号登录

### ISSUE THREAD

**Issue by Xiaolangs** [mamoe/mirai#2117]
### 问题描述

code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=
在Android平台进行运行  滑块验证也验证了 ticket 然后就出现当前登录存在安全风险，请使用常用设备或通过手机号登录

### 复现

进行登陆的时候会跳出来滑块验证也进行了验证成功返回了

### mirai-core 版本

2.11.1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

没有

### 补充信息

E/TAG: invoke: {"result":"0","ticket":"t03gphG_kY8lh9HiLT3N0R1xLwqge86FaQS-o1LSygZnFKoVDo5viNUmL6ahq64GhQCf78QuBJit6sFdGYKG5vpB6nCxLfmtUFklIxQaV9QhOjPN_WqAo4ijlKSUL5mCDJ6LIQMTpAWp2g*","randstr":"@1Qe"}
E/TAG: onSolveSliderCaptcha: t03gphG_kY8lh9HiLT3N0R1xLwqge86FaQS-o1LSygZnFKoVDo5viNUmL6ahq64GhQCf78QuBJit6sFdGYKG5vpB6nCxLfmtUFklIxQaV9QhOjPN_WqAo4ijlKSUL5mCDJ6LIQMTpAWp2g*
V/Net 869692041: Recv: wtlogin.login
V/Net 869692041: Send: wtlogin.login
V/Net 869692041: Recv: wtlogin.login
W/Net 869692041: null
    net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(869692041), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by Him188** [comment]
这个问题没有办法解决，除非实现手机号登录。手机号登录是 #1875
