### ISSUE TITLE
Console 插件在 2022.2 Beta 和 EAP 中都存在错误

### ISSUE THREAD

**Issue by minoism** [mamoe/mirai#2124]
### 问题描述

<img width="936" alt="image" src="https://user-images.githubusercontent.com/58068445/176653103-e321c3e1-039f-48d6-b787-3b09f8549886.png">
<img width="936" alt="image" src="https://user-images.githubusercontent.com/58068445/176653581-a30b332d-5877-438d-af7e-09d0766fd12f.png">

### 复现

安装插件后打开任意 kotlin 项目，不是 mirai 项目也会发生这个报错。~~而且似乎会影响高亮分析~~

确认会影响高亮，禁用插件后问题消失，补充一下: EAP 已经第七个版本了，这应该也会影响到正式版 IDEA 

### mirai-core 版本

*

### bot-protocol

ANDROID_PHONE

### 补充信息

```
java.lang.NoSuchFieldError: STRING
	at net.mamoe.mirai.console.compiler.common.diagnostics.MiraiConsoleErrorsRendering.<clinit>(MiraiConsoleErrorsRendering.kt:43)
	at net.mamoe.mirai.console.compiler.common.diagnostics.MiraiConsoleErrors.<clinit>(MiraiConsoleErrors.kt:101)
	at net.mamoe.mirai.console.intellij.QuickFixRegistrar.registerQuickFixes(QuickFixRegistrar.kt:31)
	at org.jetbrains.kotlin.idea.quickfix.QuickFixes.<init>(QuickFixes.kt:20)
    ...
```

```
java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.console.compiler.common.diagnostics.MiraiConsoleErrors
	at net.mamoe.mirai.console.intellij.QuickFixRegistrar.registerQuickFixes(QuickFixRegistrar.kt:31)
	at org.jetbrains.kotlin.idea.quickfix.QuickFixes.<init>(QuickFixes.kt:20)
    ...
```

**Comment by Him188** [comment]
221-2.13.0-171-1 已提交 JB 审核, 支持 221-222, 过几天就可以看到了

**Comment by xtexx** [comment]
我IDEA这几天一直炸的原因找到了！
