### ISSUE TITLE
使用mirai2打包方式打包的插件出现依赖错误

### ISSUE THREAD

**Issue by AdorableParker** [mamoe/mirai#2126]
### 问题描述

插件使用了batik依赖进行图片制作，使用旧的打包方式可以正常运行，使用新打包方式打包的插件，就会出现依赖错误

### 复现

1.运行bot加载mirai2包
2.聊天命令触发调用使用了相关依赖的功能
3.程序报错

### mirai-core 版本

2.11.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-console: v2.11.0

### 补充信息

[system.log](https://github.com/mamoe/mirai/files/9029447/system.log)

**Comment by Him188** [comment]
提供 build.gradle.kts 内容

**Comment by AdorableParker** [comment]
应该是这个吧[build.gradle.kts](https://github.com/AdorableParker/nymph/blob/master/bot/build.gradle)

**Comment by Karlatemp** [comment]
这个问题很有可能在 2.12.0-RC 修了, 尝试一下 2.12.0-RC, 另外请使用 IDEA或其他工具 得到 `org.apache.xerces.jaxp.SAXParserFactoryImpl` 属于哪个 jar 包 (属于哪个依赖)

**Comment by AdorableParker** [comment]
使用`2.12.0-RC`依旧是报错
```
  16:28:19 [INFO] Verifying "net.mamoe:mirai-console" v2.12.0-RC
  16:28:20 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.12.0-RC
  16:28:21 [INFO] Verifying "net.mamoe:mirai-core-all" v2.12.0-RC
  16:28:21 [INFO] Verifying "org.itxtech:mcl-addon"
  16:28:21 [INFO] Updating "org.itxtech:mcl-addon" to v2.0.2
  16:28:22 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on"
  16:28:22 [INFO] Updating "org.bouncycastle:bcprov-jdk15on" to v1.64

...

2022-07-02 16:28:24 D/JvmPluginLoader: Maven        local: C:\Users\jetpi\.m2\repository
2022-07-02 16:28:24 D/JvmPluginLoader: Gradle cache local: C:\Users\jetpi\.gradle\caches\modules-2\files-2.1
2022-07-02 16:28:24 D/JvmPluginLoader: Remote server: [https://maven.aliyun.com/repository/public]
2022-07-02 16:28:24 V/JvmPluginLoader: Plugin shared libraries: D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-shared-libraries
2022-07-02 16:28:24 D/JvmPluginLoader: Peek D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-shared-libraries\libraries.txt in shared libraries
2022-07-02 16:28:24 D/JvmPluginLoader: Skipped D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-shared-libraries\libraries.txt because extension <txt> != jar
2022-07-02 16:28:24 V/JvmPluginLoader: Linking static shared libraries....
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\com\beust\klaxon\5.5\klaxon-5.5.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked com.beust:klaxon:jar:5.5 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\com\mayabot\mynlp\resource\mynlp-resource-coredict\1.0.0\mynlp-resource-coredict-1.0.0.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked com.mayabot.mynlp.resource:mynlp-resource-coredict:jar:1.0.0 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\com\mayabot\mynlp\resource\mynlp-resource-ner\1.0.0\mynlp-resource-ner-1.0.0.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked com.mayabot.mynlp.resource:mynlp-resource-ner:jar:1.0.0 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\com\mayabot\mynlp\resource\mynlp-resource-pinyin\1.1.0\mynlp-resource-pinyin-1.1.0.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked com.mayabot.mynlp.resource:mynlp-resource-pinyin:jar:1.1.0 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\com\mayabot\mynlp\resource\mynlp-resource-pos\1.0.0\mynlp-resource-pos-1.0.0.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked com.mayabot.mynlp.resource:mynlp-resource-pos:jar:1.0.0 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\com\mayabot\mynlp\resource\mynlp-resource-transform\1.0.0\mynlp-resource-transform-1.0.0.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked com.mayabot.mynlp.resource:mynlp-resource-transform:jar:1.0.0 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\com\mayabot\mynlp\mynlp-all\3.2.2\mynlp-all-3.2.2.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked com.mayabot.mynlp:mynlp-all:jar:3.2.2 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\com\mayabot\mynlp\mynlp\3.2.2\mynlp-3.2.2.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked com.mayabot.mynlp:mynlp:jar:3.2.2 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\commons-io\commons-io\1.3.1\commons-io-1.3.1.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked commons-io:commons-io:jar:1.3.1 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking C:\Users\jetpi\.m2\repository\commons-logging\commons-logging\1.0.4\commons-logging-1.0.4.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked commons-logging:commons-logging:jar:1.0.4 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-all\1.14\batik-all-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-all:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-anim\1.14\batik-anim-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-anim:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-awt-util\1.14\batik-awt-util-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-awt-util:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-bridge\1.14\batik-bridge-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-bridge:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-codec\1.14\batik-codec-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-codec:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-constants\1.14\batik-constants-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-constants:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-css\1.14\batik-css-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-css:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-dom\1.14\batik-dom-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-dom:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-ext\1.14\batik-ext-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-ext:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-extension\1.14\batik-extension-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-extension:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-gui-util\1.14\batik-gui-util-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-gui-util:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-gvt\1.14\batik-gvt-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-gvt:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-i18n\1.14\batik-i18n-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-i18n:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-parser\1.14\batik-parser-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-parser:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-rasterizer-ext\1.14\batik-rasterizer-ext-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-rasterizer-ext:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-rasterizer\1.14\batik-rasterizer-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-rasterizer:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-script\1.14\batik-script-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-script:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-shared-resources\1.14\batik-shared-resources-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-shared-resources:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-slideshow\1.14\batik-slideshow-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-slideshow:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-squiggle-ext\1.14\batik-squiggle-ext-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-squiggle-ext:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-squiggle\1.14\batik-squiggle-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-squiggle:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-svg-dom\1.14\batik-svg-dom-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-svg-dom:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-svgbrowser\1.14\batik-svgbrowser-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-svgbrowser:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-svggen\1.14\batik-svggen-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-svggen:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-svgpp\1.14\batik-svgpp-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-svgpp:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-svgrasterizer\1.14\batik-svgrasterizer-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-svgrasterizer:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-swing\1.14\batik-swing-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-swing:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-transcoder\1.14\batik-transcoder-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-transcoder:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-ttf2svg\1.14\batik-ttf2svg-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-ttf2svg:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-util\1.14\batik-util-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-util:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\batik-xml\1.14\batik-xml-1.14.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:batik-xml:jar:1.14 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\apache\xmlgraphics\xmlgraphics-commons\2.6\xmlgraphics-commons-2.6.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.apache.xmlgraphics:xmlgraphics-commons:jar:2.6 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\jsoup\jsoup\1.14.3\jsoup-1.14.3.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.jsoup:jsoup:jar:1.14.3 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\org\xerial\sqlite-jdbc\3.36.0.3\sqlite-jdbc-3.36.0.3.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked org.xerial:sqlite-jdbc:jar:3.36.0.3 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\xalan\serializer\2.7.2\serializer-2.7.2.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked xalan:serializer:jar:2.7.2 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\xalan\xalan\2.7.2\xalan-2.7.2.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked xalan:xalan:jar:2.7.2 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\xml-apis\xml-apis-ext\1.3.04\xml-apis-ext-1.3.04.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked xml-apis:xml-apis-ext:jar:1.3.04 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>
2022-07-02 16:28:25 V/navigatorTB: Linking D:\Program Files (x86)\MiraiProject\mcl-2.1.0\plugin-libraries\xml-apis\xml-apis\1.4.01\xml-apis-1.4.01.jar (private)
2022-07-02 16:28:25 D/navigatorTB: Linked xml-apis:xml-apis:jar:1.4.01 (private) <DynLibClassLoader{IndependentCL{bot.mirai2.jar}}>

...

2022-07-02 16:29:22 W/navigatorTB: Exception in executing command
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:337)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:86)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:69)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider org.apache.xerces.jaxp.SAXParserFactoryImpl not found
        at bot.mirai2.jar[private]//javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source)
        at bot.mirai2.jar[private]//org.apache.batik.dom.util.SAXDocumentFactory.<clinit>(SAXDocumentFactory.java:401)
        at bot.mirai2.jar//com.navigatorTB_Nymph.tool.svg.BuildSVGTool.<init>(BuildSVGTool.kt:26)
        at bot.mirai2.jar//com.navigatorTB_Nymph.miscellaneous.Dynamic.<init>(Dynamic.kt:11)
        at bot.mirai2.jar//com.navigatorTB_Nymph.command.simple.SendDynamic.main(SendDynamic.kt:47)
        at bot.mirai2.jar//com.navigatorTB_Nymph.command.simple.SendDynamic.main(SendDynamic.kt:36)
        at bot.mirai2.jar//com.navigatorTB_Nymph.command.simple.SendDynamic.main$default(SendDynamic.kt:30)
        ... 26 more
```

---

有一说一我不清楚`org.apache.xerces.jaxp.SAXParserFactoryImpl`这东西是哪来的，毕竟我代码里面相关行写的是
![image](https://user-images.githubusercontent.com/35246761/176993722-4b4d7ece-68c2-4b45-9322-c929e49f5cbe.png)

```kotlin
        val parser = XMLResourceDescriptor.getXMLParserClassName()
        val doc = SAXSVGDocumentFactory(parser).createDocument(file)
```

**Comment by Itsusinn** [comment]
此问题出现的原因可能是Java的SPI机制默认使用了当前线程的“线程上下文类加载器”

我并不清楚是什么原因，插件的生命周期相关函数（onEnable一类）默认情况下使用的类加载器无法在classpath中找到SPI实现类（自2.11起，但2.11前也存在）

https://github.com/MeowCat-Studio/mirai-message-source/blob/849e39ed84ee4853f0ff636197235ab39bd7e805/src/main/kotlin/Plugin.kt#L36-L41

可以仿照我的代码，在设定线程上下文类加载器后强制加载SPI

> 可能是由于mirai新的类加载策略
> 2.10及以前需要使用
> Thread.currentThread().contextClassLoader = Plugin::class.java.classLoader
> 2.11及以后需要使用
> Thread.currentThread().contextClassLoader = Plugin.jvmPluginClasspath.pluginClassLoader

**Comment by Karlatemp** [comment]
我需要知道 org.apache.xerces.jaxp.SAXParserFactoryImpl 到底来自哪个依赖我才能分析这个错误, 在 idea 里直接访问这个类应该能直接跳转

**Comment by AdorableParker** [comment]
指这样？
![image](https://user-images.githubusercontent.com/35246761/177034415-470d02f0-dcb0-4679-8839-be63ce55e860.png)
![image](https://user-images.githubusercontent.com/35246761/177034545-086124d1-9906-494c-84e8-d933ea51fecb.png)

**Comment by Karlatemp** [comment]
是，Ctrl＋左键点进去，我需要知道这个来自哪

**Comment by AdorableParker** [comment]
点进去就这样
![image](https://user-images.githubusercontent.com/35246761/177034635-dd5dd0b7-90ff-493f-88e6-6b6c4e27fc21.png)

**Comment by sandtechnology** [comment]
请问可以提供一下新打包方式的Jar吗？

**Comment by AdorableParker** [comment]
两种打包方式的jar都在这了
[plugin.zip](https://github.com/AdorableParker/nymph/releases/download/untagged-b3e6f193dff25beaea81/plugin.zip)

**Comment by sandtechnology** [comment]
> 两种打包方式的jar都在这了 [plugin.zip](https://github.com/AdorableParker/nymph/releases/download/untagged-b3e6f193dff25beaea81/plugin.zip)

返回404 Not found 请检查一下

**Comment by AdorableParker** [comment]
现在应该没问题了

**Comment by Karlatemp** [comment]
> for mamoe
> 
> java.lang.ClassCastException: class com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl cannot be cast to class javax.xml.parsers.SAXParserFactory (com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl is in module java.xml of loader 'bootstrap'; javax.xml.parsers.SAXParserFactory is in unnamed module of loader 'ktor1-dev.mirai2.jar[private]' @5578be42)
> java.lang.ClassCastException: class com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl cannot be cast to class javax.xml.parsers.SAXParserFactory (com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl is in module java.xml of loader 'bootstrap'; javax.xml.parsers.SAXParserFactory is in unnamed module of loader 'ktor1-dev.mirai2.jar[private]' @5578be42)
> at ktor1-dev.mirai2.jar[private]//javax.xml.parsers.SAXParserFactory.newInstance(Unknown Source)
