### ISSUE TITLE
发送群消息错误 46

### ISSUE THREAD

**Issue by Pika-Lee** [mamoe/mirai#2127]
### 问题描述

今天bot被冻结了一次，解冻后登陆发现无法正常发送消息。会抛出exception异常
![QQ图片20220701224426](https://user-images.githubusercontent.com/23114990/176916929-d8b29b25-3325-4b52-8bfe-5dd91848c801.png)

### 复现

发送一条机器人指令，bot回复时报错，100%复现，尝试更换登陆协议后仍然无法发送消息。

### mirai-core 版本

2.10.0

### bot-protocol

ANDROID_WATCH

### 其他组件版本

mirai-native：2.0.0

### 系统日志

```text
[0m2022-07-01 22:37:25 V/Net 1845605751: Loading server list from cache.[0m
[92m2022-07-01 22:37:25 I/Net 1845605751: Server list: 113.96.18.168:14000, 180.101.246.123:14000, 42.81.176.211:80, 180.109.192.45:443, 120.232.67.218:443, msfwifi.3g.qq.com:8080, 14.22.9.53:8080, 157.148.42.147:80.[0m
[92m2022-07-01 22:37:26 I/Net 1845605751: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[31m2022-07-01 22:37:26 E/Net 1845605751: Failed to fetch ECDH public key from server, using default key instead
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at io.ktor.utils.io.bits.MemoryJvmKt.sliceSafe(MemoryJvm.kt:211)
	at io.ktor.utils.io.bits.Memory.slice-SK3TCg8(MemoryJvm.kt:47)
	at io.ktor.utils.io.charsets.CharsetJVMKt.encodeImpl(CharsetJVM.kt:356)
	at io.ktor.utils.io.charsets.EncodingKt.encodeToImpl(Encoding.kt:204)
	at io.ktor.utils.io.charsets.EncodingKt.encode(Encoding.kt:62)
	at io.ktor.utils.io.charsets.EncodingKt.encode$default(Encoding.kt:57)
	at io.ktor.http.CodecsKt.encodeURLParameter(Codecs.kt:123)
	at io.ktor.http.HttpUrlEncodedKt$formUrlEncodeTo$1.invoke(HttpUrlEncoded.kt:68)
	at io.ktor.http.HttpUrlEncodedKt$formUrlEncodeTo$1.invoke(HttpUrlEncoded.kt:67)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3347)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo$default(_Collections.kt:3341)
	at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:67)
	at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:108)
	at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:90)
	at io.ktor.http.URLUtilsKt.appendUrlFullPath(URLUtils.kt:101)
	at io.ktor.http.URLUtilsKt.getFullPath(URLUtils.kt:79)
	at io.ktor.http.Url.toString(URLBuilder.kt:169)
	at io.ktor.client.engine.okhttp.OkHttpEngineKt.convertToOkHttpRequest(OkHttpEngine.kt:183)
	at io.ktor.client.engine.okhttp.OkHttpEngineKt.access$convertToOkHttpRequest(OkHttpEngine.kt:1)
	at io.ktor.client.engine.okhttp.OkHttpEngine.execute(OkHttpEngine.kt:71)
	at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:85)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: wtlogin.exchange_emp[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: wtlogin.exchange_emp[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: StatSvc.register(online)[0m
[92m2022-07-01 22:37:26 I/Net 1845605751: Server time updated, serverTime: 1656686246, diff: 0ms=0.0s[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: StatSvc.register[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Loading BdhSession from cache file[0m
[92m2022-07-01 22:37:26 I/Net 1845605751: Syncing friend message history...[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[92m2022-07-01 22:37:26 I/Net 1845605751: Start loading stranger list...[0m
[92m2022-07-01 22:37:26 I/Net 1845605751: Start loading friend list...[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[92m2022-07-01 22:37:26 I/Net 1845605751: Start loading group list...[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: OidbSvc.0x496[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: OidbSvc.0x5d2_0[0m
[92m2022-07-01 22:37:26 I/Net 1845605751: Successfully loaded stranger list: 15 in total[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: friendlist.GetTroopListReqV2[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: StatSvc.GetDevLoginInfo[0m
[92m2022-07-01 22:37:26 I/Net 1845605751: Online OtherClients: mirai(MOBILE), 172_17_0_9(WINDOWS)[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: friendlist.getFriendGroupList[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Loading friend list: 87/87[0m
[92m2022-07-01 22:37:26 I/Net 1845605751: Successfully loaded friend list: 87 in total[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[92m2022-07-01 22:37:26 I/Net 1845605751: Syncing friend message history: Success.[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:26 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:27 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:27 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:27 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:27 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:27 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:27 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:27 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:27 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:28 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:28 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:28 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:28 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:28 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:28 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:29 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:29 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:29 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:29 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:29 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-01 22:37:29 V/Net 1845605751: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-01 22:37:29 V/Net 1845605751: Saving bdh session to cache[0m
[0m2022-07-01 22:37:29 V/Net 1845605751: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2022-07-01 22:37:29 V/Net 1845605751: Recv: ConfigPushSvc.PushReq[0m
[0m2022-07-01 22:37:29 V/Net 1845605751: Recv: friendlist.GetTroopMemberListReq[0m
[92m2022-07-01 22:37:29 I/Net 1845605751: Successfully loaded group list: 9 in total.[0m
[92m2022-07-01 22:37:29 I/Net 1845605751: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2022-07-01 22:37:29 I/Net 1845605751: Scheduled key refresh in 23h 55min 0.0s.[0m
[0m2022-07-01 22:38:41 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:38:41 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
[0m2022-07-01 22:38:43 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:38:43 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
[0m2022-07-01 22:38:47 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:38:47 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
[0m2022-07-01 22:40:00 V/Net 1845605751: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-07-01 22:40:00 V/Net 1845605751: Recv: MessageSvc.PbSendMsg[0m
[0m2022-07-01 22:40:09 V/Net 1845605751: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-07-01 22:40:09 V/Net 1845605751: Recv: MessageSvc.PbSendMsg[0m
[0m2022-07-01 22:40:16 V/Net 1845605751: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-07-01 22:40:16 V/Net 1845605751: Recv: MessageSvc.PbSendMsg[0m
[0m2022-07-01 22:40:28 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:40:28 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
[0m2022-07-01 22:40:41 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:40:41 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
[0m2022-07-01 22:40:52 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:40:52 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
[0m2022-07-01 22:41:00 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:41:00 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
[0m2022-07-01 22:41:46 V/Net 1845605751: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-07-01 22:41:46 V/Net 1845605751: Recv: MessageSvc.PbSendMsg[0m
[0m2022-07-01 22:41:51 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:41:51 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
[0m2022-07-01 22:42:15 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:42:16 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
[0m2022-07-01 22:42:18 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:42:19 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
[0m2022-07-01 22:42:29 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:42:29 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
[0m2022-07-01 22:42:37 V/Net 1845605751: Send: SummaryCard.ReqSummaryCard(SummaryCard.ReqSummaryCard)[0m
[0m2022-07-01 22:42:37 V/Net 1845605751: Recv: SummaryCard.ReqSummaryCard[0m
```

### 补充信息

试着用电脑QQ登陆bot账号手动发消息，发现群聊消息发出后无法看到（疑似被屏蔽），私聊正常。

之前遇到被屏蔽的情况，mirai后台没有报错提示，这次bot每发一条消息都会报错，所以来反馈下。

**Comment by cssxsh** [comment]
`java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;`

或许你该试试使用 jdk 11+

**Comment by AdorableParker** [comment]
同样的问题，但是并没有被封号，而是通过了一个群邀请事件后出现的群消息无法发送，日志报错提示是这个
```log
java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
        at net.mamoe.mirai.internal.contact.SendMessageHandler.sendMessagePacket(SendMessageHandler.kt:191)
        at net.mamoe.mirai.internal.contact.SendMessageHandler$sendMessagePacket$1.invokeSuspend(SendMessageHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
---
严格来讲是无法发送任何群消息，但是私聊环境下是完全正常的
文件是网络日志
[2022-07-02.log](https://github.com/mamoe/mirai/files/9032278/2022-07-02.log)

**Comment by AdorableParker** [comment]
我估计百分之九十九是腾讯那边的原因

**Comment by LambdaYH** [comment]
遇到了同样问题，我手q登录账号也无法发送群消息。（虽然我是用gocq的）基本上应该是腾讯问题

**Comment by AdorableParker** [comment]
今天用TIM登录了bot的账号，然后发现是腾讯专门开了一个封号类别
![image](https://user-images.githubusercontent.com/35246761/177022799-a25383b1-adb0-4c2f-a564-d895538cbf17.png)

**Comment by Pika-Lee** [comment]
补充一张图，被限制后在电脑端用bot发消息，收到了一句官方提示
![QQ图片20220703174310](https://user-images.githubusercontent.com/23114990/177034128-043c6c08-1352-4c3d-b200-2036ad5cad3e.png)

**Comment by Pika-Lee** [comment]
万能的群友给了一个解决方式，大家可以试试↓
遇到发送群消息已暂停使用的这种情况，可尝试的解决方案：打开官方手机QQ app，登录当前框架QQ后，在手机QQ聊天界面，打开链接：https://accounts.qq.com/safe/message/unlock?lock_info=5_2

**Comment by AdorableParker** [comment]
是可以解封，但是很快又会被封，我怀疑是有什么特征被盯上了

**Comment by SatellaPoi** [comment]
就是特征识别吧，我这解了2个小时就又毙了

**Comment by SWERecker** [comment]
同样情况，以前是被封登不上，现在能登上不能在群里发言，打开上面的链接解封后，过一会又被封了

**Comment by RexQian** [comment]
从昨天开始出现部分群信息会发不出来  像是被应用了严格的关键字屏蔽

**Comment by enchantedyou** [comment]
请问有什么解决办法吗

**Comment by hengkx** [comment]
我也遇到了 有解吗

**Comment by Nekoer** [comment]
用https://accounts.qq.com/safe/message/unlock?lock_info=5_5
不需要人脸直接滑块

**Comment by yefu24324** [comment]
> 用https://accounts.qq.com/safe/message/unlock?lock_info=5_5 不需要人脸直接滑块

这个解决了我遇到的问题, 就是bot风控了

**Comment by Shuangcheng-Ni** [comment]
> 用https://accounts.qq.com/safe/message/unlock?lock_info=5_5 不需要人脸直接滑块

我用这个url验证了一下，再次登录mcl就需要重新输入ticket，获取ticket并输入后mcl控制台报错如下，最终无法登录。

2022-08-12 23:08:50 W/Net 2647341135: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2647341135), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2647341135), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Shuangcheng-Ni** [comment]
> 用https://accounts.qq.com/safe/message/unlock?lock_info=5_5 不需要人脸直接滑块

我用这个url验证了一下，再次登录mcl就需要重新输入ticket，获取ticket并输入后mcl控制台报错如下，最终无法登录。

2022-08-12 23:08:50 W/Net 2647341135: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2647341135), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2647341135), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Shuangcheng-Ni** [comment]
> 用https://accounts.qq.com/safe/message/unlock?lock_info=5_5 不需要人脸直接滑块

成功了！非常感谢！

**Comment by Him188** [comment]
在遇到错误 46 时将会提示原因和解冻方案
