### ISSUE TITLE
发送图片失败

### ISSUE THREAD

**Issue by FxRayHughes** [mamoe/mirai#2139]
### 问题描述

2022-07-07 15:47:03 E/插件示例: Exception in coroutine Plugin ray.mintcat.shengyiwu of 插件示例
java.lang.IllegalArgumentException: Unsupported image type (test.png) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByByteArray@25b9e599, considering use gif/png/bmp/jpg format. image header: 89 50 4E 47 0D 0A 1A 0A 00 00 00 0D 49 48 44 52 00 00 02 81 00 00 01 FE 08 06 00 00 00 E3
        at net.mamoe.mirai.internal.message.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:160)
        at net.mamoe.mirai.internal.contact.GroupImpl$uploadImage$lambda-19$$inlined$runBIO$1.invoke(CoroutineUtils.kt:194)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

### 复现

.

### mirai-core 版本

2.12.0

### bot-protocol

ANDROID_PHONE

**Comment by cssxsh** [comment]
你为啥不把 **发送失败的图片** 发出来

**Comment by 493505110** [comment]
> java.lang.IllegalArgumentException: **Unsupported image type** (test.png) for ExternalResource

你的图片能正常打开吗

**Comment by Karlatemp** [comment]
Long time no reply
