### ISSUE TITLE
2.12.0 mirai-api-http 无法正确读配置

### ISSUE THREAD

**Issue by Initial-heart-1** [mamoe/mirai#2145]
### 问题描述

如题，除使用 mcl 升级了 mirai 外没有任何的其他改动。
咨询了 @LaoLittle 后根据其意见提交此 issue。

### 复现

并不明确如何复现，但了解到有用户同样遇见此问题。
样本量很少，但是还是有共同点，即使用 mcl 升级 mirai 至 2.12.0。
有用户新装 mirai **似乎**没有问题。
报错后配置文件**没有**改动。

### mirai-core 版本

2.12.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-api-http 2.5.2
（原版本 2.3.1 遇到问题后升级）

### 系统日志

```text
2022-07-09 17:09:01 W/net.mamoe.mirai-api-http: Linked class net.mamoe.yamlkt.YamlElement in mirai-console-2.7.0.jar but plugin not depend on it.
2022-07-09 17:09:01 W/net.mamoe.mirai-api-http: Class loading logic may change in feature.
2022-07-09 17:09:01 E/net.mamoe.mirai-api-http: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'adapterSettings' in 'setting'
    host: localhost
                  ^ at line 30, column 20

net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'adapterSettings' in 'setting'
    host: localhost
                  ^ at line 30, column 20

        at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
        at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
        at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:181)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:85)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:162)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:44)
        at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginConfig(AbstractJvmPlugin.kt:59)
        at mirai-api-http-v2.5.2.mirai2.jar//net.mamoe.mirai.api.http.HttpApiPluginBase.onEnable(HttpApiPluginBase.kt:34)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:278)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:178)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:235)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:189)
        at org.itxtech.mcl.Loader.main(Loader.java:79)
Caused by: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for '1' in 'kotlin.collections.LinkedHashMap'
    host: localhost
        ^ at line 30, column 10

        at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
        at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
        at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:181)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
        at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)
        at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.deserialize(serializerHelper.kt:170)
        at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:179)
        ... 32 more
Caused by: java.lang.ClassCastException: class net.mamoe.yamlkt.internal.YamlDecoder$BlockMapDecoder cannot be cast to class net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder (net.mamoe.yamlkt.internal.YamlDecoder$BlockMapDecoder is in unnamed module of loader 'app'; net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder is in unnamed module of loader 'mirai-console-2.7.0.jar' @3ad85136)
        at mirai-console-2.7.0.jar//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:35)
        at mirai-console-2.7.0.jar//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:30)
        at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:179)
        ... 40 more
```

**Comment by Karlatemp** [comment]
```
cd $mirai_console_location
echo =============================================
ls libs
ls plugins
echo =============================================
find . | grep jar
```

**Comment by Initial-heart-1** [comment]
> ```
> cd $mirai_console_location
> echo =============================================
> ls libs
> ls plugins
> echo =============================================
> find . | grep jar
> ```

Windows
虽然意思懂了
稍等

**Comment by cssxsh** [comment]
> Caused by: java.lang.ClassCastException: class net.mamoe.yamlkt.internal.YamlDecoder$BlockMapDecoder cannot be cast to class net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder (net.mamoe.yamlkt.internal.YamlDecoder$BlockMapDecoder is in unnamed module of loader 'app'; net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder is in unnamed module of loader 'mirai-console-2.7.0.jar' @3ad85136)
        at mirai-console-2.7.0.jar//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:35)
        at mirai-console-2.7.0.jar//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:30)
        at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:179)
        ... 40 more

确定是 2.12.0 ？

**Comment by Initial-heart-1** [comment]
> > Caused by: java.lang.ClassCastException: class net.mamoe.yamlkt.internal.YamlDecoder$BlockMapDecoder cannot be cast to class net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder (net.mamoe.yamlkt.internal.YamlDecoder$BlockMapDecoder is in unnamed module of loader 'app'; net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder is in unnamed module of loader 'mirai-console-2.7.0.jar' @3ad85136)
> > at mirai-console-2.7.0.jar//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:35)
> > at mirai-console-2.7.0.jar//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:30)
> > at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:179)
> > ... 40 more
> 
> 确定是 2.12.0 ？

确定
至少 mcl 在启动时报2.12.0

**Comment by Initial-heart-1** [comment]
> ```
> cd $mirai_console_location
> echo =============================================
> ls libs
> ls plugins
> echo =============================================
> find . | grep jar
> ```

```
=============================================
bcprov-jdk15on-1.64.jar
bcprov-jdk15on-1.64.sha1
mirai-console-2.10.0-RC2.jar
mirai-console-2.10.0-RC2.sha1
mirai-console-2.10.0.jar
mirai-console-2.10.0.sha1
mirai-console-2.10.1.jar
mirai-console-2.10.1.sha1
mirai-console-2.10.3.jar
mirai-console-2.10.3.sha1
mirai-console-2.12.0.jar
mirai-console-2.12.0.sha1
mirai-console-2.7.0.jar
mirai-console-2.7.0.sha1
mirai-console-2.7.1-dev-1.jar
mirai-console-2.7.1-dev-1.sha1
mirai-console-2.7.1.jar
mirai-console-2.7.1.sha1
mirai-console-2.9.0-M1.jar
mirai-console-2.9.0-M1.sha1
mirai-console-2.9.1.jar
mirai-console-2.9.1.sha1
mirai-console-terminal-2.10.0-RC2.jar
mirai-console-terminal-2.10.0-RC2.sha1
mirai-console-terminal-2.10.0.jar
mirai-console-terminal-2.10.0.sha1
mirai-console-terminal-2.10.1.jar
mirai-console-terminal-2.10.1.sha1
mirai-console-terminal-2.10.3.jar
mirai-console-terminal-2.10.3.sha1
mirai-console-terminal-2.12.0.jar
mirai-console-terminal-2.12.0.sha1
mirai-console-terminal-2.7.0.jar
mirai-console-terminal-2.7.0.sha1
mirai-console-terminal-2.7.1-dev-1.jar
mirai-console-terminal-2.7.1-dev-1.sha1
mirai-console-terminal-2.7.1.jar
mirai-console-terminal-2.7.1.sha1
mirai-console-terminal-2.9.0-M1.jar
mirai-console-terminal-2.9.0-M1.sha1
mirai-console-terminal-2.9.1.jar
mirai-console-terminal-2.9.1.sha1
mirai-core-all-2.10.0-RC2.jar
mirai-core-all-2.10.0-RC2.sha1
mirai-core-all-2.10.0.jar
mirai-core-all-2.10.0.sha1
mirai-core-all-2.10.1.jar
mirai-core-all-2.10.1.sha1
mirai-core-all-2.10.3.jar
mirai-core-all-2.10.3.sha1
mirai-core-all-2.12.0.jar
mirai-core-all-2.12.0.sha1
mirai-core-all-2.7.1-dev-1-all.jar
mirai-core-all-2.7.1-dev-1.jar
mirai-core-all-2.7.1-dev-1.sha1
mirai-core-all-2.7.1.jar
mirai-core-all-2.7.1.sha1
mirai-core-all-2.9.0-M1.jar
mirai-core-all-2.9.0-M1.sha1
mirai-core-all-2.9.1.jar
mirai-core-all-2.9.1.sha1
bilibili-dynamic-mirai-plugin-3.0.0-BETA1.2.mirai2.jar
bot.mirai.jar
chat-command-0.5.1.jar
debug-helper-1.0.3.mirai.jar
mcl-addon-2.0.2.jar
mcl-addon-2.0.2.sha1
meme-helper-1.1.1.mirai2.jar
mirai-api-http-v2.5.2.mirai2.jar
mirai-console-2.7.0.jar
mirai-console-2.7.0.sha1
mirai-hibernate-plugin-2.2.4.mirai2.jar
mirai-skia-plugin-1.1.3.mirai2.jar
MiraiMirage-2.0.1.mirai2.jar
MiraiSongPlugin-2.7-1.1.7.jar
=============================================
```
删除 plugins 下的 mirai-console 后故障排除
~~为什么升个级就把远古留下的 mirai-console 加载上了啊~~

**Comment by Initial-heart-1** [comment]
如何解释有相同问题的用户
也许是之前升级的时候迁移没做好？

**Comment by Karlatemp** [comment]
通过 mcl 升级时出现问题属于 mcl 问题而不是 mirai-core/mirai-console 问题, 你应该去 mcl 那边发起 issue

**Comment by Initial-heart-1** [comment]
了解



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年7月9日(星期六) 下午5:36
To: ***@***.***&gt;; 
Cc: "Initial ***@***.***&gt;; "State ***@***.***&gt;; 
Subject: Re: [mamoe/mirai] 2.12.0 mirai-api-http 无法正确读配置 (Issue #2145)





 
通过 mcl 升级时出现问题属于 mcl 问题而不是 mirai-core/mirai-console 问题, 你应该去 mcl 那边发起 issue

**Comment by fatinghenji** [comment]
该问题应该不仅仅是mcl的问题，我参考该issue删除`/libs`里面所有的老版本后问题依旧存在。
应该是`net.mamoe.yamlkt.YamlElement`的问题。
在删除/libs`里面所有的老版本后，报错如下所示：
```java
2022-07-10 08:27:36 W/net.mamoe.mirai-api-http: Linked class net.mamoe.yamlkt.YamlElement in onebot-mirai-0.3.4-all.jar but plugin not depend on it.                                                          
2022-07-10 08:27:36 W/net.mamoe.mirai-api-http: Class loading logic may change in feature.                                                                                                                    
2022-07-10 08:27:36 E/net.mamoe.mirai-api-http: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'adapterSettings' in 'setting'                                      
    host: 0.0.0.0                                                                                                                                                                                             
                ^ at line 11, column 18                                                                                                                                                                       
                                                                                                                                                                                                              
net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'adapterSettings' in 'setting'                                                                                      
    host: 0.0.0.0                                                                                                                                                                                             
                ^ at line 11, column 18                                                                                                                                                                       
                                                                                                                                                                                                              
        at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)                                                                                 
        at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)                                                                                                                    
        at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:181)                                                                                                
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)                                                                                    
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:85)                                                                                         
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:47)                                                                                         
        at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:162)                                                                                                                                                
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:44)                                                                                    
        at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginConfig(AbstractJvmPlugin.kt:59)
        at mirai-api-http-v2.5.0.mirai.jar//net.mamoe.mirai.api.http.HttpApiPluginBase.onEnable(HttpApiPluginBase.kt:34)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:131)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:278)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)       
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)    
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)             
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:178)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:235)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)              
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)              
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)          
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)                                   
        at org.itxtech.mcl.Utility.bootJars(Utility.java:89)                                           
        at org.itxtech.mcl.Utility.bootJars(Utility.java:79)                                           
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)                                         
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)                                     
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:145)                      
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:184)                                      
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)                                         
        at org.itxtech.mcl.Loader.start(Loader.java:184)                                               
        at org.itxtech.mcl.Loader.main(Loader.java:79)                                                 
Caused by: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for '1' in 'kotlin.collections.LinkedHashMap'
    host: 0.0.0.0   
        ^ at line 11, column 10

        at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
        at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)             
        at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:181)
        at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:535)
        at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)  
        at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)   
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.deserialize(serializerHelper.kt:170)
        at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:179)
        ... 32 more                                
Caused by: java.lang.ClassCastException: class net.mamoe.yamlkt.internal.YamlDecoder$BlockMapDecoder cannot be cast to class net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder (net.mamoe.yamlkt.internal.
YamlDecoder$BlockMapDecoder is in unnamed module of loader 'app'; net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder is in unnamed module of loader 'onebot-mirai-0.3.4-all.jar' @3ce443f9)
        at onebot-mirai-0.3.4-all.jar//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:35)
        at onebot-mirai-0.3.4-all.jar//net.mamoe.yamlkt.internal.YamlElementSerializer.deserialize(YamlElementSerializer.kt:30)
        at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:179)
        ... 40 more 
```
我也在`OneBot Mirai - CQHTTP Mirai`那边发起了一个[issue](https://github.com/yyuueexxiinngg/onebot-kotlin/issues/164)，但是那个插件似乎已经无人维护了。
