### ISSUE TITLE
无任何变动，插件指令私聊可以使用但是群聊会直接报错 46

### ISSUE THREAD

**Issue by rogue233** [mamoe/mirai#2149]
### 问题描述

群聊中使用插件的命令会直接报错，但是插件没有任何更新，且无任何变动操作，并且任何插件都会复现此问题。
![图片](https://user-images.githubusercontent.com/80617099/178672292-dc413495-d73c-4b47-9c65-4f297d640795.png)

### 复现

使用mcl-installer安装
随便装一个插件
群聊调用命令
报错

### mirai-core 版本

2.12.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
启动时报错：
2022-07-13 15:10:07 W/stderr: ERROR StatusLogger Log4j2 could not find a logging
 implementation. Please add log4j-core to the classpath. Using SimpleLogger to l
og to the console...

群聊使用命令时：
2022-07-13 15:00:40 E/OneBot: java.lang.IllegalStateException: Send message fail
ed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage
=)
java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Respon
se.Failed(resultType=46, errorCode=0, errorMessage=)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderPr
otocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:146
)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderPr
otocol$GeneralMessageSender.access$sendSinglePacket(GeneralMessageSenderProtocol
.kt:46)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderPr
otocol$GeneralMessageSender$sendSinglePacket$1.invokeSuspend(GeneralMessageSende
rProtocol.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:
102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:664)
```

### 补充信息

网络日志：
[2022-07-13.log](https://github.com/mamoe/mirai/files/9099825/2022-07-13.log)

完整系统日志：
[latest.log](https://github.com/mamoe/mirai/files/9099829/latest.log)

**Comment by lyh02** [comment]
我也出现了这种情况，插件指令私聊可以使用但是群聊会直接报错

**Comment by wumai-dov** [comment]
出现了同样的问题，是受tx风控的影响，冻结了群聊消息的发送。
参考下方
https://github.com/mamoe/mirai/issues/2127
