### ISSUE TITLE
在启动mirai时时间过长并且报错

### ISSUE THREAD

**Issue by XiaoDouZiQwQ** [mamoe/mirai#2151]
### 问题描述

在启动mirai时时间过长并且报错

### 复现

在家庭服务器登录会出现此问题，经本人测试，运行在同一环境下的miraimc不会出现此故障，初步排除网络问题，并且尝试了扩充熵池，并无作用

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-api-http-2.5.2
onebot-mirai-0.3.4

### 系统日志

```text
19:05:19 [INFO] iTXTech Mirai Console Loader version 2.1.0-71ec418
  19:05:19 [INFO] https://github.com/iTXTech/mirai-console-loader
  19:05:19 [INFO] This program is licensed under GNU AGPL v3
  19:05:50 [ERROR] Failed to fetch announcement for "net.mamoe:mirai-console"
  19:06:06 [ERROR] Failed to fetch announcement for "net.mamoe:mirai-console-terminal"
  19:06:52 [ERROR] Failed to fetch announcement for "net.mamoe:chat-command"
  19:07:22 [ERROR] Failed to fetch announcement for "net.mamoe:mirai-api-http"
  19:07:52 [ERROR] Failed to fetch MCL announcement.
  19:07:52 [INFO] Verifying "net.mamoe:mirai-console" v2.12.0
  19:07:53 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.12.0
  19:08:23 [ERROR] Failed to verify package "net.mamoe:mirai-console-terminal"
  19:08:23 [ERROR] java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:571)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
        at org.itxtech.mcl.component.Repository.httpGet(Repository.java:208)
        at org.itxtech.mcl.component.Repository.httpGet(Repository.java:203)
        at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:81)
        at org.itxtech.mcl.module.builtin.RepoCache$RepoWithCache.fetchPackage(RepoCache.java:88)
        at org.itxtech.mcl.module.builtin.Updater.check(Updater.java:101)
        at org.itxtech.mcl.module.builtin.Updater.load(Updater.java:60)
        at org.itxtech.mcl.module.ModuleManager.phaseLoad(ModuleManager.java:142)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:183)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:183)
        at org.itxtech.mcl.Loader.main(Loader.java:79)

  19:08:23 [INFO] Verifying "net.mamoe:mirai-core-all" v2.12.0
  19:08:23 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2
  19:08:23 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
  19:08:23 [INFO] Verifying "net.mamoe:chat-command" v0.5.1
  19:08:53 [ERROR] Failed to verify package "net.mamoe:chat-command"
  19:08:53 [ERROR] java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:571)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
        at org.itxtech.mcl.component.Repository.httpGet(Repository.java:208)
        at org.itxtech.mcl.component.Repository.httpGet(Repository.java:203)
        at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:81)
        at org.itxtech.mcl.module.builtin.RepoCache$RepoWithCache.fetchPackage(RepoCache.java:88)
        at org.itxtech.mcl.module.builtin.Updater.check(Updater.java:101)
        at org.itxtech.mcl.module.builtin.Updater.load(Updater.java:60)
        at org.itxtech.mcl.module.ModuleManager.phaseLoad(ModuleManager.java:142)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:183)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:183)
        at org.itxtech.mcl.Loader.main(Loader.java:79)

  19:08:53 [INFO] Verifying "net.mamoe:mirai-api-http" v2.5.2
  19:09:23 [ERROR] Failed to verify package "net.mamoe:mirai-api-http"
  19:09:23 [ERROR] java.net.http.HttpTimeoutException: request timed out
        at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:571)
        at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123)
        at org.itxtech.mcl.component.Repository.httpGet(Repository.java:208)
        at org.itxtech.mcl.component.Repository.httpGet(Repository.java:203)
        at org.itxtech.mcl.component.Repository.fetchPackage(Repository.java:81)
        at org.itxtech.mcl.module.builtin.RepoCache$RepoWithCache.fetchPackage(RepoCache.java:88)
        at org.itxtech.mcl.module.builtin.Updater.check(Updater.java:101)
        at org.itxtech.mcl.module.builtin.Updater.load(Updater.java:60)
        at org.itxtech.mcl.module.ModuleManager.phaseLoad(ModuleManager.java:142)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:183)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:183)
        at org.itxtech.mcl.Loader.main(Loader.java:79)

  19:09:23 [WARN] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-RC. Current version is 2.12.0//请注意开始启动和此处的时间差
2022-07-14 19:09:24 I/main: Starting mirai-console...
2022-07-14 19:09:24 I/main: Backend: version 2.12.0, built on 2022-07-03 10:57:58.
2022-07-14 19:09:24 I/main: Frontend Terminal: version 2.12.0, provided by Mamoe Technologies
2022-07-14 19:09:24 I/main: Welcome to visit https://mirai.mamoe.net/
2022-07-14 19:09:24 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-07-14 19:09:24 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-07-14 19:09:24 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-07-14 19:09:25 I/plugin: Successfully loaded plugin 自定义头衔 v1.0-SNAPSHOT
2022-07-14 19:09:25 I/plugin: Successfully loaded plugin OneBot v0.3.4
2022-07-14 19:09:25 I/plugin: Successfully loaded plugin Mesagisto v1.0-unknown
2022-07-14 19:09:25 I/plugin: Successfully loaded plugin Minecraft MOTD Fetcher v1.1.6
2022-07-14 19:09:25 I/plugin: Successfully loaded plugin 原神模拟抽卡 v1.2.1
2022-07-14 19:09:25 I/plugin: Successfully loaded plugin SimpleGroupAuth v0.1.1
2022-07-14 19:09:25 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.5.2
2022-07-14 19:09:25 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2022-07-14 19:09:25 I/plugin: Successfully loaded plugin MCL Addon v2.0.2
2022-07-14 19:09:25 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-07-14 19:09:25 I/自定义头衔: Plugin loaded
2022-07-14 19:09:25 I/OneBot: Plugin loaded! 0.3.4
2022-07-14 19:09:25 I/OneBot: 插件当前Commit 版本: 75a84ee
2022-07-14 19:09:25 W/Mesagisto: Mesagisto信使未启用!
2022-07-14 19:09:25 I/Minecraft MOTD Fetcher: McMotd is loading
2022-07-14 19:09:25 W/Minecraft MOTD Fetcher: 找不到指定的字体 : Microsoft YaHei，您可以在mcmotd.yml中修改字体名称
2022-07-14 19:09:25 I/Minecraft MOTD Fetcher: 检测到可用的字体列表: AR PL UKai CN,AR PL UKai HK,AR PL UKai TW,AR PL UKai TW MBE,AR PL UMing CN,AR PL UMing HK,AR PL UMing TW,AR PL UMing TW MBE,Dialog.bold,Dialog.bolditalic,Dialog.italic,Dialog.plain,DialogInput.bold,DialogInput.bolditalic,DialogInput.italic,DialogInput.plain,Droid Sans Fallback,Monospaced.bold,Monospaced.bolditalic,Monospaced.italic,Monospaced.plain,Noto Sans CJK HK,Noto Sans CJK HK Black,Noto Sans CJK HK Bold,Noto Sans CJK HK DemiLight,Noto Sans CJK HK Light,Noto Sans CJK HK Medium,Noto Sans CJK HK Thin,Noto Sans CJK JP,Noto Sans CJK JP Black,Noto Sans CJK JP Bold,Noto Sans CJK JP DemiLight,Noto Sans CJK JP Light,Noto Sans CJK JP Medium,Noto Sans CJK JP Thin,Noto Sans CJK KR,Noto Sans CJK KR Black,Noto Sans CJK KR Bold,Noto Sans CJK KR DemiLight,Noto Sans CJK KR Light,Noto Sans CJK KR Medium,Noto Sans CJK KR Thin,Noto Sans CJK SC,Noto Sans CJK SC Black,Noto Sans CJK SC Bold,Noto Sans CJK SC DemiLight,Noto Sans CJK SC Light,Noto Sans CJK SC Medium,Noto Sans CJK SC Thin,Noto Sans CJK TC,Noto Sans CJK TC Black,Noto Sans CJK TC Bold,Noto Sans CJK TC DemiLight,Noto Sans CJK TC Light,Noto Sans CJK TC Medium,Noto Sans CJK TC Thin,Noto Sans Mono CJK HK,Noto Sans Mono CJK HK Bold,Noto Sans Mono CJK JP,Noto Sans Mono CJK JP Bold,Noto Sans Mono CJK KR,Noto Sans Mono CJK KR Bold,Noto Sans Mono CJK SC,Noto Sans Mono CJK SC Bold,Noto Sans Mono CJK TC,Noto Sans Mono CJK TC Bold,Noto Serif CJK HK,Noto Serif CJK HK Black,Noto Serif CJK HK Bold,Noto Serif CJK HK ExtraLight,Noto Serif CJK HK Light,Noto Serif CJK HK Medium,Noto Serif CJK HK SemiBold,Noto Serif CJK JP,Noto Serif CJK JP Black,Noto Serif CJK JP Bold,Noto Serif CJK JP ExtraLight,Noto Serif CJK JP Light,Noto Serif CJK JP Medium,Noto Serif CJK JP SemiBold,Noto Serif CJK KR,Noto Serif CJK KR Black,Noto Serif CJK KR Bold,Noto Serif CJK KR ExtraLight,Noto Serif CJK KR Light,Noto Serif CJK KR Medium,Noto Serif CJK KR SemiBold,Noto Serif CJK SC,Noto Serif CJK SC Black,Noto Serif CJK SC Bold,Noto Serif CJK SC ExtraLight,Noto Serif CJK SC Light,Noto Serif CJK SC Medium,Noto Serif CJK SC SemiBold,Noto Serif CJK TC,Noto Serif CJK TC Black,Noto Serif CJK TC Bold,Noto Serif CJK TC ExtraLight,Noto Serif CJK TC Light,Noto Serif CJK TC Medium,Noto Serif CJK TC SemiBold,SansSerif.bold,SansSerif.bolditalic,SansSerif.italic,SansSerif.plain,Serif.bold,Serif.bolditalic,Serif.italic,Serif.plain
2022-07-14 19:09:25 W/Minecraft MOTD Fetcher: 正在使用第一个可用的字体: AR PL UKai CN
2022-07-14 19:09:25 I/原神模拟抽卡: 加载配置....
2022-07-14 19:09:25 I/原神模拟抽卡: 加载数据....
2022-07-14 19:09:25 I/原神模拟抽卡: Plugin loaded
2022-07-14 19:09:25 I/原神模拟抽卡: 启动定时清理任务，每天凌晨4点自动清理历史下载图片...
2022-07-14 19:09:25 I/原神模拟抽卡: 历史下载图片清理完毕...
2022-07-14 19:09:25 I/SimpleGroupAuth: SimpleGroupAuth已启动
2022-07-14 19:09:25 W/net.mamoe.mirai-api-http: Linked class net.mamoe.yamlkt.YamlElement in onebot-mirai-0.3.4-all.jar but plugin not depend on it.
2022-07-14 19:09:25 W/net.mamoe.mirai-api-http: Class loading logic may change in feature.
2022-07-14 19:09:25 W/net.mamoe.mirai-api-http: USING INITIAL KEY, please edit the key
2022-07-14 19:09:25 I/Mirai HTTP API: ********************************************************
2022-07-14 19:09:25 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-07-14 19:09:25 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-07-14 19:09:25 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-07-14 19:09:25 I/http adapter: >>> [http adapter] is listening at http://localhost:8080
2022-07-14 19:09:25 I/Mirai HTTP API: Http api server is running with verifyKey: INITKEYFycSBah5
2022-07-14 19:09:25 I/Mirai HTTP API: adaptors: [http]
2022-07-14 19:09:25 I/Mirai HTTP API: ********************************************************
2022-07-14 19:09:26 I/MCL Addon: iTXTech MCL Version: 2.1.0-71ec418
2022-07-14 19:09:26 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2022-07-14 19:09:26 I/main: 9 plugin(s) enabled.
2022-07-14 19:09:26 I/main: Auto-login 3462481896
2022-07-14 19:09:26 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2022-07-14 19:09:26 I/Bot.3462481896: Loaded account secrets from local cache.
2022-07-14 19:09:26 I/Bot.3462481896: Saved account secrets to local cache for fast login.
2022-07-14 19:09:27 I/Bot.3462481896: Login successful.
2022-07-14 19:09:27 V/Bot.3462481896: Event: BotOnlineEvent(bot=Bot(3462481896))
2022-07-14 19:09:27 I/OneBot: Bot: 3462481896 HTTP API服务端是否配置开启: false
2022-07-14 19:09:27 I/OneBot: Bot: 3462481896 正向Websocket服务端是否配置开启: true
2022-07-14 19:09:27 I/stdout: 19:09:27.773 [DefaultDispatcher-worker-1] INFO Application - Autoreload is disabled because the development mode is off.
2022-07-14 19:09:27 I/stdout: 
2022-07-14 19:09:27 I/OneBot: Bot: 3462481896 未开启接收图片缓存, 将不会缓存收取到的所有图片, 如需开启, 请在当前Bot配置中添加cacheImage=true
2022-07-14 19:09:27 I/OneBot: Bot: 3462481896 未开启接收语音缓存, 将不会缓存收取到的所有语音, 如需开启, 请在当前Bot配置中添加cacheRecord=true
2022-07-14 19:09:27 I/Bot.3462481896: Bot login successful.
2022-07-14 19:09:27 I/main: mirai-console started successfully.
2022-07-14 19:09:27 I/stdout: 19:09:27.799 [DefaultDispatcher-worker-1] INFO Application - Responding at http://0.0.0.0:6700
2022-07-14 19:09:27 I/stdout:
```

### 网络日志

```text
[92m2022-07-14 19:02:56 I/Net 3462481896: Server list: 157.148.54.249:80, 220.194.118.236:80, 112.86.240.57:14000, 59.83.209.34:14000, 116.130.229.208:443, msfwifi.3g.qq.com:8080, 163.177.30.25:80, 59.83.207.254:80, 60.29.242.161:8080, 116.130.230.31:8080.[0m
[92m2022-07-14 19:02:57 I/Net 3462481896: ECDH key is valid.[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Send: wtlogin.exchange_emp[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Recv: wtlogin.exchange_emp[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Send: StatSvc.register(online)[0m
[92m2022-07-14 19:02:57 I/Net 3462481896: Server time updated, serverTime: 1657796577, diff: 0ms=0.0s[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Recv: StatSvc.register[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Loading BdhSession from cache file[0m
[92m2022-07-14 19:02:57 I/Net 3462481896: Syncing friend message history...[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[92m2022-07-14 19:02:57 I/Net 3462481896: Start loading stranger list...[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[92m2022-07-14 19:02:57 I/Net 3462481896: Start loading friend list...[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Recv: OidbSvc.0x5d2_0[0m
[92m2022-07-14 19:02:57 I/Net 3462481896: Successfully loaded stranger list: 0 in total[0m
[92m2022-07-14 19:02:57 I/Net 3462481896: Start loading group list...[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Recv: OidbSvc.0x496[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Recv: StatSvc.GetDevLoginInfo[0m
[92m2022-07-14 19:02:57 I/Net 3462481896: Online OtherClients: 未知设备(IOS)[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Recv: friendlist.getFriendGroupList[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Loading friend list: 3/3[0m
[92m2022-07-14 19:02:57 I/Net 3462481896: Successfully loaded friend list: 3 in total[0m
[92m2022-07-14 19:02:57 I/Net 3462481896: Syncing friend message history: Success.[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Recv: friendlist.GetTroopListReqV2[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-14 19:02:57 V/Net 3462481896: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-14 19:02:58 V/Net 3462481896: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-14 19:02:58 V/Net 3462481896: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-14 19:02:58 V/Net 3462481896: Recv: friendlist.GetTroopMemberListReq[0m
[92m2022-07-14 19:02:58 I/Net 3462481896: Successfully loaded group list: 3 in total.[0m
[92m2022-07-14 19:02:58 I/Net 3462481896: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2022-07-14 19:02:58 I/Net 3462481896: Scheduled key refresh in 23h 55min 0.0s.[0m
[0m2022-07-14 19:03:05 V/Net 3462481896: Saving bdh session to cache[0m
[0m2022-07-14 19:03:05 V/Net 3462481896: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2022-07-14 19:03:05 V/Net 3462481896: Recv: ConfigPushSvc.PushReq[0m
[0m2022-07-14 19:04:48 V/Net 3462481896: Send: StatSvc.register(offline)[0m
[0m2022-07-14 19:09:26 V/Net 3462481896: Loading server list from cache.[0m
[92m2022-07-14 19:09:26 I/Net 3462481896: Server list: 157.148.54.249:80, 220.194.118.236:80, 112.86.240.57:14000, 59.83.209.34:14000, 116.130.229.208:443, msfwifi.3g.qq.com:8080, 163.177.30.25:80, 59.83.207.254:80, 60.29.242.161:8080, 116.130.230.31:8080.[0m
[92m2022-07-14 19:09:26 I/Net 3462481896: ECDH key is valid.[0m
[0m2022-07-14 19:09:26 V/Net 3462481896: Send: wtlogin.exchange_emp[0m
[0m2022-07-14 19:09:26 V/Net 3462481896: Recv: wtlogin.exchange_emp[0m
[0m2022-07-14 19:09:26 V/Net 3462481896: Send: StatSvc.register(online)[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Server time updated, serverTime: 1657796967, diff: 0ms=0.0s[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Recv: StatSvc.register[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Loading BdhSession from cache file[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Syncing friend message history...[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Start loading friend list...[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Send: OidbSvc.0x496(OidbSvc.0x496)[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Start loading stranger list...[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Recv: OidbSvc.0x5d2_0[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Successfully loaded stranger list: 0 in total[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Start loading group list...[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Recv: OidbSvc.0x496[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Recv: friendlist.getFriendGroupList[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Loading friend list: 3/3[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Successfully loaded friend list: 3 in total[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Recv: StatSvc.GetDevLoginInfo[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Online OtherClients: 未知设备(IOS)[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Syncing friend message history: Success.[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Recv: friendlist.GetTroopListReqV2[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Recv: friendlist.GetTroopMemberListReq[0m
[0m2022-07-14 19:09:27 V/Net 3462481896: Recv: friendlist.GetTroopMemberListReq[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Successfully loaded group list: 3 in total.[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2022-07-14 19:09:27 I/Net 3462481896: Scheduled key refresh in 23h 55min 0.0s.[0m
[0m2022-07-14 19:09:30 V/Net 3462481896: Saving bdh session to cache[0m
[0m2022-07-14 19:09:30 V/Net 3462481896: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2022-07-14 19:09:30 V/Net 3462481896: Recv: ConfigPushSvc.PushReq[0m
```

**Comment by MrXiaoM** [comment]
mcl 无法获取公告，检查包完整性时出现连接超时。  
更换仓库详见 https://mirai.mamoe.net/topic/1084

**Comment by Karlatemp** [comment]
这是 mcl 进行更新检查与公告获取等操作时超时, 解决方案见上文
