### ISSUE TITLE
在 `Internal error: no MessageReceipt was returned from OutgoingMessagePipeline for message` 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by DreamVoid** [mamoe/mirai#2154]
### 问题描述

在发送消息时会出现报错`在 Internal error: no MessageReceipt was returned from OutgoingMessagePipeline for message 时遇到了意料之中的问题`，而在2.11.1及以下版本无此问题。
并且相同环境下，机器人接受到的好友和群消息内容均为空白（或者说null） 
~~相同的情况也出现在昨天测试的旧版本mcl上（mcl新版本无问题）~~ 昨天遇到的是几天前报告过的问题`Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider`

### 复现

发送消息：
1. 使用2.12.0的mirai
2. 通过`Group#sendMessage(String)`方法发送消息
3. 复现完成

接收消息：
1. 使用2.12.0的mirai ~~（使用旧版本mcl也可）~~
2. 任意账号在任意群发送任意消息
3. 机器人得到的是空消息（有其他人报告是null）

### mirai-core 版本

2.12.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
日志中已移除帮助不大的内容

[11:39:25 INFO]: 2022-07-17 11:39:25 V/Net 机器人QQ: Loading server list from cache.
[11:39:25 INFO]: 2022-07-17 11:39:25 I/Net 机器人QQ: Server list: 120.232.69.173:8080, msfwifi.3g.qq.com:8080, 111.31.205.243:80, 120.232.31.192:80, 36.155.209.114:443, 36.155.248.76:80, 111.30.169.83:14000, 111.31.205.197:80, 120.232.31.164:80.
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Bot 机器人QQ: Loaded account secrets from local cache.
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Net 机器人QQ: ECDH key is valid.
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Send: wtlogin.exchange_emp
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Bot 机器人QQ: Saved account secrets to local cache for fast login.
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Recv: wtlogin.exchange_emp
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Send: StatSvc.register(online)
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Bot 机器人QQ: Login successful.
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Net 机器人QQ: Server time updated, serverTime: 1658029166, diff: 0ms=0.0s
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Recv: StatSvc.register
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Loading BdhSession from cache file
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Net 机器人QQ: Syncing friend message history...
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Net 机器人QQ: Start loading stranger list...
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Net 机器人QQ: Start loading friend list...
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Send: OidbSvc.0x496(OidbSvc.0x496)
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Recv: StatSvc.GetDevLoginInfo
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Net 机器人QQ: No OtherClient online.
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Recv: OidbSvc.0x5d2_0
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Net 机器人QQ: Syncing friend message history: Success.
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Net 机器人QQ: Successfully loaded stranger list: 2 in total
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Recv: OidbSvc.0x496
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Net 机器人QQ: Start loading group list...
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Recv: friendlist.getFriendGroupList
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Loading friend list: 3/3
[11:39:26 INFO]: 2022-07-17 11:39:26 I/Net 机器人QQ: Successfully loaded friend list: 3 in total
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Recv: friendlist.GetTroopListReqV2
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)
[11:39:26 INFO]: 2022-07-17 11:39:26 V/Net 机器人QQ: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)
[11:39:27 INFO]: 2022-07-17 11:39:27 V/Net 机器人QQ: Recv: friendlist.GetTroopMemberListReq
[11:39:27 INFO]: 2022-07-17 11:39:27 V/Net 机器人QQ: Recv: friendlist.GetTroopMemberListReq
[11:39:27 INFO]: 2022-07-17 11:39:27 I/Net 机器人QQ: Successfully loaded group list: 2 in total.
[11:39:27 INFO]: 2022-07-17 11:39:27 I/Net 机器人QQ: Scheduled refresh login session in 19d 23h 55min 0.0s.
[11:39:27 INFO]: 2022-07-17 11:39:27 I/Net 机器人QQ: Scheduled key refresh in 23h 55min 0.0s.
[11:39:27 INFO]: 2022-07-17 11:39:27 V/Bot 机器人QQ: Event: BotOnlineEvent(bot=Bot(机器人QQ))
[11:39:27 INFO]: 2022-07-17 11:39:27 I/Bot 机器人QQ: Bot login successful.
[11:39:29 INFO]: 2022-07-17 11:39:29 V/Net 机器人QQ: Saving bdh session to cache
[11:39:29 INFO]: 2022-07-17 11:39:29 V/Net 机器人QQ: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)
[11:39:29 INFO]: 2022-07-17 11:39:29 V/Net 机器人QQ: Recv: ConfigPushSvc.PushReq
> 此处执行发送消息指令，其中123为消息内容
[11:39:31 WARN]: Unexpected exception while parsing console command "指令"
org.bukkit.command.CommandException: Unhandled exception executing command 'mirai' in plugin MiraiMC v1.7
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:940) ~[purpur-1.19.jar:git-Purpur-1697]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:903) ~[purpur-1.19.jar:git-Purpur-1697]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:512) ~[purpur-1.19.jar:git-Purpur-1697]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.jar:git-Purpur-1697]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1441) ~[purpur-1.19.jar:git-Purpur-1697]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1208) ~[purpur-1.19.jar:git-Purpur-1697]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1697]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: net.mamoe.mirai.internal.message.ContextualBugReportException: 在 Internal error: no MessageReceipt was returned from OutgoingMessagePipeline for message 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    调试信息: 123
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.getSingleReceipt(MessageProtocolFacade.kt:327) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoing(MessageProtocolFacade.kt:296) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.preprocessAndSendOutgoing(MessageProtocolFacade.kt) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:264) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.contact.AbstractUserKt$sendMessageImpl$1.invokeSuspend(AbstractUser.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:202) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:283) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:257) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
[11:39:34 INFO]: 2022-07-17 11:39:34 V/Bot 机器人QQ: [群名(群号)] 昵称(QQ号) -> [这里什么都没有，发送的消息是156]
```

### 补充信息

机器人并非刚刚加入或退出这个群，也不是管理员或群主

**Comment by sandtechnology** [comment]
> Unhandled exception executing command 'mirai' in plugin MiraiMC v1.7Unhandled exception executing command 'mirai' in plugin MiraiMC v1.7

合理猜测是因为类加载器引发的问题 （在不同类加载器中的同一个class在instanceof比较时并不会成立）

你的修复[commit](https://github.com/DreamVoid/MiraiMC/commit/eaeddbdf1052d926abc4b189ac10bd1e23413cad)中并没有考虑到需要加载新类的情况，我的建议是自行新建一个类加载器处理这个问题，即让新的类加载器在PluginClassLoader和JVM自带的ClassLoader二者寻找类（先在PluginClassLoader找，找不到再去找JVM自带的ClassLoader）

**Comment by DreamVoid** [comment]
> > Unhandled exception executing command 'mirai' in plugin MiraiMC v1.7Unhandled exception executing command 'mirai' in plugin MiraiMC v1.7
> 
> 合理猜测是因为类加载器引发的问题 （在不同类加载器中的同一个class在instanceof比较时并不会成立）
> 
> 你的修复[commit](https://github.com/DreamVoid/MiraiMC/commit/eaeddbdf1052d926abc4b189ac10bd1e23413cad)中并没有考虑到需要加载新类的情况，我的建议是自行新建一个类加载器处理这个问题，即让新的类加载器在PluginClassLoader和JVM自带的ClassLoader二者寻找类（先在PluginClassLoader找，找不到再去找JVM自带的ClassLoader）

直接改用[加载mirai的classloader](https://github.com/DreamVoid/MiraiMC/blob/78f9613cb701fe64bee461c98a9767be13d0b7a0/MiraiMC-Bukkit/src/main/java/me/dreamvoid/miraimc/bukkit/BukkitPlugin.java#L31)也会出现此问题，而且我也没搞明白classloader的问题为什么能导致消息内容是空白

**Comment by Him188** [comment]
这是因为 mirai 内部是模块化的，通过 ServiceLoader 加载协议实现。由于 classloader 环境或者 service 配置（META-INF/services）异常，协议实现无法加载，就导致没有*协议处理器*来处理消息类型，进而导致报错（没有收到 receipt，因为没有处理器发送消息）
