### ISSUE TITLE
由 Native target 引发的系列问题

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai#2160]
---------------------

- `BotConfiguration.cacheDir` (JVM) 未按照预期运行
  - [x] JVM
  - [x] native

源预期: `workingDir.resolve(cacheDir)` 即 `$project-dir/test/bot-working/cache`
实际解析: `$project-dir/cache`

Analyze:
https://github.com/mamoe/mirai/blob/7284b901622c494f831581f10e8b3b99bf38cf47/mirai-core/src/commonMain/kotlin/utils/BotConfigurationExt.kt#L21-L32

https://github.com/mamoe/mirai/blob/7284b901622c494f831581f10e8b3b99bf38cf47/mirai-core/src/jvmBaseMain/kotlin/utils/BotConfigurationExt.kt#L17-L18

---------------

- [x] 一些特定的消息 (如 `ForwardMessage`) 会堵死网络协程

Analyze
https://github.com/mamoe/mirai/blob/7284b901622c494f831581f10e8b3b99bf38cf47/mirai-core/src/commonMain/kotlin/network/handler/CommonNetworkHandler.kt#L105-L124

部分操作在 decodeRaw 或者 processBody 时再次执行了 `sendAndExpect`

Packet Processor 被挂起, 后续包无法进入队列解析

-----------------

- [X] Highway 不知道为何无法工作

```
CMD randi
2022-07-21 14:21:05 V/Bot 1234567890: Event: BeforeImageUploadEvent(target=Group(0987654321), source=net.mamoe.mirai.internal.utils.ExternalResourceImplByByteArray@52306aba)
2022-07-21 14:21:05 D/Net 1234567890: Attempt #0: current.state = OK
2022-07-21 14:21:05 D/Net 1234567890: Attempt #0: Try resumeConnection
2022-07-21 14:21:05 D/States: State resuming: [Bot.1234567890.EventDispatcher] OK
2022-07-21 14:21:05 D/States: State resumed: [Bot.1234567890.EventDispatcher] OK.
2022-07-21 14:21:05 D/Net 1234567890: Attempt #0: RETURN
2022-07-21 14:21:05 V/Net 1234567890: Send: ImgStore.GroupPicUp(ImgStore.GroupPicUp)
2022-07-21 14:21:05 V/Bot 1234567890: [CloseTest后援会(0987654321)] 纤绫·洛雨(3351485985) -> randi
2022-07-21 14:21:05 V/Net 1234567890: Decoding packet: Value(ByteReadPacket(404 bytes remaining))
2022-07-21 14:21:05 V/Net 1234567890: Decoding: len=404, value=<MASKED>
2022-07-21 14:21:05 V/Packet: 开始处理一个包
2022-07-21 14:21:05 V/Packet: sequenceId = 71510
2022-07-21 14:21:05 V/Net 1234567890: Decoded: ImgStore.GroupPicUp
2022-07-21 14:21:05 D/Net 1234567890: Packet Handling Processor: receive packet ImgStore.GroupPicUp
2022-07-21 14:21:05 D/NetReplayHelper: sid=71510, cmd=ImgStore.GroupPicUp, body=<MASKED>
2022-07-21 14:21:05 V/Net 1234567890: Recv: ImgStore.GroupPicUp
2022-07-21 14:21:05 V/Net 1234567890: [Highway] Uploading group image to 120.232.130.90:8080, size=1222.72 KiB
2022-07-21 14:21:05 V/Net 1234567890: [Highway] Uploading group image to 120.232.130.90:8080, size=1222.72 KiB failed: java.lang.IllegalStateException: highway transfer failed, error 81
2022-07-21 14:21:05 V/Net 1234567890: [Highway] Uploading group image to 120.232.130.72:8080, size=1222.72 KiB
2022-07-21 14:21:06 V/Net 1234567890: [Highway] Uploading group image to 120.232.130.72:8080, size=1222.72 KiB failed: java.lang.IllegalStateException: highway transfer failed, error 81
2022-07-21 14:21:06 V/Net 1234567890: [Highway] Uploading group image to 111.30.187.252:80, size=1222.72 KiB
2022-07-21 14:21:07 V/Net 1234567890: [Highway] Uploading group image to 111.30.187.252:80, size=1222.72 KiB failed: java.lang.IllegalStateException: highway transfer failed, error 81
2022-07-21 14:21:07 V/Net 1234567890: [Highway] Uploading group image to 36.155.208.76:443, size=1222.72 KiB
2022-07-21 14:21:08 V/Net 1234567890: [Highway] Uploading group image to 36.155.208.76:443, size=1222.72 KiB failed: java.lang.IllegalStateException: highway transfer failed, error 81
2022-07-21 14:21:08 W/Bot 1234567890: An exception occurred when processing event. Subscriber scope: '<unnamed>'. Broadcaster scope: 'Bot.1234567890.EventDispatcher'
java.lang.IllegalStateException: cannot upload group image, failed on all servers.
	at net.mamoe.mirai.internal.network.highway.Highway.uploadResourceBdh(Highway.kt:449)
	at net.mamoe.mirai.internal.network.highway.Highway$uploadResourceBdh$1.invokeSuspend(Highway.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: highway transfer failed, error 81
	at net.mamoe.mirai.internal.network.highway.HighwayKt.sendReceiveHighway(Highway.kt:359)
	at net.mamoe.mirai.internal.network.highway.HighwayKt.access$sendReceiveHighway(Highway.kt:1)
	at net.mamoe.mirai.internal.network.highway.HighwayKt$sendReceiveHighway$1.invokeSuspend(Highway.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 6 more
	Suppressed: java.lang.IllegalStateException: highway transfer failed, error 81
		... 11 more
		Suppressed: java.lang.IllegalStateException: highway transfer failed, error 81
			... 11 more
			Suppressed: java.lang.IllegalStateException: highway transfer failed, error 81
				... 11 more
				Suppressed: java.lang.IllegalStateException: highway transfer failed, error 81
					... 11 more


Process finished with exit code 130

```

**Comment by Him188** [comment]
> 检查 Native 目标的运行情况

看了一下多半不能跑
