### ISSUE TITLE
发送图片遇到问题

### ISSUE THREAD

**Issue by KJZH001** [mamoe/mirai#2168]
### 问题描述

尝试发送图片时，有部分图片一直无法被发送，一尝试发送就会报错

由于看到mcl的公告说明，所以我过来发个issue

注：这些图片在我自己的电脑上和手机上都是可以正常打开的

图片来自于我的一个同学的整理打包

### 复现

似乎没有太多可以说明的复现步骤，这里我贴出我的相关代码段

只要被触发发送了相关的图片，就一定会产生相关错误
```
                val rand=功能().随机数(0,方舟干员类型.size)
                val 目录路径=功能().初始路径+"\\明日方舟抽卡\\"+方舟干员类型[rand]
                val 文件列表=功能().获取文件列表(目录路径)
                val 文件数量=文件列表.size
                val 目标图片路径=文件列表.get(功能().随机数(0,文件数量))
                logger.info { "当前QQ "+sender.id+" 抽干员发送的图片："+目标图片路径 }
                val image=subject.uploadImage(File(目标图片路径))
                val msg = PlainText("诶，我们罗德岛的咸鱼医生居然想着今天来拉包了吗？\n")
                    .plus("那么，来一起看看会招聘到谁吧~\n")
                    .plus(At(sender.id))
                    .plus(image)
                subject.sendMessage(msg)
```
（如果可以，希望请不要吐槽我的中文方法名和类名XD）

### mirai-core 版本

（Mirai-console）Backend: version 2.11.0, built on 2022-05-19 22:08:40

### bot-protocol

ANDROID_PHONE

### 其他组件版本

```

  21:04:01 [INFO] Verifying "net.mamoe:mirai-console" v2.11.0
  21:04:01 [WARN] Package "net.mamoe:mirai-console" has newer version "2.12.0"
  21:04:01 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.11.0
  21:04:01 [WARN] Package "net.mamoe:mirai-console-terminal" has newer version "2.12.0"
  21:04:01 [INFO] Verifying "net.mamoe:mirai-core-all" v2.11.0
  21:04:03 [WARN] Package "net.mamoe:mirai-core-all" has newer version "2.12.0"
  21:04:03 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2
  21:04:03 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
  21:04:03 [INFO] Verifying "org.itxtech:soyuz" v1.0.0
  21:04:03 [INFO] Verifying "net.mamoe:chat-command" v0.5.1
  21:04:04 [INFO] Verifying "net.mamoe:mirai-api-http" v2.5.2
```

### 系统日志

```text
2022-07-27 21:10:18 I/空梦云-萌界核心: 当前QQ 1556251405 抽干员发送的图片：C:\Users\Administrator\Desktop\空梦云-萌界核 心\明日方舟抽卡\重装\5 火神.png
2022-07-27 21:10:18 E/Bot.447509623: java.lang.IllegalStateException: Exception while broadcasting event 'GroupMessageEvent'
java.lang.IllegalStateException: Exception while broadcasting event 'GroupMessageEvent'
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcast$suspendImpl(EventDispatcher.kt:96)
        at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcast$1.invokeSuspend(EventDispatcher.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:202)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:202)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.IllegalStateException: 未找到异常处理器. 请继承 SimpleListenerHost 中的 handleException 方法, 或在 构造 SimpleListenerHost 时提供 CoroutineExceptionHandler
------------
Cannot find exception handler from coroutineContext.
Please extend SimpleListenerHost.handleException or provide a CoroutineExceptionHandler to the constructor of SimpleListenerHost
        at net.mamoe.mirai.event.SimpleListenerHost.handleException(JvmMethodListeners.kt:192)
        at net.mamoe.mirai.event.SimpleListenerHost$special$$inlined$CoroutineExceptionHandler$1.handleException(CoroutineExceptionHandler.kt:111)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:52)
        at net.mamoe.mirai.internal.event.Handler$onEvent$1.invokeSuspend(InternalEventListeners.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        ... 8 more
Caused by: net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callFunction(JvmMethodListenersInternal.kt:91)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callFunction(JvmMethodListenersInternal.kt:1)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callFunction$1.invokeSuspend(JvmMethodListenersInternal.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Unsupported image type (mirai) for ExternalResource net.mamoe.mirai.internal.utils.ExternalResourceImplByFile@148e88b7, considering use gif/png/bmp/jpg format. image header: 52 49 46 46 E2 91 00 00 57 45 42 50 56 50 38 58 0A 00 00 00 20 00 00 00 AD 03 00 9F 02 00
        at net.mamoe.mirai.internal.message.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:160)
        at net.mamoe.mirai.internal.contact.GroupImpl$uploadImage$lambda-19$$inlined$runBIO$1.invoke(CoroutineUtils.kt:194)
        at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
        at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
        at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        ... 4 more
```
```


### 网络日志

_No response_

### 补充信息

图片样本：
[https://drive.moeworld.tech/zh-CN/%E5%AD%98%E6%A1%A3/2022.07.29/%E9%A1%B9%E7%9B%AE-1.zip](https://drive.moeworld.tech/zh-CN/%E5%AD%98%E6%A1%A3/2022.07.29/%E9%A1%B9%E7%9B%AE-1.zip)

压缩包里的应该都是发不出去的图片

**Comment by Karlatemp** [comment]
```
C:\Users\32798>echo "52 49 46 46 E2 91 00 00 57 45 42 50 56 50 38 58 0A 00 00 00 20 00 00 00 AD 03 00 9F 02 00" | xxd -p -r | xxd
00000000: 5249 4646 e291 0000 5745 4250 5650 3858  RIFF....WEBPVP8X
00000010: 0a00 0000 2000 0000 ad03 009f 0200       .... .........
```

这是一张 webp 图片, 见 #1584
