### ISSUE TITLE
因日志文件被占用导致不能多开

### ISSUE THREAD

**Issue by zxin8580** [mamoe/mirai#2186]
```
[ERROR] java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
        at org.itxtech.mcl.Loader.start(Loader.java:189)
        at org.itxtech.mcl.Loader.main(Loader.java:79)
Caused by: java.nio.file.FileSystemException: C:\Mirai\logs\latest.log -> C:\Mirai\logs\log-2.log: 另一个程序正在使用此文件，进程无法访问。

        at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileCopy.move(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.move(Unknown Source)
        at java.base/java.nio.file.Files.move(Unknown Source)
        at net.mamoe.mirai.console.terminal.LoggingServiceI.startup$switchLogFile(LoggingService.kt:95)
        at net.mamoe.mirai.console.terminal.LoggingServiceI.startup(LoggingService.kt:100)
        at net.mamoe.mirai.console.terminal.MiraiConsoleImplementationTerminal.<init>(MiraiConsoleImplementationTerminal.kt:113)
        at net.mamoe.mirai.console.terminal.MiraiConsoleImplementationTerminal.<init>(MiraiConsoleImplementationTerminal.kt:60)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
        ... 13 more
```
因为使用了Mirai Native，使得有时需要在同路径下多开Mirai Console，是否能考虑通过优化日志的逻辑或不占用文件，避免多开报错的情况，2.10.1及之前版本中无此问题

**Comment by zxin8580** [comment]
`--no-logging`关闭日志后问题解决
