### ISSUE TITLE
仍然无法接收群消息

### ISSUE THREAD

**Issue by HoshinoTented** [mamoe/mirai#22]
Mirai version: 0.8.0
相关 log:
```
Mirai 02:47:04 : ByteReadPacket 群消息=01 00 09 01 00 06 E3 80 82 E3 80 82 19 00 39 01 00 36 AA 02 33 08 06 50 02 60 00 68 00 9A 01 28 08 0A 20 DB 50 C8 01 00 F0 01 00 F8 01 00 90 02 00 98 03 00 A0 03 02 B0 03 00 C0 03 00 D0 03 00 E8 03 00 90 04 80 C0 10 0E 00 0E 01 00 04 00 00 08 E4 07 00 04 00 00 00 04 12 00 28 05 00 04 00 00 00 01 08 00 04 00 00 00 01 02 00 0C E6 88 91 E5 A5 BD E8 8F 9C E5 95 8A 03 00 01 04 04 00 04 00 00 00 10
Mirai 02:47:04 : Packet sent:     GroupPacket.QueryGroupInfo
Mirai 02:47:04 : Packet received: GroupPacket.InfoResponse.GroupNotFound
java.lang.IllegalStateException: Cannot obtain group info for id 221056495
	at net.mamoe.mirai.Bot$ContactSystem.getGroup-aCOW_bc(Bot.kt:204)
	at net.mamoe.mirai.Bot$ContactSystem$getGroup$2.invokeSuspend(Bot.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
	at kotlinx.coroutines.TimeoutCoroutine.afterCompletionInternal(Timeout.kt:100)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:310)
	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:236)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:849)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:811)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:787)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: net.mamoe.mirai.utils.GroupNotFoundException
	at net.mamoe.mirai.Bot$ContactSystem.getGroup-aCOW_bc(Bot.kt:200)
	... 15 more
```

**Comment by Him188** [comment]
估计是 InternalId 算错
