### ISSUE TITLE
事件重复广播的问题仍然存在

### ISSUE THREAD

**Issue by sandtechnology** [mamoe/mirai#221]
## 问题
刚刚就在mirai群内复现的bug，因为事件重复广播的问题导致了群成员未找到
```
> Bot(3068879961) 12:26:20 : Event: MemberLeaveEvent.Quit(member=Member(754734680))
> Network(3068879961) 12:26:20 : Send: OnlinePush.RespPush
> Bot(3068879961) 12:26:20 : [mirai(655057127)] (1193049506) -> [mirai:source:1784977218]山前阿姊个姬器宁 滚蛋了
> Network(3068879961) 12:26:26 : Event: net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPushNotify@36736982
> Network(3068879961) 12:26:26 : Send: MessageSvc.PbGetMsg
> Bot(3068879961) 12:26:26 : Event: Active(member=Member(754734680))
> Bot(3068879961) 12:26:26 : [mirai(655057127)] (1193049506) -> [mirai:source:152884172]欢迎 山前阿姊个姬器宁 
> Bot(3068879961) 12:26:28 : [mirai(655057127)] (1193049506) -> [mirai:source:784277325]山前阿姊个姬器宁 滚蛋了
> Bot(3068879961) 12:26:28 : Event: MemberLeaveEvent.Quit(member=Member(754734680))
> Network(3068879961) 12:26:28 : Send: OnlinePush.RespPush
> Network(3068879961) 12:26:37 : Send done: Heartbeat.Alive
> Network(3068879961) 12:26:37 : Event: Heartbeat.Alive.Response
> Bot(3068879961) 12:26:38 : [mirai(655057127)] ...(1846913566) -> [mirai:source:692939947][mirai:at:1040400290] [mirai:image:{BCB08495-3F24-E351-C5AA-66B26E8BBEA9}.jpg]
> Bot(3068879961) 12:26:54 : [mirai(655057127)] ...(1846913566) -> [mirai:source:1190909219]botPermssion 没 init 吗
> Bot(3068879961) 12:26:58 : [mirai(655057127)] 垃圾 Kotlin(1040400290) -> [mirai:source:1929484418]0.36.1
> java.util.NoSuchElementException: member 754734680 not found in group 655057127
> 	at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:246)
> 	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$PbPushGroupMsg.decode(OnlinePush.kt:85)
> 	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:491)
> 	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:224)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:392)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:387)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:372)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> Bot(3068879961) 12:27:01 : [mirai(655057127)] 垃圾 Kotlin(1040400290) -> [mirai:source:1151423915]修了这个问题
> Bot(3068879961) 12:27:05 : [mirai(655057127)] saeziae(1405538335) -> [mirai:source:564060962]qwq
> java.util.NoSuchElementException: member 754734680 not found in group 655057127
> 	at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:246)
> 	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$PbPushGroupMsg.decode(OnlinePush.kt:85)
> 	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:491)
> 	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:224)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:392)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:387)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:372)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> 
```
## 如何复现
让某个群成员退群再进群

**Comment by Him188** [comment]
??都已经有sequence缓存了，除非服务器把这个包发了三次
