### ISSUE TITLE
通过mcl启动mirai时报错

### ISSUE THREAD

**Issue by fatinghenji** [mamoe/mirai#2224]
### 问题描述

启动mirai时报错

### 复现

1.使用`stop`命令停止
2.使用`./mcl`启动
3.报错产生

### mirai-core 版本

2.12.1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

```
2022-08-30 17:53:06 I/plugin: Successfully loaded plugin ApexLookUp v1.6.0                                                                                                                  
2022-08-30 17:53:06 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.5.2                                                                                                    
2022-08-30 17:53:06 I/plugin: Successfully loaded plugin OneBot v0.3.4                                                                                                                      
2022-08-30 17:53:06 I/plugin: Successfully loaded plugin Chat Command v0.5.0                                                                                                                
2022-08-30 17:53:06 I/plugin: Successfully loaded plugin MCL Addon v2.0.2  
```

### 系统日志

```text
2022-08-30 17:53:09 E/main: NettyChannelException(message=null, cause=null)                                                                                                                 
NettyChannelException(message=null, cause=null)                                                                                                                                             
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.createConnection$lambda-3(NettyNetworkHandler.kt:177)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552) 
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1186)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:773)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:749)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:105)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:174)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.util.concurrent.CancellationException: NetworkHandler closed
                at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
                at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:596)
                at kotlinx.coroutines.JobKt.cancel(Unknown Source)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.close(NetworkHandlerSupport.kt:61)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:205)
                ... 22 more
        Caused by: [CIRCULAR REFERENCE: NettyChannelException(message=null, cause=null)]
        Suppressed: StateSwitchingException(old=StateLoading, new=StateClosed, cause=NettyChannelException(message=null, cause=null))
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:302)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:422)
                ... 22 more
        Caused by: [CIRCULAR REFERENCE: NettyChannelException(message=null, cause=null)]
        Suppressed: [CIRCULAR REFERENCE: java.util.concurrent.CancellationException: NetworkHandler closed]

2022-08-30 17:53:09 I/Bot.1026152696: Bot cancelled: Bot closed
```

### 网络日志
[网络日志.log](https://github.com/mamoe/mirai/files/9451866/2022-08-30.log)

### 补充信息
该问题在[断线一分钟后仍未重连 #1361](https://github.com/mamoe/mirai/issues/1361)，中出现过。

**Comment by fatinghenji** [comment]
补充：
使用`login`命令手动登陆后，出现新的报错，如下：
```java
2022-08-30 18:24:36 I/Bot.1026152696: Loaded account secrets from local cache.                                                                                                              
2022-08-30 18:24:36 I/Bot.1026152696: Saved account secrets to local cache for fast login.                                                                                                  
2022-08-30 18:24:36 I/Bot.1026152696: Login successful.                                                                                                                                     
2022-08-30 18:24:37 V/Bot.1026152696: Event: BotOnlineEvent(bot=Bot(1026152696))                                                                                                            
2022-08-30 18:24:37 I/OneBot: Bot: 1026152696 HTTP API服务端是否配置开启: false                                                                                                             
2022-08-30 18:24:37 I/OneBot: Bot: 1026152696 正向Websocket服务端是否配置开启: false                                                                                                        
2022-08-30 18:24:37 I/OneBot: Bot: 1026152696 已开启接收图片缓存, 将会缓存收取到的所有图片                                                                                                  
2022-08-30 18:24:37 I/OneBot: Bot: 1026152696 已开启接收语音缓存, 将会缓存收取到的所有语音                                                                                                  
2022-08-30 18:24:37 I/OneBot: Bot: 1026152696 已开启心跳机制, 设定的心跳发送频率为 15000 毫秒                                                                                               
2022-08-30 18:24:37 I/Bot.1026152696: Bot login successful.                                                                                                                                 
BOT (1026152696) Login successful                                                                                                                                                           
2022-08-30 18:24:37 V/Bot.1026152696: Event: BotOfflineEvent.Dropped(bot=Bot(1026152696), cause=NettyChannelException(message=null, cause=null), reconnect=true)                            
2022-08-30 18:24:37 W/Bot.1026152696: Connection lost, reconnecting... (NettyChannelException(message=null, cause=null))                                                                    
2022-08-30 18:24:37 I/Bot.1026152696: Saved account secrets to local cache for fast login.                                                                                                  
2022-08-30 18:24:37 I/Bot.1026152696: Login successful.                                                                                                                                     
2022-08-30 18:24:37 V/Bot.1026152696: Event: BotOnlineEvent(bot=Bot(1026152696))                                                                                                            
2022-08-30 18:24:37 V/Bot.1026152696: Event: BotReloginEvent(bot=Bot(1026152696), cause=null)                                                                                               
2022-08-30 18:24:37 I/Bot.1026152696: Reconnected successfully in 0.188s.                                                                                                                   
2022-08-30 18:25:06 E/main: Exception in coroutine Bot 1026152696.MessageSvcSyncerImpl                                                                                                      
java.lang.IllegalStateException: timeout syncing friend message history.                                                                                                                    
        at net.mamoe.mirai.internal.network.components.MessageSvcSyncerImpl.syncMessageSvc(MessageSvcSyncer.kt:67)                                                                          
        at net.mamoe.mirai.internal.network.components.MessageSvcSyncerImpl.access$syncMessageSvc(MessageSvcSyncer.kt:34)                                                                   
        at net.mamoe.mirai.internal.network.components.MessageSvcSyncerImpl$syncMessageSvc$1.invokeSuspend(MessageSvcSyncer.kt)                                                             
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                                                                           
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)                                                                                                                     
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)                                                                                            
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)                                                                                   
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)                                                                                     
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)                                                                                           
                                                                                                                                                                                            
2022-08-30 18:25:31 V/Bot.1026152696: [纯狱天花板(1141089633)] 惹(425385212) -> 我ff15                                                                                                      
2022-08-30 18:25:37 V/Bot.1026152696: Event: BotOfflineEvent.RequireReconnect(bot=Bot(1026152696), cause=java.lang.IllegalStateException: Timeout waiting for ConfigPush., reconnect=true)  
2022-08-30 18:25:37 W/Bot.1026152696: Connection lost, reconnecting... (java.lang.IllegalStateException: Timeout waiting for ConfigPush.)                                                   
2022-08-30 18:25:37 V/Bot.1026152696: Event: BotOfflineEvent.Active(bot=Bot(1026152696), cause=java.lang.IllegalStateException: Timeout waiting for ConfigPush., reconnect=false)           
2022-08-30 18:25:37 I/Bot.1026152696: Bot is closed manually with exception: java.lang.IllegalStateException: Timeout waiting for ConfigPush.                                               
java.lang.IllegalStateException: Timeout waiting for ConfigPush.                                                                                                                            
        at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl.syncConfigPush(ConfigPushProcessor.kt:45)                                                                    
        at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl$syncConfigPush$1.invokeSuspend(ConfigPushProcessor.kt)                                                       
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                                                                           
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)                
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: java.util.concurrent.CancellationException: NetworkHandler closed
                at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
                at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:596)
                at kotlinx.coroutines.JobKt.cancel(Unknown Source)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.close(NetworkHandlerSupport.kt:61)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:205)
                at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:98)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.onEvent$closeNetwork(BotOfflineEventMonitor.kt:61)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.onEvent(BotOfflineEventMonitor.kt:86)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.access$onEvent(BotOfflineEventMonitor.kt:46)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl$attachJob$$inlined$subscribeAlways$default$1.invokeSuspend(EventChannelKotlinExtensions.kt:174)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl$attachJob$$inlined$subscribeAlways$default$1.invoke(EventChannelKotlinExtensions.kt)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl$attachJob$$inlined$subscribeAlways$default$1.invoke(EventChannelKotlinExtensions.kt)
                at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:511)
                at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
                at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
                at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invokeSuspend(SafeListener.kt:58)
                at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
                at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
                at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
                at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
                at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:58)
                at net.mamoe.mirai.internal.event.EventListeners.process(EventListeners.kt:119)
                at net.mamoe.mirai.internal.event.EventListeners.access$process(EventListeners.kt:33)
                at net.mamoe.mirai.internal.event.EventListeners$callListeners$2$1.invokeSuspend(EventListeners.kt:90)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                ... 4 more
        Caused by: [CIRCULAR REFERENCE: java.lang.IllegalStateException: Timeout waiting for ConfigPush.]
```
**本来以为我这个问题是孤例，但在Amiya-Bot里面遇到了有相同问题的人**

**Comment by fatinghenji** [comment]
再补充：再次重启之后问题消失了。

**Comment by fatinghenji** [comment]
再次补充日志文件，重新使用`./mcl`登陆后，正常收取1~2条消息后，出现新报错：
```java
2022-08-30 18:34:09 V/Bot.1026152696: Event: BotOfflineEvent.RequireReconnect(bot=Bot(1026152696), cause=java.lang.IllegalStateException: Timeout waiting for ConfigPush., reconnect=true)  
2022-08-30 18:34:09 W/Bot.1026152696: Connection lost, reconnecting... (java.lang.IllegalStateException: Timeout waiting for ConfigPush.)                                                   
2022-08-30 18:34:09 V/Bot.1026152696: Event: BotOfflineEvent.Active(bot=Bot(1026152696), cause=java.lang.IllegalStateException: Timeout waiting for ConfigPush., reconnect=false)           
2022-08-30 18:34:09 I/Bot.1026152696: Bot is closed manually with exception: java.lang.IllegalStateException: Timeout waiting for ConfigPush.                                               
java.lang.IllegalStateException: Timeout waiting for ConfigPush.                                                                                                                            
        at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl.syncConfigPush(ConfigPushProcessor.kt:45)                                                                    
        at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl$syncConfigPush$1.invokeSuspend(ConfigPushProcessor.kt)                                                       
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                                                                           
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)                                                                                                             
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)                                                                                                        
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)                                                                                           
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: java.util.concurrent.CancellationException: NetworkHandler closed
                at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
                at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:596)
                at kotlinx.coroutines.JobKt.cancel(Unknown Source)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.close(NetworkHandlerSupport.kt:61)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:205)
                at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:98)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.onEvent$closeNetwork(BotOfflineEventMonitor.kt:61)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.onEvent(BotOfflineEventMonitor.kt:86)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.access$onEvent(BotOfflineEventMonitor.kt:46)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl$attachJob$$inlined$subscribeAlways$default$1.invokeSuspend(EventChannelKotlinExtensions.kt:174)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl$attachJob$$inlined$subscribeAlways$default$1.invoke(EventChannelKotlinExtensions.kt)
                at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl$attachJob$$inlined$subscribeAlways$default$1.invoke(EventChannelKotlinExtensions.kt)
                at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:511)
                at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
                at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
                at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invokeSuspend(SafeListener.kt:58)
                at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
                at net.mamoe.mirai.internal.event.SafeListener$onEvent$2.invoke(SafeListener.kt)
                at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
                at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
                at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
                at net.mamoe.mirai.internal.event.SafeListener.onEvent(SafeListener.kt:58)
                at net.mamoe.mirai.internal.event.EventListeners.process(EventListeners.kt:119)
                at net.mamoe.mirai.internal.event.EventListeners.access$process(EventListeners.kt:33)
                at net.mamoe.mirai.internal.event.EventListeners$callListeners$2$1.invokeSuspend(EventListeners.kt:90)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                ... 4 more
        Caused by: [CIRCULAR REFERENCE: java.lang.IllegalStateException: Timeout waiting for ConfigPush.]
```

**Comment by Him188** [comment]
此问题已在 2.13 dev 解决
