### ISSUE TITLE
QuoteReply回复消息好像不能回复MessageSourceBuilder出来的

### ISSUE THREAD

**Issue by Coloryr** [mamoe/mirai#2239]
### 问题描述

```java
MessageSource source = new MessageSourceBuilder()
                            .id(ids1)
                            .internalId(ids2)
                            .build(qq, MessageSourceKind.GROUP);
                    QuoteReply quoteReply = new QuoteReply(source);
```
![Y$F_{OAH1P17YPG 3)XMCPA](https://user-images.githubusercontent.com/26276037/188783895-220602f5-a12c-4c30-b197-7eed9ec47f52.png)
![I03P%7VPR1GI%SQ YJBEQKW](https://user-images.githubusercontent.com/26276037/188783905-ca7ccac3-7413-4161-abbd-1986142028c0.jpg)

### 复现

使用MessageSourceBuilder只设置ids和internalId然后回复

### mirai-core 版本

2.12.2

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
[0m2022-09-07 11:35:24 V/Bot 2315986522: Event: BotOfflineEvent.Active(bot=Bot(2315986522), cause=kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelled}@3b8b1365, reconnect=false)[0m
[92m2022-09-07 11:35:57 I/Bot 2315986522: Loaded account secrets from local cache.[0m
[92m2022-09-07 11:35:58 I/Bot 2315986522: Saved account secrets to local cache for fast login.[0m
[92m2022-09-07 11:35:58 I/Bot 2315986522: Login successful.[0m
[0m2022-09-07 11:35:59 V/Bot 2315986522: Event: BotOnlineEvent(bot=Bot(2315986522))[0m
[92m2022-09-07 11:35:59 I/Bot 2315986522: Bot login successful.[0m
[0m2022-09-07 11:36:17 V/Bot 2315986522: [当了x年的JK，不知不觉就抱得美人归了(571239090)] Coloryr(402067010) -> 精华[0m
[0m2022-09-07 11:36:24 V/Bot 2315986522: Group(571239090) <- 402067010 你发送了消息 精华[0m
[0m2022-09-07 11:36:29 V/Bot 2315986522: Group(571239090) <- 设置精华消息[0m
[0m2022-09-07 11:36:57 V/Bot 2315986522: Event: BotGroupPermissionChangeEvent(group=Group(571239090), origin=MEMBER, new=ADMINISTRATOR)[0m
[0m2022-09-07 11:37:02 V/Bot 2315986522: [当了x年的JK，不知不觉就抱得美人归了(571239090)] Coloryr(402067010) -> 精华[0m
[0m2022-09-07 11:37:05 V/Bot 2315986522: Group(571239090) <- 402067010 你发送了消息 精华[0m
[0m2022-09-07 11:37:06 V/Bot 2315986522: Group(571239090) <- 设置精华消息[0m
[0m2022-09-07 11:37:22 V/Bot 2315986522: [当了x年的JK，不知不觉就抱得美人归了(571239090)] Coloryr(402067010) -> 回复[0m
[0m2022-09-07 11:37:30 V/Bot 2315986522: Group(571239090) <- 402067010 你发送了消息 回复[0m
[0m2022-09-07 11:37:48 V/Bot 2315986522: Group(571239090) <- [mirai:quote:[mirai:source:ids=[1282579], internalIds=[0], from 0 to 0 at 1662521862], content=]回复消息[0m
[0m2022-09-07 11:37:56 V/Bot 2315986522: [当了x年的JK，不知不觉就抱得美人归了(571239090)] lingfengyiyu(2755126858) -> 又是什么好玩的[0m
```

### 网络日志

```text
[0m2022-09-07 11:35:59 V/Net 2315986522: Recv: friendlist.GetTroopMemberListReq[0m
[92m2022-09-07 11:35:59 I/Net 2315986522: Successfully loaded group list: 3 in total.[0m
[92m2022-09-07 11:35:59 I/Net 2315986522: Scheduled refresh login session in 19d 23h 55min 0.0s.[0m
[92m2022-09-07 11:35:59 I/Net 2315986522: Scheduled key refresh in 23h 55min 0.0s.[0m
[0m2022-09-07 11:36:01 V/Net 2315986522: Saving bdh session to cache[0m
[0m2022-09-07 11:36:01 V/Net 2315986522: Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)[0m
[0m2022-09-07 11:36:01 V/Net 2315986522: Recv: ConfigPushSvc.PushReq[0m
[0m2022-09-07 11:36:24 V/Net 2315986522: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-09-07 11:36:24 V/Net 2315986522: Recv: MessageSvc.PbSendMsg[0m
[0m2022-09-07 11:36:28 V/Net 2315986522: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-09-07 11:36:29 V/Net 2315986522: Recv: MessageSvc.PbSendMsg[0m
[0m2022-09-07 11:36:57 V/Net 2315986522: Recv: OnlinePush.PbPushTransMsg[0m
[0m2022-09-07 11:37:05 V/Net 2315986522: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-09-07 11:37:05 V/Net 2315986522: Recv: MessageSvc.PbSendMsg[0m
[0m2022-09-07 11:37:06 V/Net 2315986522: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-09-07 11:37:06 V/Net 2315986522: Recv: MessageSvc.PbSendMsg[0m
[0m2022-09-07 11:37:06 V/Net 2315986522: Send: OidbSvc.0xeac_1(OidbSvc.0xeac_1)[0m
[0m2022-09-07 11:37:06 V/Net 2315986522: Recv: OidbSvc.0xeac_1[0m
[0m2022-09-07 11:37:30 V/Net 2315986522: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-09-07 11:37:30 V/Net 2315986522: Recv: MessageSvc.PbSendMsg[0m
[0m2022-09-07 11:37:48 V/Net 2315986522: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-09-07 11:37:48 V/Net 2315986522: Recv: MessageSvc.PbSendMsg[0m
```
```


### 补充信息

_No response_

**Comment by cssxsh** [comment]
不是应该还有个 `time` 属性吗

**Comment by Coloryr** [comment]
好像撤回也不行
```java
try {
      Bot bot = bots.get(item.bot);
      MessageSource message = new MessageSourceBuilder()
              .id(item.ids1)
              .internalId(item.ids2)
              .build(item.bot, item.kind);
      Mirai.getInstance().recallMessage(bot, message);
  } catch (Exception e) {
      ColorMiraiMain.logger.error("消息撤回失败", e);
  }
```
```
java.lang.IllegalStateException: Failed to recall message #[1282627]: Failed(result=154, errorMessage=time out)
	at net.mamoe.mirai.internal.MiraiImpl.recallMessage$suspendImpl(MiraiImpl.kt:590) ~[mirai-core-jvm-2.12.2.jar:2.12.2]
	at net.mamoe.mirai.internal.MiraiImpl$recallMessage$1.invokeSuspend(MiraiImpl.kt) ~[mirai-core-jvm-2.12.2.jar:2.12.2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.0.jar:1.7.0-release-281(1.7.0)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.7.0.jar:1.7.0-release-281(1.7.0)]
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1412) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:84) ~[mirai-core-jvm-2.12.2.jar:2.12.2]
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:192) ~[mirai-core-jvm-2.12.2.jar:2.12.2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.0.jar:1.7.0-release-281(1.7.0)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.1.jar:?]
```

**Comment by Coloryr** [comment]
> 不是应该还有个 `time` 属性吗

我试试

**Comment by Him188** [comment]
time 可能也是需要的，也有可能需要 group id 和 sender id，这取决于服务器行为。建议尽可能提供全面的属性

**Comment by Coloryr** [comment]
> time 可能也是需要的，也有可能需要 group id 和 sender id，这取决于服务器行为。建议尽可能提供全面的属性

好像对了又好像没对
```
MessageSource source = new MessageSourceBuilder()
                            .target(id)
                            .sender(fid)
                            .time(time)
                            .id(ids1)
                            .internalId(ids2)
                            .build(qq, MessageSourceKind.GROUP);
                    QuoteReply quoteReply = new QuoteReply(source);
```
![UI)E QVR OZ1_B)T~)(N 5W](https://user-images.githubusercontent.com/26276037/188789299-68b8cbae-bcdd-4edf-b049-70c62ec8e6d5.png)

![Screenshot_20220907_123128_com tencent mobileqq](https://user-images.githubusercontent.com/26276037/188789301-c9cc7eb5-413d-4243-8e7c-10a39c85ec32.jpg)

**Comment by Him188** [comment]
还要提供 original messages

**Comment by Him188** [comment]
被引用内容是需要你自己提供的
