### ISSUE TITLE
App类型消息发送失败

### ISSUE THREAD

**Issue by StageGuard** [mamoe/mirai#224]
请求：
POST: http://localhost:8080/sendGroupMessage
params: 
```
{"sessionKey":"我的SessionKey","target":我的群QQ号,"messageChain":[{"type":"App","content":"{\n    \"app\": \"com.tencent.structmsg\",\n    \"config\": {\n        \"autosize\": true,\n        \"ctime\": 1586704226,\n        \"forward\": true,\n        \"token\": \"77943689edb0852dcd79b982d1d10401\",\n        \"type\": \"normal\"\n    },\n    \"desc\": \"音乐\",\n    \"meta\": {\n        \"music\": {\n            \"action\": \"\",\n            \"android_pkg_name\": \"\",\n            \"app_type\": 1,\n            \"appid\": 100495085,\n            \"desc\": \"Yetep/Kyle Reynolds\",\n            \"jumpUrl\": \"http://music.163.com/song/1381490349/\",\n            \"musicUrl\": \"http://m8.music.126.net/20200412233528/e04fae8393ea054def3158ba38c50cd0/ymusic/070b/0558/5409/0aae7794ae221ee4da62cce2d187f4e9.mp3\",\n            \"preview\": \"{$preview}\",\n            \"sourceMsgId\": \"0\",\n            \"source_icon\": \"\",\n            \"source_url\": \"\",\n            \"tag\": \"网易云音乐\",\n            \"title\": \"Petals from a Rose\"\n        }\n    },\n    \"prompt\": \"[分享] Petals from a Rose\",\n    \"ver\": \"0.0.0.1\",\n    \"view\": \"music\"\n}\n"}]}
```
返回：`Server returned HTTP response code: 500 for URL: http://localhost:8080/sendGroupMessage`
core日志：
```
15:10:27 [ERROR] [MiraiAPIHTTP] java.lang.IllegalStateException: image upload failed: Transfer errno=10206                                                               at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImage$$inlined$use$lambda$1.emit(Collect.kt:152)                                                 at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImage$$inlined$use$lambda$1$1.invokeSuspend(Unknown Source)                                      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                                                         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)                   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)                                                                          at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)                                                                   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
看日志似乎是图片上传问题(

**Comment by Him188** [comment]
应该是长消息问题

**Comment by Him188** [comment]
但并不能找出是什么问题
