### ISSUE TITLE
安卓无法登录Mirai

### ISSUE THREAD

**Issue by kagg886** [mamoe/mirai#2245]
### 问题描述

使用gradle时，线程内调用Bot.login()时出错
但密码和账号均填写无误。

### 复现

使用代码如下:
`BotConfiguration c = new BotConfiguration();
        c.fileBasedDeviceInfo(getExternalCacheDir().getPath() + "/device.json");
        Bot b = BotFactory.INSTANCE.newBot(114514,"pass",c);

        new Thread(() -> {
            try {
                b.login();
                b.join();
            } catch (Throwable e) {
                runOnUiThread(() -> {
                    AlertDialog.Builder b1 = new AlertDialog.Builder(MainActivity.this);
                    b1.setMessage(e.getMessage());
                    b1.create().show();
                });
            }
        }).start();`

编译安装APP到模拟器(Android9)

### mirai-core 版本

2.10.1

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2022-09-10 20:43:53.400 12283-12326/com.kagg886.qqbottest I/System.out: [92m2022-09-10 12:43:53 I/Net 1693256674: Successfully fetched ecdh public key from server.[0m
2022-09-10 20:43:53.489 12283-12326/com.kagg886.qqbottest I/System.out: [0m2022-09-10 12:43:53 V/Net 1693256674: Send: wtlogin.login[0m
2022-09-10 20:43:53.734 12283-12326/com.kagg886.qqbottest I/System.out: [0m2022-09-10 12:43:53 V/Net 1693256674: Send: wtlogin.login[0m
2022-09-10 20:43:53.742 12283-12342/com.kagg886.qqbottest I/System.out: [0m2022-09-10 12:43:53 V/Net 1693256674: Recv: wtlogin.login[0m
2022-09-10 20:43:53.911 12283-12343/com.kagg886.qqbottest I/System.out: [0m2022-09-10 12:43:53 V/Net 1693256674: Recv: wtlogin.login[0m
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out: [91m2022-09-10 12:43:53 W/Net 1693256674: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1693256674), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=��)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1693256674), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=��)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out:     at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out:     at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(Unknown Source:14)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out:     at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out:     at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2022-09-10 20:43:53.916 12283-12326/com.kagg886.qqbottest I/System.out: [0m
2022-09-10 20:43:53.924 12283-12326/com.kagg886.qqbottest I/System.out: [92m2022-09-10 12:43:53 I/Bot 1693256674: Bot cancelled: Bot closed[0m
```

### 补充信息
![QQ截图20220910204050](https://user-images.githubusercontent.com/68730049/189484393-cd3eada0-bbf6-4b9c-a6c4-bd1f3bcfcc1f.png)

**Comment by Him188** [comment]
2.13.0-RC解决

**Comment by WaiMaEr** [comment]
什么时候能解决，这个问题，已经很久没有解决方法了，而且解决问题的步骤都是很模糊，不知道你们就是想让我们去专研，或者还是自己找原因。至少希望能有个具体的回答。而不是放一个链接 解决或者怎么样的，没了。既然这个问题很 多开发者都会遇见，那么就放在一个明显的地方，告知大家，而不是在用的过程当中我们又需要百度 看代码一个一个排查。框架框架，就是让开发者使用者，越来越简单 方便。这才是框架的初心

**Comment by cssxsh** [comment]
> 什么时候能解决，这个问题，已经很久没有解决方法了，而且解决问题的步骤都是很模糊，不知道你们就是想让我们去专研，或者还是自己找原因。至少希望能有个具体的回答。而不是放一个链接 解决或者怎么样的，没了。既然这个问题很 多开发者都会遇见，那么就放在一个明显的地方，告知大家，而不是在用的过程当中我们又需要百度 看代码一个一个排查。框架框架，就是让开发者使用者，越来越简单 方便。这才是框架的初心

腾讯的登录对于用户来说就是黑箱，你想要100%的成功的解决方案是不可能的

**Comment by WaiMaEr** [comment]
感谢你能回答。我很想提一个建议，既然这种情况是经常会出现的问题，我想你们在文档首页中，去描述这种情况的原因以及基本的解决方法。这样的好处在于，能解决像我这样的人，大量时间。而不是去不断试错，不断搜索大量文章等其他，最后才发现是这样的问题。&nbsp;


有我在
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月17日(星期五) 下午4:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mamoe/mirai] 安卓无法登录Mirai (Issue #2245)





  
什么时候能解决，这个问题，已经很久没有解决方法了，而且解决问题的步骤都是很模糊，不知道你们就是想让我们去专研，或者还是自己找原因。至少希望能有个具体的回答。而不是放一个链接 解决或者怎么样的，没了。既然这个问题很 多开发者都会遇见，那么就放在一个明显的地方，告知大家，而不是在用的过程当中我们又需要百度 看代码一个一个排查。框架框架，就是让开发者使用者，越来越简单 方便。这才是框架的初心
  
腾讯的登录对于用户来说就是黑箱，你想要100%的成功的解决方案是不可能的

**Comment by kagg886** [comment]
> 

mirai论坛有对于mcl登录失败的解决方案
我这个issues只是对移植到[Android的一个尝试罢了](https://github.com/kagg886/Seiko)。

**Comment by kagg886** [comment]
> 感谢你能回答。我很想提一个建议，既然这种情况是经常会出现的问题，我想你们在文档首页中，去描述这种情况的原因以及基本的解决方法。这样的好处在于，能解决像我这样的人，大量时间。而不是去不断试错，不断搜索大量文章等其他，最后才发现是这样的问题。&nbsp; 有我在 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年2月17日(星期五) 下午4:17 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [mamoe/mirai] 安卓无法登录Mirai (Issue #2245) 什么时候能解决，这个问题，已经很久没有解决方法了，而且解决问题的步骤都是很模糊，不知道你们就是想让我们去专研，或者还是自己找原因。至少希望能有个具体的回答。而不是放一个链接 解决或者怎么样的，没了。既然这个问题很 多开发者都会遇见，那么就放在一个明显的地方，告知大家，而不是在用的过程当中我们又需要百度 看代码一个一个排查。框架框架，就是让开发者使用者，越来越简单 方便。这才是框架的初心 腾讯的登录对于用户来说就是黑箱，你想要100%的成功的解决方案是不可能的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

> 

mirai论坛有对于mcl登录失败的解决方案
我这个issues只是对移植到[Android的一个尝试罢了](https://github.com/kagg886/Seiko)。
