### ISSUE TITLE
dev分支拉下来进行登录时提示NoSuchElementException

### ISSUE THREAD

**Issue by Nekoer** [mamoe/mirai#2246]
### 问题描述

运行RunTerminal.kt后使用login命令提示:
`Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider`

### 复现

Dev分支拉下来，运行mirai-console/frontend/mirai-console-terminal/test/RunTerminal.kt后使用login命令

### mirai-core 版本

Dev分支源代码

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
[Mirai Console] Set user.dir = E:\mirai-plugins\mirai\.\mirai-console\frontend\mirai-console-terminal\run
2022-09-10 23:46:48 I/main: Starting mirai-console...
2022-09-10 23:46:48 I/main: Backend: version 2.13.0, built on 2022-09-10 23:46:29.
2022-09-10 23:46:48 I/main: Frontend Terminal: version 2.13.0, provided by Mamoe Technologies
2022-09-10 23:46:48 I/main: Welcome to visit https://mirai.mamoe.net/
2022-09-10 23:46:48 V/main: Loading configurations...
2022-09-10 23:46:51 V/main: Loading JVM plugins...
2022-09-10 23:46:51 V/main: 0 external PluginLoader(s) found. 
2022-09-10 23:46:51 V/main: 0 plugin(s) loaded.
2022-09-10 23:46:51 V/main: Loading PermissionService...
2022-09-10 23:46:52 V/main: Reloaded PermissionService settings.
2022-09-10 23:46:52 V/main: Loading built-in commands...
2022-09-10 23:46:52 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2022-09-10 23:46:52 V/main: Enabling plugins...
2022-09-10 23:46:52 I/main: 0 plugin(s) enabled.
2022-09-10 23:46:53 I/main: mirai-console started successfully.
> LOGIN xxx xxx
2022-09-10 23:47:07 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2022-09-10 23:47:07 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2022-09-10 23:47:07 V/main: Bot 2098723536 working in E:\mirai-plugins\mirai\.\mirai-console\frontend\mirai-console-terminal\run\bots\2098723536
2022-09-10 23:47:08 I/Bot.2098723536: Bot cancelled: Job was cancelled
2022-09-10 23:47:08 E/Bot.2098723536: java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
	at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:21)
	at net.mamoe.mirai.utils.ServicesKt.loadService$default(Services.kt:16)
	at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:34)
	at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:33)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:33)
	at net.mamoe.mirai.event.GlobalEventChannel.context(GlobalEventChannel.kt:50)
	at net.mamoe.mirai.event.FilterEventChannel.context(EventChannel.kt:543)
	at net.mamoe.mirai.event.FilterEventChannel.context(EventChannel.kt:543)
	at net.mamoe.mirai.event.EventChannel.parentScope(EventChannel.kt:336)
	at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.attachJob(BotOfflineEventMonitor.kt:44)
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:176)
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:172)
	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)
	at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:172)
	at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:262)
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:274)
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:267)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:267)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:238)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:51)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:54)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:53)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getScope(SelectorNetworkHandler.kt:53)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:112)
	at net.mamoe.mirai.internal.AbstractBot$coroutineContext$1$1.invoke(AbstractBot.kt:62)
	at net.mamoe.mirai.internal.AbstractBot$coroutineContext$1$1.invoke(AbstractBot.kt:56)
	at kotlinx.coroutines.InvokeOnCompletion.invoke(JobSupport.kt:1392)
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1520)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
	at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:696)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:667)
	at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)
	at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)
	at kotlinx.coroutines.Job$DefaultImpls.cancel$default(Job.kt:183)
	at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:114)
	at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:94)
	at net.mamoe.mirai.Bot.close(Bot.kt:188)
	at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.doLogin$suspendImpl(LoginCommandImpl.kt:38)
	at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.doLogin$mirai_console(LoginCommandImpl.kt)
	at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.handle(LoginCommandImpl.kt:95)
	at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:191)
	at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle$default(BuiltInCommands.kt:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:337)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:167)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
	at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:187)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

Login failed: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
2022-09-10 23:47:08 E/console: java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:337)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:167)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
	at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:187)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
	at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:21)
	at net.mamoe.mirai.utils.ServicesKt.loadService$default(Services.kt:16)
	at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:34)
	at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:33)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:33)
	at net.mamoe.mirai.event.GlobalEventChannel.context(GlobalEventChannel.kt:50)
	at net.mamoe.mirai.event.FilterEventChannel.context(EventChannel.kt:543)
	at net.mamoe.mirai.event.FilterEventChannel.context(EventChannel.kt:543)
	at net.mamoe.mirai.event.EventChannel.parentScope(EventChannel.kt:336)
	at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.attachJob(BotOfflineEventMonitor.kt:44)
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:176)
	at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:172)
	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)
	at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:172)
	at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:262)
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:274)
	at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:267)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:267)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:238)
	at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:51)
	at net.mamoe.mirai.internal.QQAndroidBot.getComponents(QQAndroidBot.kt:170)
	at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:144)
	at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.doLogin$suspendImpl(LoginCommandImpl.kt:36)
	at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.doLogin$mirai_console(LoginCommandImpl.kt)
	at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.handle(LoginCommandImpl.kt:95)
	at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:191)
	at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle$default(BuiltInCommands.kt:185)
	... 24 more

2022-09-11 00:01:21 V/main: Received signal INT
2022-09-11 00:01:21 D/main: Handled  signal INT
2022-09-11 00:01:21 D/main: SHUTDOWN DAEMON STARTED.........
  
进程已结束,退出代码0
```

**Comment by Him188** [comment]
复习了这个问题， 但我不知道怎么解决

**Comment by Karlatemp** [comment]
这个实际上是kt自己的bug
首先定义一个 mpp 项目
然后再另外定义一个项目依赖这个 mpp
这个项目就会缺失 mpp 的资源

**Comment by Karlatemp** [comment]
https://youtrack.jetbrains.com/issue/KTIJ-18536/IDE-run-transitive-dependencies-resources-are-not-resolved
https://youtrack.jetbrains.com/issue/KTIJ-16582/Consumer-KotlinJVM-library-cannot-access-a-KotlinMultiplatform-JVM-target-resources-in-multi-module-Gradle-project

**Comment by Nekoer** [comment]
我在mirai-console/frontend/mirai-console-terminal/build.gradle.kts文件内加上以下代码就能用了

```
val copyResources by tasks.creating(Copy::class){
    dependsOn(":mirai-core:jvmProcessResources")
    dependsOn(":mirai-core-api:jvmProcessResources")
    from(project(":mirai-core").buildDir.resolve("processedResources/jvm"))
    from(project(":mirai-core-api").buildDir.resolve("processedResources/jvm"))
    into(buildDir.resolve("resources"))
}

tasks.getByName("classes").dependsOn(copyResources)
```

**Comment by zemise** [comment]
> 我在mirai-console/frontend/mirai-console-terminal/build.gradle.kts文件内加上以下代码就能用了
> 
> ```
> val copyResources by tasks.creating(Copy::class){
>     dependsOn(":mirai-core:jvmProcessResources")
>     dependsOn(":mirai-core-api:jvmProcessResources")
>     from(project(":mirai-core").buildDir.resolve("processedResources/jvm"))
>     from(project(":mirai-core-api").buildDir.resolve("processedResources/jvm"))
>     into(buildDir.resolve("resources"))
> }
> 
> tasks.getByName("classes").dependsOn(copyResources)
> ```

我也存在这个问题，InternalGlobalEventChannelProvider，但是我用的是build.gradle，稍微有点小白，想按你的方案尝试下，不知道怎么把kt转换过来，还请大佬指点一下

**Comment by Him188** [comment]
这个问题只会存在于 https://youtrack.jetbrains.com/issue/KTIJ-16582/Consumer-Kotlin-JVM-library-cannot-access-a-Kotlin-Multiplatform-JVM-target-resources-in-multi-module-Gradle-project 所说的情况, @abc408880155 你遇到的应该不是这个问题

**Comment by zemise** [comment]
> 这个问题只会存在于 https://youtrack.jetbrains.com/issue/KTIJ-16582/Consumer-Kotlin-JVM-library-cannot-access-a-Kotlin-Multiplatform-JVM-target-resources-in-multi-module-Gradle-project 所说的情况, @abc408880155 你遇到的应该不是这个问题

其实我也不明白我的问题到底是什么，我说下我的情况，耽误大佬一点时间，麻烦了！
我是做一个基于Mirai core的MineCraft的互通聊天插件，一直用的gradle获得的mirai core 2.9.1版本的依赖，没有错误异常，但想更新到新的任何版本，都会出现图中错误

<img width="1305" alt="iShot_2022-11-22_09 41 46" src="https://user-images.githubusercontent.com/46216418/203199687-a3a6d421-9d83-4981-a1c9-1425db16ab9c.png">
<img width="1476" alt="iShot_2022-11-22_10 00 13" src="https://user-images.githubusercontent.com/46216418/203199738-053476e3-3dbb-4ced-a2f1-c4466839a0c6.png">

<img width="1305" alt="iShot_2022-11-22_09 48 00" src="https://user-images.githubusercontent.com/46216418/203199778-a79bb096-a220-4a17-86fc-ee409ade23f4.png">
<img width="1455" alt="iShot_2022-11-22_09 54 12" src="https://user-images.githubusercontent.com/46216418/203199811-5f20a56e-8c90-4782-b529-29aae0065dd1.png">

虽然core2.9以外的版本放进minecraft的插件会报错登陆补上，但我尝试了大部分的版本在IDEA直接运行Mirai的简单机器人登陆代码，都是能正常运行的，尽管偶尔也会报警告

![4B4A1228-DCBD-4B55-AA66-609390ABBD02](https://user-images.githubusercontent.com/46216418/203200200-843a4448-1d5c-43c9-8243-9399d4d99044.png)

下面是我详细的build.gradle
<img width="992" alt="iShot_2022-11-22_10 00 54" src="https://user-images.githubusercontent.com/46216418/203200216-447db7a8-387b-4219-a5b0-3e579a37de2b.png">

由普通MC玩家转为试图学习java，并了解到Mirai，时间还不长，所以描述的有些冗杂，还请见谅

**Comment by Him188** [comment]
果然是mc，这个是类加载器问题，有相关issue了，还没解决，你可以尝试搜一下

**Comment by zemise** [comment]
> 果然是mc，这个是类加载器问题，有相关issue了，还没解决，你可以尝试搜一下

好的，谢谢大佬了，终于有个搜索方向了，不然还是一头雾水

**Comment by zemise** [comment]
> 果然是mc，这个是类加载器问题，有相关issue了，还没解决，你可以尝试搜一下

间断的反复研究了一星期，可能找到了问题所在。因为我始终是core2.9版本是没问题的，而升级就版本就编译错误，我始终怀疑版本可能有变动，因此我将版本固定在core2.13.0-RC2，同时把项目中的每个类反复删除测试，最终发现在bot.getGroup(groupID).sendMessage(MessageChain message)中，如果将MessageChain换成Message就不会报错了。

<img width="781" alt="image" src="https://user-images.githubusercontent.com/46216418/205482537-7dd181ef-1100-464e-b337-1b2dea21480f.png">

我是否可以理解为2.9.2后的版本删除了sendMessage(MessageChain)这种方式？

**Comment by sandtechnology** [comment]
> > 果然是mc，这个是类加载器问题，有相关issue了，还没解决，你可以尝试搜一下
> 
> 间断的反复研究了一星期，可能找到了问题所在。因为我始终是core2.9版本是没问题的，而升级就版本就编译错误，我始终怀疑版本可能有变动，因此我将版本固定在core2.13.0-RC2，同时把项目中的每个类反复删除测试，最终发现在bot.getGroup(groupID).sendMessage(MessageChain message)中，如果将MessageChain换成Message就不会报错了。
> 
> <img alt="image" width="781" src="https://user-images.githubusercontent.com/46216418/205482537-7dd181ef-1100-464e-b337-1b2dea21480f.png">
> 
> 我是否可以理解为2.9.2后的版本删除了sendMessage(MessageChain)这种方式？

可是...这确实就是类加载器问题啊 这个一直没删的 你自己IDE测试也能通过....

**Comment by zemise** [comment]
> > > 果然是mc，这个是类加载器问题，有相关issue了，还没解决，你可以尝试搜一下
> 
> > 
> 
> > 间断的反复研究了一星期，可能找到了问题所在。因为我始终是core2.9版本是没问题的，而升级就版本就编译错误，我始终怀疑版本可能有变动，因此我将版本固定在core2.13.0-RC2，同时把项目中的每个类反复删除测试，最终发现在bot.getGroup(groupID).sendMessage(MessageChain message)中，如果将MessageChain换成Message就不会报错了。
> 
> > 
> 
> > <img alt="image" width="781" src="https://user-images.githubusercontent.com/46216418/205482537-7dd181ef-1100-464e-b337-1b2dea21480f.png">
> 
> > 
> 
> > 我是否可以理解为2.9.2后的版本删除了sendMessage(MessageChain)这种方式？
> 
> 
> 
> 可是...这确实就是类加载器问题啊 这个一直没删的 你自己IDE测试也能通过....

嗯，的确，我的想法有错……，还是挺不能理解这个问题

**Comment by zemise** [comment]
能简单完整复现出这个我遇到的这个问题了，使用IDEA中Minecraft的插件模板，或者其他人成熟的MC插件项目，同时加入Mirai-core 2.9.2以上的版本作为依赖。
只要类中有import net.mamoe.mirai.message.data.MessageChain;甚至只要这简单的一句， 编译的时候就会出现以下问题：

警告: 未知的枚举常量 Kind.RESTRICTED_ABSTRACT_MESSAGE_KEYS
  原因: 找不到net.mamoe.mirai.console.compiler.common.ResolveContext$Kind的类文件
警告: 未知的枚举常量 Kind.RESTRICTED_ABSTRACT_MESSAGE_KEYS

不知道这个是不是就是大佬所说的类加载器问题？
还是那个奇怪的点，我把2.9.2之前的版本全测试了下，就不会出现这个问题

**Comment by Karlatemp** [comment]
@abc408880155 https://github.com/mamoe/mirai/issues/2138#issuecomment-1179673302

**Comment by sandtechnology** [comment]
> 能简单完整复现出这个我遇到的这个问题了，使用IDEA中Minecraft的插件模板，或者其他人成熟的MC插件项目，同时加入Mirai-core 2.9.2以上的版本作为依赖。 只要类中有import net.mamoe.mirai.message.data.MessageChain;甚至只要这简单的一句， 编译的时候就会出现以下问题：
> 
> 警告: 未知的枚举常量 Kind.RESTRICTED_ABSTRACT_MESSAGE_KEYS 原因: 找不到net.mamoe.mirai.console.compiler.common.ResolveContext$Kind的类文件 警告: 未知的枚举常量 Kind.RESTRICTED_ABSTRACT_MESSAGE_KEYS
> 
> 不知道这个是不是就是大佬所说的类加载器问题？ 还是那个奇怪的点，我把2.9.2之前的版本全测试了下，就不会出现这个问题

总之你不应该在这里回复这个问题 这个问题和你遇见的不相干 你需要做的是自己实现一个classloader并warp现有的classloader，然后将JVM的PlatformClassLoader包含进去 然后在加载Mirai前将ThreadContextClassLoader设置为自己warp的（
