### ISSUE TITLE
2.12.1 登录直接报错

### ISSUE THREAD

**Issue by dragon0629** [mamoe/mirai#2252]
> login 2710979412 passwordxxxxx
2022-09-15 13:13:00 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2022-09-15 13:13:00 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2022-09-15 13:13:00 V/main: Bot 2710979412 working in D:\MIRAI_2.12.1\bots\2710979412
2022-09-15 13:13:00 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2022-09-15 13:13:02 I/Bot.2710979412: Bot cancelled: Bot closed
Login failed: Parent job is Cancelling
2022-09-15 13:13:02 E/console: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@5a79ed
kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@5a79ed
Caused by: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: no further information: msfwifi.3g.qq.com/127.94.0.36:8080
        [CIRCULAR REFERENCE:kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@5a79ed]
        Suppressed: java.util.concurrent.CancellationException: Bot closed
                at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
                at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
                at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:84)
                at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
                at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        [CIRCULAR REFERENCE:kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=JobImpl{Cancelled}@5a79ed]
Caused by: java.net.BindException: Cannot assign requested address: no further information
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

版本 2.12.1 ，中午突然不正常，换了几个号都是一样。不会弹出验证码滑块等信息。敲完登录 login qq password 直接报错。

**Comment by dragon0629** [comment]
补充，切换到 2.11.0 可正常弹出滑块验证码
但是滑完还是会提示以上报错。

**Comment by Him188** [comment]
```
Caused by: io.netty.channel.AbstractChannel$AnnotatedSocketException: Cannot assign requested address: no further information: msfwifi.3g.qq.com/127.94.0.36:8080
```
看起来是你网络问题

**Comment by Him188** [comment]
https://www.google.com/search?q=Cannot+assign+requested+address&ie=UTF-8
