### ISSUE TITLE
Internal error: no MessageReceipt was returned from OutgoingMessagePipeline for message

### ISSUE THREAD

**Issue by Cater813** [mamoe/mirai#2264]
### 问题描述

无法使用/qchat

### 复现

/qchat 任意内容

### mirai-core 版本

1.7

### bot-protocol

ANDROID_PHONE

### 其他组件版本

chat2qq 1.6

### 系统日志

```text
> qchat 1
[17:35:16 INFO]: 已发送QQ群聊天消息！
[17:35:16 ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@25a73de1, id=116, owner=me.dreamvoid.chat2qq.bungee.BungeePlugin@4fc71437, task=me.dreamvoid.chat2qq.bungee.commands.qchat$$Lambda$2045/0x000000080130a680@233d40da, delay=0, period=0, running=true) encountered an exception
net.mamoe.mirai.internal.message.ContextualBugReportException: 在 Internal error: no MessageReceipt was returned from OutgoingMessagePipeline for message 时遇到了意料 之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    调试信息: [MC] 后台: 1
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26) ~[?:?]
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20) ~[?:?]
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.getSingleReceipt(MessageProtocolFacade.kt:357) ~[?:?]
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoing(MessageProtocolFacade.kt:326) ~[?:?]
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.preprocessAndSendOutgoing(MessageProtocolFacade.kt) ~[?:?]
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:264) ~[?:?]
        at net.mamoe.mirai.internal.contact.AbstractUserKt$sendMessageImpl$1.invokeSuspend(AbstractUser.kt) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233) ~[?:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[?:?]
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:283) ~[?:?]
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278) ~[?:?]
        at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:260) ~[?:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[?:?]
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[?:?]
```

**Comment by Him188** [comment]
发送的消息内容是什么?

**Comment by NoMathExpectation** [comment]
控制台没有这个指令，请去对应的插件提交issue

**Comment by Him188** [comment]
#2268 有更详细的信息
