### ISSUE TITLE
mirai MPP native 下协议实现

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#2265]
### 问题描述

相同条件下, `Android_pad` 协议报错版本过低, `Android_phone` 正常

### 复现

登录, 协议为 `Android_pad`

### mirai-core 版本

2.13.0-dev-d32a8a56

### bot-protocol

ANDROID_PAD

### 系统日志

协议为 `Android_phone` 下正常日志:
```
2022-10-04 09:33:30 I/Net <BOTID>: ECDH key is invalid, start to fetch ecdh public key from server.
2022-10-04 09:33:31 I/Net <BOTID>: Successfully fetched ecdh public key from server.
2022-10-04 09:33:31 V/Net <BOTID>: Send: wtlogin.login(9:password-login)
2022-10-04 09:33:31 I/Net <BOTID>: Native sender: Value(net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketWithRespType@dec022d0)
2022-10-04 09:33:31 V/Net <BOTID>: Recv: wtlogin.login
2022-10-04 09:33:31 I/Bot <BOTID>: Login successful
2022-10-04 09:33:31 I/Bot <BOTID>: Saved account secrets to local cache for fast login.
2022-10-04 09:33:31 V/Net <BOTID>: Send: StatSvc.register(online)
```
协议为 `Android_pad` 下错误日志:
```
2022-10-04 09:30:22 I/Net <BOTID>: ECDH key is invalid, start to fetch ecdh public key from server.
2022-10-04 09:30:23 I/Net <BOTID>: Successfully fetched ecdh public key from server.
2022-10-04 09:30:23 V/Net <BOTID>: Send: wtlogin.login(9:password-login)
2022-10-04 09:30:23 I/Net <BOTID>: Native sender: Value(net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketWithRespType@1c4023d0)
2022-10-04 09:30:23 V/Net <BOTID>: Recv: wtlogin.login
2022-10-04 09:30:23 W/Net <BOTID>: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(<BOTID>), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
    at 0   ???                                 7ff7b3c771c0       kfun:kotlin.Exception#<init>(kotlin.String?;kotlin.Throwable?){} + 0 
    at 1   ???                                 7ff7b4615120       kfun:net.mamoe.mirai.internal.network.handler.selector.NetworkException#<init>(kotlin.String;kotlin.Throwable?;kotlin.Boolean){} + 0 
    at 2   ???                                 7ff7b45dfb40       kfun:net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException#<init>(net.mamoe.mirai.network.LoginFailedException){} + 0 
    at 3   ???                                 7ff7b45efda0       kfun:net.mamoe.mirai.internal.network.handler.CommonNetworkHandler.StateConnecting.$startState$lambda$1COROUTINE$287.invokeSuspend#internal + 0 
    at 4   ???                                 7ff7b3c832c0       kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} + 0 
    at 5   ???                                 7ff7b3f1efa0       kfun:kotlinx.coroutines.internal.ScopeCoroutine#afterResume(kotlin.Any?){} + 0 
    at 6   ???                                 7ff7b3e8a3f0       kfun:kotlinx.coroutines.AbstractCoroutine#resumeWith(kotlin.Result<1:0>){} + 0 
    at 7   ???                                 7ff7b3c832c0       kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} + 0 
    at 8   ???                                 7ff7b3f13e00       kfun:kotlinx.coroutines.DispatchedTask#run(){} + 0 
    at 9   ???                                 7ff7b3f48ae0       kfun:kotlinx.coroutines.WorkerDispatcher.dispatch$lambda$0#internal + 0 
    at 10  ???                                 7ff7b3f49110       kfun:kotlinx.coroutines.WorkerDispatcher.$dispatch$lambda$0$FUNCTION_REFERENCE$827.invoke#internal + 0 
    at 11  ???                                 7ff7b3f49200       kfun:kotlinx.coroutines.WorkerDispatcher.$dispatch$lambda$0$FUNCTION_REFERENCE$827.$<bridge-UNN>invoke(){}#internal + 0 
    at 12  ???                                 7ff7b3c8f260       WorkerLaunchpad + 0 
    at 13  ???                                 7ff7b5416d50       _ZN6Worker19processQueueElementEb + 0 
    at 14  ???                                 7ff7b5416c00       _ZN12_GLOBAL__N_113workerRoutineEPv + 0 
    at 15  ???                                 7ff7b54213c0       pthread_create_wrapper + 0 
    at 16  ???                                 7ff94c4ce60c       0x0 + 140708703692300 
    at 17  ???                                 7ff94c4ce690       0x0 + 140708703692432 
    at 18  ???                                 7ff94c312430       0x0 + 140708701873200 
    at 19  ???                                 7ff94de4df50       0x0 + 140708730429264 
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(<BOTID>), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
    at 0   ???                                 7ff7b3c771c0       kfun:kotlin.Exception#<init>(kotlin.String?;kotlin.Throwable?){} + 0 
    at 1   ???                                 7ff7b3c77440       kfun:kotlin.RuntimeException#<init>(kotlin.String?;kotlin.Throwable?){} + 0 
    at 2   ???                                 7ff7b415c2c0       kfun:net.mamoe.mirai.network.LoginFailedException#<init>(kotlin.Boolean;kotlin.String?;kotlin.Throwable?){} + 0 
    at 3   ???                                 7ff7b415c380       kfun:net.mamoe.mirai.network.LoginFailedException#<init>(kotlin.Boolean;kotlin.String?;kotlin.Throwable?;kotlin.Int;kotlin.native.internal.DefaultConstructorMarker?){} + 0 
    at 4   ???                                 7ff7b415c910       kfun:net.mamoe.mirai.network.WrongPasswordException#<init>(kotlin.String?){} + 0 
    at 5   ???                                 7ff7b45d8100       kfun:net.mamoe.mirai.internal.network.components.SsoProcessorImpl.SlowLoginImpl.$doLoginCOROUTINE$273.invokeSuspend#internal + 0 
    at 6   ???                                 7ff7b3c832c0       kfun:kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(kotlin.Result<kotlin.Any?>){} + 0 
    ... and 15 more common stack frames skipped

2022-10-04 09:30:23 W/Net <BOTID>: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(<BOTID>), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= ))

net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(<BOTID>), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(<BOTID>), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
	at kotlin.Exception#<init>(Unknown Source)
	at kotlin.RuntimeException#<init>(Unknown Source)
	at net.mamoe.mirai.network.LoginFailedException#<init>(Unknown Source)
	at net.mamoe.mirai.network.LoginFailedException#<init>(Unknown Source)
	at net.mamoe.mirai.network.WrongPasswordException#<init>(Unknown Source)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.SlowLoginImpl.$doLoginCOROUTINE$273.invokeSuspend#internal(Unknown Source)
	at kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(Unknown Source)
	at kotlinx.coroutines.internal.ScopeCoroutine#afterResume(Unknown Source)
	at kotlinx.coroutines.AbstractCoroutine#resumeWith(Unknown Source)
	at kotlin.coroutines.native.internal.BaseContinuationImpl#resumeWith(Unknown Source)
	at kotlinx.coroutines.DispatchedTask#run(Unknown Source)
	at kotlinx.coroutines.WorkerDispatcher.dispatch$lambda$0#internal(Unknown Source)
	at kotlinx.coroutines.WorkerDispatcher.$dispatch$lambda$0$FUNCTION_REFERENCE$827.invoke#internal(Unknown Source)
	at kotlinx.coroutines.WorkerDispatcher.$dispatch$lambda$0$FUNCTION_REFERENCE$827.$<bridge-UNN>invoke(Unknown Source)
	at <global>.WorkerLaunchpad(Unknown Source)
	at <global>._ZN6Worker19processQueueElementEb(Unknown Source)
	at <global>._ZN12_GLOBAL__N_113workerRoutineEPv(Unknown Source)
	at <global>.pthread_create_wrapper(Unknown Source)
	at <global>.0x0(Unknown Source)
	at <global>.0x0(Unknown Source)
	at <global>.0x0(Unknown Source)
	at <global>.0x0(Unknown Source)
```

**Comment by Nambers** [comment]
准确来说，好像只有 `PHONE` 协议可用

**Comment by Him188** [comment]
JVM也不行么

**Comment by Nambers** [comment]
> JVM也不行么

就, jvm 本身是可以的，但是native下我试了下只有 phone 可以，而且登上去后只收到了一开始的 BotOnlineEvent, 其他的 Event 都不能接收。不知道是我号的问题还是什么问题

**Comment by Him188** [comment]
不确定是为什么，理论上这部分代码是 common 里写的不会出问题，仅有 ECDH 是有多平台的

**Comment by Nambers** [comment]
> 不确定是为什么，理论上这部分代码是 common 里写的不会出问题，仅有 ECDH 是有多平台的

我换个版本试一下，以及native可以开网络层显示吗

**Comment by AdoptOSS** [comment]
> net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(<BOTID>), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )


请确定一下 JVM 和 Native 使用的 device info 是否相同

**Comment by Nambers** [comment]
> > net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
> 
> 请确定一下 JVM 和 Native 使用的 device info 是否相同

我本地看是相同的，你们能复现吗(

**Comment by AdoptOSS** [comment]
个人使用经验，JVM 下用非 PHONE 协议首次登录也经常报错，但长期挂机、IP归属地、DeviceInfo不改变的情况下基本不报

**Comment by Nambers** [comment]
> 个人使用经验，JVM 下用非 PHONE 协议首次登录也经常报错，但长期挂机、IP归属地、DeviceInfo不改变的情况下基本不报

没变(
有点怪，不知道为什么在native下PHONE接不到事件，然后其他协议版本过低，但是jvm都可以用
我可以找个时间在native下重新生成个device试一下看看他自己生成的有没有问题

**Comment by Nambers** [comment]
自己实现 login-solver 就可以登录了
