### ISSUE TITLE
自行实现 LoginSolver 时遇到麻烦

### ISSUE THREAD

**Issue by MrXiaoM** [mamoe/mirai#2271]
### 问题描述

我有提取滑块验证 url 在外部弹出滑块窗口并在用户完成滑块验证后自动传回 ticket 的需要，故需要自行实现 LoginSolver。但我遇到了问题，在使用默认的 LoginSolver 的时候可以正常弹出滑块验证窗口，只要我一使用我自行实现的 LoginSolver 就会出现日志所示的报错。

### 复现

```kotlin
object RemoteLoginSolver : LoginSolver() {
    val logger = MiraiLogger.Factory.create(this::class)
    val def = CompletableDeferred<String>()
    @OptIn(MiraiExperimentalApi::class)
    override suspend fun onSolvePicCaptcha(bot: Bot, data: ByteArray): String {
        return SwingSolver.onSolvePicCaptcha(bot, data)
    }
    override suspend fun onSolveSliderCaptcha(bot: Bot, url: String): String? = coroutineScope{
        logger.info("${bot.id}:$url")
        return@coroutineScope def.await().takeIf { it.isNotEmpty() }
    }
    @OptIn(MiraiExperimentalApi::class)
    override suspend fun onSolveUnsafeDeviceLoginVerify(bot: Bot, url: String): String {
        return SwingSolver.onSolveUnsafeDeviceLoginVerify(bot, url)
    }
}
```

```kotlin
            BotFactory.INSTANCE.newBot(qq, pw) {
                loginSolver = RemoteLoginSolver
                fileBasedDeviceInfo()
            }.alsoLogin()
```

### mirai-core 版本

2.12.3

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2022-10-08 22:14:04 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2022-10-08 22:14:04 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2022-10-08 22:14:04 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2022-10-08 22:14:05 V/Net 3191684705: No server list cached.
2022-10-08 22:14:05 I/Net 3191684705: ECDH key is invalid, start to fetch ecdh public key from server.
2022-10-08 22:14:06 I/Net 3191684705: Successfully fetched ecdh public key from server.
2022-10-08 22:14:06 V/Net 3191684705: Send: wtlogin.login
2022-10-08 22:14:06 V/Net 3191684705: Send: wtlogin.login
2022-10-08 22:14:06 V/Net 3191684705: Recv: wtlogin.login
2022-10-08 22:14:06 V/Net 3191684705: Recv: wtlogin.login
2022-10-08 22:14:06 W/Net 3191684705: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3191684705), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3191684705), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2022-10-08 22:14:06 I/Bot 3191684705: Bot cancelled: Bot closed
2022-10-08 22:14:06 E/GraphicalMiraiBridge: Exception in coroutine Plugin top.mrxiaom.graphicalmirai.bridge of GraphicalMiraiBridge
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3191684705), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: java.util.concurrent.CancellationException: Bot closed
		at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
		at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
		at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:84)
		at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
		at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
		... 4 more
	Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3191684705), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )]
	Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3191684705), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )]
```

**Comment by Him188** [comment]
这是应该是服务器行为，滑块可能是需要在相同网络环境完成

**Comment by Him188** [comment]
既然使用默认的 login solver 是正常的，那应该就不是 mirai 的问题。

**Comment by Karlatemp** [comment]
add `override val isSliderSupported: Boolean get()=true`

**Comment by MrXiaoM** [comment]
> add `override val isSliderSupported: Boolean get()=true`

好的，已解决
