### ISSUE TITLE
为什么会出现这种情况，且我难以用言语表达

### ISSUE THREAD

**Issue by yizhixiaomifeng** [mamoe/mirai#2282]
### 问题描述

我已经正确地登录了机器人，但是我无论还是在QQ群里，游戏中，都无法互通，使用了chatQQ，始终都在出现此报错，错误代码在下面↓我基本确认不应该是腾讯风控，因为我仍然可以在QQ客户端中发消息

### 复现

1.正确登录了QQ机器人
2.出现问题

### mirai-core 版本

1.7（我也不知道这个对不对，文件名没写啊）

### bot-protocol

ANDROID_PHONE

### 其他组件版本

what’s this

### 系统日志

```text
首先这个是第一个错误
[18:21:34 INFO]: [Not Secure] <Mi_Feng_> 1
[18:21:34 WARN]: [MiraiMC] Plugin Chat2QQ v1.4.1 generated an exception while executing task 103
net.mamoe.mirai.internal.message.ContextualBugReportException: 在 Internal error: no MessageReceipt was returned from OutgoingMessagePipeline for message 时遇到了意料之中的问题. 请完整复制 此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    调试信息: [MC] Mi_Feng_: 1
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.getSingleReceipt(MessageProtocolFacade.kt:357) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoing(MessageProtocolFacade.kt:326) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.preprocessAndSendOutgoing(MessageProtocolFacade.kt) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:264) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.contact.AbstractUserKt$sendMessageImpl$1.invokeSuspend(AbstractUser.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:283) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:260) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
第二个错误这个是我登录成功的日志
[18:20:49 INFO]: [MiraiMC] Loaded account secrets from local cache.
[18:20:49 INFO]: [MiraiMC] ECDH key is valid.
[18:20:49 INFO]: [MiraiMC] Saved account secrets to local cache for fast login.
[18:20:49 INFO]: [MiraiMC] Login successful.
[18:20:49 INFO]: [MiraiMC] Server time updated, serverTime: 1666002049, diff: 0ms=0.0s
[18:20:49 INFO]: [MiraiMC] Syncing friend message history...
[18:20:49 INFO]: [MiraiMC] Start loading stranger list...
[18:20:49 INFO]: [MiraiMC] Start loading friend list...
[18:20:49 INFO]: [MiraiMC] Successfully loaded stranger list: 0 in total
[18:20:49 INFO]: [MiraiMC] Start loading group list...
[18:20:49 INFO]: [MiraiMC] Online OtherClients: Android手机(MOBILE)
[18:20:49 INFO]: [MiraiMC] Syncing friend message history: Success.
[18:20:49 INFO]: [MiraiMC] Successfully loaded friend list: 10 in total
[18:20:50 INFO]: [MiraiMC] Successfully loaded group list: 2 in total.
[18:20:50 INFO]: [MiraiMC] Scheduled refresh login session in 19d 23h 55min 0.0s.
[18:20:50 INFO]: [MiraiMC] Scheduled key refresh in 23h 55min 0.0s.
[18:20:50 INFO]: [MiraiMC] Bot login successful.
[18:20:50 INFO]: [MiraiMC] 悲伤的机器人(2373094382) 登录成功
[18:21:03 INFO]: [MiraiMC] [FriendMessage/2373094382]
```

### 网络日志

```text
我的文件夹内并不含有logs文件夹
```

**Comment by Him188** [comment]
#2264
