### ISSUE TITLE
2.13.0-RC 启动失败

### ISSUE THREAD

**Issue by jasonnmy** [mamoe/mirai#2284]
### 问题描述

***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    net.mamoe.mirai.internal.deps.io.ktor.client.utils.CoroutineDispatcherUtilsKt.clientDispatcher(CoroutineDispatcherUtils.kt:22)

The following method did not exist:

    'kotlinx.coroutines.CoroutineDispatcher kotlinx.coroutines.CoroutineDispatcher.limitedParallelism(int)'

The method's class, kotlinx.coroutines.CoroutineDispatcher, is available from the following locations:

    jar:file:/D:/.m2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.5.1/kotlinx-coroutines-core-jvm-1.5.1.jar!/kotlinx/coroutines/CoroutineDispatcher.class

The class hierarchy was loaded from the following locations:

    kotlinx.coroutines.CoroutineDispatcher: file:/D:/.m2/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.5.1/kotlinx-coroutines-core-jvm-1.5.1.jar
    kotlin.coroutines.AbstractCoroutineContextElement: file:/D:/.m2/org/jetbrains/kotlin/kotlin-stdlib/1.5.21/kotlin-stdlib-1.5.21.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of kotlinx.coroutines.CoroutineDispatcher

### 复现

导2.12.3没问题，13会启动不了

### mirai-core 版本

2.13.0-RC

### bot-protocol

ANDROID_PHONE

**Comment by cssxsh** [comment]
maven 详细的依赖配置 给一下？

**Comment by jasonnmy** [comment]
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.4</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <packaging>war</packaging>
    <description>Spring Boot</description>
    <properties>
        <java.version>11</java.version>
        <!--        <kotlin.version>1.5.10</kotlin.version>-->
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-logging</artifactId>
            <version>2.7.4</version>
            <exclusions>
                <exclusion>
                    <artifactId>logback-classic</artifactId>
                    <groupId>ch.qos.logback</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.30</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>2.0.9.graal</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.20</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.13.0-RC</version>
        </dependency>
    </dependencies>

</project>
```

**Comment by cssxsh** [comment]
`1.5.10` 版本的 kotlin 有些旧了，建议换 `1.7.10` 这是 mirai 目前在用的版本

**Comment by jasonnmy** [comment]
我注释了kotlin版本，用的mirai自带的，而且指定用1.7.10也不行

**Comment by cssxsh** [comment]
> kotlinx-coroutines-core

不止 kotlin
按道理 mirai-core 引用的 kotlinx-coroutines-core-jvm 应该是 1.6.4
```
    <dependency>
      <groupId>org.jetbrains.kotlinx</groupId>
      <artifactId>kotlinx-coroutines-core-jvm</artifactId>
      <version>1.6.4</version>
    </dependency>
```

你这里缺降级了，很怪

**Comment by cssxsh** [comment]
> kotlinx-coroutines-core

不止 kotlin
按道理 mirai-core 引用的 kotlinx-coroutines-core-jvm 应该是 1.6.4
```
    <dependency>
      <groupId>org.jetbrains.kotlinx</groupId>
      <artifactId>kotlinx-coroutines-core-jvm</artifactId>
      <version>1.6.4</version>
    </dependency>
```

你这里缺降级了，很怪

**Comment by jasonnmy** [comment]
> > kotlinx-coroutines-core
> 
> 不止 kotlin 按道理 mirai-core 引用的 kotlinx-coroutines-core-jvm 应该是 1.6.4
> 
> ```
>     <dependency>
>       <groupId>org.jetbrains.kotlinx</groupId>
>       <artifactId>kotlinx-coroutines-core-jvm</artifactId>
>       <version>1.6.4</version>
>     </dependency>
> ```
> 
> 你这里缺降级了，很怪


不报错了，但是调用这个时候报错了  DeviceInfo.from(ResourceUtils.getFile("classpath:config/device.json"))，文件存在，有内容，12没毛病
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at kotlinx.serialization.internal.PluginGeneratedSerialDescriptor.getElementDescriptor(PluginGeneratedSerialDescriptor.kt:135)
	at kotlinx.serialization.descriptors.SerialDescriptorKt$elementDescriptors$1$1.next(SerialDescriptor.kt:284)
	at kotlinx.serialization.descriptors.SerialDescriptorKt$elementDescriptors$1$1.next(SerialDescriptor.kt:279)
	at kotlinx.serialization.internal.PluginGeneratedSerialDescriptorKt.hashCodeImpl(PluginGeneratedSerialDescriptor.kt:137)
	at kotlinx.serialization.internal.PluginGeneratedSerialDescriptor$_hashCode$2.invoke(PluginGeneratedSerialDescriptor.kt:44)
	at kotlinx.serialization.internal.PluginGeneratedSerialDescriptor$_hashCode$2.invoke(PluginGeneratedSerialDescriptor.kt:44)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at kotlinx.serialization.internal.PluginGeneratedSerialDescriptor.get_hashCode(PluginGeneratedSerialDescriptor.kt:44)
	at kotlinx.serialization.internal.PluginGeneratedSerialDescriptor.hashCode(PluginGeneratedSerialDescriptor.kt:97)
	at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at kotlinx.serialization.json.internal.DescriptorSchemaCache.get(SchemaCache.kt:35)
	at kotlinx.serialization.json.internal.DescriptorSchemaCache.getOrPut(SchemaCache.kt:27)
	at kotlinx.serialization.json.internal.JsonTreeDecoder.elementName(TreeJsonDecoder.kt:236)
	at kotlinx.serialization.internal.NamedValueDecoder.getTag(Tagged.kt:330)
	at kotlinx.serialization.json.internal.JsonTreeDecoder.decodeElementIndex(TreeJsonDecoder.kt:205)
	at net.mamoe.mirai.utils.DeviceInfoManager$DeviceInfoVersionSerializer.deserialize(DeviceInfo.kt:291)
	at net.mamoe.mirai.utils.DeviceInfoManager$DeviceInfoVersionSerializer.deserialize(DeviceInfo.kt:291)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:206)
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:279)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:296)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:279)
	at net.mamoe.mirai.utils.DeviceInfoManager$V1$$serializer.deserialize(DeviceInfo.kt:294)
	at net.mamoe.mirai.utils.DeviceInfoManager$V1$$serializer.deserialize(DeviceInfo.kt:294)
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:59)
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:51)
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:24)
	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:119)
	at net.mamoe.mirai.utils.DeviceInfoManager.deserialize(DeviceInfo.kt:445)
	at net.mamoe.mirai.utils.DeviceInfo$Companion.from(DeviceInfo.kt:103)
	at net.mamoe.mirai.utils.DeviceInfo$Companion.from$default(DeviceInfo.kt:95)
	at net.mamoe.mirai.utils.DeviceInfo$Companion.from(DeviceInfo.kt)
	at net.mamoe.mirai.utils.DeviceInfo.from(DeviceInfo.kt)

**Comment by jasonnmy** [comment]
```
<kotlin.version>1.7.10</kotlin.version>

<dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core-jvm</artifactId>
            <version>1.6.4</version>
        </dependency>
```
这样改可以了，之前我也改过，但是版本改低了

**Comment by cssxsh** [comment]
新的报错是这个的原因

https://github.com/mamoe/mirai/issues/2280
