### ISSUE TITLE
每次业务违规冻结QQ总是伴随Transformers528 0x27L

### ISSUE THREAD

**Issue by SwtaoCyt** [mamoe/mirai#2286]
### 问题描述

机器人一天会稳定冻结一次，来来回回几个QQ一个月冻结了二三十次了，号都永久封了一个了，通过观察发现只要出现类似Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile内容QQ大概率会在稍后以业务违规的原因被冻结。
我以为是我写的机器人交互起来太像机器人，所以这几个月把机器人的所有交互逻辑都已经暂停，可疑的逻辑全部禁用，仅保留机器人自动接受好友请求与接收好友信息两个个逻辑，并且用暴力的方法多开了一个机器人保持运作稳定性，但是只是变成了一天两冻结。
想问一下有没有办法屏蔽掉，谢谢。

### 复现

只要出现类似Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile内容QQ大概率会在稍后以业务违规被冻结。

### mirai-core 版本

2.10.1

### bot-protocol

IPAD

### 系统日志

```text
2022-10-18 23:58:09 D/Net 2138805098: Unknown MsgInfo kind 736, data=0C 19 00 05 0A 01 5A 3F 0B 0A 01 5A 40 0B 0A 02 00 00 9C 40 0B 0A 02 00 00 9C 7A 0B 0A 02 00 00 9C 7B 0B
2022-10-18 23:58:09 D/Net 2138805098: Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile@1382e7fe
2022-10-18 23:58:10 D/Net 2022924442: Unknown MsgInfo kind 736, data=0C 19 00 05 0A 01 5A 3F 0B 0A 01 5A 40 0B 0A 02 00 00 9C 40 0B 0A 02 00 00 9C 7A 0B 0A 02 00 00 9C 7B 0B
2022-10-18 23:58:10 D/Net 2022924442: Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile@251fa485
2022-10-18 23:58:12 V/Net 2138805098: Send: StatSvc.RspMSFForceOffline(StatSvc.RspMSFForceOffline)
2022-10-18 23:58:12 V/Bot 2138805098: Event: BotOfflineEvent.MsfOffline(bot=Bot(2138805098), cause=MsfOfflineToken(uin=2138805098, seq=2442123244, const=0), reconnect=true)
2022-10-18 23:58:12 W/Bot 2138805098: Connection lost, reconnecting... (MsfOfflineToken(uin=2138805098, seq=2442123244, const=0))
2022-10-18 23:58:12 W/Net 2138805098: MsfOfflineToken(uin=2138805098, seq=2442123244, const=0)
MsfOfflineToken(uin=2138805098, seq=2442123244, const=0)
        at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:295)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:369)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

2022-10-18 23:58:12 V/Net 2138805098: Recv: StatSvc.ReqMSFOffline
2022-10-18 23:58:12 V/Net 2138805098: Loading server list from cache.
2022-10-18 23:58:12 I/Net 2138805098: Server list: 183.47.99.24:8080, 120.232.67.218:443, 183.47.98.25:14000, 221.238.41.118:80, 117.62.243.213:14000, 157.148.54.41:80, 180.101.246.49:443, msfwifi.3g.qq.com:8080.
2022-10-18 23:58:12 I/Net 2138805098: ECDH key is invalid, start to fetch ecdh public key from server.
2022-10-18 23:58:12 I/Net 2138805098: Successfully fetched ecdh public key from server.
2022-10-18 23:58:12 V/Net 2138805098: Send: wtlogin.exchange_emp
2022-10-18 23:58:12 V/Net 2138805098: Recv: wtlogin.exchange_emp
2022-10-18 23:58:12 V/Net 2138805098: Send: wtlogin.login
2022-10-18 23:58:12 V/Net 2138805098: Recv: wtlogin.login
2022-10-18 23:58:12 W/Net 2138805098: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2138805098), code=40, title=安全提醒, message=该帐号因涉嫌进行业务违规操作被暂时冻结，请点击下方按钮了解详情及处理。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2138805098), code=40, title=安全提醒, message=该帐号因涉嫌进行业务违规操作被暂时冻结，请点击下方按钮了解详情及处理。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
        Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(2138805098), code=40, title=安全提醒, message=请确认你输入了正确的帐号。该帐号存在被盗风险，已进入保护模式，请前往安全中心恢复。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:287)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                ... 9 more

2022-10-18 23:58:13 V/Net 2022924442: Send: StatSvc.RspMSFForceOffline(StatSvc.RspMSFForceOffline)
2022-10-18 23:58:13 V/Bot 2022924442: Event: BotOfflineEvent.MsfOffline(bot=Bot(2022924442), cause=MsfOfflineToken(uin=2022924442, seq=2503321335, const=0), reconnect=true)
2022-10-18 23:58:13 W/Bot 2022924442: Connection lost, reconnecting... (MsfOfflineToken(uin=2022924442, seq=2503321335, const=0))
2022-10-18 23:58:13 V/Net 2022924442: Recv: StatSvc.ReqMSFOffline
2022-10-18 23:58:13 W/Net 2022924442: MsfOfflineToken(uin=2022924442, seq=2503321335, const=0)
MsfOfflineToken(uin=2022924442, seq=2503321335, const=0)
        at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:295)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:369)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.util.concurrent.CancellationException: NetworkHandler closed
                at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
                at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:608)
                at kotlinx.coroutines.JobKt.cancel(Unknown Source)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.close(NetworkHandlerSupport.kt:55)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:191)
                at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:79)
                at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:322)
                at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:277)
                at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
                at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:84)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
                at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
                at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
                at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
                at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:82)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:178)
                ... 9 more
        Caused by: [CIRCULAR REFERENCE: MsfOfflineToken(uin=2022924442, seq=2503321335, const=0)]
```

**Comment by cssxsh** [comment]
有频繁冻结相关操作你应该删掉 device.json 让他重新生成会好一点

**Comment by SwtaoCyt** [comment]
这几个月device.json已经删过好多次了，然后每种登录方式都换过

**Comment by SwtaoCyt** [comment]
2022-10-19 20:28:17 D/Net 2022924442: Unknown MsgInfo kind 736, data=0C 19 00 05 0A 01 5A 3F 0B 0A 01 5A 40 0B 0A 02 00 00 9C 40 0B 0A 02 00 00 9C 7A 0B 0A 02 00 00 9C 7B 0B
2022-10-19 20:28:17 D/Net 2022924442: Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile@6adf787d
2022-10-19 20:28:19 D/Net 2138805098: Unknown MsgInfo kind 736, data=0C 19 00 05 0A 01 5A 3F 0B 0A 01 5A 40 0B 0A 02 00 00 9C 40 0B 0A 02 00 00 9C 7A 0B 0A 02 00 00 9C 7B 0B
2022-10-19 20:28:19 D/Net 2138805098: Transformers528 0x27L: ProfileChanged new data: net.mamoe.mirai.internal.network.protocol.data.proto.Submsgtype0x27$SubMsgType0x27$ModProfile@9ad8ae4
2022-10-19 20:28:20 V/Net 2022924442: Send: StatSvc.RspMSFForceOffline(StatSvc.RspMSFForceOffline)
2022-10-19 20:28:20 V/Bot 2022924442: Event: BotOfflineEvent.MsfOffline(bot=Bot(2022924442), cause=MsfOfflineToken(uin=2022924442, seq=2560718374, const=0), reconnect=true)
2022-10-19 20:28:20 W/Bot 2022924442: Connection lost, reconnecting... (MsfOfflineToken(uin=2022924442, seq=2560718374, const=0))
2022-10-19 20:28:20 V/Net 2022924442: Recv: StatSvc.ReqMSFOffline
2022-10-19 20:28:20 W/Net 2022924442: MsfOfflineToken(uin=2022924442, seq=2560718374, const=0)
MsfOfflineToken(uin=2022924442, seq=2560718374, const=0)
        at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:295)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:369)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

2022-10-19 20:28:20 V/Net 2022924442: Loading server list from cache.
2022-10-19 20:28:20 I/Net 2022924442: Server list: msfwifi.3g.qq.com:8080, 157.148.41.102:80, 183.47.102.218:8080, 180.109.192.45:14000, 14.22.9.53:8080, 120.232.22.229:443, 117.62.242.214:14000, 42.81.192.141:80.
2022-10-19 20:28:20 I/Net 2022924442: ECDH key is valid.
2022-10-19 20:28:20 V/Net 2022924442: Send: wtlogin.exchange_emp
2022-10-19 20:28:20 V/Net 2022924442: Recv: wtlogin.exchange_emp
2022-10-19 20:28:20 V/Net 2022924442: Send: wtlogin.login
2022-10-19 20:28:20 V/Net 2022924442: Recv: wtlogin.login
2022-10-19 20:28:20 W/Net 2022924442: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2022924442), code=40, title=安全提醒, message=该帐号因涉嫌进行业务违规操作被暂时冻结，请点击 下方按钮了解详情及处理。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2022924442), code=40, title=安全提醒, message=该帐号因涉嫌进行业务违规操作被暂时冻结，请点击下方按钮了解详情及处理。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
        Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(2022924442), code=40, title=安全提醒, message=请确认你输入了正确的帐号。该帐号存在被盗风险，已进入保护模式 ，请前往安全中心恢复。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:287)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                ... 9 more

2022-10-19 20:28:22 V/Net 2138805098: Send: StatSvc.RspMSFForceOffline(StatSvc.RspMSFForceOffline)
2022-10-19 20:28:22 V/Bot 2138805098: Event: BotOfflineEvent.MsfOffline(bot=Bot(2138805098), cause=MsfOfflineToken(uin=2138805098, seq=2499932698, const=0), reconnect=true)
2022-10-19 20:28:22 W/Bot 2138805098: Connection lost, reconnecting... (MsfOfflineToken(uin=2138805098, seq=2499932698, const=0))
2022-10-19 20:28:22 V/Net 2138805098: Recv: StatSvc.ReqMSFOffline
2022-10-19 20:28:22 W/Net 2138805098: MsfOfflineToken(uin=2138805098, seq=2499932698, const=0)
MsfOfflineToken(uin=2138805098, seq=2499932698, const=0)
        at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.decode(StatSvc.kt:295)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:369)
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: java.util.concurrent.CancellationException: NetworkHandler closed
                at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
                at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:608)
                at kotlinx.coroutines.JobKt.cancel(Unknown Source)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.close(NetworkHandlerSupport.kt:55)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.close(NettyNetworkHandler.kt:191)
                at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:79)
                at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:322)
                at net.mamoe.mirai.internal.network.protocol.packet.login.StatSvc$ReqMSFOffline.handle(StatSvc.kt:277)
                at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
                at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:84)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
                at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
                at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
                at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
                at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
                at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:82)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:178)
                ... 9 more
        Caused by: [CIRCULAR REFERENCE: MsfOfflineToken(uin=2138805098, seq=2499932698, const=0)]

**Comment by way-zer** [comment]
好友消息，私聊，封的很频繁。我现在都只回复群消息了
私聊消息千万别回复。试了半天，只要有私聊，基本上半天就被封了
