### ISSUE TITLE
富文本消息解析类型不全？

### ISSUE THREAD

**Issue by sandtechnology** [mamoe/mirai#229]
## 问题

```
java.lang.IllegalStateException: 在 richMsg.serviceId 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai. 调试信息: ri
chMsg.serviceId: 5, content=[1, 120, -100, 93, -111, -35, 74, -36, 64, 20, -57, 95, 101, -104, -5, 100, 38, -119, -55, 1
02, 37, -119, -88, 113, 107, -97, -96, 23, -91, -124, 49, 25, -77, 35, -7, 34, 59, 89, 86, -118, -80, 109, 105, -79, -76
, -126, 120, 33, 75, 123, -17, -123, 11, -30, -25, 77, -85, -10, 93, -86, 9, -18, -107, -81, -48, -103, 93, 118, 41, -62
, -64, 57, -1, 115, 126, -100, -113, 57, -50, -54, 32, 77, 64, -97, -106, 61, -106, 103, 46, -44, 84, 12, 1, -51, -62, 6
0, 98, 89, -20, -62, -118, 111, 43, 54, 92, -15, -100, -76, 23, -125, 30, 45, -5, 44, -92, -81, 125, 23, -102, 16, 112,
-102, 22, 9, -31, 83, -87, -23, -58, -110, 8, 109, -107, -116, 110, -69, -16, 109, -67, -1, -27, -15, -41, -8, 93, -13,
-23, -22, -23, -28, 67, 115, 121, -40, -36, 92, 79, 70, 87, -11, -25, -81, -49, -73, -33, -21, -13, -117, 122, 127, 60,
57, -6, -3, -12, -25, -25, 100, 116, 93, -33, 93, 60, 12, 63, -126, -65, -61, 111, -77, 7, -127, -25, 48, 81, 26, 36, 10
0, 55, -81, -72, 11, 49, 20, -127, -108, -60, 20, 84, 21, -117, 92, -8, 126, -61, -20, 88, -10, -102, 111, 42, -40, -20,
 -40, -118, -74, 100, -81, 41, 109, 127, -75, -91, 116, 54, -42, 125, -84, 91, -66, -127, 87, -3, 61, 117, -89, -120, 33
, 72, 35, -45, -123, 115, 94, -30, -110, -106, -16, -1, 44, 4, -81, -54, -68, 42, 58, 44, -95, -111, 108, -96, 107, 86,
75, -73, 12, -37, -42, 69, 1, -106, -67, 97, 17, -17, -54, 13, -15, 84, 110, 82, 22, 119, -7, 92, -109, -63, 60, 109, -4
9, -28, 34, 45, 53, -14, 28, 36, 119, -15, -100, 94, 94, -107, 33, 5, 25, 73, -87, 11, -101, -29, -13, -26, -26, -76, -6
6, 63, -85, 15, 126, 64, -64, 66, -7, -19, 93, -50, -117, 101, -124, -104, 26, 115, -106, -58, 106, -104, -95, -68, -96,
 25, 34, 69, 17, 72, 0, 97, -116, 90, 6, -78, -38, 8, 27, 8, 105, 24, -73, 12, -85, -115, -115, 64, 120, 65, -86, 22, -1
03, -40, 85, -96, 114, -6, 69, 78, 68, 66, 62, 61, -87, -24, 17, -52, 124, -97, 112, 34, 53, 121, -95, -85, 50, 17, 70,
-114, 43, -50, -20, -3, 3, 90, -92, -72, 79],
tryUnzip=<?xml version="1.0" encoding="utf-8"?><msg serviceID="5" templateID="12345" brief="[分享]想要沐浴阳光，就别钻进
阴影。 ???" ><item layout="0"><image uuid="{E5F68BD5-05F8-148B-9DA7-FECD026D30AD}.jpg" md5="E5F68BD505F8148B9DA7FECD026D
30AD" GroupFiledid="2167263882" minWidth="120" minHeight="120" maxWidth="180" maxHeight="180" /></item><source name="新
浪微博" icon="http://i.gtimg.cn/open/app_icon/00/73/69/03//100736903_100_m.png" appid="100736903" action="" i_actionData
="" a_actionData="" url=""/></msg>
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.contextualBugReportException(convension.kt:417)
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.contextualBugReportException$default(convension.kt:415)
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.joinToMessageChain(convension.kt:376)
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.toMessageChain(convension.kt:200)
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.toMessageChain$default(convension.kt:186)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$PbPushGroupMsg.decode(OnlinePush.kt
:105)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandr
oid(PacketFactory.kt:493)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:2
26)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler
.kt:400)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:395)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNet
workHandler.kt:380)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
## 如何复现
使用微博长图转换功能分享到QQ群

**Comment by Him188** [comment]
这个 log 原本是为 #220 添加的
