### ISSUE TITLE
2.12.2使用maven方式构建启动登录报错java.lang.NoClassDefFoundError: kotlin.time.DurationUnit

### ISSUE THREAD

**Issue by RrrrLin** [mamoe/mirai#2290]
### 问题描述

使用2.12.2登录时失败报错java.lang.NoClassDefFoundError: kotlin.time.DurationUnit

### 复现

1.使用idea通过MAVEN方式开发登录（使用框架spring-boot）
2.通过TxCaptchaHelper完成滑动验证码验证
3.报错java.lang.NoClassDefFoundError: kotlin.time.DurationUnit

### mirai-core 版本

>2.12.2

### bot-protocol

ANDROID_PHONE

### 其他组件版本

kotlin-stdlib-jdk8:'1.5.10'
kotlinx-coroutines-core-jvm:'1.5.0'
spring-boot-starter-parent:'2.5.1'

 
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.12.2</version>
            <exclusions>
                <exclusion>
                    <artifactId>kotlinx-coroutines-core-jvm</artifactId>
                    <groupId>org.jetbrains.kotlinx</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.5.10</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core-jvm</artifactId>
            <version>1.5.0</version>
        </dependency>

### 系统日志

```text
java.lang.NoClassDefFoundError: kotlin.time.DurationUnit
	at net.mamoe.mirai.internal.QQAndroidBot$close$1.invokeSuspend(QQAndroidBot.kt:78) ~[mirai-core-jvm-2.12.2.jar:2.12.2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.5.10.jar:1.5.10-release-890 (1.5.10)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:76) ~[mirai-core-jvm-2.12.2.jar:2.12.2]
	at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136) ~[mirai-core-jvm-2.12.2.jar:2.12.2]
	at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt) ~[mirai-core-jvm-2.12.2.jar:2.12.2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.5.10.jar:1.5.10-release-890 (1.5.10)]
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:398) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:432) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:421) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:329) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1408) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1519) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.5.10.jar:1.5.10-release-890 (1.5.10)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.5.10.jar:1.5.10-release-890 (1.5.10)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[kotlinx-coroutines-core-jvm-1.5.0.jar:na]
Caused by: java.lang.ClassNotFoundException: kotlin.time.DurationUnit
	at java.net.URLClassLoader.findClass(URLClassLoader.java:591) ~[na:1.8.0_282]
	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953) ~[na:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:898) ~[na:1.8.0_282]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[na:1.8.0_282]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:881) ~[na:1.8.0_282]
	... 36 common frames omitted
```

### 补充信息

登录相关代码如下：

    @Async
    public void star() {
        // 机器人
        BotConfiguration botConfig = new BotConfiguration();
        botConfig.fileBasedDeviceInfo("deviceInfo.json");
        //使用安卓手机登录。
        botConfig.setProtocol(BotConfiguration.MiraiProtocol.ANDROID_PHONE);
        //详细的网络日志开关
        botConfig.noNetworkLog();
        //上传线程数目
        botConfig.setHighwayUploadCoroutineCount(4);
        bot = BotFactory.INSTANCE.newBot(BOT_QQ, PASSWORD, botConfig);
        // 登陆
        bot.login();
        //注册指令
        commandConfig.registerCommandHeads();
        commandConfig.registerCommands(annotateScanner.getCommandList());
        //注册事件
        List<ListenerHost> events = Arrays.asList(
                messageMainEvents,
                specialEventListener
        );
        for (ListenerHost event : events)
        {
            GlobalEventChannel.INSTANCE.registerListenerHost(event);
        }
        //挂载该机器人的协程
        startTime=LocalDateTime.now();
        bot.join();
    }

**Comment by Him188** [comment]
使用协程库 1.6.0，Kotlin 标准库1.7.0
