### ISSUE TITLE
java.lang.IllegalStateException: type mismatch. Expected SIMPLE_LIST or LIST, got JceHead(tag=4, type=12(Zero)) instead

### ISSUE THREAD

**Issue by lincannm** [mamoe/mirai#230]
运行mirai-console并/login登录的时候便会出现该报错
详细输出消息如下：

07:38:20 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: type mismatch. Expected SIMPLE_LIST or LIST, got JceHead(tag=4, type=12(Zero)) instead
        at net.mamoe.mirai.qqandroid.utils.io.serialization.jce.JceDecoder.beginStructure(JceDecoder.kt:234)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:29)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:45)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Decoding.kt:231)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:233)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:233)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.FileStoragePushFSSvcList$$serializer.deserialize(ConfigPush.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.FileStoragePushFSSvcList$$serializer.deserialize(ConfigPush.kt:104)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.jce.Jce.load(JceNew.kt:43)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:39)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.loadAs$default(utils.kt:38)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils.loadAs$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.login.ConfigPushSvc$PushReq.decode(ConfigPushSvc.kt:85)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:495)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:422)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:417)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:402)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

报错后面（登录之后）还是能正常输出qq收到的消息，似乎不影响使用？（不过后来我运行demo.js的时候说Connection refused（见酷安termux评论区我有回复你），mirai我用不了哈哈）

termux用apt装的jdk包是openjdk-8-jdk（按照博客教程安装openjdk-11-jdk会发生报错不能用，报错内容记得翻译之后大概是关于反射的问题吧）

这奇怪的报错希望能修复一下

**Comment by Him188** [comment]
Fixed in 0.37.3

**Comment by lincannm** [comment]
> Fixed in 0.37.3

emmmmm
There is no version 0.37.3 in Releases

**Comment by Him188** [comment]
On the horizon
