### ISSUE TITLE
当前 QQ 版本过低

### ISSUE THREAD

**Issue by bin-tenkuu** [mamoe/mirai#2305]
### 问题描述

启动时报错提示 `当前QQ版本过低，请升级至最新版本后再登录。`

### 复现

使用任意 qq 登录即可

### mirai-core 版本

2.12.3

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2022-10-26 11:55:46 I/Bot.2506019369: [SliderCaptcha] 正在提交中...
2022-10-26 11:55:46 I/Bot.2506019369: [SliderCaptcha] Submitting...
2022-10-26 11:55:47 I/Bot.2506019369: Bot cancelled: Bot closed
2022-10-26 11:55:47 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2506019369), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2506019369), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: java.util.concurrent.CancellationException: Bot closed
		at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
		at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
		at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:84)
		at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
		at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
		at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
		at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
		at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
		at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
		at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:245)
		at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
		at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
		at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
		at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.base/java.lang.reflect.Method.invoke(Unknown Source)
		at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
		at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
		at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
		at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
		at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
		at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
		at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
		at org.itxtech.mcl.Loader.start(Loader.java:189)
		at org.itxtech.mcl.Loader.main(Loader.java:79)
	Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2506019369), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=
```

### 网络日志

```text
2022-10-26 11:42:23 V/Net 2506019369: Send: wtlogin.login
2022-10-26 11:42:23 V/Net 2506019369: Recv: wtlogin.login
2022-10-26 11:55:13 V/Net 2506019369: Send: wtlogin.login
2022-10-26 11:55:13 V/Net 2506019369: Recv: wtlogin.login
2022-10-26 11:55:13 W/Net 2506019369: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2506019369), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2506019369), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: org.jline.reader.UserInterruptException
		at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:702)
		at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
		at net.mamoe.mirai.console.terminal.ConsoleInputImpl$requestInput$2$1$1.run(ConsoleInputImpl.kt:45)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.base/java.lang.Thread.run(Unknown Source)

2022-10-26 11:55:26 V/Net 2506019369: Loading server list from cache.
2022-10-26 11:55:26 I/Net 2506019369: Server list: msfwifi.3g.qq.com:8080, 170.106.75.13:10001, 116.130.229.126:14000, 36.155.245.173:443, 183.47.102.62:80, 43.154.240.7:8080.
2022-10-26 11:55:27 I/Net 2506019369: ECDH key is invalid, start to fetch ecdh public key from server.
2022-10-26 11:55:29 I/Net 2506019369: Successfully fetched ecdh public key from server.
2022-10-26 11:55:29 V/Net 2506019369: Send: wtlogin.login
2022-10-26 11:55:29 V/Net 2506019369: Recv: wtlogin.login
2022-10-26 11:55:46 V/Net 2506019369: Send: wtlogin.login
2022-10-26 11:55:47 W/Net 2506019369: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2506019369), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2506019369), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2022-10-26 11:55:47 V/Net 2506019369: Recv: wtlogin.login
```

### 补充信息

今天重启刚刚更新到 2.12.3 版本，然后就炸了

**Comment by cssxsh** [comment]
已有相同 issue https://github.com/mamoe/mirai/issues/2298
