### ISSUE TITLE
启动报错 net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated

### ISSUE THREAD

**Issue by SugarFatFree** [mamoe/mirai#2308]
### 问题描述

更换成2.13.0-RC2版本并显示引入ktor2后报错 ；
已显示引入：
···
    implementation("io.ktor:ktor-client-core:2.1.2")
    implementation("io.ktor:ktor-client-okhttp:2.1.2")
    implementation("io.ktor:ktor-http-cio:2.1.2")
···

### 复现

···
    val bot = BotFactory.newBot(account.id, account.password) {
        protocol = BotConfiguration.MiraiProtocol.ANDROID_PAD
        cacheDir = File("./cache/${account.id}/")
        if (deviceFile.exists()) {
            deviceInfo = { deviceFile.loadAsDeviceInfo() }
        } else {
            fileBasedDeviceInfo(deviceFilePath)
        }
    }
    bot.login()
···

### mirai-core 版本

2.13.0-RC2

### bot-protocol

ANDROID_PAD

### 系统日志

```text
Exception in thread "main" java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:270)
	at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:18)
	at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357)
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39)
	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:116)
	at com.xiaoxi.AccountTestKt.login(AccountTest.kt:29)
	at com.xiaoxi.AccountTestKt.main(AccountTest.kt:10)
	at com.xiaoxi.AccountTestKt$main$2.invoke(AccountTest.kt)
	at com.xiaoxi.AccountTestKt$main$2.invoke(AccountTest.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at com.xiaoxi.AccountTestKt.main(AccountTest.kt)
Caused by: java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:270)
	at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:18)
	at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357)
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39)
	at net.mamoe.mirai.internal.message.MessageSerializersImpl.getSerializersModule(MessageSerializersImpl.kt:65)
	at net.mamoe.mirai.internal.message.MessageSerializersImpl.registerSerializers(MessageSerializersImpl.kt:76)
	at net.mamoe.mirai.message.MessageSerializers$INSTANCE.registerSerializers(MessageSerializers.kt)
	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade.<clinit>(MessageProtocolFacade.kt:165)
	at net.mamoe.mirai.internal.MiraiImplKt._MiraiImpl_static_init(MiraiImpl.kt:25)
	at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt:87)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 17 more
Caused by: java.lang.NoSuchMethodError: 'kotlinx.coroutines.CoroutineDispatcher kotlinx.coroutines.CoroutineDispatcher.limitedParallelism(int)'
	at net.mamoe.mirai.internal.deps.io.ktor.client.utils.CoroutineDispatcherUtilsKt.clientDispatcher(CoroutineDispatcherUtils.kt:22)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine$dispatcher$2.invoke(OkHttpEngine.kt:32)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine$dispatcher$2.invoke(OkHttpEngine.kt:31)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine.getDispatcher(OkHttpEngine.kt:31)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.HttpClientEngineBase$coroutineContext$2.invoke(HttpClientEngineBase.kt:22)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.HttpClientEngineBase$coroutineContext$2.invoke(HttpClientEngineBase.kt:21)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.HttpClientEngineBase.getCoroutineContext(HttpClientEngineBase.kt:21)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:51)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttp.create(OkHttp.kt:31)
	at net.mamoe.mirai.internal.deps.io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41)
	at net.mamoe.mirai.internal.MiraiImplKt.createDefaultHttpClient(MiraiImpl.kt:29)
	at net.mamoe.mirai.internal.MiraiImpl.<init>(MiraiImpl.kt:97)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 36 more
```

**Comment by cssxsh** [comment]
`kotlinx-coroutines` 版本不匹配
你可以尝试升级 kotlin 版本 到 1.7.10
或者 直接显式指定依赖 `implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4")`

你这个问题本质上和 https://github.com/mamoe/mirai/issues/2284 是一样的

**Comment by Keyezi** [comment]
> `kotlinx-coroutines` 版本不匹配 你可以尝试升级 kotlin 版本 到 1.7.10 或者 直接显式指定依赖 `implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4")`
> 
> 你这个问题本质上和 #2284 是一样的

同样遇到此问题 按这个方法操作也无法解决。
版本2.13.0

**Comment by cssxsh** [comment]
> > `kotlinx-coroutines` 版本不匹配 你可以尝试升级 kotlin 版本 到 1.7.10 或者 直接显式指定依赖 `implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4")`
> > 你这个问题本质上和 #2284 是一样的
> 
> 同样遇到此问题 按这个方法操作也无法解决。 版本2.13.0

@Keyezi  你遇到的问题和他 不一样
你的是 https://github.com/mamoe/mirai/issues/2329 
目前没有办法解决
只能先降低版本 到 2.13.0-RC2

**Comment by dlfld** [comment]
现在我用的是2.16.0，还是报这个错
