### ISSUE TITLE
消息过长时会报错 `java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 4132 out of bounds for byte[4096]`

### ISSUE THREAD

**Issue by WeiLanKing** [mamoe/mirai#2309]
### 问题描述

控制台输入无误，如题，基本信息
  11:20:38 [INFO] Verifying "net.mamoe:mirai-console" v2.13.0-RC2
  11:20:39 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.0-RC2
  11:20:39 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.0-RC2
  11:20:39 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2

### 复现

一直存在

### mirai-core 版本

2.13.0-RC2

### bot-protocol

ANDROID_PAD

### 系统日志

```text
W/main: Exception in executing command `[mirai:source:ids=[1567], internalIds=[-386594315], from friend 769970280 to 189695274 at 1666841573]/permission lp`, command owned by net.mamoe.mirai.console.command.ConsoleCommandOwner@3926f722
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 4132 out of bounds for byte[4096]
        at java.base/java.lang.System.arraycopy(Native Method)
        at io.ktor.utils.io.bits.MemoryJvmKt.copyTo-9zorpBc(MemoryJvm.kt:117)
        at io.ktor.utils.io.core.BufferPrimitivesKt.readFully(BufferPrimitives.kt:1098)
        at io.ktor.utils.io.core.InputArraysKt.readFully(InputArrays.kt:8)
        at net.mamoe.mirai.internal.message.protocol.outgoing.FriendMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt:354)
        at net.mamoe.mirai.internal.message.protocol.outgoing.FriendMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt:71)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.process(GeneralMessageSenderProtocol.kt:64)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:26)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:20)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:287)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoingImpl(MessageProtocolFacade.kt:361)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoing(MessageProtocolFacade.kt:345)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.preprocessAndSendOutgoing(MessageProtocolFacade.kt)
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:263)
        at net.mamoe.mirai.internal.contact.FriendImpl.sendMessage(FriendImpl.kt:102)
        at net.mamoe.mirai.console.command.FriendCommandSender.sendMessage$suspendImpl(CommandSender.kt:667)
        at net.mamoe.mirai.console.command.FriendCommandSender.sendMessage(CommandSender.kt)
        at net.mamoe.mirai.console.command.FriendCommandSender.sendMessage$suspendImpl(CommandSender.kt:664)
        at net.mamoe.mirai.console.command.FriendCommandSender.sendMessage(CommandSender.kt)
        at net.mamoe.mirai.console.command.BuiltInCommands$PermissionCommand.listPermissions(BuiltInCommands.kt:737)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:337)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:167)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:130)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:125)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:86)
        at chat-command-0.5.1.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:69)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Him188** [comment]
我觉得是 ktor 的 bug

**Comment by NoMathExpectation** [comment]
我也遇到这个问题了：
```log
2022-11-10 15:56:46 W/stderr: net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:147)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:1)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
2022-11-10 15:56:46 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-11-10 15:56:46 W/stderr: Caused by: java.lang.reflect.InvocationTargetException
2022-11-10 15:56:46 W/stderr:   at jdk.internal.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
2022-11-10 15:56:46 W/stderr:   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2022-11-10 15:56:46 W/stderr:   at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140)
2022-11-10 15:56:46 W/stderr:   ... 10 more
2022-11-10 15:56:46 W/stderr: Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 4132 out of bounds for byte[4096]
2022-11-10 15:56:46 W/stderr:   at java.base/java.lang.System.arraycopy(Native Method)
2022-11-10 15:56:46 W/stderr:   at io.ktor.utils.io.bits.MemoryJvmKt.copyTo-9zorpBc(MemoryJvm.kt:117)
2022-11-10 15:56:46 W/stderr:   at io.ktor.utils.io.core.BufferPrimitivesKt.readFully(BufferPrimitives.kt:1098)
2022-11-10 15:56:46 W/stderr:   at io.ktor.utils.io.core.InputArraysKt.readFully(InputArrays.kt:8)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage$suspendImpl(MessageProtocolStrategy.kt:358)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.message.protocol.outgoing.GroupMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt:139)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.process(GeneralMessageSenderProtocol.kt:64)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:26)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:20)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:287)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoingImpl(MessageProtocolFacade.kt:361)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoing(MessageProtocolFacade.kt:345)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.preprocessAndSendOutgoing(MessageProtocolFacade.kt)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:263)
2022-11-10 15:56:46 W/stderr:   at net.mamoe.mirai.internal.contact.AbstractUserKt$sendMessageImpl$1.invokeSuspend(AbstractUser.kt)
2022-11-10 15:56:46 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2022-11-10 15:56:46 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:283)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:278)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:260)
2022-11-10 15:56:46 W/stderr:   at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
2022-11-10 15:56:46 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2022-11-10 15:56:46 W/stderr:   ... 7 more
```
顺便提一下，这个异常是机器人试图发出长文本时抛出的，短文本就没出现这个问题
