### ISSUE TITLE
Mirai自动登录出错

### ISSUE THREAD

**Issue by itzdrli** [mamoe/mirai#2311]
### 问题描述

在首次启动成功添加了auto-login某个qq号，然后重启→登录，做验证等等都没有问题，然后登陆时出现报错

### 复现

正常添加各种信息如autologin等
然后config/Console/AutoLogin.yml中账号下方添加`enable: true`和`protocol: ANDROID_WATCH`
然后登录

### mirai-core 版本

2.13.0-RC

### bot-protocol

ANDROID_WATCH

### 系统日志

```text
2022-10-27 15:29:50 I/main: 9 plugin(s) enabled.
2022-10-27 15:29:50 I/main: Auto-login 486237638
2022-10-27 15:29:56 E/main: net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
        at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299)
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275)
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295)
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319)
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318)
        at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623)
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368)
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

2022-10-27 15:29:56 I/Bot.486237638: Bot cancelled: Bot closed
```
```


### 网络日志

_No response_

### 补充信息

_No response_

**Comment by cssxsh** [comment]
请确认 mirai 版本是 2.13.0-RC 或者 2.13.0-RC2

**Comment by itzdrli** [comment]
> 

mirai版本是2.13.0-RC，之前2.12.3也是这样

**Comment by cssxsh** [comment]
和 https://github.com/mamoe/mirai/issues/2167 是一样的, 之前修复过一次 https://github.com/mamoe/mirai/pull/2228, 没彻底修好

https://github.com/SkyNet1748/mirai/blob/4d8db26ba002396172573e0cf830aca363eb0813/mirai-core/src/commonMain/kotlin/utils/MiraiProtocolInternal.kt#L60-L71



miscBitMap 部分还需要修改 `184024956` -> `16252796`

**Comment by itzdrli** [comment]
> 和 #2167 是一样的, 之前修复过一次 #2228, 没彻底修好
> 
> https://github.com/SkyNet1748/mirai/blob/4d8db26ba002396172573e0cf830aca363eb0813/mirai-core/src/commonMain/kotlin/utils/MiraiProtocolInternal.kt#L60-L71
> 
> miscBitMap 部分还需要修改 `184024956` -> `16252796`

那现在的解决办法有什么吗？换协议？

**Comment by cssxsh** [comment]
> > 和 #2167 是一样的, 之前修复过一次 #2228, 没彻底修好
> > https://github.com/SkyNet1748/mirai/blob/4d8db26ba002396172573e0cf830aca363eb0813/mirai-core/src/commonMain/kotlin/utils/MiraiProtocolInternal.kt#L60-L71
> > miscBitMap 部分还需要修改 `184024956` -> `16252796`
> 
> 那现在的解决办法有什么吗？换协议？

换协议 比如 IPAD

**Comment by itzdrli** [comment]
> > > 和 #2167 是一样的, 之前修复过一次 #2228, 没彻底修好
> > > https://github.com/SkyNet1748/mirai/blob/4d8db26ba002396172573e0cf830aca363eb0813/mirai-core/src/commonMain/kotlin/utils/MiraiProtocolInternal.kt#L60-L71
> > > miscBitMap 部分还需要修改 `184024956` -> `16252796`
> > 
> > 
> > 那现在的解决办法有什么吗？换协议？
> 
> 换协议 比如 IPAD

肥肠感谢
