### ISSUE TITLE
[bug] 当前QQ版本过低，请升级至最新版本后再登录

### ISSUE THREAD

**Issue by lightsing** [mamoe/mirai#2313]
### 问题描述

无法登录新的 bot, 测试包括 2.13.0-RC2 也有相同问题，已经确认密码正确
```
2022-10-29 16:19:42 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(****), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
2022-10-29 16:19:42 I/main: mirai-console started successfully.
2022-10-29 16:19:42 I/Bot.****: Bot cancelled: Bot closed
```

### 复现

autoLogin 完成 captcha 后出现错误

### mirai-core 版本

2.12.3

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
[92m2022-10-29 14:42:40 I/main: Starting mirai-console...[0m[m
[92m2022-10-29 14:42:40 I/main: Backend: version 2.12.3, built on 2022-09-11 21:02:46.[0m[m
[92m2022-10-29 14:42:40 I/main: Frontend Terminal: version 2.12.3, provided by Mamoe Technologies[0m[m
[92m2022-10-29 14:42:40 I/main: Welcome to visit https://mirai.mamoe.net/[0m[m
[91m2022-10-29 14:42:41 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".[0m[m
[91m2022-10-29 14:42:41 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation[0m[m
[91m2022-10-29 14:42:41 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.[0m[m
[92m2022-10-29 14:42:41 I/plugin: Successfully loaded plugin Comet Workshop v0.1.0[0m[m
[92m2022-10-29 14:42:41 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop[0m[m
[92m2022-10-29 14:42:41 I/Comet Workshop: Plugin loaded[0m[m
[92m2022-10-29 14:42:41 I/main: 1 plugin(s) enabled.[0m[m
[91m2022-10-29 14:42:41 W/stderr: [0m[m
[92m2022-10-29 14:42:41 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.[0m[m
[92m2022-10-29 14:42:41 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.[0m[m
[92m2022-10-29 14:42:41 I/main: Auto-login 1670189420[0m[m
[91m2022-10-29 14:42:41 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...[0m[m
[91m2022-10-29 14:42:43 W/stderr: Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.[0m[m
[92m2022-10-29 14:43:08 I/Bot.***** Bot cancelled: Bot closed[0m[m
[31m2022-10-29 14:43:08 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1670189420), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(****), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: java.util.concurrent.CancellationException: Bot closed
		at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
		at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:112)
		at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:84)
		at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136)
		at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
		at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
		at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
		at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
		at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
		at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
		at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:245)
		at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
		at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
		at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
		at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
	Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(****), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)]
[0m[m
[92m2022-10-29 14:43:08 I/main: mirai-console started successfully.[0m[m
[91m2022-10-29 14:46:06 W/console: Closing input service...[0m[m
```

**Comment by cssxsh** [comment]
已有相似问题

https://github.com/mamoe/mirai/issues/2298
