### ISSUE TITLE
2.13.0-RC2启动时报错kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by Deficuet** [mamoe/mirai#2317]
### 问题描述

使用.bat手动启动：
```
@echo off
java -cp "./libs/*" net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader %*
pause
```
控制台窗口显示后马上打印该报错信息，之后显现Mirai Console字符画。启动完成之后，指令栏无法输入任何字符
openjdk版本11.0.2
启动过程中完全不动控制台窗口也会报该错误。不知道是否需要提供cmd的属性和默认值？

### 复现

libs文件夹内放入如下三个文件：
mirai-console-2.13.0-RC2-all.jar
mirai-console-terminal-2.13.0-RC2-all.jar
mirai-core-all-2.13.0-RC2-all.jar

之后启动.bat即可

### mirai-core 版本

2.13.0-RC2

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
Exception in thread "WindowsStreamPump" kotlin.UninitializedPropertyAccessException
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.getBridge$mirai_console(MiraiConsoleImplementation.kt:491)
        at net.mamoe.mirai.console.MiraiConsole$INSTANCE.__delegate_0$lambda-6(MiraiConsole.kt:161)
        at net.mamoe.mirai.console.MiraiConsole$INSTANCE.$$delegate_0-wrapper(MiraiConsole.kt)
        at net.mamoe.mirai.console.MiraiConsole$INSTANCE.getMainLogger(MiraiConsole.kt)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoaderKt$initSignalHandler$1.invoke(MiraiConsoleTerminalLoader.kt:202)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoaderKt$initSignalHandler$1.invoke(MiraiConsoleTerminalLoader.kt:200)
        at net.mamoe.mirai.console.terminal.MiraiConsoleImplementationTerminalKt.terminal$lambda-7$lambda-0(MiraiConsoleImplementationTerminal.kt:185)
        at org.jline.terminal.impl.AbstractTerminal.raise(AbstractTerminal.java:89)
        at org.jline.terminal.impl.jansi.win.JansiWinSysTerminal.processConsoleInput(JansiWinSysTerminal.java:151)
        at org.jline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:460)
        at java.base/java.lang.Thread.run(Thread.java:834)
2022-10-22 21:12:06 I/main: Starting mirai-console...
2022-10-22 21:12:06 I/main:
 
================================[ Mirai consosle 2.13.0-RC2 ]=================================
```

### 补充信息

什么protocol其实不重要

**Comment by Karlatemp** [comment]
请不要在 console 还在初始化的时候改变窗口大小, 这个问题已经修复了 (48143d7b3c0057a7344993a5d46ff735a03e1037)

**Comment by Deficuet** [comment]
我写了啊，弹出窗口后根本没动窗口。需要cmd的属性和默认值吗？

**Comment by Karlatemp** [comment]
你可以先在最新的 dev 构建中找到 mirai-console 临时替换

**Comment by Karlatemp** [comment]
这个问题已经修了, 目前已知的原因就是因为窗口大小调整
