### ISSUE TITLE
[Exception] image upload failed

### ISSUE THREAD

**Issue by boxlab** [mamoe/mirai#232]
An exception catched when **sending** image to group.

```
java.lang.IllegalStateException: image upload failed: Transfer errno=10206
	at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImage$$inlined$use$lambda$1.emit(Collect.kt:152)
	at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImage$$inlined$use$lambda$1$1.invokeSuspend(Unknown Source)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.contact.ContactJavaFriendlyAPI.sendMessage(ContactJavaFriendlyAPI.kt:345)
	at me.redneno.hoshinoharuka.lambda$onEnable$0(hoshinoharuka.java:150)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Him188** [comment]
感谢, 请协助以下问题:
- 提供上传时的原图
- 是第一次上传还是重复上传
- 重试上传是否能解决问题

**Comment by boxlab** [comment]
1. 原图 [https://send.boxmoe.cn/download/1350763aba0d72aa/#njJsicEIBPs9PhSuVtbVEA](https://send.boxmoe.cn/download/1350763aba0d72aa/#njJsicEIBPs9PhSuVtbVEA)
2. 多次尝试失败
3. 同上

除此之外还有部分NSFW/敏感图片，似乎是被QQ自动拦截了

**Comment by Him188** [comment]
文件似乎过期? 无法下载

**Comment by Him188** [comment]
经测试图片可以正常发送, 问题是长消息发送失败. 
可尝试 0.37.3 版本, 优化了长消息过程

**Comment by boxlab** [comment]
尝试了 0.37.4 版本，仍然存在同样问题。
另外，我尝试使用腾讯QQ客户端发送出现问题的图片会有如下提示
![image](https://user-images.githubusercontent.com/26276464/79598216-21874c00-8116-11ea-83d6-27c8753b48f8.png)

**Comment by Him188** [comment]
可能是账号问题，我的账号可以发送这张图片

**Comment by boxlab** [comment]
我测试了三个账号都无法发送。
*BTW：是否有什么办法可以改变图片的特征呢？QQ识别图片的依据是什么*

**Comment by mzdluo123** [comment]
无法发送，pc tim客户端以图片形式发送图片显示成功，在其他设备无法看到
建议不要发送你认为不该发送的图片
