### ISSUE TITLE
升级 2.13.0 后仍然提示“”当前QQ版本过低，请升级至最新版本后再登录

### ISSUE THREAD

**Issue by ByteTuxiaobei** [mamoe/mirai#2323]
### 问题描述

启动后提示
```
2022-11-01 23:37:10 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(*), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(*), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:309)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
无法正常登录

### 复现

执行登录
```
./mcl
```

### mirai-core 版本

2.13.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

```
  23:35:41 [INFO] Verifying "net.mamoe:mirai-console" v2.13.0
  23:35:42 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.0
  23:35:42 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.0
  23:35:42 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2
  23:35:42 [INFO] Verifying "net.mamoe:mirai-api-http" v2.6.2
```

**Comment by Karlatemp** [comment]
你需要先删除 `bots\XXXXX` 的数据

**Comment by ByteTuxiaobei** [comment]
> 你需要先删除 `bots\XXXXX` 的数据

谢谢，已经解决
