### ISSUE TITLE
2.13.0找不到OkHttp

### ISSUE THREAD

**Issue by xiaokun5460** [mamoe/mirai#2324]
### 问题描述

引入依赖缺失问题.经测试2.13.0-RC2无问题.异常发生于`BotFactory.INSTANCE.newBot(qq, password, config);`

```
Caused by: java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586) ~[na:na]
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813) ~[na:na]
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729) ~[na:na]
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403) ~[na:na]
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:270) ~[kotlin-stdlib-1.6.21.jar:1.6.21-release-334(1.6.21)]
	at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:18) ~[mirai-core-utils-jvm-2.13.0.jar:2.13.0]
	at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357) ~[mirai-core-api-jvm-2.13.0.jar:2.13.0]
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348) ~[mirai-core-api-jvm-2.13.0.jar:2.13.0]
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39) ~[mirai-core-api-jvm-2.13.0.jar:2.13.0]
	at net.mamoe.mirai.internal.message.MessageSerializersImpl.getSerializersModule(MessageSerializersImpl.kt:65) ~[mirai-core-api-jvm-2.13.0.jar:2.13.0]
	at net.mamoe.mirai.internal.message.MessageSerializersImpl.registerSerializers(MessageSerializersImpl.kt:76) ~[mirai-core-api-jvm-2.13.0.jar:2.13.0]
	at net.mamoe.mirai.message.MessageSerializers$INSTANCE.registerSerializers(MessageSerializers.kt) ~[mirai-core-api-jvm-2.13.0.jar:2.13.0]
	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade.<clinit>(MessageProtocolFacade.kt:165) ~[mirai-core-jvm-2.13.0.jar:2.13.0]
	at net.mamoe.mirai.internal.MiraiImplKt._MiraiImpl_static_init(MiraiImpl.kt:25) ~[mirai-core-jvm-2.13.0.jar:2.13.0]
	at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt:87) ~[mirai-core-jvm-2.13.0.jar:2.13.0]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789) ~[na:na]
	... 39 common frames omitted
Caused by: java.lang.NoClassDefFoundError: net/mamoe/mirai/internal/deps/io/ktor/client/engine/okhttp/OkHttp
	at net.mamoe.mirai.internal.MiraiImplKt.createDefaultHttpClient(MiraiImpl.kt:29) ~[mirai-core-jvm-2.13.0.jar:2.13.0]
	at net.mamoe.mirai.internal.MiraiImpl.<init>(MiraiImpl.kt:97) ~[mirai-core-jvm-2.13.0.jar:2.13.0]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789) ~[na:na]
	... 58 common frames omitted
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttp
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 66 common frames omitted
```

### 复现

Java maven 引入2.13.0版本 执行BotFactory.INSTANCE.newBot(qq, password, config);

### mirai-core 版本

2.13.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

<dependency>
        <groupId>net.mamoe</groupId>
        <artifactId>mirai-core-jvm</artifactId>
        <version>2.13.0</version>
</dependency>

**Comment by aowubulao** [comment]
相同的问题，尝试引入ktor相关依赖后依然不行，这是部分dependency tree

```
[INFO] +- net.mamoe:mirai-core-jvm:jar:2.13.0:compile
[INFO] |  +- net.mamoe:mirai-core-api-jvm:jar:2.13.0:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-reflect:jar:1.7.10:compile
[INFO] |  |  \- net.mamoe:mirai-console-compiler-annotations-jvm:jar:2.13.0:runtime
[INFO] |  +- org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:jar:1.3.3:compile
[INFO] |  +- org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:jar:1.3.3:compile
[INFO] |  +- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:jar:1.6.4:compile
[INFO] |  +- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.7.10:compile
[INFO] |  +- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:jar:1.3.8:compile
[INFO] |  +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.7.10:compile
[INFO] |  |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.7.10:compile
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.64:runtime
[INFO] |  +- me.him188:kotlin-jvm-blocking-bridge-runtime-jvm:jar:2.1.0-170.1:runtime
[INFO] |  +- me.him188:kotlin-dynamic-delegation-jvm:jar:0.3.0-170.1:runtime
[INFO] |  +- net.mamoe:mirai-core-utils-jvm:jar:2.13.0:runtime
[INFO] |  +- org.jetbrains.kotlinx:kotlinx-serialization-protobuf-jvm:jar:1.3.3:runtime
[INFO] |  +- org.jetbrains.kotlinx:atomicfu-jvm:jar:0.18.3:runtime
[INFO] |  \- io.netty:netty-all:jar:4.1.53.Final:runtime
[INFO] +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.7.10:compile
[INFO] |  \- org.jetbrains:annotations:jar:13.0:compile
[INFO] +- org.jetbrains.kotlinx:kotlinx-coroutines-core:jar:1.6.4:compile
```

**Comment by SamsaraEventually** [comment]
我也遇到了相同问题，似乎是编译版本和运行版本有差异

**Comment by qoxyfega** [comment]
我也遇到了相同问题

**Comment by cssxsh** [comment]
你需要加上依赖 `net.mamoe:mirai-core-utils:2.13.0`

**Comment by SamsaraEventually** [comment]
我引入了net.mamoe:mirai-core-utils:2.13.0但是还是一样的找不到okhttp

**Comment by lcx1969001** [comment]
> 我引入了net.mamoe:mirai-core-utils:2.13.0但是还是一样的找不到okhttp

我也是

**Comment by cssxsh** [comment]
目前无法手动处理，只能等修复
原因是 2.13.0 发布时修改了编译打包设置

https://github.com/mamoe/mirai/compare/v2.13.0-RC2...v2.13.0#diff-90410215d59de60e5ebebdfa1af243eed642bd322687057a0c3d089b6a2846e2

**Comment by Him188** [comment]
那个是为了解决 #2291，测试通过了，不知道为什么发版不行

**Comment by Baishou-Kl** [comment]
这个问题目前解决了吗 2.13.0版本

**Comment by Baishou-Kl** [comment]
> 目前无法手动处理，只能等修复 原因是 2.13.0 发布时修改了编译打包设置
> 
> [v2.13.0-RC2...v2.13.0#diff-90410215d59de60e5ebebdfa1af243eed642bd322687057a0c3d089b6a2846e2](https://github.com/mamoe/mirai/compare/v2.13.0-RC2...v2.13.0#diff-90410215d59de60e5ebebdfa1af243eed642bd322687057a0c3d089b6a2846e2)

这个问题目前解决了吗 2.13.0版本

**Comment by Alceatraz** [comment]
之前换用 2.13RC的时候也遇到了，`net/mamoe/mirai/internal/deps/io/ktor/client/engine/okhttp/OkHttp` 我用的是`java -cd "lib/*.jar" xxxxx.Main` 的运行方法，吧okhttp mirai-core-utils放里边也没用。先退回2.12苟一波（
话说him连在咖啡馆都修BUG也太惨了5555555555
