### ISSUE TITLE
自`564a7ce8`起，无法启动mirai

### ISSUE THREAD

**Issue by Nekoer** [mamoe/mirai#2329]
### 问题描述

`564a7ce8`开始启动出现下面错误
```
"C:\Program Files\Java\jdk-18.0.2.1\bin\java.exe" "-javaagent:D:\IntelliJ IDEA 2021.2.2\lib\idea_rt.jar=64906:D:\IntelliJ IDEA 2021.2.2\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath E:\mirai-plugins\mirai\mirai-console\frontend\mirai-console-terminal\build\classes\kotlin\test;E:\mirai-plugins\mirai\mirai-console\frontend\mirai-console-terminal\build\classes\kotlin\main;E:\mirai-plugins\mirai\mirai-console\frontend\mirai-console-terminal\build\resources\main;E:\.gradle\caches\modules-2\files-2.1\org.jline\jline\3.21.0\2bf6f2311356f309fda0412e9389d2499346b5a1\jline-3.21.0.jar;E:\.gradle\caches\modules-2\files-2.1\org.fusesource.jansi\jansi\2.4.0\321c614f85f1dea6bb08c1817c60d53b7f3552fd\jansi-2.4.0.jar;E:\mirai-plugins\mirai\mirai-console\frontend\mirai-console-frontend-base\build\classes\kotlin\main;E:\mirai-plugins\mirai\mirai-core\build\classes\kotlin\jvm\main;E:\mirai-plugins\mirai\mirai-console\backend\mirai-console\build\classes\atomicfu\main;E:\mirai-plugins\mirai\mirai-console\backend\mirai-console\build\resources\main;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-test-junit5\1.7.10\1977faecddc1c312be4775e6110d3072f553d89d\kotlin-test-junit5-1.7.10.jar;E:\.gradle\caches\modules-2\files-2.1\org.junit.jupiter\junit-jupiter-api\5.7.2\f4b4079732a9c537983324cfa4e46655f21d2c56\junit-jupiter-api-5.7.2.jar;E:\mirai-plugins\mirai\mirai-core-utils\build\classes\kotlin\jvm\main;E:\mirai-plugins\mirai\mirai-core-api\build\classes\kotlin\jvm\main;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.7.10\d70d7d2c56371f7aa18f32e984e3e2e998fe9081\kotlin-stdlib-jdk8-1.7.10.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-jdk8\1.6.4\5bc4b0bf6fd90fc190fd2f17e919c74c6274cb71\kotlinx-coroutines-jdk8-1.6.4.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.7.10\bac80c520d0a9e3f3673bc2658c6ed02ef45a76a\kotlin-stdlib-common-1.7.10.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-test\1.7.10\4d644a88cc0a386712d4b1c1b4ca748203421e07\kotlin-test-1.7.10.jar;E:\.gradle\caches\modules-2\files-2.1\org.junit.platform\junit-platform-commons\1.7.2\34adfea6c13fc4a996cf38cdad80800ce850d198\junit-platform-commons-1.7.2.jar;E:\.gradle\caches\modules-2\files-2.1\org.apiguardian\apiguardian-api\1.1.0\fc9dff4bb36d627bdc553de77e1f17efd790876c\apiguardian-api-1.1.0.jar;E:\.gradle\caches\modules-2\files-2.1\org.opentest4j\opentest4j\1.2.0\28c11eb91f9b6d8e200631d46e20a7f407f2a046\opentest4j-1.2.0.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.7.10\165e600dfea6185cf5efa700756294cc4904dbeb\kotlin-reflect-1.7.10.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.7.10\1ef73fee66f45d52c67e2aca12fd945dbe0659bf\kotlin-stdlib-jdk7-1.7.10.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.7.10\d2abf9e77736acc4450dc4a3f707fa2c10f5099d\kotlin-stdlib-1.7.10.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-core-jvm\1.6.4\2c997cd1c0ef33f3e751d3831929aeff1390cb30\kotlinx-coroutines-core-jvm-1.6.4.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-serialization-json-jvm\1.3.3\6298c404c1159685fb657f15fa5b78630da58c96\kotlinx-serialization-json-jvm-1.3.3.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-serialization-core-jvm\1.3.3\3c22103b5d8e3c262db19e85d90405ca78b49efd\kotlinx-serialization-core-jvm-1.3.3.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar;E:\.gradle\caches\modules-2\files-2.1\org.junit.jupiter\junit-jupiter-engine\5.7.2\9415680a889f00b8205a094c5c487bc69dc7077d\junit-jupiter-engine-5.7.2.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-compress\1.21\4ec95b60d4e86b5c95a0e919cb172a0af98011ef\commons-compress-1.21.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-api\2.17.2\f42d6afa111b4dec5d2aea0fe2197240749a4ea6\log4j-api-2.17.2.jar;E:\.gradle\caches\modules-2\files-2.1\io.netty\netty-handler\4.1.63.Final\879a43c2325b08e92e8967218b6ddb0ed4b7a0d3\netty-handler-4.1.63.Final.jar;E:\.gradle\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.64\1467dac1b787b5ad2a18201c0c281df69882259e\bcprov-jdk15on-1.64.jar;E:\mirai-plugins\mirai\mirai-console\tools\compiler-annotations\build\classes\kotlin\jvm\main;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\19.0.0\efbff6752f67a7c9de3e4251c086a88e23591dfd\annotations-19.0.0.jar;E:\.gradle\caches\modules-2\files-2.1\io.github.karlatemp\caller\1.1.1\fac1cd2ebcd66bc514893627baa852beaeef2f65\caller-1.1.1.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-resolver-provider\3.8.4\2ccbd1e2c713922353ccd779e56aeefc7a9fa56f\maven-resolver-provider-3.8.4.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven.resolver\maven-resolver-impl\1.7.3\664533f46b4d74ec0e7d74ce76e06c74d89b5269\maven-resolver-impl-1.7.3.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven.resolver\maven-resolver-connector-basic\1.7.3\ace036615ca70d065cbf4966ea6eb1076565d902\maven-resolver-connector-basic-1.7.3.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven.resolver\maven-resolver-transport-http\1.7.3\8b094a65725c6e427e2f834e0c5049410e13a114\maven-resolver-transport-http-1.7.3.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven.resolver\maven-resolver-api\1.7.3\2602fc14676d79d1802dcc3bfcfb3628c598ee8\maven-resolver-api-1.7.3.jar;E:\.gradle\caches\modules-2\files-2.1\org.junit.platform\junit-platform-engine\1.7.2\2573770b46b8a199ed5f6b0f96fb99e468bfe891\junit-platform-engine-1.7.2.jar;E:\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-client-okhttp-jvm\2.1.0\bf6a93539f7dc95bcb09fda9763624cd47667034\ktor-client-okhttp-jvm-2.1.0.jar;E:\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-client-core-jvm\2.1.0\9f817ae55e463f27d885ef051ff88e4c2acea7da\ktor-client-core-jvm-2.1.0.jar;E:\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-io-jvm\2.1.0\ccd958db554677538c21515a0acd62862bb6b2a0\ktor-io-jvm-2.1.0.jar;E:\.gradle\caches\modules-2\files-2.1\me.him188\kotlin-jvm-blocking-bridge-runtime-jvm\2.1.0-170.1\ec9edfb542ecc33a866ee29272f377d3874fe142\kotlin-jvm-blocking-bridge-runtime-jvm-2.1.0-170.1.jar;E:\.gradle\caches\modules-2\files-2.1\me.him188\kotlin-dynamic-delegation-jvm\0.3.0-170.1\26e8caa5b5f09229032906571fee57b784713470\kotlin-dynamic-delegation-jvm-0.3.0-170.1.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-serialization-protobuf-jvm\1.3.3\5827acdf771e6d013c208107876f222a57c1016\kotlinx-serialization-protobuf-jvm-1.3.3.jar;E:\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec\4.1.63.Final\d4d2fccea88c80e56d59ce1053c53df0f9f4f5db\netty-codec-4.1.63.Final.jar;E:\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport\4.1.63.Final\9a8bbe1ba082c9434e6f524d3864a53f340f2df\netty-transport-4.1.63.Final.jar;E:\.gradle\caches\modules-2\files-2.1\io.netty\netty-resolver\4.1.63.Final\d07cd47c101dfa655d6d5cc304d523742fd78ca8\netty-resolver-4.1.63.Final.jar;E:\.gradle\caches\modules-2\files-2.1\io.netty\netty-buffer\4.1.63.Final\40028ce5ac7c43f1c9a1439f74637cad04013e23\netty-buffer-4.1.63.Final.jar;E:\.gradle\caches\modules-2\files-2.1\io.netty\netty-common\4.1.63.Final\e1206b46384d4dcbecee2901f18ce65ecf02e8a4\netty-common-4.1.63.Final.jar;E:\.gradle\caches\modules-2\files-2.1\net.mamoe.yamlkt\yamlkt-jvm\0.12.0\94be70bd28ae8f0d75ec7811fc531d68712f795d\yamlkt-jvm-0.12.0.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven.resolver\maven-resolver-spi\1.7.3\322ed310bc40aa548d58b555130b27e1887bfda3\maven-resolver-spi-1.7.3.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven.resolver\maven-resolver-util\1.7.3\9c7bad4dd3912beb3bcbca777359088e98235f52\maven-resolver-util-1.7.3.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-model-builder\3.8.4\8e039db854cee3ddbca932b90c0c06cdcb9dc640\maven-model-builder-3.8.4.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-model\3.8.4\71057054ea1e5e341b2196804a426e3243f6cb2e\maven-model-3.8.4.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-repository-metadata\3.8.4\c62113372f740797767d520f604d0543dcdfc92f\maven-repository-metadata-3.8.4.jar;E:\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-utils\3.3.0\cf43b5391de623b36fe066a21127baef82c64022\plexus-utils-3.3.0.jar;E:\.gradle\caches\modules-2\files-2.1\javax.inject\javax.inject\1\6975da39a7040257bd51d21a231b76c915872d38\javax.inject-1.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven.resolver\maven-resolver-named-locks\1.7.3\71bb6016d8d415836187b791a9df3bf5cb401c44\maven-resolver-named-locks-1.7.3.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-lang3\3.8.1\6505a72a097d9270f7a9e7bf42c4238283247755\commons-lang3-3.8.1.jar;E:\.gradle\caches\modules-2\files-2.1\javax.annotation\javax.annotation-api\1.3.2\934c04d3cfef185a8008e7bf34331b79730a9d43\javax.annotation-api-1.3.2.jar;E:\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.36\6c62681a2f655b49963a5983b8b0950a6120ae14\slf4j-api-1.7.36.jar;E:\.gradle\caches\modules-2\files-2.1\org.slf4j\jcl-over-slf4j\1.7.32\32c060250bcc5282cdbc1fd7008c12eb4ebad00e\jcl-over-slf4j-1.7.32.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpclient\4.5.13\e5f6cae5ca7ecaac1ec2827a9e2d65ae2869cada\httpclient-4.5.13.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.httpcomponents\httpcore\4.4.14\9dd1a631c082d92ecd4bd8fd4cf55026c720a8c1\httpcore-4.4.14.jar;E:\.gradle\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\4.9.3\b0b14b3d12980912723fb8b66afb48dcda742fcb\okhttp-4.9.3.jar;E:\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlinx\kotlinx-coroutines-slf4j\1.6.4\9369fcabacb66a55ca3b7939b72bb0b62af112ce\kotlinx-coroutines-slf4j-1.6.4.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-artifact\3.8.4\6dba6d03ac7abd8b895595b0ee7000ce35c3d421\maven-artifact-3.8.4.jar;E:\.gradle\caches\modules-2\files-2.1\org.codehaus.plexus\plexus-interpolation\1.26\25b919c664b79795ccde0ede5cee0fd68b544197\plexus-interpolation-1.26.jar;E:\.gradle\caches\modules-2\files-2.1\org.apache.maven\maven-builder-support\3.8.4\19e7c1dd9ab8c3266db19e067e2b7b8764f0fa6a\maven-builder-support-3.8.4.jar;E:\.gradle\caches\modules-2\files-2.1\org.eclipse.sisu\org.eclipse.sisu.inject\0.3.5\d4265dd4f0f1d7a06d80df5a5f475d5ff9c17140\org.eclipse.sisu.inject-0.3.5.jar;E:\.gradle\caches\modules-2\files-2.1\commons-codec\commons-codec\1.11\3acb4705652e16236558f0f4f2192cc33c3bd189\commons-codec-1.11.jar;E:\.gradle\caches\modules-2\files-2.1\com.squareup.okio\okio\2.8.0\49b64e09d81c0cc84b267edd0c2fd7df5a64c78c\okio-jvm-2.8.0.jar;E:\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-events-jvm\2.1.0\ef58c3c3d012ab115011af1e2f2afc357433c220\ktor-events-jvm-2.1.0.jar;E:\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-websocket-serialization-jvm\2.1.0\d202979642d5091a18587b3f81269c0a9a8acc78\ktor-websocket-serialization-jvm-2.1.0.jar;E:\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-http-jvm\2.1.0\eff494019c2c1a0e9db6e13533d241ecd6bbc822\ktor-http-jvm-2.1.0.jar;E:\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-utils-jvm\2.1.0\1b3ca53f817d054ba00c8a3e92a50ba655428c71\ktor-utils-jvm-2.1.0.jar;E:\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-serialization-jvm\2.1.0\e1d36c91035d2eddd1f202411248a4b6944ea387\ktor-serialization-jvm-2.1.0.jar;E:\.gradle\caches\modules-2\files-2.1\io.ktor\ktor-websockets-jvm\2.1.0\17015d23235fd5e784230875e630f6bd1418fdf8\ktor-websockets-jvm-2.1.0.jar net.mamoe.mirai.console.terminal.RunTerminalKt
[Mirai Console] Set user.dir = E:\mirai-plugins\mirai\.\mirai-console\frontend\mirai-console-terminal\run
Exception in thread "main" java.lang.NoClassDefFoundError: kotlinx/atomicfu/AtomicFU
	at net.mamoe.mirai.utils.LateinitMutableProperty.<init>(LateinitMutableProperty.kt:37)
	at net.mamoe.mirai.utils.LateinitMutablePropertyKt.lateinitMutableProperty(LateinitMutableProperty.kt:32)
	at net.mamoe.mirai.utils.MiraiLoggerFactoryImplementationBridge.<clinit>(MiraiLogger.kt:269)
	at net.mamoe.mirai.console.frontendbase.AbstractMiraiConsoleFrontendImplementation.createLoggerFactory(AbstractMiraiConsoleFrontendImplementation.kt:97)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.<init>(MiraiConsoleImplementationBridge.kt:144)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:505)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.RunTerminalKt.main(RunTerminal.kt:34)
	at net.mamoe.mirai.console.terminal.RunTerminalKt.main(RunTerminal.kt)
Caused by: java.lang.ClassNotFoundException: kotlinx.atomicfu.AtomicFU
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 9 more

进程已结束,退出代码1
```
`564a7ce8`之前几个版本会出现以下内容：
```
2022-11-02 17:20:46 I/main: Starting mirai-console...
2022-11-02 17:20:47 I/main: 

==================================[ Mirai consosle 2.14.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2022-11-02 17:20:47 I/main: Backend: version 2.14.0, built on 2022-11-02 17:20:33.
2022-11-02 17:20:47 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2022-11-02 17:20:47 I/main: Welcome to visit https://mirai.mamoe.net/
2022-11-02 17:20:47 V/main: Loading configurations...
2022-11-02 17:20:48 E/main: Failed to init MiraiConsole.
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.IMirai
	at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:21)
	at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357)
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39)
	at net.mamoe.mirai.internal.message.MessageSerializersImpl.getSerializersModule(MessageSerializersImpl.kt:65)
	at net.mamoe.mirai.message.MessageSerializers$INSTANCE.getSerializersModule(MessageSerializers.kt)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl$createYaml$1.invoke(MultiFilePluginDataStorageImpl.kt:114)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl$createYaml$1.invoke(MultiFilePluginDataStorageImpl.kt:112)
	at net.mamoe.yamlkt.YamlKt.Yaml(Yaml.kt:242)
	at net.mamoe.yamlkt.YamlKt.Yaml$default(Yaml.kt:240)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.createYaml(MultiFilePluginDataStorageImpl.kt:112)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:43)
	at net.mamoe.mirai.console.internal.data.builtins.ConsoleDataScopeImpl.addAndReloadConfig(ConsoleDataScopeImpl.kt:41)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:265)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.RunTerminalKt.main(RunTerminal.kt:34)
	at net.mamoe.mirai.console.terminal.RunTerminalKt.main(RunTerminal.kt)
	Suppressed: java.lang.ExceptionInInitializerError
		at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade.<clinit>(MessageProtocolFacade.kt)
		at net.mamoe.mirai.internal.MiraiImplKt._MiraiImpl_static_init(MiraiImpl.kt:25)
		at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt:87)
		at java.base/java.lang.Class.forName0(Native Method)
		at java.base/java.lang.Class.forName(Class.java:315)
		at net.mamoe.mirai.utils.ServicesKt.findCreateInstance(Services.kt:27)
		at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:20)
		... 17 more
	Caused by: java.lang.IllegalStateException: Failed to load services for MessageProtocol from your classpath. Check you ClassLoader environment and ensure services for 'net.mamoe.mirai.internal.message.protocol.MessageProtocol' can be loaded. This should not happen if you are using mirai under default JVM classloader or using Mirai Console.If so, please file an issue. If you are trying to load mirai manually from other classloader, e.g. in another plugin system like Minecraft, it's your responsibility to ensure the Java SPI works.
		at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.<init>(MessageProtocolFacade.kt:208)
		at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.<init>(MessageProtocolFacade.kt:193)
		at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.<init>(MessageProtocolFacade.kt:162)
		at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.<clinit>(MessageProtocolFacade.kt)
		... 24 more

```

### 复现

[Guild Support分支](https://github.com/Nekoer/mirai) git pull下来执行

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

### 补充信息

均试过gradle clean 和 reimport

**Comment by Him188** [comment]
#2315 导致的

**Comment by Him188** [comment]
![image](https://user-images.githubusercontent.com/12100985/204155445-dccd2053-70be-4f50-bb41-df7e82211567.png)

可能是 Kotlin 问题, 也可能是 atomicFU 问题, classpath 里这应该是 `mirai-core-utils/build/classes/atomicfu/jvm/main`
![image](https://user-images.githubusercontent.com/12100985/204155488-6f4cef0d-cc0c-4649-9736-2d479b05839d.png)
