### ISSUE TITLE
在 GroupImpl 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by Deficuet** [mamoe/mirai#2333]
### 问题描述

插件启动bot登录时报错
已经加入该群很长时间了，只是个普通群员

### 复现

我不到啊

### mirai-core 版本

2.13.0

### bot-protocol

IPAD

### 系统日志

```text
2022-11-08 07:38:27 V/Net 1526905693: Recv: friendlist.GetTroopMemberListReq
2022-11-08 07:38:27 V/Net 1526905693: Recv: friendlist.GetTroopMemberListReq
2022-11-08 07:38:27 V/Net 1526905693: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)
2022-11-08 07:38:27 V/Net 1526905693: Recv: friendlist.GetTroopMemberListReq
2022-11-08 07:38:27 V/Net 1526905693: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)
2022-11-08 07:38:27 V/Net 1526905693: Recv: friendlist.GetTroopMemberListReq
2022-11-08 07:38:27 E/Group: ContextualBugReportException(message=在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 1037601822
groupUin: 1037601822
membersCount: 0
botId: 1526905693
owner: null, cause=null)
ContextualBugReportException(message=在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离 开这个群 调试信息: groupId: 1037601822
groupUin: 1037601822
membersCount: 0
botId: 1526905693
owner: null, cause=null)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
        at net.mamoe.mirai.internal.contact.GroupImplKt.GroupImpl(GroupImpl.kt:102)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.addGroupToBot(ContactUpdater.kt:252)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.access$addGroupToBot(ContactUpdater.kt:73)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl$addGroupToBot$1.invokeSuspend(ContactUpdater.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2022-11-08 07:38:27 V/Net 1526905693: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)
2022-11-08 07:38:27 V/Net 1526905693: Recv: friendlist.GetTroopMemberListReq
2022-11-08 07:38:27 V/Net 1526905693: Recv: friendlist.GetTroopMemberListReq
2022-11-08 07:38:27 V/Net 1526905693: Recv: friendlist.GetTroopMemberListReq
2022-11-08 07:38:27 V/Net 1526905693: Recv: friendlist.GetTroopMemberListReq
2022-11-08 07:38:27 V/Net 1526905693: Send: friendlist.GetTroopMemberListReq(friendlist.GetTroopMemberListReq)
2022-11-08 07:38:27 V/Net 1526905693: Recv: friendlist.GetTroopMemberListReq
```

**Comment by Him188** [comment]
#1977
