### ISSUE TITLE
能出个`2.13.0-fix`版之类的吗？

### ISSUE THREAD

**Issue by Coloryr** [mamoe/mirai#2339]
简单的修补下#2334 #2324 的问题
```
Exception in thread "main" java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:272)
	at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:18)
	at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357)
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39)
	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:116)
```

```
    val miraiVersion = "2.13.0"

    compile("net.mamoe", "mirai-core", miraiVersion)
    compile("net.mamoe", "mirai-core-utils", miraiVersion)
    compile("net.mamoe", "mirai-console" , miraiVersion)
    compile("net.mamoe", "mirai-console-terminal", miraiVersion)
    compile("net.mamoe", "mirai-console-frontend-base", miraiVersion)
```

（寄器人寄了好多天了，旧版用不了，新版也用不了

**Comment by Keyezi** [comment]
用RC2

**Comment by sandtechnology** [comment]
2.13.1好像在路上了 但是应该因为作者这几天太忙没空修 我这也是自己build的（

**Comment by Coloryr** [comment]
> 用RC2

RC2会有更新QQ的问题

**Comment by cssxsh** [comment]
> > 用RC2
> 
> RC2会有更新QQ的问题

换协议，比如 IPAD

**Comment by Him188** [comment]
最近太忙了, 在学校咖啡厅的时候都在修

#2331 刚修好, 再加点测试就可以了

**Comment by Him188** [comment]
#2331 修好就会马上发 2.13.1
