### ISSUE TITLE
2.13.0 最新版已无法登陆

### ISSUE THREAD

**Issue by WorldLeen** [mamoe/mirai#2347]
### 问题描述

已确认当前使用版本为 2.13.0 （最新）
事情是这样，首先我正在正常使用项目，随后提示需要进行滑动验证
于是我是用手机的验证APP通过验证，随后便第一次提示无法登陆，信息为：
“code=235”，“当前QQ版本过低”
我认为可能是之前的问题又出现了，于是我决定换几个协议试试，然而在多次切换协议后，QQ彻底无法登陆了，日志如下：
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2022-11-12 18:41:03 V/Net (QQ号隐藏): Loading server list from cache.
2022-11-12 18:41:03 V/Net (QQ号隐藏): Server list: 116.130.229.216:14000, 36.155.207.149:443, 43.154.240.21:8080, 183.47.102.62:80, msfwifi.3g.qq.com:8080.
2022-11-12 18:41:03 I/Net (QQ号隐藏): ECDH key is invalid, start to fetch ecdh public key from server.
2022-11-12 18:41:06 I/Net (QQ号隐藏): Successfully fetched ecdh public key from server.
2022-11-12 18:41:07 V/Net (QQ号隐藏): Send: wtlogin.login(9:password-login)
2022-11-12 18:41:07 I/Bot (QQ号隐藏): [SliderCaptcha] 需要滑动验证码, 请按照以下链接的步骤完成滑动验证码, 然后输入获取到的 ticket
2022-11-12 18:41:07 I/Bot (QQ号隐藏): [SliderCaptcha] Slider captcha required. Please solve the captcha with following link. Type ticket here after completion.
2022-11-12 18:41:07 I/Bot (QQ号隐藏): [SliderCaptcha] @see https://github.com/project-mirai/mirai-login-solver-selenium
2022-11-12 18:41:07 I/Bot (QQ号隐藏): [SliderCaptcha] @see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
2022-11-12 18:41:07 I/Bot (QQ号隐藏): [SliderCaptcha] 或者输入 TxCaptchaHelper 来使用 TxCaptchaHelper 完成滑动验证码
2022-11-12 18:41:07 I/Bot (QQ号隐藏): [SliderCaptcha] Or type `TxCaptchaHelper` to resolve slider captcha with TxCaptchaHelper.apk
2022-11-12 18:41:07 I/Bot (QQ号隐藏): [SliderCaptcha] Captcha link: https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=(QQ号隐藏)&sid=3424234047875807377&cap_cd=wrDlc4zl9sTnHYEIJf4FUhqS4IE3EMoSAfC6vrFsxfzfFgGM5M_Ntw**&clientype=1&apptype=2
2022-11-12 18:41:07 V/Net (QQ号隐藏): Recv: wtlogin.login
TxCaptchaHelper
2022-11-12 18:41:12 I/Bot (QQ号隐藏): [SliderCaptcha] @see https://github.com/mzdluo123/TxCaptchaHelper
2022-11-12 18:41:12 I/Bot (QQ号隐藏): Sending request...
2022-11-12 18:41:13 I/Bot (QQ号隐藏): 请在手机端使用请求码1852完成验证，完成后再次发送请求得到ticket
2022-11-12 18:41:24 V/Net (QQ号隐藏): Send: wtlogin.login(2:submit-slider)
2022-11-12 18:41:24 V/Net (QQ号隐藏): Recv: wtlogin.login
2022-11-12 18:41:24 W/Net (QQ号隐藏): Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot((QQ号隐藏)), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot((QQ号隐藏)), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:309)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        ... 9 more

2022-11-12 18:41:24 W/Net (QQ号隐藏): Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot((QQ号隐藏)), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=))
Exception in thread "main" net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot((QQ号隐藏)), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录 。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:309)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
2022-11-12 18:41:24 I/Bot (QQ号隐藏): Bot cancelled: Bot closed
```

除此以外，已使用所有协议尝试（ANDROID_PHONE，ANDROID_WATCH，MACOS）均有此问题
### mirai-core 版本

2.13.0

### bot-protocol

ANDROID_PHONE

**Comment by WorldLeen** [comment]
另外，我推测 网络不稳定 只是因为我频繁重试登陆
真正的问题应该是 2.13.0 也再次出现了“235 版本过低”的问题

在前几次尝试中，我已正确使用手机APP进行滑动和点击验证码验证，但程序无法正常登陆，提示为”版本过低“
因此我认为2.13.0（不是RC或RC-2）现在已经没有办法登陆上去了

**Comment by WorldLeen** [comment]
经过反复尝试，终于成功登陆了
顺便提醒一下各位朋友，任何时候如果失败超过3次就不要继续试了，否则就会出现237错误，真的登不上哦。

**Comment by ColdeZhang** [comment]
> 经过反复尝试，终于成功登陆了
> 顺便提醒一下各位朋友，任何时候如果失败超过3次就不要继续试了，否则就会出现237错误，真的登不上哦。

@WorldLeen 那如果出现了237怎么办呢？ 只能等一会儿继续再尝试？

**Comment by landall** [comment]
> 经过反复尝试，终于成功登陆了 顺便提醒一下各位朋友，任何时候如果失败超过3次就不要继续试了，否则就会出现237错误，真的登不上哦。

所以反复尝试，具体是做了什么，就是经常登录，然后输入ticket？

**Comment by aaacde** [comment]
感觉反复尝试登录出现237后  (无法登陆，疑似最新风控 "当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录 。) 该设别就被锁定无法登录了，或者qq被锁定无法在新设备登录，当错误变为版本过低后，换个设备可能可以登录成功。
