### ISSUE TITLE
在 MultiMsg.ApplyDown 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by Nambers** [mamoe/mirai#2348]
### 问题描述

接收一个转发消息

### 复现

None

### mirai-core 版本

2.13.0-RC2

### bot-protocol

MACOS

### 系统日志

```text
2022.11.16 11:00:11 [ERROR] Net <bot id> - Exception in decoding packet.
net.mamoe.mirai.internal.message.ContextualBugReportException: 在 MultiMsg.ApplyDown 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   Decode failure result=192 调试信息: MultiMsgApplyDownRsp#406025650 {
            bytesDownIpV6=[]
            msgResid=D9u1a9viNuBYi8ieFFbUG341/umcX1k0PSjoK9VolcXJrvfdDaZmmk+emdfMD0iF
            result=0x000000C0(192)
            uint32DownIp=[]
            uint32DownPort=[]
            uint32DownV6Port=[]
    }
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.protocol.packet.chat.MultiMsg$ApplyDown.decode(MultiMsg.kt:145) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.21.jar:1.7.21-release-272(1.7.21)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at java.lang.Thread.run(Thread.java:832) ~[?:?]
2022.11.16 11:00:11 [ERROR] Bot <bot id> - Exception on parsing packet.
java.lang.IllegalStateException: Exception in net.mamoe.mirai.internal.network.notice.group.GroupMessageProcessor@29326609 while processing packet PbPushMsg.
	at net.mamoe.mirai.internal.network.components.NoticeProcessorPipelineImpl.handleExceptionInProcess(NoticeProcessorPipeline.kt:105) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.components.NoticeProcessorPipelineImpl.handleExceptionInProcess(NoticeProcessorPipeline.kt:80) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:289) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline$process$2.invokeSuspend(ProcessorPipeline.kt) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.21.jar:1.7.21-release-272(1.7.21)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.7.21.jar:1.7.21-release-272(1.7.21)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.63.Final.jar:4.1.63.Final]
	at java.lang.Thread.run(Thread.java:832) ~[?:?]
Caused by: java.lang.IllegalStateException: Failed to download forward message `D9u1a9viNuBYi8ieFFbUG341/umcX1k0PSjoK9VolcXJrvfdDaZmmk+emdfMD0iF`
	at net.mamoe.mirai.internal.MiraiImpl.downloadForwardMessage$suspendImpl(MiraiImpl.kt:732) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.MiraiImpl$downloadForwardMessage$1.invokeSuspend(MiraiImpl.kt) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	... 12 more
Caused by: net.mamoe.mirai.internal.message.ContextualBugReportException: 在 MultiMsg.ApplyDown 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   Decode failure result=192 调试信息: MultiMsgApplyDownRsp#406025650 {
            bytesDownIpV6=[]
            msgResid=D9u1a9viNuBYi8ieFFbUG341/umcX1k0PSjoK9VolcXJrvfdDaZmmk+emdfMD0iF
            result=0x000000C0(192)
            uint32DownIp=[]
            uint32DownPort=[]
            uint32DownV6Port=[]
    }
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.protocol.packet.chat.MultiMsg$ApplyDown.decode(MultiMsg.kt:145) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-jvm-2.13.0-RC2.jar:2.13.0-RC2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.21.jar:1.7.21-release-272(1.7.21)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	... 7 more
```

**Comment by Him188** [comment]
#2343
