### ISSUE TITLE
在安卓系統下出現 java.lang.StackOverflowError

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#2352]
### 问题描述

我將mirai集成進android時出現了以下問題：
`java.lang.StackOverflowError: stack size 1036KB`

### 复现

似乎是啟動console時就立即發生的事情

### mirai-core 版本

2.13.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
java.lang.StackOverflowError: stack size 1036KB
	at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:167)
	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:44)
	at net.mamoe.mirai.utils.MiraiLoggerFactoryImplementationBridge.get_instance(MiraiLogger.kt:269)
	at net.mamoe.mirai.utils.MiraiLoggerFactoryImplementationBridge.getInstance$mirai_core_api(MiraiLogger.kt:273)
	at net.mamoe.mirai.utils.MiraiLoggerFactoryImplementationBridge.create(MiraiLogger.kt:318)
	at net.mamoe.mirai.utils.MiraiLogger$Factory$INSTANCE.create(MiraiLogger.kt)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$ControlledLoggerFactory.create(MiraiConsoleImplementationBridge.kt:113)
	at net.mamoe.mirai.utils.MiraiLoggerFactoryImplementationBridge.create(MiraiLogger.kt:318)
	at net.mamoe.mirai.utils.MiraiLogger$Factory$INSTANCE.create(MiraiLogger.kt)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$ControlledLoggerFactory.create(MiraiConsoleImplementationBridge.kt:113)
	at net.mamoe.mirai.utils.MiraiLoggerFactoryImplementationBridge.create(MiraiLogger.kt:318)
	at net.mamoe.mirai.utils.MiraiLogger$Factory$INSTANCE.create(MiraiLogger.kt)
	at
...
net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:184)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService.startConsole$lambda-3$lambda-2(MiraiCoreConsoleService.kt:255)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService.$r8$lambda$LIRcwkn0y9zIWj7NHkz5tukDgOg(MiraiCoreConsoleService.kt)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at java.lang.Thread.run(Thread.java:818)
```

### 补充信息

推測可能和我的這個實現有關係：
```
class AndroidMiraiConsole(val context: Context) : MiraiConsoleImplementation,
        CoroutineScope by CoroutineScope(CoroutineExceptionHandler { _, throwable ->
            throwable.printStackTrace()
            AndroidMiraiLogger.error(throwable)
        }
        ) {
...
    override fun createLoggerFactory(context: MiraiConsoleImplementation.FrontendLoggingInitContext): MiraiLogger.Factory {
        return MiraiLogger.Factory.INSTANCE
    }
```

其中省略號是大量重複內容，應該是死循環了

**Comment by zhaodice** [comment]
UPDATE:
当我把
```
    override fun createLoggerFactory(context: MiraiConsoleImplementation.FrontendLoggingInitContext): MiraiLogger.Factory {
        return MiraiLogger.Factory.INSTANCE
    }
```
改成
```
    override fun createLoggerFactory(context: MiraiConsoleImplementation.FrontendLoggingInitContext): MiraiLogger.Factory {
        return object : MiraiLogger.Factory {
            override fun create(requester: Class<*>, identity: String?): MiraiLogger {
                return AndroidMiraiLogger
            }
        }
    }
```
后，这个问题解决，新的问题又出现了：

```
java.lang.StackOverflowError: stack size 1036KB
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.getCommandManager(MiraiConsoleImplementationBridge.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.__delegate_0$lambda-0(CommandManager.kt:177)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.$$delegate_0-wrapper(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
```
无限输出`at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)`
然后还是`java.lang.StackOverflowError`，正在调查

**Comment by zhaodice** [comment]
UPDATE:
当我把
```
    override val commandManager: CommandManager
        get() = CommandManager.INSTANCE
```
改成
```
    override val commandManager: CommandManager
        get() = backendAccess.createDefaultCommandManager(coroutineContext)
```
递归错误解除，又产生了新的错误
```
[23:04:22] [ERROR] java.lang.IllegalStateException: Failed to init command net.mamoe.mirai.console.command.BuiltInCommands$AutoLoginCommand@365eb706.
	at net.mamoe.mirai.console.internal.command.CommandManagerImpl.registerCommand(CommandManagerImpl.kt:89)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.BuiltInCommands.registerAll$mirai_console(BuiltInCommands.kt:707)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:327)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService.startConsole$lambda-3$lambda-2(MiraiCoreConsoleService.kt:252)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService.$r8$lambda$LIRcwkn0y9zIWj7NHkz5tukDgOg(MiraiCoreConsoleService.kt)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.util.NoSuchElementException: net.mamoe.mirai.console.internal.command.CommandConfig
	at net.mamoe.mirai.console.MiraiConsoleImplementation$ConsoleDataScope$-CC.$default$get(MiraiConsoleImplementation.kt:287)
	at net.mamoe.mirai.console.internal.data.builtins.ConsoleDataScopeImpl.get(ConsoleDataScopeImpl.kt)
	at net.mamoe.mirai.console.internal.command.CommandManagerImpl.getCommandPrefix(CommandManagerImpl.kt:180)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.getCommandPrefix(CommandManager.kt)
	at net.mamoe.mirai.console.internal.command.CommandReflector$Companion$generateUsage$1.invoke(CommandReflector.kt:188)
	at net.mamoe.mirai.console.internal.command.CommandReflector$Companion$generateUsage$1.invoke(CommandReflector.kt:181)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3499)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3516)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3515)
	at net.mamoe.mirai.console.internal.command.CommandReflector$Companion.generateUsage(CommandReflector.kt:181)
	at net.mamoe.mirai.console.internal.command.CommandReflector.generateUsage(CommandReflector.kt:172)
	at net.mamoe.mirai.console.command.CompositeCommand$usage$2.invoke(CompositeCommand.kt:111)
	at net.mamoe.mirai.console.command.CompositeCommand$usage$2.invoke(CompositeCommand.kt:109)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.console.command.CompositeCommand.getUsage(CompositeCommand.kt:109)
	at net.mamoe.mirai.console.internal.command.CommandManagerImpl.registerCommand(CommandManagerImpl.kt:87)
	... 8 more
```

继续调查

**Comment by zhaodice** [comment]
问题原因是,好像是usage加载出问题了？
```
java.util.NoSuchElementException: net.mamoe.mirai.console.internal.command.CommandConfig
	at net.mamoe.mirai.console.MiraiConsoleImplementation$ConsoleDataScope$-CC.$default$get(MiraiConsoleImplementation.kt:287)
	at net.mamoe.mirai.console.internal.data.builtins.ConsoleDataScopeImpl.get(ConsoleDataScopeImpl.kt)
	at net.mamoe.mirai.console.internal.command.CommandManagerImpl.getCommandPrefix(CommandManagerImpl.kt:180)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.getCommandPrefix(CommandManager.kt)
	at net.mamoe.mirai.console.internal.command.CommandReflector$Companion$generateUsage$1.invoke(CommandReflector.kt:188)
	at net.mamoe.mirai.console.internal.command.CommandReflector$Companion$generateUsage$1.invoke(CommandReflector.kt:181)
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3499)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:3516)
	at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:3515)
	at net.mamoe.mirai.console.internal.command.CommandReflector$Companion.generateUsage(CommandReflector.kt:181)
	at net.mamoe.mirai.console.internal.command.CommandReflector.generateUsage(CommandReflector.kt:172)
	at net.mamoe.mirai.console.command.CompositeCommand$usage$2.invoke(CompositeCommand.kt:111)
	at net.mamoe.mirai.console.command.CompositeCommand$usage$2.invoke(CompositeCommand.kt:109)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.console.command.CompositeCommand.getUsage(CompositeCommand.kt:109)
	at net.mamoe.mirai.console.internal.command.CommandManagerImpl.registerCommand(CommandManagerImpl.kt:87)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(CommandManager.kt)
	at net.mamoe.mirai.console.command.BuiltInCommands.registerAll$mirai_console(BuiltInCommands.kt:707)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:327)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService.startConsole$lambda-3$lambda-2(MiraiCoreConsoleService.kt:252)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService.$r8$lambda$LIRcwkn0y9zIWj7NHkz5tukDgOg(MiraiCoreConsoleService.kt)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by sandtechnology** [comment]
这边其实建议可以参考 https://github.com/mzdluo123/MiraiAndroid/ 看看

**Comment by zhaodice** [comment]
> 这边其实建议可以参考 https://github.com/mzdluo123/MiraiAndroid/ 看看

它好久没更新了，我这次用的是很新的console，比如CommandManager的使用，它已经过时了
MiraiAndroid用的是
```
override val commandManager: CommandManager
        get() = CommandManagerImpl(coroutineContext)
```
而最新版的console已经没有CommandManagerImpl了（大概

**Comment by sandtechnology** [comment]
我的意思是可以参考它的加载方式啦（
Android下应该是比较痛苦的 加油（

**Comment by zhaodice** [comment]
> 我的意思是可以参考它的加载方式啦（ Android下应该是比较痛苦的 加油（

恩多谢，现在主要是卡在这里了
```
package net.mamoe.mirai.console.internal.command
...
override val commandPrefix: String get() = DataScope.get<CommandConfig>().commandPrefix
```
不知道为什么，现在只要调用commandPrefix就会报错
`java.util.NoSuchElementException: net.mamoe.mirai.console.internal.command.CommandConfig`
暂时还没找到原因
