### ISSUE TITLE
2.13.0无法使用ANDROID_PHONE协议登录

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [mamoe/mirai#2360]
### 问题描述

如图
![NQA)_AVX($@8NCJZDL3HNAW](https://user-images.githubusercontent.com/86163024/203731271-f97ec084-f198-4b8b-bdcb-7c1a8e5521d5.png)

### 复现

autologin和手动登录均无法登录

### mirai-core 版本

2.13.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2022-11-24 16:17:38 I/Bot.2522860289: Loaded account secrets from local cache.
2022-11-24 16:17:38 I/Bot.2522860289: Saved account secrets to local cache for fast login.
2022-11-24 16:17:38 I/Bot.2522860289: Bot cancelled: Bot closed
Login failed: Received packet returnCode = -10003, which may mean session expired.
2022-11-24 16:17:38 E/console: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
        at net.mamoe.mirai.internal.network.components.PacketCodecException.<init>(PacketCodec.kt:72)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseSsoFrame(PacketCodec.kt:178)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:127)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.decodePacket(CommonNetworkHandler.kt:148)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$decodePacket(CommonNetworkHandler.kt:102)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
        Suppressed: net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
                ... 14 more
        Caused by: [CIRCULAR REFERENCE: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.]
```

**Comment by cssxsh** [comment]
> which may mean session expired.

请手动删除 `bots/.../cache` 下的 `session.bin` 等文件

https://github.com/mamoe/mirai/issues/2346

**Comment by YuYue-Amatsuki** [comment]
> > which may mean session expired.
> 
> 请手动删除 `bots/.../cache` 下的 `session.bin` 等文件
> 
> #2346

感谢，已解决
