### ISSUE TITLE
安卓下插件无法正常重载onEnable ，只因父类实现了onEnable并设为final

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#2377]
### 问题描述

安卓平台加载Dex插件时，出现错误，Enable 哪怕是空函数也是这样

### 复现

仿照MiraiAndroid的方式加载dex插件，出现该情况，其中旧版（2.11）正常

### mirai-core 版本

2.13.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-console,mirai-core,mirai-terminal 皆为2.13.0

### 系统日志

```text
net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load service zhao.dice.cqhttp.MiraiPluginLoader.
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(SourceFile:2)
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServices(SourceFile)
	at df.h.invoke(SourceFile)
	at kotlin.sequences.TransformingSequence$iterator$1.next(SourceFile)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(SourceFile)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(SourceFile)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(SourceFile)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(SourceFile)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(SourceFile)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(SourceFile)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(SourceFile)
	at kotlin.sequences.SequencesKt___SequencesKt.toSet(SourceFile)
	at df.f.extractPlugins(SourceFile:6)
	at net.mamoe.mirai.console.plugin.loader.AbstractFilePluginLoader.listPlugins(SourceFile)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(SourceFile)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(SourceFile)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(SourceFile)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(SourceFile:2)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(SourceFile)
	at com.koushikdutta.async.b.run(SourceFile:10)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.LinkageError: Method void zhao.dice.cqhttp.MiraiPluginLoader.onEnable() overrides final method in class Lnet/mamoe/mirai/console/internal/plugin/JvmPluginInternal; (declaration of 'zhao.dice.cqhttp.MiraiPluginLoader' appears in /data/data/org.mirai.zhao.dice/cache/MiraiSpace/plugins/AstralCore.exe)
	at dalvik.system.DexFile.defineClassNative(Native Method)
	at dalvik.system.DexFile.defineClass(DexFile.java:226)
	at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
	at dalvik.system.DexPathList.findClass(DexPathList.java:321)
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
	at df.e.a(SourceFile)
	at df.e.findClass(SourceFile)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:309)
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(SourceFile)
	... 20 more

PS:混淆部分与mirai无关
```

### 补充信息

Android 5.1,其他版本尚未测试

**非常奇怪的是，编译目标为Debug就正常，而编译目标为release就异常（与混淆无关，已排查）**

**Comment by zhaodice** [comment]
Plugin code:
```
package zhao.dice.cqhttp

import net.mamoe.mirai.console.plugin.jvm.JvmPluginDescription
import net.mamoe.mirai.console.plugin.jvm.KotlinPlugin
import org.mirai.zhao.pluginLib.PluginUtil


/*
* 当前使用的框架：
* https://github.com/mamoe/mirai
* 框架候选：
* https://github.com/YuQWorks/Mirai-Rain
* https://github.com/YuQWorks/YuQ-Mirai
*
* */

object MiraiPluginLoader : KotlinPlugin(
        JvmPluginDescription(
                id = "zhao.dice",
                version = "1.0.0",
        ) {
            name("ZhaoDice")
            author("赵怡然")
        }
){
    private var enabled=false
    override fun onEnable() {
        if(enabled)
            return
        //PluginUtil.register(this) 哪怕注释了也无法改变错误
        enabled=true
    }
}

```

**Comment by zhaodice** [comment]
项目较为复杂，需要其他信息可以补充
(先把issue贴在这里，如果我先找到解决方法会继续更新就当是案例了)

**Comment by zhaodice** [comment]
https://www.jianshu.com/p/107cdc197b70

发现了一个类似的问题，可能是因为super类含有同样的、已经实现了的、final的onEnable方法，导致插件无法正常override?

**Comment by zhaodice** [comment]
![Screenshot_20221204_122010](https://user-images.githubusercontent.com/63996691/205474299-0fd63a0e-fb42-4620-9444-6d53c9f5e690.png)

从反编译上定位问题，本插件继承了KotlinPlugin，KotlinPlugin继承了AbstractJvmPlugin，AbstractJvmPlugin继承了JvmPluginInternal
```
    @Override // net.mamoe.mirai.console.plugin.jvm.JvmPlugin
    public final /* synthetic */ void onEnable() {
```
其中，final方法【无法】被重写，故而出错

**Comment by zhaodice** [comment]
草，可能是Android编译器的问题? 我反编译原始jar，就没看见这个final方法

**Comment by zhaodice** [comment]
好了，经过定位是desuger的问题，它不知道发了什么羊癫疯给里面擅自插入了final的实现方法导致无法正常重写,如果解决了我会贴在这里

**Comment by zhaodice** [comment]
似乎没有很好的办法，唯一能想到的就是反编译，移除多余的final函数，如果有的话可以在这里讨论

**Comment by zhaodice** [comment]
Ref: https://issuetracker.google.com/issues/241154844

**Comment by Him188** [comment]
debug 正常点，release不正常，那大概率就是R8之类优化问题

**Comment by zhaodice** [comment]
> debug 正常点，release不正常，那大概率就是R8之类优化问题

没错，我编译目标为21的时候，它就会产生final void onEnable() 
编译目标为24时（安卓8）,就不会产生final void onEnable() 

而且, 我做了一个实验，当我在项目源代码里【显式】调用KotlinPlugin并实现onEnable的时候，JvmPluginInternal会产生void onEnable

当我【隐式】调用KotlinPlugin的时候（也就是通过调用dex插件），R8会加final关键字，JvmPluginInternal会产生final void onEnable，导致插件无法重写onEnable

（一般情况下肯定是隐式的，我不可能把插件和框架编译成一体吧XD）

**Comment by zhaodice** [comment]
以前遇到过不少kotlin量子问题，即我必须写一段垃圾代码，【象征性地】调用一下目标类，才能保证不会出错，否则如果只是单纯通过反射调用, 就各种玄学错误，说找不到零参构造函数啊balabala什么的, 

(kotlin对反射，相对于java似乎不是特别的友好反正)

**Comment by Him188** [comment]
我觉得你关掉 R8 优化就行了, 这不是 mirai 问题
