### ISSUE TITLE
启动报错 缺少Okhttp

### ISSUE THREAD

**Issue by SuYueQiuLiang** [mamoe/mirai#2380]
### 问题描述

启动的时候找不到Okhttp类

### 复现

使用mirai-core 2.13.0开发，编译启动后出现

### mirai-core 版本

2.13.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
Exception in thread "main" java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1393)
        at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:270)
        at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:18)
        at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357)
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348)
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39)
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:116)
        at org.suyue.bot.Config.loadConfig(Config.java:40)
        at org.suyue.bot.Main.main(Main.java:27)
Caused by: java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1393)
        at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:270)
        at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:18)
        at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357)
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348)
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39)
        at net.mamoe.mirai.internal.message.MessageSerializersImpl.getSerializersModule(MessageSerializersImpl.kt:65)
        at net.mamoe.mirai.internal.message.MessageSerializersImpl.registerSerializers(MessageSerializersImpl.kt:76)
        at net.mamoe.mirai.message.MessageSerializers$INSTANCE.registerSerializers(MessageSerializers.kt)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade.<clinit>(MessageProtocolFacade.kt:165)
        at net.mamoe.mirai.internal.MiraiImplKt._MiraiImpl_static_init(MiraiImpl.kt:25)
        at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt:87)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
        ... 10 more
Caused by: java.lang.NoClassDefFoundError: net/mamoe/mirai/internal/deps/io/ktor/client/engine/okhttp/OkHttp
        at net.mamoe.mirai.internal.MiraiImplKt.createDefaultHttpClient(MiraiImpl.kt:29)
        at net.mamoe.mirai.internal.MiraiImpl.<init>(MiraiImpl.kt:97)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
        ... 29 more
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttp
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
        ... 37 more
```

**Comment by MrXiaoM** [comment]
2.13.1 修复了这个问题

**Comment by Him188** [comment]
用2.13.1
