### ISSUE TITLE
发送图片时`java.lang.NoSuchMethodError: 'net.mamoe.mirai.internal.deps.io.ktor.utils.io.core.Input net.mamoe.mirai.utils.ExternalResource.input()'`

### ISSUE THREAD

**Issue by 4o4E** [mamoe/mirai#2381]
### 问题描述

发送图片时`java.lang.NoSuchMethodError: 'net.mamoe.mirai.internal.deps.io.ktor.utils.io.core.Input net.mamoe.mirai.utils.ExternalResource.input()'`

### 复现

发送图片

### mirai-core 版本

2.13.1

### bot-protocol

IPAD

### 系统日志

```text
java.lang.NoSuchMethodError: 'net.mamoe.mirai.internal.deps.io.ktor.utils.io.core.Input net.mamoe.mirai.utils.ExternalResource.input()'
	at net.mamoe.mirai.internal.message.image.ImageDecoderKt.calculateImageInfo(ImageDecoder.kt:152) ~[mirai-core-jvm-2.13.1.jar:2.13.1]
	at net.mamoe.mirai.internal.contact.CommonGroupImpl$uploadImage$lambda-16$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23) ~[mirai-core-jvm-2.13.1.jar:2.13.1]
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.20.jar:1.7.20-release-201(1.7.20)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
```

**Comment by Him188** [comment]
好像是忘了为 mirai-core-api 设置 relocate
