### ISSUE TITLE
FriendAddEvent中向新好友发送消息会抛出异常

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2390]
### 问题描述

如题所述

### 复现

在FriendAddEvent事件监听中向该新好友发送一条打招呼消息，例如：
![image](https://user-images.githubusercontent.com/76583155/207600564-4f9ce522-8adf-4d98-ade7-132bb0142f63.png)

### mirai-core 版本

2.13.0-M1

### bot-protocol

ANDROID_PAD

### 系统日志

```text
2022-12-14 20:49:36 E/Bot.2860688653: java.lang.IllegalStateException: Exception while broadcasting event 'FriendAddEvent'
java.lang.IllegalStateException: Exception while broadcasting event 'FriendAddEvent'
	at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcast$suspendImpl(EventDispatcher.kt:104)
	at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcast$1.invokeSuspend(EventDispatcher.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callFunction(JvmMethodListenersInternal.kt:91)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callFunction(JvmMethodListenersInternal.kt:1)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callFunction$1.invokeSuspend(JvmMethodListenersInternal.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	... 8 more
Caused by: java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=16, errorCode=0, errorMessage=发送失败，请先添加对方为好友)
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:150)
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.access$sendSinglePacket(GeneralMessageSenderProtocol.kt:50)
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender$sendSinglePacket$1.invokeSuspend(GeneralMessageSenderProtocol.kt)
	... 9 more
```

**Comment by Him188** [comment]
看起来是mirai处理太快了，服务器事件发早了，自己加个delay吧

**Comment by Karlatemp** [comment]
可能是因为 mirai 是「收到即处理」，是立刻处理的，而服务器那边还没完成相关的操作，我个人的建议是自行加个 delay 延迟几秒钟

**Comment by MrY-Cat** [comment]
确实是加个delay解决一下比较好。不过也许可以在该事件进行一些注释，来提醒事件发生时服务器不会立即完成相关操作。
