### ISSUE TITLE
版本过低

### ISSUE THREAD

**Issue by cyear** [mamoe/mirai#2392]
昨天正常使用，今天提示版本过低

2022-12-15 10:40:45 I/Bot.3384277286: 请在手机端使用请求码8026完成验证，完成后再次发送请求得到ticket
2022-12-15 10:40:49 I/Bot.3384277286: Bot cancelled: Bot closed
2022-12-15 10:40:49 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3384277286), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载 页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3384277286), code=235, title=温馨 提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by liliang8858** [comment]
同样问题
