### ISSUE TITLE
再次出现qq版本过低

### ISSUE THREAD

**Issue by ChengTu-Lazy** [mamoe/mirai#2395]
### 问题描述

早上还在正常使用，被正常的请求一次之后就出现了qq断连，再次登录之后就显示qq版本过低，已使用` ./mcl -u `更新，再次登录依然显示qq版本过低
![image](https://user-images.githubusercontent.com/61143962/208271262-81426118-71d7-4cea-a9ae-9a6ccf4dcb08.png)

### 复现

./mcl
登录qq
输入验证码

### mirai-core 版本

2.8.2

### bot-protocol

ANDROID_PHONE

### 其他组件版本

![image](https://user-images.githubusercontent.com/61143962/208271237-1306bcf6-de39-463a-a266-9faedae9a69e.png)

### 系统日志

```text
2022-12-18 01:10:26 V/Bot.2721190182: Event: BotOfflineEvent.Dropped(bot=Bot(2721190182), cause=HeartbeatFailedException: 2721190182.AliveHeartbeat, recoverable=true, cause=PacketTimeoutException(message=2721190182.AliveHeartbeat Scheduler: Timeout receiving action response, cause=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms), reconnect=true)
2022-12-18 01:10:26 W/Bot.2721190182: Connection lost, reconnecting... (HeartbeatFailedException: 2721190182.AliveHeartbeat, recoverable=true, cause=PacketTimeoutException(message=2721190182.AliveHeartbeat Scheduler: Timeout receiving action response, cause=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms))
2022-12-18 01:10:46 I/Bot.2721190182: Bot cancelled: Bot closed
```

### 网络日志

```text
[0m2022-12-18 00:08:57 V/: Send: LongConn.OffPicUp(LongConn.OffPicUp)[0m
[0m2022-12-18 00:08:58 V/: Recv: LongConn.OffPicUp[0m
[0m2022-12-18 00:08:58 V/: [Highway] Uploading private image to 42.81.193.229:443, size=96.2 KiB[0m
[0m2022-12-18 00:08:58 V/: [Highway] Uploading private image: succeed at 232 KiB/s[0m
[0m2022-12-18 00:08:58 V/: Send: ImgStore.GroupPicUp(ImgStore.GroupPicUp)[0m
[0m2022-12-18 00:08:58 V/: Recv: ImgStore.GroupPicUp[0m
[0m2022-12-18 00:08:58 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-12-18 00:08:59 V/: Recv: MessageSvc.PbSendMsg[0m
[0m2022-12-18 00:21:32 V/: Send: LongConn.OffPicUp(LongConn.OffPicUp)[0m
[0m2022-12-18 00:21:33 V/: Recv: LongConn.OffPicUp[0m
[0m2022-12-18 00:21:33 V/: [Highway] Uploading private image to 157.148.42.169:80, size=96.3 KiB[0m
[0m2022-12-18 00:21:34 V/: [Highway] Uploading private image: succeed at 97 KiB/s[0m
[0m2022-12-18 00:21:34 V/: Send: ImgStore.GroupPicUp(ImgStore.GroupPicUp)[0m
[0m2022-12-18 00:21:34 V/: Recv: ImgStore.GroupPicUp[0m
[0m2022-12-18 00:21:34 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-12-18 00:21:34 V/: Recv: MessageSvc.PbSendMsg[0m
[0m2022-12-18 00:33:24 V/: Send: LongConn.OffPicUp(LongConn.OffPicUp)[0m
[0m2022-12-18 00:33:24 V/: Recv: LongConn.OffPicUp[0m
[0m2022-12-18 00:33:24 V/: [Highway] Uploading private image to 183.2.144.17:8080, size=96.06 KiB[0m
[0m2022-12-18 00:33:25 V/: [Highway] Uploading private image: succeed at 96 KiB/s[0m
[0m2022-12-18 00:33:25 V/: Send: ImgStore.GroupPicUp(ImgStore.GroupPicUp)[0m
[0m2022-12-18 00:33:25 V/: Recv: ImgStore.GroupPicUp[0m
[0m2022-12-18 00:33:25 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-12-18 00:33:26 V/: Recv: MessageSvc.PbSendMsg[0m
[0m2022-12-18 01:03:45 V/: Send: LongConn.OffPicUp(LongConn.OffPicUp)[0m
[0m2022-12-18 01:03:46 V/: Recv: LongConn.OffPicUp[0m
[0m2022-12-18 01:03:46 V/: [Highway] Uploading private image to 157.148.42.169:80, size=95.86 KiB[0m
[0m2022-12-18 01:03:46 V/: [Highway] Uploading private image: succeed at 101 KiB/s[0m
[0m2022-12-18 01:03:46 V/: Send: ImgStore.GroupPicUp(ImgStore.GroupPicUp)[0m
[0m2022-12-18 01:03:47 V/: Recv: ImgStore.GroupPicUp[0m
[0m2022-12-18 01:03:47 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2022-12-18 01:03:47 V/: Recv: MessageSvc.PbSendMsg[0m
[91m2022-12-18 01:10:26 W/: Exception in resumeConnection.
HeartbeatFailedException: 2721190182.AliveHeartbeat, recoverable=true, cause=PacketTimeoutException(message=2721190182.AliveHeartbeat Scheduler: Timeout receiving action response, cause=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateOK$heartbeatJobs$1$1.invoke(CommonNetworkHandler.kt:346)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateOK$heartbeatJobs$1$1.invoke(CommonNetworkHandler.kt:346)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:329)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateOK$heartbeatJobs$1.invoke(CommonNetworkHandler.kt:408)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateOK$heartbeatJobs$1.invoke(CommonNetworkHandler.kt:345)
	at net.mamoe.mirai.internal.network.components.TimeBasedHeartbeatSchedulerImpl$launchHeartbeatJobAsync$1.invokeSuspend(HeartbeatScheduler.kt:131)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: PacketTimeoutException(message=2721190182.AliveHeartbeat Scheduler: Timeout receiving action response, cause=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms)
	at net.mamoe.mirai.internal.network.components.TimeBasedHeartbeatSchedulerImpl$launchHeartbeatJobAsync$1.invokeSuspend(HeartbeatScheduler.kt:133)
	... 12 more
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.base/java.lang.Thread.run(Unknown Source)
[0m
[0m2022-12-18 01:10:26 V/: Loading server list from cache.[0m
[0m2022-12-18 01:10:26 V/: Server list: 114.222.112.90:14000, 120.232.22.229:443, 117.62.243.225:14000, 123.151.54.57:14000, 157.148.57.39:80, msfwifi.3g.qq.com:8080, 123.151.54.180:80, 119.147.190.142:8080.[0m
[92m2022-12-18 01:10:26 I/: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2022-12-18 01:10:26 I/: Successfully fetched ecdh public key from server.[0m
[0m2022-12-18 01:10:26 V/: Send: wtlogin.exchange_emp(10:fast-login)[0m
[0m2022-12-18 01:10:31 V/: Send: wtlogin.exchange_emp(10:fast-login)[0m
[0m2022-12-18 01:10:36 V/: Send: wtlogin.login(9:password-login)[0m
[0m2022-12-18 01:10:41 V/: Send: wtlogin.login(9:password-login)[0m
[91m2022-12-18 01:10:46 W/: Exception in resumeConnection.
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.base/java.lang.Thread.run(Unknown Source)
[0m
[91m2022-12-18 01:10:46 W/: Network selector received exception, closing bot. (kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms)[0m
[91m2022-12-18 01:10:46 W/: Exception in resumeConnection.
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.base/java.lang.Thread.run(Unknown Source)
	Suppressed: HeartbeatFailedException: 2721190182.AliveHeartbeat, recoverable=true, cause=PacketTimeoutException(message=2721190182.AliveHeartbeat Scheduler: Timeout receiving action response, cause=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateOK$heartbeatJobs$1$1.invoke(CommonNetworkHandler.kt:346)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateOK$heartbeatJobs$1$1.invoke(CommonNetworkHandler.kt:346)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:329)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateOK$heartbeatJobs$1.invoke(CommonNetworkHandler.kt:408)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateOK$heartbeatJobs$1.invoke(CommonNetworkHandler.kt:345)
		at net.mamoe.mirai.internal.network.components.TimeBasedHeartbeatSchedulerImpl$launchHeartbeatJobAsync$1.invokeSuspend(HeartbeatScheduler.kt:131)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Caused by: PacketTimeoutException(message=2721190182.AliveHeartbeat Scheduler: Timeout receiving action response, cause=kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms)
		at net.mamoe.mirai.internal.network.components.TimeBasedHeartbeatSchedulerImpl$launchHeartbeatJobAsync$1.invokeSuspend(HeartbeatScheduler.kt:133)
		... 12 more
	Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
		at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
		at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
		at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
		at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
		at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
		at java.base/java.lang.Thread.run(Unknown Source)
[0m
[91m2022-12-18 01:10:46 W/: Network selector received exception, closing bot. (kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms)[0m
[0m2022-12-18 08:10:32 V/Net 2721190182: Loading server list from cache.[0m
[0m2022-12-18 08:10:32 V/Net 2721190182: Server list: 114.222.112.90:14000, 120.232.22.229:443, 117.62.243.225:14000, 123.151.54.57:14000, 157.148.57.39:80, msfwifi.3g.qq.com:8080, 123.151.54.180:80, 119.147.190.142:8080.[0m
[92m2022-12-18 08:10:32 I/Net 2721190182: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2022-12-18 08:10:33 I/Net 2721190182: Successfully fetched ecdh public key from server.[0m
[0m2022-12-18 08:10:33 V/Net 2721190182: Send: wtlogin.login(9:password-login)[0m
[0m2022-12-18 08:10:33 V/Net 2721190182: Recv: wtlogin.login[0m
[91m2022-12-18 08:16:10 W/Net 2721190182: Exception in resumeConnection.
java.io.IOError: java.io.IOException: Input/output error
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:170)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
	at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:923)
	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:956)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:651)
	at net.mamoe.mirai.console.terminal.JLineInputDaemon.run(JLineInputDaemon.kt:78)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Input/output error
	at java.base/java.io.FileInputStream.read0(Native Method)
	at java.base/java.io.FileInputStream.read(Unknown Source)
	at org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73)
	at org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62)
	at org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168)
	at org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57)
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:160)
	... 7 more
[0m
[91m2022-12-18 08:16:10 W/Net 2721190182: Network selector received exception, closing bot. (java.io.IOError: java.io.IOException: Input/output error)[0m
[0m2022-12-18 08:16:59 V/Net 2721190182: Loading server list from cache.[0m
[0m2022-12-18 08:16:59 V/Net 2721190182: Server list: 114.222.112.90:14000, 120.232.22.229:443, 117.62.243.225:14000, 123.151.54.57:14000, 157.148.57.39:80, msfwifi.3g.qq.com:8080, 123.151.54.180:80, 119.147.190.142:8080.[0m
[92m2022-12-18 08:16:59 I/Net 2721190182: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2022-12-18 08:16:59 I/Net 2721190182: Successfully fetched ecdh public key from server.[0m
[0m2022-12-18 08:16:59 V/Net 2721190182: Send: wtlogin.login(9:password-login)[0m
[0m2022-12-18 08:17:00 V/Net 2721190182: Recv: wtlogin.login[0m
[0m2022-12-18 08:17:32 V/Net 2721190182: Send: wtlogin.login(2:submit-slider)[0m
[0m2022-12-18 08:17:32 V/Net 2721190182: Recv: wtlogin.login[0m
[91m2022-12-18 08:17:32 W/Net 2721190182: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(2721190182), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=
```

### 补充信息

无

**Comment by cssxsh** [comment]
你需要删掉 `bot/.../` 下的全部文件，因为已经被拉黑了

**Comment by ChengTu-Lazy** [comment]
> 你需要删掉 `bot/.../` 下的全部文件，因为已经被拉黑了

删掉 `bot/.../` 下的全部文件后重新登陆问题就解决了，感谢回答
