### ISSUE TITLE
支持群内回复消息

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#24]
```
Mirai 15:38:12 : ByteReadPacket 群消息=19 00 2D 01 00 2A EA 02 27 08 9F 01 10 A2 FF 8C F0 03 18 D0 C4 D7 EF 05 20 01 2A 12 0A 10 0A 0E E5 BB BA E8 AE AE 5B E5 9B BE E7 89 87 5D 30 00 01 00 1D 01 00 0A 40 48 69 6D 31 38 38 6D 6F 65 06 00 0D 00 01 00 00 00 0A 00 3E 03 3F A2 00 00 01 00 04 01 00 01 20 01 00 1D 01 00 0A 40 48 69 6D 31 38 38 6D 6F 65 06 00 0D 00 01 00 00 00 0A 00 3E 03 3F A2 00 00 01 00 1F 01 00 1C 20 E4 BD A0 E8 BF 99 E6 98 AF E4 BB 80 E4 B9 88 E7 A5 9E E7 A7 98 E7 89 88 E6 9C AC 19 00 3A 01 00 37 AA 02 34 50 00 60 00 68 00 88 01 00 9A 01 28 08 09 78 00 C8 01 00 F0 01 00 F8 01 00 90 02 00 C8 02 00 98 03 00 A0 03 00 B0 03 00 C0 03 00 D0 03 00 E8 03 00 90 04 00 0E 00 0E 01 00 04 00 00 00 00 07 00 04 00 00 00 01 12 00 21 05 00 04 00 00 00 01 08 00 04 00 00 00 01 01 00 0C E5 8D 83 E9 87 8C E5 86 B0 E5 B0 81 03 00 01 01
java.lang.IllegalStateException: Count not readTLVMap: duplicated key 0x00000001. map={1=[B@76e16d4d}, duplicating value=[B@39e5e329, remaining=01 00 1D 01 00 0A 40 48 69 6D 31 38 38 6D 6F 65 06 00 0D 00 01 00 00 00 0A 00 3E 03 3F A2 00 00 01 00 1F 01 00 1C 20 E4 BD A0 E8 BF 99 E6 98 AF E4 BB 80 E4 B9 88 E7 A5 9E E7 A7 98 E7 89 88 E6 9C AC 19 00 3A 01 00 37 AA 02 34 50 00 60 00 68 00 88 01 00 9A 01 28 08 09 78 00 C8 01 00 F0 01 00 F8 01 00 90 02 00 C8 02 00 98 03 00 A0 03 00 B0 03 00 C0 03 00 D0 03 00 E8 03 00 90 04 00 0E 00 0E 01 00 04 00 00 00 00 07 00 04 00 00 00 01 12 00 21 05 00 04 00 00 00 01 08 00 04 00 00 00 01 01 00 0C E5 8D 83 E9 87 8C E5 86 B0 E5 B0 81 03 00 01 01
	at net.mamoe.mirai.utils.io.InputUtilsKt.readTLVMap(InputUtils.kt:79)
	at net.mamoe.mirai.utils.io.InputUtilsKt.readTLVMap$default(InputUtils.kt:59)
	at net.mamoe.mirai.network.protocol.tim.packet.event.GroupMessageEventParserAndHandler.parse(MessageEvent.kt:148)
	at net.mamoe.mirai.network.protocol.tim.packet.event.EventPacketFactory.decode-MgswzbQ(EventPacketFactory.kt:51)
	at net.mamoe.mirai.network.protocol.tim.packet.event.EventPacketFactory$decode$1.invokeSuspend(EventPacketFactory.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterCompletionInternal(Scopes.kt:32)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:310)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:276)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:807)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:787)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Mirai 15:38:22 : ByteReadPacket 群消息=01 00 34 01 00 31 E6 88 91 E6 80 8E E4 B9 88 E6 B2 A1 E8 A7 81 E8 BF 87 E9 82 A3 E4 B8 AA 20 6F 70 65 6E 20 61 73 20 62 69 6E 61 72 79 20 E7 9A 84 E9 80 89 E9 A1 B9 19 00 3A 01 00 37 AA 02 34 50 00 60 00 68 00 88 01 00 9A 01 28 08 09 78 00 C8 01 00 F0 01 00 F8 01 00 90 02 00 C8 02 00 98 03 00 A0 03 00 B0 03 00 C0 03 00 D0 03 00 E8 03 00 90 04 00 0E 00 0E 01 00 04 00 00 00 00 07 00 04 00 00 00 01 12 00 21 05 00 04 00 00 00 01 08 00 04 00 00 00 01 01 00 0C E5 8D 83 E9 87 8C E5 86 B0 E5 B0 81 03 00 01 01
Mirai 15:38:22 : Packet received: GroupMessage(group=655057127, senderName=千里冰封, sender=951394653, permission=MEMBER, message=我怎么没见过那个 open as binary 的选项)
```

**Comment by Him188** [comment]
已支持
