### ISSUE TITLE
上传长消息时连接服务器失败

### ISSUE THREAD

**Issue by jqqqqqqqqqq** [mamoe/mirai#240]
Core版本 V0.37.4
Console版本 V0.4.9
HTTPAPI 版本 V1.6.3
其他插件： console-addition V0.2.3

场景：

QQ1：消息 "1"

Bot：消息"2" -> 消息 "1"     (-> 表示quote)

QQ1： 消息 "3" -> 消息 "2"

Bot：消息 "4" -> 消息 "3"

消息 "4" 在 quote 消息 "3" 的时候第一次发送出发下列error并发送失败，第二次则能正常发出（指对于被quote的消息，第二次试图quote能正常发送，被quote消息本身有quote 来自bot的消息）
Bot并未显示掉线，且其他功能正常，不quote直接发正常

```
 02:20:37 [ERROR] [MiraiAPIHTTP] java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at net.mamoe.mirai.qqandroid.utils.PlatformSocket$connect$3.invokeSuspend(PlatformSocket.kt:86)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

与此同时虽然每次发的消息只有一位数字，即长度为1，log中出现：
```
 02:19:21 [INFO] [NETWORK] Send done: MultiMsg.ApplyUp
 02:19:21 [INFO] [NETWORK] Packet: MultiMsg.ApplyUp.Response.RequireUpload(proto=net.mamoe.mirai.qqandroid.network.protocol.data.proto.MultiMsg$MultiMsgApplyUpRsp@77b7ff98)
 02:19:21 [INFO] [NETWORK] [Highway] Uploading group long message#22947 to 203.205.236.76:8080: size=595
 02:19:37 [INFO] [NETWORK] Send done: Heartbeat.Alive
 02:19:37 [INFO] [NETWORK] Packet: Heartbeat.Alive.Response
 02:19:43 [INFO] [NETWORK] Send done: MultiMsg.ApplyUp
 02:19:43 [INFO] [NETWORK] Packet: MultiMsg.ApplyUp.Response.RequireUpload(proto=net.mamoe.mirai.qqandroid.network.protocol.data.proto.MultiMsg$MultiMsgApplyUpRsp@507acf6b)
 02:19:43 [INFO] [NETWORK] [Highway] Uploading group long message#22949 to 203.205.237.170:8080: size=597
 02:19:44 [INFO] [NETWORK] [Highway] Uploading group long message#22949: succeed

```

不确定是否有关

**Comment by jqqqqqqqqqq** [comment]
消息正文只有一个字符 ，quote消息内容也只有一个字符，不确定是否属于长消息

**Comment by Chenwe-i-lin** [comment]
`Quote` 包极其巨大, 可能是因为这个原因.

**Comment by Him188** [comment]
应该是服务器无响应. 目前没有写重试

**Comment by jqqqqqqqqqq** [comment]
确实是网络不稳定的缘故，复现无数次之后出现了一次直接发出去的情况
