### ISSUE TITLE
找不到服务类net.mamoe.mirai.event.InternalGlobalEventChannelProvider的实现

### ISSUE THREAD

**Issue by WutzuBert** [mamoe/mirai#2411]
### 问题描述

我尝试在一个BungeeCord服务端插件中使用Mirai-core作为依赖
在登录Bot时抛出以下异常
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
    at net.mamoe.mirai.utils.ActualsKt.loadService(Actuals.kt:40)
    at net.mamoe.mirai.utils.ActualsKt.loadService$default(Actuals.kt:35)
    at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:31)
    at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:30)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:30)
    at net.mamoe.mirai.event.GlobalEventChannel.context(GlobalEventChannel.kt:47)
    at net.mamoe.mirai.event.FilterEventChannel.context(EventChannel.kt:766)
    at net.mamoe.mirai.event.FilterEventChannel.context(EventChannel.kt:766)
    at net.mamoe.mirai.event.EventChannel.parentScope(EventChannel.kt:341)
    at net.mamoe.mirai.internal.network.components.BotOfflineEventMonitorImpl.attachJob(BotOfflineEventMonitor.kt:48)
    at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:180)
    at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:176)
    at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
    at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:176)
    at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:264)
    at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:276)
    at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:269)
    at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:229)
    at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:200)
    at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:58)
    at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:47)
    at net.mamoe.mirai.internal.QQAndroidBot.getComponents(QQAndroidBot.kt:174)
    at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:135)
    at net.mamoe.mirai.Bot$login$1.invoke(Bot.kt:65535)
    at net.mamoe.mirai.Bot$login$1.invoke(Bot.kt)
    at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
    at me.him188.kotlin.jvm.blocking.bridge.internal.RunSuspendKt.$runSuspend$(RunSuspend.kt:18)
    at net.mamoe.mirai.Bot.login(Bot.kt)
问题代码行内容：bot.login

### 复现

bot.login();
GlobalEventChannel.INSTANCE.filter(ev -> ev instanceof GroupMessageEvent && ((GroupMessageEvent) ev).getSubject().getId() == groupID).subscribeAlways(GroupMessageEvent.class, event -> {事件处理器内容}

### mirai-core 版本

2.12.3

### bot-protocol

ANDROID_PHONE

### 其他组件版本

BungeeCord-1.12

**Comment by Karlatemp** [comment]
善用搜索
![Screenshot_2023-01-03-09-17-20-29_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/30070303/210289119-175d9d25-947c-42cc-85eb-103ea7d81777.jpg)

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/issues/2138
