### ISSUE TITLE
登录报错，提示“服务连接中，请稍后再试”

### ISSUE THREAD

**Issue by kirito141211** [mamoe/mirai#2426]
### 问题描述

- 2.13.3后登录填完验证码ticket提示”服务连接中，请稍后再试“
- 参考过[登录报错，提示“服务连接中，请稍后再试” · Issue #2425 · mamoe/mirai](https://github.com/mamoe/mirai/issues/2425)
- 做过如下尝试，均出现同样错误。
    - 更换QQ号，
    - 删除bots
    - 在全新的服务器手动安装MCL
- 将版本改为2.13.2之后，正常登录，但2.13.2版本某些账号登录会报[尝试登录账号时，出现net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException错误 · Issue #2418 · mamoe/mirai](https://github.com/mamoe/mirai/issues/2418)
```
2023-01-15 07:02:39 I/Bot.1291163347: [SliderCaptcha] 正在提交中...
2023-01-15 07:02:39 I/Bot.1291163347: [SliderCaptcha] Submitting...
2023-01-15 07:02:39 I/Bot.1291163347: Bot cancelled: Bot closed
Login failed: Error(bot=Bot(1291163347), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
2023-01-15 07:02:39 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1291163347), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1291163347), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### 复现

使用2.13.3版本登录均会出现

### mirai-core 版本

2.13.3

### bot-protocol

ANDROID_PHONE

**Comment by cssxsh** [comment]
你看看是不是安装了
https://github.com/cssxsh/mirai-device-generator

PS: 用的人很多，但我很久没更新了，有一定几率和别人撞了？

**Comment by kirito141211** [comment]
> 你看看是不是安装了 https://github.com/cssxsh/mirai-device-generator
> 
> PS: 用的人很多，但我很久没更新了，有一定几率和别人撞了？

没有，我从这里直接下载zip解压后什么都没装直接登录，也这样。把版本改成2.13.2就不会报这个错了。[iTXTech/mirai-console-loader: 模块化、轻量级且支持完全自定义的 mirai 加载器。](https://github.com/iTXTech/mirai-console-loader)

**Comment by cssxsh** [comment]
那建议使用 https://github.com/KasukuSakura/mirai-login-solver-sakura
完成验证试试看

**Comment by sandtechnology** [comment]
感觉应该是忘记了实现这个 一会PR一下
https://github.com/Mrs4s/MiraiGo/commit/6f4f491002733025a3dd93e0bde13acc673839f8
https://github.com/Mrs4s/MiraiGo/commit/0ce160e357c5b8bc36167b6720c4554b4db02e86

**Comment by Lycofuture** [comment]
我也遇到了这个问题，请问怎么退回之前的版本

**Comment by Kwisma** [comment]
我也遇到了此问题，请问怎么降版本吗

**Comment by dragon0629** [comment]
> 那建议使用 https://github.com/KasukuSakura/mirai-login-solver-sakura 完成验证试试看

一样的问题，正好在试用，用这个扫码后报错依旧

2023-01-15 20:23:57 D/mirai-login-solver-sakura: [id: 0xe8d6da52, L:/192.168.10.224:49565 - R:/192.168.10.235:39190] [http   ] New http request: DefaultHttpRequest(decodeResult: success, version: HTTP/1.1) - POST /request/complete/87510077 HTTP/1.1
2023-01-15 20:23:57 V/mirai-login-solver-sakura: [id: 0xe8d6da52, L:/192.168.10.224:49565 - R:/192.168.10.235:39190] [http   ] DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
POST /request/complete/87510077 HTTP/1.1
Host: 192.168.10.224:49565
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/4.9.3
content-length: 155
2023-01-15 20:23:57 D/mirai-login-solver-sakura: [id: 0xe8d6da52, L:/192.168.10.224:49565 - R:/192.168.10.235:39190] [http   ] [87510077] post response: t03a8ai59NYbrviyDnvvcYzC2WY1v7CR7fYlACQpwmJgsLCtzFtMv61JnxdsSGBdg0V8Tamg8VYnYNlURO1RA8HQj0IkmRw4Wclc42pSxVFvzzOc5j0AXKm2hTtRwFMjYbfAXljzfG-b25lCAvioCyuTQ**
2023-01-15 20:23:57 I/Bot.2710979412: Bot cancelled: Bot closed
Login failed: Error(bot=Bot(2710979412), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
2023-01-15 20:23:57 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2710979412), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2710979412), code=6, title=登录失败, message=服务连接中， 请稍后再试。(0x6), errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)


已尝试：
删掉device.json重新生成
手机qq同网络环境在线

**Comment by kirito141211** [comment]
> 那建议使用 https://github.com/KasukuSakura/mirai-login-solver-sakura 完成验证试试看

就是用这个验证生成token去认证的，提交滑块验证token之后出现了这个结果。

**Comment by kirito141211** [comment]
> 我也遇到了此问题，请问怎么降版本吗

修改config.json里对应的版本就行

**Comment by HYLZ-2019** [comment]
同样的问题，用mcl退到2.13.2后，仍然报错：
2023-01-15 21:53:34 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(**********), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)

**Comment by Xwdit** [comment]
更换为IPAD协议可以解决这个问题

**Comment by Speechless22** [comment]
我也有一样的问题

**Comment by sandtechnology** [comment]
PR 已提交，但是需要账号进行测试和debug，因为我并没有这种情况：https://github.com/mamoe/mirai/pull/2433
所以说有人愿意提供出现这种情况的账号给我吗，可以发邮件到 [REACT] 带上账号和密码（可以在官方客户端进行修改成简单密码再修改回来

**Comment by dragon0629** [comment]
> PR 已提交，但是需要账号进行测试和debug，因为我并没有这种情况：#2433
> 所以说有人愿意提供出现这种情况的账号给我吗，可以发邮件到 [sandtech0586@gmail.com](mailto:sandtech0586@gmail.com) 带上账号和密码（可以在官方客户端进行修改成简单密码再修改回来

我的小号账密发你了

**Comment by sandtechnology** [comment]
> > PR 已提交，但是需要账号进行测试和debug，因为我并没有这种情况：#2433
> > 所以说有人愿意提供出现这种情况的账号给我吗，可以发邮件到 [sandtech0586@gmail.com](mailto:sandtech0586@gmail.com) 带上账号和密码（可以在官方客户端进行修改成简单密码再修改回来
> 
> 我的小号账密发你了

感谢，进行测试后通过了 到手机验证码登录环节了

**Comment by sandtechnology** [comment]
好像还是有些问题 等我debug完再提交吧）

**Comment by sandtechnology** [comment]
@dragon0629 好了 bug修好了 非常感谢提供账号 记得修改密码（

**Comment by zhaodice** [comment]
> @dragon0629 好了 bug修好了 非常感谢提供账号 记得修改密码（

下载了预编译版本，替换好后问题解决了

**Comment by zhaodice** [comment]
可是...我看了一下代码，pow? 死循环计算? 直到正确的结果...
这不是挖矿吗？tx想干什么哦...

**Comment by cssxsh** [comment]
> 可是...我看了一下代码，pow? 死循环计算? 直到正确的结果... 这不是挖矿吗？tx想干什么哦...

类区块链校验登录

**Comment by sandtechnology** [comment]
https://blog.csdn.net/lucky_greenegg/article/details/52530570

> 工作量证明(Proof Of Work，简称POW)，简单理解就是一份证明，用来确认你做过一定量的工作。监测工作的整个过程通常是极为低效的，而通过对工作的结果进行认证来证明完成了相应的工作量，则是一种非常高效的方式。比如现实生活中的毕业证、驾驶证等等，也是通过检验结果的方式（通过相关的考试）所取得的证明。

> 工作量证明系统（或者说协议、函数），是一种应对拒绝服务攻击和其他服务滥用的经济对策。它要求发起者进行一定量的运算，也就意味着需要消耗计算机一定的时间。这个概念由Cynthia Dwork 和Moni Naor 1993年在学术论文中首次提出。而工作量证明（POW）这个名词，则是在1999年 Markus Jakobsson 和Ari Juels的文章中才被真正提出。

**Comment by zhaodice** [comment]
tx搞这个没有用，因为手机不可能设置高难度的目标，而这又可以轻而易举地被其他具有高算力的机器攻破。（而且白嫖算力的嫌疑还蛮大的）

**Comment by sandtechnology** [comment]
> tx搞这个没有用，因为手机不可能设置高难度的目标，而这又可以轻而易举地被其他具有高算力的机器攻破。（而且白嫖算力的嫌疑还蛮大的）

总之这是Off Topic的，但是可以在我的PR下讨论应该（
我觉得这确实可以进行防御 具体叙述此处不提了（
