### ISSUE TITLE
java.lang.IllegalStateException: Failed to load services for MessageProtocol from your classpath.

### ISSUE THREAD

**Issue by disymayufei** [mamoe/mirai#2427]
### 问题描述

不确定是不是由于我打包方式错误引起的，还望大佬指导一下。
我现在是依赖mirai编写一个Minecraft-QQ机器人插件，之前的2.10.3和2.11.1版本都是正常的，从2.12.0起一直到2.13.2，打包后运行插件都会产生下方日志中提到的错误。我解包编写好的插件查看后，是可以找到net.mamoe.mirai.internal.message.protocol.MessageProtocol类的，我不确定这是不是一个bug

### 复现

1. 依赖mirai-core-jvm-2.13.2开发Minecraft插件
2. 使用maven打包上述插件
3. 放置于Minecraft服务器运行，产生下方的错误

### mirai-core 版本

2.13.2

### bot-protocol

MACOS

### 系统日志

```text
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.IMirai
        at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:21) ~[?:?]
        at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357) ~[?:?]
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348) ~[?:?]
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39) ~[?:?]
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:116) ~[?:?]
        at cn.starlight.disy.qqbot.bot.RunnableBot.<init>(RunnableBot.java:38) ~[?:?]
        at cn.starlight.disy.qqbot.Main.onEnable(Main.java:39) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Thread.java:831) [?:?]
        Suppressed: java.lang.ExceptionInInitializerError
                at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade.<clinit>(MessageProtocolFacade.kt) ~[?:?]
                at net.mamoe.mirai.internal.MiraiImplKt._MiraiImpl_static_init(MiraiImpl.kt:25) ~[?:?]
                at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt:94) ~[?:?]
                at java.lang.Class.forName0(Native Method) ~[?:?]
                at java.lang.Class.forName(Class.java:375) ~[?:?]
                at net.mamoe.mirai.utils.ServicesKt.findCreateInstance(Services.kt:27) ~[?:?]
                at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:20) ~[?:?]
                at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357) ~[?:?]
                at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348) ~[?:?]
                at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39) ~[?:?]
                at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:116) ~[?:?]
                at cn.starlight.disy.qqbot.bot.RunnableBot.<init>(RunnableBot.java:38) ~[?:?]
                at cn.starlight.disy.qqbot.Main.onEnable(Main.java:39) ~[?:?]
                at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
                at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
                at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
                at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
                at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
                at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
                at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
                at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
                at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot-1.16.5.jar:3096a-Spigot-9fb885e-af1a232]
                at java.lang.Thread.run(Thread.java:831) [?:?]
        Caused by: java.lang.IllegalStateException: Failed to load services for MessageProtocol from your classpath. Check you ClassLoader environment and ensure services for 'net.mamoe.mirai.internal.message.protocol.MessageProtocol' can be loaded. This should not happen if you are using mirai under default JVM classloader or using Mirai Console.If so, please file an issue. If you are trying to load mirai manually from other classloader, e.g. in another plugin system like Minecraft, it's your responsibility to ensure the Java SPI works.
                at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.<init>(MessageProtocolFacade.kt:208) ~[?:?]
                at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.<init>(MessageProtocolFacade.kt:193) ~[?:?]
                at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.<init>(MessageProtocolFacade.kt:162) ~[?:?]
                at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.<clinit>(MessageProtocolFacade.kt) ~[?:?]
```

### 补充信息

以下是Maven中的pom.xml：

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cn.starlight.disy.qqbot</groupId>
    <artifactId>SL-QQBot</artifactId>
    <version>3.0</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>

                <configuration>
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>

                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>cn.starlight.disy.qqbot.Main</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>spigot-pub</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/public/</url>
        </repository>
    </repositories>

    <properties>
        <maven.compiler.source>16</maven.compiler.source>
        <maven.compiler.target>16</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.16.5-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.24</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>23.1.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.13.2</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.java-websocket</groupId>
            <artifactId>Java-WebSocket</artifactId>
            <version>1.5.3</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

</project>

**Comment by cssxsh** [comment]
这和 SPI 的工作原理有关

你需要切换 线程的 `classLoader`
```
        val current = Thread.currentThread()
        val oc = current.contextClassLoader
        try {
            current.contextClassLoader = Mirai::class.java.classLoader
            
            // do something

        } finally {
            current.contextClassLoader = oc
        }
```

或者你 你开启一个单独的线程用于启动 mirai (记得调整contextClassLoader)

**Comment by disymayufei** [comment]
感谢大佬，上一个报错没有了，不过报错变了一个：
[21:43:18] [Thread-14/WARN]: Exception in thread "Thread-14" java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:21)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.utils.ServicesKt.loadService$default(Services.kt:16)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:34)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:33)
[21:43:18] [Thread-14/WARN]:    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:33)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.event.GlobalEventChannel.createListener(GlobalEventChannel.kt:47)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.event.EventChannel.createListener0$mirai_core_api(EventChannel.kt:722)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.event.FilterEventChannel.createListener(EventChannel.kt:540)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.event.EventChannel.createListener0$mirai_core_api(EventChannel.kt:722)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.event.FilterEventChannel.createListener(EventChannel.kt:540)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt:625)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.event.EventChannel.subscribeAlways$default(EventChannel.kt:617)
[21:43:18] [Thread-14/WARN]:    at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt)
[21:43:18] [Thread-14/WARN]:    at cn.starlight.disy.qqbot.bot.RunnableBot.launchBot(RunnableBot.java:87)
[21:43:18] [Thread-14/WARN]:    at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by cssxsh** [comment]
> at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:21)

还是一样的问题

**Comment by disymayufei** [comment]
问题已解决，感谢大佬
