### ISSUE TITLE
更新版本以后再次出现 net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null报错

### ISSUE THREAD

**Issue by apotatopudding** [mamoe/mirai#2429]
### 问题描述

- 我的bot在使用2.13.2时，其中一个账号出现net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null报错，我一共有三个账号在提供bot服务，有且仅有这一个账号出现该报错，其他两个账号都正常，当时在issues搜索时发现官方人员已在修复bug，于是停止了该账号的服务并等待更新
- 2.13.3版本更新后我更新了mirai框架，删除了cache和device.json后再次启动该报错账号，再一次出现同样的报错信息
- 我已经尝试过更换协议，其中，ANDROID_PAD协议出现的报错信息为net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3273836145), code=45, title=禁止登录, message=您好，您当前使用的版本过低，前往QQ官网im.qq.com下载新版QQ。, errorInfo=)，ANDROID_WATCH协议未进行尝试，其他所有协议报错均为DecryptionFailedException: null
- 在该账号尝试登录失败以后，我在同一台电脑尝试使用其他正常账号再次进行登录，没有出现任何报错信息可以完美登录
- 完整报错代码如下
`2023-01-16 02:21:17.393  WARN 21544 --- [atcher-worker-3] net.mamoe.mirai.Bot                      : Exception in resumeConnection.

net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null
	at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-01-16 02:21:17.393 ERROR 21544 --- [ntLoopGroup-2-7] net.mamoe.mirai.Bot                      : Exception in decoding packet.

net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null
	at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-jvm-2.13.2.jar:2.13.2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.6.0.jar:1.6.0-release-798(1.6.0)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.0.jar:na]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.54.Final.jar:4.1.54.Final]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-01-16 02:21:17.393  WARN 21544 --- [atcher-worker-3] net.mamoe.mirai.Bot                      : Network selector received exception, closing bot. (net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException)
2023-01-16 02:21:17.398  INFO 21544 --- [ntLoopGroup-2-8] net.mamoe.mirai.Bot                      : Bot cancelled: Bot closed
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
	at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299)
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275)
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295)
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319)
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318)
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623)
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368)
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)`

### 复现

在服务器端和pc端各尝试过数次，其余账号皆无问题，仅有该账号出现此报错。

### mirai-core 版本

2.13.3

### bot-protocol

IPAD

**Comment by sandtechnology** [comment]
> net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275) ~[mirai-core-jvm-**2.13.2**.jar:**2.13.2**]
> mirai-core 版本
> **2.13.3**

确认版本正确？

**Comment by apotatopudding** [comment]
> > net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275) ~[mirai-core-jvm-**2.13.2**.jar:**2.13.2**]
> > mirai-core 版本
> > **2.13.3**
> 
> 确认版本正确？

是的，已经清理缓存检查过，但是现在没法登录复现了，账号登录太多次现在锁定上，登录报错变成了网络不稳定登录失败，可能需要明天才能再复现了

**Comment by apotatopudding** [comment]
> > net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275) ~[mirai-core-jvm-**2.13.2**.jar:**2.13.2**]
> > mirai-core 版本
> > **2.13.3**
> 
> 确认版本正确？

刚刚尝试把maven仓库清空重新引用后再次登录，信息变为请求手机验证码，输入验证码以后登录恢复正常了。可能是idea的引用出现了问题，很抱歉打扰到您，非常感谢您的耐心解答
