### ISSUE TITLE
在 解析 richMsg 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai.

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai#243]
mirai-core-qqandroid-jvm-0.37.0.jar

```
[23:05:56] [SEVERE] java.lang.IllegalStateException: 在 解析 richMsg 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai. 调试信息: 00 3C 3F 78 6D 6C 20 76 65 72 73 69 6F 6E 3D 27 31 2E 30 27 20 65 6E 63 6F 64 69 6E 67 3D 27 55 54 46 2D 38 27 20 73 74 61 6E 64 61 6C 6F 6E 65 3D 27 79 65 73 27 3F 3E 3C 6D 73 67 20 74 65 6D 70 6C 61 74 65 49 44 3D 22 31 32 33 22 20 75 72 6C 3D 22 68 74 74 70 73 3A 2F 2F 79 6F 75 79 75 6E 36 36 36 2E 63 6F 6D 2F 22 20 73 65 72 76 69 63 65 49 44 3D 22 33 33 22 20 61 63 74 69 6F 6E 3D 22 77 65 62 22 20 61 63 74 69 6F 6E 44 61 74 61 3D 22 22 20 62 72 69 65 66 3D 22 E3 80 90 E9 93 BE E6 8E A5 E3 80 91 E4 BC 98 E4 BA 91 36 36 36 22 20 66 6C 61 67 3D 22 38 22 3E 3C 69 74 65 6D 20 6C 61 79 6F 75 74 3D 22 32 22 3E 3C 70 69 63 74 75 72 65 20 63 6F 76 65 72 3D 22 68 74 74 70 3A 2F 2F 31 2E 75 72 6C 2E 63 6E 2F 74 69 71 71 2F 72 65 6D 69 6E 64 2F 69 6D 67 2F 6C 69 6E 6B 2E 70 6E 67 22 2F 3E 3C 74 69 74 6C 65 3E E4 BC 98 E4 BA 91 36 36 36 3C 2F 74 69 74 6C 65 3E 3C 73 75 6D 6D 61 72 79 3E E4 BC 98 E4 BA 91 36 36 36 E4 BC 98 E4 BA 91 36 36 36 3C 2F 73 75 6D 6D 61 72 79 3E 3C 2F 69 74 65 6D 3E 3C 2F 6D 73 67 3E
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.message.ConvensionKt.contextualBugReportException(convension.kt:417) [mirai-core-qqandroid-jvm-0.37.0.jar:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.message.ConvensionKt.joinToMessageChain(convension.kt:287) [mirai-core-qqandroid-jvm-0.37.0.jar:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.message.ConvensionKt.toMessageChain(convension.kt:200) [mirai-core-qqandroid-jvm-0.37.0.jar:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.message.ConvensionKt.toMessageChain$default(convension.kt:186) [mirai-core-qqandroid-jvm-0.37.0.jar:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$PbPushGroupMsg.decode(OnlinePush.kt:105) [?:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:493) [mirai-core-qqandroid-jvm-0.37.0.jar:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:226) [mirai-core-qqandroid-jvm-0.37.0.jar:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:400) [mirai-core-qqandroid-jvm-0.37.0.jar:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:395) [mirai-core-qqandroid-jvm-0.37.0.jar:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:380) [?:?]
[23:05:56] [SEVERE] 	at app/kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-console-wrapper-0.2.0-all.jar:?]
[23:05:56] [SEVERE] 	at app/kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) [mirai-console-wrapper-0.2.0-all.jar:?]
[23:05:56] [SEVERE] 	at app/kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [mirai-console-wrapper-0.2.0-all.jar:?]
[23:05:56] [SEVERE] 	at app/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) [?:?]
[23:05:56] [SEVERE] 	at app/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [?:?]
[23:05:56] [SEVERE] 	at app/kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [?:?]
[23:05:56] [SEVERE] Caused by: java.util.zip.DataFormatException: incorrect header check
[23:05:56] [SEVERE] 	at java.base@13.0.2/java.util.zip.Inflater.inflateBytesBytes(Native Method) [JavaRuntime:?]
[23:05:56] [SEVERE] 	at java.base@13.0.2/java.util.zip.Inflater.inflate(Inflater.java:378) [JavaRuntime:?]
[23:05:56] [SEVERE] 	at java.base@13.0.2/java.util.zip.Inflater.inflate(Inflater.java:464) [JavaRuntime:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.utils.MiraiPlatformUtils.unzip(MiraiPlatformUtils.kt:30) [mirai-core-qqandroid-jvm-0.37.0.jar:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.utils.MiraiPlatformUtils.unzip$default(MiraiPlatformUtils.kt) [mirai-core-qqandroid-jvm-0.37.0.jar:?]
[23:05:56] [SEVERE] 	at app/net.mamoe.mirai.qqandroid.message.ConvensionKt.joinToMessageChain(convension.kt:288) [mirai-core-qqandroid-jvm-0.37.0.jar:?]
[23:05:56] [SEVERE] 	... 14 more
```

**Comment by Him188** [comment]
请尝试0.37.4
此问题已修复，可能在0.37.4发布了，也可能还没发布
