### ISSUE TITLE
启动报错 java.util.zip.ZipException: zip END header not found

### ISSUE THREAD

**Issue by stars-spark** [mamoe/mirai#2430]
### 问题描述

2023-01-16 14:14:18 E/main: Failed to init MiraiConsole.
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.init0(JvmPluginClassLoader.kt:271)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.init1(JvmPluginClassLoader.kt:263)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.<init>(JvmPluginClassLoader.kt:258)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.<init>(JvmPluginClassLoader.kt)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN$Companion.newLoader(JvmPluginClassLoader.kt:371)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:209)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.listPlugins(BuiltInJvmPluginLoaderImpl.kt:67)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:189)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:135)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:145)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:279)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:196)
	at org.itxtech.mcl.Loader.main(Loader.java:84)
	Suppressed: java.lang.RuntimeException: Failed to initialize new JvmPluginClassLoader, file=/home/lee/Desktop/小灵/plugins/pixiv-1.7.5.mirai2.jar
		at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.init1(JvmPluginClassLoader.kt:265)
		... 27 more

### 复现

启动

### mirai-core 版本

2.13.3

### bot-protocol

ANDROID_PAD

### 其他组件版本

14:14:08 [INFO] Verifying "net.mamoe:mirai-console" v2.13.3
  14:14:09 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.3
  14:14:09 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.3
  14:14:10 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  14:14:10 [INFO] Verifying "net.mamoe:mirai-api-http" v2.6.2
  14:14:10 [INFO] Verifying "net.mamoe:chat-command" v0.5.1
  14:14:10 [INFO] Verifying "xyz.cssxsh.mirai:mirai-administrator" v1.3.1
  14:14:10 [INFO] Verifying "io.github.gnuf0rce:debug-helper" v1.3.5
  14:14:10 [INFO] Verifying "com.hcyacg:pixiv" v1.7.4
  14:14:10 [ERROR] "com.hcyacg:pixiv" is corrupted.
  14:14:10 [INFO] Updating "com.hcyacg:pixiv" to v1.7.4
 Downloading pixiv-1.7.4.mirai2.jar [==============================] 1.05 MB                         
 Downloading pixiv-1.7.4.mirai2.jar.sha1 [==============================] 40 B                    
  14:14:12 [INFO] Verifying "xyz.cssxsh.mirai:mirai-device-generator" v1.1.3

**Comment by cssxsh** [comment]
plugins 里面有损坏的插件插件文件，你需要自己检查

**Comment by zhaodice** [comment]
> plugins 里面有损坏的插件插件文件，你需要自己检查

我猜测下载的过程中没有验证文件完整性，文件下载了又没有完全下载

**Comment by cssxsh** [comment]
> Suppressed: java.lang.RuntimeException: Failed to initialize new JvmPluginClassLoader, file=/home/lee/Desktop/小灵/plugins/pixiv-1.7.5.mirai2.jar

**Comment by is-liu** [comment]
朋友你这个问题是怎么解决的，困扰我好久了
