### ISSUE TITLE
启动报错 net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException

### ISSUE THREAD

**Issue by Chen-Luan** [mamoe/mirai#2434]
### 问题描述

启动后自动登录时遇到报错 net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
已尝试在MACOS和ANDROID_PAID登陆

### 复现

启动

### mirai-core 版本

Mirai consosle 2.13.0

### bot-protocol

MACOS

### 其他组件版本

/status

Running MiraiConsole v2.13.0, built on 2022-11-01 10:47:11.
Frontend Terminal: version 2.13.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: MiraiNative v2.0.0-cssxsh, MCL Addon v2.0.2

Object Pending Finalization Count: 0
                 committed |  init   |  used   |   max
    Heap Memory:  56.81MB  | 16.0MB  | 31.03MB | 247.5MB
Non-Heap Memory:  40.92MB  | 160.0KB | 40.31MB |   -1

### 系统日志

```text
Mirai Dice 启动脚本
初始化
检测Java
Java: .\jre\bin\java
检测Git
Git: git
  21:12:52 [INFO] iTXTech Mirai Console Loader version 2.1.1-d66fada
  21:12:52 [INFO] https://github.com/iTXTech/mirai-console-loader
  21:12:52 [INFO] This program is licensed under GNU AGPL v3
  21:12:59 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  21:12:59 [INFO] Verifying "net.mamoe:mirai-console" v2.13.0
  21:12:59 [WARN] Package "net.mamoe:mirai-console" has newer version "2.12.3"
  21:12:59 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.0
  21:12:59 [WARN] Package "net.mamoe:mirai-console-terminal" has newer version "2.12.3"
  21:12:59 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.0
  21:12:59 [WARN] Package "net.mamoe:mirai-core-all" has newer version "2.12.3"
  21:12:59 [INFO] Verifying "org.itxtech:mcl-addon" v2.0.2
  21:12:59 [WARN] Package "org.itxtech:mcl-addon" has newer version "2.1.0"
  21:12:59 [WARN] Run ./mcl -u to update packages.
2023-01-16 21:13:01 I/main: Starting mirai-console...
2023-01-16 21:13:01 I/main:

==================================[ Mirai consosle 2.13.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-01-16 21:13:01 I/main: Backend: version 2.13.0, built on 2022-11-01 10:47:11.
2023-01-16 21:13:01 I/main: Frontend Terminal: version 2.13.0, provided by Mamoe Technologies
2023-01-16 21:13:01 I/main: Welcome to visit https://mirai.mamoe.net/
2023-01-16 21:13:02 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2023-01-16 21:13:02 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2023-01-16 21:13:02 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2023-01-16 21:13:02 I/plugin: Successfully loaded plugin MiraiNative v2.0.0-cssxsh
2023-01-16 21:13:02 I/plugin: Successfully loaded plugin MCL Addon v2.0.2
2023-01-16 21:13:02 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-01-16 21:13:02 I/MiraiNative: 正在加载 Mirai Native Bridge E:\跑团专用\Dice\data\org.itxtech.mirainative\CQP.dll
2023-01-16 21:13:03 I/MiraiNative: 插件 Dice.Driver.CQ.dll 已被加载，返回值为 0 。
2023-01-16 21:13:03 I/MCL Addon: iTXTech MCL Version: 2.1.1-d66fada
2023-01-16 21:13:03 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-01-16 21:13:03 I/main: 2 plugin(s) enabled.
2023-01-16 21:13:03 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2023-01-16 21:13:03 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2023-01-16 21:13:03 I/main: Auto-login 3576711232, protocol: MACOS, heartbeatStrategy: STAT_HB
2023-01-16 21:13:03 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2023-01-16 21:13:20 E/main: net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
        at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299)
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275)
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295)
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319)
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318)
        at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623)
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368)
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

2023-01-16 21:13:20 I/Bot.3576711232: Bot cancelled: Bot closed
2023-01-16 21:13:20 I/main: mirai-console started successfully.

```
```


### 网络日志

```text
附件 2023-01-16.log
```

### 补充信息

[2023-01-16.log](https://github.com/mamoe/mirai/files/10426111/2023-01-16.log)

**Comment by MrXiaoM** [comment]
#2418
