### ISSUE TITLE
Bot 的昵称，好有列表和群组列表未正常加载

### ISSUE THREAD

**Issue by StageGuard** [mamoe/mirai#2441]
### 问题描述

在某些情况下，即使 Bot 登录成功且 Log 显示 `Successfully loaded group list: xx in total` 的情况下，依然未正确加载联系人列表至 Bot 中。
`bot.friends` 和 `bot.groups` 为空，nick 为空字符串。

### 复现

由于无法稳定复现，我只能提供类似代码。
我仅在 2.13 后发现该问题，因为我从 2.13 开始编写相关项目，估计为历史遗留问题。
`build.gradle`
```groovy
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt'
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'kotlin-parcelize'
}

android {
    compileSdk 33
    //...
}
dependencies {
    runtimeOnly("net.mamoe:mirai-core-android:$mirai_version") {
        exclude module: 'atomicfu', group: 'org.jetbrains.kotlinx'
    }
    api "net.mamoe:mirai-core-api-android:$mirai_version"
    implementation "net.mamoe:mirai-core-utils-android:$mirai_version"}
}
```
登录代码
```kotlin
class Service : LifecycleService() {
    lateinit var bot: Bot
    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        super.onStartCommand(intent, flags, startId)
        bot = BotFactory.newBot(12345L, "password") {
            parentCoroutineContext = lifecycleScope.coroutineContext
            protocol = MiraiProtocol.ANDROID_PHONE
            enableContactCache()
        }
        val job = lifecycleScope.launch {
            bot.login()
            bot.join()
        }
        return Service.START_STICKY
    }
}
```

### mirai-core 版本

2.14.0-RC

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2023-01-19 14:35:05.863  2072-2072  Bot.12345   I  Bot login successful.
2023-01-19 14:35:06.846  2072-3231  Net.12345   V  Validated caches.
2023-01-19 14:35:06.848  2072-3231  Net.12345   V  No server list cached.
2023-01-19 14:35:07.483  2072-3231  Bot.12345   I  Loaded account secrets from local cache.
2023-01-19 14:35:07.487  2072-3231  Net.12345   I  ECDH key is valid.
2023-01-19 14:35:07.829  2072-3231  Net.12345   V  Send: wtlogin.exchange_emp(10:fast-login)
2023-01-19 14:35:08.220  2072-3303  Net.12345   V  Recv: wtlogin.exchange_emp
2023-01-19 14:35:08.306  2072-3231  Bot.12345   I  Saved account secrets to local cache for fast login.
2023-01-19 14:35:08.834  2072-3231  Net.12345   V  Send: StatSvc.register(online)
2023-01-19 14:35:09.015  2072-3231  Bot.12345   I  Login successful.
2023-01-19 14:35:09.015  2072-3314  Net.12345   I  Server time updated, serverTime: 1674110109, diff: 0ms=0.0s
2023-01-19 14:35:09.017  2072-3314  Net.12345   V  Recv: StatSvc.register
2023-01-19 14:35:09.020  2072-2072  Net.12345   I  Syncing friend message history...
2023-01-19 14:35:09.032  2072-2072  Net.12345   V  Loading BdhSession from cache file
2023-01-19 14:35:09.045  2072-3259  Net.12345   I  Loaded 368 friends from local cache.
2023-01-19 14:35:09.047  2072-3258  Net.12345   I  Start loading stranger list...
2023-01-19 14:35:09.049  2072-3244  Net.12345   I  Start loading friendGroup list...
2023-01-19 14:35:09.081  2072-3232  Net.12345   V  Send: OidbSvc.0x496(OidbSvc.0x496)
2023-01-19 14:35:09.083  2072-3258  Net.12345   V  Send: OidbSvc.0x5d2_0(OidbSvc.0x5d2_0)
2023-01-19 14:35:09.102  2072-3231  Net.12345   V  Send: StatSvc.GetDevLoginInfo(StatSvc.GetDevLoginInfo)
2023-01-19 14:35:09.122  2072-3259  Net.12345   V  Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)
2023-01-19 14:35:09.129  2072-3244  Net.12345   V  Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)
2023-01-19 14:35:09.287  2072-3315  Net.12345   V  Recv: StatSvc.GetDevLoginInfo
2023-01-19 14:35:09.288  2072-3244  Net.12345   I  Online OtherClients: Android(MOBILE)
2023-01-19 14:35:09.314  2072-3244  Net.12345   I  Start loading group list...
2023-01-19 14:35:09.316  2072-3315  Net.12345   V  Recv: OidbSvc.0x496
2023-01-19 14:35:09.335  2072-3244  Net.12345   V  Send: friendlist.GetTroopListReqV2(friendlist.GetTroopListReqV2)
2023-01-19 14:35:09.352  2072-3244  Net.12345   I  Successfully loaded stranger list: 3 in total
2023-01-19 14:35:09.352  2072-3316  Net.12345   V  Recv: OidbSvc.0x5d2_0
2023-01-19 14:35:09.527  2072-3319  Net.12345   V  Recv: friendlist.getFriendGroupList
2023-01-19 14:35:11.469  2072-3319  Net.12345   V  Recv: friendlist.GetTroopListReqV2
2023-01-19 14:35:12.304  2072-3244  Net.12345   I  Loaded 47 members from local cache for group <group name> (123456)
2023-01-19 14:35:12.477  2072-3257  Net.12345   I  Loaded 78 members from local cache for group <group name> (123456)
2023-01-19 14:35:12.531  2072-3232  Net.12345   I  Loaded 58 members from local cache for group <group name> (123456)
2023-01-19 14:35:12.629  2072-3258  Net.12345   I  Loaded 63 members from local cache for group <group name> (123456)
2023-01-19 14:35:13.104  2072-3259  Net.12345   I  Loaded 107 members from local cache for group <group name> (123456)
2023-01-19 14:35:13.215  2072-3761  Net.12345   V  Saving bdh session to cache
2023-01-19 14:35:13.370  2072-3761  Net.12345   V  Send: ConfigPushSvc.PushResp(ConfigPushSvc.PushResp)
2023-01-19 14:35:13.380  2072-3761  Net.12345   V  Recv: ConfigPushSvc.PushReq
2023-01-19 14:35:13.630  2072-3231  Net.12345   I  Loaded 140 members from local cache for group <group name> (123456)
2023-01-19 14:35:14.349  2072-3232  Net.12345   I  Loaded 176 members from local cache for group <group name> (123456)
2023-01-19 14:35:14.405  2072-3232  Net.12345   V  Send: friendlist.getFriendGroupList(friendlist.getFriendGroupList)
2023-01-19 14:35:15.324  2072-3231  Net.12345   I  Loaded 226 members from local cache for group <group name> (123456)
2023-01-19 14:35:15.553  2072-3244  Net.12345   I  Loaded 412 members from local cache for group <group name> (123456)
2023-01-19 14:35:15.691  2072-3231  Net.12345   I  Loaded 39 members from local cache for group <group name> (123456)
2023-01-19 14:35:15.964  2072-3244  Net.12345   I  Loaded 50 members from local cache for group <group name> (123456)
2023-01-19 14:35:16.127  2072-3258  Net.12345   I  Loaded 376 members from local cache for group <group name> (123456)
2023-01-19 14:35:16.267  2072-3244  Net.12345   I  Loaded 89 members from local cache for group <group name> (123456)
2023-01-19 14:35:16.550  2072-3244  Net.12345   I  Loaded 52 members from local cache for group <group name> (123456)
2023-01-19 14:35:16.777  2072-3232  Net.12345   I  Loaded 417 members from local cache for group <group name> (123456)
2023-01-19 14:35:17.379  2072-3232  Net.12345   I  Loaded 46 members from local cache for group <group name> (123456)
2023-01-19 14:35:17.482  2072-3232  Net.12345   I  Loaded 13 members from local cache for group <group name> (123456)
2023-01-19 14:35:17.916  2072-3232  Net.12345   I  Loaded 63 members from local cache for group <group name> (123456)
2023-01-19 14:35:18.363  2072-3259  Net.12345   I  Loaded 681 members from local cache for group <group name> (123456)
2023-01-19 14:35:18.600  2072-3259  Net.12345   I  Loaded 31 members from local cache for group <group name> (123456)
2023-01-19 14:35:18.665  2072-3257  Net.12345   I  Loaded 760 members from local cache for group <group name> (123456)
2023-01-19 14:35:18.670  2072-3259  Net.12345   I  Loaded 9 members from local cache for group <group name> (123456)
2023-01-19 14:35:18.859  2072-3257  Net.12345   I  Loaded 20 members from local cache for group <group name> (123456)
2023-01-19 14:35:19.090  2072-3259  Net.12345   I  Loaded 56 members from local cache for group <group name> (123456)
2023-01-19 14:35:19.342  2072-3257  Net.12345   I  Loaded 75 members from local cache for group <group name> (123456)
2023-01-19 14:35:19.455  2072-3232  Net.12345   I  Loaded 189 members from local cache for group <group name> (123456)
2023-01-19 14:35:19.506  2072-3232  Net.12345   W  An exception was thrown during 'loading friendGroups' of Bot 12345. Trying to ignore the error and continue logging in...
  kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
  	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
  	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
  	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
  	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
  	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
  	at java.lang.Thread.run(Thread.java:920)
2023-01-19 14:35:19.564  2072-2072  Net.12345   I  Syncing friend message history: Success.
2023-01-19 14:35:19.752  2072-3258  Net.12345   I  Loaded 499 members from local cache for group <group name> (123456)
2023-01-19 14:35:20.062  2072-3259  Net.12345   I  Loaded 168 members from local cache for group <group name> (123456)
2023-01-19 14:35:20.164  2072-3259  Net.12345   I  Loaded 18 members from local cache for group <group name> (123456)
2023-01-19 14:35:20.190  2072-3257  Net.12345   I  Loaded 109 members from local cache for group <group name> (123456)
2023-01-19 14:35:20.304  2072-3257  Net.12345   I  Loaded 9 members from local cache for group <group name> (123456)
2023-01-19 14:35:20.405  2072-3257  Net.12345   I  Loaded 12 members from local cache for group <group name> (123456)
2023-01-19 14:35:20.688  2072-3259  Net.12345   I  Loaded 75 members from local cache for group <group name> (123456)
2023-01-19 14:35:20.784  2072-3258  Net.12345   I  Loaded 193 members from local cache for group <group name> (123456)
2023-01-19 14:35:21.151  2072-3258  Net.12345   I  Loaded 66 members from local cache for group <group name> (123456)
2023-01-19 14:35:21.365  2072-3257  Net.12345   I  Loaded 144 members from local cache for group <group name> (123456)
2023-01-19 14:35:21.414  2072-3258  Net.12345   I  Loaded 51 members from local cache for group <group name> (123456)
2023-01-19 14:35:21.450  2072-3259  Net.12345   I  Loaded 145 members from local cache for group <group name> (123456)
2023-01-19 14:35:21.538  2072-3259  Net.12345   I  Loaded 9 members from local cache for group <group name> (123456)
2023-01-19 14:35:21.619  2072-3231  Net.12345   I  Loaded 778 members from local cache for group <group name> (123456)
2023-01-19 14:35:21.978  2072-3259  Net.12345   I  Loaded 82 members from local cache for group <group name> (123456)
2023-01-19 14:35:22.109  2072-3258  Net.12345   I  Loaded 92 members from local cache for group <group name> (123456)
2023-01-19 14:35:22.398  2072-3258  Net.12345   I  Loaded 44 members from local cache for group <group name> (123456)
2023-01-19 14:35:22.459  2072-3257  Net.12345   I  Loaded 167 members from local cache for group <group name> (123456)
2023-01-19 14:35:22.541  2072-3231  Net.12345   I  Loaded 147 members from local cache for group <group name> (123456)
2023-01-19 14:35:22.977  2072-3231  Net.12345   I  Loaded 75 members from local cache for group <group name> (123456)
2023-01-19 14:35:23.157  2072-3231  Net.12345   I  Loaded 31 members from local cache for group <group name> (123456)
2023-01-19 14:35:23.170  2072-3259  Net.12345   I  Loaded 193 members from local cache for group <group name> (123456)
2023-01-19 14:35:23.237  2072-3259  Net.12345   I  Loaded 7 members from local cache for group <group name> (123456)
2023-01-19 14:35:23.417  2072-3258  Net.12345   I  Loaded 159 members from local cache for group <group name> (123456)
2023-01-19 14:35:23.496  2072-3257  Net.12345   I  Loaded 154 members from local cache for group <group name> (123456)
2023-01-19 14:35:23.592  2072-3259  Net.12345   I  Loaded 55 members from local cache for group <group name> (123456)
2023-01-19 14:35:24.124  2072-3231  Net.12345   I  Loaded 161 members from local cache for group <group name> (123456)
2023-01-19 14:35:24.187  2072-3259  Net.12345   I  Loaded 90 members from local cache for group <group name> (123456)
2023-01-19 14:35:24.406  2072-3232  Net.12345   I  Loaded 685 members from local cache for group <group name> (123456)
2023-01-19 14:35:24.441  2072-3231  Net.12345   I  Loaded 49 members from local cache for group <group name> (123456)
2023-01-19 14:35:24.524  2072-3232  Net.12345   I  Loaded 10 members from local cache for group <group name> (123456)
2023-01-19 14:35:24.555  2072-3257  Net.12345   I  Loaded 157 members from local cache for group <group name> (123456)
2023-01-19 14:35:24.690  2072-3258  Net.12345   I  Loaded 191 members from local cache for group <group name> (123456)
2023-01-19 14:35:24.800  2072-3259  Net.12345   I  Loaded 115 members from local cache for group <group name> (123456)
2023-01-19 14:35:24.976  2072-3231  Net.12345   I  Loaded 187 members from local cache for group <group name> (123456)
2023-01-19 14:35:26.064  2072-3244  Net.12345   I  Loaded 2574 members from local cache for group <group name> (123456)
2023-01-19 14:35:26.088  2072-3244  Net.12345   I  Successfully loaded group list: 62 in total.
2023-01-19 14:35:26.098  2072-3231  Net.12345   I  Scheduled refresh login session in 19d 23h 55min 0.0s.
2023-01-19 14:35:26.100  2072-3257  Net.12345   I  Scheduled key refresh in 23h 55min 0.0s.
2023-01-19 14:35:26.100  2072-3244  Bot.12345   V  Event: BotOnlineEvent(bot=Bot(12345))
2023-01-19 14:35:26.106  2072-2072  Bot.12345   I  Bot login successful.

```

**Comment by Him188** [comment]
应该不是 regression

**Comment by StageGuard** [comment]
非 mirai bug
