### ISSUE TITLE
无法登陆账户，“服务连接中，请稍后再试。”

### ISSUE THREAD

**Issue by KrisTHL181** [mamoe/mirai#2442]
### 问题描述

填写完毕Ticket后出现
2023-01-19 20:06:28 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...

net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(***), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)

### 复现

填完Ticket之后就出现了

### mirai-core 版本

2.13.3

### bot-protocol

ANDROID_PHONE

### 其他组件版本

Running MiraiConsole v2.13.3, built on 2023-01-14 09:43:14.
Frontend Terminal: version 2.13.3, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: MCL Addon v2.1.1

Object Pending Finalization Count: 0
                 committed |  init   |  used   |  max  
    Heap Memory:  100.0MB  | 186.0MB | 47.27MB | 2.89GB
Non-Heap Memory:  77.68MB  | 7.31MB  | 76.14MB |   -1  

### 系统日志

```text
20:06:21 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  20:06:21 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.5 (arch: 64)
  20:06:21 [INFO] https://github.com/iTXTech/mirai-console-loader
  20:06:21 [INFO] This program is licensed under GNU AGPL v3
  20:06:22 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
 
MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  20:06:22 [INFO] Verifying "net.mamoe:mirai-console" v2.13.3
  20:06:23 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.3
  20:06:23 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.3
  20:06:24 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
2023-01-19 20:06:26 I/main: Starting mirai-console...
2023-01-19 20:06:26 I/main: 

==================================[ Mirai consosle 2.13.3 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-01-19 20:06:26 I/main: Backend: version 2.13.3, built on 2023-01-14 09:43:14.
2023-01-19 20:06:26 I/main: Frontend Terminal: version 2.13.3, provided by Mamoe Technologies
2023-01-19 20:06:26 I/main: Welcome to visit https://mirai.mamoe.net/
2023-01-19 20:06:26 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2023-01-19 20:06:26 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2023-01-19 20:06:26 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2023-01-19 20:06:27 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-01-19 20:06:27 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-01-19 20:06:27 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-01-19 20:06:27 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-01-19 20:06:27 I/main: 1 plugin(s) enabled.
2023-01-19 20:06:27 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2023-01-19 20:06:27 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2023-01-19 20:06:27 I/main: Auto-login 3581338560, protocol: ANDROID_PHONE, heartbeatStrategy: STAT_HB
2023-01-19 20:06:28 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2023-01-19 20:07:09 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3581338560), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3581338560), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-01-19 20:07:09 I/Bot.3581338560: Bot cancelled: Bot closed
2023-01-19 20:07:09 I/main: mirai-console started successfully.
```

### 网络日志

```text
2023-01-19 20:07:09 W/Net 3581338560: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(3581338560), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3581338560), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	... 9 more

2023-01-19 20:07:09 W/Net 3581338560: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(3581338560), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=))
```

**Comment by sandtechnology** [comment]
#2426

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/issues/2426

已有相似问题, 且已在 `2.14.0-RC` 中解决

https://github.com/mamoe/mirai/releases/tag/v2.14.0-RC

https://mirai.mamoe.net/topic/1653

**Comment by HYLZ-2019** [comment]
> 

请问这个2.14.0-RC应该怎么安装？点那个release的链接是404（

**Comment by cssxsh** [comment]
> > 
> 
> 请问这个2.14.0-RC应该怎么安装？点那个release的链接是404（

https://mirai.mamoe.net/topic/1653

**Comment by HYLZ-2019** [comment]
> > > 
> > 
> > 
> > 请问这个2.14.0-RC应该怎么安装？点那个release的链接是404（
> 
> https://mirai.mamoe.net/topic/1653

谢谢您，我按照步骤操作了，但是登录仍然会报错：
2023-01-19 20:57:30 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(*), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
启动器里的版本信息是：
  20:56:34 [INFO] Verifying "net.mamoe:mirai-console" v2.14.0-RC
  20:56:35 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.14.0-RC
  20:56:35 [INFO] Verifying "net.mamoe:mirai-core-all" v2.14.0-RC
  20:56:36 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  20:56:36 [INFO] Verifying "net.mamoe:mirai-api-http" v2.6.2
  20:56:36 [INFO] Verifying "net.mamoe:chat-command" v0.5.1
  20:56:36 [INFO] Verifying "net.mamoe:mirai-login-solver-selenium" v1.0-dev-17
  20:56:36 [WARN] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-RC. Current version is 2.14.0-RC

**Comment by cssxsh** [comment]
> > > > 
> > > 
> > > 
> > > 请问这个2.14.0-RC应该怎么安装？点那个release的链接是404（
> > 
> > 
> > https://mirai.mamoe.net/topic/1653
> 
> 谢谢您，我按照步骤操作了，但是登录仍然会报错： 2023-01-19 20:57:30 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(*), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=) 启动器里的版本信息是： 20:56:34 [INFO] Verifying "net.mamoe:mirai-console" v2.14.0-RC 20:56:35 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.14.0-RC 20:56:35 [INFO] Verifying "net.mamoe:mirai-core-all" v2.14.0-RC 20:56:36 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1 20:56:36 [INFO] Verifying "net.mamoe:mirai-api-http" v2.6.2 20:56:36 [INFO] Verifying "net.mamoe:chat-command" v0.5.1 20:56:36 [INFO] Verifying "net.mamoe:mirai-login-solver-selenium" v1.0-dev-17 20:56:36 [WARN] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-RC. Current version is 2.14.0-RC


你需要删掉 `bots/.../cache` 这个缓存文件夹

另外建议使用 https://github.com/KasukuSakura/mirai-login-solver-sakura 解决登录验证

**Comment by HYLZ-2019** [comment]
> 
您好，我删掉bots/.../cache之后，又用上了sakura solver，但是仍然会报错：

```
2023-01-19 21:28:20 I/Bot.xxx: Calculating type 2 PoW, it can take some time....
2023-01-19 21:28:20 I/Bot.xxx: Got PoW result, cost: 117 ms
请使用 SakuraLoginSolver 打开 http://<ip>:42987/request/request/52894230 来完成验证
2023-01-19 21:29:36 I/Bot.xxx: Bot cancelled: Bot closed
2023-01-19 21:29:36 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(xxx), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(xxx), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)

我尝试将protocol从ANDROID_PHONE换成IPAD，然后报了新错：

2023-01-19 21:35:08 W/io.netty.channel.DefaultChannelPipeline: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: Duplicate handler name: post-msg-receiver
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:247)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar//com.kasukusakura.mlss.slovbroadcast.SakuraTransmitDaemon.processHttpMsg(SakuraTransmitDaemon.kt:269)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar//com.kasukusakura.mlss.slovbroadcast.SakuraTransmitDaemon.access$processHttpMsg(SakuraTransmitDaemon.kt:48)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar//com.kasukusakura.mlss.slovbroadcast.SakuraTransmitDaemon$HttpConnectHandler.channelRead(SakuraTransmitDaemon.kt:721)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar//com.kasukusakura.mlss.slovbroadcast.SakuraTransmitDaemon$processHttpMsg$4$1.channelRead(SakuraTransmitDaemon.kt:297)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:829)

2023-01-19 21:35:08 W/io.netty.channel.DefaultChannelPipeline: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.util.IllegalReferenceCountException: refCnt: 0
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:289)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:280)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1103)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1096)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1087)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar//com.kasukusakura.mlss.slovbroadcast.SakuraTransmitDaemon$processHttpMsg$4$1.channelRead(SakuraTransmitDaemon.kt:272)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at mirai-login-solver-sakura-0.0.7.mirai2.jar[private]//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

然后卡死在这里。

下一次开./mcl（仍然是IPAD），提示
2023-01-19 21:37:52 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(xxx), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)

**Comment by cssxsh** [comment]
@HYLZ-2019 

你是不是处理 滑块太慢了
这容易被当成网络环境不好 也就是超时了

建议你多试几次

**Comment by cssxsh** [comment]
@HYLZ-2019 
还不行的话 就再删一遍 `bot/.../cache`, 顺便把 `device.json` 也删掉

**Comment by Him188** [comment]
@Karlatemp  java.lang.IllegalArgumentException: Duplicate handler name: post-msg-receiver,

看上面日志

**Comment by HYLZ-2019** [comment]
> @HYLZ-2019 还不行的话 就再删一遍 `bot/.../cache`, 顺便把 `device.json` 也删掉

删掉bot/.../cache和device.json后，成功登录了。非常感谢！
