### ISSUE TITLE
MessageReceipt没有确保sourceId可用

### ISSUE THREAD

**Issue by ryoii** [mamoe/mirai#245]
## 问题

mamoe/mirai-api-http#66

```
java.lang.IllegalStateException: sequenceId not yet available
	at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl.getSequenceId(outgoingSourceImpl.kt:125)
	at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl.getId(outgoingSourceImpl.kt:114)
	at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$1.invokeSuspend(outgoingSourceImpl.kt:134)
	at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$1.invoke(outgoingSourceImpl.kt)
	at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$$inlined$subscribingGetAsync$1$2$1.invokeSuspend(linear.kt:102)
	at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$$inlined$subscribingGetAsync$1$2$1.invoke(linear.kt)
	at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$$inlined$subscribingGetAsync$1$2$2.invokeSuspend(subscriber.kt:141)
	at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$$inlined$subscribingGetAsync$1$2$2.invoke(subscriber.kt)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:76)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:76)
	at net.mamoe.mirai.event.internal.InternalEventListenersKt$callAndRemoveIfRequired$$inlined$forEachNode$lambda$1.invokeSuspend(InternalEventListeners.kt:162)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

## 如何复现

发送群消息、临时消息获得MeesageReceipt后，立刻获取`receipt.source.id`

**Comment by Him188** [comment]
0.37.5？

**Comment by ryoii** [comment]
是
