### ISSUE TITLE
重新使用Kotlin开发之后无法加载MiraiImpl

### ISSUE THREAD

**Issue by SuYueQiuLiang** [mamoe/mirai#2451]
### 问题描述

同一个项目，最近尝试使用Kotlin完全重构之后出现问题，无法加载MiraiImpl

### 复现

使用idea基于Mirai-core开发，kotlin编译器1.7.22，语言版本1.7，api版本1.7，找不到方法
int kotlin.text.CharsKt.digitToInt(char, int)

### mirai-core 版本

2.13.4

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
Exception in thread "main" java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804)
        at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1393)
        at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:240)
        at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:18)
        at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357)
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348)
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39)
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:116)
        at org.suyue.bot.manager.BotManager.loadBots(BotManager.kt:30)
        at org.suyue.bot.console.Interface.run(Interface.kt:26)
        at org.suyue.bot.console.InterfaceKt.main(Interface.kt:13)
        at org.suyue.bot.console.InterfaceKt.main(Interface.kt)
Caused by: java.lang.NoSuchMethodError: 'int kotlin.text.CharsKt.digitToInt(char, int)'
        at net.mamoe.mirai.utils.MiraiUtils__ConversionsKt.parseFromHexChunk(Conversions.kt:201)
        at net.mamoe.mirai.utils.MiraiUtils.parseFromHexChunk(Unknown Source)
        at net.mamoe.mirai.utils.MiraiUtils__ConversionsKt.hexToBytes(Conversions.kt:187)
        at net.mamoe.mirai.utils.MiraiUtils.hexToBytes(Unknown Source)
        at net.mamoe.mirai.internal.message.protocol.encode.MessageEncoderPipelineImpl.<clinit>(MessageEncoderPipeline.kt:83)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.<init>(MessageProtocolFacade.kt:197)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.<init>(MessageProtocolFacade.kt:193)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.<init>(MessageProtocolFacade.kt:162)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.<clinit>(MessageProtocolFacade.kt)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade.<clinit>(MessageProtocolFacade.kt)
        at net.mamoe.mirai.internal.MiraiImplKt._MiraiImpl_static_init(MiraiImpl.kt:25)
        at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt:94)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
        ... 12 more
```

**Comment by cssxsh** [comment]
给出你项目的配置文件

**Comment by SuYueQiuLiang** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.example</groupId>
    <artifactId>MyQQBot</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>
    <modules>
        <module>MCBot</module>
        <module>LezzBot</module>
        <module>MainBotAdmin</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>
    <repositories>
        <repository>
            <id>alimaven</id>
            <name>aliyun maven</name>
            <url>https://maven.aliyun.com/nexus/content/groups/public/</url>
        </repository>
        <repository>
            <id>minecraft-libraries</id>
            <name>Minecraft Libraries</name>
            <url>https://libraries.minecraft.net</url>
        </repository>

    </repositories>
    <dependencies>

        <dependency>
            <groupId>com.mojang</groupId>
            <artifactId>brigadier</artifactId>
            <version>1.0.18</version>
        </dependency>
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.13.4</version>
        </dependency>
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-logging-slf4j</artifactId>
            <version>2.13.4</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
            <version>4.9.0</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>converter-gson</artifactId>
            <version>2.9.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>2.0.21</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.retrofit2</groupId>
            <artifactId>retrofit</artifactId>
            <version>2.9.0</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.10.0</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>2.0.5</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>2.0.5</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.19.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.19.0</version>
        </dependency>
    </dependencies>
</project>

> 给出你项目的配置文件

**Comment by cssxsh** [comment]
我按照你给 `POM` 内容得到的 依赖树如下
```
[WARNING] The artifact org.slf4j:slf4j-log4j12:jar:2.0.5 has been relocated to org.slf4j:slf4j-reload4j:jar:2.0.5
[INFO] org.example:issue_2451:jar:1.0-SNAPSHOT
[INFO] +- com.mojang:brigadier:jar:1.0.18:compile
[INFO] +- net.mamoe:mirai-core-jvm:jar:2.13.4:compile
[INFO] |  +- net.mamoe:mirai-core-api-jvm:jar:2.13.4:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-reflect:jar:1.7.10:compile
[INFO] |  |  +- net.mamoe:mirai-console-compiler-annotations-jvm:jar:2.13.4:runtime
[INFO] |  |  \- org.jetbrains:annotations:jar:19.0.0:compile
[INFO] |  +- org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:jar:1.3.3:compile
[INFO] |  +- org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:jar:1.3.3:compile
[INFO] |  +- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:jar:1.6.4:compile
[INFO] |  +- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.7.10:compile
[INFO] |  +- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:jar:1.6.4:compile
[INFO] |  +- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.7.10:compile
[INFO] |  |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.7.10:compile
[INFO] |  +- org.bouncycastle:bcprov-jdk15on:jar:1.64:runtime
[INFO] |  +- me.him188:kotlin-jvm-blocking-bridge-runtime-jvm:jar:2.1.0-170.1:runtime
[INFO] |  +- me.him188:kotlin-dynamic-delegation-jvm:jar:0.3.0-170.1:runtime
[INFO] |  +- net.mamoe:mirai-core-utils-jvm:jar:2.13.4:runtime
[INFO] |  +- org.jetbrains.kotlinx:kotlinx-serialization-protobuf-jvm:jar:1.3.3:runtime
[INFO] |  +- org.jetbrains.kotlinx:atomicfu-jvm:jar:0.18.3:runtime
[INFO] |  \- io.netty:netty-all:jar:4.1.63.Final:runtime
[INFO] +- net.mamoe:mirai-logging-slf4j:jar:2.13.4:compile
[INFO] |  +- net.mamoe:mirai-logging-log4j2:jar:2.13.4:runtime
[INFO] |  \- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.2:runtime
[INFO] +- com.squareup.okhttp3:logging-interceptor:jar:4.9.0:compile
[INFO] +- com.squareup.retrofit2:converter-gson:jar:2.9.0:compile
[INFO] |  \- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] +- com.alibaba:fastjson:jar:2.0.21:compile
[INFO] |  \- com.alibaba.fastjson2:fastjson2-extension:jar:2.0.21:compile
[INFO] |     \- com.alibaba.fastjson2:fastjson2:jar:2.0.21:compile
[INFO] +- com.squareup.retrofit2:retrofit:jar:2.9.0:compile
[INFO] +- com.squareup.okhttp3:okhttp:jar:4.10.0:compile
[INFO] |  +- com.squareup.okio:okio-jvm:jar:3.0.0:compile
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.6.20:compile
[INFO] +- org.slf4j:slf4j-api:jar:2.0.5:compile
[INFO] +- org.slf4j:slf4j-reload4j:jar:2.0.5:compile
[INFO] |  \- ch.qos.reload4j:reload4j:jar:1.2.22:compile
[INFO] +- org.apache.logging.log4j:log4j-api:jar:2.19.0:compile
[INFO] \- org.apache.logging.log4j:log4j-core:jar:2.19.0:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27.608 s
[INFO] Finished at: 2023-01-22T20:37:49+08:00
[INFO] ------------------------------------------------------------------------
```

看依赖树没发现 有关kotlin的问题
可能是你打包没包含 `kotlin-lib` ？
或者你运行的环境里是 低版本的  `kotlin-lib`

另外看你的日志框架使用的是 `log4j` 
你应该使用 `mirai-logging-log4j2` 替换 `mirai-logging-slf4j`
