### ISSUE TITLE
更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。”

### ISSUE THREAD

**Issue by KrisTHL181** [mamoe/mirai#2453]
### 问题描述

更新完毕之后发生。尝试过删除bot文件夹的cache目录，无用。

### 复现

更新完毕之后发生。

### mirai-core 版本

2.13.4

### bot-protocol

ANDROID_PHONE

### 其他组件版本

Running MiraiConsole v2.13.4, built on 2023-01-21 21:19:40.
Frontend Terminal: version 2.13.4, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: MCL Addon v2.1.1

Object Pending Finalization Count: 0
                 committed |  init   |  used   |  max  
    Heap Memory:  100.0MB  | 186.0MB | 46.88MB | 2.89GB
Non-Heap Memory:  78.06MB  | 7.31MB  | 76.34MB |   -1  

### 系统日志

```text
kris@KrisTHL181:~/Mirai/MCL$ ~/java/jdk-17.0.5+8/bin/java -jar mcl.jar -u
  18:27:51 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  18:27:51 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.5 (arch: 64)
  18:27:51 [INFO] https://github.com/iTXTech/mirai-console-loader
  18:27:51 [INFO] This program is licensed under GNU AGPL v3
  18:27:52 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
 
MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  18:27:52 [INFO] Verifying "net.mamoe:mirai-console" v2.13.4
  18:27:53 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.4
  18:27:54 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.4
  18:27:54 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
2023-01-23 18:27:56 I/main: Starting mirai-console...
2023-01-23 18:27:56 I/main: 

==================================[ Mirai consosle 2.13.4 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-01-23 18:27:56 I/main: Backend: version 2.13.4, built on 2023-01-21 21:19:40.
2023-01-23 18:27:56 I/main: Frontend Terminal: version 2.13.4, provided by Mamoe Technologies
2023-01-23 18:27:56 I/main: Welcome to visit https://mirai.mamoe.net/
2023-01-23 18:27:56 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2023-01-23 18:27:56 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2023-01-23 18:27:56 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2023-01-23 18:27:57 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-01-23 18:27:57 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-01-23 18:27:57 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-01-23 18:27:57 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-01-23 18:27:57 I/main: 1 plugin(s) enabled.
2023-01-23 18:27:58 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2023-01-23 18:27:58 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2023-01-23 18:27:58 I/main: Auto-login 3581338560, protocol: ANDROID_PHONE, heartbeatStrategy: STAT_HB
2023-01-23 18:27:58 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2023-01-23 18:27:59 I/Bot.3581338560: Calculating type 2 PoW, it can take some time....
2023-01-23 18:27:59 I/Bot.3581338560: Got PoW result, cost: 151 ms
2023-01-23 18:28:11 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3581338560), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3581338560), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-01-23 18:28:11 I/Bot.3581338560: Bot cancelled: Bot closed
2023-01-23 18:28:11 I/main: mirai-console started successfully.
```

### 网络日志

```text
2023-01-23 18:27:58 V/Net 3581338560: No server list cached.
2023-01-23 18:27:58 I/Net 3581338560: ECDH key is invalid, start to fetch ecdh public key from server.
2023-01-23 18:27:59 I/Net 3581338560: Successfully fetched ecdh public key from server.
2023-01-23 18:27:59 V/Net 3581338560: Send: wtlogin.login(9:password-login)
2023-01-23 18:28:00 V/Net 3581338560: Recv: wtlogin.login
2023-01-23 18:28:11 V/Net 3581338560: Send: wtlogin.login(2:submit-slider)
2023-01-23 18:28:11 V/Net 3581338560: Recv: wtlogin.login
2023-01-23 18:28:11 W/Net 3581338560: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(3581338560), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3581338560), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	... 9 more

2023-01-23 18:28:11 W/Net 3581338560: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(3581338560), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=))
```

### 补充信息

尝试过使用其他ISSUE的解决方法，皆无用。

**Comment by zhaodice** [comment]
是的，部分用户出现了这种情况，目前不是太严重，感觉是协议没修干净

**Comment by KrisTHL181** [comment]
刚才协议换成ANDROID_WATCH就好了，重启一下又不行了。。。

**Comment by Mystery406** [comment]
+1，我是把device.json和cache文件夹都删了才可以登录

**Comment by KrisTHL181** [comment]
> +1，我是把device.json和cache文件夹都删了才可以登录

我删过了，没用（偶尔用ANDROID_WATCH能好，但是一般不行

**Comment by zhaodice** [comment]
连电脑QQ正常登陆都版本过低了，是大规模改协议吧可能

**Comment by amakerlife** [comment]
> +1，我是把device.json和cache文件夹都删了才可以登录

我也是这种情况，删了以后可以登录

**Comment by cssxsh** [comment]
> 连电脑QQ正常登陆都版本过低了，是大规模改协议吧可能

并不是改协议，而是大规模风控
`code=235` 和 `code=237` 都是风控的表现形式
频繁出现说明你这个号已经被半锁了，需要`身份验证/设备验证`

**Comment by zhaodice** [comment]
> > 连电脑QQ正常登陆都版本过低了，是大规模改协议吧可能
> 
> 并不是改协议，而是大规模风控 `code=235` 和 `code=237` 都是风控的表现形式 频繁出现说明你这个号已经被半锁了，需要`身份验证/设备验证`

电脑qq出现版本过低的情况后，我又重新更新了电脑qq，又可以登了，总感觉确有版本检测在里面。
我觉得风控的形式可能表现在多种因素：网络信用权重过低+帐号信用权重过低+版本号过低 = 拒绝登录

**Comment by soysong7788** [comment]
> > +1，我是把device.json和cache文件夹都删了才可以登录
> 
> 我也是这种情况，删了以后可以登录
我删了以后登录不了，只能进展到滑动验证，然后就报错了，无法进入验证码环节。QQ已经更新到最新版本，试过重新配置和更换路径，换QQ号，都不行。

**Comment by soysong7788** [comment]
> +1，我是把device.json和cache文件夹都删了才可以登录

我删了以后登录不了，只能进展到滑动验证，然后就报错了，无法进入验证码环节。QQ已经更新到最新版本，试过重新配置和更换路径，换QQ号，都不行。

**Comment by kartikzheng** [comment]
> > +1，我是把device.json和cache文件夹都删了才可以登录
> 
> 我删了以后登录不了，只能进展到滑动验证，然后就报错了，无法进入验证码环节。QQ已经更新到最新版本，试过重新配置和更换路径，换QQ号，都不行。

我的情况跟你一样，请问解决了吗？

**Comment by soysong7788** [comment]
还没有…是不是mirai的版本问题？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月29日 20:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) |

+1，我是把device.json和cache文件夹都删了才可以登录

我删了以后登录不了，只能进展到滑动验证，然后就报错了，无法进入验证码环节。QQ已经更新到最新版本，试过重新配置和更换路径，换QQ号，都不行。

我的情况跟你一样，请问解决了吗？

**Comment by kartikzheng** [comment]
> 还没有…是不是mirai的版本问题？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年01月29日 20:57 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) | +1，我是把device.json和cache文件夹都删了才可以登录 我删了以后登录不了，只能进展到滑动验证，然后就报错了，无法进入验证码环节。QQ已经更新到最新版本，试过重新配置和更换路径，换QQ号，都不行。 我的情况跟你一样，请问解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我在其他机器，相同mirai版本，不同QQ是正常登录的，就一个服务器上提示235和237错误。手机QQ和电脑端验证码后都可以登录，就mirai进入不了验证码验证，更换协议删除缓存均不行。

**Comment by soysong7788** [comment]
听你这么说，问题出在QQ上啊…我去重新注册个QQ再试一次



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月29日 21:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) |

还没有…是不是mirai的版本问题？
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年01月29日 20:57 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) | +1，我是把device.json和cache文件夹都删了才可以登录 我删了以后登录不了，只能进展到滑动验证，然后就报错了，无法进入验证码环节。QQ已经更新到最新版本，试过重新配置和更换路径，换QQ号，都不行。 我的情况跟你一样，请问解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>

我在其他机器，相同mirai版本，不同QQ是正常登录的，就一个服务器上提示235和237错误。手机QQ和电脑端验证码后都可以登录，就mirai进入不了验证码验证，更换协议删除缓存均不行。

**Comment by kartikzheng** [comment]
> 听你这么说，问题出在QQ上啊…我去重新注册个QQ再试一次
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年01月29日 21:05 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) | 还没有…是不是mirai的版本问题？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年01月29日 20:57 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) | +1，我是把device.json和cache文件夹都删了才可以登录 我删了以后登录不了，只能进展到滑动验证，然后就报错了，无法进入验证码环节。QQ已经更新到最新版本，试过重新配置和更换路径，换QQ号，都不行。 我的情况跟你一样，请问解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***> 我在其他机器，相同mirai版本，不同QQ是正常登录的，就一个服务器上提示235和237错误。手机QQ和电脑端验证码后都可以登录，就mirai进入不了验证码验证，更换协议删除缓存均不行。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

更换QQ是可以的，但我用于生产的话，不能老换QQ啊。 就是我这个QQ被限制了，估计得过几天看能不能解除。 我加了设备锁也无法进入验证码环节。

**Comment by soysong7788** [comment]
我明白你的意思了，那确实不能老是换。但QQ被锁可能问题不在我们这里…除非我们自己开发前端？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月29日 21:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) |

听你这么说，问题出在QQ上啊…我去重新注册个QQ再试一次
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年01月29日 21:05 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) | 还没有…是不是mirai的版本问题？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年01月29日 20:57 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) | +1，我是把device.json和cache文件夹都删了才可以登录 我删了以后登录不了，只能进展到滑动验证，然后就报错了，无法进入验证码环节。QQ已经更新到最新版本，试过重新配置和更换路径，换QQ号，都不行。 我的情况跟你一样，请问解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 我在其他机器，相同mirai版本，不同QQ是正常登录的，就一个服务器上提示235和237错误。手机QQ和电脑端验证码后都可以登录，就mirai进入不了验证码验证，更换协议删除缓存均不行。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

更换QQ是可以的，但我用于生产的话，不能老换QQ啊。 就是我这个QQ被限制了，估计得过几天看能不能解除。 我加了设备锁也无法进入验证码环节。

**Comment by kartikzheng** [comment]
> 我明白你的意思了，那确实不能老是换。但QQ被锁可能问题不在我们这里…除非我们自己开发前端？
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2023年01月29日 21:09 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) | 听你这么说，问题出在QQ上啊…我去重新注册个QQ再试一次 … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年01月29日 21:05 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) | 还没有…是不是mirai的版本问题？ … ---- 回复的原邮件 ---- | 发件人 | @.> | | 日期 | 2023年01月29日 20:57 | | 收件人 | @.> | | 抄送至 | @.>@.> | | 主题 | Re: [mamoe/mirai] 更新完之后，提示“当前QQ版本过低，请升级至最新版本后再登录。” (Issue #2453) | +1，我是把device.json和cache文件夹都删了才可以登录 我删了以后登录不了，只能进展到滑动验证，然后就报错了，无法进入验证码环节。QQ已经更新到最新版本，试过重新配置和更换路径，换QQ号，都不行。 我的情况跟你一样，请问解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 我在其他机器，相同mirai版本，不同QQ是正常登录的，就一个服务器上提示235和237错误。手机QQ和电脑端验证码后都可以登录，就mirai进入不了验证码验证，更换协议删除缓存均不行。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 更换QQ是可以的，但我用于生产的话，不能老换QQ啊。 就是我这个QQ被限制了，估计得过几天看能不能解除。 我加了设备锁也无法进入验证码环节。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

恩，你有条件的话，可以试下跟手机端热点网络一致试试

**Comment by zhaodice** [comment]
> 恩，你有条件的话，可以试下跟手机端热点网络一致试试

不用试了，我这边不少用户用的是自己的手机wifi/流量，都提示版本过低，换成miraiGo就可以登…(当然有一些人又可以正常登)

**Comment by kartikzheng** [comment]
> > 恩，你有条件的话，可以试下跟手机端热点网络一致试试
> 
> 不用试了，我这边不少用户用的是自己的手机wifi/流量，都提示版本过低，换成miraiGo就可以登…(当然有一些人又可以正常登)

期待官方修复bug

**Comment by cssxsh** [comment]
> > > 恩，你有条件的话，可以试下跟手机端热点网络一致试试
> > 
> > 
> > 不用试了，我这边不少用户用的是自己的手机wifi/流量，都提示版本过低，换成miraiGo就可以登…(当然有一些人又可以正常登)
> 
> 期待官方修复bug

然而这波并不是 bug, 235/237 都是疑似风险登录（盗号）才会出现，
但是现在腾讯加大的风控力度，

以至于，你用官方的客户端登录（我测试过安卓手机）一样会报网络不稳定
然后跳转到 `身份验证`, 身份验证和扫码登录本质一个类型，都是无密码(快捷)登录

结论 就是目前对于新号码/风控号码来说，最好使用 `ANDROID_WATCH` (风控较弱) , 碰碰运气

**Comment by kartikzheng** [comment]
> > > > 恩，你有条件的话，可以试下跟手机端热点网络一致试试
> > > 
> > > 
> > > 不用试了，我这边不少用户用的是自己的手机wifi/流量，都提示版本过低，换成miraiGo就可以登…(当然有一些人又可以正常登)
> > 
> > 
> > 期待官方修复bug
> 
> 然而这波并不是 bug, 235/237 都是疑似风险登录（盗号）才会出现， 但是现在腾讯加大的风控力度，
> 
> 以至于，你用官方的客户端登录（我测试过安卓手机）一样会报网络不稳定 然后跳转到 `身份验证`, 身份验证和扫码登录本质一个类型，都是无密码(快捷)登录
> 
> 结论 就是目前对于新号码/风控号码来说，最好使用 `ANDROID_WATCH` (风控较弱) , 碰碰运气

我用真实手机和电脑端，通过短信验证码都成功登陆了，如果mirai能出来短信验证码这一环节就好了，现在注册的新号是可以正常登陆。

**Comment by zhaodice** [comment]
> 结论 就是目前对于新号码/风控号码来说，最好使用 `ANDROID_WATCH` (风控较弱) , 碰碰运气

开发一下新的登陆方式吧，我记得，有个登陆模式是，只要纯输入手机号就可以开始登陆，短信验证码验证通过后会选择QQ并验证一下密码，就可以了，这种方式亲测在错误代码"网络不稳定"的情况下仍然可以登陆。

**Comment by SaithZhang** [comment]
昨天还能用，今天更新QQ后又不能用了

**Comment by 2efPer** [comment]
我也是这个问题，删除bots文件夹、彻底卸载mirai重装，全都一样。另外很多人说修改bot-protocol，我找了很久没找到这个配置项在哪里。如果果真是被风控了，难道必须要找个新QQ号了吗

**Comment by SaithZhang** [comment]
> 我也是这个问题，删除bots文件夹、彻底卸载mirai重装，全都一样。另外很多人说修改bot-protocol，我找了很久没找到这个配置项在哪里。如果果真是被风控了，难道必须要找个新QQ号了吗

![image](https://user-images.githubusercontent.com/22760210/218234290-01141141-3d65-4f21-b9bb-e196b13b1883.png)
在这个下面，不过我改了也没用 还是提示235，大号，小号都用不了了。

**Comment by zhendehanzi** [comment]
同样问题，应该是风控没跑了，我按照上述操作来了一遍，报错代码成功从235-->237

**Comment by zhaodice** [comment]
> 同样问题，应该是风控没跑了，我按照上述操作来了一遍，报错代码成功从235-->237

237的意思是登录太频繁（无论登录是否成功都算在次数里）

**Comment by dragon0629** [comment]
> > 连电脑QQ正常登陆都版本过低了，是大规模改协议吧可能
> 
> 并不是改协议，而是大规模风控 `code=235` 和 `code=237` 都是风控的表现形式 频繁出现说明你这个号已经被半锁了，需要`身份验证/设备验证`

主要在MIRAIGO上就可以正常登录……这真的有点说不通，感觉还是协议问题，有一些没处理到
话说mirai和GO不是一样的内核啊？我一直以为GO是在mirai基础上开发的。

**Comment by cssxsh** [comment]
> > > 连电脑QQ正常登陆都版本过低了，是大规模改协议吧可能
> > 
> > 
> > 并不是改协议，而是大规模风控 `code=235` 和 `code=237` 都是风控的表现形式 频繁出现说明你这个号已经被半锁了，需要`身份验证/设备验证`
> 
> 主要在MIRAIGO上就可以正常登录……这真的有点说不通，感觉还是协议问题，有一些没处理到 话说mirai和GO不是一样的内核啊？我一直以为GO是在mirai基础上开发的。

MIRAIGO 的 扫码登录就是 `身份验证/设备验证` 的一种形式

**Comment by dragon0629** [comment]
> > > > 连电脑QQ正常登陆都版本过低了，是大规模改协议吧可能
> > > 
> > > 
> > > 并不是改协议，而是大规模风控 `code=235` 和 `code=237` 都是风控的表现形式 频繁出现说明你这个号已经被半锁了，需要`身份验证/设备验证`
> > 
> > 
> > 主要在MIRAIGO上就可以正常登录……这真的有点说不通，感觉还是协议问题，有一些没处理到 话说mirai和GO不是一样的内核啊？我一直以为GO是在mirai基础上开发的。
> 
> MIRAIGO 的 扫码登录就是 `身份验证/设备验证` 的一种形式

但是他可以登录上去呀，同一个Q号
GO扫完码登录就上去了可以开始处理群消息和事件了，不会报235啊
mirai 扫完码或者过一下滑块就报个235然后就进行不下去了。

**Comment by cssxsh** [comment]
> 块就报个235然后就进行不下去了

MIRAIGO 的 扫码登录就是 `身份验证/设备验证`, 不是密码验证

Mirai 实现的是 `密码验证` 中间穿插的 滑块，扫码，短信都是腾讯服务器发过来的要求

**Comment by dragon0629** [comment]
> > 块就报个235然后就进行不下去了
> 
> MIRAIGO 的 扫码登录就是 `身份验证/设备验证`, 不是密码验证
> 
> Mirai 实现的是 `密码验证` 中间穿插的 滑块，扫码，短信都是腾讯服务器发过来的要求

大概明白了`-`
所以可以认为是MIRAI实现登录走了个长征路线，随便哪边出现了敌人都会整体上受到阻拦
GO直接挖了个地道
所以MIRAI其实最好也需要这个地道？XD
然后目前缺地道工程师来实现。

**Comment by cssxsh** [comment]
> > > 块就报个235然后就进行不下去了
> > 
> > 
> > MIRAIGO 的 扫码登录就是 `身份验证/设备验证`, 不是密码验证
> > Mirai 实现的是 `密码验证` 中间穿插的 滑块，扫码，短信都是腾讯服务器发过来的要求
> 
> 大概明白了`-` 所以可以认为是MIRAI实现登录走了个长征路线，随便哪边出现了敌人都会整体上受到阻拦 GO直接挖了个地道 所以MIRAI其实最好也需要这个地道？XD 然后目前缺地道工程师来实现。

`code=235, title=温馨提示, message=当前QQ版本 过低`
本质上就和 `当前QQ版本不支持，请在手机QQ上查看` 的那种消息一样
是一个跳转提示，跳转到 `身份验证/设备验证` 即扫码登录


本质上也是QQ为了 提高手机客户端使用率的搞事操作，
这样处理就能保证QQ用户必然是 手机客户端用户
也就必然是 `小`世界 之类的乱七八糟东西的用户

**Comment by dragon0629** [comment]
> > > > 块就报个235然后就进行不下去了
> > > 
> > > 
> > > MIRAIGO 的 扫码登录就是 `身份验证/设备验证`, 不是密码验证
> > > Mirai 实现的是 `密码验证` 中间穿插的 滑块，扫码，短信都是腾讯服务器发过来的要求
> > 
> > 
> > 大概明白了`-` 所以可以认为是MIRAI实现登录走了个长征路线，随便哪边出现了敌人都会整体上受到阻拦 GO直接挖了个地道 所以MIRAI其实最好也需要这个地道？XD 然后目前缺地道工程师来实现。
> 
> `code=235, title=温馨提示, message=当前QQ版本 过低` 本质上就和 `当前QQ版本不支持，请在手机QQ上查看` 的那种消息一样 是一个跳转提示，跳转到 `身份验证/设备验证` 即扫码登录
> 
> 本质上也是QQ为了 提高手机客户端使用率的搞事操作， 这样处理就能保证QQ用户必然是 手机客户端用户 也就必然是 `小`世界 之类的乱七八糟东西的用户

感谢解答
“是一个跳转提示，跳转到 身份验证/设备验证 即扫码登录”
但是似乎目前大家的困扰就是 "并没有跳转到 身份验证/设备扫码" ，而是直接STOP了
如果能跳转到  身份验证/设备扫码 的话，是不是就没有这个问题了 0_0
现在就是验证和设备扫码的机会也没有，直接停了。所以大家一旦遇到这个就无法完成登录，因为没有支持身份验证和设备扫码。

**Comment by zhengpeirong** [comment]
![image](https://user-images.githubusercontent.com/46894344/219290788-1b41942b-d76e-4112-afd1-b405c12783c9.png)
改成ANDROID_WATCH
测试发现有用。

**Comment by yulangde** [comment]
一直在使用的，今天晚上突然出现这个报错：
(bot=Bot(***), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
更换bot之后仍然报错：
(bot=Bot(***), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
