### ISSUE TITLE
Failed to initialize module `java.desktop`

### ISSUE THREAD

**Issue by tjc0726** [mamoe/mirai#2459]
### 问题描述

无图形界面运行login时报
W/WindowHelperJvm: Failed to initialize module `java.desktop`
好像不影响使用，但是想请问下有什么办法消除报错吗

之前版本好像会提示如下，但是现在版本无提示

> Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
> Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.

### 复现

./mcl
login xxx xxx

### mirai-core 版本

2.13.4

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2023-01-25 21:00:34 W/WindowHelperJvm: Failed to initialize module `java.desktop`
java.lang.UnsatisfiedLinkError: /home/ubuntu/java/lib/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
	at java.base/java.lang.System.loadLibrary(Unknown Source)
	at java.desktop/java.awt.Toolkit$2.run(Unknown Source)
	at java.desktop/java.awt.Toolkit$2.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.desktop/java.awt.Toolkit.loadLibraries(Unknown Source)
	at java.desktop/java.awt.Toolkit.initStatic(Unknown Source)
	at java.desktop/java.awt.Toolkit.<clinit>(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at net.mamoe.mirai.utils.WindowHelperJvm.<clinit>(SwingSolver.kt:247)
	at net.mamoe.mirai.utils.PlatformLoginSolverImplementations$default$2.invoke(LoginSolver.jvm.kt:34)
	at net.mamoe.mirai.utils.PlatformLoginSolverImplementations$default$2.invoke(LoginSolver.jvm.kt:33)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.utils.PlatformLoginSolverImplementations.getDefault(LoginSolver.jvm.kt:33)
	at net.mamoe.mirai.utils.LoginSolver.<clinit>(LoginSolver.kt:135)
	at net.mamoe.mirai.utils.BotConfiguration.<init>(BotConfiguration.kt:222)
	at net.mamoe.mirai.utils.BotConfiguration.<clinit>(BotConfiguration.kt:626)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:196)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:180)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$doStart$10$1.invokeSuspend(MiraiConsoleImplementationBridge.kt:389)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:346)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:196)
	at org.itxtech.mcl.Loader.main(Loader.java:84)
```

**Comment by cssxsh** [comment]
> 可添加 JVM 属性 mirai.no-desktop 以关闭

?

**Comment by tjc0726** [comment]
> > 可添加 JVM 属性 mirai.no-desktop 以关闭
> 
> ?

现在版本没有这个提示了是为啥
这个提示是我翻看到之前别的issue的日志中有才知道

**Comment by Him188** [comment]
2.14.0-RC 已经去除了这个，可以试试
