### ISSUE TITLE
群临时会话无法发送消息

### ISSUE THREAD

**Issue by XeroAlpha** [mamoe/mirai#246]
## 问题
群临时会话无法发送消息
代码：
```
    bot.subscribeTempMessages {
        always {
            if (group.id == ca_talk_group) {
                message.getOrNull(PlainText.Key)?.contentToString()?.let {
                    talkGroupRespond(it)?.let { reply(it) }
                }
            }
        }
    }
```
talkGroupRespond:
```
fun talkGroupRespond(req : String) : String? {
    return when {
        req == "菜单" -> {
            "目前没有功能"
        }
        else -> null
    }
}
```
错误信息（QQ号用qqqqqqq代替）：
```
Network(qqqqqqq) 18:18:42 : Send done: MessageSvc.PbSendMsg
Network(qqqqqqq) 18:18:42 : Packet: MessageSvc.PbSendMsg.Response.Failed(resultType=102, errorCode=0, errorMessage=发送失败，您与对方不在共同的群，可尝试加对方为好友后聊天)
Bot(qqqqqqq) 18:18:42 : An exception was thrown under a coroutine of Bot
java.lang.IllegalStateException: send message failed
	at net.mamoe.mirai.qqandroid.contact.MemberImpl.sendMessageImpl(MemberImpl.kt:80)
	at net.mamoe.mirai.qqandroid.contact.MemberImpl$sendMessageImpl$1.invokeSuspend(MemberImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

## 如何复现
1. 让机器人加个群
2. 通过群临时会话私聊机器人“菜单”

**Comment by Him188** [comment]
考虑到一些安全因素, 目前不允许主动发起临时会话. 需要由对方向机器人发送一句话.

**Comment by Him188** [comment]
... 发现这就是被动

**Comment by Chenwe-i-lin** [comment]
> ... 发现这就是被动

草

**Comment by ryoii** [comment]
这个问题可能是，临时会话是通过会话列表中向bot发起的，因此没有具体的group值。
或者曾经发起过临时会话，但bot已不在群中。而后再会话列表中向bot发起临时会话。
请描述一下具体情况 @XeroAlpha

**Comment by Him188** [comment]
请问能否透露群号码？可将个位十位百位都修改（而不改变其他数字）后发出来。

**Comment by XeroAlpha** [comment]
> 这个问题可能是，临时会话是通过会话列表中向bot发起的，因此没有具体的group值。
> 或者曾经发起过临时会话，但bot已不在群中。而后再会话列表中向bot发起临时会话。
> 请描述一下具体情况 @XeroAlpha

应当是第一种情况。

**Comment by Chenwe-i-lin** [comment]
> 这个问题可能是，临时会话是通过会话列表中向bot发起的，因此没有具体的group值。
> 或者曾经发起过临时会话，但bot已不在群中。而后再会话列表中向bot发起临时会话。
> 请描述一下具体情况 @XeroAlpha

建议针对后一种情况进行预判断
