### ISSUE TITLE
paper 1.19.3 登入时报 Exception in decoding packet.

### ISSUE THREAD

**Issue by AngelLuoLi** [mamoe/mirai#2466]
### 问题描述

[14:52:11 INFO]: [MiraiMC] 登录新的机器人账号: 3253144522, 协议: ANDROID_PHONE
[14:52:11 INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[14:52:11 INFO]: [MiraiMC] Successfully fetched ecdh public key from server.
[14:52:12 ERROR]: [MiraiMC] Exception in decoding packet.
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null
	at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:52:12 WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null
	at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:52:12 WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException)
[14:52:12 WARN]: [MiraiMC] 登录机器人时出现异常，原因: null
[14:52:12 INFO]: [MiraiMC] Bot cancelled: Bot closed

### 复现

安装教程进行登入

### mirai-core 版本

1.7.1

### bot-protocol

ANDROID_PHONE

**Comment by AngelLuoLi** [comment]
发错了。。
