### ISSUE TITLE
在 GroupImpl 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by GBLW22** [mamoe/mirai#2467]
### 问题描述

启动mirai后，bot成功启动，但是报错如下信息。其他功能一切正常，只对这个群聊信息无法监听。

### 复现

开启后自动报错

### mirai-core 版本

2.13.4

### bot-protocol

IPAD

### 其他组件版本

Running MiraiConsole v2.13.4, built on 2023-01-21 21:19:40.
Frontend Terminal: version 2.13.4, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: AntiRecall v1.0.3, Chat Command v0.5.0, net.mamoe.mirai-api-http v2.6.2, mirai-device-generator v1.1.3, mirai-slf4j-bridge v1.0.0, SimpleWelcome v1.1.0, Soyuz v1.0.0, MCL Addon v2.1.1, mirai-hibernate-plugin v2.5.1, HuYanSession v2.3.1

Object Pending Finalization Count: 0
                 committed |  init   |   used   |  max
    Heap Memory:  492.0MB  | 512.0MB | 82.26MB  | 7.96GB
Non-Heap Memory:  140.0MB  | 7.31MB  | 136.46MB |   -1

### 系统日志

```text
2023-01-31 18:12:21 I/Bot.2586724374: Login successful
2023-01-31 18:12:21 I/Bot.2586724374: Saved account secrets to local cache for fast login.
2023-01-31 18:12:21 I/Bot.2586724374: Login successful.
2023-01-31 18:12:23 E/Group: ContextualBugReportException(message=在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 1018550614
groupUin: 1018550614
membersCount: 34
botId: 2586724374
owner: null, cause=null)
ContextualBugReportException(message=在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 1018550614
groupUin: 1018550614
membersCount: 34
botId: 2586724374
owner: null, cause=null)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
        at net.mamoe.mirai.internal.contact.GroupImplKt.GroupImpl(GroupImpl.kt:102)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.addGroupToBot(ContactUpdater.kt:252)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.access$addGroupToBot(ContactUpdater.kt:73)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl$addGroupToBot$1.invokeSuspend(ContactUpdater.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-01-31 18:12:24 V/Bot.2586724374: Event: BotOnlineEvent(bot=Bot(2586724374))
2023-01-31 18:12:24 I/Bot.2586724374: Bot login successful.
2023-01-31 18:12:24 I/main: mirai-console started successfully.
```

### 补充信息

重启后恢复正常，对该群一切功能正常运行。机器人不是管理员或者群主，并且已入群半年以上，没有被禁言或者踢出

**Comment by GBLW22** [comment]
补充：重启后恢复正常，对该群一切功能正常运行。机器人不是管理员或者群主，并且已入群半年以上，没有被禁言或者踢出

**Comment by MrY-Cat** [comment]
同名issue指路： #1977 #2333

**Comment by Him188** [comment]
#1977
