### ISSUE TITLE
MockImage 无法在 SingleMessage scope 下反序列化

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#2472]
kotlinx.serialization.SerializationException: Class 'MockImage' is not registered for polymorphic serialization in the scope of 'SingleMessage'.

codes:
```kotlin
@OptIn(ExperimentalSerializationApi::class)
val json by lazy {
    Json {
        serializersModule = MessageSerializers.serializersModule
        ignoreUnknownKeys = true
        encodeDefaults = true
        explicitNulls = false
    }
}

...

// event
this@OperationTest.javaClass.getResourceAsStream("/img.png")!!.use { res ->
            res.toExternalResource().use {
                val img = bot.uploadMockImage(it)
                member.says(buildMessageChain {
                    add("imgUploaded")
                    add(img)
                })
            }
        }

...

//  Packet.kt:872
message = json.encodeToString(event.message.let {
                    if (it.contains(MessageSource)) it.drop(1)
                    else it
                })
```

logs
```
2023-01-17 19:02:22 W/Bot 852401814784986658: An exception occurred when processing event. Subscriber scope: '<unnamed>'. Broadcaster scope: 'EventDispatcher'
kotlinx.serialization.SerializationException: Class 'MockImage' is not registered for polymorphic serialization in the scope of 'SingleMessage'.
Mark the base class as 'sealed' or register the serializer explicitly.
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:113)
	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:109)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:224)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
	at kotlinx.serialization.internal.CollectionLikeSerializer.serialize(CollectionSerializers.kt:69)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:219)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:85)
	at tech.eritquearcus.miraicp.shared.Packets$Outgoing$MessageEventData.<init>(Packet.kt:872)
```
![image](https://user-images.githubusercontent.com/35139537/213039422-5ff7c80a-7a5d-45f3-923f-31d13630b135.png)
```
[OnlineMsgSrcFromGroup#2113891589 {
            bot=<!>
            ids=[0xA1F6177D(-1577707651)]
            internalIds=[0x1C894554(478758228)]
            originalMessage=[imgUploaded, MockImage#1235381529 {
                    _stringValue=Lazy value not initialized yet.
                    imageId={BCD49145-8622-AD80-04D2-930CEF55E8E1}.png
                    imageType=ImageType#259630944 {
                            formatName=gif
                    }
                    urlPath=http://127.0.0.1:13057/images/BCD49145-8622-AD80-04D2-930CEF55E8E1
            }]
            sender=<!>
            time=0x63C73BB1(1674001329)
    }, imgUploaded, MockImage#1235381529 {
            _stringValue=Lazy value not initialized yet.
            imageId={BCD49145-8622-AD80-04D2-930CEF55E8E1}.png
            imageType=ImageType#259630944 {
                    formatName=gif
            }
            urlPath=http://127.0.0.1:13057/images/BCD49145-8622-AD80-04D2-930CEF55E8E1
    }]
```

_Originally posted by @Nambers in https://github.com/mamoe/mirai/issues/2414#issuecomment-1386253123_

**Comment by Karlatemp** [comment]
1ea68d82

> PR 已经跑通了，我也不知道为啥会爆这个错，当时也忘记确定版本了，可能是没 include 或者因为别的原因
> 总之 PR 无此方面的修改也跑通了
