### ISSUE TITLE
在 MultiMsg.ApplyDown 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by Steven-WZH** [mamoe/mirai#2481]
### 问题描述

net.mamoe.mirai.internal.message.ContextualBugReportException: 在 MultiMsg.ApplyDown 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   Decode failure result=192 调试信息: MultiMsgApplyDownRsp#1332743392 {
            bytesDownIpV6=[]
            msgResid=btZUudYEc+W87HTEzh9ziBRgWHZt4jezotO5kVa26Hpc7se6cqTIbh/bmCodW4DY
            result=0x000000C0(192)
            uint32DownIp=[]
            uint32DownPort=[]
            uint32DownV6Port=[]
    }
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at net.mamoe.mirai.internal.network.protocol.packet.chat.MultiMsg$ApplyDown.decode(MultiMsg.kt:145) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[mirai-core-all-2.14.0.jar:2.14.0]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.82.Final.jar:4.1.82.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 复现

qq服务器炸了之后再登陆

### mirai-core 版本

2.14

### bot-protocol

ANDROID_PHONE

**Comment by Karlatemp** [comment]
在 QQ Service 中断期间的任何报错均不属于 mirai 问题, 请明天重启后重试
