### ISSUE TITLE
今天QQ崩溃后登陆报错Failed to decode BdhSession

### ISSUE THREAD

**Issue by HYY1116** [mamoe/mirai#2482]
### 问题描述

今天QQ服务大面积出现问题后再通过登陆QQ，在登陆成功后一段时间（~10s）会出现报错Failed to decode BdhSession.

### 复现

今天QQ服务大面积出现问题后再通过登陆QQ，在登陆成功后一段时间（~10s）会出现报错Failed to decode BdhSession.
对于接收消息貌似无影响，但是会导致无法发送消息

### mirai-core 版本

2.13.4

### bot-protocol

ANDROID_PHONE

### 其他组件版本

net.mamoe.mirai-api-http v2.6.2
MCL Addon v2.1.1

### 系统日志

```text
==================================[ Mirai consosle 2.13.4 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-02-10 11:34:21 I/main: Backend: version 2.13.4, built on 2023-01-21 21:19:40.
2023-02-10 11:34:21 I/main: Frontend Terminal: version 2.13.4, provided by Mamoe Technologies
2023-02-10 11:34:21 I/main: Welcome to visit https://mirai.mamoe.net/
2023-02-10 11:34:21 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2023-02-10 11:34:21 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2023-02-10 11:34:21 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2023-02-10 11:34:22 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.6.2
2023-02-10 11:34:22 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-02-10 11:34:23 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-02-10 11:34:23 I/Mirai HTTP API: ********************************************************
2023-02-10 11:34:23 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2023-02-10 11:34:23 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2023-02-10 11:34:23 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2023-02-10 11:34:23 I/http adapter: >>> [http adapter] is listening at http://localhost:8080
2023-02-10 11:34:23 I/ws adapter: >>> [ws adapter] is listening at ws://localhost:8080
2023-02-10 11:34:23 I/Mirai HTTP API: Http api server is running with verifyKey: hyy20001116
2023-02-10 11:34:23 I/Mirai HTTP API: adaptors: [http,ws]
2023-02-10 11:34:23 I/Mirai HTTP API: ********************************************************
2023-02-10 11:34:23 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-02-10 11:34:23 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-02-10 11:34:23 I/main: 2 plugin(s) enabled.
2023-02-10 11:34:23 I/main: mirai-console started successfully.
2023-02-10 11:34:31 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2023-02-10 11:34:32 I/Bot.2373301339: Login successful
2023-02-10 11:34:32 I/Bot.2373301339: Saved account secrets to local cache for fast login.
2023-02-10 11:34:32 I/Bot.2373301339: Login successful.
2023-02-10 11:34:33 V/Bot.2373301339: Event: BotOnlineEvent(bot=Bot(2373301339))
2023-02-10 11:34:33 I/Bot.2373301339: Bot login successful.
2023-02-10 11:34:40 E/Bot.2373301339: java.lang.IllegalStateException: Failed to decode BdhSession
java.lang.IllegalStateException: Failed to decode BdhSession
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle$handleConfigPush(ConfigPushSvc.kt:127)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle(ConfigPushSvc.kt:165)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle(ConfigPushSvc.kt:40)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:108)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:106)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:160)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: msgSubcmd0x501RspBody not found
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle$handleConfigPush(ConfigPushSvc.kt:107)
	... 37 more

2023-02-10 11:35:06 I/Bot.2373301339: Loaded account secrets from local cache.
2023-02-10 11:35:06 I/Bot.2373301339: Saved account secrets to local cache for fast login.
2023-02-10 11:35:06 I/Bot.2373301339: Login successful.
2023-02-10 11:35:06 V/Bot.2373301339: Event: BotOnlineEvent(bot=Bot(2373301339))
2023-02-10 11:35:06 I/Bot.2373301339: Bot login successful.
2023-02-10 11:35:12 V/Bot.2373301339: Event: BotOfflineEvent.Dropped(bot=Bot(2373301339), cause=NettyChannelException(message=null, cause=null), reconnect=true)
2023-02-10 11:35:12 W/Bot.2373301339: Connection lost, reconnecting... (NettyChannelException(message=null, cause=null))
2023-02-10 11:35:12 W/Bot.2373301339: Connection lost, reconnecting... (NettyChannelException(message=null, cause=null))
2023-02-10 11:35:12 I/Bot.2373301339: Reconnected successfully in 0.0s.
2023-02-10 11:35:12 I/Bot.2373301339: Saved account secrets to local cache for fast login.
2023-02-10 11:35:12 I/Bot.2373301339: Login successful.
2023-02-10 11:35:12 V/Bot.2373301339: Event: BotOnlineEvent(bot=Bot(2373301339))
2023-02-10 11:35:12 V/Bot.2373301339: Event: BotReloginEvent(bot=Bot(2373301339), cause=null)
2023-02-10 11:35:12 I/Bot.2373301339: Reconnected successfully in 0.272s.
2023-02-10 11:35:18 V/Bot.2373301339: Event: BotOfflineEvent.Dropped(bot=Bot(2373301339), cause=NettyChannelException(message=null, cause=null), reconnect=true)
2023-02-10 11:35:18 W/Bot.2373301339: Connection lost, reconnecting... (NettyChannelException(message=null, cause=null))
2023-02-10 11:35:18 W/Bot.2373301339: Connection lost, reconnecting... (NettyChannelException(message=null, cause=null))
2023-02-10 11:35:18 I/Bot.2373301339: Reconnected successfully in 0.006s.
2023-02-10 11:35:18 I/Bot.2373301339: Saved account secrets to local cache for fast login.
2023-02-10 11:35:18 I/Bot.2373301339: Login successful.
2023-02-10 11:35:18 V/Bot.2373301339: Event: BotOnlineEvent(bot=Bot(2373301339))
2023-02-10 11:35:18 V/Bot.2373301339: Event: BotReloginEvent(bot=Bot(2373301339), cause=null)
2023-02-10 11:35:18 I/Bot.2373301339: Reconnected successfully in 0.199s.
2023-02-10 11:35:20 E/Bot.2373301339: java.lang.IllegalStateException: Failed to decode BdhSession
java.lang.IllegalStateException: Failed to decode BdhSession
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle$handleConfigPush(ConfigPushSvc.kt:127)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle(ConfigPushSvc.kt:165)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle(ConfigPushSvc.kt:40)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:108)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:106)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:160)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: msgSubcmd0x501RspBody not found
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle$handleConfigPush(ConfigPushSvc.kt:107)
	... 37 more

2023-02-10 11:35:26 E/Bot.2373301339: java.lang.IllegalStateException: Failed to decode BdhSession
java.lang.IllegalStateException: Failed to decode BdhSession
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle$handleConfigPush(ConfigPushSvc.kt:127)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle(ConfigPushSvc.kt:165)
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle(ConfigPushSvc.kt:40)
	at net.mamoe.mirai.internal.network.components.CallPacketFactoryPacketHandler.handlePacket(PacketHandler.kt:105)
	at net.mamoe.mirai.internal.network.components.PacketHandlerChain.handlePacket(PacketHandler.kt:42)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invokeSuspend(NetworkHandlerSupport.kt:108)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport$collectReceived$3.invoke(NetworkHandlerSupport.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:106)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:160)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: msgSubcmd0x501RspBody not found
	at net.mamoe.mirai.internal.network.protocol.packet.login.ConfigPushSvc$PushReq.handle$handleConfigPush(ConfigPushSvc.kt:107)
	... 37 more

2023-02-10 11:35:27 W/console: 未知指令: /log, 输入 ? 获取帮助
2023-02-10 11:35:34 W/console: 未知指令: /quit, 输入 ? 获取帮助
2023-02-10 11:35:36 V/Bot.2373301339: Event: BotOfflineEvent.Active(bot=Bot(2373301339), cause=null, reconnect=false)
2023-02-10 11:35:36 I/Bot.2373301339: Bot is closed manually
2023-02-10 11:35:36 I/Bot.2373301339: Bot cancelled: Job was cancelled
```

**Comment by HYY1116** [comment]
同时登陆也会出现
Login failed: 拒绝连接: msfwifi.3g.qq.com/58.212.179.125:8080
2023-02-10 11:44:39 E/console: io.netty.channel.AbstractChannel$AnnotatedConnectException: 拒绝连接: msfwifi.3g.qq.com/58.212.179.125:8080
io.netty.channel.AbstractChannel$AnnotatedConnectException: 拒绝连接: msfwifi.3g.qq.com/58.212.179.125:8080
        Suppressed: NettyChannelException(message=null, cause=io.netty.channel.AbstractChannel$AnnotatedConnectException: 拒绝连接: msfwifi.3g.qq.com/58.212.179.125:8080)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.createConnection$suspendImpl(NettyNetworkHandler.kt:116)
                at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$createConnection$1.invokeSuspend(NettyNetworkHandler.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Caused by: [CIRCULAR REFERENCE: io.netty.channel.AbstractChannel$AnnotatedConnectException: 拒绝连接: msfwifi.3g.qq.com/58.212.179.125:8080]
Caused by: java.net.ConnectException: 拒绝连接
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:707)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)

不清楚是不是我的网络原因，这个问题随机出现，而且已经出现两次不同ip

**Comment by dragon0629** [comment]
+1
2023-02-10 11:34:40 E/Bot.2373301339: java.lang.IllegalStateException: Failed to decode BdhSession
java.lang.IllegalStateException: Failed to decode BdhSession

**Comment by Williamsunsir** [comment]
+1

**Comment by HYY1116** [comment]
目前好像好了？不再出现类似报错

**Comment by Williamsunsir** [comment]
看样子现在好了

**Comment by Karlatemp** [comment]
在 QQ Service 中断期间的任何报错均不属于 mirai 问题, 请明天重启后重试
