### ISSUE TITLE
net.mamoe.mirai.internal.message.ContextualBugReportException: 在 GroupImpl 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by 4o4E** [mamoe/mirai#2486]
### 问题描述

在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai

### 复现

登陆时出现，bot未启用好友列表和群成员列表的缓存

bot是群员身份，没有刚刚加入或离开这个群（很早就加入了群）

### mirai-core 版本

2.14.0

### bot-protocol

IPAD

### 系统日志

```text
[15:24:40.534] [net.mamoe.mirai.internal.contact.GroupImpl/ERROR] null
net.mamoe.mirai.internal.message.ContextualBugReportException: 在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 5***3
groupUin: 5***3
membersCount: 0
botId: 2***0
owner: null
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26) ~[mirai-core-jvm-2.14.0.jar:2.14.0]
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20) ~[mirai-core-jvm-2.14.0.jar:2.14.0]
	at net.mamoe.mirai.internal.contact.GroupImplKt.GroupImpl(GroupImpl.kt:105) ~[mirai-core-jvm-2.14.0.jar:2.14.0]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.addGroupToBot(ContactUpdater.kt:252) ~[mirai-core-jvm-2.14.0.jar:2.14.0]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.access$addGroupToBot(ContactUpdater.kt:73) ~[mirai-core-jvm-2.14.0.jar:2.14.0]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl$addGroupToBot$1.invokeSuspend(ContactUpdater.kt) ~[mirai-core-jvm-2.14.0.jar:2.14.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.22.jar:1.7.22-release-288(1.7.22)]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.7.22.jar:1.7.22-release-288(1.7.22)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
```

**Comment by Karlatemp** [comment]
在 QQ Service 中断期间的任何报错均不属于 mirai 问题, 请明天重启后重试
