### ISSUE TITLE
登录报错，提示”当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录"

### ISSUE THREAD

**Issue by WutzuBert** [mamoe/mirai#2496]
### 问题描述

当我尝试在Mirai-Console登录Bot时，完成滑块验证后出现登陆失败“当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录”

### 复现

在Mirai-console登录账号（版本2.14.0-RC）

### mirai-core 版本

2.14.0-RC

### bot-protocol

IPAD

### 其他组件版本

Running MiraiConsole v2.14.0-RC, built on 2023-01-18 20:32:50.
Frontend Terminal: version 2.14.0-RC, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: top.berthua.plugin(crashed_enable_error) v1.2.9-SNAPSHOT, MCL Addon v1.2.2

Object Pending Finalization Count: 0
                 committed |  init  |  used   |   max  
    Heap Memory:  77.0MB   | 62.0MB | 50.33MB | 982.0MB
Non-Heap Memory:  66.5MB   | 7.31MB | 64.14MB |   -1   

### 系统日志

```text
13:18:31 [INFO] iTXTech Mirai Console Loader version 1.2.2-60c67fb
  13:18:31 [INFO] https://github.com/iTXTech/mirai-console-loader
  13:18:31 [INFO] This program is licensed under GNU AGPL v3
  13:18:31 [INFO] Fetching Mirai Console Loader Announcement...
  13:18:32 [INFO] Mirai Console Loader Announcement:
[WARNING] 您目前使用的仓库源 gitee 将不再受到支持
[WARNING] 我们已经停止对 gitee 源的同步更新
[WARNING] 如果您依然使用此源, 则不会再受到我们的更新推送
[WARNING]
[WARNING] 详见
[WARNING] `- https://mirai.mamoe.net/topic/1084/
[WARNING] `- https://github.com/project-mirai/mirai-repo-mirror
[WARNING]
[WARNING]                 Mamoe Technologies & iTX Technologies
[WARNING]                                            03/30/2022


  13:18:32 [INFO] Verifying "net.mamoe:mirai-console" v2.14.0-RC
  13:18:32 [WARN] Package "net.mamoe:mirai-console" has newer version "2.11.0-M1"
  13:18:32 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.14.0-RC
  13:18:32 [WARN] Package "net.mamoe:mirai-console-terminal" has newer version "2.11.0-M1"
  13:18:32 [INFO] Verifying "net.mamoe:mirai-core-all" v2.14.0-RC
  13:18:33 [WARN] Package "net.mamoe:mirai-core-all" has newer version "2.11.0-M1"
  13:18:33 [INFO] Verifying "org.itxtech:mcl-addon" v1.2.2
  13:18:33 [WARN] Run ./mcl -u to update packages.
2023-02-12 13:18:34 I/main: Starting mirai-console...
2023-02-12 13:18:34 I/main: 

=================================[ Mirai consosle 2.14.0-RC ]=================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-02-12 13:18:34 I/main: Backend: version 2.14.0-RC, built on 2023-01-18 20:32:50.
2023-02-12 13:18:34 I/main: Frontend Terminal: version 2.14.0-RC, provided by Mamoe Technologies
2023-02-12 13:18:34 I/main: Welcome to visit https://mirai.mamoe.net/
2023-02-12 13:18:35 I/plugin: Successfully loaded plugin top.berthua.plugin v1.2.9-SNAPSHOT
2023-02-12 13:18:35 I/plugin: Successfully loaded plugin MCL Addon v1.2.2
2023-02-12 13:18:35 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-02-12 13:18:35 I/top.berthua.plugin: Plugin loaded!
2023-02-12 13:18:36 I/Net 1243733821: ECDH key is invalid, start to fetch ecdh public key from server.
2023-02-12 13:18:36 I/Net 1243733821: Successfully fetched ecdh public key from server.
2023-02-12 13:18:36 I/Bot 1243733821: [SliderCaptcha] 需要滑动验证码, 请按照以下链接的步骤完成滑动验证码, 然后输入获取到的 ticket
2023-02-12 13:18:36 I/Bot 1243733821: [SliderCaptcha] Slider captcha required. Please solve the captcha with following link. Type ticket here after completion.
2023-02-12 13:18:36 I/Bot 1243733821: [SliderCaptcha] @see https://github.com/project-mirai/mirai-login-solver-selenium
2023-02-12 13:18:36 I/Bot 1243733821: [SliderCaptcha] @see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
2023-02-12 13:18:36 I/Bot 1243733821: [SliderCaptcha] 或者输入 TxCaptchaHelper 来使用 TxCaptchaHelper 完成滑动验证码
2023-02-12 13:18:36 I/Bot 1243733821: [SliderCaptcha] Or type `TxCaptchaHelper` to resolve slider captcha with TxCaptchaHelper.apk
2023-02-12 13:18:36 I/Bot 1243733821: [SliderCaptcha] Captcha link: https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=1243733821&sid=2741034274418882220&cap_cd=ncuCqsBAnHudP8gEdyI5bpO4RUz5-gmp70wokF_KUY_tkqAkr0hyOg**&clientype=1&apptype=2
TxCaptchaHelper
2023-02-12 13:18:42 I/Bot 1243733821: [SliderCaptcha] @see https://github.com/mzdluo123/TxCaptchaHelper
2023-02-12 13:18:42 I/Bot 1243733821: Sending request...
2023-02-12 13:18:43 I/Bot 1243733821: 请在手机端使用请求码3827完成验证，完成后再次发送请求得到ticket
2023-02-12 13:19:03 W/Net 1243733821: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1243733821), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1243733821), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	... 9 more

2023-02-12 13:19:03 W/Net 1243733821: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1243733821), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=))
2023-02-12 13:19:03 E/top.berthua.plugin: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1243733821), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1243733821), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-12 13:19:03 I/MCL Addon: iTXTech MCL Version: 1.2.2-60c67fb
2023-02-12 13:19:03 I/Bot 1243733821: Bot cancelled: Bot closed
2023-02-12 13:19:03 I/main: 1 plugin(s) enabled.
2023-02-12 13:19:03 I/main: mirai-console started successfully.
```

**Comment by cssxsh** [comment]
https://mirai.mamoe.net/topic/223

**Comment by dragon0629** [comment]
这个算好的了，有时候网页登录qq都会出现这个报错，比如用qq登录腾讯云后台
一般重试几次就可以好

**Comment by lijing-2008** [comment]
> https://mirai.mamoe.net/topic/223

你好，我按照上面的两种方式都验证了，还是不行呢，依然报错237

**Comment by RF-Tar-Railt** [comment]
尝试切换为MACOS协议

**Comment by Him188** [comment]
#2570
