### ISSUE TITLE
在2023.2.10日腾讯重启服务器后疑似全军覆没

### ISSUE THREAD

**Issue by alongw** [mamoe/mirai#2497]
### 问题描述

我使用的mirai版本：2.13.2

我使用的登录协议：IPAD

腾讯权级足够高的QQ账号（此账号从来没有被风控过，登录密码一次必成功，从未出现过滑块短信等验证码）在正常使用的过程中异常报错，报错后始终无法重新登录。
附上当时的截图

![image](https://user-images.githubusercontent.com/64565408/218311763-db1d3ba7-c0c8-47b6-8e3a-22dd5867ed39.png)

此后，我尝试重启程序，他会重复出现图片中的错误

```
E/main: net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
```

我尝试搜索，发现在[#2167](https://github.com/mamoe/mirai/issues/2167)的[最新回复](https://github.com/mamoe/mirai/issues/2167#issuecomment-1425125130)中存在相同的问题。这个回复和我遇到的问题是同一天。

我尝试删除了bots文件夹，再次启动。他会在启动的过程中卡死。

```
2023-02-12 20:47:35 I/main: Auto-login ***, protocol: IPAD, heartbeatStrategy: STAT_HB
2023-02-12 20:47:35 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Usi
ng SimpleLogger to log to the console...
```

当按下ctrl+c时

```
2023-02-12 20:47:35 I/main: Auto-login ***, protocol: IPAD, heartbeatStrategy: STAT_HB
2023-02-12 20:47:35 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Usi
ng SimpleLogger to log to the console...
2023-02-12 20:54:56 I/Bot.***: Bot cancelled: Job was cancelled
2023-02-12 20:54:56 E/main: StateSwitchingException(old=StateConnecting, new=StateClosed, cause=null)
StateSwitchingException(old=StateConnecting, new=StateClosed, cause=null)
        at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.setStateImpl$mirai_core(NetworkHandlerSupport.kt:352)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler.close(CommonNetworkHandler.kt:418)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.close(SelectorNetworkHandler.kt:119)
        at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:114)
        at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:96)
        at net.mamoe.mirai.Bot.closeAndJoin$suspendImpl(Bot.kt:245)
        at net.mamoe.mirai.Bot.closeAndJoin(Bot.kt)
        at net.mamoe.mirai.Bot.closeAndJoin$default(Bot.kt:244)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.shutdown$mirai_console(MiraiConsoleImplementation.kt:453)
        at net.mamoe.mirai.console.MiraiConsole$INSTANCE$shutdown$1.invokeSuspend(MiraiConsole.kt:265)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-12 20:54:56 I/main: mirai-console started successfully.
```

于是我尝试将协议更换，并清空bots文件夹。
我与我的朋友一同对安卓手机、ipad、Mac、安卓PAD进行测试，均卡在

```
2023-02-12 20:40:57 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Usi
ng SimpleLogger to log to the console...
```

并且与上面的报错相同。

于是我尝试删除`AutoLogin.yml`，在添加登录后错误依旧。

于是我又尝试了重新安装mirai。

重新安装后添加了自动登录，与之前不同的是，这次在原来卡死的时候弹出了滑块验证码，过完之后依旧报错。

附上重新安装后的全部日志

```
  21:27:33 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  21:27:33 [INFO] Runtime: Java HotSpot(TM) 64-Bit Server VM 17.0.3 (arch: 64)
  21:27:33 [INFO] https://github.com/iTXTech/mirai-console-loader
  21:27:33 [INFO] This program is licensed under GNU AGPL v3
  21:27:34 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  21:27:34 [INFO] Verifying "net.mamoe:mirai-console" v2.13.2
  21:27:47 [WARN] Package "net.mamoe:mirai-console" has newer version "2.14.0"
  21:27:47 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.13.2
  21:27:48 [WARN] Package "net.mamoe:mirai-console-terminal" has newer version "2.14.0"
  21:27:48 [INFO] Verifying "net.mamoe:mirai-core-all" v2.13.2
  21:27:49 [WARN] Package "net.mamoe:mirai-core-all" has newer version "2.14.0"
  21:27:49 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  21:27:49 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
  21:27:49 [WARN] Run ./mcl -u to update packages.
2023-02-12 21:27:51 I/main: Starting mirai-console...
2023-02-12 21:27:51 I/main:

==================================[ Mirai consosle 2.13.2 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓ ▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓ ▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-02-12 21:27:51 I/main: Backend: version 2.13.2, built on 2022-12-05 01:50:53.
2023-02-12 21:27:51 I/main: Frontend Terminal: version 2.13.2, provided by Mamoe Technologies
2023-02-12 21:27:51 I/main: Welcome to visit https://mirai.mamoe.net/
2023-02-12 21:27:52 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2023-02-12 21:27:52 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2023-02-12 21:27:52 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2023-02-12 21:27:52 I/plugin: Successfully loaded plugin mirai-api-http v2.7.1
2023-02-12 21:27:52 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-02-12 21:27:53 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-02-12 21:27:53 I/Mirai HTTP API: ********************************************************
2023-02-12 21:27:53 W/stderr: [DefaultDispatcher-worker-1] INFO MahKtorAdapter[http,ws] - Autoreload is disabled because the development mode is off.
2023-02-12 21:27:53 W/stderr: [DefaultDispatcher-worker-1] INFO MahKtorAdapter[http,ws] - Application started in 0.272 seconds.
2023-02-12 21:27:53 W/stderr: [DefaultDispatcher-worker-2] INFO MahKtorAdapter[http,ws] - Responding at http://***
2023-02-12 21:27:53 I/http adapter: >>> [http adapter] is listening at http://***
2023-02-12 21:27:53 I/ws adapter: >>> [ws adapter] is listening at ws://***
2023-02-12 21:27:53 I/Mirai HTTP API: Http api server is running with verifyKey: ***
2023-02-12 21:27:53 I/Mirai HTTP API: adaptors: [http,ws]
2023-02-12 21:27:53 I/Mirai HTTP API: ********************************************************
2023-02-12 21:27:54 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-02-12 21:27:54 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-02-12 21:27:54 I/main: 2 plugin(s) enabled.
2023-02-12 21:27:54 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2023-02-12 21:27:54 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2023-02-12 21:27:54 I/main: Auto-login ***, protocol: IPAD, heartbeatStrategy: STAT_HB
2023-02-12 21:27:54 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2023-02-12 21:28:48 E/main: net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
        at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299)
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275)
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295)
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319)
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318)
        at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623)
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368)
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

2023-02-12 21:28:48 I/Bot.***: Bot cancelled: Bot closed
2023-02-12 21:28:48 I/main: mirai-console started successfully.
```

### 复现

重启mirai

### mirai-core 版本

2.13.2

### bot-protocol

IPAD

### 其他组件版本

mirai-api-http-v2.7.1.mirai2
mcl-addon-2.1.1

### 补充信息

我尝试过将Mirai更新到最新的版本（2.14.0），但是在这过程中并不是很顺利，我会继续尝试并将进展更新。

**Comment by MrXiaoM** [comment]
请升级到2.14.0。

我当天也是这样，也是IPAD协议，也是2.13.2，更新了就好了

**Comment by Him188** [comment]
2.14.0 已修复
