### ISSUE TITLE
在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志

### ISSUE THREAD

**Issue by xiatiaopoi** [mamoe/mirai#2507]
### 问题描述

2023-02-16 12:21:44 E/Group: ContextualBugReportException(message=在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志
提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 940462486
groupUin: 940462486
membersCount: 250
botId: 2336922251
owner: null, cause=null)
ContextualBugReportException(message=在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose    并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 940462486
groupUin: 940462486
membersCount: 250
botId: 2336922251
owner: null, cause=null)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
        at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
        at net.mamoe.mirai.internal.contact.GroupImplKt.GroupImpl(GroupImpl.kt:105)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.addGroupToBot(ContactUpdater.kt:252)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.access$addGroupToBot(ContactUpdater.kt:73)
        at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl$addGroupToBot$1.invokeSuspend(ContactUpdater.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-16 12:21:52 V/Bot.2336922251: Event: BotOnlineEvent(bot=Bot(2336922251))

### 复现

未知，登录后1分钟内发生

### mirai-core 版本

2.14.0

### bot-protocol

MACOS

### 补充信息

此时 Bot 不是为群管理员或群主, 和不是刚刚加入或离开这个群

**Comment by Him188** [comment]
#1977
