### ISSUE TITLE
java.lang.NoClassDefFoundError: net/mamoe/mirai/utils/SwingSolver

### ISSUE THREAD

**Issue by CL4399** [mamoe/mirai#2508]
### 问题描述

 E/console: java.lang.NoClassDefFoundError: net/mamoe/mirai/utils/SwingSolver

### 复现

执行 /login 命令并回填登录验证后报错  E/console: java.lang.NoClassDefFoundError: net/mamoe/mirai/utils/SwingSolver

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

**Comment by cssxsh** [comment]
日志？

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/blob/dev/ci-release-helper/changelogs/2.14.0-RC.md#%E4%B8%8D%E5%85%BC%E5%AE%B9%E5%8F%98%E6%9B%B4

**Comment by CL4399** [comment]
2023-02-16 14:50:11 I/Bot.2678305346: Bot cancelled: Bot closed
Login failed: net/mamoe/mirai/utils/SwingSolver
2023-02-16 14:50:11 E/console: java.lang.NoClassDefFoundError: net/mamoe/mirai/utils/SwingSolver
java.lang.NoClassDefFoundError: net/mamoe/mirai/utils/SwingSolver
        at mirai-login-solver-selenium-1.0-dev-17-all.jar//net.mamoe.mirai.selenium.SeleniumLoginSolverImpl.onSolveUnsafeDeviceLoginVerify(SeleniumLoginSolverImpl.kt:43)
        at net.mamoe.mirai.utils.LoginSolver.onSolveDeviceVerification$suspendImpl(LoginSolver.kt:91)
        at net.mamoe.mirai.utils.LoginSolver.onSolveDeviceVerification(LoginSolver.kt)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:278)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.utils.SwingSolver
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.loadClass(JvmPluginClassLoader.kt:440)
        ... 14 more

**Comment by cssxsh** [comment]
> mirai-login-solver-selenium

这个插件已经废弃

**Comment by CL4399** [comment]
好的，多谢
