### ISSUE TITLE
0.38.0中，发送群消息时发生java.lang.IllegalStateException

### ISSUE THREAD

**Issue by lincannm** [mamoe/mirai#251]
## 问题
mirai-core-qqandroid-jvm-0.38.0.jar，版本号为0.38.0
（按照<https://stageguard.top/2020/04/01/run-qqbot-on-termux-android/>搭建好的环境）

发送群消息时，mirai-http-api（localhost:8080/sendGroupMessage）返回500：
![S00421-22033270](https://user-images.githubusercontent.com/41236336/79876902-2e5db580-841e-11ea-9d1c-3a17da585fc9.jpg)

在mirai-console中可以看见输出的报错，报错如下：
```
14:02:48 [ERROR] [MiraiAPIHTTP] java.lang.IllegalStateException: sequenceId not yet available
        at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl.getSequenceId(outgoingSourceImpl.kt:125)
        at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl.getId(outgoingSourceImpl.kt:114)
        at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$1.invokeSuspend(outgoingSourceImpl.kt:134)
        at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$1.invoke(outgoingSourceImpl.kt)
        at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$$inlined$subscribingGetAsync$1$2$1.invokeSuspend(linear.kt:102)
        at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$$inlined$subscribingGetAsync$1$2$1.invoke(linear.kt)
        at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$$inlined$subscribingGetAsync$1$2$2.invokeSuspend(subscriber.kt:141)
        at net.mamoe.mirai.qqandroid.message.MessageSourceToGroupImpl$startWaitingSequenceId$$inlined$subscribingGetAsync$1$2$2.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:76)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:76)
        at net.mamoe.mirai.event.internal.InternalEventListenersKt$callAndRemoveIfRequired$$inlined$forEachNode$lambda$1.invokeSuspend(InternalEventListeners.kt:162)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
不过有些时候即使有500和报错，群消息照样发送（后来消息就发不了了）

## 如何复现
在js文件中（类似[mirai-rhinojs-sdk](https://github.com/StageGuard/mirai-rhinojs-sdk)中的demo.js），调用miraiSession.sendGroupMessage(...)来发送群消息，就彳亍了

**Comment by lincannm** [comment]
望修复

**Comment by Him188** [comment]
将在0.38.1发布修复
