### ISSUE TITLE
获取特定 RoamingMessages 时崩溃

### ISSUE THREAD

**Issue by ojhdt** [mamoe/mirai#2514]
### 问题描述

绝大多数历史消息可正常获取，但某些消息获取失败且导致程序崩溃。无法知晓具体消息类型。

### 复现

正常调用 `group.roamingMessages.getMessagesIn()` 。

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PAD

### 系统日志

```text
FATAL EXCEPTION: DefaultDispatcher-worker-19
	Process: com.ojhdtapp.miraipluginforparabox, PID: 10587
	java.lang.NullPointerException
		at net.mamoe.mirai.internal.message.source.OnlineMessageSourceFromGroupImpl.<init>(incomingSourceImpl.kt:217)
		at net.mamoe.mirai.internal.message.ReceiveMessageTransformer.createMessageSource(ReceiveMessageHandler.kt:144)
		at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChain(ReceiveMessageHandler.kt:114)
		at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline(ReceiveMessageHandler.kt:53)
		at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline(ReceiveMessageHandler.kt:80)
		at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline$default(ReceiveMessageHandler.kt:70)
		at net.mamoe.mirai.internal.contact.roaming.RoamingMessagesImplGroup$getMessagesIn$2$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:224)
		at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$5.collect(SafeCollector.common.kt:115)
		at net.mamoe.mirai.internal.contact.roaming.RoamingMessagesImplGroup$getMessagesIn$2$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:113)
		at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
		at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
		at net.mamoe.mirai.internal.contact.roaming.RoamingMessagesImplGroup$getMessagesIn$2.invokeSuspend(RoamingMessagesImplGroup.kt:57)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
		at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
		at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
		Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e7a0d9f, Dispatchers.IO]
```

**Comment by sandtechnology** [comment]
https://github.com/mamoe/mirai/blob/9f36eff070b17fc9260154b063431ab9fc6d4945/mirai-core/src/commonMain/kotlin/message/source/incomingSourceImpl.kt#L217
看起来是richText为null，需要考虑跳过，可能是某些特殊消息

**Comment by StageGuard** [comment]
另外还有个问题是获取群漫游记录时如果有被踢成员的消息可能也会异常，无法找到 sender

**Comment by Karlatemp** [comment]
72c128b7a318e2aab9965dce967bbcfeb74ca9c6 会对此有所帮助

96472d9e167ee2c32cebe515d376d7d09ee5eaff 应该会修复此错误

**Comment by ojhdt** [comment]
> [72c128b](https://github.com/mamoe/mirai/commit/72c128b7a318e2aab9965dce967bbcfeb74ca9c6) 会对此有所帮助
> 
> [96472d9](https://github.com/mamoe/mirai/commit/96472d9e167ee2c32cebe515d376d7d09ee5eaff) 应该会修复此错误

[96472d9](https://github.com/mamoe/mirai/commit/96472d9e167ee2c32cebe515d376d7d09ee5eaff) 已修复此错误，但出现了类似的错误，日志如下：
```
java.lang.IllegalStateException: Failed to transform internal message to facade message, msg=[
        Msg#168480810 {
                contentHead=ContentHead#196681229 {
                        pkgNum=0x00000001(1)
                }
                msgBody=MsgBody#219626451 {
                        richText=RichText#256963344 {
                                elems=[Elem#210747951 {
                                        text=Text#90243525 {
                                                str=[已删除]
                                        }
                                }]
                        }
                }
                msgHead=MsgHead#217497539 {
                        c2cCmd=0x00000001(1)
                        groupInfo=GroupInfo#64097145 {
                                groupCode=0x0000000038403879(943732857)
                                groupType=0x0000007F(127)
                        }
                        isSrcMsg=false
                        msgSeq=0x0008E37B(582523)
                        msgType=0x00000052(82)
                }
        }]
        at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChain(ReceiveMessageHandler.kt:112)
        at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline(ReceiveMessageHandler.kt:54)
        at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline(ReceiveMessageHandler.kt:81)
        at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline$default(ReceiveMessageHandler.kt:71)
        at net.mamoe.mirai.internal.contact.roaming.RoamingMessagesImplGroup$getMessagesIn$2$invokeSuspend$$inlined$map$1$2.emit(Emitters.kt:224)
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$5.collect(SafeCollector.common.kt:115)
        at net.mamoe.mirai.internal.contact.roaming.RoamingMessagesImplGroup$getMessagesIn$2$invokeSuspend$$inlined$map$1.collect(SafeCollector.common.kt:113)
        at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
        at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
        at net.mamoe.mirai.internal.contact.roaming.RoamingMessagesImplGroup$getMessagesIn$2.invokeSuspend(RoamingMessagesImplGroup.kt:57)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
