### ISSUE TITLE
Code45禁止登入

### ISSUE THREAD

**Issue by SkyItemChen** [mamoe/mirai#2524]
### 问题描述

E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(*********), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(*********), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

### 复现

登入账号即会产生该问题，无法登入

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

Running MiraiConsole v2.14.0, built on 2023-02-06 14:25:21.
Frontend Terminal: version 2.14.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: MCL Addon v2.1.1

Object Pending Finalization Count: 0
                 committed |  init   |  used   |  max
    Heap Memory:  108.0MB  | 512.0MB | 26.98MB | 7.94GB
Non-Heap Memory:  55.25MB  | 7.31MB  | 53.64MB |   -1

### 系统日志

```text
2023-02-22 14:12:16 I/main: Starting mirai-console...
2023-02-22 14:12:16 I/main: 

==================================[ Mirai consosle 2.14.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-02-22 14:12:16 I/main: Backend: version 2.14.0, built on 2023-02-06 14:25:21.
2023-02-22 14:12:16 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-02-22 14:12:16 I/main: Welcome to visit https://mirai.mamoe.net/
2023-02-22 14:12:37 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-02-22 14:12:37 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-02-22 14:12:37 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-02-22 14:12:37 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-02-22 14:12:37 I/main: 1 plugin(s) enabled.
2023-02-22 14:12:37 I/main: mirai-console started successfully.
2023-02-22 14:21:18 I/main: Starting mirai-console...
2023-02-22 14:21:18 I/main: 

==================================[ Mirai consosle 2.14.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-02-22 14:21:18 I/main: Backend: version 2.14.0, built on 2023-02-06 14:25:21.
2023-02-22 14:21:18 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-02-22 14:21:18 I/main: Welcome to visit https://mirai.mamoe.net/
2023-02-22 14:21:19 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-02-22 14:21:19 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-02-22 14:21:19 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-02-22 14:21:19 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-02-22 14:21:19 I/main: 1 plugin(s) enabled.
2023-02-22 14:21:19 I/main: Auto-login 3386135992, protocol: ANDROID_PHONE, heartbeatStrategy: STAT_HB
2023-02-22 14:21:20 I/Bot.3386135992: Calculating type 2 PoW, it can take some time....
2023-02-22 14:21:20 I/Bot.3386135992: Got PoW result, cost: 44 ms
2023-02-22 14:21:20 I/Bot.3386135992: [SliderCaptcha] 需要滑动验证码, 请按照以下链接的步骤完成滑动验证码, 然后输入获取到的 ticket
2023-02-22 14:21:20 I/Bot.3386135992: [SliderCaptcha] Slider captcha required. Please solve the captcha with following link. Type ticket here after completion.
2023-02-22 14:21:20 I/Bot.3386135992: [SliderCaptcha] @see https://github.com/project-mirai/mirai-login-solver-selenium
2023-02-22 14:21:20 I/Bot.3386135992: [SliderCaptcha] @see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
2023-02-22 14:21:20 I/Bot.3386135992: [SliderCaptcha] 或者输入 TxCaptchaHelper 来使用 TxCaptchaHelper 完成滑动验证码
2023-02-22 14:21:20 I/Bot.3386135992: [SliderCaptcha] Or type `TxCaptchaHelper` to resolve slider captcha with TxCaptchaHelper.apk
2023-02-22 14:21:20 I/Bot.3386135992: [SliderCaptcha] Captcha link: https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=3386135992&sid=4442814155203130464&cap_cd=DD3U_jMdMmiORbBrdEjHxPRdxApgAZ53p31v0qbfAfwOEziz73MSIg**&clientype=1&apptype=2
2023-02-22 14:27:13 I/Bot.3386135992: [SliderCaptcha] @see https://github.com/mzdluo123/TxCaptchaHelper
2023-02-22 14:27:13 I/Bot.3386135992: Sending request...
2023-02-22 14:27:14 I/Bot.3386135992: 请在手机端使用请求码973完成验证，完成后再次发送请求得到ticket
2023-02-22 14:27:44 I/Bot.3386135992: Bot cancelled: Bot closed
2023-02-22 14:27:44 E/main: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-02-22 14:27:44 I/main: mirai-console started successfully.
2023-02-22 14:28:10 I/main: Starting mirai-console...
2023-02-22 14:28:10 I/main: 

==================================[ Mirai consosle 2.14.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-02-22 14:28:10 I/main: Backend: version 2.14.0, built on 2023-02-06 14:25:21.
2023-02-22 14:28:10 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-02-22 14:28:10 I/main: Welcome to visit https://mirai.mamoe.net/
2023-02-22 14:28:10 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-02-22 14:28:10 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-02-22 14:28:10 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-02-22 14:28:10 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-02-22 14:28:10 I/main: 1 plugin(s) enabled.
2023-02-22 14:28:10 I/main: Auto-login 3386135992, protocol: ANDROID_PHONE, heartbeatStrategy: STAT_HB
2023-02-22 14:28:11 I/Bot.3386135992: Calculating type 2 PoW, it can take some time....
2023-02-22 14:28:11 I/Bot.3386135992: Got PoW result, cost: 47 ms
2023-02-22 14:28:11 I/Bot.3386135992: [SliderCaptcha] 需要滑动验证码, 请按照以下链接的步骤完成滑动验证码, 然后输入获取到的 ticket
2023-02-22 14:28:11 I/Bot.3386135992: [SliderCaptcha] Slider captcha required. Please solve the captcha with following link. Type ticket here after completion.
2023-02-22 14:28:11 I/Bot.3386135992: [SliderCaptcha] @see https://github.com/project-mirai/mirai-login-solver-selenium
2023-02-22 14:28:11 I/Bot.3386135992: [SliderCaptcha] @see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
2023-02-22 14:28:11 I/Bot.3386135992: [SliderCaptcha] 或者输入 TxCaptchaHelper 来使用 TxCaptchaHelper 完成滑动验证码
2023-02-22 14:28:11 I/Bot.3386135992: [SliderCaptcha] Or type `TxCaptchaHelper` to resolve slider captcha with TxCaptchaHelper.apk
2023-02-22 14:28:11 I/Bot.3386135992: [SliderCaptcha] Captcha link: https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=3386135992&sid=2481623773069293052&cap_cd=TZwFCCYpmsZSJR6zOHX9CXW1vqebzT5s17ajE9mFkSKlRlceClY2pg**&clientype=1&apptype=2
2023-02-22 14:28:21 I/Bot.3386135992: [SliderCaptcha] @see https://github.com/mzdluo123/TxCaptchaHelper
2023-02-22 14:28:21 I/Bot.3386135992: Sending request...
2023-02-22 14:28:23 I/Bot.3386135992: 请在手机端使用请求码2761完成验证，完成后再次发送请求得到ticket
2023-02-22 14:28:33 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3386135992), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3386135992), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-22 14:28:33 I/Bot.3386135992: Bot cancelled: Bot closed
2023-02-22 14:28:33 I/main: mirai-console started successfully.
2023-02-22 14:31:37 I/Bot.3386135992: Calculating type 2 PoW, it can take some time....
2023-02-22 14:31:37 I/Bot.3386135992: Got PoW result, cost: 32 ms
2023-02-22 14:31:37 I/Bot.3386135992: [SliderCaptcha] 需要滑动验证码, 请按照以下链接的步骤完成滑动验证码, 然后输入获取到的 ticket
2023-02-22 14:31:37 I/Bot.3386135992: [SliderCaptcha] Slider captcha required. Please solve the captcha with following link. Type ticket here after completion.
2023-02-22 14:31:37 I/Bot.3386135992: [SliderCaptcha] @see https://github.com/project-mirai/mirai-login-solver-selenium
2023-02-22 14:31:37 I/Bot.3386135992: [SliderCaptcha] @see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
2023-02-22 14:31:37 I/Bot.3386135992: [SliderCaptcha] 或者输入 TxCaptchaHelper 来使用 TxCaptchaHelper 完成滑动验证码
2023-02-22 14:31:37 I/Bot.3386135992: [SliderCaptcha] Or type `TxCaptchaHelper` to resolve slider captcha with TxCaptchaHelper.apk
2023-02-22 14:31:37 I/Bot.3386135992: [SliderCaptcha] Captcha link: https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=3386135992&sid=3287979607738136266&cap_cd=I9wf8P7SUqIh9N8CYAkbADf4QwN8Exu60kjP2SldHkmqH2w-KGIhRw**&clientype=1&apptype=2
2023-02-22 14:31:43 I/Bot.3386135992: [SliderCaptcha] @see https://github.com/mzdluo123/TxCaptchaHelper
2023-02-22 14:31:43 I/Bot.3386135992: Sending request...
2023-02-22 14:31:44 I/Bot.3386135992: 请在手机端使用请求码6564完成验证，完成后再次发送请求得到ticket
2023-02-22 14:31:58 I/Bot.3386135992: Bot cancelled: Bot closed
2023-02-22 14:31:58 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3386135992), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3386135992), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-22 14:34:08 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2212295912), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2212295912), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-22 14:34:08 I/Bot.2212295912: Bot cancelled: Bot closed
2023-02-22 14:44:33 I/main: Starting mirai-console...
2023-02-22 14:44:33 I/main: 

==================================[ Mirai consosle 2.14.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-02-22 14:44:33 I/main: Backend: version 2.14.0, built on 2023-02-06 14:25:21.
2023-02-22 14:44:33 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-02-22 14:44:33 I/main: Welcome to visit https://mirai.mamoe.net/
2023-02-22 14:44:33 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-02-22 14:44:33 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-02-22 14:44:33 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-02-22 14:44:33 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-02-22 14:44:33 I/main: 1 plugin(s) enabled.
2023-02-22 14:44:33 I/main: mirai-console started successfully.
2023-02-22 14:45:16 I/main: Starting mirai-console...
2023-02-22 14:45:16 I/main: 

==================================[ Mirai consosle 2.14.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-02-22 14:45:16 I/main: Backend: version 2.14.0, built on 2023-02-06 14:25:21.
2023-02-22 14:45:16 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-02-22 14:45:16 I/main: Welcome to visit https://mirai.mamoe.net/
2023-02-22 14:45:16 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-02-22 14:45:16 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-02-22 14:45:16 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-02-22 14:45:16 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-02-22 14:45:16 I/main: 1 plugin(s) enabled.
2023-02-22 14:45:16 I/main: mirai-console started successfully.
```

**Comment by pilgrim773** [comment]
删除bot目录下的qq号文件夹后把协议改成MACOS试试，我是这样解决45的

**Comment by SkyItemChen** [comment]
> 删除bot目录下的qq号文件夹后把协议改成MACOS试试，我是这样解决45的

怎么更改协议

**Comment by pilgrim773** [comment]
> > 删除bot目录下的qq号文件夹后把协议改成MACOS试试，我是这样解决45的
> 
> 怎么更改协议

`./config/Console/AutoLogin.yml` 根据注释修改 `protocol`

**Comment by chuanzhubin** [comment]
> 

我是删掉bots里的qq号文件夹, 然后验证码ticket通过之后, 又来一个扫码连接. 不知道下一步怎么走了

**Comment by 951043684** [comment]
> > > 删除bot目录下的qq号文件夹后把协议改成MACOS试试，我是这样解决45的
> > 
> > 
> > 怎么更改协议
> 
> `./config/Console/AutoLogin.yml` 根据注释修改 `protocol`

按照你说的做了还是不行

**Comment by 1061700625** [comment]
[Duplicate of #2538](https://github.com/mamoe/mirai/issues/2538#issuecomment-1461652829)

**Comment by Him188** [comment]
#2570

**Comment by onepiecewyz** [comment]
> 删除bot目录下的qq号文件夹后把协议改成MACOS试试，我是这样解决45的

it works!

**Comment by StarDreamAndFeng** [comment]
#2630 这种方法能够登录

**Comment by ayakagachi** [comment]
2024-06-26 15:31:45 I/fix-protocol-version: 当前各登录协议版本日期:
ANDROID_PHONE  8.9.63.11390  2023-05-26T10:46:18+08:00
ANDROID_PAD    8.9.63.11390  2023-05-26T10:46:18+08:00
ANDROID_WATCH  2.0.8         2019-06-03T20:25:31+08:00
IPAD           8.9.50.611    2023-02-16T15:10:14+08:00
MACOS          6.8.2.21241   2022-03-14T11:11:35+08:00

大佬我还是不行，签名服务用的是unidbg-fetch-qsign，支持8.9.58，但是MACOS无法更新到8.9.58

报错如下：
2024-06-26 15:31:45 E/KFCFactory: MACOS 尚不支持签名服务，大概率登录失败
2024-06-26 15:31:45 I/TLV544Provider: load: file:///F:/mirai/mcl-2.1.2/t544-enc-windows-x64.dll
2024-06-26 15:31:52 I/TLV544Provider: t544 command: 810_9 with MACOS
2024-06-26 15:32:20 I/TLV544Provider: t544 command: 810_2 with MACOS
2024-06-26 15:32:20 E/main: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
...
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(481903188), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)]

**Comment by 1061700625** [comment]
都凉了，目前能用的就是这个了：https://blog.csdn.net/sxf1061700625/article/details/126948888
