### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by bunnyi116** [mamoe/mirai#2537]
### 问题描述

```
2023-02-27 14:57:29 E/Mah Debug: java.util.concurrent.CancellationException: ArrayChannel was cancelled
java.util.concurrent.CancellationException: ArrayChannel was cancelled
	at kotlinx.coroutines.channels.AbstractChannel.cancel(AbstractChannel.kt:656)
	at kotlinx.coroutines.channels.ReceiveChannel$DefaultImpls.cancel$default(Channel.kt:279)
	at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.websocket.DefaultWebSocketSessionImpl$runOutgoingProcessor$1.invokeSuspend(DefaultWebSocketSession.kt:228)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:183)
	at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:190)
	at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1475)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:900)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
	at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:696)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:667)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:747)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)
	at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)
	at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:549)
	at kotlinx.coroutines.JobKt.cancel(Unknown Source)
	at kotlinx.coroutines.JobKt__JobKt.cancel$default(Job.kt:548)
	at kotlinx.coroutines.JobKt.cancel$default(Unknown Source)
	at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.server.cio.backend.ServerPipelineKt$startServerConnectionPipeline$1.invokeSuspend(ServerPipeline.kt:180)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-27 14:57:29 E/Mah Debug: java.util.concurrent.CancellationException: ArrayChannel was cancelled
java.util.concurrent.CancellationException: ArrayChannel was cancelled
	at kotlinx.coroutines.channels.AbstractChannel.cancel(AbstractChannel.kt:656)
	at kotlinx.coroutines.channels.ReceiveChannel$DefaultImpls.cancel$default(Channel.kt:279)
	at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.websocket.DefaultWebSocketSessionImpl$runOutgoingProcessor$1.invokeSuspend(DefaultWebSocketSession.kt:228)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
	at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:245)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:183)
	at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:190)
	at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1475)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:900)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
	at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:696)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:667)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:747)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
	at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
	at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
	at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
	at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
	at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
	at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)
	at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)
	at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:549)
	at kotlinx.coroutines.JobKt.cancel(Unknown Source)
	at kotlinx.coroutines.JobKt__JobKt.cancel$default(Job.kt:548)
	at kotlinx.coroutines.JobKt.cancel$default(Unknown Source)
	at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.server.cio.backend.ServerPipelineKt$startServerConnectionPipeline$1.invokeSuspend(ServerPipeline.kt:180)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### 复现

未知，看后台突然报错，发送消息后台就有报错，重新重启程序后又正常了，报错日志已放

### mirai-core 版本

2.14.0

### bot-protocol

IPAD

**Comment by Him188** [comment]
@ryoii

**Comment by bunnyi116** [comment]
今天查看后台 又出现这个 `java.util.concurrent.CancellationException: ArrayChannel was cancelled` 报错，也不知道是什么原因引起的，我在群里发送一条信息，视乎是机器人接收到信息后就爆错误，望解决~！

```
2023-02-28 13:50:21 E/Mah Debug: java.util.concurrent.CancellationException: ArrayChannel was cancelled
java.util.concurrent.CancellationException: ArrayChannel was cancelled
        at kotlinx.coroutines.channels.AbstractChannel.cancel(AbstractChannel.kt:656)
        at kotlinx.coroutines.channels.ReceiveChannel$DefaultImpls.cancel$default(Channel.kt:279)
        at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.websocket.DefaultWebSocketSessionImpl$runOutgoingProcessor$1.invokeSuspend(DefaultWebSocketSession.kt:228)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:69)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:245)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.cancel(CancellableContinuationImpl.kt:183)
        at kotlinx.coroutines.CancellableContinuationImpl.parentCancelled$kotlinx_coroutines_core(CancellableContinuationImpl.kt:190)
        at kotlinx.coroutines.ChildContinuation.invoke(JobSupport.kt:1475)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:900)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
        at kotlinx.coroutines.JobSupport.cancelMakeCompleting(JobSupport.kt:696)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:667)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:747)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.parentCancelled(JobSupport.kt:637)
        at kotlinx.coroutines.ChildHandleNode.invoke(JobSupport.kt:1466)
        at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1500)
        at kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:795)
        at kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:755)
        at kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:671)
        at kotlinx.coroutines.JobSupport.cancelInternal(JobSupport.kt:632)
        at kotlinx.coroutines.JobSupport.cancel(JobSupport.kt:617)
        at kotlinx.coroutines.JobKt__JobKt.cancel(Job.kt:549)
        at kotlinx.coroutines.JobKt.cancel(Unknown Source)
        at kotlinx.coroutines.JobKt__JobKt.cancel$default(Job.kt:548)
        at kotlinx.coroutines.JobKt.cancel$default(Unknown Source)
        at mirai-api-http-2.8.0.mirai2.jar[shared]//io.ktor.server.cio.backend.ServerPipelineKt$startServerConnectionPipeline$1.invokeSuspend(ServerPipeline.kt:180)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```


![JBEX)Y%B8G{~JP(8NKDL72](https://user-images.githubusercontent.com/37466008/221766026-e504df59-a541-483a-b132-dcf77a01f65b.png)


版本信息

![image](https://user-images.githubusercontent.com/37466008/221766973-a88782da-bd60-4ec5-96bb-e2117a34a4fb.png)


![image](https://user-images.githubusercontent.com/37466008/221767157-fd834363-de91-4b29-97a1-64029ac6abaf.png)

**Comment by ryoii** [comment]
远端连接关闭，检查你的客户端

**Comment by bunnyi116** [comment]
> 远端连接关闭，检查你的客户端

我的其他号码都是正常的

![image](https://user-images.githubusercontent.com/37466008/221776464-ea7d6f64-1c5e-43a9-b65d-5fea01366e90.png)

**Comment by ryoii** [comment]
和其他号有什么关系

**Comment by bunnyi116** [comment]
> Reference in new issu

那你指的客户端指的是Mirai-Console还是说是连接到Mirai-Api-Http的客户端？

**Comment by ryoii** [comment]
websocket 的客户端

**Comment by bunnyi116** [comment]
好的，不过为什么已经断开了，他怎么还一直报错，他不自动断开吗一直抛出异常？

**Comment by bunnyi116** [comment]
> websocket 的客户端

既然Mirai-Console已经抛出了断开的异常和提示，为何Mirai-Api-Http不进行断开处理，我觉得可以断开避免重复抛出异常，如果是考虑到WS客户端会重新连接，那就设定一个生命周期，期间就不要继续抛出异常了，直接提示WS客户端断开，超过这个生命周期时间，就主动断开连接。

**Comment by ryoii** [comment]
因为我从来没有捕获过这种错误。websocket断开会发送 CloseFrame 主动断开，即使异常断开也会有 tcp 断开。我不知道什么客户端会出现这种断也断不干净的 bug。反正我用各种测试工具从来没有复现过

**Comment by bunnyi116** [comment]
> 因为我从来没有捕获过这种错误。websocket断开会发送 CloseFrame 主动断开，即使异常断开也会有 tcp 断开。我不知道什么客户端会出现这种断也断不干净的 bug。反正我用各种测试工具从来没有复现过

行吧，就这样吧。

**Comment by bunnyi116** [comment]
> 因为我从来没有捕获过这种错误。websocket断开会发送 CloseFrame 主动断开，即使异常断开也会有 tcp 断开。我不知道什么客户端会出现这种断也断不干净的 bug。反正我用各种测试工具从来没有复现过

已经复现问题，连接到WebSocket后断开时出现。

```c#
        var uri = new Uri($"ws://192.168.10.10:20000/all?verifyKey={verifyKey}&qq={qq}");
        var ws = new ClientWebSocket();
        var cts = new CancellationTokenSource();
        await ws.ConnectAsync(uri, CancellationToken.None);
        var rcvBytes = new byte[1024];
        var rcvBuffer = new ArraySegment<byte>(rcvBytes);
        while (true)
        {
            var rcvResult = await ws.ReceiveAsync(rcvBuffer, cts.Token);

            Console.WriteLine("[网络状态]：{0}", ws.State);
            Console.WriteLine("[消息类型]：{0}", rcvResult.MessageType);
            Console.WriteLine("[消息长度]：{0}", rcvResult.Count);
            Console.WriteLine("[消息结尾]：{0}", rcvResult.EndOfMessage);

            byte[] msgBytes = rcvBuffer.Skip(rcvBuffer.Offset).Take(rcvResult.Count).ToArray();
            string rcvMsg = Encoding.UTF8.GetString(msgBytes);
            Console.WriteLine("[消息内容]：{0}", rcvMsg);
            Console.WriteLine();
        }
```

![image](https://user-images.githubusercontent.com/37466008/222107373-62f519fb-f42d-4a71-944e-6bec53193fb5.png)

**Comment by ryoii** [comment]
这是通过 ctrl c 强制终止进程退出的么

**Comment by bunnyi116** [comment]
> 这是通过 ctrl c 强制终止进程退出的么

之前我是使用Mirai.Net 连接的，视乎也会出现。

后面我自己尝试用WS客户端连接到Mirai，是调试运行环境时直接关闭调试运行。

其实Mirai已经捕捉到了断开，你只要处理一下WS断开异常就行，后台和日志全是报错，一直存在。



猜测：问题应该出在 Mirai WS服务端断开抛出异常后，未对会话监听列表（Array，`2023-02-28 13:50:21 E/Mah Debug: java.util.concurrent.CancellationException: ArrayChannel was cancelled`）进行移除该会话的列表，导致接收到信息的时候，广播给所有会话列表中WS客户端，但由于WS实际已经是断开状态，所以抛出异常。

**Comment by ryoii** [comment]
问题就是不论我怎么写 test case，不论我怎么用什么方式断开客户端，最终都会释放 websocket

**Comment by bunnyi116** [comment]
> 问题就是不论我怎么写 测试用例，不论我怎么用什么方式断开客户端，最终都会释放 websocket

这报错只会在Mirai接收到QQ消息时候抛出

**Comment by Bunnui** [comment]
要不加个QQ 演示给你看看

**Comment by bunnyi116** [comment]
重新安装后没有这个情况了
