### ISSUE TITLE
 code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。

### ISSUE THREAD

**Issue by RzZ123** [mamoe/mirai#2538]
### 问题描述

code=45,这个报错不断重复，更改账户还是协议都没用。

### 复现

登入账号即会产生该问题，无法登入

### mirai-core 版本

2.14.0

### bot-protocol

MACOS

### 其他组件版本

"net.mamoe:mirai-console": {
      "channel": "maven-stable",
      "version": "2.14.0",
      "type": "libs",
      "versionLocked": false
    },
    "net.mamoe:mirai-console-terminal": {
      "channel": "maven-stable",
      "version": "2.14.0",
      "type": "libs",
      "versionLocked": false
    },
    "net.mamoe:mirai-core-all": {
      "channel": "maven-stable",
      "version": "2.14.0",
      "type": "libs",
      "versionLocked": false
    },
    "org.itxtech:mcl-addon": {
      "channel": "maven-stable",
      "version": "2.1.1",
      "type": "plugins",
      "versionLocked": false
    },
    "org.bouncycastle:bcprov-jdk15on": {
      "channel": "stable",
      "version": "1.64",
      "type": "libs",
      "versionLocked": false
    }

### 系统日志

```text
==================================[ Mirai consosle 2.14.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-02-27 19:39:26 I/main: Backend: version 2.14.0, built on 2023-02-06 14:25:21.
2023-02-27 19:39:26 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-02-27 19:39:26 I/main: Welcome to visit https://mirai.mamoe.net/
2023-02-27 19:39:27 I/plugin: Successfully loaded plugin mirai-login-solver-sakura v0.0.8
2023-02-27 19:39:27 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-02-27 19:39:27 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-02-27 19:39:27 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-02-27 19:39:27 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-02-27 19:39:27 I/main: 2 plugin(s) enabled.
2023-02-27 19:39:27 I/main: mirai-console started successfully.
2023-02-27 19:39:38 I/Bot.1143864376: Bot cancelled: Bot closed
2023-02-27 19:39:38 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1143864376), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1143864376), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-27 19:41:32 I/Bot.1143864376: Bot cancelled: Bot closed
2023-02-27 19:41:32 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1143864376), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1143864376), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-27 19:41:40 I/Bot.1143864376: Bot cancelled: Bot closed
2023-02-27 19:41:40 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1143864376), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1143864376), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-27 19:43:35 I/main: Starting mirai-console...
2023-02-27 19:43:35 I/main: 

==================================[ Mirai consosle 2.14.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-02-27 19:43:35 I/main: Backend: version 2.14.0, built on 2023-02-06 14:25:21.
2023-02-27 19:43:35 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-02-27 19:43:35 I/main: Welcome to visit https://mirai.mamoe.net/
2023-02-27 19:43:36 I/plugin: Successfully loaded plugin mirai-login-solver-sakura v0.0.8
2023-02-27 19:43:36 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-02-27 19:43:36 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-02-27 19:43:37 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-02-27 19:43:37 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-02-27 19:43:37 I/main: 2 plugin(s) enabled.
2023-02-27 19:43:37 I/main: mirai-console started successfully.
2023-02-27 19:43:49 I/Bot.1143864376: Bot cancelled: Bot closed
2023-02-27 19:43:49 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1143864376), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1143864376), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-02-27 19:45:39 I/MCL Addon: Package: net.mamoe:mirai-console  Channel: maven-stable  Type: libs  Version: 2.14.0  Locked: false
2023-02-27 19:45:39 I/MCL Addon: Package: net.mamoe:mirai-console-terminal  Channel: maven-stable  Type: libs  Version: 2.14.0  Locked: false
2023-02-27 19:45:39 I/MCL Addon: Package: net.mamoe:mirai-core-all  Channel: maven-stable  Type: libs  Version: 2.14.0  Locked: false
2023-02-27 19:45:39 I/MCL Addon: Package: org.itxtech:mcl-addon  Channel: maven-stable  Type: plugins  Version: 2.1.1  Locked: false
2023-02-27 19:45:39 I/MCL Addon: Package: org.bouncycastle:bcprov-jdk15on  Channel: stable  Type: libs  Version: 1.64  Locked: false
```

### 网络日志

```text
无
```

### 补充信息

无

**Comment by SkyblueMr** [comment]
无解，是麻花疼那边对账号限制导致的，我后面用最新版的PC端QQ也是登陆不了，提示版本过低，登陆方式还是用手机扫码登陆的都不行

**Comment by jinjidechefeng** [comment]
> 无解，是麻花疼那边对账号限制导致的，我后面用最新版的PC端QQ也是登陆不了，提示版本过低，登陆方式还是用手机扫码登陆的都不行
我这也是这个报错，唉，是先要申请qq机器人吧

**Comment by Sunosay** [comment]
除了更改macos协议还有别的办法吗 这种情况有什么办法解除

**Comment by MarindaCloud** [comment]
今天也遇到了这个问题，后续还会遇到网络环境异常问题无法登录，删除**bot/qq号**无果。
如果你是使用MCL，那么请你重新下载mcl2.1.2版本启动，并且一切初始化，手动校验验证码和手机号验证码，登录成功！

**Comment by 1061700625** [comment]
已解决，请看：https://blog.csdn.net/sxf1061700625/article/details/126948888

**Comment by Him188** [comment]
#2570
