### ISSUE TITLE
登录失败，返回的code是235，提示当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面

### ISSUE THREAD

**Issue by xiaodi001-01** [mamoe/mirai#2545]
### 问题描述

在2/8日时，我打开了mcl.cmd，然后开始自动登录，提示net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(XXXXXXXXXX), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)，第二次登录的时候我从MCL Installer的release内的mcl-installer-1.0.7-windows-amd64.exe下载的MCL的所有文件替换了我运行mcl的文件并且删除了device.json，在登录账号时，需要滑动验证码，我使用了这台电脑上的360安全浏览器滑动了验证码，仍然失败，两次登录使用的操作系统都是windows10专业工作站版

### 复现

1.使用mirai的自动登录去登录之前登不上的账号
2.如果像我删除了device.json，会弹出验证码
3.滑动验证码，如果没弹出就忽略
4.出现错误net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(XXXXXXXXXX), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

Running MiraiConsole v2.14.0, built on 2023-02-06 14:25:21.
Frontend Terminal: version 2.14.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: mirai-api-http v2.8.0, MCL Addon v2.1.1

Object Pending Finalization Count: 0
                 committed |  init   |  used   |  max
    Heap Memory:  110.0MB  | 256.0MB | 45.38MB | 3.98GB
Non-Heap Memory:  74.31MB  | 7.31MB  | 72.68MB |   -1

### 系统日志

```text
Login failed: Error(bot=Bot(1966289318), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点 击进入下载页面, errorInfo=)
2023-03-03 17:03:54 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(XXXXXXXXXX), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(XXXXXXXXXX), code=235, title=温馨提示, message=当前QQ版本 过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by Pika-Lee** [comment]
+1
![QQ截图20230303195541](https://user-images.githubusercontent.com/23114990/222874595-167c8870-f464-439c-8f77-04984714c756.png)
版本2.14.0

**Comment by 1770460850** [comment]
+1
![image](https://user-images.githubusercontent.com/46707123/222877154-1ddf096e-9c7d-4a24-831c-8b966dbf8040.png)

**Comment by windy664** [comment]
我也是啊 怎么办

**Comment by AtaraxiaEta** [comment]
+1

**Comment by G4-SIMPLE** [comment]
+1

**Comment by G4-SIMPLE** [comment]
我把AutoLogin.yml里的协议切换到的安卓手表，然后就能登录了
protocol: ANDROID_WATCH

**Comment by AtaraxiaEta** [comment]
> 我把AutoLogin.yml里的协议切换到的安卓手表，然后就能登录了
> 
> protocol: ANDROID_WATCH

确实 我也是换成安卓手表的协议就暂时可以用了，其他协议暂时都不行。手表的协议如果之前群组有消息不提示的话要都打开消息提醒才能收到消息

**Comment by 1770460850** [comment]
换成了ANDROID_WATCH还是不行，但是MACOS可以
版本2.14.0

**Comment by just45** [comment]
用MACOS，用了两天就会提示版本过低

**Comment by YXHXianYu** [comment]
同，ANDROID_WATCH和MACOS都无法登入

**Comment by ahzvenol** [comment]
+1，已经在线的bot和本地客户端都被强制下线了，换用ANDROID_WATCH协议可以登录，但是这个协议没法正常接收戳一戳消息，MACOS协议还是报版本过低

**Comment by 1770460850** [comment]
MACOS用了两天也登不上了
![image](https://user-images.githubusercontent.com/46707123/223332953-de727974-8be6-459b-a3aa-990396d0ba42.png)

**Comment by weixin19961213** [comment]
+1，已经在线的bot和本地客户端都被强制下线了，换用ANDROID_WATCH协议可以登录，

**Comment by PEIKnifer** [comment]
+1同样是这个问题，所有协议都是这个问题，删除bots文件夹也没有用，基本什么方法都试了，版本暂时补丁也试了，还是这个版本问题

**Comment by cssxsh** [comment]
> +1同样是这个问题，所有协议都是这个问题，删除bots文件夹也没有用，基本什么方法都试了，版本暂时补丁也试了，还是这个版本问题

版本暂时补丁的readme你看了吗，要删 device.json 不然腾讯还是会因为设备信息拉黑你
