### ISSUE TITLE
登录失败，unknown login result type: 180

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2555]
### 问题描述

在遇到238之后更换协议到安卓手机遇到的

### 复现

未知

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2023-03-07 22:29:45 W/stderr: Exception in thread "main" java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = kotlin.Unit
2023-03-07 22:29:45 W/stderr: 	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:242)
2023-03-07 22:29:45 W/stderr: 	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
2023-03-07 22:29:45 W/stderr: 	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
2023-03-07 22:29:45 W/stderr: 	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
2023-03-07 22:29:45 W/stderr: 	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
2023-03-07 22:29:45 W/stderr: 	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
2023-03-07 22:29:45 W/stderr: 	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
2023-03-07 22:29:45 W/stderr: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
2023-03-07 22:29:45 W/stderr: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
2023-03-07 22:29:45 W/stderr: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
2023-03-07 22:29:45 W/stderr: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
2023-03-07 22:29:45 W/stderr: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
2023-03-07 22:29:45 W/stderr: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
2023-03-07 22:29:45 W/stderr: 	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
2023-03-07 22:29:45 W/stderr: 	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
2023-03-07 22:29:45 W/stderr: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-03-07 22:29:45 W/stderr: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-03-07 22:29:45 W/stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
2023-03-07 22:29:45 W/stderr: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
2023-03-07 22:29:45 W/stderr: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
2023-03-07 22:29:45 W/stderr: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
2023-03-07 22:29:45 I/Bot.2305339556: Bot cancelled: Bot closed
```

**Comment by MrXiaoM** [comment]
`TLVMap = kotlin.Unit` 大草

有笨比 [dumpTlvMap](https://github.com/mamoe/mirai/blob/dev/mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt#L249-L251) 忘了返回我不说是谁（

------

#1649 应该是类似的，可以看看。

**Comment by MrY-Cat** [comment]
> `TLVMap = kotlin.Unit` 大草
> 
> 有笨比 [dumpTlvMap](https://github.com/mamoe/mirai/blob/dev/mirai-core/src/commonMain/kotlin/network/protocol/packet/login/WtLogin.kt#L249-L251) 忘了返回我不说是谁（
> 
> #1649 应该是类似的，可以看看。

w(ﾟДﾟ)w

**Comment by Him188** [comment]
#2570
