### ISSUE TITLE
无法发送群长消息

### ISSUE THREAD

**Issue by boxlab** [mamoe/mirai#256]
## 问题

发送群长消息时遇到异常

```
java.lang.IllegalStateException: cannot upload group long message, failed on all servers.
	at net.mamoe.mirai.qqandroid.QQAndroidBotBase.lowLevelSendGroupLongOrForwardMessage$mirai_core_qqandroid(QQAndroidBot.common.kt:639)
	at net.mamoe.mirai.qqandroid.QQAndroidBotBase$lowLevelSendGroupLongOrForwardMessage$1.invokeSuspend(QQAndroidBot.common.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.contact.ContactJavaFriendlyAPI.sendMessage(ContactJavaFriendlyAPI.kt:345)
	at me.redneno.hoshinoharuka.lambda$onEnable$8(hoshinoharuka.java:361)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalAccessError: class net.mamoe.mirai.qqandroid.QQAndroidBotBase$lowLevelSendGroupLongOrForwardMessage$$inlined$run$lambda$1 tried to access method 'java.lang.Object net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImage(net.mamoe.mirai.qqandroid.network.QQAndroidClient, java.lang.String, int, byte[], java.lang.Object, int, byte[], int, kotlin.coroutines.Continuation)' (net.mamoe.mirai.qqandroid.QQAndroidBotBase$lowLevelSendGroupLongOrForwardMessage$$inlined$run$lambda$1 and net.mamoe.mirai.qqandroid.network.highway.HighwayHelper are in unnamed module of loader 'app')
Caused by: java.lang.IllegalAccessError: class net.mamoe.mirai.qqandroid.QQAndroidBotBase$lowLevelSendGroupLongOrForwardMessage$$inlined$run$lambda$1 tried to access method 'java.lang.Object net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImage(net.mamoe.mirai.qqandroid.network.QQAndroidClient, java.lang.String, int, byte[], java.lang.Object, int, byte[], int, kotlin.coroutines.Continuation)' (net.mamoe.mirai.qqandroid.QQAndroidBotBase$lowLevelSendGroupLongOrForwardMessage$$inlined$run$lambda$1 and net.mamoe.mirai.qqandroid.network.highway.HighwayHelper are in unnamed module of loader 'app')

	at net.mamoe.mirai.qqandroid.QQAndroidBotBase$lowLevelSendGroupLongOrForwardMessage$$inlined$run$lambda$1.invokeSuspend(QQAndroidBot.common.kt:615)
	at net.mamoe.mirai.qqandroid.QQAndroidBotBase$lowLevelSendGroupLongOrForwardMessage$$inlined$run$lambda$1.invoke(QQAndroidBot.common.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:78)
	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:57)
	at net.mamoe.mirai.qqandroid.QQAndroidBotBase.lowLevelSendGroupLongOrForwardMessage$mirai_core_qqandroid(QQAndroidBot.common.kt:613)
	... 15 more

```

## 如何复现

1. 发送一则长消息

**Comment by Him188** [comment]
已经修复，明天下午或晚上会发布 0.39.1
