### ISSUE TITLE
code=238, title=禁止登录, message=请使用手Q扫描二维码或短信登录

### ISSUE THREAD

**Issue by Takeoff0518** [mamoe/mirai#2568]
版本 2.13.4，MCL版本 2.1.2，协议ANDROID_WATCH，正常登录时突然提示滑块验证，在完成后提示 238，（使用 ANDROID_PAD 或者 ANDROID_PHONE 提示版本过低）

尝试使用 [fix-protocol-version](https://github.com/cssxsh/fix-protocol-version) 后仍然提示 238，已确定插件加载正常。

```
2023-03-11 19:05:10 I/Bot.2*****: [SliderCaptcha] 正在提交中...
2023-03-11 19:05:10 I/Bot.2*****: [SliderCaptcha] Submitting...
2023-03-11 19:05:10 I/Bot.2*****: Bot cancelled: Bot closed
Login failed: Error(bot=Bot(2*****), code=238, title=禁止登录, message=请使用手Q扫描二维码或短信登录。, errorInfo=)
2023-03-11 19:05:10 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2*****), code=238, title=禁止登录, message=请使用手Q扫描二维码或短信登录。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2*****), code=238, title=禁止登录, message=请使用手Q扫描二维码或短信登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by cssxsh** [comment]
`fix-protocol-version` 是用来处理 `code=235` 的

**Comment by zhaodice** [comment]
> `fix-protocol-version` 是用来处理 `code=235` 的

这个是code=238，可能需要参考一下gocq的协议

**Comment by cssxsh** [comment]
> > `fix-protocol-version` 是用来处理 `code=235` 的
> 
> 这个是code=238，可能需要参考一下gocq的协议

fix-protocol-version 是用来处理 code=235 的， 而且协议要选 `ANDROID_PAD` 或者 `ANDROID_PHONE`

**Comment by UlyssesZh** [comment]
巧了! 我也是, 昨天的时候 bot 突然下线 (`Server notifies offline. (dropped by StatSvc.ReqMSFOffline)`), 然后再次登录的时候的错误提示跟楼主一样. 我觉得可能是因为近期有风控?

**Comment by ChrisShen-github** [comment]
等一个解决办法

**Comment by Moyulingjiu** [comment]
等一个解决办法，我也是所有协议全部不行了，bot直接无法上线。

**Comment by YuMingC233** [comment]
插眼

**Comment by dragon0629** [comment]
扫码再不出，登录快要挂光了……

**Comment by Him188** [comment]
https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88

**Comment by Lin-XCC** [comment]
> https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88

问一下大概什么时候mirai-core会更新解决登录限制问题，或者说在java环境下要怎么用这个东西呢？

**Comment by YuMingC233** [comment]
> https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88

一、下载该插件并放入 `mirai/plugins` 文件夹下
https://github.com/cssxsh/fix-protocol-version

二、删除 `mirai/bots` 文件夹

三、更改 `mirai/config/Console/AutoLogin.yml` 中的登录协议为MACOS

四、按照以往流程正常开启并登录mirai。

这个是临时解决方案，后续可能会失效。

**Comment by Him188** [comment]
#2570
