### ISSUE TITLE
报错的提示信息要我提交  这个问题没有复现  不重要

### ISSUE THREAD

**Issue by JingyuNankin** [mamoe/mirai#2573]
### 问题描述

在一次启动时，报错如下，提示我到这里反馈。
是在一次关闭QQ机器人之后，立即启动QQ机器人，产生的提示。该Bot不是管理员或群主，并非刚刚加入或离开该群。

```
2023-03-15 00:54:06 E/Group: ContextualBugReportException(message=在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 640437751
groupUin: 640437751
membersCount: 250
botId: 2543434165
owner: 420635989, cause=null)
ContextualBugReportException(message=在 GroupImpl 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai: https://github.com/mamoe/mirai/issues/new/choose   并告知此时 Bot 是否为群管理员或群主, 和是否刚刚加入或离开这个群 调试信息: groupId: 640437751
groupUin: 640437751
membersCount: 250
botId: 2543434165
owner: 420635989, cause=null)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException(contextualBugReportException.kt:26)
	at net.mamoe.mirai.internal.message.ContextualBugReportExceptionKt.contextualBugReportException$default(contextualBugReportException.kt:20)
	at net.mamoe.mirai.internal.contact.GroupImplKt.GroupImpl(GroupImpl.kt:105)
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.addGroupToBot(ContactUpdater.kt:252)
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.access$addGroupToBot(ContactUpdater.kt:73)
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl$addGroupToBot$1.invokeSuspend(ContactUpdater.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
弹出该报错之后，无法在该群使用该机器人的功能。在终端可以看到在该群触发的消息，但是响应消息时，出现以下报错。
```
Exception in thread "DefaultDispatcher-worker-11" kotlin.UninitializedPropertyAccessException: lateinit property botAsMember has not been initialized
	at net.mamoe.mirai.internal.contact.CommonGroupImpl.getBotAsMember(GroupImpl.kt:150)
	at net.mamoe.mirai.internal.contact.CommonGroupImpl.getBotAsMember(GroupImpl.kt:135)
	at net.mamoe.mirai.contact.Group.getBotMuteRemaining(Group.kt:104)
	at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage$suspendImpl(GroupImpl.kt:443)
	at net.mamoe.mirai.internal.contact.CommonGroupImpl.sendMessage(GroupImpl.kt)
	at com.icedata.sika.bridge.SikaContact.sendMessage(SikaContact.kt:44)
	at com.icedata.sika.bridge.SikaContact.sendMessage(SikaContact.kt:56)
	at com.icedata.sika.core.Command.sendSimply(Command.kt:30)
	at com.icedata.hantang.launcher.AmberLauncherKt$main$10.invokeSuspend(AmberLauncher.kt:222)
	at com.icedata.hantang.launcher.AmberLauncherKt$main$10.invoke(AmberLauncher.kt)
	at com.icedata.hantang.launcher.AmberLauncherKt$main$10.invoke(AmberLauncher.kt)
	at com.icedata.sika.core.CommandProcessor$3.invokeSuspend(CommandProcessor.kt:21)
	at com.icedata.sika.core.CommandProcessor$3.invoke(CommandProcessor.kt)
	at com.icedata.sika.core.CommandProcessor$3.invoke(CommandProcessor.kt)
	at com.icedata.sika.core.AbstractAsyncProcessor.execute$suspendImpl(Processor.kt:67)
	at com.icedata.sika.core.AbstractAsyncProcessor.execute(Processor.kt)
	at com.icedata.sika.core.CommandProcessorBus$broadcast$2.invokeSuspend(CommandProcessorBus.kt:21)
	at com.icedata.sika.core.CommandProcessorBus$broadcast$2.invoke(CommandProcessorBus.kt)
	at com.icedata.sika.core.CommandProcessorBus$broadcast$2.invoke(CommandProcessorBus.kt)
	at com.icedata.sika.util.LockAsyncExtendKt$readAsync$2$1.invokeSuspend(LockAsyncExtend.kt:10)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6208fcdc, Dispatchers.Default]
```
该机器人在其它群、私聊正常。
再次启动该机器人，无相关报错，无法复现问题。
若不是报错内容中写到要提交，我也不会提交。

### 复现

暂时无法复现。不影响我后续的使用。

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

```
plugins {
    java
    kotlin("jvm") version "1.6.21"
    kotlin("plugin.serialization") version "1.6.21"
}
```

```
    val miraiVersion = "2.14.0"
    api("net.mamoe", "mirai-core-api", miraiVersion)
    runtimeOnly("net.mamoe", "mirai-core", miraiVersion)
```
使用Kotlin开发、Gradle进行包管理的QQ机器人。

**Comment by Him188** [comment]
#1977
