### ISSUE TITLE
依赖未找到

### ISSUE THREAD

**Issue by bin-tenkuu** [mamoe/mirai#2578]
### 问题描述

在使用ktorserver时发现，调用序列化包里`EmptySerializersModule()`这个方法后会报错：
```log
2023-03-19 00:10:36 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while loading my.ktbot.binbot v0.1
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:258)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:35)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:50)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:93)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:149)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:178)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:464)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:168)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:167)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:52)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:89)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:79)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:101)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:109)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:148)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:189)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:146)
	at org.itxtech.mcl.Loader.start(Loader.java:189)
	at org.itxtech.mcl.Loader.main(Loader.java:79)
Caused by: java.lang.NoSuchMethodError: 'kotlinx.serialization.modules.SerializersModule kotlinx.serialization.modules.SerializersModuleBuildersKt.EmptySerializersModule()'
	at MainBot-1.0.0.mirai2.jar//my.ktbot.PluginMain.onLoad(PluginMain.kt:33)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:248)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:256)
	... 23 more

2023-03-19 00:10:36 D/main: SHUTDOWN DAEMON STARTED.........
2023-03-19 00:10:37 D/main: [exitProcessAndForceHalt] called with code 0
2023-03-19 00:10:37 D/main: [exitProcessAndForceHalt] isShutdowning = false

进程已结束,退出代码0
```

### 复现

导入
```kts
	implementation("org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.5.0")
	implementation("org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.5.0")
```
插件加载：
```kotlin
    override fun PluginComponentStorage.onLoad() {
        EmptySerializersModule() // error
    }

```

### mirai-core 版本

2.14.0

### bot-protocol

ANDROID_PHONE

**Comment by cssxsh** [comment]
kotlinx-serialization 属于特殊依赖
所以不会走插件定义的版本，而是走 mirai-console 内置的
https://github.com/mamoe/mirai/blob/4d41e53bf3cb0419a4f60230f52a8336689e6f77/buildSrc/src/main/kotlin/Versions.kt#L39-L42

**Comment by Him188** [comment]
2.15.0-M1 不出意外会更新依赖版本

**Comment by bin-tenkuu** [comment]
我看了一下版本1.4.1有这个函数。1.3.3的版本我这好像有其他的库依赖了高版本的，降不下去

**Comment by Him188** [comment]
fixed in https://github.com/mamoe/mirai/commit/427c37e6499d089d9b64c310a40de600af9745bf
