### ISSUE TITLE
在安卓系统上出现 java.lang.StackOverflowError: stack size 1037KB

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai#2586]
### 问题描述

启动Console时，执行到此处 L305 处
https://github.com/mamoe/mirai/blob/cb603adbfcc601b0b33e01ab43541576c6fff6cc/mirai-console/backend/mirai-console/src/internal/plugin/JvmPluginInternal.kt#L305
出现堆栈死循环直到堆栈溢出

### 复现

在安卓系统启动Console服务即可出现。报告：Failed to init MiraiConsole.

### mirai-core 版本

1.15.0-M1

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
java.lang.StackOverflowError: stack size 1037KB
	at kotlin.coroutines.jvm.internal.RestrictedContinuationImpl.<init>(ContinuationImpl.kt:83)
	at kotlin.coroutines.jvm.internal.RestrictedSuspendLambda.<init>(ContinuationImpl.kt:144)
	at kotlinx.coroutines.JobSupport$children$1.<init>(Unknown Source:3)
	at kotlinx.coroutines.JobSupport$children$1.create(Unknown Source:4)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:124)
	at kotlin.sequences.SequencesKt__SequenceBuilderKt.iterator(SequenceBuilder.kt:38)
	at kotlin.sequences.SequencesKt__SequenceBuilderKt$sequence$$inlined$Sequence$1.iterator(Sequences.kt:681)
	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$2.invoke(_Sequences.kt:854)
	at kotlin.sequences.SequencesKt___SequencesKt$flatMap$2.invoke(_Sequences.kt:854)
    at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	//...非常多，完全在ensureItemIterator和hasNext之间踢皮球
    at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
		at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:315)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.indexOf(_Sequences.kt:190)
	at kotlin.sequences.SequencesKt___SequencesKt.contains(_Sequences.kt:24)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.<init>(JvmPluginInternal.kt:305)
	at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.<init>(AbstractJvmPlugin.kt:37)
	at net.mamoe.mirai.console.plugin.jvm.KotlinPlugin.<init>(KotlinPlugin.kt:23)
	at net.mamoe.mirai.console.plugin.jvm.KotlinPlugin.<init>(KotlinPlugin.kt:20)
	at astral.dice.mirai.MiraiPluginLoader.<init>(MiraiPluginLoader.kt:17)
	at astral.dice.mirai.MiraiPluginLoader.<clinit>(Unknown Source:2)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:51)
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServices(PluginServiceHelper.kt:42)
	at org.mirai.zhao.dice.console.lower.DexPluginLoader$extractPlugins$findAllInstances$2.invoke(DexPluginLoader.kt:87)
	at org.mirai.zhao.dice.console.lower.DexPluginLoader$extractPlugins$findAllInstances$2.invoke(DexPluginLoader.kt:82)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:314)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:316)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:828)
	at org.mirai.zhao.dice.console.lower.DexPluginLoader.extractPlugins(DexPluginLoader.kt:105)
	at net.mamoe.mirai.console.plugin.loader.AbstractFilePluginLoader.listPlugins(FilePluginLoader.kt:53)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(Unknown Source:4)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:195)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:141)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:151)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:302)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:500)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService.startConsole$lambda$5$lambda$4(MiraiCoreConsoleService.kt:392)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService.$r8$lambda$2sBgunNcKuvB_2O6iymbDzTubFg(Unknown Source:0)
	at org.mirai.zhao.dice.console.MiraiCoreConsoleService$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by zhaodice** [comment]
调试跟踪到了这里"_Sequences.kt":

```
@file:kotlin.jvm.JvmMultifileClass
@file:kotlin.jvm.JvmName("SequencesKt")

package kotlin.sequences
...
public fun <@kotlin.internal.OnlyInputTypes T> Sequence<T>.indexOf(element: T): Int {
    var index = 0
    for (item in this) {
        checkIndexOverflow(index)
        if (element == item)
            return index
        index++
    }
    return -1
}
```
其中`for (item in this) {` 循环了2次，第一次index = 0，第二次index=1，然后在index=1的情况下就死掉了（未执行到checkIndexOverflow），推测和for循环的循环体无关，是for循环指令本身出了问题（具体可能需要反编译看它编译成了什么）

**Comment by sandtechnology** [comment]
很明显是编译优化炸了（

**Comment by zhaodice** [comment]
> 很明显是编译优化炸了（

没有开混淆，就单纯Debug模式下编译的，这也搞优化就有点那啥了（

**Comment by sandtechnology** [comment]
哦 kt 1.18.0 的问题也有可能 你可以看看youtrack上面有没有issue 没有去提一下

**Comment by Him188** [comment]
然而桌面 JVM 的 test 是过的，test 会加载多个插件测试

**Comment by zhaodice** [comment]
安卓坑点挺多的....也不知道是不是编译器整的，主要是为了升级到kotlin 1.8，被迫升级gradle 8.0看看能不能强制退回去看看

**Comment by Him188** [comment]
at astral.dice.mirai.MiraiPluginLoader.<init>(MiraiPluginLoader.kt:17)

你是不是 coroutineContext 有问题

**Comment by Him188** [comment]
kt 1.8没更新sequence，不大可能是kt问题

**Comment by zhaodice** [comment]
> at astral.dice.mirai.MiraiPluginLoader.(MiraiPluginLoader.kt:17)
> 
> 你是不是 coroutineContext 有问题

MiraiPluginLoader是个插件，思，难道是插件炸了吗
但是第17行是这个：
```
object MiraiPluginLoader : KotlinPlugin(
```

**Comment by zhaodice** [comment]
感觉不会出什么问题吧...至少以前的mirai版本是没问题的
```
object MiraiPluginLoader : KotlinPlugin(
        JvmPluginDescription(
                id = "zhao.dice",
                version = "1.0.0",
        ) {
            name("ZhaoDice")
            author("赵怡然")
        }
){
    private var enabled=false
    override fun onEnable() {
        if(enabled)
            return
        try {
            PluginUtil.register(this)
        }catch (e:Throwable){
            e.printStackTrace()
        }
        enabled =true
    }

}
```

**Comment by zhaodice** [comment]
我禁用插件试试看

**Comment by zhaodice** [comment]
暂时排除mirai的问题，因为禁用插件后似乎正常了，我再研究一下，有变化再open

**Comment by zhaodice** [comment]
还是有点问题，插件没有做任何事情，之所以报错包含插件的堆栈是因为插件含有“KotlinPlugin”作为初始化的父类，而KotlinPlugin出了问题，所以问题可能出在类加载器上，是上下文不对还是...先把问题摆在这里吧

**Comment by zhaodice** [comment]
问题可能是因为我自己实现了Console，之前没有什么问题，但最近mirai的版本似乎加了
pluginManager的coroutineContext ？
我没有很好处理着一块所以炸的？我猜的，如果可以的话可以给点建议应该怎么改吗，似乎没找到文档，现在就翻注释和源码的样子

**Comment by Him188** [comment]
@Karlatemp

**Comment by zhaodice** [comment]
问题解决，参考了这句：
https://github.com/mamoe/mirai/blob/cb78ed34a5719c209e136747a6323d8c424e7e1e/mirai-console/backend/mirai-console/src/MiraiConsoleImplementation.kt#L354
```
public fun createDefaultJvmPluginLoader(coroutineContext: CoroutineContext): JvmPluginLoader =
            BuiltInJvmPluginLoaderImpl(coroutineContext + MiraiConsole.pluginManager.impl.coroutineContext.job)
```

我意识到，初始化`JvmPluginLoader`的时候，传递的`coroutineContext`需要加
` + MiraiConsole.pluginManager.impl.coroutineContext.job`

于是我抱着试试看的态度，给`coroutineContext`加了这个东西，奇迹般正常了，之前的版本这样是可以的，这个新设计是故意的还是不小心（bushi

**Comment by zhaodice** [comment]
总结：
初始化传递给`JvmPluginLoader`的`CoroutineContext`必须加 ` + MiraiConsole.pluginManager.impl.coroutineContext.job`，否则就会在
```
 check(allJobs.contains(job)) { 
```
的时候爆炸

先不close，要不先看看这个情况，要不要加个判断什么的，死循环也不是个事，以免后人踩坑。
