### ISSUE TITLE
扫码登录后提示code=235

### ISSUE THREAD

**Issue by jushe** [mamoe/mirai#2588]
### 问题描述

扫码后登录提示code=235尽快升级qq

### 复现

版本为2.15.0-M1，协议为MACOS，使用扫码登录后确定登录后出现。

### mirai-core 版本

2.15.0-M1

### bot-protocol

MACOS

### 系统日志

```text
2023-03-23 17:45:35 D/Net 2187875153: querying qrcode state.
2023-03-23 17:45:35 V/Net 2187875153: Send: wtlogin.trans_emp
2023-03-23 17:45:35 D/Net 2187875153: qrcode state changed: WAITING_FOR_SCAN
2023-03-23 17:45:35 I/Bot 2187875153: [QRCodeLogin] 等待扫描二维码中
2023-03-23 17:45:35 I/Bot 2187875153: [QRCodeLogin] Waiting for scanning qrcode.
2023-03-23 17:45:35 V/Net 2187875153: Recv: wtlogin.trans_emp
2023-03-23 17:45:40 D/Net 2187875153: querying qrcode state.
2023-03-23 17:45:40 V/Net 2187875153: Send: wtlogin.trans_emp
2023-03-23 17:45:40 V/Net 2187875153: Recv: wtlogin.trans_emp
2023-03-23 17:45:45 D/Net 2187875153: querying qrcode state.
2023-03-23 17:45:45 V/Net 2187875153: Send: wtlogin.trans_emp
2023-03-23 17:45:45 V/Net 2187875153: Recv: wtlogin.trans_emp
2023-03-23 17:45:45 D/Net 2187875153: qrcode state changed: WAITING_FOR_CONFIRM
2023-03-23 17:45:45 I/Bot 2187875153: [QRCodeLogin] 扫描完成，请在手机 QQ 确认登录
2023-03-23 17:45:45 I/Bot 2187875153: [QRCodeLogin] Scan complete. Please confirm login.
2023-03-23 17:45:50 D/Net 2187875153: querying qrcode state.
2023-03-23 17:45:50 V/Net 2187875153: Send: wtlogin.trans_emp
2023-03-23 17:45:50 V/Net 2187875153: Recv: wtlogin.trans_emp
2023-03-23 17:45:50 D/Net 2187875153: qrcode state changed: CONFIRMED
2023-03-23 17:45:50 I/Bot 2187875153: [QRCodeLogin] 已确认登录
2023-03-23 17:45:50 I/Bot 2187875153: [QRCodeLogin] Login confirmed.
2023-03-23 17:45:50 V/Net 2187875153: Send: wtlogin.login(9:qrcode-login)
2023-03-23 17:45:50 V/Net 2187875153: Recv: wtlogin.login
2023-03-23 17:45:50 W/Net 2187875153: Failed with auth method: QRCode
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2187875153), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-03-23 17:45:50 V/Net 2187875153: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2187875153), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
2023-03-23 17:45:50 D/Net 2187875153: CAS: Consumed(LatchImpl(CompletableDeferredImpl{Active}@53170d76)) -> ProducerReady: true
2023-03-23 17:45:50 D/Net 2187875153: CAS: ProducerReady -> Producing(deferred.completed=false): true
2023-03-23 17:45:50 V/Net 2187875153: [AuthControl/auth] Authorization failed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2187875153), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
2023-03-23 17:45:50 D/Net 2187875153: CAS: Producing(deferred.completed=false) -> Finished(Producing(deferred.completed=false), net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2187875153), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)): true
2023-03-23 17:45:50 W/Net 2187875153: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException

2023-03-23 17:45:50 I/Net 2187875153: ECDH key is valid.
2023-03-23 17:45:50 V/Net 2187875153: [AuthControl/acquire] Acquiring auth method
2023-03-23 17:45:50 D/Net 2187875153: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.internal.network.auth.ProducerFailureException]@2147320355
2023-03-23 17:45:50 W/Net 2187875153: Failed with auth method: Error[net.mamoe.mirai.internal.network.auth.ProducerFailureException]@2147320355
net.mamoe.mirai.internal.network.auth.ProducerFailureException
        at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
        at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2187875153), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        ... 5 more

2023-03-23 17:45:50 W/Net 2187875153: Exception in resumeConnection.
net.mamoe.mirai.internal.network.auth.ProducerFailureException
        at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
        at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2187875153), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                ... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2187875153), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)]

2023-03-23 17:45:50 W/Net 2187875153: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.auth.ProducerFailureException)
Exception in thread "main" net.mamoe.mirai.internal.network.auth.ProducerFailureException
        at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
        at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2187875153), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                ... 5 more
        Suppressed: net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2187875153), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)]
```

**Comment by jushe** [comment]
使用android_watch协议的话扫码会出现使用同一wifi或者同一热点登录的提示（bot部署在了服务器上）

**Comment by cssxsh** [comment]
你可以试试删除 `bots/<qq>/device.json` 后重新尝试登陆

**Comment by StageGuard** [comment]
暂时定为一般 235 问题，请尝试删除 device.json，更改协议 或 尝试同一网络登录等方式。

**Comment by jushe** [comment]
> 你可以试试删除 `bots/<qq>/device.json` 后重新尝试登陆

还是不行，报错和之前一样。

**Comment by jushe** [comment]
> 暂时定为一般 235 问题，请尝试删除 device.json，更改协议 或 尝试同一网络登录等方式。

删除device.json依然是一样的报错。修改协议的话，扫码目前只支持macos和android_watch协议。其他登录方式无法登录。
使用android_watch协议在同一网络下登录成功，但是需要将bot部署到服务器上的场景时，由于云端和手机所在网络不一致无法登录。

**Comment by StageGuard** [comment]
> 删除device.json依然是一样的报错。修改协议的话，扫码目前只支持macos和android_watch协议。其他登录方式无法登录。 使用android_watch协议在同一网络下登录成功，但是需要将bot部署到服务器上的场景时，由于云端和手机所在网络不一致无法登录。

尝试同一网络登录成功后将登录后的凭证传到部署服务器上

**Comment by jushe** [comment]
> > 删除device.json依然是一样的报错。修改协议的话，扫码目前只支持macos和android_watch协议。其他登录方式无法登录。 使用android_watch协议在同一网络下登录成功，但是需要将bot部署到服务器上的场景时，由于云端和手机所在网络不一致无法登录。
> 
> 尝试同一网络登录成功后将登录后的凭证传到部署服务器上

有效，已解决问题，感谢
