### ISSUE TITLE
登陆失败code=45,235,237等问题(注意不是238)

### ISSUE THREAD

**Issue by linux-rm** [mamoe/mirai#2597]
### 问题描述

我的机器人账号可以正常在真Android手机和linux客户端(linux QQ 3)登陆,
但用mirai就会`code=45,235,237`
device.json使用的aoki生成的

希望能出个linux协议并支持扫码登陆,二维码直接打印在终端 __`(最希望出的功能)`__:
```
$ pip install qrcode
#......
$ qr https://mirai.mamoe.net
█████████████████████████████████
█████████████████████████████████
████ ▄▄▄▄▄ █▄    █▄▄ █ ▄▄▄▄▄ ████
████ █   █ █▀▀ ▄▀▀ ▄▀█ █   █ ████
████ █▄▄▄█ █ ▄▀█▄ ▄▄ █ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ ▀▄▀▄█ ▀ █▄▄▄▄▄▄▄████
████ ▀▀█ ▀▄▄▄ █▀ █ ▀▀▄▄▄  █▀▄████
████ █▀ ▀ ▄▄▄ ▄▄▀▄▄ █▄▄ ▀▄ ▀█████
████   █ ▀▄█▄█▄█▄█▀ ▀ ▄▄▀▄▄ ▄████
██████▄▄▀▄▄█▄▄ █▀▄▄▄▄ ▀  ▄ ▀█████
████▄▄▄██▄▄▄▀██▄▀▀▀▄ ▄▄▄ ▄▄██████
████ ▄▄▄▄▄ █▄▄█ ▄█ ▀ █▄█ ▀▀█▀████
████ █   █ █▄█▄█▄▀█▀▄   ▄▄   ████
████ █▄▄▄█ ██▄▀█▀█▄ █ ▄▀▀ ▀ █████
████▄▄▄▄▄▄▄█▄▄▄▄▄▄▄▄█▄▄███▄▄▄████
█████████████████████████████████
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
```

### 复现

$ rm -rf bots
$ scp -P 8022 -r termux@192.168.x.x:/sdcard/Android/top.mrxiaom.mirai.aoki/files/AokiMirai/bots
$ ./mcl
# 详见下方日志

### mirai-core 版本

iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8

### bot-protocol

ANDROID_PHONE

### 其他组件版本

> /status
Running MiraiConsole v2.14.0, built on 2023-02-06 14:25:21.
Frontend Terminal: version 2.14.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: mirai-api-http v2.9.1, Chat Command v0.5.0, fix-protocol-version v1.3.0, MCL Addon v2.1.1

Object Pending Finalization Count: 0
                 committed |  init   |  used   |  max  
    Heap Memory:  108.0MB  | 250.0MB | 53.12MB | 3.89GB
Non-Heap Memory:  74.87MB  | 7.31MB  | 73.28MB |   -1  
> 

### 系统日志

```text
$ ./mcl
  14:14:04 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  14:14:04 [INFO] Runtime: OpenJDK 64-Bit Server VM 19.0.2 (arch: 64)
  14:14:04 [INFO] https://github.com/iTXTech/mirai-console-loader
  14:14:04 [INFO] This program is licensed under GNU AGPL v3
  14:14:06 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653
 
MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  14:14:06 [INFO] Verifying "net.mamoe:mirai-console" v2.14.0
  14:14:08 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.14.0
  14:14:08 [INFO] Verifying "net.mamoe:mirai-core-all" v2.14.0
  14:14:09 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
  14:14:09 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" v1.64
  14:14:09 [INFO] Verifying "net.mamoe:mirai-api-http" v2.9.1
  14:14:09 [INFO] Verifying "net.mamoe:chat-command" v0.5.1
  14:14:09 [WARN] Package "net.mamoe:chat-command" requires "net.mamoe:mirai-console" version 2.0-RC. Current version is 2.14.0
2023-03-26 14:14:10 I/main: Starting mirai-console...
2023-03-26 14:14:10 I/main: 

==================================[ Mirai consosle 2.14.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-03-26 14:14:10 I/main: Backend: version 2.14.0, built on 2023-02-06 14:25:21.
2023-03-26 14:14:10 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-03-26 14:14:10 I/main: Welcome to visit https://mirai.mamoe.net/
2023-03-26 14:14:11 I/plugin: Successfully loaded plugin mirai-api-http v2.9.1
2023-03-26 14:14:11 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2023-03-26 14:14:11 W/fix-protocol-version: Mirai版本低于预期，将升级协议版本
2023-03-26 14:14:11 I/plugin: Successfully loaded plugin fix-protocol-version v1.3.0
2023-03-26 14:14:11 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-03-26 14:14:11 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-03-26 14:14:12 W/mirai-api-http: USING INITIAL KEY, please edit the key
2023-03-26 14:14:12 I/Mirai HTTP API: ********************************************************
2023-03-26 14:14:12 I/MahKtorAdapter[http]: Autoreload is disabled because the development mode is off.
2023-03-26 14:14:12 I/MahKtorAdapter[http]: Application started in 0.118 seconds.
2023-03-26 14:14:12 I/http adapter: >>> [http adapter] is listening at http://localhost:8080
2023-03-26 14:14:12 I/MahKtorAdapter[http]: Responding at http://localhost:8080
2023-03-26 14:14:12 I/Mirai HTTP API: Http api server is running with verifyKey: INITKEYHj2ntFBu
2023-03-26 14:14:12 I/Mirai HTTP API: adaptors: [http]
2023-03-26 14:14:12 I/Mirai HTTP API: ********************************************************
2023-03-26 14:14:12 I/fix-protocol-version: 当前各协议版本日期: 
ANDROID_PHONE   8.9.33.10335   2023-01-13T16:51:38+08:00
ANDROID_PAD   8.9.33.10335   2023-01-13T16:51:38+08:00
ANDROID_WATCH   2.0.5   2019-06-03T20:25:31+08:00
IPAD   8.9.33.614   2021-12-31T11:36:26+08:00
MACOS   5.8.9   2020-07-27T15:50:08+08:00

2023-03-26 14:14:12 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-03-26 14:14:12 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-03-26 14:14:12 I/main: 4 plugin(s) enabled.
2023-03-26 14:14:12 I/main: Auto-login 1663349203, protocol: ANDROID_PHONE, heartbeatStrategy: STAT_HB
2023-03-26 14:14:13 I/Bot.1663349203: Calculating type 2 PoW, it can take some time....
2023-03-26 14:14:13 I/Bot.1663349203: Got PoW result, cost: 72 ms
2023-03-26 14:14:13 I/Bot.1663349203: [SliderCaptcha] 需要滑动验证码, 请按照以下链接的步骤完成滑动验证码, 然后输入获取到的 ticket
2023-03-26 14:14:13 I/Bot.1663349203: [SliderCaptcha] Slider captcha required. Please solve the captcha with following link. Type ticket here after completion.
2023-03-26 14:14:13 I/Bot.1663349203: [SliderCaptcha] @see https://github.com/project-mirai/mirai-login-solver-selenium
2023-03-26 14:14:13 I/Bot.1663349203: [SliderCaptcha] @see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
2023-03-26 14:14:13 I/Bot.1663349203: [SliderCaptcha] 或者输入 TxCaptchaHelper 来使用 TxCaptchaHelper 完成滑动验证码
2023-03-26 14:14:13 I/Bot.1663349203: [SliderCaptcha] Or type `TxCaptchaHelper` to resolve slider captcha with TxCaptchaHelper.apk
2023-03-26 14:14:13 I/Bot.1663349203: [SliderCaptcha] Captcha link: https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=1663349203&sid=7265841999329092277&cap_cd=fMLKFyV_kPrghZ8Bid7OQXAqZZBL8cA8g80fDhzBaccT0rOFI6W44A**&clientype=1&apptype=2
LOGIN> > t03ET-BWDtBJOmmg-RYf8NwdVc5-gyXxMl0lKQYCmuvmCcHwhwKxGpyrpeJWw-5nECV76W-ZaIQgIzSLSSLcQSu72unIGt7cHyTE6uH05UCy_eV2bMb3k8H3mzVIgd3tdxW0urPDoby9Ufb6BMpfJ0aGzwAZXRUM1QMtFc8bEyrCwEaTcOQcdsh38pp0GSWLmZnsOaWbWwMV2c*

2023-03-26 14:14:44 I/Bot.1663349203: [SliderCaptcha] 正在提交中...
2023-03-26 14:14:44 I/Bot.1663349203: [SliderCaptcha] Submitting...
2023-03-26 14:14:44 E/main: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1663349203), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1663349203), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-03-26 14:14:44 I/main: mirai-console started successfully.
2023-03-26 14:14:44 I/Bot.1663349203: Bot cancelled: Bot closed
> /status
Running MiraiConsole v2.14.0, built on 2023-02-06 14:25:21.
Frontend Terminal: version 2.14.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: mirai-api-http v2.9.1, Chat Command v0.5.0, fix-protocol-version v1.3.0, MCL Addon v2.1.1

Object Pending Finalization Count: 0
                 committed |  init   |  used   |  max  
    Heap Memory:  108.0MB  | 250.0MB | 53.12MB | 3.89GB
Non-Heap Memory:  74.87MB  | 7.31MB  | 73.28MB |   -1  
>
```

### 网络日志

```text
2023-03-26 14:14:13 V/Net 1663349203: Invalidate caches because hash file not available.
2023-03-26 14:14:13 V/Net 1663349203: No server list cached.
2023-03-26 14:14:13 I/Net 1663349203: ECDH key is invalid, start to fetch ecdh public key from server.
2023-03-26 14:14:13 I/Net 1663349203: Successfully fetched ecdh public key from server.
2023-03-26 14:14:13 V/Net 1663349203: Send: wtlogin.login(9:password-login)
2023-03-26 14:14:13 V/Net 1663349203: Recv: wtlogin.login
2023-03-26 14:14:44 V/Net 1663349203: Send: wtlogin.login(2:submit-slider)
2023-03-26 14:14:44 V/Net 1663349203: Recv: wtlogin.login
2023-03-26 14:14:44 W/Net 1663349203: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1663349203), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1663349203), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	... 9 more

2023-03-26 14:14:44 W/Net 1663349203: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1663349203), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=))
```

**Comment by StageGuard** [comment]
多次尝试 #2570 提供的解决方案

**Comment by huanmeng-qwq** [comment]
同，[提供的解决方法](https://[mirai.mamoe.net](https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88)/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88)网页也打不开，确定不是网络问题

**Comment by linux-rm** [comment]
改为MACOS终于正常了
