### ISSUE TITLE
长信息和xml信息发送失败

### ISSUE THREAD

**Issue by XuuChannel** [mamoe/mirai#2604]
### 问题描述

大约超过10行的文字信息以及xml信息发送的时候正常返回code0
但是在群聊里没有刚发出的消息 他人看不到

此外 发送json会提示
{"code":500,"msg":"Failed sending message to Group(), reason=LIMITED_MESSAGING.
不知道是否与此有关

### 复现

↑

### mirai-core 版本

2.14.0

### bot-protocol

MACOS

### 其他组件版本

mirai-api-http v2.7.1, Chat Command v0.5.0, MCL Addon v2.1.1
通过python(requests)与http api交互

**Comment by XuuChannel** [comment]
补充：重启mcl后偶尔发送成功 时间久了后还是会失效

**Comment by kurikomoe** [comment]
相同情况，疑似是被 shadow ban 了。目前文字转图片后发送没问题。

环境说明：
mirai 运行于位于境外的vps，新注册的 QQ 号，Android QQ 登录过，已提交身份证过实名。
使用 fix protocol 插件只能用 macos 协议登录。
2.15.0-M1 境内测试，能用 android watch 扫码登录，境外登录失败。

出现问题的 device.json 在之前一段时间都是正常的（大概新号注册半周左右，随后长段文字会被屏蔽）

**Comment by Him188** [comment]
@XuuChannel 试试 2.15.0-M1 用扫描登录还会不会有这种情况

**Comment by XuuChannel** [comment]
> @XuuChannel 试试 2.15.0-M1 用扫描登录还会不会有这种情况

没搞懂怎么开启扫码登陆（小白

**Comment by kurikomoe** [comment]
> > @XuuChannel 试试 2.15.0-M1 用扫描登录还会不会有这种情况
> 
> 没搞懂怎么开启扫码登陆（小白

自己改了一下 terminal，默认使用扫码登录。
解压附件 test.zip，之后去 [repo](https://repo.maven.apache.org/maven2/net/mamoe/mirai-core-all/2.15.0-M1/) 上下载  `mirai-core-all-2.15.0-M1-all.jar`  放在 libs 目录中。
linux 的话直接运行 mcl.sh，windows 参考 [url](https://docs.mirai.mamoe.net/console/Run.html#%E6%89%8B%E5%8A%A8%E9%85%8D%E7%BD%AE%E7%8B%AC%E7%AB%8B%E5%90%AF%E5%8A%A8)。

使用命令 `login <QQ>  <随意字符>  [ANDROID_WATCH 或 MACOS]` 。

因为关闭了其他登陆方式，所以只有扫码登录了。

附件：
[test.zip](https://github.com/mamoe/mirai/files/11118206/test.zip)

**Comment by MrXiaoM** [comment]
> > @XuuChannel 试试 2.15.0-M1 用扫描登录还会不会有这种情况
> 
> 没搞懂怎么开启扫码登陆（小白

https://github.com/MrXiaoM/mirai-console-dev-qrlogin

**Comment by XuuChannel** [comment]
扫码登陆不上
```
2023-04-03 06:49:48 E/QRLogin: net.mamoe.mirai.internal.network.auth.ProducerFailureException
net.mamoe.mirai.internal.network.auth.ProducerFailureException
        at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
        at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2646593791), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                ... 5 more
        Suppressed: net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2646593791), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)]

2023-04-03 06:49:48 I/Bot.2646593791: Bot cancelled: Bot closed
2023-04-03 06:49:48 V/Bot.2646593791: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Failure@7757025d
```

**Comment by kurikomoe** [comment]
> 

ANDROID_WATCH + 同一个 wifi/局域网 下 + 境内？

**Comment by XuuChannel** [comment]
> > 
> 
> ANDROID_WATCH + 同一个 wifi/局域网 下 + 境内？

不在境内（）

**Comment by Him188** [comment]
等更多人汇报信息

**Comment by landall** [comment]
> 等更多人汇报信息

我有完全一样的问题。App、Json类型的消息报错。短Text消息没问题。

**Comment by landall** [comment]
2023-07-30 14:56:10 E/Mah Debug: net.mamoe.mirai.contact.SendMessageFailedException: Failed sending message to Group(871301822), reason=LIMITED_MESSAGING. Tips: 问题原因可能是账号被多次举报或被服务器认为不安全. 若账号在官方客户端也无法发出消息, 可尝试用手机 QQ 登录后访问 https://accounts.qq.com/safe/message/unlock?lock_info=5_5 解冻.
net.mamoe.mirai.contact.SendMessageFailedException: Failed sending message to Group(871301822), reason=LIMITED_MESSAGING. Tips: 问题原因可能是账号被多次举报或被服务器认为不安全. 若账号在官方客户端也无法发出消息, 可尝试用手机 QQ 登录后访问 https://accounts.qq.com/safe/message/unlock?lock_info=5_5 解冻.
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:165)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.access$sendSinglePacket(GeneralMessageSenderProtocol.kt:52)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender$sendSinglePacket$1.invokeSuspend(GeneralMessageSenderProtocol.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by landall** [comment]
我目前看到的表现是这样的：
   往群里发Json会报这个错。
   往好友发Json会直接没反应。
   往群里或者好友发App消息，会直接没反应，不知道是不是json拼得有逻辑问题。

**Comment by Him188** [comment]
我记得这些东西现在要签名了，不能简单拼接

**Comment by landall** [comment]
> 我记得这些东西现在要签名了，不能简单拼接

是的，所有的Json和App信息，请求里都有一个与当前时间有关系的签名字段，网上公开的那些基本都不能用了。

**Comment by landall** [comment]
shadow ban是存在的，我的Bot就只能发送文字和图片等基础的，Json和App发送了就直接被忽略。
