### ISSUE TITLE
密码登录时滑块验证通过却无法登录

### ISSUE THREAD

**Issue by wander303** [mamoe/mirai#2605]
### 问题描述

密码登录时滑块验证通过却无法登录
code=45
但是试过两个QQ号都是45，有一个是常用QQ号，不至于第一次就被风控

### 复现

登录时就会出现，不管有没有密保

### mirai-core 版本

2.15.0m1

### bot-protocol

ANDROID_PAD

### 系统日志

```text
2023-04-01 17:54:50 I/Bot.登录QQ号: Calculating type 2 PoW, it can take some time....
2023-04-01 17:54:50 I/Bot.登录QQ号: Got PoW result, cost: 276 ms
2023-04-01 17:55:33 E/console: net.mamoe.mirai.internal.network.auth.ProducerFailureException
net.mamoe.mirai.internal.network.auth.ProducerFailureException
	at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
	at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(登录QQ号), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
	Suppressed: net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(登录QQ号), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)]

2023-04-01 17:55:33 I/Bot.登录QQ号: Bot cancelled: Bot closed
2023-04-01 17:56:06 E/mirai-login-solver-sakura: [id: 0x262818d5, L:/192.168.0.4:36015 - R:/124.117.210.118:5324] [exceptionCaught]
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Unknown Source)

2023-04-01 17:56:06 W/io.netty.channel.DefaultChannelPipeline: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(Unknown Source)
	at java.base/sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:259)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at mirai-login-solver-sakura-0.0.10.mirai2.jar[private]//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by dest1n1s** [comment]
同样遇到了这个问题

**Comment by Him188** [comment]
看置顶
