### ISSUE TITLE
ClassCastException: class WeakReference cannot be cast to ...

### ISSUE THREAD

**Issue by inkydragon** [mamoe/mirai#261]
使用 GUI 版本发送消息会出现 “ClassCastException: class java.lang.ref.WeakReference cannot be cast to class net.mamoe.mirai.Bot”。
pure 版本没问题，但是貌似不支持 UTF-8 环境，所有中文均为乱码。
折腾了一下编码设置从乱码变成了 “锟斤拷”。win terminal/wsl/cmd 都会乱码。

以下是 GUI 版本的问题说明：

### 版本信息
+ mirai一键包3.0
+ 无插件

### 复现步骤
+ `/login`
+ `say 群号 "test"`

### 补充信息

<details><summary>GUI 导出的日志</summary>

```
[11:30:10] [Mirai 0.0.7 Pkmon] Mirai-console now running under H:\mirai
[11:30:10] [Mirai 0.0.7 Pkmon] Get news in github: https://github.com/mamoe/mirai
[11:30:10] [Mirai 0.0.7 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
[11:30:10] [Mirai 0.0.7 Pkmon] Powered by Mamoe Technologies and contributors
[11:30:10] [Plugin Manager] 开始加载H:\mirai/plugins/下的插件
[11:30:10] [Plugin Manager] 加载了0个插件
[11:30:10] [Mirai 0.0.7 Pkmon] Mirai-console 启动完成
[11:30:10] [Mirai 0.0.7 Pkmon] "/login qqnumber qqpassword " to login a bot
[11:30:10] [Mirai 0.0.7 Pkmon] "/login qq号 qq密码 " 来登录一个BOT
[11:30:34] [Bot Login] login...
[11:30:36] [Command] QQ_NUMBER login successes
[11:30:51] [Command] 在运行指令时出现了未知错误
[11:30:51] [Mirai 0.0.7 Pkmon] java.lang.ClassCastException: class java.lang.ref.WeakReference cannot be cast to class net.mamoe.mirai.Bot (java.lang.ref.WeakReference is in module java.base of loader 'bootstrap'; net.mamoe.mirai.Bot is in unnamed module of loader net.mamoe.mirai.console.wrapper.MiraiClassLoader @1964d75)
	at net.mamoe.mirai.console.command.DefaultCommands$invoke$4$1.invokeSuspend(DefaultCommands.kt:233)
	at net.mamoe.mirai.console.command.DefaultCommands$invoke$4$1.invoke(DefaultCommands.kt)
	at net.mamoe.mirai.console.command.AnonymousCommand.onCommand(Command.kt:112)
	at net.mamoe.mirai.console.command.CommandManager.processCommandImpl(CommandManager.kt:156)
	at net.mamoe.mirai.console.command.CommandManager$processCommand$2.invokeSuspend(CommandManager.kt:146)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
[11:32:45] [Command] 当前有1个BOT在线
```
</details>

<details><summary>控制台输出</summary>

```
You are running Mirai-Console-Wrapper under H:\mirai
Starting Mirai Console Graphical, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Fetching Newest Console Version of Graphical
Local Console-Graphical Version: 0.0.7 | Newest Console-Graphical Version: 0.0.7
Local Core Version: 0.39.1 | Newest Core Version: 0.39.1
Version check complete, starting Mirai
shadow-Protocol:H:\mirai\content\mirai-core-qqandroid-jvm-0.39.1.jar
Console        :H:\mirai\content\mirai-console-graphical-0.0.7.jar
Root           :H:\mirai/
Loaded H:\mirai\lib\..\bin\api-ms-win-core-console-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-datetime-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-debug-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-errorhandling-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-file-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-file-l1-2-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-file-l2-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-handle-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-heap-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-interlocked-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-libraryloader-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-localization-l1-2-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-memory-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-namedpipe-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-processenvironment-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-processthreads-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-processthreads-l1-1-1.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-profile-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-rtlsupport-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-string-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-synch-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-synch-l1-2-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-sysinfo-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-timezone-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-core-util-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-conio-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-convert-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-environment-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-filesystem-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-heap-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-locale-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-math-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-multibyte-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-private-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-process-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-runtime-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-stdio-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-string-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-time-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\api-ms-win-crt-utility-l1-1-0.dll from relative path
Loaded H:\mirai\lib\..\bin\ucrtbase.dll from relative path
Loaded H:\mirai\lib\..\bin\vcruntime140.dll from relative path
Loaded H:\mirai\lib\..\bin\msvcp140.dll from relative path
Loaded H:\mirai\lib\..\bin\concrt140.dll from relative path
Prism pipeline init order: d3d sw
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.d3d.D3DPipeline
Loading D3D native library ...
Loaded H:\mirai\lib\..\bin\prism_d3d.dll from relative path
        succeeded.
D3DPipelineManager: Created D3D9Ex device
Direct3D initialization succeeded
(X) Got class = class com.sun.prism.d3d.D3DPipeline
Initialized prism pipeline: com.sun.prism.d3d.D3DPipeline
JavaFX: using com.sun.javafx.tk.quantum.QuantumToolkit
Loaded H:\mirai\lib\..\bin\glass.dll from relative path
Maximum supported texture size: 8192
Maximum texture size clamped to 4096
OS Information:
        Windows version 10.0 build 18363
D3D Driver Information:
        Intel(R) HD Graphics 5500
        \\.\DISPLAY1
        Driver igdumdim32.dll, version 20.19.15.5058
        Pixel Shader version 3.0
        Device : ven_8086, dev_1616, subsys_222517AA
        Max Multisamples supported: 4
 vsync: true vpipe: true
4 24, 2020 11:30:10  tornadofx.Stylesheet$Companion detectAndInstallUrlHandler
Ϣ: Installing CSS url handler, since it was not picked up automatically
Loaded H:\mirai\lib\..\bin\javafx_font.dll from relative path
new alphas with length = 4096
PPSRenderer: scenario.effect - createShader: LinearConvolveShadow_64
new alphas with length = 57344
PPSRenderer: scenario.effect - createShader: Blend_SRC_IN
new alphas with length = 61440
PPSRenderer: scenario.effect - createShader: LinearConvolveShadow_4
PPSRenderer: scenario.effect - createShader: LinearConvolveShadow_8
PPSRenderer: scenario.effect - createShader: LinearConvolveShadow_128
PPSRenderer: scenario.effect - createShader: LinearConvolveShadow_96
new alphas with length = 1159168
```
</details>

### prue

设置用的：zh_CN+GBK；
字体是：YaHei Consolas Hybrid
还是锟斤拷看着顺眼，乱码不太行。

<details><summary>PURE 成功发送的 log</summary>

```
You are running Mirai-Console-Wrapper under H:\mirai
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Fetching Newest Console Version of Pure
Local Console-Pure Version: 0.4.11 | Newest Console-Pure Version: 0.4.11
Local Core Version: 0.39.1 | Newest Core Version: 0.39.1
Version check complete, starting Mirai
shadow-Protocol:H:\mirai\content\mirai-core-qqandroid-jvm-0.39.1.jar
Console        :H:\mirai\content\mirai-console-0.4.11.jar
Root           :H:\mirai/
 11:54:54 [INFO] [Mirai 0.4.11 Pkmon] Mirai-console now running under H:\mirai
 11:54:54 [INFO] [Mirai 0.4.11 Pkmon] Get news in github: https://github.com/mamoe/mirai
 11:54:54 [INFO] [Mirai 0.4.11 Pkmon] Mirai为锟斤拷源锟斤拷目锟斤拷锟斤拷锟皆撅拷锟斤拷锟截匡拷源锟斤拷目协锟斤拷
 11:54:54 [INFO] [Mirai 0.4.11 Pkmon] Powered by Mamoe Technologies and contributors
 11:54:54 [INFO] [Plugin Manager] 锟斤拷始锟斤拷锟斤拷H:\mirai/plugins/锟铰的诧拷锟▒
 11:54:54 [INFO] [Plugin Manager] 锟斤拷锟斤拷锟斤拷0锟斤拷锟斤拷锟▒
 11:54:54 [INFO] [Mirai 0.4.11 Pkmon] Mirai-console 锟斤拷锟斤拷锟斤拷
 11:54:54 [INFO] [Mirai 0.4.11 Pkmon] "/login qqnumber qqpassword " to login a bot
 11:54:54 [INFO] [Mirai 0.4.11 Pkmon] "/login qq锟斤拷 qq锟斤拷锟斤拷 " 锟斤拷锟斤拷录一锟斤拷BOT
login QQ_NUMBER PWD
 11:54:57 [INFO] [Bot Login] login...
 11:54:58 [INFO] [BOT QQ_NUMBER] Logging in...
 11:54:58 [INFO] [NETWORK] Connected to server 42.81.169.46:8080
 11:54:58 [INFO] [NETWORK] Send done: wtlogin.login
 11:54:58 [INFO] [NETWORK] Packet: LoginPacketResponse.Success
 11:54:58 [INFO] [NETWORK] Login successful
 11:54:58 [INFO] [NETWORK] Send done: StatSvc.register
 11:54:58 [INFO] [NETWORK] Packet: Response(StatSvc.register)
 11:54:58 [INFO] [NETWORK] 锟斤拷始锟斤拷锟截猴拷锟斤拷锟斤拷息
 11:54:58 [INFO] [NETWORK] 锟斤拷始锟斤拷锟斤拷群锟斤拷锟叫憋拷锟斤拷群锟斤拷员锟叫憋拷
 11:54:58 [INFO] [NETWORK] Send done: friendlist.getFriendGroupList
 11:54:58 [INFO] [NETWORK] Send done: friendlist.GetTroopListReqV2
 11:54:58 [INFO] [NETWORK] Packet: FriendList.GetFriendGroupList.Response
 11:54:58 [INFO] [NETWORK] 锟斤拷锟节硷拷锟截猴拷锟斤拷锟叫憋拷 2/2
 11:54:58 [INFO] [NETWORK] 锟斤拷锟斤拷锟叫憋拷锟斤拷锟斤拷锟斤拷, 锟斤拷 2锟斤拷
 11:54:58 [INFO] [NETWORK] Packet: FriendList.GetFriendGroupList.Response
 11:54:58 [INFO] [NETWORK] Send done: OidbSvc.0x88d_7
 11:54:59 [INFO] [NETWORK] Send done: friendlist.GetTroopMemberListReq
 11:54:59 [INFO] [NETWORK] Packet: FriendList.GetTroopMemberList.Response
 11:54:59 [INFO] [NETWORK] 群锟斤拷锟叫憋拷锟斤拷群锟斤拷员锟斤拷锟斤拷锟斤拷锟▒, 锟斤拷 1锟斤拷
 11:54:59 [INFO] [NETWORK] Awaiting ConfigPushSvc.PushReq
 11:54:59 [INFO] [NETWORK] Send done: MessageSvc.PbGetMsg
 11:54:59 [INFO] [NETWORK] unknown PbGetMsg type 528
 11:54:59 [INFO] [BOT QQ_NUMBER] Login successful
 11:54:59 [INFO] [Command] QQ_NUMBER login successes
 11:55:01 [INFO] [NETWORK] Received commandName: ConfigPushSvc.PushDomain
 11:55:01 [INFO] [BOT QQ_NUMBER] Event: ConfigPushSvc.PushReq.PushReqResponse.Success
 11:55:01 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
 11:55:01 [INFO] [NETWORK] ConfigPushSvc.PushReq: success
say QQ_GROUP_NUMBER "test"
 11:55:07 [INFO] [NETWORK] Send done: MessageSvc.PbSendMsg
 11:55:08 [INFO] [NETWORK] Packet: MessageSvc.PbSendMsg.Response.SUCCESS
 11:55:08 [INFO] [BOT QQ_NUMBER] Group(QQ_GROUP_NUMBER) <- "test"
 11:55:08 [INFO] [Mirai 0.4.11 Pkmon] 锟斤拷息锟斤拷锟斤拷锟斤拷
```
</details>

**Comment by Him188** [comment]
使用最新的 core 0.39.1 和 console 0.4.11 即可

**Comment by Him188** [comment]
一般重启一次 wrapper 可自动更新

**Comment by Him188** [comment]
GUI 版本应该是刚好那个时候还没有更新到0.4.11才有 ClassCastException
