### ISSUE TITLE
QR 登录失败 remaining payload is too short, current is 35.

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#2611]
branch: 2.15.0-RC bddee1fd2032a00718c794a020239b38d9b3abc4

```kotlin
Exception in thread "main" net.mamoe.mirai.internal.network.auth.ProducerFailureException
	at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
	at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: java.lang.IllegalStateException: remaining payload is too short, current is 35.
		at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$TransEmp.decode(WtLogin.kt:812)
		at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:552)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
		at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
		at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
		at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
		at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
		at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
Caused by: [CIRCULAR REFERENCE: java.lang.IllegalStateException: remaining payload is too short, current is 35.]
```

Full logs:

```
2023-04-04 20:53:04 V/Net 123123123: Validated caches.
2023-04-04 20:53:04 V/Net 123123123: No server list cached.
2023-04-04 20:53:04 D/Net 123123123: CAS: JustInitialized -> CreatingProducer: true
2023-04-04 20:53:04 D/Net 123123123: CAS: CreatingProducer -> ProducerReady: true
2023-04-04 20:53:04 D/Net 123123123: CAS: ProducerReady -> Producing(deferred.completed=false): true
2023-04-04 20:53:04 I/Net 123123123: ECDH key is invalid, start to fetch ecdh public key from server.
2023-04-04 20:53:04 V/Net 123123123: [AuthControl/auth] Authorization started
2023-04-04 20:53:04 D/Net 123123123: CAS: Producing(deferred.completed=false) -> Consuming(value=null): true
2023-04-04 20:53:06 I/Net 123123123: Successfully fetched ecdh public key from server.
2023-04-04 20:53:06 V/Net 123123123: [AuthControl/acquire] Acquiring auth method
2023-04-04 20:53:06 D/Net 123123123: CAS: Consuming(value=QRCode) -> Consumed(LatchImpl(CompletableDeferredImpl{Active}@81d8db9)): true
2023-04-04 20:53:06 D/Net 123123123: [AuthControl/acquire] Authorization responded: QRCode
2023-04-04 20:53:06 D/Net 123123123: requesting qrcode.
2023-04-04 20:53:06 V/Net 123123123: Send: wtlogin.trans_emp
2023-04-04 20:53:07 W/Net 123123123: Failed with auth method: QRCode
java.lang.IllegalStateException: remaining payload is too short, current is 35.
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$TransEmp.decode(WtLogin.kt:812)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:552)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

重启之后正常了, 但是一直报 unknown flag3, 值有 80, -104, -120, 32, 16, 但是二维码正常显示, 也可以正常扫描, 不影响
```
2023-04-04 20:59:39 W/Packet: unknown flag3: 80 in packet wtlogin.trans_emp, which may means protocol is updated.
net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Illegal flag3. Expected 0, whereas got 80. packet type=10, encrypt method=2. 
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:112)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.decodePacket(CommonNetworkHandler.kt:149)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$decodePacket(CommonNetworkHandler.kt:103)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Illegal flag3. Expected 0, whereas got 80. packet type=10, encrypt method=2. 
	at net.mamoe.mirai.internal.network.components.PacketCodecException.<init>(PacketCodec.kt:73)
	... 13 more
```

另外额外发现如果查 QR 的请求 timeout 了, 会进入并卡在 request auth method 状态, 日志没了

**Comment by Him188** [comment]
@StageGuard any thoughts

**Comment by StageGuard** [comment]
> @StageGuard any thoughts

偶尔触发？

**Comment by Him188** [comment]
我的小号登录必发, 每个请求都有

**Comment by StageGuard** [comment]
> 我的小号登录必发, 每个请求都有

完全无法获取二维码么，那个 warning 应该是没问题的

**Comment by Him188** [comment]
可以获取, 只是有 warning

**Comment by Him188** [comment]
我觉得可以考虑忽略 warning, (用 system prop 开启)
