### ISSUE TITLE
2023.3.31起无法登录 DecryptionFailedException: null

### ISSUE THREAD

**Issue by kuresaru** [mamoe/mirai#2614]
### 问题描述

2023.3.31起无法登录 一直报DecryptionFailedException: null 或者版本过低, 2.14.0和2.15.0-M1都不能登录

### 复现

登录过程稳定发生, 修改device无效

### mirai-core 版本

2.14.0和2.15.0-M1

### bot-protocol

ANDROID_PAD

### 其他组件版本

```
plugins {
	id("org.springframework.boot") version "2.7.7"
	id("io.spring.dependency-management") version "1.0.15.RELEASE"
	kotlin("jvm") version "1.8.10"
	kotlin("plugin.spring") version "1.8.10"
	kotlin("plugin.jpa") version "1.8.10"
}

dependencies {
	val miraiVersion = "2.15.0-M1"

	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-data-redis-reactive")
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("org.springframework.boot:spring-boot-starter-thymeleaf")
	implementation("org.springframework.boot:spring-boot-starter-oauth2-client")
	implementation("org.springframework.boot:spring-boot-starter-amqp")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
	implementation("mysql:mysql-connector-java:8.0.25")
	implementation("com.squareup.okhttp3:okhttp:3.14.9")
	implementation("com.huaban:jieba-analysis:1.0.3-SNAPSHOT") // https://github.com/GlassyWing/better-jieba
	implementation("com.madgag:animated-gif-lib:1.4") // https://github.com/rtyley/animated-gif-lib-for-java
	implementation("net.coobird:thumbnailator:0.4.19")
	implementation("net.mamoe:mirai-core-jvm:$miraiVersion") {
		exclude("net.mamoe","mirai-core-api")
		exclude("net.mamoe","mirai-core-utils")
	}
	implementation("net.mamoe:mirai-core-api-jvm:$miraiVersion") {
		exclude("net.mamoe", "mirai-core-utils")
	}
	implementation("net.mamoe:mirai-core-utils-jvm:$miraiVersion")
	implementation("xyz.cssxsh.mirai:mirai-device-generator:1.1.3")
	implementation("org.jsoup:jsoup:1.13.1")
	implementation("com.google.code.gson:gson:2.8.6")
	implementation("commons-cli:commons-cli:1.4")
	implementation("com.kennycason:kumo-core:1.28")
	implementation("com.kennycason:kumo-tokenizers:1.28")
}
```

### 系统日志

```text
以下为2.14.0错误日志, 2.15.0-M1好像也是一样

2023-04-09 13:32:17.613 [main] INFO  [top.scraft.robitgw.service.MiraiService] - 开始登录
mirai verbose Network/No server list cached.
2023-04-09 13:32:17.991 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/No server list cached.
mirai info Network/ECDH key is invalid, start to fetch ecdh public key from server.
2023-04-09 13:32:18.036 [DefaultDispatcher-worker-1] INFO  [top.scraft.robitgw.MiraiLogger] - Network/ECDH key is invalid, start to fetch ecdh public key from server.
mirai info Network/Successfully fetched ecdh public key from server.
2023-04-09 13:32:18.668 [DefaultDispatcher-worker-1] INFO  [top.scraft.robitgw.MiraiLogger] - Network/Successfully fetched ecdh public key from server.
mirai verbose Network/Send: wtlogin.login(9:password-login)
2023-04-09 13:32:18.753 [DefaultDispatcher-worker-1] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: wtlogin.login(9:password-login)
mirai warning Network/Exception in resumeConnection.
2023-04-09 13:32:19.255 [nioEventLoopGroup-4-3] ERROR [top.scraft.robitgw.MiraiLogger] - mirai error Network/Exception in decoding packet.
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null
	at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299)
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275)
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295)
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319)
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318)
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623)
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368)
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-04-09 13:32:19.257 [DefaultDispatcher-worker-3] WARN  [top.scraft.robitgw.MiraiLogger] - Network/Exception in resumeConnection.
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null
	at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299)
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275)
	at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295)
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319)
	at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318)
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623)
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368)
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231)
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
mirai warning Network/Network selector received exception, closing bot. (net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException)
2023-04-09 13:32:19.261 [DefaultDispatcher-worker-3] WARN  [top.scraft.robitgw.MiraiLogger] - Network/Network selector received exception, closing bot. (net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException)
2023-04-09 13:32:19.275 [DefaultDispatcher-worker-3] INFO  [top.scraft.robitgw.service.MiraiService] - 登录失败
mirai info Mirai/Bot cancelled: Bot closed
2023-04-09 13:32:19.293 [nioEventLoopGroup-4-4] INFO  [top.scraft.robitgw.MiraiLogger] - Mirai/Bot cancelled: Bot closed
```
```


### 网络日志

_No response_

### 补充信息

_No response_

**Comment by cssxsh** [comment]
刷新缓存

**Comment by kuresaru** [comment]
> 刷新缓存

删除cache目录还是一样

**Comment by kuresaru** [comment]
刚去看了下最后一次在线之后的日志

```
2023-03-27 13:59:40.617 [nioEventLoopGroup-213-1] TRACE [top.scraft.robitgw.MiraiLogger] - Mirai/Event: BotOfflineEvent.Dropped(bot=Bot(906021525), cause=net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired., reconnect=true)
2023-03-27 13:59:40.618 [nioEventLoopGroup-213-1] WARN  [top.scraft.robitgw.MiraiLogger] - Mirai/Connection lost, reconnecting... (net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.)
2023-03-27 13:59:40.621 [nioEventLoopGroup-213-1] WARN  [top.scraft.robitgw.MiraiLogger] - Network/Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseSsoFrame(PacketCodec.kt:178)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:128)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.decodePacket(CommonNetworkHandler.kt:148)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$decodePacket(CommonNetworkHandler.kt:102)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
        at net.mamoe.mirai.internal.network.components.PacketCodecException.<init>(PacketCodec.kt:72)
        ... 15 common frames omitted
2023-03-27 13:59:40.626 [nioEventLoopGroup-213-1] ERROR [top.scraft.robitgw.MiraiLogger] - mirai error Network/Error while decoding packet 'ByteReadPacket(0 bytes remaining)'
net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseSsoFrame(PacketCodec.kt:178)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:128)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.decodePacket(CommonNetworkHandler.kt:148)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$decodePacket(CommonNetworkHandler.kt:102)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
        at net.mamoe.mirai.internal.network.components.PacketCodecException.<init>(PacketCodec.kt:72)
        ... 15 common frames omitted
2023-03-27 13:59:40.652 [DefaultDispatcher-worker-5] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Loading server list from cache.
2023-03-27 13:59:40.654 [DefaultDispatcher-worker-5] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Server list: 157.255.13.204:80, 116.130.229.216:8080, 116.147.18.148:80, 116.130.229.208:443, 59.83.209.34:14
000, 125.39.196.158:443, 163.177.30.32:80, 59.83.208.214:443, msfwifi.3g.qq.com:8080, 125.39.196.233:80.
2023-03-27 13:59:40.655 [DefaultDispatcher-worker-5] INFO  [top.scraft.robitgw.MiraiLogger] - Network/ECDH key is invalid, start to fetch ecdh public key from server.
2023-03-27 13:59:40.803 [DefaultDispatcher-worker-4] INFO  [top.scraft.robitgw.MiraiLogger] - Network/Successfully fetched ecdh public key from server.
2023-03-27 13:59:40.809 [DefaultDispatcher-worker-4] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: wtlogin.exchange_emp(10:fast-login)
2023-03-27 13:59:40.835 [nioEventLoopGroup-214-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: wtlogin.exchange_emp
2023-03-27 13:59:40.837 [DefaultDispatcher-worker-4] INFO  [top.scraft.robitgw.MiraiLogger] - Mirai/Saved account secrets to local cache for fast login.
2023-03-27 13:59:40.837 [DefaultDispatcher-worker-4] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: StatSvc.register(online)
2023-03-27 13:59:40.854 [nioEventLoopGroup-214-4] ERROR [top.scraft.robitgw.MiraiLogger] - mirai error Network/Error while decoding packet 'ByteReadPacket(0 bytes remaining)'
net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseSsoFrame(PacketCodec.kt:178)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:127)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.decodePacket(CommonNetworkHandler.kt:148)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$decodePacket(CommonNetworkHandler.kt:102)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
        at net.mamoe.mirai.internal.network.components.PacketCodecException.<init>(PacketCodec.kt:72)
        ... 15 common frames omitted
2023-03-27 13:59:40.856 [DefaultDispatcher-worker-3] WARN  [top.scraft.robitgw.MiraiLogger] - Network/Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseSsoFrame(PacketCodec.kt:178)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:127)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.decodePacket(CommonNetworkHandler.kt:148)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$decodePacket(CommonNetworkHandler.kt:102)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:125)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
        at net.mamoe.mirai.internal.network.components.PacketCodecException.<init>(PacketCodec.kt:72)
        ... 15 common frames omitted
2023-03-27 13:59:43.871 [DefaultDispatcher-worker-5] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Loading server list from cache.
2023-03-27 13:59:43.872 [DefaultDispatcher-worker-5] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Server list: 157.255.13.204:80, 116.130.229.216:8080, 116.147.18.148:80, 116.130.229.208:443, 59.83.209.34:14
000, 125.39.196.158:443, 163.177.30.32:80, 59.83.208.214:443, msfwifi.3g.qq.com:8080, 125.39.196.233:80.
2023-03-27 13:59:43.872 [DefaultDispatcher-worker-5] INFO  [top.scraft.robitgw.MiraiLogger] - Network/ECDH key is valid.
2023-03-27 13:59:43.881 [DefaultDispatcher-worker-5] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: wtlogin.exchange_emp(10:fast-login)
2023-03-27 13:59:43.917 [DefaultDispatcher-worker-5] INFO  [top.scraft.robitgw.MiraiLogger] - Mirai/Saved account secrets to local cache for fast login.
2023-03-27 13:59:43.919 [DefaultDispatcher-worker-5] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Send: StatSvc.register(online)
2023-03-27 13:59:43.920 [nioEventLoopGroup-215-3] TRACE [top.scraft.robitgw.MiraiLogger] - Network/Recv: wtlogin.exchange_emp
2023-03-27 13:59:43.936 [nioEventLoopGroup-215-4] ERROR [top.scraft.robitgw.MiraiLogger] - mirai error Network/Error while decoding packet 'ByteReadPacket(0 bytes remaining)'
net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Received packet returnCode = -10003, which may mean session expired.
```
后边一直循环

**Comment by cssxsh** [comment]
> 刷新缓存

指 gradle 缓存

你的 mirai 依赖肯定有问题

**Comment by kuresaru** [comment]
好神奇, 可以用了, 感谢
