### ISSUE TITLE
同时发送多条消息时出现PacketCodecException

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2625]
### 问题描述

在同时一瞬间发送大约10条消息时出现，同时手机端QQ也会被强制退出

### 复现

让机器人在指定群中使用launch中for循环发送5条消息，launch外使用for循环发送5条，也许能复现

### mirai-core 版本

2.14.0

### bot-protocol

MACOS

### 系统日志

```text
2023-04-14 00:57:14 V/Bot.2860688653: Event: BotOfflineEvent.Dropped(bot=Bot(2860688653), cause=net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Received packet returnCode = -10004, which may mean session expired., reconnect=true)
2023-04-14 00:57:14 W/Bot.2860688653: Connection lost, reconnecting... (net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Received packet returnCode = -10004, which may mean session expired.)
```

### 网络日志

```text
[93m2023-04-14 00:57:15 W/Net 2860688653: Timeout awaiting sequenceId for message(@227801068). Some features may not work properly.
java.util.concurrent.CancellationException: Bot closed
	at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
	at net.mamoe.mirai.internal.AbstractBot.close(AbstractBot.kt:121)
	at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:97)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.resumeConnection$suspendImpl(SelectorNetworkHandler.kt:141)
	at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$resumeConnection$1.invokeSuspend(SelectorNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(2860688653), code=16, title=登录失败, message=你的用户身份已失效，为保证帐号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	... 4 more
	Suppressed: net.mamoe.mirai.internal.network.components.PacketCodecException: java.lang.IllegalStateException: Received packet returnCode = -10004, which may mean session expired.
		at net.mamoe.mirai.internal.network.components.PacketCodecImpl.parseSsoFrame(PacketCodec.kt:178)
		at net.mamoe.mirai.internal.network.components.PacketCodecImpl.decodeRaw(PacketCodec.kt:128)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.decodePacket(CommonNetworkHandler.kt:148)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$decodePacket(CommonNetworkHandler.kt:102)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:125)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Caused by: java.lang.IllegalStateException: Received packet returnCode = -10004, which may mean session expired.
		at net.mamoe.mirai.internal.network.components.PacketCodecException.<init>(PacketCodec.kt:72)
		... 15 more
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2860688653), code=16, title=登录失败, message=你的用户身份已失效，为保证帐号安全，请你重新登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	... 9 more
	Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(2860688653), code=16, title=登录失败, message=你的用户身份已失效，为保证帐号安全，请你重新登录。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:364)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		... 9 more
[0m
```

**Comment by Him188** [comment]
发消息太快了

**Comment by MrY-Cat** [comment]
> 发消息太快了

可是另一个机器人经常同时发好多条，也不会出现这个问题）

**Comment by sandtechnology** [comment]
> > 发消息太快了
> 
> 可是另一个机器人经常同时发好多条，也不会出现这个问题）

那不就说明不是mirai问题了吗

**Comment by MrY-Cat** [comment]
> > > 发消息太快了
> > 
> > 
> > 可是另一个机器人经常同时发好多条，也不会出现这个问题）
> 
> 那不就说明不是mirai问题了吗

有道理，那可能是腾讯对不同的号宽容度不一样，这个号发快了就直接被强制下线了
