### ISSUE TITLE
禁止登录，QQ版本过低

### ISSUE THREAD

**Issue by boxdl** [mamoe/mirai#2628]
__       __ __                   __  ______                                      __|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓

2023-04-15 08:37:59 I/main: Backend: version 2.14.0, built on 2023-02-06 14:25:21.
2023-04-15 08:37:59 I/main: Frontend Terminal: version 2.14.0, provided by Mamoe Technologies
2023-04-15 08:37:59 I/main: Welcome to visit https://mirai.mamoe.net/
2023-04-15 08:38:01 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-04-15 08:38:02 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-04-15 08:38:02 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-04-15 08:38:02 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-04-15 08:38:02 I/main: 1 plugin(s) enabled.
2023-04-15 08:38:02 I/main: mirai-console started successfully.
2023-04-15 08:39:10 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2930771281), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2930771281), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-04-15 08:39:10 I/Bot.2930771281: Bot cancelled: Bot closed

**Comment by MrXiaoM** [comment]
https://mirai.mamoe.net/topic/223

**Comment by qfys521** [comment]
#2570

**Comment by boxdl** [comment]
> https://mirai.mamoe.net/topic/223
还是不行

**Comment by qfys521** [comment]
换MACOS协议试试

**Comment by boxdl** [comment]
> 换MACOS协议试试

换了没用，我那个只能支持密码输入，code都是45

**Comment by boxdl** [comment]
> 换MACOS协议试试

不行

**Comment by qfys521** [comment]
用Aoki重新生成设备文件？(记得备份)

**Comment by boxdl** [comment]
> 

提供一下下载地址

**Comment by boxdl** [comment]
> 用Aoki重新生成设备文件？(记得备份)

可以提供一下下载地址？

**Comment by qfys521** [comment]
MrXiaoM/Aoki

**Comment by boxdl** [comment]
> MrXiaoM/Aoki

复制过来登录怎么登录，我用默认登录会报错

**Comment by qfys521** [comment]
> 复制过来登录怎么登录，我用默认登录会报错

什么报错

**Comment by qfys521** [comment]
> 复制过来登录怎么登录，我用默认登录会报错

用的什么协议？原文件需要替换(记得备份)

**Comment by Him188** [comment]
用 2.15.0-M1, 试试扫码登录

**Comment by mckuhei** [comment]
临时解决方案同#2627

**Comment by Him188** [comment]
试试扫码登录, 如果不行就等 2.15.0-RC, 会有 #2613
