### ISSUE TITLE
mirai 2.15.0-M1 登录 code=238/45 且没有二维码

### ISSUE THREAD

**Issue by linux-rm** [mamoe/mirai#2650]
### 问题描述

无论什么协议，都没有二维码登录
除了手表code=238,其它45

### 复现

更新到 2.15 M1

### mirai-core 版本

2.15.0-M1

### bot-protocol

Anyone

### 其他组件版本

```json
{
  "module_packages": [
    "mcl:org.itxtech.mcl.module.builtin"
  ],
  "mirai_repo": "https://repo.mirai.mamoe.net/keep/mcl",
  "maven_repo": [
    "https://maven.aliyun.com/repository/public"
  ],
  "packages": {
    "net.mamoe:mirai-console": {
      "channel": "maven-prerelease",
      "version": "2.15.0-M1",
      "type": "libs",
      "versionLocked": false
    },
    "net.mamoe:mirai-console-terminal": {
      "channel": "maven-prerelease",
      "version": "2.15.0-M1",
      "type": "libs",
      "versionLocked": false
    },
    "net.mamoe:mirai-core-all": {
      "channel": "maven-prerelease",
      "version": "2.15.0-M1",
      "type": "libs",
      "versionLocked": false
    },
    "org.itxtech:mcl-addon": {
      "channel": "maven-stable",
      "version": "2.1.1",
      "type": "plugins",
      "versionLocked": false
    },
    "org.bouncycastle:bcprov-jdk15on": {
      "channel": "maven-prerelease",
      "version": "1.65.01",
      "type": "libs",
      "versionLocked": false
    },
    "net.mamoe:mirai-api-http": {
      "channel": "maven-prerelease",
      "version": "2.9.1",
      "type": "plugins",
      "versionLocked": false
    },
    "net.mamoe:chat-command": {
      "channel": "maven-prerelease",
      "version": "0.6.0",
      "type": "plugins",
      "versionLocked": false
    }
  },
  "archiveSuffix": [
    ".zip",
    ".mirai2.jar",
    ".mirai.jar",
    "-all.jar",
    ".jar"
  ],
  "disabled_modules": [],
  "proxy": "",
  "log_level": 1,
  "modules_props": {}
}
```

### 系统日志

```text
2023-04-28 05:54:50 I/main: Starting mirai-console...
2023-04-28 05:54:50 I/main:

=================================[ Mirai console 2.15.0-M1 ]==================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-04-28 05:54:50 I/main: Backend: version 2.15.0-M1, built on 2023-03-21 14:16:35.
2023-04-28 05:54:50 I/main: Frontend Terminal: version 2.15.0-M1, provided by Mamoe Technologies
2023-04-28 05:54:50 I/main: Welcome to visit https://mirai.mamoe.net/
2023-04-28 05:56:10 I/plugin: Successfully loaded plugin mirai-api-http v2.9.1
2023-04-28 05:56:10 I/plugin: Successfully loaded plugin Chat Command v0.6.0
2023-04-28 05:56:17 W/io.netty.util.internal.MacAddressUtil: Failed to find a usable hardware address from the network interfaces; using random bytes: 5e:b4:65:60:1c:99:04:47
2023-04-28 05:56:40 I/plugin: Successfully loaded plugin mirai-login-solver-sakura v0.0.10
2023-04-28 05:56:40 I/plugin: Successfully loaded plugin fix-protocol-version v1.4.0
2023-04-28 05:56:40 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-04-28 05:56:44 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-04-28 05:56:58 I/Mirai HTTP API: ********************************************************
2023-04-28 05:56:59 I/MahKtorAdapter[http]: Autoreload is disabled because the development mode is off.
2023-04-28 05:56:59 I/MahKtorAdapter[http]: Application started in 0.96 seconds.
2023-04-28 05:57:00 I/MahKtorAdapter[http]: Responding at http://localhost:8080
2023-04-28 05:57:00 I/http adapter: >>> [http adapter] is listening at http://localhost:8080
2023-04-28 05:57:00 I/Mirai HTTP API: Http api server is running out of verify mode
2023-04-28 05:57:00 I/Mirai HTTP API: adaptors: [http]
2023-04-28 05:57:00 I/Mirai HTTP API: ********************************************************
2023-04-28 05:57:11 I/fix-protocol-version: 当前各协议版本日期:
ANDROID_PHONE  8.9.33.10335  2023-01-13T08:51:38Z
ANDROID_PAD    8.9.33.10335  2023-01-13T08:51:38Z
ANDROID_WATCH  2.0.5         2019-06-03T12:25:31Z
IPAD           8.9.33.614    2021-12-31T03:36:26Z
MACOS          6.7.9         1970-01-01T00:00Z

2023-04-28 05:57:39 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-04-28 05:57:39 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-04-28 05:57:39 I/main: 5 plugin(s) enabled.
2023-04-28 05:57:39 I/main: Auto-login 3036403736, protocol: MACOS, heartbeatStrategy: STAT_HB
2023-04-28 05:57:40 W/io.netty.util.internal.MacAddressUtil: Failed to find a usable hardware address from the network interfaces; using random bytes: 4d:01:b3:6a:90:31:e2:12
2023-04-28 05:57:44 E/main: net.mamoe.mirai.internal.network.auth.ProducerFailureException
net.mamoe.mirai.internal.network.auth.ProducerFailureException
        at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
        at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3036403736), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                ... 5 more
        Suppressed: net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3036403736), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重 试。, errorInfo=)]

2023-04-28 05:57:44 V/Bot.3036403736: Event: net.mamoe.mirai.console.events.AutoLoginEvent$Failure@c82ad22
2023-04-28 05:57:44 I/main: mirai-console started successfully.
2023-04-28 05:57:44 I/Bot.3036403736: Bot cancelled: Bot closed
```

### 网络日志

```text
2023-04-28 05:57:41 V/Net 3036403736: Invalidate caches because hash file not available.
2023-04-28 05:57:41 V/Net 3036403736: No server list cached.
2023-04-28 05:57:41 D/Net 3036403736: CAS: JustInitialized -> CreatingProducer: true
2023-04-28 05:57:41 D/Net 3036403736: CAS: CreatingProducer -> ProducerReady: true
2023-04-28 05:57:41 D/Net 3036403736: CAS: ProducerReady -> Producing(deferred.completed=false): true
2023-04-28 05:57:41 I/Net 3036403736: ECDH key is invalid, start to fetch ecdh public key from server.
2023-04-28 05:57:41 V/Net 3036403736: [AuthControl/auth] Authorization started
2023-04-28 05:57:41 D/Net 3036403736: CAS: Producing(deferred.completed=false) -> Consuming(value=null): true
2023-04-28 05:57:42 I/Net 3036403736: Successfully fetched ecdh public key from server.
2023-04-28 05:57:42 V/Net 3036403736: [AuthControl/acquire] Acquiring auth method
2023-04-28 05:57:42 D/Net 3036403736: CAS: Consuming(value=Password@1830154353) -> Consumed(LatchImpl(CompletableDeferredImpl{Active}@4e3f5124)): true
2023-04-28 05:57:42 D/Net 3036403736: [AuthControl/acquire] Authorization responded: Password@1830154353
2023-04-28 05:57:43 V/Net 3036403736: Send: wtlogin.login(9:password-login)
2023-04-28 05:57:44 W/Net 3036403736: Failed with auth method: Password@1830154353
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3036403736), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-04-28 05:57:44 V/Net 3036403736: [AuthControl/resume] Fire auth failed with cause: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3036403736), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
2023-04-28 05:57:44 D/Net 3036403736: CAS: Consumed(LatchImpl(CompletableDeferredImpl{Active}@4e3f5124)) -> ProducerReady: true
2023-04-28 05:57:44 D/Net 3036403736: CAS: ProducerReady -> Producing(deferred.completed=false): true
2023-04-28 05:57:44 V/Net 3036403736: Recv: wtlogin.login
2023-04-28 05:57:44 V/Net 3036403736: [AuthControl/auth] Authorization failed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3036403736), code=45, title=禁止登录, message=你当前使用的QQ 版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
2023-04-28 05:57:44 D/Net 3036403736: CAS: Producing(deferred.completed=false) -> Finished(Producing(deferred.completed=false), net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3036403736), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)): true
2023-04-28 05:57:44 W/Net 3036403736: Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException

2023-04-28 05:57:44 I/Net 3036403736: ECDH key is valid.
2023-04-28 05:57:44 V/Net 3036403736: [AuthControl/acquire] Acquiring auth method
2023-04-28 05:57:44 D/Net 3036403736: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.internal.network.auth.ProducerFailureException]@215782863
2023-04-28 05:57:44 W/Net 3036403736: Failed with auth method: Error[net.mamoe.mirai.internal.network.auth.ProducerFailureException]@215782863
net.mamoe.mirai.internal.network.auth.ProducerFailureException
        at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
        at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3036403736), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        ... 5 more

2023-04-28 05:57:44 W/Net 3036403736: Exception in resumeConnection.
net.mamoe.mirai.internal.network.auth.ProducerFailureException
        at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
        at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3036403736), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                ... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3036403736), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重 试。, errorInfo=)]

2023-04-28 05:57:44 W/Net 3036403736: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.auth.ProducerFailureException)
```

**Comment by cssxsh** [comment]
> 2023-04-28 05:56:10 I/plugin: Successfully loaded plugin mirai-api-http v2.9.1
> 2023-04-28 05:56:10 I/plugin: Successfully loaded plugin Chat Command v0.6.0
> 2023-04-28 05:56:17 W/io.netty.util.internal.MacAddressUtil: Failed to find a usable hardware address from the network interfaces; using random bytes: 5e:b4:65:60:1c:99:04:47
> 2023-04-28 05:56:40 I/plugin: Successfully loaded plugin mirai-login-solver-sakura v0.0.10
> 2023-04-28 05:56:40 I/plugin: Successfully loaded plugin fix-protocol-version v1.4.0
> 2023-04-28 05:56:40 I/plugin: Successfully loaded plugin MCL Addon v2.1.1

首先 `2.15.0-M1` 还没有提供官方的扫码登录`指令`，目前只是有一个第三方 https://github.com/MrXiaoM/mirai-console-dev-qrlogin 插件

其次你的日志是`自动登录` , 它其实是密码登录
