### ISSUE TITLE
获取群精华消息报错

### ISSUE THREAD

**Issue by kukume** [mamoe/mirai#2668]
### 问题描述

1、获取群精华消息报错
在我的一个群中，其中有精华消息
```text
https://xxxx.xxxx.me
```
在调用`group.essences.getPage(0, 20)`出现异常，异常信息为
```java
java.lang.IllegalStateException: parse digest data error, status: 0 - success
	at net.mamoe.mirai.internal.contact.essence.GroupDigestProtocolKt.loadData(GroupDigestProtocol.kt:86) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.contact.essence.GroupDigestProtocolKt.getDigestList(GroupDigestProtocol.kt:107) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.contact.essence.GroupDigestProtocolKt$getDigestList$1.invokeSuspend(GroupDigestProtocol.kt) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.8.20.jar:1.8.20-release-327(1.8.20)]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.8.20.jar:1.8.20-release-327(1.8.20)]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.8.20.jar:1.8.20-release-327(1.8.20)]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.8.20.jar:1.8.20-release-327(1.8.20)]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.8.20.jar:1.8.20-release-327(1.8.20)]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.8.20.jar:1.8.20-release-327(1.8.20)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at me.kuku.mirai.config.ScheduledSuspendMethodRunnable.run(ScheduledSuspendConfig.kt:52) ~[main/:na]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.7.jar:6.0.7]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Failed to parse 'int'
JSON input: .....ontent":[{"msg_type":1,"text":"https://xxxxx.xxxxx.me"}]}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.unparsedPrimitive(TreeJsonDecoder.kt:146) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedInt(TreeJsonDecoder.kt:380) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeTaggedInt(TreeJsonDecoder.kt:36) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.internal.TaggedDecoder.decodeIntElement(Tagged.kt:252) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at net.mamoe.mirai.internal.contact.essence.DigestMessage$$serializer.deserialize(GroupDigestProtocol.kt:50) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.contact.essence.DigestMessage$$serializer.deserialize(GroupDigestProtocol.kt:50) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:280) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:297) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:280) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:207) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:280) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:297) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:280) ~[kotlinx-serialization-core-jvm-1.5.0.jar:1.5.0]
	at net.mamoe.mirai.internal.contact.essence.DigestList$$serializer.deserialize(GroupDigestProtocol.kt:38) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at net.mamoe.mirai.internal.contact.essence.DigestList$$serializer.deserialize(GroupDigestProtocol.kt:38) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:61) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.json.internal.AbstractJsonTreeDecoder.decodeSerializableValue(TreeJsonDecoder.kt:52) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.json.internal.TreeJsonDecoderKt.readJson(TreeJsonDecoder.kt:25) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at kotlinx.serialization.json.Json.decodeFromJsonElement(Json.kt:117) ~[kotlinx-serialization-json-jvm-1.5.0.jar:na]
	at net.mamoe.mirai.internal.contact.essence.GroupDigestProtocolKt.loadData(GroupDigestProtocol.kt:84) ~[mirai-core-jvm-2.15.0-dev-90.jar:2.15.0-dev-90]
	... 44 common frames omitted
```
2、群精华消息事件是哪个？
在 #2293 中已经提及了群精华事件，该issues已经被关闭，但是我无法找到群精华消息事件。

### 复现

复现如问题描述

### mirai-core 版本

2.15.0-dev-90

### bot-protocol

ANDROID_PAD

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/blob/c57fdd7790e02a723158f91cdb3b697642709a0f/mirai-core/src/commonMain/kotlin/contact/essence/GroupDigestProtocol.kt#L51-L72

推测  msg_random 和 msg_seq 解析失败

**Comment by cssxsh** [comment]
频繁出现吗

**Comment by kukume** [comment]
我这个群必出现，没在其他群测试过

**Comment by cssxsh** [comment]
> 我这个群必出现，没在其他群测试过

找一条出现的精华消息，`引用回复` 它，然后把日志记录一下
我需要 `[mirai:quote:[mirai:source:ids=..., internalIds=...` 的 ids 和 internalIds 确认是为何解析失败

**Comment by kukume** [comment]
[mirai:quote:[mirai:source:ids=[98019], internalIds=[1351051379], from 1104195224 to 115492521 at 1685161905], content=<not yet initialized>]te s
我把一张图片设置了精华，然后回复了这张图片的消息日志
