### ISSUE TITLE
ANDROID_WATCH协议下匿名成员使用sender.mute()会出现java.lang.IllegalStateException

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2670]
### 问题描述

如题，只要对匿名成员调用sender.mute(不超过7天的任何秒数)就会出现

### 复现

如题，只要对匿名成员调用sender.mute(不超过7天的任何秒数)就会出现

### mirai-core 版本

2.15.0-M1

### bot-protocol

ANDROID_WATCH

### 系统日志

```text
java.lang.IllegalStateException: {"cgicode":1002,"retcode":151,"msg":"error set group forbid [errcode:1002:151]","result":[]}
	at net.mamoe.mirai.internal.MiraiImpl.muteAnonymousMember$suspendImpl(MiraiImpl.kt:618)
	at net.mamoe.mirai.internal.MiraiImpl$muteAnonymousMember$1.invokeSuspend(MiraiImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### 补充信息

我记得以前的版本的时候匿名的禁言是正常的，只是最多7天，不知道最近哪个版本开始不行了

 与 #2626  有关

**Comment by MrY-Cat** [comment]
#2711 2.15.0修复
