### ISSUE TITLE
【mirai-core】【ANDROID_WATCH】晚上九点左右到早上8点左右，不定时出现无法发送消息

### ISSUE THREAD

**Issue by ghost** [mamoe/mirai#2685]
### 问题描述

查看log日志发现，mirai内部的日志框架输出了已经发送了消息，但是并未触发MessagePreEvent和MessagePostEvent事件，并且QQ客户端并没有收到该消息
```log
23:28:06.900 [nioEventLoopGroup-3-6] net.mamoe.mirai.Bot(LoggerAdapterImpls.kt:35)
[TRACE] [AI体验学习交流群(72******74)] 永不认输(48***85) -> 查 在线

23:28:06.900 [nioEventLoopGroup-4-3] net.mamoe.mirai.Bot(LoggerAdapterImpls.kt:35)
[TRACE] [AI体验学习交流群(72*******74)] 永不认输(48*****85) -> 查 在线

23:28:06.900 [nioEventLoopGroup-2-7] net.mamoe.mirai.Bot(LoggerAdapterImpls.kt:35)
[TRACE] [AI体验学习交流群(72****874)][SYNC] <- 查 在线

23:28:07.194 [DefaultDispatcher-worker-1] net.mamoe.mirai.Bot(LoggerAdapterImpls.kt:35)
[TRACE] Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)

23:28:07.384 [nioEventLoopGroup-2-8] net.mamoe.mirai.Bot(LoggerAdapterImpls.kt:35)
[TRACE] Recv: MessageSvc.PbSendMsg

23:28:10.102 [DefaultDispatcher-worker-4] net.mamoe.mirai.Bot(LoggerAdapterImpls.kt:35)
[TRACE] Group(72****874) <- 在线账号：\n3051****6\n1328****06\n48****785
```
![G(E9F1Z@}`D9%9W5(@1EJE](https://github.com/mamoe/mirai/assets/96032725/f58df4bf-1450-4116-88b1-e36c12476737)

这个消息并没有出现`在线账号：\n3*******6\n132****06\n48****85`在客户端

### 复现

1. mirai-core-jvm 使用 二维码登录 ANDROID_WATCH
2. 机器人不定时出现无法发送消息的情况，无法发送消息的期间客户端始终接受不到消息
3. 需要注意的是，无法发送消息的情况似乎仅出现在群聊，因为将消息发送到好友会话中，好友是可以正常显示该消息的
4. 该情况可能仅出现在群聊，且期间，任意群聊均无法接受到机器人发送的消息
5. 准确来说可能机器人并没有发送消息
6. 但奇怪的是MiraiLogger输出了发送消息的trance日志
7. 更奇怪的是我的全局监听事件MessagePreEvent和MessagePostEvent事件并没有被触发
8. 该情况大概率出现在晚上九点左右到早上8点左右

### mirai-core 版本

2.15.0-M1

### bot-protocol

ANDROID_WATCH

### 系统日志

```text
[20:53:29.302] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Bot login successful.
[23:27:31.901] [INFO] - com.zaxxer.hikari.HikariDataSource.close(HikariDataSource.java:350) - HikariPool-1 - Shutdown initiated...
[23:27:31.963] [INFO] - com.zaxxer.hikari.HikariDataSource.close(HikariDataSource.java:352) - HikariPool-1 - Shutdown completed.
[23:27:45.023] [INFO] - org.springframework.boot.StartupInfoLogger.logStarting(StartupInfoLogger.java:55) - Starting Application using Java 11.0.19 on yf8eressengsw35 with PID 11204 (C:\Users\tenfond_154534133812\Documents\IdeaProjects\mirai\target\classes started by tenfond_154534133812 in C:\Users\tenfond_154534133812\Documents\IdeaProjects\mirai)
[23:27:45.047] [INFO] - org.springframework.boot.SpringApplication.logStartupProfileInfo(SpringApplication.java:631) - No active profile set, falling back to 1 default profile: "default"
[23:27:47.380] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Initializing ProtocolHandler ["https-jsse-nio-8086"]
[23:27:47.382] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Starting service [Tomcat]
[23:27:47.383] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Starting Servlet engine: [Apache Tomcat/9.0.75]
[23:27:47.602] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Initializing Spring embedded WebApplicationContext
[23:27:48.863] [INFO] - com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:110) - HikariPool-1 - Starting...
[23:27:49.421] [INFO] - com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:123) - HikariPool-1 - Start completed.
[23:27:50.490] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Starting ProtocolHandler ["https-jsse-nio-8086"]
[23:27:50.685] [INFO] - org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:173) - Connector [https-jsse-nio-8086], TLS virtual host [_default_], certificate type [UNDEFINED] configured from [file:/C:/Users/tenfond_154534133812/Documents/IdeaProjects/mirai/target/classes/META-INF/ssl/mirai.p12] using alias [tomcat] and with trust store [null]
[23:27:50.730] [INFO] - org.springframework.boot.StartupInfoLogger.logStarted(StartupInfoLogger.java:61) - Started Application in 6.613 seconds (JVM running for 10.498)
[23:27:50.735] [INFO] - com.tenfond.spring.controller.QqBotEventListener.botOnlineEventListener(QqBotEventListener.java:60) - BotOnlineEventListener Running
[23:27:50.901] [INFO] - com.tenfond.spring.controller.QqBotEventListener.botOfflineEventListener(QqBotEventListener.java:95) - BotOfflineEventListener Running
[23:27:50.902] [INFO] - com.tenfond.spring.controller.QqBotEventListener.botActiveOfflineEventListener(QqBotEventListener.java:106) - BotActiveOfflineEventListener Running
[23:27:50.904] [INFO] - com.tenfond.spring.controller.QqBotEventListener.botForceOfflineEventListener(QqBotEventListener.java:113) - BotForceOfflineEventListener Running
[23:27:50.904] [INFO] - com.tenfond.spring.controller.QqBotEventListener.botDroppedOfflineEventListener(QqBotEventListener.java:120) - BotDroppedOfflineEventListener Running
[23:27:50.905] [INFO] - com.tenfond.spring.controller.QqBotEventListener.botRequireReconnectOfflineEventListener(QqBotEventListener.java:129) - BotRequireReconnectOfflineEventListener Running
[23:27:50.906] [INFO] - com.tenfond.spring.controller.QqBotEventListener.botReloginEventListener(QqBotEventListener.java:136) - BotReloginEventListener Running
[23:27:50.907] [INFO] - com.tenfond.spring.controller.QqBotEventListener.botAvatarChangedEventListener(QqBotEventListener.java:143) - BotAvatarChangedEventListener Running
[23:27:50.907] [INFO] - com.tenfond.spring.controller.QqBotEventListener.botNickChangedEventListener(QqBotEventListener.java:150) - BotNickChangedEventListener Running
[23:27:50.908] [INFO] - com.tenfond.spring.controller.QqBotEventListener.nudgeEventListener(QqBotEventListener.java:157) - BotOfflineEventListener Running
[23:27:50.912] [INFO] - com.tenfond.spring.controller.QqMessageEventListener.messageEventListener(QqMessageEventListener.java:37) - MessageEventListener Running
[23:27:50.912] [INFO] - com.tenfond.spring.controller.QqMessagePostSendEventListener.messagePostSendEventListener(QqMessagePostSendEventListener.java:35) - MessagePostSendEventListener Running
[23:27:50.912] [INFO] - com.tenfond.spring.controller.QqMessagePreSendEventListener.messagePreSendEventListener(QqMessagePreSendEventListener.java:27) - MessagePreSendEventListener Running
[23:27:51.512] [INFO] - com.tenfond.config.PropertiesLoader.getYaml(PropertiesLoader.java:34) - yaml path = file:/C:/Users/tenfond_154534133812/Documents/IdeaProjects/mirai/target/classes/config.yml
[23:27:51.522] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:34) - HeartbeatStrategy: STAT_HB
[23:27:51.523] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:45) - Protocol: ANDROID_WATCH
[23:27:51.524] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:49) - WorkingDir: D:/ProgramData/mirai/485997785/
[23:27:51.524] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:62) - BasedDeviceInfo: android_watch_config.json
[23:27:51.529] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:105) - EnableContactCache: true
[23:27:52.823] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded account secrets from local cache.
[23:27:52.826] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - ECDH key is valid.
[23:27:53.167] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Saved account secrets to local cache for fast login.
[23:27:53.355] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Login successful.
[23:27:53.355] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Server time updated, serverTime: 1685806073, diff: 0ms=0.0s
[23:27:53.368] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Syncing friend message history...
[23:27:53.382] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Start loading friendGroup list...
[23:27:53.383] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 134 friends from local cache.
[23:27:53.387] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Start loading stranger list...
[23:27:53.483] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Start loading group list...
[23:27:53.488] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Successfully loaded stranger list: 0 in total
[23:27:53.511] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Online OtherClients: HUAWEI MatePad(IOS), Xiaomi 12 Pro (天玑版)(MOBILE)
[23:27:53.746] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Successfully loaded friendGroup list: 9 in total
[23:27:53.852] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 646 members from local cache for group [3/5周鲲年] 原子世界 (18******61)
[23:27:53.875] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 120 members from local cache for group 𝓞𝓬𝓮𝓪𝓷𝓲𝓪 𝓜𝓲𝓵𝓲𝓽𝓪𝓻𝔂 𝓑𝓪𝓼𝓮 (214807171)
[23:27:53.879] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 4 members from local cache for group 程序开发(学习群) (272*****2)
[23:27:53.899] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Syncing friend message history: Success.
[23:27:53.939] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 8 members from local cache for group 有福同享有难退群 (48******5)
[23:27:53.966] [WARN] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.warning0(LoggerAdapterImpls.kt:53) - Exception while loading GroupMemberListCache for group 314122535, possibly file corrupted. Deleting cache file.
net.mamoe.mirai.internal.deps.io.ktor.utils.io.charsets.MalformedInputException: Input length = 3
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.charsets.CharsetJVMKt.throwExceptionWrapped(CharsetJVM.kt:325) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.charsets.CharsetJVMKt.decode(CharsetJVM.kt:199) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.charsets.EncodingKt.decode(Encoding.kt:99) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.charsets.EncodingKt.decode$default(Encoding.kt:97) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.utils.MiraiUtils__IOKt.readAllText(IO.kt:154) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.utils.MiraiUtils.readAllText(Unknown Source) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.utils.FileKt.readText(File.kt:79) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.network.GroupMemberListCaches.get(ContactListCache.kt:118) ~[mirai-core-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.addGroupToBot(ContactUpdater.kt:235) ~[mirai-core-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.access$addGroupToBot(ContactUpdater.kt:73) ~[mirai-core-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl$reloadGroupList$2$2$1$1.invokeSuspend(ContactUpdater.kt:306) ~[mirai-core-jvm-2.15.0-M1.jar:2.15.0-M1]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.22.jar:1.7.22-release-288(1.7.22)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
[23:27:53.981] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 667 members from local cache for group 理想小镇 (371*****6)
[23:27:54.401] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 411 members from local cache for group COLACAPE Spring (977868784)
[23:27:54.420] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 87 members from local cache for group Internal test group of netease supervision group (102*****26)
[23:27:54.742] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 1253 members from local cache for group Future_Link_Studio (1072204519)
[23:27:54.748] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 1553 members from local cache for group Fast Builder ε Community  (1098232840)
[23:27:56.462] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Successfully loaded group list: 41 in total.
[23:27:56.700] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Saved 4 groups to local cache.
[23:27:56.718] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Scheduled key refresh in 23h 55min 0.0s.
[23:27:56.719] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Scheduled refresh login session in 19d 23h 55min 0.0s.
[23:27:56.745] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Bot login successful.
[23:27:56.748] [INFO] - com.tenfond.spring.controller.QqBotEventListener.lambda$botOnlineEventListener$2(QqBotEventListener.java:63) - 48******85 上线
[23:27:56.808] [INFO] - com.tenfond.config.PropertiesLoader.getYaml(PropertiesLoader.java:34) - yaml path = file:/C:/Users/tenfond_154534133812/Documents/IdeaProjects/mirai/target/classes/config.yml
[23:27:56.812] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:34) - HeartbeatStrategy: STAT_HB
[23:27:56.812] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:45) - Protocol: ANDROID_WATCH
[23:27:56.813] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:49) - WorkingDir: D:/ProgramData/mirai/1328752606/
[23:27:56.813] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:62) - BasedDeviceInfo: android_watch_config.json
[23:27:56.813] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:105) - EnableContactCache: true
[23:27:56.882] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded account secrets from local cache.
[23:27:56.882] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - ECDH key is valid.
[23:27:56.990] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Saved account secrets to local cache for fast login.
[23:27:57.147] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Server time updated, serverTime: 1685806077, diff: 0ms=0.0s
[23:27:57.148] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Login successful.
[23:27:57.150] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Syncing friend message history...
[23:27:57.152] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Start loading friendGroup list...
[23:27:57.153] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 8 friends from local cache.
[23:27:57.155] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Start loading stranger list...
[23:27:57.222] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Start loading group list...
[23:27:57.323] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - No OtherClient online.
[23:27:57.326] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Successfully loaded friendGroup list: 4 in total
[23:27:57.331] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Successfully loaded stranger list: 1 in total
[23:27:57.364] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 25 members from local cache for group AI体验学习交流群 (72*****74)
[23:27:57.914] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Successfully loaded group list: 5 in total.
[23:27:57.939] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Saved 1 groups to local cache.
[23:27:57.953] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Bot login successful.
[23:27:57.967] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Scheduled key refresh in 23h 55min 0.0s.
[23:27:57.967] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Scheduled refresh login session in 19d 23h 55min 0.0s.
[23:27:57.967] [INFO] - com.tenfond.spring.controller.QqBotEventListener.lambda$botOnlineEventListener$2(QqBotEventListener.java:63) - 1328752606 上线
[23:27:57.997] [INFO] - com.tenfond.config.PropertiesLoader.getYaml(PropertiesLoader.java:34) - yaml path = file:/C:/Users/tenfond_154534133812/Documents/IdeaProjects/mirai/target/classes/config.yml
[23:27:58.001] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:34) - HeartbeatStrategy: STAT_HB
[23:27:58.001] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:45) - Protocol: ANDROID_WATCH
[23:27:58.002] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:49) - WorkingDir: D:/ProgramData/mirai/3051794966/
[23:27:58.002] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:62) - BasedDeviceInfo: android_watch_config.json
[23:27:58.002] [INFO] - com.tenfond.config.QqBotConfiguration.<init>(QqBotConfiguration.java:105) - EnableContactCache: true
[23:27:58.024] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Syncing friend message history: Success.
[23:27:58.064] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded account secrets from local cache.
[23:27:58.064] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - ECDH key is valid.
[23:27:58.161] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Saved account secrets to local cache for fast login.
[23:27:58.259] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Server time updated, serverTime: 1685806078, diff: 0ms=0.0s
[23:27:58.261] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Login successful.
[23:27:58.264] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Syncing friend message history...
[23:27:58.269] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 13 friends from local cache.
[23:27:58.270] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Start loading friendGroup list...
[23:27:58.274] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Start loading stranger list...
[23:27:58.337] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Start loading group list...
[23:27:58.356] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Successfully loaded stranger list: 0 in total
[23:27:58.357] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Online OtherClients: Xiaomi 12 Pro (天玑版)(MOBILE)
[23:27:58.445] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Successfully loaded friendGroup list: 9 in total
[23:27:58.456] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 7 members from local cache for group 轻轻松松学习群 (1038654367)
[23:27:58.456] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Loaded 25 members from local cache for group AI体验学习交流群 (723*****4)
[23:27:59.072] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Successfully loaded group list: 6 in total.
[23:27:59.091] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Saved 1 groups to local cache.
[23:27:59.093] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Scheduled key refresh in 23h 55min 0.0s.
[23:27:59.094] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Scheduled refresh login session in 19d 23h 55min 0.0s.
[23:27:59.094] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Bot login successful.
[23:27:59.094] [INFO] - com.tenfond.spring.controller.QqBotEventListener.lambda$botOnlineEventListener$2(QqBotEventListener.java:63) - 305****66 上线
[23:27:59.162] [INFO] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.info0(LoggerAdapterImpls.kt:47) - Syncing friend message history: Success.
```

### 网络日志

```text
[23:27:53.966] [WARN] - net.mamoe.mirai.internal.utils.Log4jLoggerAdapter.warning0(LoggerAdapterImpls.kt:53) - Exception while loading GroupMemberListCache for group 314122535, possibly file corrupted. Deleting cache file.
net.mamoe.mirai.internal.deps.io.ktor.utils.io.charsets.MalformedInputException: Input length = 3
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.charsets.CharsetJVMKt.throwExceptionWrapped(CharsetJVM.kt:325) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.charsets.CharsetJVMKt.decode(CharsetJVM.kt:199) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.charsets.EncodingKt.decode(Encoding.kt:99) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.deps.io.ktor.utils.io.charsets.EncodingKt.decode$default(Encoding.kt:97) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.utils.MiraiUtils__IOKt.readAllText(IO.kt:154) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.utils.MiraiUtils.readAllText(Unknown Source) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.utils.FileKt.readText(File.kt:79) ~[mirai-core-utils-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.network.GroupMemberListCaches.get(ContactListCache.kt:118) ~[mirai-core-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.addGroupToBot(ContactUpdater.kt:235) ~[mirai-core-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl.access$addGroupToBot(ContactUpdater.kt:73) ~[mirai-core-jvm-2.15.0-M1.jar:2.15.0-M1]
	at net.mamoe.mirai.internal.network.components.ContactUpdaterImpl$reloadGroupList$2$2$1$1.invokeSuspend(ContactUpdater.kt:306) ~[mirai-core-jvm-2.15.0-M1.jar:2.15.0-M1]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.7.22.jar:1.7.22-release-288(1.7.22)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[kotlinx-coroutines-core-jvm-1.6.4.jar:?]
```

**Comment by Takeoff0518** [comment]
#2671

**Comment by MrY-Cat** [comment]
风控

**Comment by tanfond** [comment]
有时候 MiraiLogger 输出了接受到的消息，但全局监听的MessageEvent事件没有被触发，不知道什么好事

**Comment by Him188** [comment]
#2688
