### ISSUE TITLE
2.15.0-M1登录时抛出net.mamoe.mirai.internal.network.auth.ProducerFailureException

### ISSUE THREAD

**Issue by WutzuBert** [mamoe/mirai#2687]
### 问题描述

在本地Windows电脑调试时，二维码登录/密码登录都是正常的
但当我将整个mcl端迁移到Linux主机上进行登录时，抛出了该异常

### 复现

1.使用版本为2.15.0-M1的Mirai三件套
2.在Linux机器上执行登录

### mirai-core 版本

2.15.0-M1

### bot-protocol

ANDROID_WATCH

### 其他组件版本

mirai-console-dev-qrlogin-0.1.8.mirai2

### 系统日志

```text
2023-06-06 14:21:13 W/QRLoginSolver: 当前没有桌面环境，将不使用窗口式扫码登录监听器。
2023-06-06 14:21:13 I/QRLoginSolver: 登录解决器更换为 QRLoginSolver
2023-06-06 14:21:13 I/Bot.1243733821: Bot cancelled: Bot closed
2023-06-06 14:21:13 E/console: net.mamoe.mirai.internal.network.auth.ProducerFailureException
net.mamoe.mirai.internal.network.auth.ProducerFailureException
	at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
	at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.internal.network.auth.IllegalProducerStateException: CreatingProducer
	at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope$Producer.emit(CoroutineOnDemandValueScope.kt:76)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1$sessionImpl$1.authByQRCode(AuthControl.kt:53)
	at net.mamoe.mirai.internal.network.auth.DefaultBotAuthorizationFactoryImpl$byQRCode$1.authorize(DefaultBotAuthorizationFactoryImpl.kt:46)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1.invokeSuspend(AuthControl.kt:77)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1.invoke(AuthControl.kt)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1.invoke(AuthControl.kt)
	at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope$Producer$1.invokeSuspend(CoroutineOnDemandValueScope.kt:50)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	... 5 more
```

### 网络日志

```text
[0m
[93m2023-06-06 14:21:08 W/Net 1243733821: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.auth.ProducerFailureException)[0m
[0m2023-06-06 14:21:13 V/Net 1243733821: Validated caches.[0m
[0m2023-06-06 14:21:13 V/Net 1243733821: No server list cached.[0m
[96m2023-06-06 14:21:13 D/Net 1243733821: CAS: JustInitialized -> CreatingProducer: true[0m
[0m2023-06-06 14:21:13 V/Net 1243733821: [AuthControl/auth] Authorization started[0m
[0m2023-06-06 14:21:13 V/Net 1243733821: [AuthControl/auth] Authorization failed: net.mamoe.mirai.internal.network.auth.IllegalProducerStateException: CreatingProducer[0m
[96m2023-06-06 14:21:13 D/Net 1243733821: CAS: CreatingProducer -> Finished(CreatingProducer, net.mamoe.mirai.internal.network.auth.IllegalProducerStateException: CreatingProducer): true[0m
[96m2023-06-06 14:21:13 D/Net 1243733821: CAS: CreatingProducer -> ProducerReady: false[0m
[92m2023-06-06 14:21:13 I/Net 1243733821: ECDH key is invalid, start to fetch ecdh public key from server.[0m
[92m2023-06-06 14:21:13 I/Net 1243733821: Successfully fetched ecdh public key from server.[0m
[0m2023-06-06 14:21:13 V/Net 1243733821: [AuthControl/acquire] Acquiring auth method[0m
[96m2023-06-06 14:21:13 D/Net 1243733821: [AuthControl/acquire] Authorization responded: Error[net.mamoe.mirai.internal.network.auth.ProducerFailureException]@883524511[0m
[93m2023-06-06 14:21:13 W/Net 1243733821: Failed with auth method: Error[net.mamoe.mirai.internal.network.auth.ProducerFailureException]@883524511
net.mamoe.mirai.internal.network.auth.ProducerFailureException
	at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
	at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.internal.network.auth.IllegalProducerStateException: CreatingProducer
	at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope$Producer.emit(CoroutineOnDemandValueScope.kt:76)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1$sessionImpl$1.authByQRCode(AuthControl.kt:53)
	at net.mamoe.mirai.internal.network.auth.DefaultBotAuthorizationFactoryImpl$byQRCode$1.authorize(DefaultBotAuthorizationFactoryImpl.kt:46)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1.invokeSuspend(AuthControl.kt:77)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1.invoke(AuthControl.kt)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1.invoke(AuthControl.kt)
	at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope$Producer$1.invokeSuspend(CoroutineOnDemandValueScope.kt:50)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	... 5 more
[0m
[93m2023-06-06 14:21:13 W/Net 1243733821: Exception in resumeConnection.
net.mamoe.mirai.internal.network.auth.ProducerFailureException
	at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152)
	at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.internal.network.auth.IllegalProducerStateException: CreatingProducer
	at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope$Producer.emit(CoroutineOnDemandValueScope.kt:76)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1$sessionImpl$1.authByQRCode(AuthControl.kt:53)
	at net.mamoe.mirai.internal.network.auth.DefaultBotAuthorizationFactoryImpl$byQRCode$1.authorize(DefaultBotAuthorizationFactoryImpl.kt:46)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1.invokeSuspend(AuthControl.kt:77)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1.invoke(AuthControl.kt)
	at net.mamoe.mirai.internal.network.auth.AuthControl$userDecisions$1.invoke(AuthControl.kt)
	at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope$Producer$1.invokeSuspend(CoroutineOnDemandValueScope.kt:50)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	... 5 more
[0m
[93m2023-06-06 14:21:13 W/Net 1243733821: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.auth.ProducerFailureException)[0m
```

### 补充信息

操作系统：Ubuntu Server:18.04

**Comment by MrXiaoM** [comment]
重复 #2623

**Comment by WutzuBert** [comment]
> 重复 #2623

这个issue解决方法里的预览版本早就过期被删除了

**Comment by Him188** [comment]
本 commit 的预览版本号: 2.15.0-dev-98 在 <https://github.com/mamoe/mirai/blob/dev/docs/UsingSnapshots.md> 查看如何使用预览版本

**Comment by Him188** [comment]
https://build.mirai.mamoe.net/v1/mirai-core/dev/indexes/latest
获得最新版本号
