### ISSUE TITLE
mirai-console 禁用插件后再启用插件报错 net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while enabling xxxxxx

### ISSUE THREAD

**Issue by douziiA** [mamoe/mirai#2691]
### 问题描述

禁用插件后再启用插件报错
`net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while enabling LuckPerms`

### 复现

1. 先禁用
 `JvmPluginLoader.BuiltIn.disable((JvmPlugin) plugin);`
or
`PluginManager.INSTANCE.disablePlugin(plugin);`

效果日志:
```
2023-06-13 09:14:33 I/LuckPerms: Starting shutdown process...
2023-06-13 09:14:33 I/LuckPerms: Closing storage...
2023-06-13 09:14:33 I/LuckPerms: Goodbye!
```

2. 再启动
`JvmPluginLoader.BuiltIn.enable((JvmPlugin) plugin);`
or
`PluginManager.INSTANCE.enablePlugin(plugin);`

报错日志:
```
2023-06-13 09:42:32 W/stderr: Exception in thread "main" net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while enabling LuckPerms
2023-06-13 09:42:32 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:311)
2023-06-13 09:42:32 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
2023-06-13 09:42:32 W/stderr: 	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
2023-06-13 09:42:32 W/stderr: 	at com.douzii.botcms.MiraibotApplication.main(MiraibotApplication.java:37)
2023-06-13 09:42:32 W/stderr: Caused by: java.lang.IllegalStateException: Failed to switch plugin 'io.github.karlatemp.luckperms-mirai' status from LOAD_LOAD_DONE to ENABLE_PENDING, current status = DISABLED
2023-06-13 09:42:32 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.switchStatusOrFail$mirai_console(JvmPluginInternal.kt:116)
2023-06-13 09:42:32 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:219)
2023-06-13 09:42:32 W/stderr: 	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:305)
2023-06-13 09:42:32 W/stderr: 	... 3 more
> 
```

### mirai-core 版本

2.15.0-M1

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-console-terminal 2.15.0-M1
mirai-console 2.15.0-M1

### 系统日志

```text
2023-06-13 09:14:33 I/LuckPerms: Starting shutdown process...
2023-06-13 09:14:33 I/LuckPerms: Closing storage...
2023-06-13 09:14:33 I/LuckPerms: Goodbye!
2023-06-13 09:14:41 I/stdout: java.lang.IllegalStateException: Plugin 'LuckPerms' is already loaded and cannot be reloaded.
```

**Comment by douziiA** [comment]
翻了一下JvmPluginInternal.kt
可能是因为插件状态转换成DISABLED无法和LOAD_LOAD_DONE匹配报错

internalOnDisable代码块
```
onSuccess = {
                pluginStatus.value = PluginStatus.DISABLED //最后转换DISABLED

                cancel(CancellationException("plugin disabled"))
            },
```

internalOnEnable代码块
```
switchStatusOrFail(PluginStatus.LOAD_LOAD_DONE, PluginStatus.ENABLE_PENDING)
```

状态不匹配报错代码块
```
@JvmSynthetic
    internal fun switchStatusOrFail(expect: PluginStatus, update: PluginStatus) {
        val nowStatus = pluginStatus.value
        if (nowStatus === expect) {//因为DISABLED 不等于 LOAD_LOAD_DONE
            //省略的代码块
        }
        error("Failed to switch plugin '$id' status from $expect to $update, current status = $nowStatus")//抛出的异常
    }
```

有没有其他方法让他禁用以后再启动，还是没办法因为某种原因不实现这功能

**Comment by Karlatemp** [comment]
https://github.com/mamoe/mirai/blob/3ec8e552cda81f1e7f28a4c033c32557ab40e73d/mirai-console/docs/plugin/JVMPlugin.md?plain=1#L364-L370
