### ISSUE TITLE
Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper

### ISSUE THREAD

**Issue by AsakuraFuuko** [mamoe/mirai#270]
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Fetching Newest Console Version of Pure
Local Core Version: 0.39.2 | Newest Core Version: 0.39.2
Local Console-Pure Version: 0.4.11 | Newest Console-Pure Version: 0.4.11
Version check complete, starting Mirai
shadow-Protocol:/root/mirai/content/mirai-core-qqandroid-jvm-0.39.2.jar
Console        :/root/mirai/content/mirai-console-0.4.11.jar
Root           :/root/mirai/
 10:58:46 [INFO] [Mirai 0.4.11 Pkmon] Mirai-console now running under /root/mirai
 10:58:46 [INFO] [Mirai 0.4.11 Pkmon] Get news in github: https://github.com/mamoe/mirai
 10:58:46 [INFO] [Mirai 0.4.11 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
 10:58:46 [INFO] [Mirai 0.4.11 Pkmon] Powered by Mamoe Technologies and contributors
 10:58:46 [INFO] [Plugin Manager] 开始加载/root/mirai/plugins/下的插件
 10:58:46 [INFO] [Plugin Manager] loading plugin MiraiAPIHTTP
 10:58:46 [INFO] [Plugin Manager] successfully loaded plugin MiraiAPIHTTP version v1.6.3 by ryoii
 10:58:46 [INFO] [Plugin Manager] Mirai HTTP API Server Plugin
 10:58:46 [INFO] [MiraiAPIHTTP] Loading Mirai HTTP API plugin
 10:58:46 [INFO] [MiraiAPIHTTP] Trying to Start Mirai HTTP Server in 0.0.0.0:6800
 10:58:46 [INFO] [MiraiAPIHTTP] Starting Mirai HTTP Server in 0.0.0.0:6800
Mirai HTTP API 10:58:46 : Http api server is running with authKey:
 10:58:46 [INFO] [MiraiAPIHTTP] 心跳模块启用状态: false
 10:58:46 [INFO] [MiraiAPIHTTP] 上报模块启用状态: false
 10:58:46 [INFO] [Plugin Manager] 加载了1个插件
 10:58:46 [INFO] [Mirai 0.4.11 Pkmon] Mirai-console 启动完成
 10:58:46 [INFO] [Mirai 0.4.11 Pkmon] "/login qqnumber qqpassword " to login a bot
 10:58:46 [INFO] [Mirai 0.4.11 Pkmon] "/login qq号 qq密码 " 来登录一个BOT
/login xxxx xxxx
 10:58:52 [INFO] [Bot Login] login...
 10:58:52 [INFO] [Mirai 0.4.11 Pkmon] java.awt.AWTError: Assistive Technology not found: org.GNOME.Accessibility.AtkWrapper
        at java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:807)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:886)
        at java.awt.Desktop.isDesktopSupported(Desktop.java:169)
        at net.mamoe.mirai.utils.LoginSolver$Companion.getDefault(LoginSolver.jvm.kt:137)
        at net.mamoe.mirai.utils.BotConfiguration.<init>(BotConfiguration.kt:75)
        at net.mamoe.mirai.utils.BotConfiguration.<clinit>(BotConfiguration.kt:82)
        at net.mamoe.mirai.console.command.DefaultCommands.login(DefaultCommands.kt:374)
        at net.mamoe.mirai.console.command.DefaultCommands$invoke$2$1.invokeSuspend(DefaultCommands.kt:188)
        at net.mamoe.mirai.console.command.DefaultCommands$invoke$2$1.invoke(DefaultCommands.kt)
        at net.mamoe.mirai.console.command.AnonymousCommand.onCommand(Command.kt:122)
        at net.mamoe.mirai.console.command.CommandManager.processCommandImpl(CommandManager.kt:156)
        at net.mamoe.mirai.console.command.CommandManager$processCommand$2.invokeSuspend(CommandManager.kt:146)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by AsakuraFuuko** [comment]
> vim /etc/java-8-openjdk/accessibility.properties

注释掉这行，可用

> assistive_technologies=org.GNOME.Accessibility.AtkWrapper

**Comment by Karlatemp** [comment]
很奇怪, Desktop.isDesktopSupported这玩意还要try-catch
