### ISSUE TITLE
用mcl启动报错java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutineScope

### ISSUE THREAD

**Issue by ghost** [mamoe/mirai#2710]
### 问题描述

用mcl启动mirai报此错误
** mirai 2.14.0可以正常启动
```
12:02:32 [ERROR] java.lang.NoClassDefFoundError: kotlinx/coroutines/CoroutineScope
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)                                 at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
        at java.base/java.lang.Class.getMethodsRecursive(Class.java:3543)
        at java.base/java.lang.Class.getMethod0(Class.java:3529)
        at java.base/java.lang.Class.getMethod(Class.java:2225)
        at org.itxtech.mcl.Utility.lambda$bootJars$0(Utility.java:78)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:85)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.ClassNotFoundException: kotlinx.coroutines.CoroutineScope
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 42 more
```

### 复现

1. 用MCL Installer Auto Release ae9f946安装mcl，然后自动安装mirai 2.14.0（可以正常启动）
2. 在config.json里把maven-stable与2.14.0分别替换成maven-beta与2.15.0-RC
3. 启动mcl，自动安装mirai 2.15.0-RC，然后无法正常启动，报错

### mirai-core 版本

2.15.0-RC

### bot-protocol

ANDROID_PHONE

### 其他组件版本

无法启动mirai-console

### 系统日志

```text
[pastebin](https://pastebin.com/E0djWrJh)
```

### 网络日志

```text
无
```

### 补充信息

环境: Ubuntu 22.04
Java: openjdk-17-jre

**Comment by StageGuard** [comment]
maven 仓库下载的构建没有依赖，请前往 repo.mirai.mamoe.net 下载对应版本的后缀带 -all 的包

**Comment by gamecss** [comment]
> maven 仓库下载的构建没有依赖，请前往 repo.mirai.mamoe.net 下载对应版本的后缀带 -all 的包

好像没有mirai-core-all？

**Comment by ghost** [comment]
> maven 仓库下载的构建没有依赖，请前往 repo.mirai.mamoe.net 下载对应版本的后缀带 -all 的包

@StageGuard 我用了这些（确是从repo.mirai.mamoe.net下载的）
```
  14:49:38 [INFO] Verifying "net.mamoe:mirai-console" v2.15.0-RC-2-15-release-1
  14:49:38 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.15.0-RC-2-15-release-1
  14:49:39 [INFO] Verifying "net.mamoe:mirai-core-jvm" v2.15.0-RC-2-15-release-1
```
但是问题依旧

**Comment by cssxsh** [comment]
> maven 仓库下载的构建没有依赖，请前往 repo.mirai.mamoe.net 下载对应版本的后缀带 -all 的包

@StageGuard 你说反了吧 repo.mirai.mamoe.net 的 snapshots 包反倒才是没有 -all 包

@gamecss 

我推测是阿里云的问题，
可以尝试修改 config.json 文件
```
  "maven_repo": [
    "https://repo.huaweicloud.com/repository/maven"
  ],
```
另外把版本改回 2.15.0-RC

**Comment by ghost** [comment]
> > maven 仓库下载的构建没有依赖，请前往 repo.mirai.mamoe.net 下载对应版本的后缀带 -all 的包
> 
> @StageGuard 你说反了吧 repo.mirai.mamoe.net 的 snapshots 包反倒才是没有 -all 包
> 
> @gamecss
> 
> 我推测是阿里云的问题， 可以尝试修改 config.json 文件
> 
> ```
>   "maven_repo": [
>     "https://repo.huaweicloud.com/repository/maven"
>   ],
> ```
> 
> 另外把版本改回 2.15.0-RC

有用，感谢！
