### ISSUE TITLE
消息撤回失败后再次撤回显示已经撤回，但是查看后未撤回

### ISSUE THREAD

**Issue by lliioollcn** [mamoe/mirai#274]
## 问题
机器人撤回消息失败后再次撤回会抛出消息已经撤回，但是实际没有撤回
以下为报错
```
 17:10:22 [INFO] [NETWORK] Packet: Failed(result=1001, errorMessage=No message meets the requirements)
Exception in thread "EventTask-1" java.lang.Error: java.lang.reflect.InvocationTargetException
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.lliiooll.managers.EventManager.callA(EventManager.java:66)
        at cn.lliiooll.managers.EventManager.lambda$call$0(EventManager.java:53)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        ... 2 more
Caused by: java.lang.IllegalStateException: Failed to recall message #9901: Failed(result=1001, errorMessage=No message meets the requirements)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.recall$suspendImpl(QQAndroidBot.common.kt:473)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase$recall$1.invokeSuspend(QQAndroidBot.common.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.BotJavaFriendlyAPI.recall(BotJavaFriendlyAPI.kt:225)
        at cn.lliiooll.executors.event.listeners.AntiDeleteMessageListener.onGroupMsg(AntiDeleteMessageListener.java:96)
        ... 9 more
 17:10:24 [INFO] [BOT 310349950] [星瞳圣域服务器群(463370226)] 3119163503(3119163503) -> [mirai:source:9911,448919007][mirai:image:{126FDC39-ABF4-70AD-20C9-D4F60235F51B}.mirai]
Exception in thread "EventTask-3" java.lang.Error: java.lang.reflect.InvocationTargetException
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.lliiooll.managers.EventManager.callA(EventManager.java:66)
        at cn.lliiooll.managers.EventManager.lambda$call$0(EventManager.java:53)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        ... 2 more
Caused by: java.lang.IllegalStateException: [mirai:source:9901,1119460322] had already been recalled.
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.recall$suspendImpl(QQAndroidBot.common.kt:364)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.recall(QQAndroidBot.common.kt)
        at net.mamoe.mirai.BotJavaFriendlyAPI$__recallBlockingForJava__$$inlined$runBlocking$2.invokeSuspend(BotJavaFriendlyAPI.kt:224)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.BotJavaFriendlyAPI.recall(BotJavaFriendlyAPI.kt:225)
        at cn.lliiooll.executors.event.listeners.AntiDeleteMessageListener.onGroupMsg(AntiDeleteMessageListener.java:96)
        ... 9 more
 17:10:25 [INFO] [BOT 310349950] [星瞳圣域服务器群(463370226)] 3119163503(3119163503) -> [mirai:source:9912,985633780][mirai:image:{126FDC39-ABF4-70AD-20C9-D4F60235F51B}.mirai]
Exception in thread "EventTask-4" java.lang.Error: java.lang.reflect.InvocationTargetException
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.lliiooll.managers.EventManager.callA(EventManager.java:66)
        at cn.lliiooll.managers.EventManager.lambda$call$0(EventManager.java:53)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        ... 2 more
Caused by: java.lang.IllegalStateException: [mirai:source:9901,1119460322] had already been recalled.
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.recall$suspendImpl(QQAndroidBot.common.kt:364)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.recall(QQAndroidBot.common.kt)
        at net.mamoe.mirai.BotJavaFriendlyAPI$__recallBlockingForJava__$$inlined$runBlocking$2.invokeSuspend(BotJavaFriendlyAPI.kt:224)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.BotJavaFriendlyAPI.recall(BotJavaFriendlyAPI.kt:225)
        at cn.lliiooll.executors.event.listeners.AntiDeleteMessageListener.onGroupMsg(AntiDeleteMessageListener.java:96)
        ... 9 more
 17:10:26 [INFO] [BOT 310349950] [星瞳圣域服务器群(463370226)] 3119163503(3119163503) -> [mirai:source:9913,457792331][mirai:image:{126FDC39-ABF4-70AD-20C9-D4F60235F51B}.mirai]
Exception in thread "EventTask-0" java.lang.Error: java.lang.reflect.InvocationTargetException
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cn.lliiooll.managers.EventManager.callA(EventManager.java:66)
        at cn.lliiooll.managers.EventManager.lambda$call$0(EventManager.java:53)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        ... 2 more
Caused by: java.lang.IllegalStateException: [mirai:source:9901,1119460322] had already been recalled.
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.recall$suspendImpl(QQAndroidBot.common.kt:364)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.recall(QQAndroidBot.common.kt)
        at net.mamoe.mirai.BotJavaFriendlyAPI$__recallBlockingForJava__$$inlined$runBlocking$2.invokeSuspend(BotJavaFriendlyAPI.kt:224)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.BotJavaFriendlyAPI.recall(BotJavaFriendlyAPI.kt:225)
        at cn.lliiooll.executors.event.listeners.AntiDeleteMessageListener.onGroupMsg(AntiDeleteMessageListener.java:96)
        ... 9 more
```

## 如何复现
无

**Comment by Him188** [comment]
设计就是这样

**Comment by Him188** [comment]
能否提供第一次撤回的代码和相关环境

**Comment by lliioollcn** [comment]
抱歉，问题发现了。
只有你发送之后立即撤回，机器人在撤回你发送的消息的时候就会失败，然后抛错
