### ISSUE TITLE
插件依赖没有自动下载

### ISSUE THREAD

**Issue by EricDeng1001** [mamoe/mirai#2756]
### 问题描述

我做了一个插件无法运行，经过调查是插件依赖没有自动下载。为了最小化问题可能，我做了一个特别简单的项目。

### 复现

1. 使用IDEA的插件创建一个项目，选用kotlin和gradle kotlin
2. 添加一个依赖
```
dependencies {
    implementation("com.microsoft.playwright:playwright:1.36.0")
}
```
3. 使用gradle:mirai:buildPlugin编译
4. 放到mcl 2.1.2 的plugins目录
6. 运行，报错，找不到类（一个被依赖的类，理应存在于classpath里面）
7. 观察日志，发现没有下载。

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

Running MiraiConsole v2.15.0, built on 2023-07-11 04:57:17.
Frontend Terminal: version 2.15.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: Demo(crashed_enable_error) v0.1.0, mirai-login-solver-sakura v0.0.11, MCL Addon v2.1.1

Object Pending Finalization Count: 0
                 committed |  init  |  used   |   max
    Heap Memory:  112.0MB  | 1.0GB  | 38.57MB | 15.93GB
Non-Heap Memory:  64.06MB  | 7.31MB | 62.37MB |   -1

### 系统日志

```text
19:33:23 [INFO] iTX Technologies Mirai Console Loader version 2.1.2-61c8bd8
  19:33:23 [INFO] Runtime: OpenJDK 64-Bit Server VM 17.0.8 (arch: 64)
  19:33:23 [INFO] https://github.com/iTXTech/mirai-console-loader
  19:33:23 [INFO] This program is licensed under GNU AGPL v3
  19:33:24 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

如果在图片上传的时候遇到问题请与我们联系 (需要提供图片文件源本)
`- 如 Unsupported image type for ExternalResource *
`  considering use gif/png/bmp/jpg format.
`- Tracker: https://github.com/mamoe/mirai/issues/new/choose

常用资源整合
`- https://mirai.mamoe.net/topic/653

MCL 已推出 2.1.0，更好的支持 Mirai 2.11 的插件系统，建议更新。

  19:33:24 [INFO] Verifying "net.mamoe:mirai-console" v2.15.0
  19:33:25 [INFO] Verifying "net.mamoe:mirai-console-terminal" v2.15.0
  19:33:25 [INFO] Verifying "net.mamoe:mirai-core-all" v2.15.0
  19:33:25 [INFO] Verifying "org.itxtech:mcl-addon" v2.1.1
2023-07-26 19:33:27 I/main: Starting mirai-console...
2023-07-26 19:33:27 I/main:

===================================[ Mirai console 2.15.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-07-26 19:33:27 I/main: Backend: version 2.15.0, built on 2023-07-11 04:57:17.
2023-07-26 19:33:27 I/main: Frontend Terminal: version 2.15.0, provided by Mamoe Technologies
2023-07-26 19:33:27 I/main: Welcome to visit https://mirai.mamoe.net/
2023-07-26 19:33:28 I/plugin: Successfully loaded plugin Demo v0.1.0
2023-07-26 19:33:28 I/plugin: Successfully loaded plugin mirai-login-solver-sakura v0.0.11
2023-07-26 19:33:28 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-07-26 19:33:28 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2023-07-26 19:33:28 I/Demo: Plugin loaded
2023-07-26 19:33:28 E/Demo: java.lang.RuntimeException: Failed to create driver
java.lang.RuntimeException: Failed to create driver
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:105)
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.impl.driver.Driver.ensureDriverInstalled(Driver.java:57)
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.impl.PlaywrightImpl.createImpl(PlaywrightImpl.java:45)
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.impl.PlaywrightImpl.create(PlaywrightImpl.java:35)
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.Playwright.create(Playwright.java:110)
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.Playwright.create(Playwright.java:114)
        at MCLTest-0.1.0.mirai2.jar//com.example.Demo.onEnable(Demo.kt:19)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:237)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:308)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:39)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:54)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:181)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:359)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toURI()" because the return value of "java.lang.ClassLoader.getResource(String)" is null
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.impl.driver.jar.DriverJar.getDriverResourceURI(DriverJar.java:119)
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.impl.driver.jar.DriverJar.extractDriverToTempDir(DriverJar.java:123)
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.impl.driver.jar.DriverJar.initialize(DriverJar.java:66)
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.impl.driver.Driver.initialize(Driver.java:64)
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.impl.driver.Driver.createAndInstall(Driver.java:101)
        ... 31 more

2023-07-26 19:33:28 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2023-07-26 19:33:28 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2023-07-26 19:33:28 I/main: 2 plugin(s) enabled.
2023-07-26 19:33:28 I/main: mirai-console started successfully.
```

### 补充信息

可以复现问题的项目地址在这：
https://github.com/EricDeng1001/MCLTest

**Comment by EricDeng1001** [comment]
再补充一点信息：我尝试手动把所有依赖放到plugin-dependency目录，但是没有用，我在onEnable()方法内调用
`println(System.getProperty("java.class.path"))`发现仅输出一个`mcl.jar`

**Comment by cssxsh** [comment]
https://github.com/mamoe/mirai/blob/dev/mirai-console/docs/plugin/JVMPlugin-Debug.md#%E4%BD%BF%E7%94%A8%E7%9A%84%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BA%93%E6%8A%A5%E9%94%99%E6%B2%A1%E6%9C%89%E6%A8%A1%E5%9D%97%E5%AE%9E%E7%8E%B0

**Comment by Karlatemp** [comment]
你应该查看

```
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toURI()" because the return value of "java.lang.ClassLoader.getResource(String)" is null
        at MCLTest-0.1.0.mirai2.jar[private]//com.microsoft.playwright.impl.driver.jar.DriverJar.getDriverResourceURI(DriverJar.java:119)
```

找到最终原因再报告，而且你可以在 `config/Console/Logger.yml` 开启全部日志

出现 `[private]` 说明依赖库已经下载了

**Comment by EricDeng1001** [comment]
> https://github.com/mamoe/mirai/blob/dev/mirai-console/docs/plugin/JVMPlugin-Debug.md#%E4%BD%BF%E7%94%A8%E7%9A%84%E7%AC%AC%E4%B8%89%E6%96%B9%E5%BA%93%E6%8A%A5%E9%94%99%E6%B2%A1%E6%9C%89%E6%A8%A1%E5%9D%97%E5%AE%9E%E7%8E%B0

解决了，thanks
