### ISSUE TITLE
从maven拉到的Mirai-console:2.15.0 jar包中  slf4j冲突 初步判断是引用错误

### ISSUE THREAD

**Issue by Jasonyou-boy** [mamoe/mirai#2776]
### 问题描述

从maven拉到的Mirai-console:2.15.0 jar包中  slf4j冲突 初步判断是引用错误

### 复现

使用gradle拉取Mirai-console:2.15.0 并启动

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PHONE

### 补充信息

![image](https://github.com/mamoe/mirai/assets/96352227/4da255ea-b7d8-4e46-af7a-c73312c459a3)
经过查验，slf4j-api-1.6.6.jar中确实不存在 void org.slf4j.helpers.SubstituteLoggerFactory.postInitialization()方法

**Comment by Jasonyou-boy** [comment]
**错误提示**
2023-08-17 00:39:03 E/main: Failed to init MiraiConsole.
java.lang.NoSuchMethodError: 'void org.slf4j.helpers.SubstituteLoggerFactory.postInitialization()'
	at net.mamoe.mirai.console.internal.logging.externalbind.slf4j.MiraiConsoleSLF4JAdapter.doSlf4JInit$mirai_console(MiraiConsoleSLF4JService.kt:79)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:291)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
	at com.happysnaker.RunTerminalKt.main(RunTerminal.kt:17)
	at com.happysnaker.RunTerminalKt$main$2.invoke(RunTerminal.kt)
	at com.happysnaker.RunTerminalKt$main$2.invoke(RunTerminal.kt)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at com.happysnaker.RunTerminalKt.main(RunTerminal.kt)

**Comment by Karlatemp** [comment]
#2055 #2056
https://github.com/project-mirai/mirai-console-plugin-template/blob/master/src/test/kotlin/RunMirai.kt#L12-L19

**Comment by Jasonyou-boy** [comment]
非常感谢，问题已解决
