### ISSUE TITLE
收到短视频消息时报错

### ISSUE THREAD

**Issue by 0f-0b** [mamoe/mirai#2793]
### 问题描述

群内收到视频时 Console 报错。

### 复现

群成员发送视频。

### mirai-core 版本

8ac0536deb71e165c865fae77b2e849dc344534a

### bot-protocol

ANDROID_PAD

### 其他组件版本

```text
Running MiraiConsole v2.16.0+local, built on 2023-09-06 23:24:58.
Frontend Terminal: version 2.16.0+local, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: fix-protocol-version v1.10.0, mirai-api-http v2.9.1, Silk Converter v0.0.6-fix-cssxsh, QRLogin v0.2.0

Object Pending Finalization Count: 0
                 committed |  init   |  used   |  max
    Heap Memory:  92.0MB   | 128.0MB | 59.01MB | 2.0GB
Non-Heap Memory: 115.68MB  | 7.31MB  | 99.55MB |  -1
```

### 系统日志

```text
2023-09-07 23:07:48 E/Bot.**: Exception on parsing packet.
java.lang.IllegalStateException: Exception in net.mamoe.mirai.internal.network.notice.group.GroupMessageProcessor@69ab73b7 while processing packet PbPushMsg.
        at net.mamoe.mirai.internal.network.components.NoticeProcessorPipelineImpl.handleExceptionInProcess(NoticeProcessorPipeline.kt:105)
        at net.mamoe.mirai.internal.network.components.NoticeProcessorPipelineImpl.handleExceptionInProcess(NoticeProcessorPipeline.kt:80)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:289)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:275)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.OnlinePushPbPushGroupMsg.decode(OnlinePush.PbPushGroupMsg.kt:37)
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:586)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:158)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:103)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:127)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:127)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1623)
Caused by: java.lang.IllegalStateException: Cannot find group **.
        at net.mamoe.mirai.internal.message.data.OnlineShortVideoMsgInternal.refine(shortVideo.kt:47)
        at net.mamoe.mirai.internal.message.DeepMessageRefiner.refineDeep(RefinableMessage.kt:234)
        at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline(ReceiveMessageHandler.kt:56)
        at net.mamoe.mirai.internal.message.ReceiveMessageHandlerKt.toMessageChainOnline$default(ReceiveMessageHandler.kt:49)
        at net.mamoe.mirai.internal.network.notice.group.GroupMessageProcessor.processImpl(GroupMessageProcessor.kt:190)
        at net.mamoe.mirai.internal.network.notice.group.GroupMessageProcessor.processImpl(GroupMessageProcessor.kt:44)
        at net.mamoe.mirai.internal.network.components.SimpleNoticeProcessor.process(NoticeProcessorPipeline.kt:147)
        at net.mamoe.mirai.internal.network.components.SimpleNoticeProcessor.process(NoticeProcessorPipeline.kt:141)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:287)
        ... 28 more
```

### 补充信息

日志中第二个 `**` 是发送者的 QQ 号，而不是群号。报错前后共收到过另外 7 条短视频消息，均正常处理。

* 签名服务：<https://hub.docker.com/layers/kiliokuara/vivo50/70107d8e1b4acb747026c95a853523b575e7d98f/images/sha256-267be8976ff383fa75bc16cb47922de4d1b9cbc9df0d20f185ec11ce916317a3>。
* 协议版本：8.9.58.11170。

**Comment by StageGuard** [comment]
这条消息的上下文是群聊，私聊还是群临时会话？

https://github.com/mamoe/mirai/blob/82483f0f13c0d3679704d0bbc32a1f3735162148/mirai-core/src/commonMain/kotlin/message/data/shortVideo.kt#L47

这段代码功能是没问题的，log 输出有 bug，所以如果消息上下文是群，需要你确认这个群是否存在

**Comment by 0f-0b** [comment]
上下文是机器人所在的群之一，另外 7 条正常处理的消息在其他群。

用 3937bca234f6f9d30a820ff5b2da97578f6d4fc1 复现，日志里 `Cannot find group` 后随的值恰好比实际群号大 3890000000。

**Comment by StageGuard** [comment]
> 上下文是机器人所在的群之一，另外 7 条正常处理的消息在其他群。
> 
> 用 [3937bca](https://github.com/mamoe/mirai/commit/3937bca234f6f9d30a820ff5b2da97578f6d4fc1) 复现，日志里 `Cannot find group` 后随的值恰好比实际群号大 3890000000。

那可能是 groupUin 和 groupCode 不一样，试一下这个分支 https://github.com/mamoe/mirai/tree/short-video-refine-group-id

**Comment by 0f-0b** [comment]
> 试一下这个分支 <https://github.com/mamoe/mirai/tree/short-video-refine-group-id>

不报错了。
