### ISSUE TITLE
登录qq的连接没办法走代理

### ISSUE THREAD

**Issue by hanbao233xD** [mamoe/mirai#2795]
### 问题描述

尝试了通过Proxifier和修改运行参数设置代理，Proxifier代理报错（见日志），Clash使用tunmode提示unknown host（这个应该是服务器系统问题），在Mirai论坛搜索到了设置参数的方法，结果除了qq的包都走了代理（
![image](https://github.com/mamoe/mirai/assets/39661586/53ac1483-af5d-4681-bf93-ba6b2aef1fb8)

### 复现

![image](https://github.com/mamoe/mirai/assets/39661586/ab507f18-2b5e-4132-b18e-bcbde61624d0)

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PAD

### 系统日志

```text
2023-09-09 19:14:09 E/console: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:14)
	at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: java.lang.IllegalStateException: NetworkHandler is already closed.
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateClosed.sendPacketImpl(CommonNetworkHandler.kt:396)
		at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler.sendPacketImpl(CommonNetworkHandler.kt:37)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.sendAndExpect(NetworkHandlerSupport.kt:123)
		at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.sendAndExpect(NetworkHandlerSupport.kt:149)
		at net.mamoe.mirai.internal.network.handler.NetworkHandler.sendAndExpect$default(NetworkHandler.kt:194)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$LoginStrategy.sendAndExpect(SsoProcessor.kt:367)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:423)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.doSlowLogin$suspendImpl(SsoProcessor.kt:175)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.doSlowLogin(SsoProcessor.kt)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:273)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:14)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:58)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:14)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:58)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:14)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:58)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$resumeRootWith(SuspendFunctionGun.kt:14)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:58)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:141)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:126)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:101)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpSend$DefaultSender.execute(HttpSend.kt:138)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpRedirect$Plugin$install$1.invokeSuspend(HttpRedirect.kt:61)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpRedirect$Plugin$install$1.invoke(HttpRedirect.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpRedirect$Plugin$install$1.invoke(HttpRedirect.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpSend$InterceptedSender.execute(HttpSend.kt:116)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:147)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpSend$InterceptedSender.execute(HttpSend.kt:116)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpSend$Plugin$install$1.invokeSuspend(HttpSend.kt:104)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpSend$Plugin$install$1.invoke(HttpSend.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpSend$Plugin$install$1.invoke(HttpSend.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:91)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.DefaultTransformKt$defaultTransformers$1.invokeSuspend(DefaultTransform.kt:53)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.DefaultTransformKt$defaultTransformers$1.invoke(DefaultTransform.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.DefaultTransformKt$defaultTransformers$1.invoke(DefaultTransform.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.proceedWith(SuspendFunctionGun.kt:91)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invokeSuspend(HttpCallValidator.kt:126)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(HttpCallValidator.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpCallValidator$Companion$install$1.invoke(HttpCallValidator.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invokeSuspend(HttpRequestLifecycle.kt:35)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(HttpRequestLifecycle.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.client.plugins.HttpRequestLifecycle$Plugin$install$1.invoke(HttpRequestLifecycle.kt)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:123)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:81)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:101)
		at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
		at net.mamoe.mirai.internal.deps.io.ktor.client.HttpClient.execute$ktor_client_core(HttpClient.kt:187)
		at net.mamoe.mirai.internal.deps.io.ktor.client.statement.HttpStatement.executeUnsafe(HttpStatement.kt:107)
		at net.mamoe.mirai.internal.deps.io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:46)
		at net.mamoe.mirai.internal.deps.io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:61)
		at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl$refreshInitialPublicKeyAndApplyEcdh$initialPublicKey$1$respStr$1.invokeSuspend(EcdhInitialPublicKeyUpdater.kt:144)
		at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl$refreshInitialPublicKeyAndApplyEcdh$initialPublicKey$1$respStr$1.invoke(EcdhInitialPublicKeyUpdater.kt)
		at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl$refreshInitialPublicKeyAndApplyEcdh$initialPublicKey$1$respStr$1.invoke(EcdhInitialPublicKeyUpdater.kt)
		at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:100)
		at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:146)
		at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:44)
		at kotlinx.coroutines.TimeoutKt.withTimeout-KLykuaI(Timeout.kt:71)
		at net.mamoe.mirai.internal.network.components.EcdhInitialPublicKeyUpdaterImpl.refreshInitialPublicKeyAndApplyEcdh(EcdhInitialPublicKeyUpdater.kt:94)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:258)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		... 25 more
Caused by: [CIRCULAR REFERENCE: java.lang.IllegalStateException: NetworkHandler is already closed.]
```

**Comment by hanbao233xD** [comment]
qq显示的位置是服务器ip所在位置
![3320de0c15a9b47c3c8bd16fa1d32df9](https://github.com/mamoe/mirai/assets/39661586/c81a98d4-05b6-46ad-9874-85fd6a38f10c)

**Comment by diyigemt** [comment]
mcl启动参数加上
```bash
-p host:port
```
试试?
![image](https://github.com/mamoe/mirai/assets/41864956/dede6a6a-a0a1-4a03-8ed0-a1ba1ca52dc3)

**Comment by cssxsh** [comment]
网络相关的问题为什么不提交网络日志
