### ISSUE TITLE
为什么会要求更新qsign？？

### ISSUE THREAD

**Issue by 3336148332** [mamoe/mirai#2799]
### 问题描述

刚刚配置好qsign本地服务，但是就在配置mirai的时候出现了，“2023-09-17 01:06:28 E/KFCFactory: 请更新 unidbg-fetch-qsign”字样，请过多反调试依旧如此。请帮帮忙。

### 复现

不管有手机还pad登录都会出现这种问题

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

fix-protocol-version-1.11.0.mirai2.jar
mcl-addon-2.1.1.jar
mirai-api-http-2.9.1.mirai2.jar

### 系统日志

```text
2023-09-17 01:21:31 W/EncryptService.alert: Encrypt service was loaded: KFCFactory(config=file:///E:/1/KFCFactory.json)
2023-09-17 01:21:31 W/EncryptService.alert: All outgoing message may be leaked by this service.
2023-09-17 01:21:31 W/EncryptService.alert: Use this service if and only if you trusted this service and the service provider.
2023-09-17 01:21:31 W/EncryptService.alert: Service details:
2023-09-17 01:21:31 W/EncryptService.alert:   `- Jvm Class: class xyz.cssxsh.mirai.tool.KFCFactory
2023-09-17 01:21:31 W/EncryptService.alert:   `- ClassLoader: JvmPluginClassLoader{fix-protocol-version-1.11.0.mirai2.jar}
2023-09-17 01:21:31 W/EncryptService.alert:   `- Source: file:/E:/1/plugins/fix-protocol-version-1.11.0.mirai2.jar
2023-09-17 01:21:31 W/EncryptService.alert:   `- Protected Domain: ProtectionDomain  (file:/E:/1/plugins/fix-protocol-version-1.11.0.mirai2.jar <no signer certificates>)
 JvmPluginClassLoader{fix-protocol-version-1.11.0.mirai2.jar}
 <no principals>
 java.security.Permissions@41bff53e (
 ("java.io.FilePermission" "E:\1\plugins\fix-protocol-version-1.11.0.mirai2.jar" "read")
)


2023-09-17 01:21:31 I/KFCFactory: ANDROID_PHONE(8.9.63) EncryptService by fuqiuluo/unidbg-fetch-qsign from file:///E:/1/KFCFactory.json
2023-09-17 01:21:31 W/Bot.3336148332: KFCFactory(config=file:///E:/1/KFCFactory.json) is not yet supported EncryptService with bot Bot(3336148332)
java.lang.UnsupportedOperationException: repeated create EncryptService
        at fix-protocol-version-1.11.0.mirai2.jar//xyz.cssxsh.mirai.tool.KFCFactory.createForBot(KFCFactory.kt:81)
        at net.mamoe.mirai.internal.network.components.EncryptServiceHolderImpl.<init>(EncryptServiceHolder.kt:49)
        at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:288)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:192)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:191)
        at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)
        at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:191)
        at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:300)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:312)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:305)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:277)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:249)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:51)
        at net.mamoe.mirai.internal.QQAndroidBot.getComponents(QQAndroidBot.kt:189)
        at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:154)
        at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.doLogin$suspendImpl(LoginCommandImpl.kt:40)
        at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.doLogin$mirai_console(LoginCommandImpl.kt)
        at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.handle(LoginCommandImpl.kt:99)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:202)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle$default(BuiltInCommands.kt:196)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:339)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:84)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:187)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2023-09-17 01:21:31 I/Bot.3336148332: Bot cancelled: Bot closed
Login failed: 请检查 unidbg-fetch-qsign by http://127.0.0.1:11390 的可用性
2023-09-17 01:21:31 E/console: java.lang.RuntimeException: 请检查 unidbg-fetch-qsign by http://127.0.0.1:11390 的可用性
java.lang.RuntimeException: 请检查 unidbg-fetch-qsign by http://127.0.0.1:11390 的可用性
        at fix-protocol-version-1.11.0.mirai2.jar//xyz.cssxsh.mirai.tool.KFCFactory.createForBot(KFCFactory.kt:128)
        at net.mamoe.mirai.internal.network.components.EncryptServiceHolderImpl.<init>(EncryptServiceHolder.kt:49)
        at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:288)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:192)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:191)
        at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)
        at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:191)
        at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:300)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:312)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:305)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:277)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:249)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:51)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:54)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler$scope$2.invoke(SelectorNetworkHandler.kt:53)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getScope(SelectorNetworkHandler.kt:53)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.access$getScope(SelectorNetworkHandler.kt:45)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.resumeConnection$suspendImpl(SelectorNetworkHandler.kt:130)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.resumeConnection(SelectorNetworkHandler.kt)
        at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:145)
        at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.doLogin$suspendImpl(LoginCommandImpl.kt:40)
        at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.doLogin$mirai_console(LoginCommandImpl.kt)
        at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.handle(LoginCommandImpl.kt:99)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:202)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle$default(BuiltInCommands.kt:196)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:339)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:84)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:187)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.base/sun.nio.ch.Net.connect0(Native Method)
        at java.base/sun.nio.ch.Net.connect(Net.java:580)
        at java.base/sun.nio.ch.Net.connect(Net.java:569)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:576)
        at java.base/java.net.Socket.connect(Socket.java:666)
        at java.base/java.net.Socket.connect(Socket.java:600)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:385)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:407)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1308)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1241)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1127)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1056)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1657)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1581)
        at java.base/java.net.URL.openStream(URL.java:1317)
        at kotlin.io.TextStreamsKt.readBytes(ReadWrite.kt:149)
        at fix-protocol-version-1.11.0.mirai2.jar//xyz.cssxsh.mirai.tool.KFCFactory.createForBot(KFCFactory.kt:112)
        ... 48 more
```

### 补充信息

为本地签名服务日志
[2023-09-17 01:20:35] [INFO]: 当前版本:v1.1.0
[2023-09-17 01:20:35] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2023-09-17 01:20:35] [INFO]: 使用服务器 http://127.0.0.1:13579 进行数据包签名
[2023-09-17 01:20:35] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2023-09-17 01:20:40] [INFO]: 开始尝试登录并同步消息...
[2023-09-17 01:20:40] [INFO]: 使用协议: Android Pad 8.9.63.11390
[2023-09-17 01:20:45] [INFO]: Protocol -> connect to server: 111.30.187.245:8080
[2023-09-17 01:20:46] [WARNING]: Protocol -> device lock is disable. http api may fail.
[2023-09-17 01:20:48] [INFO]: 正在检查协议更新...
[2023-09-17 01:20:49] [INFO]: 收到服务器地址更新通知, 将在下一次重连时应用.
[2023-09-17 01:20:54] [INFO]: 登录成功 欢迎使用: 潇博然
[2023-09-17 01:20:54] [INFO]: 开始加载好友列表...
[2023-09-17 01:20:54] [INFO]: 共加载 4 个好友.
[2023-09-17 01:20:54] [INFO]: 开始加载群列表...
[2023-09-17 01:20:56] [INFO]: 共加载 4 个群.
[2023-09-17 01:20:56] [INFO]: 资源初始化完成, 开始处理信息.
[2023-09-17 01:20:56] [INFO]: アトリは、高性能ですから!
[2023-09-17 01:20:56] [INFO]: 正在检查更新.
[2023-09-17 01:20:56] [INFO]: CQ WebSocket 服务器已启动: [::]:24680
[2023-09-17 01:20:56] [WARNING]: 检查更新失败！
[2023-09-17 01:20:56] [INFO]: 检查更新完成. 当前已运行最新版本.
[2023-09-17 01:20:56] [INFO]: 开始诊断网络情况
[2023-09-17 01:20:59] [INFO]: 网络诊断完成. 未发现问题

**Comment by cssxsh** [comment]
> Login failed: 请检查 unidbg-fetch-qsign by http://127.0.0.1:11390 的可用性

> [2023-09-17 01:20:35] [INFO]: 使用服务器 http://127.0.0.1:13579/ 进行数据包签名

请确认地址配置无误
