### ISSUE TITLE
图片发送异常

### ISSUE THREAD

**Issue by ryoii** [mamoe/mirai#28]
版本：0.8.2

主动发送图片时出现异常
```
sender.uploadImage(File("pic.jpg"));
sender.sendImage(URL(url));
```
均出现异常`java.io.EOFException: One more byte required but reached end of input`

**Comment by Him188** [comment]
请问能否提供完整的 stacktrace?

**Comment by ryoii** [comment]
```
java.io.EOFException: One more byte required but reached end of input
	at kotlinx.io.core.ByteReadPacketBase.readByteSlow(Packet.kt:186)
	at kotlinx.io.core.ByteReadPacketBase.readByteSlow2(Packet.kt:181)
	at kotlinx.io.core.ByteReadPacketBase.readByte(Packet.kt:170)
	at net.mamoe.mirai.network.protocol.tim.packet.action.FriendImagePacket.decode-MgswzbQ(FriendImage.kt:460)
	at net.mamoe.mirai.network.protocol.tim.TIMBotNetworkHandler$BotSocketAdapter$processReceive$2.invokeSuspend(TIMBotNetworkHandler.kt:174)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by Him188** [comment]
TIMPC 协议将不再受支持，Android 协议会解决这个问题。
