### ISSUE TITLE
无法加载插件 mirai-api-http

### ISSUE THREAD

**Issue by gebederry** [mamoe/mirai#2801]
### 问题描述

佬，mirai-console 加载插件 `mirai-api-http` 时报错

### 复现

启动 mirai-console 时

### mirai-core 版本

`2.16.0-RC`

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-api-http: `2.9.1`

### 系统日志

```text
mirai-console 的日志

2023-09-19 10:55:25 I/main: Backend: version 2.16.0-RC, built on 2023-09-03 23:55:17.
2023-09-19 10:55:25 I/main: Frontend Terminal: version 2.16.0-RC, provided by Mamoe Technologies
2023-09-19 10:55:25 I/main: Welcome to visit https://mirai.mamoe.net/
2023-09-19 10:55:29 I/plugin: Successfully loaded plugin mirai-administrator v1.4.3
2023-09-19 10:55:45 I/plugin: Successfully loaded plugin mirai-login-solver-sakura v0.0.12
2023-09-19 10:55:45 I/plugin: Successfully loaded plugin Keyword Remind v1.1.0
2023-09-19 10:55:45 I/plugin: Successfully loaded plugin mirai-device-generator v1.3.0
2023-09-19 10:55:45 I/plugin: Successfully loaded plugin Chat Command v0.6.0
2023-09-19 10:55:45 I/plugin: Cannot load plugin mirai-api-http v2.9.1
2023-09-19 10:55:45 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while loading mirai-api-http v2.9.1
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:373)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:40)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:54)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:100)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:164)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:303)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:196)
	at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.lang.IllegalStateException: A JvmPlugin loaded by plugin.yml must has same description reference
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:362)
	... 23 more
```
```


### 网络日志

_No response_

### 补充信息

Java 版本: `OpenJDK 17`

**Comment by gebederry** [comment]
似乎是 2.16.0-RC 新增的严格检测 mah 插件描述不规范一致的问题..😵

**Comment by 0f-0b** [comment]
323f6b363cdf5d6f69977d82ab0f2fb8ef4fe23a 已经修了。
