### ISSUE TITLE
启动mcl出现Writer not setup

### ISSUE THREAD

**Issue by pilgrim773** [mamoe/mirai#2820]
### 问题描述

昨天就出现了，启动时每输出一行正常日志，就报Writer not setup。昨天也是瞎弄的，好像是有的Screen会话没关全，mirai进程冲突了导致的，但是今天我已经确认了没有重复的mirai启动了，还是这样子：

```
java.lang.IllegalStateException: Writer not setup
        at net.mamoe.mirai.console.frontendbase.logging.DailySplitLogRecorder.record(LogRecorder.kt:147)
        at net.mamoe.mirai.console.frontendbase.logging.AsyncLogRecorderForwarded.asyncRecord(LogRecorder.kt:85)
        at net.mamoe.mirai.console.frontendbase.logging.AsyncLogRecorder$2.invokeSuspend(LogRecorder.kt:61)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2023-11-16 20:57:31 I/ba-activity-pusher: Source: STUDENT from GitHub already up to date.
java.lang.IllegalStateException: Writer not setup
        at net.mamoe.mirai.console.frontendbase.logging.DailySplitLogRecorder.record(LogRecorder.kt:147)
        at net.mamoe.mirai.console.frontendbase.logging.AsyncLogRecorderForwarded.asyncRecord(LogRecorder.kt:85)
        at net.mamoe.mirai.console.frontendbase.logging.AsyncLogRecorder$2.invokeSuspend(LogRecorder.kt:61)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2023-11-16 20:57:32 I/ba-activity-pusher: Source: LOCALIZATION from GitHub already up to date.
java.lang.IllegalStateException: Writer not setup
        at net.mamoe.mirai.console.frontendbase.logging.DailySplitLogRecorder.record(LogRecorder.kt:147)
        at net.mamoe.mirai.console.frontendbase.logging.AsyncLogRecorderForwarded.asyncRecord(LogRecorder.kt:85)
        at net.mamoe.mirai.console.frontendbase.logging.AsyncLogRecorder$2.invokeSuspend(LogRecorder.kt:61)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2023-11-16 20:57:34 W/ba-activity-pusher: 获取数据源: RAID 失败，请检查网络连接
java.lang.IllegalStateException: Writer not setup
        at net.mamoe.mirai.console.frontendbase.logging.DailySplitLogRecorder.record(LogRecorder.kt:147)
        at net.mamoe.mirai.console.frontendbase.logging.AsyncLogRecorderForwarded.asyncRecord(LogRecorder.kt:85)
        at net.mamoe.mirai.console.frontendbase.logging.AsyncLogRecorder$2.invokeSuspend(LogRecorder.kt:61)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
2023-11-16 20:57:36 W/ba-activity-pusher: 获取数据源: COMMON 失败，请检查网络连接
java.lang.IllegalStateException: Writer not setup
        at net.mamoe.mirai.console.frontendbase.logging.DailySplitLogRecorder.record(LogRecorder.kt:147)
        at net.mamoe.mirai.console.frontendbase.logging.AsyncLogRecorderForwarded.asyncRecord(LogRecorder.kt:85)
        at net.mamoe.mirai.console.frontendbase.logging.AsyncLogRecorder$2.invokeSuspend(LogRecorder.kt:61)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

进程检查：
```
[myaccount@VM-24-7-centos mirai]$ ps -ef|grep mcl
lightho+  934945  932754  0 21:02 pts/3    00:00:00 grep --color=auto mcl
[myaccount@VM-24-7-centos mirai]$ ps -ef|grep mirai
root      932615  932422  0 20:57 pts/2    00:00:02 /home/myaccount/mirai/java/bin/java -classpath /home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/unidbg-fetch-qsign-1.1.9.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/unidbg-android-105.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-server-content-negotiation-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-serialization-kotlinx-json-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-server-status-pages-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-server-netty-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-server-host-common-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-server-core-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-serialization-kotlinx-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-serialization-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-events-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-websockets-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-http-cio-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-http-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-network-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-utils-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/ktor-io-jvm-2.3.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/kotlin-stdlib-jdk8-1.8.22.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/kotlinx-serialization-json-jvm-1.5.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/kotlinx-serialization-protobuf-jvm-1.5.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/kotlinx-serialization-core-jvm-1.5.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/logback-classic-1.2.11.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/kotlinx-coroutines-jdk8-1.7.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/kotlinx-coroutines-core-jvm-1.7.1.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/kotlin-stdlib-jdk7-1.8.22.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/kotlin-reflect-1.8.10.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/kotlin-stdlib-1.8.22.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/slf4j-api-1.7.36.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/kotlin-stdlib-common-1.8.22.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/config-1.4.2.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/jansi-2.4.0.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-codec-http2-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/alpn-api-1.1.3.v20160715.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-transport-native-kqueue-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-transport-native-epoll-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/logback-core-1.2.11.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/annotations-23.0.0.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-codec-http-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-handler-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-codec-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-transport-classes-kqueue-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-transport-classes-epoll-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-transport-native-unix-common-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-transport-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-buffer-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-resolver-4.1.92.Final.jar:/home/myaccount/Qsign-1.1.9b4/unidbg-fetch-qsign/lib/netty-common-4.1.92.Final.jar MainKt --basePath=txlib/8.9.80
lightho+  935014  932754  0 21:02 pts/3    00:00:00 grep --color=auto mirai
```

那个mirai其实是签名服务进程，用了mirai下面里的java

### 复现

如描述

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PAD

**Comment by pilgrim773** [comment]
已自行解决 与本项目无关
