### ISSUE TITLE
在试图连接机器人时出现以下报错

### ISSUE THREAD

**Issue by levi0111** [mamoe/mirai#2845]
### 问题描述

在试图将mirai连接到机器人时出现报错：
Bot is closed manually with exception: java.lang.IllegalStateException: Timeout waiting for ConfigPush.

### 复现

测试了两个机器人分别是greenonions 和 theresa3rd 时都会产生该报错，试图更换网络环境（如使用手机热点）也仍然出现。

### mirai-core 版本

2.16.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

使用其它组件列表：
mcl-addon-2.1.1
mirai-api-http-2.10.0
mirai-login-solver-sakura-0.0.12
qsign-1.2.1-beta-dev-d62ddce

### 系统日志

```text
2024-03-23 15:57:15 I/Bot.3675102813: Login successful.
2024-03-23 15:57:20 V/Bot.3675102813: Event: BotOnlineEvent(bot=Bot(3675102813))
2024-03-23 15:57:20 I/Bot.3675102813: Bot login successful.
2024-03-23 15:57:53 I/stdout: Find native function Java_com_tencent_mobileqq_sign_QQSecuritySign_getSign => RX@0x4008fa24[libfekit.so]0x8fa24
2024-03-23 15:57:53 I/stdout: JNIEnv->NewObjectV(class com/tencent/mobileqq/sign/QQSecuritySign$SignResult, <init>() => com.tencent.mobileqq.sign.QQSecuritySign$SignResult@683da347) was called from RX@0x400b596c[libfekit.so]0xb596c
2024-03-23 15:57:53 I/stdout: JNIEnv->GetStringUtfChars("3675102813") was called from RX@0x40097c4c[libfekit.so]0x97c4c
2024-03-23 15:57:53 I/stdout: JNIEnv->NewStringUTF("Q7QVkXbtuaF1") was called from RX@0x400a03f8[libfekit.so]0xa03f8
2024-03-23 15:57:53 I/stdout: JNIEnv->CallVoidMethodV(com.tencent.mobileqq.qsec.qsecurity.QSec@2569e384, updateO3DID("Q7QVkXbtuaF1")) was called from RX@0x400b5a08[libfekit.so]0xb5a08
2024-03-23 15:57:53 I/stdout: JNIEnv->NewByteArray(12) was called from RX@0x4008ffa4[libfekit.so]0x8ffa4
2024-03-23 15:57:53 I/stdout: JNIEnv->SetByteArrayRegion([B@7f5b1a22, 0, 12, unidbg@0xbffff231) was called from RX@0x400911f4[libfekit.so]0x911f4
2024-03-23 15:57:53 I/stdout: JNIEnv->SetObjectField(com.tencent.mobileqq.sign.QQSecuritySign$SignResult@683da347, token [B => [B@7f5b1a22) was called from RX@0x40091218[libfekit.so]0x91218
2024-03-23 15:57:53 I/stdout: JNIEnv->GetArrayLength([B@7af9a915 => 341) was called from RX@0x400a07ec[libfekit.so]0xa07ec
2024-03-23 15:57:53 I/stdout: JNIEnv->GetStringUtfChars("8.9.85") was called from RX@0x400a70f8[libfekit.so]0xa70f8
2024-03-23 15:57:53 I/stdout: JNIEnv->GetStringUtfChars("MessageSvc.PbSendMsg") was called from RX@0x400a7200[libfekit.so]0xa7200
2024-03-23 15:57:53 I/stdout: JNIEnv->NewStringUTF("[FEKit_]") was called from RX@0x40395ed0[libfekit.so]0x395ed0
2024-03-23 15:57:53 I/stdout: JNIEnv->NewStringUTF("qq_sign.h:156 [GetSign] cmd:MessageSvc.PbSendMsg") was called from RX@0x40395ed0[libfekit.so]0x395ed0
2024-03-23 15:57:53 I/stdout: Accept  com/tencent/mobileqq/fe/IFEKitLog->i(Ljava/lang/String;ILjava/lang/String;)V
2024-03-23 15:57:53 I/stdout: JNIEnv->GetMethodID(com/tencent/mobileqq/fe/IFEKitLog.i(Ljava/lang/String;ILjava/lang/String;)V) => 0xd8f7802f was called from RX@0x40394e7c[libfekit.so]0x394e7c
2024-03-23 15:57:53 I/stdout: JNIEnv->CallVoidMethodV(com.tencent.mobileqq.fe.IFEKitLog@63f83c4a, i("[FEKit_]", 0x1, "qq_sign.h:156 [GetSign] cmd:MessageSvc.PbSendMsg")) was called from RX@0x40205008[libfekit.so]0x205008
2024-03-23 15:57:53 I/stdout: JNIEnv->NewByteArray(155) was called from RX@0x400a0494[libfekit.so]0xa0494
2024-03-23 15:57:53 I/stdout: JNIEnv->SetByteArrayRegion([B@57650818, 0, 155, RW@0x40ce43c0) was called from RX@0x400a0f00[libfekit.so]0xa0f00
2024-03-23 15:57:53 I/stdout: JNIEnv->SetObjectField(com.tencent.mobileqq.sign.QQSecuritySign$SignResult@683da347, extra [B => [B@57650818) was called from RX@0x400a0f24[libfekit.so]0xa0f24
2024-03-23 15:57:53 I/stdout: JNIEnv->NewByteArray(16) was called from RX@0x4009021c[libfekit.so]0x9021c
2024-03-23 15:57:53 I/stdout: JNIEnv->SetByteArrayRegion([B@7083bbbc, 0, 16, unidbg@0xbffff151) was called from RX@0x40090260[libfekit.so]0x90260
2024-03-23 15:57:53 I/stdout: JNIEnv->GetArrayLength([B@7083bbbc => 16) was called from RX@0x403966c4[libfekit.so]0x3966c4
2024-03-23 15:57:53 I/stdout: JNIEnv->GetByteArrayRegion([B@7083bbbc, 0, 16, RW@0x40ce3040) was called from RX@0x40105290[libfekit.so]0x105290
2024-03-23 15:57:53 I/stdout: JNIEnv->GetStringUtfChars("MessageSvc.PbSendMsg") was called from RX@0x40396290[libfekit.so]0x396290
2024-03-23 15:57:53 I/stdout: JNIEnv->GetStringUTFLength("MessageSvc.PbSendMsg") was called from RX@0x40396034[libfekit.so]0x396034
2024-03-23 15:57:53 I/stdout: JNIEnv->NewStringUTF("[FEKit_]") was called from RX@0x40395ed0[libfekit.so]0x395ed0
2024-03-23 15:57:53 I/stdout: JNIEnv->NewStringUTF("sign_tail_manager.h:147 tryRequestTail") was called from RX@0x40395ed0[libfekit.so]0x395ed0
2024-03-23 15:57:53 I/stdout: Accept  com/tencent/mobileqq/fe/IFEKitLog->e(Ljava/lang/String;ILjava/lang/String;)V
2024-03-23 15:57:53 I/stdout: JNIEnv->GetMethodID(com/tencent/mobileqq/fe/IFEKitLog.e(Ljava/lang/String;ILjava/lang/String;)V) => 0xa676d42b was called from RX@0x40394e7c[libfekit.so]0x394e7c
2024-03-23 15:57:53 I/stdout: JNIEnv->CallVoidMethodV(com.tencent.mobileqq.fe.IFEKitLog@63f83c4a, e("[FEKit_]", 0x1, "sign_tail_manager.h:147 tryRequestTail")) was called from RX@0x40205008[libfekit.so]0x205008
2024-03-23 15:57:53 I/stdout: JNIEnv->NewStringUTF("[FEKit_]") was called from RX@0x40395ed0[libfekit.so]0x395ed0
2024-03-23 15:57:53 I/stdout: JNIEnv->NewStringUTF("sign_tail_manager.h:154 channel not ready") was called from RX@0x40395ed0[libfekit.so]0x395ed0
2024-03-23 15:57:53 I/stdout: Accept  com/tencent/mobileqq/fe/IFEKitLog->e(Ljava/lang/String;ILjava/lang/String;)V
2024-03-23 15:57:53 I/stdout: JNIEnv->GetMethodID(com/tencent/mobileqq/fe/IFEKitLog.e(Ljava/lang/String;ILjava/lang/String;)V) => 0xa676d42b was called from RX@0x40394e7c[libfekit.so]0x394e7c
2024-03-23 15:57:53 I/stdout: JNIEnv->CallVoidMethodV(com.tencent.mobileqq.fe.IFEKitLog@63f83c4a, e("[FEKit_]", 0x1, "sign_tail_manager.h:154 channel not ready")) was called from RX@0x40205008[libfekit.so]0x205008
2024-03-23 15:57:53 I/stdout: JNIEnv->NewByteArray(64) was called from RX@0x40104cfc[libfekit.so]0x104cfc
2024-03-23 15:57:53 I/stdout: JNIEnv->SetByteArrayRegion([B@188b41de, 0, 64, RW@0x40cde5a0) was called from RX@0x40104f2c[libfekit.so]0x104f2c
2024-03-23 15:57:53 I/stdout: JNIEnv->ReleaseStringUTFChars("MessageSvc.PbSendMsg") was called from RX@0x40396484[libfekit.so]0x396484
2024-03-23 15:57:53 I/stdout: JNIEnv->SetObjectField(com.tencent.mobileqq.sign.QQSecuritySign$SignResult@683da347, sign [B => [B@188b41de) was called from RX@0x400a0e9c[libfekit.so]0xa0e9c
2024-03-23 15:57:53 I/stdout: JNIEnv->ReleaseStringUTFChars("8.9.85") was called from RX@0x400912d0[libfekit.so]0x912d0
2024-03-23 15:57:53 I/stdout: JNIEnv->ReleaseStringUTFChars("MessageSvc.PbSendMsg") was called from RX@0x4009133c[libfekit.so]0x9133c
2024-03-23 15:57:53 I/stdout: JNIEnv->ReleaseStringUTFChars("3675102813") was called from RX@0x4008fe70[libfekit.so]0x8fe70
2024-03-23 15:57:54 V/Bot.3675102813: Friend(3240006062) <- 欢迎使用【Theresa3rd-Bot v0.11.3】
群聊发送【#菜单】可以查看所有指令
局域网下访问下列地址进行Bot相关配置
http://127.0.0.1:8088
http://169.254.133.91:8088
部署或者使用教程请访问
https://www.theresa3rd.cn
2024-03-23 15:58:07 V/Bot.3675102813: Event: GroupRecall(bot=Bot(3675102813), authorId=3312366162, messageIds=[46597], messageInternalIds=[826196150], messageTime=1711205833, operator=NormalMember(3312366162), group=Group(748932382), author=NormalMember(3312366162))
2024-03-23 15:58:20 V/Bot.3675102813: Event: BotOfflineEvent.RequireReconnect(bot=Bot(3675102813), cause=java.lang.IllegalStateException: Timeout waiting for ConfigPush., reconnect=true)
2024-03-23 15:58:20 I/QSignService: destroy 3675102813
2024-03-23 15:58:20 W/Bot.3675102813: Connection lost, reconnecting... (java.lang.IllegalStateException: Timeout waiting for ConfigPush.)
2024-03-23 15:58:20 V/Bot.3675102813: Event: BotOfflineEvent.Active(bot=Bot(3675102813), cause=java.lang.IllegalStateException: Timeout waiting for ConfigPush., reconnect=false)
2024-03-23 15:58:20 I/QSignService: destroy 3675102813
2024-03-23 15:58:20 I/Bot.3675102813: Bot is closed manually with exception: java.lang.IllegalStateException: Timeout waiting for ConfigPush.
java.lang.IllegalStateException: Timeout waiting for ConfigPush.
	at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl.syncConfigPush(ConfigPushProcessor.kt:45)
	at net.mamoe.mirai.internal.network.components.ConfigPushProcessorImpl$syncConfigPush$1.invokeSuspend(ConfigPushProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by zhaodice** [comment]
修过了，但无release，建议自己编译

**Comment by levi0111** [comment]
> 修过了，但无release，建议自己编译

谢谢，解决了
