### ISSUE TITLE
java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=108, errorCode=0, errorMessage=)

### ISSUE THREAD

**Issue by MrY-Cat** [mamoe/mirai#2854]
### 问题描述

不知道触发原因是什么，触发之后就变成只能收消息不能发消息了，重启mcl后正常

### 复现

未知触发方式

### mirai-core 版本

2.15.0

### bot-protocol

ANDROID_PAD

### 系统日志

```text
2024-07-01 08:47:37 V/Bot.2305339556: [复读喵星球官方群(1027488229)] 小小沐(2624593044) -> 购买神圣五色晶球
2024-07-01 08:47:37 E/复读喵星球: Exception in coroutine Plugin yyd.mrycat.bot.mirai-cat of 复读喵星球
java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=108, errorCode=0, errorMessage=)
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:173)
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.access$sendSinglePacket(GeneralMessageSenderProtocol.kt:52)
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender$sendSinglePacket$1.invokeSuspend(GeneralMessageSenderProtocol.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

### 网络日志

```text
[0m2024-07-01 08:47:37 V/: Send: MessageSvc.PbSendMsg(MessageSvc.PbSendMsg)[0m
[0m2024-07-01 08:47:37 V/: Recv: MessageSvc.PbSendMsg[0m
[0m2024-07-01 08:50:58 V/: Send: trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Access(mobileqq.msf.security)[0m
[0m2024-07-01 08:50:58 V/: Recv: trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Access[0m
[0m2024-07-01 09:30:58 V/: Send: trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Access(mobileqq.msf.security)[0m
[0m2024-07-01 09:30:58 V/: Recv: trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Access[0m
[0m2024-07-01 09:46:58 V/: Send: MultiMsg.ApplyDown(MultiMsg.ApplyDown)[0m
[0m2024-07-01 09:46:58 V/: [Http] Downloading forward message from https://ssl.htdata.qq.com:443[0m
[0m2024-07-01 09:46:58 V/: Recv: MultiMsg.ApplyDown[0m
[0m2024-07-01 09:46:59 V/: [Http] Downloading forward message: succeed[0m
[0m2024-07-01 10:00:31 V/: Recv: OnlinePush.PbPushTransMsg[0m
[0m2024-07-01 10:10:59 V/: Send: trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish(mobileqq.msf.security)[0m
```

### 补充信息

采用签名服务登录

**Comment by MrY-Cat** [comment]
今天又发生了，有点更详细的日志：
2024-08-07 10:13:26 E/Bot.2305339556: java.lang.IllegalStateException: Exception while broadcasting event 'GroupMessageEvent'
java.lang.IllegalStateException: Exception while broadcasting event 'GroupMessageEvent'
	at net.mamoe.mirai.internal.network.components.EventDispatcherImpl.broadcast$suspendImpl(EventDispatcher.kt:104)
	at net.mamoe.mirai.internal.network.components.EventDispatcherImpl$broadcast$1.invokeSuspend(EventDispatcher.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:233)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callFunction(JvmMethodListenersInternal.kt:91)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callFunction(JvmMethodListenersInternal.kt:1)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callFunction$1.invokeSuspend(JvmMethodListenersInternal.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	... 8 more
Caused by: java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=108, errorCode=0, errorMessage=)
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.sendSinglePacket(GeneralMessageSenderProtocol.kt:173)
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.access$sendSinglePacket(GeneralMessageSenderProtocol.kt:52)
	at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender$sendSinglePacket$1.invokeSuspend(GeneralMessageSenderProtocol.kt)
	... 9 more
