### ISSUE TITLE
登录失败(需要下载新版QQ)

### ISSUE THREAD

**Issue by SFKgroup** [mamoe/mirai#2859]
### 问题描述

在试图登录我的QQ账号时，发生如下错误，导致无法登录QQ:
程序报错，返回信息为:"登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。"

### 复现

使用/login 或 /autologin 登录QQ
(在protocol == ANDROID_PHONE 或 protocol == ANDROID_PAD)

### mirai-core 版本

2.16.0

### bot-protocol

ANDROID_PHONE

### 其他组件版本

mirai-api-http v2.10.0
Silk Converter v0.0.3

### 系统日志

```text
===================================[ Mirai console 2.16.0 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2024-08-27 15:57:09 I/main: Backend: version 2.16.0, built on 2023-10-20 06:28:10.
2024-08-27 15:57:09 I/main: Frontend Terminal: version 2.16.0, provided by Mamoe Technologies
2024-08-27 15:57:09 I/main: Welcome to visit https://mirai.mamoe.net/
2024-08-27 15:57:10 I/plugin: Successfully loaded plugin mirai-api-http v2.10.0
2024-08-27 15:57:10 E/Silk Converter: java.lang.NoSuchMethodError: 'void net.mamoe.mirai.spi.AudioToSilkService$Companion.setService(net.mamoe.mirai.spi.AudioToSilkService)'
java.lang.NoSuchMethodError: 'void net.mamoe.mirai.spi.AudioToSilkService$Companion.setService(net.mamoe.mirai.spi.AudioToSilkService)'
	at mirai-silk-converter-0.0.5-all.jar//net.mamoe.mirai.silkconverter.MiraiSilkConverterConsolePlugin.onLoad(ConsolePluginMode.kt:49)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:388)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:371)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:40)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:54)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:100)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:164)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:303)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:196)
	at org.itxtech.mcl.Loader.main(Loader.java:84)

2024-08-27 15:57:10 E/Silk Converter: Configuration location: 【blank】\data\net.mamoe.mirai-silk-converter
2024-08-27 15:57:10 I/plugin: Successfully loaded plugin Silk Converter v0.0.3
2024-08-27 15:57:10 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2024-08-27 15:57:10 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2024-08-27 15:57:10 W/mirai-api-http: USING INITIAL KEY, please edit the key
2024-08-27 15:57:10 I/Mirai HTTP API: ********************************************************
2024-08-27 15:57:10 I/MahKtorAdapter[http]: Autoreload is disabled because the development mode is off.
2024-08-27 15:57:10 I/MahKtorAdapter[http]: Application started in 0.157 seconds.
2024-08-27 15:57:10 I/MahKtorAdapter[http]: Responding at http://localhost:8080
2024-08-27 15:57:10 I/http adapter: >>> [http adapter] is listening at http://localhost:8080
2024-08-27 15:57:10 I/Mirai HTTP API: Http api server is running with verifyKey: INITKEYGJMqhQRL
2024-08-27 15:57:10 I/Mirai HTTP API: adaptors: [http]
2024-08-27 15:57:10 I/Mirai HTTP API: ********************************************************
2024-08-27 15:57:10 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2024-08-27 15:57:10 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2024-08-27 15:57:10 I/main: 4 plugin(s) enabled.
2024-08-27 15:57:10 I/main: Auto-login 【blank】, protocol: ANDROID_PHONE, heartbeatStrategy: STAT_HB
2024-08-27 15:57:12 I/Bot.【blank】: Calculating type 2 PoW, it can take some time....
2024-08-27 15:57:12 I/Bot.【blank】: Got PoW result, cost: 66 ms
2024-08-27 15:57:12 I/Bot.【blank】: [SliderCaptcha] 需要滑动验证码, 请按照以下链接的步骤完成滑动验证码, 然后输入获取到的 ticket
2024-08-27 15:57:12 I/Bot.【blank】: [SliderCaptcha] Slider captcha required. Please solve the captcha with following link. Type ticket here after completion.
2024-08-27 15:57:12 I/Bot.【blank】: [SliderCaptcha] @see https://github.com/project-mirai/mirai-login-solver-selenium
2024-08-27 15:57:12 I/Bot.【blank】: [SliderCaptcha] @see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
2024-08-27 15:57:12 I/Bot.【blank】: [SliderCaptcha] 或者输入 helper 来使用 TxCaptchaHelper 完成滑动验证码
2024-08-27 15:57:12 I/Bot.【blank】: [SliderCaptcha] Or type helper to resolve slider captcha with TxCaptchaHelper.apk
2024-08-27 15:57:12 W/Bot.【blank】: [SliderCaptcha] TxCaptchaHelper 的在线服务疑似被屏蔽，可能无法使用。TxCaptchaHelper 现已无法满足登录QQ机器人，请在以下链接下载全新的验证器
2024-08-27 15:57:12 W/Bot.【blank】: [SliderCaptcha] The service of TxCaptchaHelper might be blocked. We recommend you to download the new login solver plugin in below link.
2024-08-27 15:57:12 W/Bot.【blank】: [SliderCaptcha] @see https://github.com/KasukuSakura/mirai-login-solver-sakura
2024-08-27 15:57:12 I/Bot.【blank】: [SliderCaptcha] Captcha link: https://ti.qq.com/safe/tools/captcha/sms-verify-login?【blank】
2024-08-27 15:57:35 I/Bot.【blank】: [SliderCaptcha] 正在提交中...
2024-08-27 15:57:35 I/Bot.【blank】: [SliderCaptcha] Submitting...
2024-08-27 15:57:35 E/main: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(【blank】), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
		at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
		... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(【blank】), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)]

2024-08-27 15:57:35 V/Bot.【blank】: Event: AutoLoginEvent.Failure(bot=【blank】, protocol=ANDROID_PHONE, cause=net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.)
2024-08-27 15:57:35 I/Bot.【blank】: Bot cancelled: Bot closed
2024-08-27 15:57:35 I/main: mirai-console started successfully.
```

**Comment by shigu666** [comment]
详情见这个帖子
https://mirai.mamoe.net/topic/223/
