### ISSUE TITLE
报错。提示找不到方法limitedParallelism

### ISSUE THREAD

**Issue by laoliucxy** [mamoe/mirai#2862]
### 问题描述

Java开发，使用maven构建的项目。
       <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.16.0</version>
        </dependency>
  <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.9.20</version>
        </dependency>

### 复现

Bot bot = BotFactory.INSTANCE.newBot(106480221, "test")。报错提示找不到方法limitedParallelism

### mirai-core 版本

2.16.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
Caused by: java.lang.NoSuchMethodError: 'kotlinx.coroutines.CoroutineDispatcher kotlinx.coroutines.CoroutineDispatcher.limitedParallelism(int)'
	at net.mamoe.mirai.internal.deps.io.ktor.client.utils.CoroutineDispatcherUtilsKt.clientDispatcher(CoroutineDispatcherUtils.kt:22)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine$dispatcher$2.invoke(OkHttpEngine.kt:32)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine$dispatcher$2.invoke(OkHttpEngine.kt:31)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine.getDispatcher(OkHttpEngine.kt:31)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.HttpClientEngineBase$coroutineContext$2.invoke(HttpClientEngineBase.kt:22)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.HttpClientEngineBase$coroutineContext$2.invoke(HttpClientEngineBase.kt:21)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.HttpClientEngineBase.getCoroutineContext(HttpClientEngineBase.kt:21)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:51)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttp.create(OkHttp.kt:31)
	at net.mamoe.mirai.internal.deps.io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41)
	at net.mamoe.mirai.internal.MiraiImplKt.createDefaultHttpClient(MiraiImpl.kt:31)
	at net.mamoe.mirai.internal.MiraiImpl.<init>(MiraiImpl.kt:104)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 43 more
```

**Comment by MrXiaoM** [comment]
尝试使用 kotlin stdlib 1.8.10，尽可能与 mirai 编译使用的 kotlin 版本一致

**Comment by laoliucxy** [comment]
还是报相同的异常。mavn中配置文件：
 <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.16.0</version>
        </dependency>
 <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.8.10</version>
        </dependency>

异常如下：
Exception in thread "main" java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:270)
	at net.mamoe.mirai.utils.ServicesKt$loadService$jdkService$2.invoke(Services.kt:36)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.utils.ServicesKt.loadService$lambda$1(Services.kt:35)
	at net.mamoe.mirai.utils.ServicesKt.access$loadService$lambda$1(Services.kt:1)
	at net.mamoe.mirai.utils.ServicesKt$loadService$services$2.invoke(Services.kt:46)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.utils.ServicesKt.loadService$lambda$2(Services.kt:43)
	at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:57)
	at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:350)
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:341)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39)
	at net.mamoe.mirai.auth.BotAuthorization$Companion$factory$2.invoke(BotAuthorization.kt:93)
	at net.mamoe.mirai.auth.BotAuthorization$Companion$factory$2.invoke(BotAuthorization.kt:92)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.auth.BotAuthorization$Companion.getFactory(BotAuthorization.kt:92)
	at net.mamoe.mirai.auth.BotAuthorization$Companion.byQRCode(BotAuthorization.kt:77)
	at net.mamoe.mirai.auth.BotAuthorization.byQRCode(BotAuthorization.kt)
	at com.example.miraitest.demos.test.Main.main(Main.java:15)
Caused by: java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:270)
	at net.mamoe.mirai.utils.ServicesKt$loadService$jdkService$2.invoke(Services.kt:36)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.utils.ServicesKt.loadService$lambda$1(Services.kt:35)
	at net.mamoe.mirai.utils.ServicesKt.access$loadService$lambda$1(Services.kt:1)
	at net.mamoe.mirai.utils.ServicesKt$loadService$services$2.invoke(Services.kt:46)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.utils.ServicesKt.loadService$lambda$2(Services.kt:43)
	at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:57)
	at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:350)
	at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:341)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39)
	at net.mamoe.mirai.internal.message.MessageSerializersImpl.getSerializersModule(MessageSerializersImpl.kt:74)
	at net.mamoe.mirai.internal.message.MessageSerializersImpl.registerSerializers(MessageSerializersImpl.kt:85)
	at net.mamoe.mirai.message.MessageSerializers$INSTANCE.registerSerializers(MessageSerializers.kt)
	at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade.<clinit>(MessageProtocolFacade.kt:167)
	at net.mamoe.mirai.internal.MiraiImplKt._MiraiImpl_static_init(MiraiImpl.kt:27)
	at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt:95)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 21 more
Caused by: java.lang.NoSuchMethodError: 'kotlinx.coroutines.CoroutineDispatcher kotlinx.coroutines.CoroutineDispatcher.limitedParallelism(int)'
	at net.mamoe.mirai.internal.deps.io.ktor.client.utils.CoroutineDispatcherUtilsKt.clientDispatcher(CoroutineDispatcherUtils.kt:22)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine$dispatcher$2.invoke(OkHttpEngine.kt:32)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine$dispatcher$2.invoke(OkHttpEngine.kt:31)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine.getDispatcher(OkHttpEngine.kt:31)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.HttpClientEngineBase$coroutineContext$2.invoke(HttpClientEngineBase.kt:22)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.HttpClientEngineBase$coroutineContext$2.invoke(HttpClientEngineBase.kt:21)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.HttpClientEngineBase.getCoroutineContext(HttpClientEngineBase.kt:21)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttpEngine.<init>(OkHttpEngine.kt:51)
	at net.mamoe.mirai.internal.deps.io.ktor.client.engine.okhttp.OkHttp.create(OkHttp.kt:31)
	at net.mamoe.mirai.internal.deps.io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41)
	at net.mamoe.mirai.internal.MiraiImplKt.createDefaultHttpClient(MiraiImpl.kt:31)
	at net.mamoe.mirai.internal.MiraiImpl.<init>(MiraiImpl.kt:104)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 47 more

**Comment by laoliucxy** [comment]
解决了，Springboot版本太低了
