### ISSUE TITLE
账号被冻过一次后MACOS协议也无法解决code45

### ISSUE THREAD

**Issue by alsojiangshi** [mamoe/mirai#2864]
### 问题描述

如题

### 复现

之前使用MACOS可以解决code45版本过低问题，后面账号被冻结了一次，然后现在MACOS也会code45

### mirai-core 版本

2.16.0

### bot-protocol

MACOS

### 其他组件版本

Running MiraiConsole v2.16.0, built on 2023-10-20 06:28:10.
Frontend Terminal: version 2.16.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: Chat Command v0.6.0, org.gptbot.Plugin v0.1, mirai-api-http v2.10.0, mirai-login-solver-sakura v0.0.12, MCL Addon v2.1.1

Object Pending Finalization Count: 0
                 committed |  init   |  used   |  max
    Heap Memory:  118.0MB  | 244.0MB | 51.17MB | 3.8GB
Non-Heap Memory:  98.93MB  | 7.31MB  | 95.34MB |  -1
2024-09-16 10:38:24 W/io.netty.channel.DefaultChannelPipeline: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.timeout.ReadTimeoutException

### 系统日志

```text
2024-09-16 10:33:01 I/Bot.2494570747: Loaded account secrets from local cache.
2024-09-16 10:33:02 I/Bot.2494570747: Loaded account secrets from local cache.
2024-09-16 10:33:05 I/Bot.2494570747: Loaded account secrets from local cache.
Login failed: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
2024-09-16 10:33:05 E/console: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$login$1.invokeSuspend(SsoProcessor.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:138)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:112)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:14)
        at net.mamoe.mirai.internal.deps.io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:62)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2494570747), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                ... 6 more
        Suppressed: java.lang.IllegalStateException: Fast login failed: Error(bot=Bot(2494570747), code=16, title=登录失败, message=你的用户身份已失效，为保证账号安全，请你重新登录。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl.doLogin(SsoProcessor.kt:528)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$FastLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                ... 6 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2494570747), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=)]

2024-09-16 10:33:05 I/Bot.2494570747: Bot cancelled: Bot closed
```

**Comment by XuJingJingZhenShuaiA** [comment]
详情见这个帖子
https://mirai.mamoe.net/topic/223/

**Comment by Ra2-IFV** [comment]
Try this
https://mirai.mamoe.net/topic/2673/qsign-9-0-55-9-0-95-%E5%85%AC%E7%9B%8A-api%E5%8F%91%E5%B8%83/1

**Comment by alsojiangshi** [comment]
My Sakura Login Solver hints "no sevice available" when I scan the QR code.
By the way,when I use MACOS,it appears,too.

**Comment by Ra2-IFV** [comment]
Do not use the cloud service, it's dead

**Comment by Ra2-IFV** [comment]
> Try this https://mirai.mamoe.net/topic/2673/qsign-9-0-55-9-0-95-%E5%85%AC%E7%9B%8A-api%E5%8F%91%E5%B8%83/1

It's the only way to get a stable instance

**Comment by alsojiangshi** [comment]
I input the ticket and click the button,but I get a code 237
`2024-09-23 21:17:02 I/KFCFactory: create EncryptService(id=2494570747), protocol=ANDROID_PAD(9.0.56) by fuqiuluo/unidbg-fetch-qsign from file:///D:/mcl/KFCFactory.json
2024-09-23 21:17:03 I/KFCFactory: unidbg-fetch-qsign by https://zyr15r-astralqsign.hf.space about
{"msg":"IAA 云天明 章北海 赵怡然","code":0,"data":{"protocol":{"code":"6372","package_name":"com.tencent.mobileqq","qua":"V1_AND_SQ_9.0.56_6372_YYB_D","version":"9.0.56"},"stat":{"Call":{"Energy":6,"Sign":557},"Speed":{"minute_5":15,"minute_1":4,"minute_10":24},"Performance":{"Energy":106,"Sign":105}},"instances":["0c1b"],"version":"1.2.4","support":["9.0.65","9.0.55","9.0.85","9.0.56","9.0.90","9.0.95","9.0.81","9.0.60"]}}
2024-09-23 21:17:03 I/UnidbgFetchQsign: Bot(2494570747) initialize by https://zyr15r-astralqsign.hf.space
2024-09-23 21:17:04 I/UnidbgFetchQsign: Bot(2494570747) register, 注册成功。
2024-09-23 21:17:04 I/UnidbgFetchQsign: Bot(2494570747) initialize complete
2024-09-23 21:17:05 I/Bot.2494570747: Calculating type 2 PoW, it can take some time....
2024-09-23 21:17:05 I/Bot.2494570747: Got PoW result, cost: 22 ms
2024-09-23 21:17:46 I/Bot.2494570747: Calculating type 2 PoW, it can take some time....
2024-09-23 21:17:46 I/Bot.2494570747: Got PoW result, cost: 20 ms
2024-09-23 21:18:56 I/UnidbgFetchQsign: Bot(2494570747) destroy, IAA 云天明 章北海 赵怡然
Login failed: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
2024-09-23 21:18:56 E/console: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2494570747), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                ... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2494570747), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)]

2024-09-23 21:18:56 I/Bot.2494570747: Bot cancelled: Bot closed`

**Comment by Ra2-IFV** [comment]
You failed too many times, try later
Or, do a login on your phone, under the server network

**Comment by alsojiangshi** [comment]
已解决，感谢
