### ISSUE TITLE
现在能登录吗？

### ISSUE THREAD

**Issue by pandolia** [mamoe/mirai#2873]
### 问题描述

打开滑块验证网页后，滑块之后，没反应了。

### 复现

输入命令：/login xxxx

### mirai-core 版本

2.16.0

### bot-protocol

ANDROID_PHONE

### 系统日志

```text
2024-11-28 15:51:09 I/Bot.3497303033: Calculating type 2 PoW, it can take some time....
2024-11-28 15:51:09 I/Bot.3497303033: Got PoW result, cost: 52 ms
2024-11-28 15:51:09 I/Bot.3497303033: [SliderCaptcha] 需要滑动验证码, 请按照以下链接的步骤完成滑动验证码, 然后输入获取到的 ticket
2024-11-28 15:51:09 I/Bot.3497303033: [SliderCaptcha] Slider captcha required. Please solve the captcha with following link. Type ticket here after completion.
2024-11-28 15:51:09 I/Bot.3497303033: [SliderCaptcha] @see https://github.com/project-mirai/mirai-login-solver-selenium
2024-11-28 15:51:09 I/Bot.3497303033: [SliderCaptcha] @see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/
2024-11-28 15:51:09 I/Bot.3497303033: [SliderCaptcha] 或者输入 helper 来使用 TxCaptchaHelper 完成滑动验证码
2024-11-28 15:51:09 I/Bot.3497303033: [SliderCaptcha] Or type helper to resolve slider captcha with TxCaptchaHelper.apk
2024-11-28 15:51:09 W/Bot.3497303033: [SliderCaptcha] TxCaptchaHelper 的在线服务疑似被屏蔽，可能无法使用。TxCaptchaHelper 现已无法满足登录QQ机器人，请在以下链接下载全新的验证器
2024-11-28 15:51:09 W/Bot.3497303033: [SliderCaptcha] The service of TxCaptchaHelper might be blocked. We recommend you to download the new login solver plugin in below link.
2024-11-28 15:51:09 W/Bot.3497303033: [SliderCaptcha] @see https://github.com/KasukuSakura/mirai-login-solver-sakura
2024-11-28 15:51:09 I/Bot.3497303033: [SliderCaptcha] Captcha link: https://ti.qq.com/safe/tools/captcha/sms-verify-login?aid=16&uin=3497303033&sid=3671405799462674669&cap_cd=_PEww_VVQW0pvPoORMWm9EswayWqjycm8kUUO8rzhIR1Y1d32JNF-A**&clientype=1&apptype=2
```

### 网络日志

```text
无
```

### 补充信息

无

**Comment by MrXiaoM** [comment]
> 请按照以下链接的步骤完成滑动验证码,
> see https://docs.mirai.mamoe.net/mirai-login-solver-selenium/

不看文档导致的

**Comment by pandolia** [comment]
确认一下哈，这个文档的方法能用吗？我看这个文档上的第一句话就是：“由于服务器再次更新验证逻辑，此模块已经无法正常工作”。

**Comment by MrXiaoM** [comment]
> 确认一下哈，这个文档的方法能用吗？我看这个文档上的第一句话就是：“由于服务器再次更新验证逻辑，此模块已经无法正常工作”。

如果你只使用 mirai，没有签名服务，没有登录验证解决器，那就不能用。

**Comment by pandolia** [comment]
> > 确认一下哈，这个文档的方法能用吗？我看这个文档上的第一句话就是：“由于服务器再次更新验证逻辑，此模块已经无法正常工作”。
> 
> 如果你只使用 mirai，没有签名服务，没有登录验证解决器，那就不能用。

谢谢！您说的签名服务和登录验证解决器是通过/mcl update 命令安装吗？还是需要下载安装？

**Comment by MrXiaoM** [comment]
> 谢谢！您说的签名服务和登录验证解决器是通过/mcl update 命令安装吗？还是需要下载安装？

https://wiki.mrxiaom.top/mirai/45
https://wiki.mrxiaom.top/mirai/1-2

**Comment by pandolia** [comment]
> > 谢谢！您说的签名服务和登录验证解决器是通过/mcl update 命令安装吗？还是需要下载安装？
> 
> https://wiki.mrxiaom.top/mirai/45 https://wiki.mrxiaom.top/mirai/1-2

收到，非常感谢！

**Comment by pandolia** [comment]
已经安装了登录验证解决器 mirai-login-solver-sakura-0.0.12.mirai2.jar 和 签名服务 trpgbot-1.13.4.mirai2.jar ，手机也安装了 apk-release.apk 。登录验证解决器应该没问题了，可以用手机扫码。签名服务还有点问题，麻烦大佬再帮我看一下哈：


 file:///D:/Language/mirai/_env/network.json
2024-11-29 10:04:29 W/trpgbot: 您正在使用远程签名服务，数据包将经过签名服务器，请勿添加不可信源
2024-11-29 10:04:29 W/EncryptService.alert: Encrypt service was loaded: trpgbot.NetworkServiceFactory(config=file:///D:/Language/mirai/_env/network.json)
2024-11-29 10:04:29 W/EncryptService.alert: All outgoing message may be leaked by this service.
2024-11-29 10:04:29 W/EncryptService.alert: Use this service if and only if you trusted this service and the service provider.
2024-11-29 10:04:29 W/EncryptService.alert: Service details:
2024-11-29 10:04:29 W/EncryptService.alert:   `- Jvm Class: class xyz.cssxsh.mirai.tool.NetworkServiceFactory
2024-11-29 10:04:29 W/EncryptService.alert:   `- ClassLoader: JvmPluginClassLoader{trpgbot-1.13.4.mirai2.jar}
2024-11-29 10:04:29 W/EncryptService.alert:   `- Source: file:/D:/Language/mirai/_env/plugins/trpgbot-1.13.4.mirai2.jar
2024-11-29 10:04:29 W/EncryptService.alert:   `- Protected Domain: ProtectionDomain  (file:/D:/Language/mirai/_env/plugins/trpgbot-1.13.4.mirai2.jar <no signer certificates>)
 JvmPluginClassLoader{trpgbot-1.13.4.mirai2.jar}
 <no principals>
 java.security.Permissions@c497a55 (
 ("java.io.FilePermission" "D:\Language\mirai\_env\plugins\trpgbot-1.13.4.mirai2.jar" "read")
)


2024-11-29 10:04:29 I/trpgbot: 正在运行 trpgbot.qsign v1.13.4
2024-11-29 10:04:29 I/trpgbot: 正在检查可用的签名服务器
2024-11-29 10:04:29 I/trpgbot.factory: 正在尝试连接 主服务器 wss://qsign.trpgbot.com/ws
2024-11-29 10:04:30 I/trpgbot.adapter.ws: 已连接到签名服务器
2024-11-29 10:04:31 I/trpgbot.factory: 服务器 wss://qsign.trpgbot.com/ws 可用
2024-11-29 10:04:31 E/trpgbot: 注册服务失败
java.lang.IllegalStateException: 从仓库 MrXiaoM/protocol-versions 获取协议列表失败
        at trpgbot-1.13.4.mirai2.jar//xyz.cssxsh.mirai.tool.NetworkServiceFactory.checkProtocolUpdate$trpgbot(NetworkServiceFactory.kt:208)
        at trpgbot-1.13.4.mirai2.jar//xyz.cssxsh.mirai.tool.FixProtocolVersionPlugin.onLoad(FixProtocolVersionPlugin.kt:57)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnLoad$mirai_console(JvmPluginInternal.kt:388)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:371)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:40)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:54)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:100)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:164)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:303)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:512)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:182)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:181)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:59)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/MrXiaoM/protocol-versions/contents/android_pad
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at trpgbot-1.13.4.mirai2.jar//xyz.cssxsh.mirai.tool.NetworkServiceFactory.checkProtocolUpdate$trpgbot(NetworkServiceFactory.kt:196)
        ... 26 more

2024-11-29 10:04:31 I/plugin: Successfully loaded plugin trpgbot v1.13.4
2024-11-29 10:04:31 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2024-11-29 10:04:31 I/main: Prepared built-in commands: autoLogin, help, login, logout, permission, status, stop
2024-11-29 10:04:31 W/mirai-api-http: USING INITIAL KEY, please edit the key
2024-11-29 10:04:31 I/Mirai HTTP API: ********************************************************
2024-11-29 10:04:31 I/MahKtorAdapter[http]: Autoreload is disabled because the development mode is off.
2024-11-29 10:04:32 I/MahKtorAdapter[http]: Application started in 0.228 seconds.
2024-11-29 10:04:32 I/MahKtorAdapter[http]: Responding at http://localhost:8080
2024-11-29 10:04:32 I/http adapter: >>> [http adapter] is listening at http://localhost:8080
2024-11-29 10:04:32 I/Mirai HTTP API: Http api server is running with verifyKey: INITKEYnOk83xKY
2024-11-29 10:04:32 I/Mirai HTTP API: adaptors: [http]
2024-11-29 10:04:32 I/Mirai HTTP API: ********************************************************
2024-11-29 10:04:32 I/trpgbot: 当前各登录协议版本日期:
ANDROID_PHONE  8.9.58.11170  2023-05-19T11:35+08:00
ANDROID_PAD    8.9.58.11170  2023-05-19T11:35+08:00
ANDROID_WATCH  9.0.3         2022-03-23T10:14:56+08:00
IPAD           8.9.50.611    2023-02-16T15:10:14+08:00
MACOS          6.8.2.21241   2022-03-14T11:11:35+08:00


         !!!    请使用 ANDROID_PAD 协议    !!!
            如需使用其他协议，请手动升级协议版本

2024-11-29 10:04:32 I/MCL Addon: iTXTech MCL Version: 2.1.2-61c8bd8
2024-11-29 10:04:32 W/MCL Addon: iTXTech Soyuz 未安装，Soyuz MCL Handler 特性已禁用
2024-11-29 10:04:32 I/main: 5 plugin(s) enabled.
2024-11-29 10:04:32 I/main: mirai-console started successfully.
> login ?? ??? ANDROID_PAD
2024-11-29 10:05:32 W/Bot.3497303033: trpgbot.NetworkServiceFactory(config=file:///D:/Language/mirai/_env/network.json) is not yet supported EncryptService with bot Bot(3497303033)
java.lang.UnsupportedOperationException: 协议 ANDROID_PAD 未提供 qua
        at trpgbot-1.13.4.mirai2.jar//xyz.cssxsh.mirai.tool.NetworkServiceFactory.createForBot(NetworkServiceFactory.kt:112)
        at net.mamoe.mirai.internal.network.components.EncryptServiceHolderImpl.<init>(EncryptServiceHolder.kt:49)
        at net.mamoe.mirai.internal.QQAndroidBot.createBotLevelComponents(QQAndroidBot.kt:288)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:192)
        at net.mamoe.mirai.internal.QQAndroidBot$defaultBotLevelComponents$2.invoke(QQAndroidBot.kt:191)
        at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:47)
        at net.mamoe.mirai.internal.QQAndroidBot.getDefaultBotLevelComponents(QQAndroidBot.kt:191)
        at net.mamoe.mirai.internal.QQAndroidBot.createNetworkLevelComponents(QQAndroidBot.kt:300)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:312)
        at net.mamoe.mirai.internal.QQAndroidBot$createNetworkHandler$1.invoke(QQAndroidBot.kt:305)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelectorKt$KeepAliveNetworkHandlerSelector$1.createInstance(AbstractKeepAliveNetworkHandlerSelector.kt:277)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.refreshInstance(AbstractKeepAliveNetworkHandlerSelector.kt:249)
        at net.mamoe.mirai.internal.network.handler.selector.AbstractKeepAliveNetworkHandlerSelector.getCurrentInstanceOrCreate(AbstractKeepAliveNetworkHandlerSelector.kt:57)
        at net.mamoe.mirai.internal.network.handler.selector.SelectorNetworkHandler.getContext(SelectorNetworkHandler.kt:51)
        at net.mamoe.mirai.internal.AbstractBot$network$2.invoke(AbstractBot.kt:139)
        at net.mamoe.mirai.internal.AbstractBot$network$2.invoke(AbstractBot.kt:137)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.internal.AbstractBot.getNetwork(AbstractBot.kt:137)
        at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:147)
        at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.doLogin$suspendImpl(LoginCommandImpl.kt:40)
        at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.doLogin$mirai_console(LoginCommandImpl.kt)
        at net.mamoe.mirai.console.internal.command.builtin.LoginCommandImpl.handle(LoginCommandImpl.kt:99)
        at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:203)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:339)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:84)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:187)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2024-11-29 10:05:34 I/Bot.3497303033: Calculating type 2 PoW, it can take some time....
2024-11-29 10:05:34 I/Bot.3497303033: Got PoW result, cost: 95 ms
2024-11-29 10:05:47 I/Bot.3497303033: Bot cancelled: Bot closed
Login failed: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
2024-11-29 10:05:47 E/console: net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
net.mamoe.mirai.network.BotAuthorizationException: BotAuthorization(BotAuthorization.byPassword(<ERASED>)) threw an exception during authorization process. See cause below.
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:263)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3497303033), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:490)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                ... 5 more
Caused by: [CIRCULAR REFERENCE: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3497303033), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)]

**Comment by pandolia** [comment]
登录成功了

**Comment by pandolia** [comment]
非常感谢大佬的帮助！！
