### ISSUE TITLE
MemberJoinEvent 比 MemberJoinRequestEvent 早广播

### ISSUE THREAD

**Issue by y702332688** [mamoe/mirai#288]
//测试 成员加入群的事件
`
mBot.subscribeAlways<MemberJoinEvent> {
    group.sendMessage(PlainText("恭喜老哥 ${member.nick} 加入"))
}
`

申请之后(没同意入群)机器人就响应了，并且安卓QQ没收到群通知(群主，电脑可以收到入群申请)，关闭机器人就收到群通知了，电脑端同意入群之后会再响应一次

工具Android Studio 3.6.3
mirai版本:0.40.0
安卓QQ:8.3.3.4515
申请入群的QQ设备:iPhone，QQ版本:8.3.5.612

**Comment by ryoii** [comment]
我测试了几遍，没有复现问题，不论是bot为管理员还是群主。其他管理员是PC还是安卓都能收到消息。
建议你用设备登录一遍bot账号，再重新用mirai登录bot。
如果这样还复现，请继续反馈

**Comment by y702332688** [comment]
> 我测试了几遍，没有复现问题，不论是bot为管理员还是群主。其他管理员是PC还是安卓都能收到消息。
> 建议你用设备登录一遍bot账号，再重新用mirai登录bot。
> 如果这样还复现，请继续反馈

依旧如此，MemberJoinEvent有时还会失效，并且MemberJoinEvent比MemberJoinRequestEvent事件要早

`
            //禁言监听
            mBot.subscribeAlways<MemberMuteEvent> {
                group.sendMessage(PlainText("恭喜老哥 ${member.nick} 喜提禁言套餐一份"))
            }
            //解除禁言监听
            mBot.subscribeAlways<MemberUnmuteEvent> {
                group.sendMessage(PlainText("恭喜老哥 ${member.nick} 禁言已解除"))
            }
            //测试 成员加入群的事件
            mBot.subscribeAlways<MemberJoinEvent> {
                group.sendMessage(PlainText("恭喜老哥 ${member.nick} 加入"))
            }
            //请求加入群事件
            mBot.subscribeAlways<MemberJoinRequestEvent> {
                group.sendMessage(PlainText("入群申请"))
            }
`

log输出信息

2020-04-30 16:20:39.522 5257-5302/com.bitmean.qq I/System.out: [0mNetwork(577655642) 16:20:39 : Send: Heartbeat.Alive
2020-04-30 16:20:39.556 5257-5302/com.bitmean.qq I/System.out: [0mNetwork(577655642) 16:20:39 : Packet: Heartbeat.Alive.Response
2020-04-30 16:20:50.411 5257-5336/com.bitmean.qq I/System.out: [0mBot(577655642) 16:20:50 : Event: MemberLeaveEvent.Kick(member=Member(702332688), operator=Member(1241799452))
2020-04-30 16:20:50.412 5257-5336/com.bitmean.qq I/System.out: [0mNetwork(577655642) 16:20:50 : Send: OnlinePush.RespPush
2020-04-30 16:20:54.493 5257-5336/com.bitmean.qq I/System.out: [0mNetwork(577655642) 16:20:54 : Packet: net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPushNotify@de58dc7
2020-04-30 16:20:54.496 5257-5336/com.bitmean.qq I/System.out: [0mNetwork(577655642) 16:20:54 : Send: MessageSvc.PbGetMsg
2020-04-30 16:20:54.598 5257-5336/com.bitmean.qq I/System.out: [0mNetwork(577655642) 16:20:54 : Send: MessageSvc.PbDeleteMsg
2020-04-30 16:20:54.600 5257-5336/com.bitmean.qq I/System.out: [0mNetwork(577655642) 16:20:54 : Send: ProfileService.Pb.ReqSystemMsgNew.Group
2020-04-30 16:20:54.601 5257-5303/com.bitmean.qq I/System.out: [0mBot(577655642) 16:20:54 : Event: Active(member=Member(702332688))
2020-04-30 16:20:54.604 5257-5302/com.bitmean.qq I/System.out: [0mNetwork(577655642) 16:20:54 : Send: MessageSvc.PbSendMsg
2020-04-30 16:20:54.757 5257-5336/com.bitmean.qq I/System.out: [0mBot(577655642) 16:20:54 : Event: MemberJoinRequestEvent(bot=Bot(577655642), eventId=1588234852355721, message=, fromId=702332688, groupId=78472999, groupName=测试, fromNick=墨语)
2020-04-30 16:20:54.760 5257-5351/com.bitmean.qq I/System.out: [0mNetwork(577655642) 16:20:54 : Send: MessageSvc.PbSendMsg
2020-04-30 16:20:54.775 5257-5303/com.bitmean.qq I/System.out: [0mNetwork(577655642) 16:20:54 : Packet: MessageSvc.PbSendMsg.Response.SUCCESS
2020-04-30 16:20:54.840 5257-5351/com.bitmean.qq I/System.out: [0mBot(577655642) 16:20:54 : Group(78472999) <- 恭喜老哥 墨语 加入
2020-04-30 16:20:54.935 5257-5303/com.bitmean.qq I/System.out: [0mNetwork(577655642) 16:20:54 : Packet: MessageSvc.PbSendMsg.Response.SUCCESS
2020-04-30 16:20:55.005 5257-5336/com.bitmean.qq I/System.out: [0mBot(577655642) 16:20:55 : Group(78472999) <- 入群申请

**Comment by y702332688** [comment]
> 我测试了几遍，没有复现问题，不论是bot为管理员还是群主。其他管理员是PC还是安卓都能收到消息。
> 建议你用设备登录一遍bot账号，再重新用mirai登录bot。
> 如果这样还复现，请继续反馈

如果可以的话，加我QQ1241799452  我远程演示给你看

**Comment by ryoii** [comment]
你用设备登录bot账号 -> 群通知 -> 清空验证消息(右上角)
在进行尝试

**Comment by y702332688** [comment]
> 你用设备登录bot账号 -> 群通知 -> 清空验证消息(右上角)
> 再进行尝试

我录屏了，我现在发百度云，你看下

**Comment by y702332688** [comment]
> 你用设备登录bot账号 -> 群通知 -> 清空验证消息(右上角)
> 再进行尝试

链接：https://pan.baidu.com/s/1a1X5oMQWCQMF-hbwMTjUhQ 
提取码：vyf3

**Comment by ryoii** [comment]
视频里没有看到**MemberJoinEvent比MemberJoinRequestEvent事件要早**

**Comment by y702332688** [comment]
> 视频里没有看到**MemberJoinEvent比MemberJoinRequestEvent事件要早**

早的不是必现的，不过几率很大，等下我再录下

**Comment by y702332688** [comment]
> 你用设备登录bot账号 -> 群通知 -> 清空验证消息(右上角)
> 再进行尝试

又遇到一种情况，群主禁言成员，机器人收到禁言事件后解禁成员禁言，群主再次禁言成员，机器人的禁言事件就收不到了

**Comment by y702332688** [comment]
> 你用设备登录bot账号 -> 群通知 -> 清空验证消息(右上角)
> 再进行尝试

链接：https://pan.baidu.com/s/1CaaLTYN6A0nX5fASE7-ymA 
提取码：6d63 

还有MemberJoinEvent事件下是不是不能使用 member.mute(6000)？我这么用并没有禁言，不知道我用的对不对

**Comment by y702332688** [comment]
> 视频里没有看到**MemberJoinEvent比MemberJoinRequestEvent事件要早**

这个你看，链接：https://pan.baidu.com/s/1wbQEg126s1d7Uckm9vYWxA 
提取码：z8ju
MemberJoinEvent比MemberJoinRequestEvent
并且MemberJoinEvent下偶尔member.mute(120)可用，可用几率很小，目前我只遇到一次

**Comment by daofeng2015** [comment]
就不能用蓝奏云链接吗？百度恶心死了

**Comment by y702332688** [comment]
> 就不能用蓝奏云链接吗？百度恶心死了

对于非把主管意识强加别人身上来说，我只能说，我想，不多做解释，再见

**Comment by ieew** [comment]
我这遇到了一个类似的问题，当bot收到他人邀请bot入群的时候，http api 就会报错，并且提示提交到mirai这里来。下面是错误信息



17:38:17 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: 在 解析 richMsg 时遇到了意料之中的问题.  请完整复制此日志提交给 mirai. 调试信息: 00 3C 3F 78 6D 6C 20 76 65 72 73 69 6F 6E 3D 27 31 2E 30 27 20 65 6E 63 6F 64 69 6E 67 3D 27 55 54 46 2D 38 27 20 73 74 61 6E 64 61 6C 6F 6E 65 3D 27 79 65 73 27 20 3F 3E 3C 6D 73 67 20 73 65 72 76 69 63 65 49 44 3D 22 31 32 38 22 20 74 65 6D 70 6C 61 74 65 49 44 3D 22 31 32 33 34 35 22 20 61 63 74 69 6F 6E 3D 22 6E 61 74 69 76 65 22 20 62 72 69 65 66 3D 22 5B E9 93 BE E6 8E A5 5D E9 82 80 E8 AF B7 E4 BD A0 E5 8A A0 E5 85 A5 E7 BE A4 E8 81 8A 22 20 73 6F 75 72 63 65 4D 73 67 49 64 3D 22 30 22 20 75 72 6C 3D 22 22 3E 3C 69 74 65 6D 20 6C 61 79 6F 75 74 3D 22 32 22 3E 3C 70 69 63 74 75 72 65 20 63 6F 76 65 72 3D 22 22 2F 3E 3C 74 69 74 6C 65 3E E9 82 80 E8 AF B7 E4 BD A0 E5 8A A0 E5 85 A5 E7 BE A4 E8 81 8A 3C 2F 74 69 74 6C 65 3E 3C 73 75 6D 6D 61 72 79 20 2F 3E 3C 2F 69 74 65 6D 3E 3C 64 61 74 61 20 67 72 6F 75 70 63 6F 64 65 3D 22 36 35 35 30 35 37 31 32 37 22 20 67 72 6F 75 70 6E 61 6D 65 3D 22 6D 69 72 61 69 22 20 6D 73 67 73 65 71 3D 22 31 35 38 38 34 31 32 32 39 36 37 32 32 30 31 31 22 20 6D 73 67 74 79 70 65 3D 22 32 22 2F 3E 3C 2F 6D 73 67 3E
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.contextualBugReportException(convension.kt:417)
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.joinToMessageChain(convension.kt:287)
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.toMessageChain(convension.kt:200)
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.toMessageChain$default(convension.kt:186)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.MessageSvc$PbGetMsg$decode$$inlined$mapNotNull$1$2.emit(Collect.kt:178)
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1$lambda$1.emit(Collect.kt:138)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Collect.kt:138)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.MessageSvc$PbGetMsg$decode$$inlined$filterNot$1$2.emit(Collect.kt:140)
        at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.MessageSvc$PbGetMsg$decode$$inlined$filterNot$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.MessageSvc$PbGetMsg$decode$$inlined$mapNotNull$1.collect(SafeCollector.common.kt:114)
        at kotlinx.coroutines.flow.FlowKt__CollectionKt.toCollection(Collection.kt:32)
        at kotlinx.coroutines.flow.FlowKt.toCollection(Unknown Source)
        at kotlinx.coroutines.flow.FlowKt__CollectionKt.toList(Collection.kt:15)
        at kotlinx.coroutines.flow.FlowKt.toList(Unknown Source)
        at kotlinx.coroutines.flow.FlowKt__CollectionKt.toList$default(Collection.kt:15)
        at kotlinx.coroutines.flow.FlowKt.toList$default(Unknown Source)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.MessageSvc$PbGetMsg.decode(MessageSvc.kt:313)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:485)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:226)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:400)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:395)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:380)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.util.zip.DataFormatException: incorrect header check
        at java.util.zip.Inflater.inflateBytes(Native Method)
        at java.util.zip.Inflater.inflate(Inflater.java:259)
        at java.util.zip.Inflater.inflate(Inflater.java:280)
        at net.mamoe.mirai.qqandroid.utils.MiraiPlatformUtils.unzip(MiraiPlatformUtils.kt:30)
        at net.mamoe.mirai.qqandroid.utils.MiraiPlatformUtils.unzip$default(MiraiPlatformUtils.kt)
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.joinToMessageChain(convension.kt:288)
        ... 30 more

**Comment by Him188** [comment]
> 我这遇到了一个类似的问题:
> 当bot收到他人邀请bot入群的时候，http api 就会报错，并且提示提交到mirai这里来。下面是错误信息
> 
> ```
> 17:38:17 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: 在 解析 richMsg 时遇到了意料之中的问题.  请完整复制此日志提交给 mirai. 调试信息: 00 3C 3F 78 6D 6C 20 76 65 72 73 69 6F 6E 3D 27 31 2E 30 27 20 65 6E 63 6F 64 69 6E 67 3D 27 55 54 46 2D 38 27 20 73 74 61 6E 64 61 6C 6F 6E 65 3D 27 79 65 73 27 20 3F 3E 3C 6D 73 67 20 73 65 72 76 69 63 65 49 44 3D 22 31 32 38 22 20 74 65 6D 70 6C 61 74 65 49 44 3D 22 31 32 33 34 35 22 20 61 63 74 69 6F 6E 3D 22 6E 61 74 69 76 65 22 20 62 72 69 65 66 3D 22 5B E9 93 BE E6 8E A5 5D E9 82 80 E8 AF B7 E4 BD A0 E5 8A A0 E5 85 A5 E7 BE A4 E8 81 8A 22 20 73 6F 75 72 63 65 4D 73 67 49 64 3D 22 30 22 20 75 72 6C 3D 22 22 3E 3C 69 74 65 6D 20 6C 61 79 6F 75 74 3D 22 32 22 3E 3C 70 69 63 74 75 72 65 20 63 6F 76 65 72 3D 22 22 2F 3E 3C 74 69 74 6C 65 3E E9 82 80 E8 AF B7 E4 BD A0 E5 8A A0 E5 85 A5 E7 BE A4 E8 81 8A 3C 2F 74 69 74 6C 65 3E 3C 73 75 6D 6D 61 72 79 20 2F 3E 3C 2F 69 74 65 6D 3E 3C 64 61 74 61 20 67 72 6F 75 70 63 6F 64 65 3D 22 36 35 35 30 35 37 31 32 37 22 20 67 72 6F 75 70 6E 61 6D 65 3D 22 6D 69 72 61 69 22 20 6D 73 67 73 65 71 3D 22 31 35 38 38 34 31 32 32 39 36 37 32 32 30 31 31 22 20 6D 73 67 74 79 70 65 3D 22 32 22 2F 3E 3C 2F 6D 73 67 3E
>         at net.mamoe.mirai.qqandroid.message.ConvensionKt.contextualBugReportException(convension.kt:417)
>         at net.mamoe.mirai.qqandroid.message.ConvensionKt.joinToMessageChain(convension.kt:287)
>         at net.mamoe.mirai.qqandroid.message.ConvensionKt.toMessageChain(convension.kt:200)
>         at net.mamoe.mirai.qqandroid.message.ConvensionKt.toMessageChain$default(convension.kt:186)
>         at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.MessageSvc$PbGetMsg$decode$$inlined$mapNotNull$1$2.emit(Collect.kt:178)
>         at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
>         at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1$lambda$1.emit(Collect.kt:138)
>         at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Collect.kt:138)
>         at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.MessageSvc$PbGetMsg$decode$$inlined$filterNot$1$2.emit(Collect.kt:140)
>         at kotlinx.coroutines.flow.FlowKt__BuildersKt$asFlow$$inlined$unsafeFlow$3.collect(SafeCollector.common.kt:115)
>         at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.MessageSvc$PbGetMsg$decode$$inlined$filterNot$1.collect(SafeCollector.common.kt:114)
>         at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1.collect(SafeCollector.common.kt:114)
>         at kotlinx.coroutines.flow.FlowKt__MergeKt$flattenConcat$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:114)
>         at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.MessageSvc$PbGetMsg$decode$$inlined$mapNotNull$1.collect(SafeCollector.common.kt:114)
>         at kotlinx.coroutines.flow.FlowKt__CollectionKt.toCollection(Collection.kt:32)
>         at kotlinx.coroutines.flow.FlowKt.toCollection(Unknown Source)
>         at kotlinx.coroutines.flow.FlowKt__CollectionKt.toList(Collection.kt:15)
>         at kotlinx.coroutines.flow.FlowKt.toList(Unknown Source)
>         at kotlinx.coroutines.flow.FlowKt__CollectionKt.toList$default(Collection.kt:15)
>         at kotlinx.coroutines.flow.FlowKt.toList$default(Unknown Source)
>         at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.MessageSvc$PbGetMsg.decode(MessageSvc.kt:313)
>         at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:485)
>         at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:226)
>         at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:400)
>         at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:395)
>         at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:380)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> Caused by: java.util.zip.DataFormatException: incorrect header check
>         at java.util.zip.Inflater.inflateBytes(Native Method)
>         at java.util.zip.Inflater.inflate(Inflater.java:259)
>         at java.util.zip.Inflater.inflate(Inflater.java:280)
>         at net.mamoe.mirai.qqandroid.utils.MiraiPlatformUtils.unzip(MiraiPlatformUtils.kt:30)
>         at net.mamoe.mirai.qqandroid.utils.MiraiPlatformUtils.unzip$default(MiraiPlatformUtils.kt)
>         at net.mamoe.mirai.qqandroid.message.ConvensionKt.joinToMessageChain(convension.kt:288)
>         ... 30 more
> ```

使用 `0.40.0`
