### ISSUE TITLE
机器人掉线重连期间进群的群员会提示找不到群员

### ISSUE THREAD

**Issue by lindongbin** [mamoe/mirai#298]
服务器的机器人有时候会掉线重连，刚好这期间有人进群，然后这个人的发言内容日志不显示，会提示找不到群员

> [0m 03:36:10 [INFO] [NETWORK ERROR] java.util.NoSuchElementException: member 239991899 not found in group 480729380
	at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:276)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$PbPushGroupMsg.decode(OnlinePush.kt:93)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:495)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:467)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:462)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:447)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[39;49m
[0m 03:36:14 [INFO] [NETWORK] Send: Heartbeat.Alive[39;49m
[0m 03:36:15 [INFO] [NETWORK] Packet: Heartbeat.Alive.Response[39;49m
[0m 03:36:26 [INFO] [NETWORK ERROR] java.util.NoSuchElementException: member 239991899 not found in group 480729380
	at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:276)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$PbPushGroupMsg.decode(OnlinePush.kt:93)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:495)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:467)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:462)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:447)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

断线重连的log类似这种：

> [0m 04:24:59 [INFO] [NETWORK] Send: Heartbeat.Alive[39;49m
[0m 04:25:01 [INFO] [NETWORK] Send: Heartbeat.Alive[39;49m
[0m 04:25:08 [INFO] [BOT 1009383773] Connection dropped by server or lost, retrying login[39;49m
[0m 04:25:08 [INFO] [NETWORK] Connected to server 42.81.172.22:80[39;49m
[0m 04:25:08 [INFO] [NETWORK] Send: wtlogin.login[39;49m
[0m 04:25:08 [INFO] [NETWORK] Packet: WtLogin.Login.LoginPacketResponse.DeviceLockLogin[39;49m
[0m 04:25:08 [INFO] [NETWORK] Send: wtlogin.login[39;49m
[0m 04:25:09 [INFO] [NETWORK] Packet: LoginPacketResponse.Success[39;49m
[0m 04:25:09 [INFO] [NETWORK] Login successful[39;49m
[0m 04:25:09 [INFO] [NETWORK] Send: StatSvc.register[39;49m
[0m 04:25:09 [INFO] [NETWORK] Packet: Response(StatSvc.register)[39;49m
[0m 04:25:09 [INFO] [BOT 1009383773] Reconnected successfully[39;49m
[0m 04:25:13 [INFO] [NETWORK] Received commandName: ConfigPushSvc.PushDomain[39;49m
[0m 04:25:13 [INFO] [BOT 1009383773] Event: ConfigPushSvc.PushReq.PushReqResponse.Success[39;49m
[0m 04:25:13 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp[39;49m

**Comment by Him188** [comment]
请问使用的 core 版本号是?

**Comment by lindongbin** [comment]
> 
> 
> 请问使用的 core 版本号是?

0.40.0
