### ISSUE TITLE
对群匿名消息调用getGroup()抛出异常

### ISSUE THREAD

**Issue by Under-estimate** [mamoe/mirai#303]
## 错误信息：
```text
 java.lang.IllegalStateException: WeakRef is released
	at net.mamoe.mirai.utils.UnsafeWeakRef.get(WeakRef.kt:23)
	at net.mamoe.mirai.message.GroupMessage.getSender(GroupMessage.kt:57)
	at net.mamoe.mirai.message.GroupMessage.getGroup(GroupMessage.kt:45)
	at com.zjs.qqlite.ui.MainFrame.openDetails(MainFrame.java:203)
	...之后省略
```
出错位置附近的代码请看MainFrame.java

### MessagePane.java
```java
//每当Bot接收到新消息时，就会以这个消息创建一个MessagePane
public class MessagePane extends JPanel{
    ContactMessage message
    public MessagePane(ContactMessage message){
        this.message=message;
        initComponents();
    }
    private void initComponents(){
        JTextArea l_message=new JTextArea();
        if(message instanceof GroupMessage){
            //奇怪的是，下面的getGroup()并没有出错
            l_message.setText("["+((GroupMessage)message).getGroup().getName()+">"+message.getSenderName()+"]"+message.getMessage().contentToString());
        }else if(message instanceof FriendMessage){
            l_message.setText("["+message.getSenderName()+"]"+message.getMessage().contentToString());
        }
        l_message.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if(e.getButton()!=MouseEvent.BUTTON3)return;
                //SharedData.mainFrame的类型是MainFrame（请看下一个代码区块）
                SharedData.mainFrame.openDetails(message);
            }
        });
        add(l_message);
        //在此之后还省略了一些使用message.getGroup()的代码，但这些都没有出错。
    }
}
```
### MainFrame.java
```java
pubilc class MainFrame extends JFrame{
    JTextArea full_message=new JTextArea();
    ContactMessage activeMessage=null;
    public void openDetails(ContactMessage message){
        if(activeMessage==message)return;
        activeMessage=message;
        if(message instanceof GroupMessage){
            ////////下面的getGroup()出错了!!!////////
            full_message.setText("["+((GroupMessage)message).getGroup().getName()+"]中的["+message.getSenderName()+"]:\r\n"
                +message.getMessage().contentToString());
        }else if(message instanceof  FriendMessage){
            full_message.setText("["+message.getSenderName()+"]:\r\n"
            +message.getMessage().contentToString());
        }
    }
}
```

## 说明：
+ 对于非匿名消息，不会出现IllegalStateException异常。
+ 执行openDetails()时当前Bot仍在发出匿名消息的群中，没有被踢出，群也没有解散。

## 开发环境：
IntelliJ IDEA Ultimate 2020.1 和 Mirai Console Dev 1.1.4
开发语言：Java + Gradle

## 插件运行环境：
Mirai Console-Graphical 0.0.7
Core Version: 0.40.0 
来自：Mirai一键包3.0.exe

**Comment by Him188** [comment]
感谢你的提交, 将在 1.0.0 发布修复
