### ISSUE TITLE
bot接受好友申请时group id处理错误

### ISSUE THREAD

**Issue by VonXXGhost** [mamoe/mirai#309]
## 问题

在部分情况下处理来自群的好友申请时会报错java.util.NoSuchElementException: group XXXXX。

> java.util.NoSuchElementException: group 382896xxxx
	at net.mamoe.mirai.Bot.getGroup(Bot.kt:134) ~[mirai-core-1.0-RC.jar:?]
	at net.mamoe.mirai.event.events.NewFriendRequestEvent.<init>(BotEvents.kt:704) ~[mirai-core-1.0-RC.jar:?]
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.NewContact$SystemMsgNewFriend.decode(NewContact.kt:50) ~[mirai-core-qqandroid-1.0-RC.jar:?]
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:492) ~[mirai-core-qqandroid-1.0-RC.jar:?]
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:230) ~[mirai-core-qqandroid-1.0-RC.jar:?]
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:470) ~[mirai-core-qqandroid-1.0-RC.jar:?]
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:465) ~[mirai-core-qqandroid-1.0-RC.jar:?]
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:450) [mirai-core-qqandroid-1.0-RC.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.3.72.jar:1.3.72-release-468 (1.3.72)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) [kotlinx-coroutines-core-1.3.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-1.3.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) [kotlinx-coroutines-core-1.3.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-1.3.4.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-1.3.4.jar:?]

## 如何复现

在一个群号 _groupCode / 1000000 < 500_ 的群向bot发送好友申请，即便不subscribe相关事件也会报错。

貌似是调用了Group.calculateGroupUinByGroupCode(groupCode)，但实际应该判断的应该是groupCode？

**Comment by cyanray** [comment]
我遇到了同样的问题，但是我的触发条件不同。
通过 QQ 号码搜索机器人账号然后加为好友（而不是通过群组添加好友），也会触发这个错误。

```
 20:12:20 [INFO] [NETWORK ERROR] java.util.NoSuchElementException: group 202000000
        at net.mamoe.mirai.Bot.getGroup(Bot.kt:134)
        at net.mamoe.mirai.event.events.NewFriendRequestEvent.<init>(BotEvents.kt:704)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.NewContact$SystemMsgNewFriend.decode(NewContact.kt:50)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:492)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:230)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:470)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:450)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
