### ISSUE TITLE
邀请 Bot 进群时事件处理异常。

### ISSUE THREAD

**Issue by IceCream-Open** [mamoe/mirai#319]
在试图邀请 Bot 加入某个群时，事件响应异常。
邀请人没有群管理权限。
在邀请人是非好友的时候触发异常。
在邀请人是好友的时候触发异常，并且机器人将发送进群申请。

```
<!--如果有控制台报错，请尽量在这里附加全面的日志. (不建议截图)-->
java.util.NoSuchElementException: group 群号
	at net.mamoe.mirai.Bot.getGroup(Bot.kt:131)
	at net.mamoe.mirai.event.events.MemberJoinRequestEvent.<init>(group.kt:307)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:164)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:484)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:226)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:466)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:461)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:446)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)



```

### 如何复现

使用一个非管理权限的账号邀请 Bot 进入某群。

### 版本
mirai: `1.0-RC2-1`

**Comment by ryoii** [comment]
邀请人没有管理权限的时候，Bot的申请入群需要管理员审核。
Bot被邀请入群出现了`MemberJoinRequestEvent`，需要考虑**非管理员邀请Bot入群**是否有发意料之外的包
