### ISSUE TITLE
响应 MemberJoinRequestEvent 时提示请求过期，已被其他管理员响应

### ISSUE THREAD

**Issue by kirainmoe** [mamoe/mirai#322]
## 问题

mirai-api-http 正常接受 `MemberJoinRequestEvent` ：

```txt
23:31:38 [INFO] [BOT{xxxxx}] Event: MemberJoinRequestEvent(bot=Bot({xxxxx}), eventId=1588433497927111, message={xxxxx}, fromId={xxxxx}, groupId={xxxxx}, groupName={xxxxx}, fromNick={xxxxx})
```

当向`/resp/memberJoinRequestEvent` POST 响应时，返回 500，同时在 console 中返回请求已过期，入群申请已被其他管理员处理；然而实际上并没有人处理，抛出此错误后其他管理员仍然可以正常审批。

```txt
23:31:38 [ERROR] [MiraiAPIHTTP] java.lang.IllegalStateException: the request Bot({xxxxxx}) is outdated: Another operator has already responded it.
	at net.mamoe.mirai.qqandroid.QQAndroidBot.acceptMemberJoinRequest(QQAndroidBot.common.kt:141)
	at net.mamoe.mirai.event.events.MemberJoinRequestEvent.accept(BotEvents.kt:688)
	at net.mamoe.mirai.api.http.route.EventRouteModuleKt$eventRouteModule$1$$special$$inlined$miraiVerify$2$1.invokeSuspend(BaseRoute.kt:348)
	at net.mamoe.mirai.api.http.route.EventRouteModuleKt$eventRouteModule$1$$special$$inlined$miraiVerify$2$1.invoke(BaseRoute.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.routing.Routing.executeResult(Routing.kt:147)
	at io.ktor.routing.Routing.interceptor(Routing.kt:34)
	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:139)
	at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:120)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.cio.CIOApplicationEngine$startConnector$server$1$1.invokeSuspend(CIOApplicationEngine.kt:167)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

## 如何复现

触发加群事件并响应即可。BOT 的权限为普通管理员。

**Comment by Him188** [comment]
这个问题可能是 `1.0-RC2-1` 前没有正确解析入群申请的问题. 
是否在 `1.0-RC2-1` 仍然有这个问题?

**Comment by kirainmoe** [comment]
`1.0-RC2-1` 可以处理申请了，但是 HTTP API 仍然返回 500，错误内容如下：

```
 16:22:26 [INFO] [BOT 731172035] Event: MemberJoinRequestEvent(bot=Bot(xxxxxxxx), eventId=xxxxxxxx, message=xxxxxxxx, fromId=xxxxxxxx, groupId=xxxxxxxx, groupName=xxxxxxxx, fromNick=xxxxxxxx)
 16:22:26 [INFO] [NETWORK] Send: ProfileService.Pb.ReqSystemMsgAction.Group
 16:22:26 [ERROR] [MiraiAPIHTTP] kotlinx.serialization.SerializationException: Can't locate argument-less serializer for class Success. For generic classes, such as lists, please provide serializer explicitly.
	at kotlinx.serialization.PlatformUtilsKt.serializer(PlatformUtils.kt:21)
	at kotlinx.serialization.modules.SerialModuleExtensionsKt.getContextualOrDefault(SerialModuleExtensions.kt:26)
	at net.mamoe.mirai.api.http.route.EventRouteModuleKt$eventRouteModule$1$$special$$inlined$miraiVerify$2$1.invokeSuspend(BaseRoute.kt:371)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
