### ISSUE TITLE
加载好友列表失败

### ISSUE THREAD

**Issue by BOFA1ex** [mamoe/mirai#329]
场景描述:
登录成功后, 能正常获取信息, 但是引入订阅事件逻辑, 就会抛出以下异常. 
ps: 入口类的编写, 参考官方module#mirai-demo-java#BlockingTest, 如有不对, 望大佬指点迷津.

异常堆栈信息:
```
Bot(xxxxxx) 02:24:21 : Cannot init. some features may be affected
Exception in thread "main" net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$TimeoutException: timeout receiving response of friendlist.getFriendGroupList
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$sendAndExpect$6.invokeSuspend(QQAndroidBotNetworkHandler.kt:639)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.BotJavaFriendlyAPI.login(BotJavaFriendlyAPI.kt:205)
	at com.icoder0.mirai.Application.main(Application.java:29)
```

入口类
```
 long qqAccount = 123456L;
 String qqPwk = "xxxx";
 final Bot bot = BotFactoryJvm.newBot(qqAccount, qqPwk, new BotConfiguration() {
     {
         // 保存设备信息到文件
         setDeviceInfo(context ->
         SystemDeviceInfoKt.loadAsDeviceInfo(new File("deviceInfo.json"), context)
         );
     }
});
try {
     bot.login();
     // 获取列表好友信息
     bot.getFriends().forEach(System.err::println);
     Events.registerEvents(bot, new ListenerHost() {
         @EventHandler
         public void onGroupMessage(GroupMessageEvent ignore) {
         }
     });
} finally {
     bot.join();
}
```
依赖文件
```
<properties>
        <mirai.version>1.0-RC2</mirai.version>
</properties>
<dependencies>
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core</artifactId>
            <version>${mirai.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-qqandroid</artifactId>
            <version>${mirai.version}</version>
            <optional>true</optional>
        </dependency>
</dependencies>
```

**Comment by Him188** [comment]
网络不好，重启即可

**Comment by BOFA1ex** [comment]
> 网络不好，重启即可
已解决.
