### ISSUE TITLE
解析 Transformers528 0x27L ModGroupProfile 群 troop.credit.data 时遇到了意料之中的问题

### ISSUE THREAD

**Issue by Genanik** [mamoe/mirai#351]
mirai她自己让我来发issue的.jpg  

```
19:38:18 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: 在 解析 Transformers528 0x27L ModGroupProfile 群 troop.credit.data 时遇到了意料之中的问题. 请完整复制此日志提 交给 mirai.  调试信息: this=ModGroupProfile#1460597828 {
            cmdUin=0x0000000000000000(0)
            groupCode=0x000000001D7058A0(493901984)
            groupUin=0x00000000ED758520(3983901984)
            msgGroupProfileInfos=[GroupProfileInfo#1787598329 {
                    field=0x00000003(3)
                    value=35
            }]
    }
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.contextualBugReportException(convension.kt:456)
        at net.mamoe.mirai.qqandroid.message.ConvensionKt.contextualBugReportException$default(convension.kt:454)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.Transformers528$5$3$1.invoke(OnlinePush.ReqPush.kt:467)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.Transformers528$5$3$1.invoke(OnlinePush.ReqPush.kt:351)
        at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:172)
        at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:132)
        at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:156)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:278)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:265)
        at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:278)
        at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:265)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:696)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:270)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:466)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:461)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:450)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### 如何复现

我也不知道咋出现的（  `p`）

### 版本
mirai: `1.0.1` 

(PS: 这群号咋也要发上来...)

**Comment by Him188** [comment]
这个时候修改了群的哪一个资料？

**Comment by Him188** [comment]
@Genanik

**Comment by Genanik** [comment]
- 抱歉这么晚回复。。不过我也不清楚这时候改动了什么设置😞🤤🤤🤤

**Comment by Him188** [comment]
无法确定是哪一项数据
