### ISSUE TITLE
无需同意直接进群时，在加载新群信息完成前收到消息过早处理

### ISSUE THREAD

**Issue by takayama-lily** [mamoe/mirai#370]
人比较少的群里，好友拉群无需同意就会自动入群，
此时控制台出现报错信息

```
2020-06-15 13:28:36 V/Net 646702491: Send: MessageSvc.PbGetMsg
2020-06-15 13:28:36 V/Net 646702491: Send: MessageSvc.PbGetMsg
2020-06-15 13:28:36 V/Net 646702491: Send: MessageSvc.PbDeleteMsg
2020-06-15 13:28:36 V/Net 646702491: Send: friendlist.GetTroopListReqV2
2020-06-15 13:28:36 V/Net 646702491: Send: MessageSvc.PbDeleteMsg
2020-06-15 13:28:36 V/Net 646702491: Recv: FriendList.GetFriendGroupList.Response
2020-06-15 13:28:36 V/Net 646702491: Send: OidbSvc.0x88d_7
2020-06-15 13:28:36 E/Net 646702491: Exception in NetworkHandler
java.util.NoSuchElementException: group 231406576
	at net.mamoe.mirai.Bot.getGroup(Bot.kt:186)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePushReqPush$decode$packets$1.invoke(OnlinePush.ReqPush.kt:84)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePushReqPush$decode$packets$1.invoke(OnlinePush.ReqPush.kt:61)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePushReqPush$deco$2.invoke(OnlinePush.ReqPush.kt:72)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePushReqPush$deco$2.invoke(OnlinePush.ReqPush.kt:61)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:277)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:265)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:695)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:270)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-06-15 13:28:36 V/Net 646702491: Send: friendlist.GetTroopMemberListReq
2020-06-15 13:28:37 V/Net 646702491: Recv: FriendList.GetTroopMemberList.Response
2020-06-15 13:28:37 V/Net 646702491: Send: ProfileService.Pb.ReqSystemMsgNew.Group
2020-06-15 13:28:37 V/Bot 646702491: Event: BotJoinGroupEvent.Active(group=Group(231406576))
2020-06-15 13:28:37 V/Net 646702491: Send: ProfileService.Pb.ReqSystemMsgNew.Group
2020-06-15 13:28:37 V/Net 646702491: Send: friendlist.GetTroopListReqV2
2020-06-15 13:28:37 V/Net 646702491: Send: OnlinePush.RespPush
2020-06-15 13:28:37 V/Net 646702491: Send: OnlinePush.RespPush
2020-06-15 13:28:37 V/Net 646702491: Send: friendlist.GetTroopListReqV2
2020-06-15 13:28:37 V/Net 646702491: Recv: FriendList.GetFriendGroupList.Response
2020-06-15 13:28:37 V/Net 646702491: Send: OidbSvc.0x88d_7
2020-06-15 13:28:37 V/Net 646702491: Send: friendlist.GetTroopMemberListReq
2020-06-15 13:28:37 V/Net 646702491: Recv: FriendList.GetFriendGroupList.Response
2020-06-15 13:28:37 V/Net 646702491: Send: OidbSvc.0x88d_7
2020-06-15 13:28:37 V/Net 646702491: Recv: FriendList.GetTroopMemberList.Response
2020-06-15 13:28:37 V/Bot 646702491: Event: BotJoinGroupEvent.Invite(invitor=Member(372914165))
2020-06-15 13:28:37 V/Net 646702491: Send: friendlist.GetTroopMemberListReq
2020-06-15 13:28:37 V/Net 646702491: Recv: FriendList.GetTroopMemberList.Response
2020-06-15 13:28:37 V/Bot 646702491: Event: BotJoinGroupEvent.Invite(invitor=Member(372914165))
```

### 如何复现

拉群就能复现

### 版本
mirai: `1.0.2`

**Comment by Him188** [comment]
新群信息还没加载完成，就接受到了一条群消息
