### ISSUE TITLE
接到 BotOfflineEvent.Dropped 后没有 close network

### ISSUE THREAD

**Issue by sandtechnology** [mamoe/mirai#376]
在罕见情况下，掉线不会自动重连，导致无法正常收发消息
（部分消息已做打码处理）

```
2020-06-17 10:12:42 D/Net [机器人QQ号]: unknown sh type 736
2020-06-17 10:12:42 D/Net [机器人QQ号]: data=0C 19 00 05 0A 01 5A 3F 0B 0A 01 5A 40 0B 0A 02 00 00 9C 40 0B 0A 02 00 00 9C 7A 0B 0A 02 00 00 9C 7B 0B
2020-06-17 10:12:42 V/Net [机器人QQ号]: Send: OnlinePush.RespPush
2020-06-17 10:12:42 V/Net [机器人QQ号]: Send: MessageSvc.PbGetMsg
2020-06-17 10:12:42 V/Net [机器人QQ号]: Send: MessageSvc.PbDeleteMsg
2020-06-17 10:12:42 V/Bot [机器人QQ号]: [群聊消息]
2020-06-17 10:12:42 V/Bot [机器人QQ号]: [群聊消息]
2020-06-17 10:12:42 D/Net [机器人QQ号]: Transformers528 0x27L: new data: ForwardBody#32688007 {
            msgModProfile=ModProfile#28508776 {
                    msgProfileInfos=[ProfileInfo#6677664 {
                            field=0x00005A3F(23103)
                            value=00 00 82 01 00 00 00 01
                    }, ProfileInfo#6677664 {
                            field=0x00005A40(23104)
                            value=0C 00 11 00 0C 00 00 00
                    }]
                    uin=0x000000006554EF99([机器人QQ号])
            }
            opType=0x00000014(20)
    }
2020-06-17 10:12:42 V/Net [机器人QQ号]: Send: OnlinePush.RespPush
2020-06-17 10:12:45 D/Net [机器人QQ号]: Received unknown commandName: OnlinePush.SidTicketExpired
2020-06-17 10:12:45 V/Bot [机器人QQ号]: Event: Dropped(bot=Bot([机器人QQ号]), cause=MsfOfflineToken(uin=[机器人QQ号], seq=2567774193, const=0))
2020-06-17 10:12:45 V/Net [机器人QQ号]: Send: StatSvc.RspMSFForceOffline
2020-06-17 10:12:50 E/Net [机器人QQ号]: Exception in NetworkHandler
java.lang.IllegalStateException: returnCode = -10004
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:305)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:214)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-06-17 10:12:50 E/Net [机器人QQ号]: Exception in NetworkHandler
java.lang.IllegalStateException: returnCode = -10004
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:305)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:214)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-06-17 10:12:54 E/Net [机器人QQ号]: Exception in NetworkHandler
java.lang.IllegalStateException: returnCode = -10004
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:305)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:214)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-06-17 10:13:16 V/Net [机器人QQ号]: Send: Heartbeat.Alive
2020-06-17 10:13:16 V/Net [机器人QQ号]: Recv: Heartbeat.Alive.Response
2020-06-17 10:14:16 V/Net [机器人QQ号]: Send: Heartbeat.Alive
2020-06-17 10:14:16 V/Net [机器人QQ号]: Recv: Heartbeat.Alive.Response
2020-06-17 10:15:16 V/Net [机器人QQ号]: Send: Heartbeat.Alive


```

### 如何复现

未知

### 版本
mirai: `1.0.2`

**Comment by Him188** [comment]
关键内容:
```
2020-06-17 10:12:45 D/Net [机器人QQ号]: Received unknown commandName: OnlinePush.SidTicketExpired
```

**Comment by Him188** [comment]
可能能帮助解决 #328

**Comment by Him188** [comment]
@sandtechnology  能否添加更详细的日志? 需要知道从上次重连到这个错误发生的间隔时长

**Comment by sandtechnology** [comment]
> 
> 
> @sandtechnology 能否添加更详细的日志? 需要知道从上次重连到这个错误发生的间隔时长

还好我没删日志.jpg 貌似是特定服务器才有的问题？
```
2020-06-17 10:09:16 I/Bot [机器人账号]: Connection dropped by server or lost, retrying login
2020-06-17 10:09:16 I/Net [机器人账号]: Connected to server msfwifi.3g.qq.com:8080
2020-06-17 10:09:16 V/Net [机器人账号]: Send: wtlogin.login
2020-06-17 10:09:16 V/Net [机器人账号]: Recv: LoginPacketResponse.Success
2020-06-17 10:09:16 I/Net [机器人账号]: Login successful
2020-06-17 10:09:16 V/Net [机器人账号]: Send: StatSvc.register
2020-06-17 10:09:16 V/Net [机器人账号]: Recv: Response(StatSvc.register)
2020-06-17 10:09:16 I/Bot [机器人账号]: Reconnected successfully in 0.352s
2020-06-17 10:09:16 I/Net [机器人账号]: Syncing friend message history...
2020-06-17 10:09:16 V/Net [机器人账号]: Send: MessageSvc.PbGetMsg
2020-06-17 10:09:16 I/Net [机器人账号]: Syncing friend message history: Success
2020-06-17 10:09:18 V/Bot [机器人账号]: [群聊消息]
2020-06-17 10:09:18 V/Bot [机器人账号]: [群聊消息]
2020-06-17 10:09:19 V/Net [机器人账号]: Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
2020-06-17 10:09:19 V/Net [机器人账号]: Send: ConfigPushSvc.PushResp
2020-06-17 10:09:19 D/Net [机器人账号]: Received unknown commandName: ConfigPushSvc.PushDomain
2020-06-17 10:09:19 V/Net [机器人账号]: Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
2020-06-17 10:09:19 V/Net [机器人账号]: Send: ConfigPushSvc.PushResp
`
