### ISSUE TITLE
断线重连期间其他客户端代收入群提示等消息导致新群员丢失

### ISSUE THREAD

**Issue by Under-estimate** [mamoe/mirai#382]
Bot因网络不稳定而断网期间，恰好有新成员加入某一个群，此后若此成员发言或被@，控制台会报错。
+ 若此成员被其他群员@，@消息会被正常处理，但仍会报错。
+ 若此成员主动发言，其发言的消息不会被正常处理（注册的监听器不会收到此消息）。

---

详细报错信息(这是用户被@时的报错信息，已剔除普通的消息信息)：
```
 17:13:29 [INFO] [NETWORK] Send: OnlinePush.RespPush
 17:13:32 [INFO] [NETWORK] Send: OnlinePush.RespPush
 17:13:37 [INFO] [NETWORK] Send: OnlinePush.RespPush
 17:13:47 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 17:13:47 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
 17:13:51 [INFO] [NETWORK] unknown group 528 type 0x0000000000000115, data: 08 CC 88 8C 80 03 10 BE 88 94 D9 04 1A 14 08 00 10 05 18 CF A6 B7 F7 05 20 02 28 FF FF FF FF 0F 32 00
 17:13:51 [INFO] [NETWORK] Send: OnlinePush.RespPush
 17:13:55 [INFO] [NETWORK] Received unknown commandName: StatSvc.SvcReqMSFLoginNotify
 17:13:55 [INFO] [NETWORK] Received unknown commandName: StatSvc.SvcReqMSFLoginNotify
 17:13:55 [INFO] [NETWORK] Received unknown commandName: StatSvc.SvcReqMSFLoginNotify
 17:13:59 [INFO] [NETWORK] Send: OnlinePush.RespPush
 17:14:04 [INFO] [NETWORK] Send: Heartbeat.Alive
 17:14:04 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response

[此时断网，并让新成员加群，然后恢复网络连接]

 17:14:19 [INFO] [NETWORK] Received unknown commandName: MessageSvc.PushReaded
 17:14:19 [INFO] [NETWORK] Exception in NetworkHandler
 17:14:19 [INFO] [NETWORK] Received unknown commandName: MessageSvc.RequestPushStatus
 17:14:19 [INFO] [NETWORK] Send: OnlinePush.RespPush
 17:14:19 [INFO] [NETWORK] Send: OnlinePush.RespPush
 17:14:19 [INFO] [NETWORK] Send: OnlinePush.RespPush
 17:14:19 [INFO] [NETWORK] Received unknown commandName: MessageSvc.RequestPushStatus
 17:14:19 [INFO] [NETWORK] Received unknown commandName: MessageSvc.RequestPushStatus
 17:14:19 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 17:14:19 [INFO] [BOT 1260717118] [Entropy(939952043)] Ceoreparque(2131594716) -> [mirai:source:2504,1731171627][mirai:at:805504076]  欢迎进群~\n\n本群问答系统已上线，回复Wiki:Help获取使用帮助。
 17:14:19 [INFO] [NETWORK] Send: OnlinePush.RespPush
 17:14:19 [INFO] [NETWORK ERROR] java.util.NoSuchElementException: member 805504076 not found in group 939952043
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:273)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePushPbPushGroupMsg.decode(OnlinePush.PbPushGroupMsg.kt:77)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:496)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

 17:14:19 [INFO] [NETWORK] Send: MessageSvc.PbDeleteMsg
```

### 如何复现

1. 确保Bot启动时用户A和Bot不处在同一个群聊中。
3. 将Bot断网（模拟网络不稳定）。
4. 用户A加入群聊，保持Bot处在断网状态。
5. **在因断网触发重新登录之前**，恢复Bot的网络连接。
> 如果触发了重新登录，则不会报错。
6. 用户A发言或被其他成员@。
7. 控制台报错。

### 版本
mirai: `1.0.2`

**Comment by Him188** [comment]
请尽量附加更完整的日志（包含此次断网前后）

**Comment by Under-estimate** [comment]
经实验，如果因断网时间过长触发Bot重新登录，则不会出现报错的情况。
完整日志已更新。

**Comment by Him188** [comment]
>  17:14:19 [INFO] [NETWORK] Received unknown commandName: MessageSvc.PushReaded

入群提示被另一个客户端接收, 因此没有在重连后收到

**Comment by Him188** [comment]
似乎已经修复了
