### ISSUE TITLE
重新申请加群时bot处理报错

### ISSUE THREAD

**Issue by hzm18** [mamoe/mirai#383]
bot在处理[重新申请加群]时<MemberJoinRequestEvent>的`reject()`操作报错。

报错信息如下：
```
2020-06-20 18:32:10 E/Bot XXXXXXXXX: An exception was thrown under a coroutine of Bot
java.lang.IllegalStateException: the request Bot(XXXXXXXXX) is outdated: Another operator has already responded it.
	at net.mamoe.mirai.qqandroid.QQAndroidBot.rejectMemberJoinRequest(QQAndroidBot.common.kt:155)
	at net.mamoe.mirai.event.events.MemberJoinRequestEvent.reject(group.kt:358)
	at net.mamoe.mirai.event.events.MemberJoinRequestEvent.reject$default(group.kt:358)
	at com.mzzz.BotApplicationKt$main$2.invokeSuspend(BotApplication.kt:21)
	at com.mzzz.BotApplicationKt$main$2.invoke(BotApplication.kt)


```

### 如何复现
A申请加群，但是bot拒绝(inject)通过，然后A再次发起加群请求时，会报错。

### 版本
mirai: `net.mamoe:mirai-core-qqandroid:1.1-EA` 

```
测试的代码
suspend fun main() {
    val qq = ******L;
    val password = "*********"
    val bot = Bot(qq, password) {
        fileBasedDeviceInfo()
        inheritCoroutineContext()
    }.alsoLogin()

    bot.subscribeAlways<MemberJoinRequestEvent> {
        println(it.groupId)
        println(it.message)
        println(it.fromId)
        it.reject()
    }
    bot.join();
}
```

**Comment by hzm18** [comment]
执行`inject()`时确认群里没有该申请用户

**Comment by Karlatemp** [comment]
已经成功复现
相关代码
```kotlin
val logger = Bootstrap.logger
logger.info("Pre")
logger.info(bot.groups[<HIDDEN>].members.joinToString(", ") { member ->
    member.toString()
})
logger.info("=>")
kotlin.runCatching {
    this.reject(false)
}.onFailure {
    logger.log(Level.SEVERE, "ERRRO!", it)
}
logger.info("Post...")
logger.info(bot.groups[<HIDDEN>].members.joinToString(", ") { member ->
    member.toString()
})
logger.info("== == == == == == == ==")
```
相关日志
```
[2020/06/20 18:52:21] [Bot ----------] [FINE] Event: MemberJoinRequestEvent(bot=Bot(----------), eventId=1592650344162413, message=问题：a\n答案：1, fromId=344-------, groupId=---------, groupName=---, fromNick=---)
[2020/06/20 18:52:21] [  Bootstrap   ] [INFO] Pre
[2020/06/20 18:52:21] [  Bootstrap   ] [INFO] Member(90-------), Member(327-------)
[2020/06/20 18:52:21] [  Bootstrap   ] [INFO] =>
[2020/06/20 18:52:21] [  Bootstrap   ] [INFO] Post...
[2020/06/20 18:52:21] [  Bootstrap   ] [INFO] Member(90-------), Member(327-------), Member(344-------)
[2020/06/20 18:52:21] [  Bootstrap   ] [INFO] == == == == == == == ==
```
猜测是reject处理错误
