### ISSUE TITLE
同时上传大量群图片时报错

### ISSUE THREAD

**Issue by mzdluo123** [mamoe/mirai#387]
```
 20:09:32 [ERROR] [MiraiAPIHTTP] java.lang.IllegalStateException: cannot upload
group image, failed on all servers.
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper.uploadImageTo
Servers(HighwayHelper.kt:110)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImageTo
Servers$2.invokeSuspend(HighwayHelper.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:
113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:46)
        at kotlinx.coroutines.flow.internal.SafeCollector.invokeSuspend(SafeColl
ector.kt:37)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:665)
Caused by: java.lang.IllegalStateException: highway transfer failed, error 83
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImage$$
inlined$use$lambda$1.emit(Collect.kt:149)
        at net.mamoe.mirai.qqandroid.network.highway.HighwayHelper$uploadImage$$
inlined$use$lambda$1$1.invokeSuspend(Unknown Source)
        ... 6 more
```

版本mirai-core-qqandroid-1.0.2，mirai-console-0.5.2

**Comment by Him188** [comment]
应该无法在协议上避免

**Comment by Him188** [comment]
可以考虑增大单个包的大小来减少包的数量
