### ISSUE TITLE
请问friendlist.GetTroopListReqV2接口是否有改动？

### ISSUE THREAD

**Issue by fzls** [mamoe/mirai#406]
今天开始启动mirai console的登陆的时候报[NETWORK ERROR] java.lang.IllegalStateException: type mismatch 10。
最开始以为是版本问题，尝试重新到github下载了MiraiOK在一个全新的目录拉取了一份最新的二进制，并使用机器人登录，仍报相同错误，查看过各个mirai仓库的issue，似乎还没看到相关的issue，所以来此问一下。

根据现有的报错日志，和今日之前的正常启动日志，应该是Send: friendlist.GetTroopListReqV2的这个接口的问题

环境：
1. 使用miraiOK_windows_amd64.exe更新到最新版mirai-console-wrapper-1.3.0.jar
2. 使用的机器人小号QQ使用pc tim和手机QQ登录均可正常登录

启动并登录机器人的日志输出如下
```
[13:26:06.2278] I MiraiOK 20200628.233649 running at windows-amd64
[13:26:06.2278] I 此程序以Affero GPL3.0协议发布，使用时请遵守协议
[13:26:06.2278] I 代码库: github.com/LXY1226/MiraiOK gitee.com/LXY1226/MiraiOK
[13:26:06.3538] I JRE: java version "1.8.0_181"
[13:26:06.3538] I JRE: Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
[13:26:06.3538] I JRE: Java HotSpot(TM) Client VM (build 25.181-b13, mixed mode)
[13:26:06.3538] I 删除.lastupdate来在下次强制检查更新
[13:26:06.3538] I 启动Mirai...
Using proxy: null
You are running Mirai-Console-Wrapper under D:\downloads\新建文件夹 (89)
All additional libraries are located at D:\downloads\新建文件夹 (89)\libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Stay on current version.
Fetching Newest Console Version of Pure
Stay on current version.
Version check complete, starting Mirai
shadow-Protocol:D:\downloads\新建文件夹 (89)\content\mirai-core-qqandroid-1.0.2.jar
Console        :D:\downloads\新建文件夹 (89)\content\mirai-console-0.5.2.jar
Root           :D:\downloads\新建文件夹 (89)/
 13:26:06 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console now running under D:\downloads\新建文件夹 (89)
 13:26:06 [INFO] [Mirai 0.5.2 Pkmon] Get news in github: https://github.com/mamoe/mirai
 13:26:06 [INFO] [Mirai 0.5.2 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
 13:26:06 [INFO] [Mirai 0.5.2 Pkmon] Powered by Mamoe Technologies and contributors
 13:26:06 [INFO] [Plugin Manager] 开始加载D:\downloads\新建文件夹 (89)/plugins/下的插件
 13:26:06 [INFO] [Plugin Manager] 加载了0个插件
 13:26:06 [INFO] [Mirai 0.5.2 Pkmon] Mirai-console 启动完成
 13:26:06 [INFO] [Mirai 0.5.2 Pkmon] "login qqnumber qqpassword " to login a bot
 13:26:06 [INFO] [Mirai 0.5.2 Pkmon] "login qq号 qq密码 " 来登录一个BOT
 13:26:06 [INFO] [Bot Login] login...
 13:26:07 [INFO] [BOT 3036079506] Logging in...
 13:26:07 [INFO] [NETWORK] Connected to server 114.221.148.59:14000
 13:26:07 [INFO] [NETWORK] Send: wtlogin.login
 13:26:08 [INFO] [NETWORK] Recv: LoginPacketResponse.Success
 13:26:08 [INFO] [NETWORK] Login successful
 13:26:08 [INFO] [NETWORK] Send: StatSvc.register
 13:26:08 [INFO] [NETWORK] Recv: Response(StatSvc.register)
 13:26:08 [INFO] [NETWORK] 开始加载好友信息
 13:26:08 [INFO] [NETWORK] 开始加载群组列表与群成员列表
 13:26:08 [INFO] [NETWORK] Send: friendlist.getFriendGroupList
 13:26:08 [INFO] [NETWORK] Send: friendlist.GetTroopListReqV2
 13:26:08 [INFO] [NETWORK] Recv: FriendList.GetFriendGroupList.Response
 13:26:08 [INFO] [NETWORK] 正在加载好友列表 3/3
 13:26:08 [INFO] [NETWORK] 好友列表加载完成, 共 3个
 13:26:08 [INFO] [NETWORK] Exception in NetworkHandler
 13:26:08 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: type mismatch 10
        at moe.him188.jcekt.internal.JceInput.readJceLongValue(JceInput.kt:209)
        at moe.him188.jcekt.internal.JceDecoder.decodeTaggedLong(JceDecoder.kt:324)
        at moe.him188.jcekt.internal.JceDecoder.decodeTaggedLong(JceDecoder.kt:23)
        at kotlinx.serialization.internal.TaggedDecoder.decodeLongElement(Tagged.kt:223)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.StGroupRankInfo$$serializer.deserialize(TroopList.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.StGroupRankInfo$$serializer.deserialize(TroopList.kt:94)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:16)
        at kotlinx.serialization.builtins.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)
        at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:87)
        at kotlinx.serialization.internal.ListLikeSerializer.readAll(CollectionSerializers.kt:83)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:31)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:45)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Decoding.kt:231)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableValue(Tagged.kt:153)
        at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:233)
        at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
        at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:233)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.GetTroopListRespV2$$serializer.deserialize(TroopList.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.data.jce.GetTroopListRespV2$$serializer.deserialize(TroopList.kt:40)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:225)
        at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:153)
        at moe.him188.jcekt.Jce.load(Jce.kt:47)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.readJceStruct(utils.kt:50)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils.readJceStruct(utils.kt:1)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt:63)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize$SerializationUtils__UtilsKt(utils.kt:92)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket(utils.kt:60)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils.readUniPacket(utils.kt:1)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket$default(utils.kt:58)
        at net.mamoe.mirai.qqandroid.utils.io.serialization.SerializationUtils.readUniPacket$default(utils.kt:1)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.list.FriendList$GetTroopListSimplify.decode(FriendList.kt:83)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:488)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by Him188** [comment]
#405

**Comment by Him188** [comment]
马上会发布 1.0.3 版本修复这个问题

**Comment by fzls** [comment]
> 马上会发布 1.0.3 版本修复这个问题

好的呢，今天早上重启电脑突然启动不了还以为是qq协议更新了，折腾大半天哈哈哈。那我就等新版本啦0-0
