### ISSUE TITLE
群主解散群后再恢复群，群列表没有正确刷新

### ISSUE THREAD

**Issue by RedBeanN** [mamoe/mirai#410]
挺神奇的一个操作，群主解散群以后再恢复，获取群列表没有恢复后的群，console也没有该群的对话消息

第一次遇到的时候（当时还是`mirai-core-qqandroid-1.0.2`）发送对话有错误日志，复现的时候（强制更新到了`mirai-core-qqandroid-1.0.3`）问题仍然存在但没有报错也没有相关的日志

以下是第一次遇到时的报错
```
20:12:43 [INFO] [NETWORK ERROR] java.util.NoSuchElementException: group xxxxxxxxx
	at net.mamoe.mirai.Bot.getGroup(Bot.kt:134)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$ReqPush$decode$packets$1.invoke(OnlinePush.kt:613)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$ReqPush$decode$packets$1.invoke(OnlinePush.kt:241)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$ReqPush$deco$2.invoke(OnlinePush.kt:252)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePush$ReqPush$deco$2.invoke(OnlinePush.kt:241)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:277)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:265)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:695)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:274)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:230)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:470)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:465)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:450)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### 如何复现
1. 群主选择解散群聊（此时bot会收到`BotLeaveEvent`）
2. 在 [QQ恢复系统](https://huifu.qq.com/) 选择恢复群聊
3. 在恢复后的群里发消息，bot收不到对应的消息，console没有对应的输出

### 版本
mirai: `mirai-core-qqandroid-1.0.3` 

推测可能和 #404 是相同的问题

**Comment by ryoii** [comment]
确实和 #404 是相同问题
