### ISSUE TITLE
回复信息时发生错误

### ISSUE THREAD

**Issue by Steve-xmh** [mamoe/mirai#421]
我制作了一个文档查询指令，输入关键字后向指令发送者回复一个字符串表示结果（字符数量已经限制在了单条信息内，但是还是较长（约 1000 字节左右））。但是在获取成功准备回复的时候发生了错误。

```
2020-07-07 00:28:25 V/Bot 机器人QQ: SteveXMH(我的QQ) -> [mirai:source:28626,-1977196787]搜索文档 Instance
2020-07-07 00:28:26 V/Net 机器人QQ: Send: MessageSvc.PbSendMsg
2020-07-07 00:28:26 V/Net 机器人QQ: Recv: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
2020-07-07 00:28:26 E/Bot 机器人QQ: An exception was thrown under a coroutine of Bot
java.lang.IllegalStateException: Send temp message failed: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
	at net.mamoe.mirai.qqandroid.contact.UtilKt.sendMessageImpl(util.kt:63)
	at net.mamoe.mirai.qqandroid.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

### 如何复现
对一个刚刚回复相应指令的好友（或群成员）回复大约 1000 字左右的消息（单条）

### 版本
mirai: mirai-core-1.1-EA.jar

### 备注
普通长度（<100字节左右）的文本可以正常发送没有问题。

**Comment by Him188** [comment]
经测试, 1000-2000字的群消息都可以正常发送. 好友消息不能发送是因为长消息不受支持.

**Comment by Him188** [comment]
#171
