### ISSUE TITLE
快速连续延迟撤回多条MessageReceipt时报错

### ISSUE THREAD

**Issue by liding58** [mamoe/mirai#425]
快速连续延迟撤回多条MessageReceipt时报错
result=1008, errorMessage=security check not pass

```
00:54:18 [INFO] [NETWORK] Recv: Failed(result=1008, errorMessage=security check not pass)
 00:54:18 [INFO] [BOT 1619109486] An exception was thrown under a coroutine of Bot
 00:54:18 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: Failed to recall message #1118: Failed(result=1008, errorMessage=security check not pass)
	at net.mamoe.mirai.qqandroid.QQAndroidBotBase.recall$suspendImpl(QQAndroidBot.common.kt:462)
	at net.mamoe.mirai.qqandroid.QQAndroidBotBase$recall$1.invokeSuspend(QQAndroidBot.common.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


```

### 版本
mirai: `` <!--在``中填写你正在使用的版本号，如0.40.0-->

**Comment by liding58** [comment]
现尝试使用Queue存放需要撤销的信息并延迟按序撤回，
((MessageReceipt) o).recallIn(recallInTime);
或
bot.recallIn((MessageChain) o, recallInTime);

但如果队列各自延迟时间过短，依然可能会出现1008，
由于recallIn始终不会报错，IllegalStateException: Failed to recall message只有在delay time到时才有可能发生所以很难catch IllegalStateException来放回队列循环

**Comment by Him188** [comment]
应该是 QQ 服务器进行的安全检查导致

**Comment by Him188** [comment]
经讨论, 我们决定应该由调用方处理延迟问题
