### ISSUE TITLE
当回复的好友信息里包含有图片时，回复的消息会发送失败

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#426]
当回复的好友信息里包含有图片时，回复的消息会发送失败

控制台报错：

```
2020-07-08 04:28:45 V/Net 3337342367: Recv: MessageSvcPbSendMsg.Response.Failed(resultType=10, errorCode=0, errorMessage=)
java.lang.IllegalStateException: send message failed
	at net.mamoe.mirai.qqandroid.contact.UtilKt.sendMessageImpl(util.kt:38)
	at net.mamoe.mirai.qqandroid.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

### 如何复现

复现代码：
`    bot.subscribeFriendMessages { has<Image> { quoteReply("test") } }`

### 版本
mirai: `` 1.0.4``

**Comment by Him188** [comment]
含图片时消息（编码后）很长，需要按长消息模式发送。mirai还不支持好友消息的长消息。可在 #171 查看进度
