### ISSUE TITLE
在 “登录失败” “请你稍后重试” 时稍后重试，而不要停止 Bot

### ISSUE THREAD

**Issue by mzdluo123** [mamoe/mirai#428]
在长期运行机器人之后可能会导致重连失败，并且机器人将无法处理信息

```
 01:07:08 [INFO] [BOT ******] Connection dropped by server or lost, retrying
login
 01:07:09 [INFO] [NETWORK] Connected to server 125.94.60.146:80
 01:07:09 [INFO] [NETWORK] Send: wtlogin.login
 01:07:09 [INFO] [NETWORK] Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLog
in
 01:07:09 [INFO] [NETWORK] Send: wtlogin.login
 01:07:09 [INFO] [NETWORK] Recv: Error(title=登录失败, message=请你稍后重试。(0x
9a), errorInfo=)
 01:07:09 [INFO] [BOT ********] Cannot reconnect due to fatal error.
 01:07:09 [INFO] [BOT ********] An exception was thrown under a coroutine of Bo
t
 01:07:09 [INFO] [NETWORK ERROR] java.util.concurrent.CancellationException: Can
not reconnect due to fatal error.
        at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:2
2)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1$invokeSuspend$$in
lined$measureTime$lambda$1.invokeSuspend(BotImpl.kt:119)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:
113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
```

版本 1.1.0

**Comment by Him188** [comment]
> ```
> Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
> ```

尝试关闭设备锁

**Comment by mzdluo123** [comment]
但是重启之后是可以正常登录的，之前也是可以登录的，在某次重连的时候出现了这个错误

**Comment by Him188** [comment]
应在收到这样的错误消息时当作 '掉线' 处理，继续重连

**Comment by kenvix** [comment]
有时似乎还可以因为 `WrongPasswordException` 引起？

```
2020-07-14 02:59:12 I/Bot 1513002057: Connection dropped by server or lost, retrying login
2020-07-14 02:59:12 I/Net 1513002057: Connected to server msfwifi.3g.qq.com:8080
2020-07-14 02:59:12 V/Net 1513002057: Send: wtlogin.login
2020-07-14 02:59:12 V/Net 1513002057: Recv: Error(title=登录失败, message=请你稍后重试。(0x9a), errorInfo=)
2020-07-14 02:59:12 I/Bot 1513002057: Cannot reconnect due to fatal error.
2020-07-14 02:59:12 E/Bot 1513002057: An exception was thrown under a coroutine of Bot
java.util.concurrent.CancellationException: Cannot reconnect due to fatal error.
        at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1$invokeSuspend$$inlined$measureTime$lambda$1.invokeSuspend(BotImpl.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(title=登录失败, message=请你稍后重试。(0x9a), errorInfo=)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:180)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        ... 9 more

2020-07-14 03:14:12 I/Bot 1513002057: Bot cancelled: Cannot reconnect due to fatal error.
```

**Comment by Him188** [comment]
所有在登录阶段被服务器拒绝而导致的异常都会包装为WrongPasswordException

**Comment by smallT** [comment]
这两天开始用 mirai-core-qqandroid 1.3.3版本的，QQ帐号会被冻结掉，有人有碰到么？
先是报了几次：
java.lang.IllegalStateException: 在 解析 OnlinePush.PbPushTransMsg, msgType=529 时遇到了意料之中的问题. ...
   at net.mamoe.mirai.qqandroid.message.ConversionsKt.contextualBugReportException(conversions.kt:494)
的错误后，报了

java.lang.IllegalStateException: returnCode = -10004
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:315)

然后就被冻结了

**Comment by hswyxj** [comment]
13:10:32 [INFO] [NETWORK] Send: wtlogin.login
 13:10:32 [INFO] [NETWORK] Recv: Error(title=禁止登录, message=当前上网环境异常
，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)

这个是怎么回事？
