### ISSUE TITLE
通过Java登录mirai机器人出现用户名或密码错误

### ISSUE THREAD

**Issue by WuZeyue** [mamoe/mirai#433]
`Exception in thread "main" net.mamoe.mirai.network.WrongPasswordException: Error(title=登录失败, message=帐号或密码错误，请重新输入。, errorInfo=)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:180)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.BotJavaFriendlyAPI$DefaultImpls.login(BotJavaFriendlyAPI.kt:202)
	at net.mamoe.mirai.Bot.login(Bot.kt:50)
	at RobotTest.main(RobotTest.java:18)
`
按理说，用户名和密码都是对的。然后，关于账号，因为我看到qq的类型为long，所以常数后面加了标识，但登录不上；去掉也是。另外，关于编码，gbk和utf-8我都用了，甚至iso8859-1和什么utf-16都用了，都登不上。
以下是Java代码（账号密码不方便写出来）：
`import net.mamoe.mirai.Bot;
import net.mamoe.mirai.BotFactoryJvm;
import net.mamoe.mirai.utils.BotConfiguration;

public class RobotTest {

    public static void main(String[] args){
        final Bot bot = BotFactoryJvm.newBot(, "", new BotConfiguration() {
            {

                //保存设备信息到文件
                fileBasedDeviceInfo("deviceInfo.json");
                // setLoginSolver();
                // setBotLoggerSupplier();
            }
        });

        bot.login();
        bot.getFriends().forEach(friend -> System.out.println(friend.getId() + ":" + friend.getNick()));
    }
}
`

**Comment by sandtechnology** [comment]
https://github.com/sandtechnology/DantuiHelper/blob/c0762c2b83110e63e8f9a1209bf30efd7099722f/src/main/java/sandtechnology/Mirai.java#L28
可以考虑以MD5方式登录，目前我没试过明文
https://github.com/sandtechnology/DantuiHelper/blob/c0762c2b83110e63e8f9a1209bf30efd7099722f/src/main/java/sandtechnology/config/ConfigLoader.java#L151-L162

**Comment by WuZeyue** [comment]
> https://github.com/sandtechnology/DantuiHelper/blob/c0762c2b83110e63e8f9a1209bf30efd7099722f/src/main/java/sandtechnology/Mirai.java#L28
> 可以考虑以MD5方式登录，目前我没试过明文
> https://github.com/sandtechnology/DantuiHelper/blob/c0762c2b83110e63e8f9a1209bf30efd7099722f/src/main/java/sandtechnology/config/ConfigLoader.java#L151-L162

试了，不行
`import net.mamoe.mirai.Bot;
import net.mamoe.mirai.BotFactoryJvm;
import net.mamoe.mirai.utils.BotConfiguration;

import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;

public class RobotTest{

    public static void main(String[] args){

        String password="cptbtptpbcptdtptp";
        String md5Password = null;
        try{
            MessageDigest digest = MessageDigest.getInstance("MD5");
            digest.update(password.getBytes(StandardCharsets.UTF_8));
            md5Password=new BigInteger(1,digest.digest()).toString(16);
        }catch(Exception e){
            e.printStackTrace();
        }

        final Bot bot = BotFactoryJvm.newBot(1109607743L,md5Password, new BotConfiguration() {
            {

                //保存设备信息到文件
                fileBasedDeviceInfo("deviceInfo.json");
                // setLoginSolver();
                // setBotLoggerSupplier();
            }
        });

        bot.login();
        bot.getFriends().forEach(friend -> System.out.println(friend.getId() + ":" + friend.getNick()));
    }
}
`
另外，digest()最后确定返回md5 hash值，返回值为8位字符串。因为md5 hash值是16位的hex值，实际上就是8位的字符（我搜到的这么说），BigInteger函数则将8位的字符串转换成16位hex值，用字符串来表示；得到字符串形式的hash值

**Comment by Him188** [comment]
md5登录是传 `byte[]`

**Comment by Him188** [comment]
登录在协议上不会产生问题。请检查你的账号密码等数据是否正确。

**Comment by WuZeyue** [comment]
> 登录在协议上不会产生问题。请检查你的账号密码等数据是否正确。

我用复制粘贴试过了，用QQ可以登上。是不是有什么细节文档里没写。说实话，我真想把账号密码给你们。。。
