### ISSUE TITLE
关于经常掉线问题,每天都至少会掉线2到3次

### ISSUE THREAD

**Issue by HHeyJ** [mamoe/mirai#437]
2020-07-16 10:08:01.900 ERROR 7319 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.net.SocketException: 断开的管道
        at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[na:na]
        at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1052) ~[na:na]
        at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[na:na]
        at java.base/java.io.BufferedOutputStream.write(BufferedOutputStream.java:127) ~[na:na]
        at net.mamoe.mirai.qqandroid.utils.PlatformSocket$send$4.invokeSuspend(PlatformSocket.kt:52) ~[mirai-core-qqandroid-1.1-EA.jar!/:na]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.3.61.jar!/:1.3.61-release-180 (1.3.61)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) ~[kotlinx-coroutines-core-1.3.3.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561) ~[kotlinx-coroutines-core-1.3.3.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727) ~[kotlinx-coroutines-core-1.3.3.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667) ~[kotlinx-coroutines-core-1.3.3.jar!/:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655) ~[kotlinx-coroutines-core-1.3.3.jar!/:na]

**Comment by Him188** [comment]
请附详细日志

是否有影响正常使用？

掉线后理应自动重连

**Comment by HHeyJ** [comment]
> 请附详细日志
> 
> 是否有影响正常使用？
> 
> 掉线后理应自动重连

[0m2020-07-16 05:06:24 V/Net 3420204519: Recv: Heartbeat.Alive.Response
[92m2020-07-16 05:06:48 I/Bot 3420204519: Connection dropped by server or lost, retrying login
[31m2020-07-16 05:06:48 E/Bot 3420204519: An exception was thrown under a coroutine of Bot
java.lang.NoClassDefFoundError: kotlin/time/TimeSource$Monotonic
	at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:278)
	at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invoke(BotImpl.kt)
	at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:269)
	at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
	at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:255)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$startPacketReceiverJobOrKill$2$rawInput$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:85)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Caused by: java.lang.ClassNotFoundException: kotlin.time.TimeSource$Monotonic
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:92)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more

[0m2020-07-16 05:07:24 V/Net 3420204519: Send: Heartbeat.Alive
[92m2020-07-16 05:07:34 I/Bot 3420204519: Connection dropped by server or lost, retrying login
[31m2020-07-16 05:07:34 E/Bot 3420204519: An exception was thrown under a coroutine of Bot
java.lang.NoClassDefFoundError: kotlin/time/TimeSource$Monotonic
	at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:278)
	at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invoke(BotImpl.kt)
	at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:269)
	at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
	at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:154)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
	at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:255)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$startHeartbeatJobOrKill$1$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:105)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)

2020-07-16 05:20:02.340 ERROR 7319 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

java.net.SocketException: 断开的管道
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[na:na]
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1052) ~[na:na]
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81) ~[na:na]
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142) ~[na:na]
	at net.mamoe.mirai.qqandroid.utils.PlatformSocket$send$4.invokeSuspend(PlatformSocket.kt:53) ~[mirai-core-qqandroid-1.1-EA.jar!/:na]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.3.61.jar!/:1.3.61-release-180 (1.3.61)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) ~[kotlinx-coroutines-core-1.3.3.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561) ~[kotlinx-coroutines-core-1.3.3.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727) ~[kotlinx-coroutines-core-1.3.3.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667) ~[kotlinx-coroutines-core-1.3.3.jar!/:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655) ~[kotlinx-coroutines-core-1.3.3.jar!/:na]

**Comment by HHeyJ** [comment]
> 请附详细日志
> 
> 是否有影响正常使用？
> 
> 掉线后理应自动重连

重登2次后找不到class类 socket就断开了

**Comment by Him188** [comment]
请使用 Kotlin 1.3.70+

**Comment by HHeyJ** [comment]
> 请使用 Kotlin 1.3.70+, 因 mirai 依赖 1.3.72


<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib</artifactId>
    <version>1.3.72</version>
</dependency>

是这个包么

**Comment by Him188** [comment]
是, 因为我在你给的堆栈里看到
> at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.3.61.jar!/:1.3.61-release-180 (1.3.61)]

**Comment by HHeyJ** [comment]
> 是, 因为我在你给的堆栈里看到
> 
> > at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.3.61.jar!/:1.3.61-release-180 (1.3.61)]

sure
