### ISSUE TITLE
java.lang.IllegalArgumentException: argument type mismatch

### ISSUE THREAD

**Issue by HappyOnion801** [mamoe/mirai#445]
我代码如下：
```java
Events.registerEvents(bot, new SimpleListenerHost() {
    @EventHandler
    public void listenFriendMessageEvent(@Nullable FriendMessageEvent event){
        Optional.ofNullable(event).orElseThrow(
                () -> new IllegalArgumentException("event不可为空")
        ).getSender().sendMessage("你好");
    }
});
``````
每次收到好友消息时都会出现以下异常信息：
```
2020-07-17 12:06:40 E/Bot 498861397: An exception was thrown under a coroutine of Bot
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.mamoe.mirai.event.Events__JvmMethodListenersKt$registerEvent$14$1.invokeSuspend(JvmMethodListeners.kt:350)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
版本：
```
mirai-core-1.1.2
mirai-core-qqandroid-1.1.1
jdk 11
```

**Comment by Him188** [comment]
请查看 #443  以获取修复进度
