### ISSUE TITLE
支持群外人员被群员邀请入群时向管理发送的加群申请

### ISSUE THREAD

**Issue by XeroAlpha** [mamoe/mirai#458]
无法解析subType=1,groupMsgType=22的事件，对应为か冷(2068766019)邀请.(1639374647)进群
```
[2020-07-22 12:03:50 Net E]Exception in NetworkHandlerjava.lang.IllegalStateException: 在 parse SystemMsgNewGroup, subType=1 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai. 并尽量描述此时机器人是否正被邀请加入群, 或者是有有新群员加入此群 调试信息: SystemMsg#1160932917 {
            actionUin=0x000000007B4EDD43(2068766019)
            actionUinNick=か冷
            actionUinQqNick=か冷
            actions=[SystemMsgAction#1278426797 {
                    actionInfo=SystemMsgActionInfo#80675020 {
                            blacklist=false
                            groupCode=0x00000000121A0F19(303697689)
                            type=0x0000000C(12)
                    }
                    detailName=拒绝
                    name=拒绝
                    result=已拒绝
            }, SystemMsgAction#1278426797 {
                    actionInfo=SystemMsgActionInfo#80675020 {
                            blacklist=false
                            groupCode=0x00000000121A0F19(303697689)
                            type=0x0000000B(11)
                    }
                    detailName=同意
                    name=同意
                    result=已同意
            }, SystemMsgAction#1278426797 {
                    actionInfo=SystemMsgActionInfo#80675020 {
                            blacklist=false
                            groupCode=0x00000000121A0F19(303697689)
                            type=0x0000000E(14)
                    }
                    detailName=忽略
                    name=忽略
                    result=已忽略
            }]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x00000000121A0F19(303697689)
            groupExtFlag=0x00A10040(10551360)
            groupFlagext3=0x00002000(8192)
            groupInfo=GroupInfo#1539990507 {
                    appPrivilegeFlag=0x000980D0(622800)
            }
            groupMsgType=0x00000016(22)
            groupName=MCBE命令助手反馈区
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=邀请人：%action_uin%
            msgAdditional=来自：群成员か冷的邀请
            msgDescribe=申请加入 %group_name%
            msgInviteExtinfo=MsgInviteExt#1834015663 {
                    srcCode=0x0000000000000000(0)
            }
            msgTitle=加群申请
            reqUinAge=0x00000015(21)
            reqUinNick=.
            srcId=0x00002027(8231)
            subSrcId=0x00000300(768)
            subType=0x00000001(1)
    }
	at net.mamoe.mirai.qqandroid.message.ConversionsKt.contextualBugReportException(conversions.kt:462)
	at net.mamoe.mirai.qqandroid.message.ConversionsKt.contextualBugReportException$default(conversions.kt:460)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:167)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:488)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:468)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:463)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:452)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

#### 复现
让一个群员邀请别人进群即可，记得开邀请进群需管理审核

#### 版本
mirai: `1.1.3`

建议添加一个新事件，或为 `MemberJoinRequestEvent` 增加邀请人参数，事件解析在 `net.mamoe.mirai.qqandroid.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode`

**Comment by XeroAlpha** [comment]
补充：不支持该问题似乎会影响之后的加群消息接收。日志显示，之后的收到普通的加群请求均会报与之前邀请加群相同的错误，例如：

在收到无名(593220145)的普通的加群申请时，日志中显示出现以下错误：
```
[2020-07-22 06:50:18 Net E] Exception in NetworkHandler java.lang.IllegalStateException: 在 parse SystemMsgNewGroup, subType=1 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai. 并尽量描述此时机器人是否正被邀请加入群, 或者是有有新群员加入此群 调试信息: SystemMsg#1607355038 {
            actionUin=0x000000007B4EDD43(2068766019)
            actionUinNick=か冷
            actionUinQqNick=か冷
            actions=[SystemMsgAction#173959698 {
                    actionInfo=SystemMsgActionInfo#2064825335 {
                            blacklist=false
                            groupCode=0x00000000121A0F19(303697689)
                            type=0x0000000C(12)
                    }
                    detailName=拒绝
                    name=拒绝
                    result=已拒绝
            }, SystemMsgAction#173959698 {
                    actionInfo=SystemMsgActionInfo#2064825335 {
                            blacklist=false
                            groupCode=0x00000000121A0F19(303697689)
                            type=0x0000000B(11)
                    }
                    detailName=同意
                    name=同意
                    result=已同意
            }, SystemMsgAction#173959698 {
                    actionInfo=SystemMsgActionInfo#2064825335 {
                            blacklist=false
                            groupCode=0x00000000121A0F19(303697689)
                            type=0x0000000E(14)
                    }
                    detailName=忽略
                    name=忽略
                    result=已忽略
            }]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x00000000121A0F19(303697689)
            groupExtFlag=0x00A10040(10551360)
            groupFlagext3=0x00002000(8192)
            groupInfo=GroupInfo#1525154887 {
                    appPrivilegeFlag=0x000980D0(622800)
            }
            groupMsgType=0x00000016(22)
            groupName=MCBE命令助手反馈区
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=邀请人：%action_uin%
            msgAdditional=来自：群成员か冷的邀请
            msgDescribe=申请加入 %group_name%
            msgInviteExtinfo=MsgInviteExt#489924599 {
                    srcCode=0x0000000000000000(0)
            }
            msgTitle=加群申请
            reqUinAge=0x00000015(21)
            reqUinNick=.
            srcId=0x00002027(8231)
            subSrcId=0x00000300(768)
            subType=0x00000001(1)
    }
	at net.mamoe.mirai.qqandroid.message.ConversionsKt.contextualBugReportException(conversions.kt:462)
	at net.mamoe.mirai.qqandroid.message.ConversionsKt.contextualBugReportException$default(conversions.kt:460)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:167)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:488)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:468)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:463)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:452)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
同样的错误一起出现，直至收到下一个邀请加群申请：
```
[2020-07-22 08:34:17 Net E] Exception in NetworkHandler java.lang.IllegalStateException: 在 parse SystemMsgNewGroup, subType=1 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai. 并尽量描述此时机器人是否正被邀请加入群, 或者是有有新群员加入此群 调试信息: SystemMsg#1607355038 {
            actionUin=0x00000000D1A58297(3517285015)
            actionUinNick=16岁清纯少女被他哥哥搂着打
            actionUinQqNick=????墨?白?????
            actions=[SystemMsgAction#173959698 {
                    actionInfo=SystemMsgActionInfo#2064825335 {
                            blacklist=false
                            groupCode=0x00000000121A0F19(303697689)
                            type=0x0000000C(12)
                    }
                    detailName=拒绝
                    name=拒绝
                    result=已拒绝
            }, SystemMsgAction#173959698 {
                    actionInfo=SystemMsgActionInfo#2064825335 {
                            blacklist=false
                            groupCode=0x00000000121A0F19(303697689)
                            type=0x0000000B(11)
                    }
                    detailName=同意
                    name=同意
                    result=已同意
            }, SystemMsgAction#173959698 {
                    actionInfo=SystemMsgActionInfo#2064825335 {
                            blacklist=false
                            groupCode=0x00000000121A0F19(303697689)
                            type=0x0000000E(14)
                    }
                    detailName=忽略
                    name=忽略
                    result=已忽略
            }]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x00000000121A0F19(303697689)
            groupExtFlag=0x00A10040(10551360)
            groupFlagext3=0x00002000(8192)
            groupInfo=GroupInfo#1525154887 {
                    appPrivilegeFlag=0x000980D0(622800)
            }
            groupMsgType=0x00000016(22)
            groupName=MCBE命令助手反馈区
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=邀请人：%action_uin%
            msgAdditional=来自：群成员16岁清纯少女被他哥哥搂着打的邀请
            msgDescribe=申请加入 %group_name%
            msgInviteExtinfo=MsgInviteExt#489924599 {
                    srcCode=0x0000000000000000(0)
            }
            msgTitle=加群申请
            reqUinGender=0x000000FF(255)
            reqUinNick=良宵谁与共
            subType=0x00000001(1)
    }
	at net.mamoe.mirai.qqandroid.message.ConversionsKt.contextualBugReportException(conversions.kt:462)
	at net.mamoe.mirai.qqandroid.message.ConversionsKt.contextualBugReportException$default(conversions.kt:460)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:167)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:488)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:468)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:463)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:452)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
目前尚未测试其他管理处理掉这些申请后是否会阻止这一情况的发生。但我处理掉这两个申请后，发现机器人似乎收不到新的加群申请了，这一情况待测试。

**Comment by Him188** [comment]
在记录中没有找到 1639374647.

请确认是否有误:
- Bot 是管理员
- 2068766019 是群员
- 1639374647 不是群员
- 2068766019 邀请了 1639374647 入群

**Comment by whxlxl** [comment]
2.0版本也出现了相同的错误

**Comment by sandtechnology** [comment]
> 
> 
> 2.0版本也出现了相同的错误

请提供相关的网络日志

**Comment by whxlxl** [comment]
> > 2.0版本也出现了相同的错误
> 
> 请提供相关的网络日志

2021-01-20 19:36:19 E/Net 318201913: Exception in NetworkHandler
java.lang.IllegalStateException: 在 parse SystemMsgNewGroup, subType=1 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai. 并尽量描述此时机器人是否正被邀请加入群, 或者是有有新群员加入此群 调试信息: SystemMsg#5643355 {
            actionUin=0x0000000026ECB195(653046165)
            actionUinNick=白小纯
            actionUinQqNick=白小纯
            actions=[SystemMsgAction#488122367 {
                    actionInfo=SystemMsgActionInfo#664191470 {
                            blacklist=false
                            groupCode=0x000000001E93610E(512975118)
                            type=0x0000000C(12)
                    }
                    detailName=拒绝
                    name=拒绝
                    result=已拒绝
            }, SystemMsgAction#488122367 {
                    actionInfo=SystemMsgActionInfo#664191470 {
                            blacklist=false
                            groupCode=0x000000001E93610E(512975118)
                            type=0x0000000B(11)
                    }
                    detailName=同意
                    name=同意
                    result=已同意
            }, SystemMsgAction#488122367 {
                    actionInfo=SystemMsgActionInfo#664191470 {
                            blacklist=false
                            groupCode=0x000000001E93610E(512975118)
                            type=0x0000000E(14)
                    }
                    detailName=忽略
                    name=忽略
                    result=已忽略
            }]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x000000001E93610E(512975118)
            groupExtFlag=0x40210040(1075904576)
            groupInfo=GroupInfo#2118154612 {
                    appPrivilegeFlag=0x000100D0(65744)
            }
            groupMsgType=0x00000016(22)
            groupName=会玩
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=邀请人：%action_uin%
            msgAdditional=来自：群成员白小纯的邀请
            msgDescribe=申请加入 %group_name%
            msgInviteExtinfo=MsgInviteExt#793576359 {
                    srcCode=0x0000000000000000(0)
            }
            msgTitle=加群申请
            reqUinAge=0x00000015(21)
            reqUinFaceid=0x00003A02(14850)
            reqUinGender=0x00000001(1)
            reqUinNick=蓝大大
            subType=0x00000001(1)
    }
	at net.mamoe.mirai.internal.message.ConversionsKt.contextualBugReportException(conversions.kt:641)
	at net.mamoe.mirai.internal.message.ConversionsKt.contextualBugReportException$default(conversions.kt:639)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:175)
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:507)
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:237)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:563)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:558)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:541)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by whxlxl** [comment]
> > 2.0版本也出现了相同的错误
> 
> 请提供相关的网络日志

```java
2021-01-20 19:36:19 E/Net 318201913: Exception in NetworkHandler
java.lang.IllegalStateException: 在 parse SystemMsgNewGroup, subType=1 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai. 并尽量描述此时机器人是否正被邀请加入群, 或者是有有新群员加入此群 调试信息: SystemMsg#5643355 {
            actionUin=0x0000000026ECB195(653046165)
            actionUinNick=白小纯
            actionUinQqNick=白小纯
            actions=[SystemMsgAction#488122367 {
                    actionInfo=SystemMsgActionInfo#664191470 {
                            blacklist=false
                            groupCode=0x000000001E93610E(512975118)
                            type=0x0000000C(12)
                    }
                    detailName=拒绝
                    name=拒绝
                    result=已拒绝
            }, SystemMsgAction#488122367 {
                    actionInfo=SystemMsgActionInfo#664191470 {
                            blacklist=false
                            groupCode=0x000000001E93610E(512975118)
                            type=0x0000000B(11)
                    }
                    detailName=同意
                    name=同意
                    result=已同意
            }, SystemMsgAction#488122367 {
                    actionInfo=SystemMsgActionInfo#664191470 {
                            blacklist=false
                            groupCode=0x000000001E93610E(512975118)
                            type=0x0000000E(14)
                    }
                    detailName=忽略
                    name=忽略
                    result=已忽略
            }]
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x000000001E93610E(512975118)
            groupExtFlag=0x40210040(1075904576)
            groupInfo=GroupInfo#2118154612 {
                    appPrivilegeFlag=0x000100D0(65744)
            }
            groupMsgType=0x00000016(22)
            groupName=会玩
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=邀请人：%action_uin%
            msgAdditional=来自：群成员白小纯的邀请
            msgDescribe=申请加入 %group_name%
            msgInviteExtinfo=MsgInviteExt#793576359 {
                    srcCode=0x0000000000000000(0)
            }
            msgTitle=加群申请
            reqUinAge=0x00000015(21)
            reqUinFaceid=0x00003A02(14850)
            reqUinGender=0x00000001(1)
            reqUinNick=蓝大大
            subType=0x00000001(1)
    }
	at net.mamoe.mirai.internal.message.ConversionsKt.contextualBugReportException(conversions.kt:641)
	at net.mamoe.mirai.internal.message.ConversionsKt.contextualBugReportException$default(conversions.kt:639)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:175)
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:507)
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:237)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:563)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:558)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:541)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

**Comment by sandtechnology** [comment]
@Him188

**Comment by ryoii** [comment]
补充subType
