### ISSUE TITLE
无法正常获取到某些图床的图片

### ISSUE THREAD

**Issue by Reshirem** [mamoe/mirai#469]
- [x ] 我已经对照 CHANGELOG ，相关问题未在近期更新中解决
- [x ] 我已经搜索了已有的 Issues 列表中有没相关的信息
- [x ] 我已经阅读了 Mirai 的相关文档

搭配`cqhttp-mirai`发送`sm.ms`图床的图片时，mirai无法获取到图片，正常浏览器访问是能访问的，疑似是header缺少或不对导致。
```
 09:59:51 [ERROR] [CQHTTPMirai] java.io.IOException: Server returned HTTP response code: 403 for URL: https://vip1.loli.net/2020/01/16/bYkSDotufTnAwX6.jpg
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at net.mamoe.mirai.utils.FileCacheStrategy$TempCache.newImageCache(FileCacheStrategy.jvm.kt:183)
        at net.mamoe.mirai.utils.FileCacheStrategy$PlatformDefault.newImageCache(FileCacheStrategy.jvm.kt)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput$init$3.invokeSuspend(DeferredReusableInput.jvm.kt:27)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput$init$3.invoke(DeferredReusableInput.jvm.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.utils.internal.DeferredReusableInput.init(DeferredReusableInput.jvm.kt:19)
        at net.mamoe.mirai.qqandroid.contact.FriendImpl.uploadImage(FriendImpl.kt:99)
        at net.mamoe.mirai.utils.ExternalImageKt.upload(ExternalImage.kt:107)
        at net.mamoe.mirai.message.SendImageUtilsJvmKt.uploadAsImage(SendImageUtilsJvm.kt:95)
        at tech.mihoyo.mirai.util.CQMessgeParserKt$convertToMiraiMessage$$inlined$with$lambda$2.invokeSuspend(CQMessgeParser.kt:314)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
![image](https://user-images.githubusercontent.com/12333564/88496619-58f87500-cff0-11ea-9de3-3a77947b2f94.png)

**Comment by ryoii** [comment]
反爬问题，mirai提供基本的url图片下载，不提供反反爬功能
尝试自行下载通过文件发送图片

**Comment by mzdluo123** [comment]
请自行实现图片下载以适应不同图床的安全规则。此issue与mirai无关
