### ISSUE TITLE
Network Protocol: java.lang.IllegalStateException: returnCode = -10008

### ISSUE THREAD

**Issue by qianjunakasumi** [mamoe/mirai#470]
- [x ] 我已经对照 CHANGELOG ，相关问题未在近期更新中解决
- [x ] 我已经搜索了已有的 Issues 列表中有没相关的信息
- [x ] 我已经阅读了 Mirai 的相关文档

发送消息时遇到问题

* 2020年7月26日5：00整点发送消息失败
* 失败后 HTTP API 返回正常状态码

主要
```
 05:00:00 [INFO] [NETWORK] Exception in NetworkHandler
 05:00:00 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: returnCode = -10008
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:305)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:214)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

 05:00:05 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 05:00:05 [INFO] [NETWORK] Exception in NetworkHandler
 05:00:05 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: returnCode = -10008
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:305)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:214)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

 05:00:10 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 05:00:10 [INFO] [NETWORK] Exception in NetworkHandler
 05:00:10 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: returnCode = -10008
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:305)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:214)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

 05:00:15 [ERROR] [MiraiAPIHTTP] kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:158)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:128)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
        at java.lang.Thread.run(Thread.java:748)

 05:00:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:00:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:01:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:01:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:02:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:02:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:03:35 [INFO] [BOT 21******79] Connection dropped by server or lost, retrying login
 05:03:35 [INFO] [NETWORK] Connected to server 114.221.148.59:14000
 05:03:35 [INFO] [NETWORK] Send: wtlogin.login
 05:03:35 [INFO] [NETWORK] Recv: LoginPacketResponse.Success
 05:03:35 [INFO] [NETWORK] Login successful
```

生产事故前后半小时
```
 04:30:04 [INFO] [BOT 21******79] Connection dropped by server or lost, retrying login
 04:30:05 [INFO] [NETWORK] Connected to server 125.94.60.146:80
 04:30:05 [INFO] [NETWORK] Send: wtlogin.login
 04:30:05 [INFO] [NETWORK] Recv: LoginPacketResponse.Success
 04:30:05 [INFO] [NETWORK] Login successful
 04:30:05 [INFO] [NETWORK] Send: StatSvc.register
 04:30:05 [INFO] [NETWORK] Recv: Response(StatSvc.register)
 04:30:05 [INFO] [BOT 21******79] Reconnected successfully in 0.232s
 04:30:05 [INFO] [NETWORK] Syncing friend message history...
 04:30:05 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 04:30:05 [INFO] [NETWORK] Syncing friend message history: Success
 04:30:08 [INFO] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 04:30:08 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
 04:30:08 [INFO] [NETWORK] Received unknown commandName: ConfigPushSvc.PushDomain
 04:30:08 [INFO] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 04:30:08 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
 04:30:58 [INFO] [NETWORK] Send: OnlinePush.RespPush
 04:31:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:31:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:31:06 [INFO] [NETWORK] Send: OnlinePush.RespPush
 04:32:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:32:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:33:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:33:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:34:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:34:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:35:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:35:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:36:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:36:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:37:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:37:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:38:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:38:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:39:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:39:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:40:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:40:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:41:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:41:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:42:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:42:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:43:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:43:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:44:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:44:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:45:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:45:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:46:05 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:46:05 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:46:50 [INFO] [BOT 21******79] Connection dropped by server or lost, retrying login
 04:46:50 [INFO] [NETWORK] Connected to server 114.221.148.59:14000
 04:46:50 [INFO] [NETWORK] Send: wtlogin.login
 04:46:50 [INFO] [NETWORK] Recv: LoginPacketResponse.Success
 04:46:50 [INFO] [NETWORK] Login successful
 04:46:50 [INFO] [NETWORK] Send: StatSvc.register
 04:46:50 [INFO] [NETWORK] Recv: Response(StatSvc.register)
 04:46:50 [INFO] [BOT 21******79] Reconnected successfully in 0.439s
 04:46:50 [INFO] [NETWORK] Syncing friend message history...
 04:46:50 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 04:46:50 [INFO] [NETWORK] Syncing friend message history: Success
 04:46:53 [INFO] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 04:46:53 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
 04:46:53 [INFO] [NETWORK] Received unknown commandName: ConfigPushSvc.PushDomain
 04:46:53 [INFO] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 04:46:53 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
 04:47:50 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:47:50 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:48:50 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:48:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:49:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:49:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:50:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:50:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:51:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:51:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:52:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:52:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:53:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:53:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:54:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:54:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:55:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:55:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:56:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:56:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:57:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:57:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:58:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:58:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 04:59:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 04:59:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:00:00 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 05:00:00 [INFO] [NETWORK] Exception in NetworkHandler
 05:00:00 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: returnCode = -10008
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:305)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:214)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

 05:00:05 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 05:00:05 [INFO] [NETWORK] Exception in NetworkHandler
 05:00:05 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: returnCode = -10008
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:305)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:214)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

 05:00:10 [INFO] [NETWORK] Send: MessageSvc.PbSendMsg
 05:00:10 [INFO] [NETWORK] Exception in NetworkHandler
 05:00:10 [INFO] [NETWORK ERROR] java.lang.IllegalStateException: returnCode = -10008
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:305)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:214)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

 05:00:15 [ERROR] [MiraiAPIHTTP] kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:158)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:128)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
        at java.lang.Thread.run(Thread.java:748)

 05:00:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:00:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:01:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:01:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:02:51 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:02:51 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:03:35 [INFO] [BOT 21******79] Connection dropped by server or lost, retrying login
 05:03:35 [INFO] [NETWORK] Connected to server 114.221.148.59:14000
 05:03:35 [INFO] [NETWORK] Send: wtlogin.login
 05:03:35 [INFO] [NETWORK] Recv: LoginPacketResponse.Success
 05:03:35 [INFO] [NETWORK] Login successful
 05:03:35 [INFO] [NETWORK] Send: StatSvc.register
 05:03:35 [INFO] [NETWORK] Recv: Response(StatSvc.register)
 05:03:35 [INFO] [BOT 21******79] Reconnected successfully in 0.467s
 05:03:35 [INFO] [NETWORK] Syncing friend message history...
 05:03:35 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 05:03:35 [INFO] [NETWORK] Syncing friend message history: Success
 05:03:38 [INFO] [NETWORK] Received unknown commandName: ConfigPushSvc.PushDomain
 05:03:38 [INFO] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 05:03:38 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
 05:04:35 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:04:35 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:05:35 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:05:35 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:06:35 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:06:35 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:07:35 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:07:35 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:08:35 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:08:35 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:09:35 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:09:35 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:10:35 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:10:35 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:11:35 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:11:35 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:12:35 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:12:35 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:13:35 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:13:35 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:14:35 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:14:36 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:15:36 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:15:36 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:16:36 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:16:36 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:17:36 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:17:36 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:18:36 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:18:36 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:19:36 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:19:36 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:20:20 [INFO] [BOT 21******79] Connection dropped by server or lost, retrying login
 05:20:20 [INFO] [NETWORK] Connected to server 42.81.172.22:80
 05:20:20 [INFO] [NETWORK] Send: wtlogin.login
 05:20:20 [INFO] [NETWORK] Recv: LoginPacketResponse.Success
 05:20:20 [INFO] [NETWORK] Login successful
 05:20:20 [INFO] [NETWORK] Send: StatSvc.register
 05:20:20 [INFO] [NETWORK] Recv: Response(StatSvc.register)
 05:20:20 [INFO] [BOT 21******79] Reconnected successfully in 0.405s
 05:20:20 [INFO] [NETWORK] Syncing friend message history...
 05:20:20 [INFO] [NETWORK] Send: MessageSvc.PbGetMsg
 05:20:20 [INFO] [NETWORK] Syncing friend message history: Success
 05:20:23 [INFO] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 05:20:23 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
 05:20:23 [INFO] [NETWORK] Received unknown commandName: ConfigPushSvc.PushDomain
 05:20:23 [INFO] [NETWORK] Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
 05:20:23 [INFO] [NETWORK] Send: ConfigPushSvc.PushResp
 05:21:20 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:21:20 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:22:20 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:22:20 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:23:20 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:23:20 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:24:20 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:24:20 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:25:20 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:25:20 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:26:20 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:26:20 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:27:20 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:27:20 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:28:20 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:28:20 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
 05:29:20 [INFO] [NETWORK] Send: Heartbeat.Alive
 05:29:20 [INFO] [NETWORK] Recv: Heartbeat.Alive.Response
```

#### 复现

未重启MiraiOK，第二天同一时刻消息发送正常

不知晓问题发生的原因，暂无法复现。

#### 版本
mirai: `1.3.0 ` 

```
mirai-console-wrapper-1.3.0
mirai-console-0.5.2
mirai-core-qqandroid-1.0.3
MiraiOK 20200629.160938 running at windows-amd64
```

**Comment by qianjunakasumi** [comment]
使用HTTP API 插件`mirai-api-http-v1.7.3`

**Comment by Him188** [comment]
这个问题是服务器因某种原因拒绝了客户端的通信, mirai 应处理这种情况并及时重连

**Comment by Him188** [comment]
解决方法 (for mamoe): 在 `net/mamoe/mirai/qqandroid/network/protocol/packet/PacketFactory.kt:308` 抛出一个特定的异常并由上层调用方捕获, 然后广播一个新的 `net.mamoe.mirai.event.events.BotOfflineEvent` 以触发重连. 需要新增一个 `BotOfflineEvent` 的子类.

**Comment by mzdluo123** [comment]
我也遇到了这个问题，在某些情况导致强制下线（例如在手机QQ强制下线机器人）时程序并不会退出而是继续保持心跳但不会收到消息
