### ISSUE TITLE
无法重连

### ISSUE THREAD

**Issue by mzdluo123** [mamoe/mirai#473]
```
 17:42:09 [INFO] [NETWORK] Send: wtlogin.login
 17:42:14 [INFO] [NETWORK] Send: wtlogin.login
 17:42:19 [INFO] [NETWORK] Send: wtlogin.login
 17:42:24 [INFO] [NETWORK ERROR] kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:158)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:128)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
        at java.base/java.lang.Thread.run(Thread.java:834)

 17:42:24 [INFO] [NETWORK] Connected to server 114.221.144.215:80
 17:42:24 [INFO] [NETWORK] Send: wtlogin.login
 17:42:29 [INFO] [NETWORK] Send: wtlogin.login
 17:42:34 [INFO] [NETWORK] Send: wtlogin.login
 17:42:39 [INFO] [NETWORK ERROR] kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:158)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:128)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
        at java.base/java.lang.Thread.run(Thread.java:834)

 17:42:39 [INFO] [BOT 1023718443] Cannot reconnect.
 17:42:39 [INFO] [NETWORK ERROR] net.mamoe.mirai.network.NoServerAvailableException: no server available
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.relogin$suspendImpl(QQAndroidBot.common.kt:943)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase$relogin$1.invokeSuspend(QQAndroidBot.common.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:158)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:128)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
        at java.base/java.lang.Thread.run(Thread.java:834)

 17:42:39 [INFO] [BOT 1023718443] Retrying in 3s...
 17:42:42 [INFO] [NETWORK] Connected to server 114.221.148.59:14000
 17:42:42 [INFO] [NETWORK] Send: wtlogin.login
 17:42:47 [INFO] [NETWORK] Send: wtlogin.login
 17:42:52 [INFO] [NETWORK] Send: wtlogin.login
 17:42:57 [INFO] [NETWORK ERROR] kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:158)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:128)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
        at java.base/java.lang.Thread.run(Thread.java:834)

 17:42:57 [INFO] [NETWORK] Connected to server 114.221.144.215:80
 17:42:57 [INFO] [NETWORK] Send: wtlogin.login
 17:43:02 [INFO] [NETWORK] Send: wtlogin.login

```

确认不是网络问题，但是重启程序能够正常使用，这是我的第二台服务器出现这样的问题了

**Comment by Him188** [comment]
需要版本号和全面的日志（从掉线开始）

**Comment by takayama-lily** [comment]
![`P2}Y$QR7{)ERH(B$PW07(O](https://user-images.githubusercontent.com/12014361/90338926-15f65400-e028-11ea-9672-8a9a20c86ed6.png)
v1.1.3
断线重连后成功后，马上又显示断线。
然后显示在0秒内重连成功。
之后其实bot已经掉线，收不到任何消息。

**Comment by Him188** [comment]
难以找到原因, 故推迟

**Comment by skqszy123** [comment]
出现相同问题

**Comment by Him188** [comment]
应该只是网络不好? 服务器 5s 都没有相应也办法
