### ISSUE TITLE
群聊中艾特人数较多时报错

### ISSUE THREAD

**Issue by Jovines** [mamoe/mirai#539]
```

java.lang.IllegalStateException: Send group message failed: MessageSvcPbSendMsg.Response.Failed(resultType=34, errorCode=0, errorMessage=)
	at net.mamoe.mirai.qqandroid.contact.GroupImpl.sendMessageImpl(GroupImpl.kt:369)
	at net.mamoe.mirai.qqandroid.contact.GroupImpl$sendMessageImpl$1.invokeSuspend(GroupImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


```

#### 版本
mirai: `1.2.2 `

**Comment by Jovines** [comment]
需求是：机器人是链接了学校一个打卡的平台，需要特定时间段在群聊中公示并艾特到具体的人

**Comment by Him188** [comment]
请提供复现消息内容

**Comment by yyuueexxiinngg** [comment]
此Issue或与帐号, 网络环境等有关, `cqhttp-mirai`那边也有人提此Issue

https://github.com/yyuueexxiinngg/cqhttp-mirai/issues/66
> 第15个人开始报错，第14个人换成任意成员都可以成功


我自己测试时`Bot`在At 15人及以上时可复现, `log`与本Issue相同, 但同样版本请其他群友测试却可以正常发送

**Comment by Him188** [comment]
可能需要按长消息，或者分片发送？需要调查

**Comment by ryoii** [comment]
应该是对At消息的长度估计有误，现在是单纯按照群名片计算的
