### ISSUE TITLE
Bot在Close时不接收消息则无法退出

### ISSUE THREAD

**Issue by ForteScarlet** [mamoe/mirai#557]
当Bot登录后并执行`closeAndJoin`的时候，如果这个bot没有接收任何消息（测试为群消息与私信消息）则其无法关闭。

测试代码：
```kotlin
    val bot = Bot(111, "********").alsoLogin()

    TimeUnit.SECONDS.sleep(10)

    println("do close...")

    bot.closeAndJoin()

    println("closed.")

```

日志参考：
```
2020-08-30 01:39:23 I/Bot 2370606773: Logging in...
2020-08-30 01:39:23 I/Net 2370606773: Connected to server msfwifi.3g.qq.com:8080
2020-08-30 01:39:23 V/Net 2370606773: Send: wtlogin.login
2020-08-30 01:39:23 V/Net 2370606773: Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
2020-08-30 01:39:23 V/Net 2370606773: Send: wtlogin.login
2020-08-30 01:39:23 V/Net 2370606773: Recv: LoginPacketResponse.Success
2020-08-30 01:39:23 I/Net 2370606773: Login successful
2020-08-30 01:39:23 V/Net 2370606773: Send: StatSvc.register
2020-08-30 01:39:24 V/Net 2370606773: Recv: Response(StatSvc.register)
2020-08-30 01:39:24 I/Net 2370606773: 开始加载好友信息
2020-08-30 01:39:24 I/Net 2370606773: 开始加载群组列表与群成员列表
2020-08-30 01:39:24 V/Net 2370606773: Send: friendlist.getFriendGroupList
2020-08-30 01:39:24 V/Net 2370606773: Send: friendlist.GetTroopListReqV2
2020-08-30 01:39:24 V/Net 2370606773: Recv: FriendList.GetFriendGroupList.Response
2020-08-30 01:39:24 V/Net 2370606773: Recv: FriendList.GetFriendGroupList.Response
2020-08-30 01:39:24 V/Net 2370606773: 正在加载好友列表 6/6
2020-08-30 01:39:24 I/Net 2370606773: 好友列表加载完成, 共 6个
2020-08-30 01:39:24 V/Net 2370606773: Send: OidbSvc.0x88d_7
2020-08-30 01:39:24 V/Net 2370606773: Send: OidbSvc.0x88d_7
2020-08-30 01:39:24 V/Net 2370606773: Send: OidbSvc.0x88d_7
2020-08-30 01:39:24 V/Net 2370606773: Send: OidbSvc.0x88d_7
2020-08-30 01:39:24 V/Net 2370606773: Send: friendlist.GetTroopMemberListReq
2020-08-30 01:39:24 V/Net 2370606773: Send: friendlist.GetTroopMemberListReq
2020-08-30 01:39:24 V/Net 2370606773: Send: friendlist.GetTroopMemberListReq
2020-08-30 01:39:24 V/Net 2370606773: Send: friendlist.GetTroopMemberListReq
2020-08-30 01:39:24 V/Net 2370606773: Recv: FriendList.GetTroopMemberList.Response
2020-08-30 01:39:24 V/Net 2370606773: Recv: FriendList.GetTroopMemberList.Response
2020-08-30 01:39:24 V/Net 2370606773: Recv: FriendList.GetTroopMemberList.Response
2020-08-30 01:39:24 V/Net 2370606773: Recv: FriendList.GetTroopMemberList.Response
2020-08-30 01:39:24 I/Net 2370606773: 群组列表与群成员加载完成, 共 4个
2020-08-30 01:39:24 I/Net 2370606773: Awaiting ConfigPushSvc.PushReq
2020-08-30 01:39:24 I/Net 2370606773: Syncing friend message history...
2020-08-30 01:39:24 V/Net 2370606773: Send: MessageSvc.PbGetMsg
2020-08-30 01:39:24 V/Net 2370606773: Send: MessageSvc.PbDeleteMsg
2020-08-30 01:39:24 I/Net 2370606773: Syncing friend message history: Success
2020-08-30 01:39:24 I/Bot 2370606773: Login successful
2020-08-30 01:39:27 D/Net 2370606773: Received unknown commandName: ConfigPushSvc.PushDomain
2020-08-30 01:39:27 V/Net 2370606773: Recv: ConfigPushSvc.PushReq.PushReqResponse.Success
2020-08-30 01:39:27 V/Net 2370606773: Send: ConfigPushSvc.PushResp
2020-08-30 01:39:27 I/Net 2370606773: ConfigPushSvc.PushReq: Success
do close...
```
`do close...`后，收到消息前会一直阻塞。

请问有什么办法能够解决这个问题吗？

**Comment by Him188** [comment]
For mamoe:
```
val bot = Bot(qq, password) {
    fileBasedDeviceInfo()
}.alsoLogin()
println("Close...")
bot.closeAndJoin()
println("Close OK")
```

测试正常

**Comment by Him188** [comment]
For mamoe: 
```
val bot = Bot(qq, password) {
    fileBasedDeviceInfo()
}.alsoLogin()
delay(5.seconds)
println("Close...")
bot.closeAndJoin()
println("Close OK")
```

阻塞直到收到好友消息或群消息

**Comment by Him188** [comment]
Coroutine dump:
```
Coroutines dump 2020/09/15 10:08:35

Coroutine kotlin.coroutines.jvm.internal.RunSuspend@7caa69cf, state: SUSPENDED
	at net.mamoe.mirai.qqandroid.MKt.main(m.kt:101)
	(Coroutine creation stacktrace)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:87)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at net.mamoe.mirai.qqandroid.MKt.main(m.kt)

Coroutine StandaloneCoroutine{Active}@4fc7a960, state: SUSPENDED
	at io.ktor.network.selector.ActorSelectorManager.receiveOrNullSuspend(ActorSelectorManager.kt:164)
	at io.ktor.network.selector.ActorSelectorManager.receiveOrNull(ActorSelectorManager.kt:154)
	at io.ktor.network.selector.ActorSelectorManager.process(ActorSelectorManager.kt:87)
	at io.ktor.network.selector.ActorSelectorManager$1.invokeSuspend(ActorSelectorManager.kt:45)
	(Coroutine creation stacktrace)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:122)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at io.ktor.network.selector.ActorSelectorManager.<init>(ActorSelectorManager.kt:40)
	at io.ktor.network.selector.SelectorManagerKt.SelectorManager(SelectorManager.kt:15)
	at io.ktor.client.engine.cio.CIOEngine$selectorManager$2.invoke(CIOEngine.kt:33)
	at io.ktor.client.engine.cio.CIOEngine$selectorManager$2.invoke(CIOEngine.kt:21)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.ktor.client.engine.cio.CIOEngine.getSelectorManager(CIOEngine.kt)
	at io.ktor.client.engine.cio.CIOEngine.<init>(CIOEngine.kt:35)
	at io.ktor.client.engine.cio.CIO.create(CIOCommon.kt:23)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:40)
	at io.ktor.client.HttpClientKt.HttpClient$default(HttpClient.kt:37)
	at net.mamoe.mirai.qqandroid.utils.MiraiPlatformUtils.<clinit>(MiraiPlatformUtils.kt:86)
	at net.mamoe.mirai.qqandroid.BotAccount.<init>(BotAccount.kt:26)
	at net.mamoe.mirai.qqandroid.QQAndroid.newBot(QQAndroid.kt:31)
	at net.mamoe.mirai.qqandroid.MKt.main(m.kt:98)
	at net.mamoe.mirai.qqandroid.MKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at net.mamoe.mirai.qqandroid.MKt.main(m.kt)

Coroutine StandaloneCoroutine{Active}@2c6d817d, state: SUSPENDED
	at io.ktor.client.engine.cio.CIOEngine$1.invokeSuspend(CIOEngine.kt:62)
	(Coroutine creation stacktrace)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:122)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:129)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at io.ktor.client.engine.cio.CIOEngine.<init>(CIOEngine.kt:60)
	at io.ktor.client.engine.cio.CIO.create(CIOCommon.kt:23)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:40)
	at io.ktor.client.HttpClientKt.HttpClient$default(HttpClient.kt:37)
	at net.mamoe.mirai.qqandroid.utils.MiraiPlatformUtils.<clinit>(MiraiPlatformUtils.kt:86)
	at net.mamoe.mirai.qqandroid.BotAccount.<init>(BotAccount.kt:26)
	at net.mamoe.mirai.qqandroid.QQAndroid.newBot(QQAndroid.kt:31)
	at net.mamoe.mirai.qqandroid.MKt.main(m.kt:98)
	at net.mamoe.mirai.qqandroid.MKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at net.mamoe.mirai.qqandroid.MKt.main(m.kt)

Coroutine StandaloneCoroutine{Cancelling}@56fb7f72, state: RUNNING
	at java.base@14.0.1/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base@14.0.1/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:46)
	at java.base@14.0.1/sun.nio.ch.NioSocketImpl.tryRead(NioSocketImpl.java:261)
	at java.base@14.0.1/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:312)
	at java.base@14.0.1/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base@14.0.1/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base@14.0.1/java.net.Socket$SocketInputStream.read(Socket.java:982)
	at java.base@14.0.1/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base@14.0.1/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base@14.0.1/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at app//kotlinx.io.streams.StreamsKt.readPacketImpl(Streams.kt:60)
	at app//kotlinx.io.streams.StreamsKt.readPacketAtMost(Streams.kt:46)
	at app//net.mamoe.mirai.qqandroid.utils.PlatformSocket$read$3.invokeSuspend(PlatformSocket.kt:76)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$startPacketReceiverJobOrKill$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:83)
	(Coroutine creation stacktrace)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:122)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.startPacketReceiverJobOrKill(QQAndroidBotNetworkHandler.kt:80)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:154)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:250)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

Coroutine StandaloneCoroutine{Active}@79308073, state: RUNNING
	at java.base/java.lang.Thread.getStackTrace(Thread.java:1598)
	at kotlinx.coroutines.debug.internal.DebugProbesImpl.enhanceStackTraceWithThreadDumpImpl(DebugProbesImpl.kt:239)
	at kotlinx.coroutines.debug.internal.DebugProbesImpl.dumpCoroutinesSynchronized(DebugProbesImpl.kt:194)
	at kotlinx.coroutines.debug.internal.DebugProbesImpl.dumpCoroutines(DebugProbesImpl.kt:183)
	at kotlinx.coroutines.debug.DebugProbes.dumpCoroutines(DebugProbes.kt:144)
	at kotlinx.coroutines.debug.DebugProbes.dumpCoroutines$default(DebugProbes.kt:144)
	at net.mamoe.mirai.qqandroid.MKt$main$2.invokeSuspend(m.kt:45)
	(Coroutine creation stacktrace)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt.createCoroutineUnintercepted(IntrinsicsJvm.kt:122)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:26)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at net.mamoe.mirai.qqandroid.MKt.main(m.kt:43)
	at net.mamoe.mirai.qqandroid.MKt$main$1.invokeSuspend(m.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:250)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by Him188** [comment]
经调查, 发现是网络层在阻塞读取:
```kotlin
    actual suspend fun read(): ByteReadPacket {
        return withContext(Dispatchers.IO) {
            try {
                readChannel.readPacketAtMost(Long.MAX_VALUE) // BLOCKING HERE
            } catch (e: IOException) {
                throw ReadPacketInternalException(e)
            }
        }
    }
```
