### ISSUE TITLE
打包后出现NoClassDefFoundError错误

### ISSUE THREAD

**Issue by 1847757288** [mamoe/mirai#558]
从网上翻了一堆idea打包项目成jar的教程，最后总是报出NoClassDefFoundError
```
C:\Users\Administrator>java -jar C:\Users\Administrator\Desktop\机器人\build\libs\test1-1.0-SNAPSHOT.jar
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
        at net.mamoe.mirai.Run.Main$Companion.main(Main.kt)
        at net.mamoe.mirai.Run.Main.main(Main.kt)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more

```
在idea里都可以正常运行的。。

**Comment by Him188** [comment]
这是正常现象。
请不要在不熟悉这方面的情况下打包。
使用 https://github.com/project-mirai/mirai-repo

**Comment by Alceatraz** [comment]
> 从网上翻了一堆idea打包项目成jar的教程，最后总是报出NoClassDefFoundError
> 
> ```
> C:\Users\Administrator>java -jar C:\Users\Administrator\Desktop\机器人\build\libs\test1-1.0-SNAPSHOT.jar
> Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
>         at net.mamoe.mirai.Run.Main$Companion.main(Main.kt)
>         at net.mamoe.mirai.Run.Main.main(Main.kt)
> Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
>         at java.net.URLClassLoader.findClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
>         at java.lang.ClassLoader.loadClass(Unknown Source)
>         ... 2 more
> ```
> 
> 在idea里都可以正常运行的。。

mirai打包成功以后貌似和普通jar不太一样，我实验结果：使用classpath加载所有依赖的jar，自己的代码打包成不含库的状态
```shell
java -cp mirai.jar;mirai.jar;xxx.jar;myapp.jar full.qualified.name.to.main.class
```
