### ISSUE TITLE
企业QQ无法登陆

### ISSUE THREAD

**Issue by chi1216** [mamoe/mirai#564]
企业QQ无法登陆，我确定账号密码无误。

![image](https://user-images.githubusercontent.com/46589416/91865150-0cb5ea00-ecac-11ea-8561-7cc5635f2175.png)

```
[0m2020-09-01 23:36:45 V/Net 3008550958: Recv: Error(title=禁止登录, message=帐号不存在或因安全问题登录受限，请联系当地经销商/官网客服处理。, errorInfo=)
Exception in thread "main" net.mamoe.mirai.network.WrongPasswordException: Error(title=禁止登录, message=帐号不存在或因 安全问题登录受限，请联系当地经销商/官网客服处理。, errorInfo=)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:180)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.BotJavaFriendlyAPI$DefaultImpls.login(BotJavaFriendlyAPI.kt:202)
        at net.mamoe.mirai.Bot.login(Bot.kt:50)
        at ai.start.AI.main(AI.java:76)


```

#### 复现

任何时候

#### 版本
mirai: `1.2.0 `

**Comment by Him188** [comment]
你可以使用普通 QQ 账号. mirai 并不支持商业活动. 企业 QQ 即使要支持, 也不可能在近几年内完成.
