### ISSUE TITLE
新成员入群后报错

### ISSUE THREAD

**Issue by xszqxszq** [mamoe/mirai#567]
新成员入群后发送消息之后后台报错。推测为新成员入群后未被加入GroupMessageEvent.sender.group.members

```
2020-09-03 11:58:54 V/Net 2262349573: Send: OnlinePush.RespPush
2020-09-03 11:58:54 V/Net 2262349573: Send: OnlinePush.RespPush
2020-09-03 11:58:54 V/Net 2262349573: Recv: net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPushNotify@43924297
2020-09-03 11:58:54 V/Net 2262349573: Send: MessageSvc.PbGetMsg
2020-09-03 11:58:54 V/Net 2262349573: Send: MessageSvc.PbDeleteMsg
2020-09-03 11:58:55 V/Net 2262349573: Send: Heartbeat.Alive
2020-09-03 11:58:55 V/Net 2262349573: Recv: Heartbeat.Alive.Response
2020-09-03 11:59:00 E/Net 2262349573: Exception in NetworkHandler
java.util.NoSuchElementException: member 2590668640 not found in group 2153826545
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:277)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePushPbPushGroupMsg.decode(OnlinePush.PbPushGroupMsg.kt:80)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:501)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:237)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:485)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:480)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:463)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-09-03 11:59:02 V/Net 2262349573: Send: OnlinePush.RespPush
2020-09-03 11:59:02 V/Net 2262349573: Send: OnlinePush.RespPush
2020-09-03 11:59:06 E/Net 2262349573: Exception in NetworkHandler
java.util.NoSuchElementException: member 2590668640 not found in group 2153826545
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:277)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePushPbPushGroupMsg.decode(OnlinePush.PbPushGroupMsg.kt:80)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:501)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:237)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:485)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:480)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:463)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-09-03 11:59:55 V/Net 2262349573: Send: Heartbeat.Alive
2020-09-03 11:59:55 V/Net 2262349573: Recv: Heartbeat.Alive.Response
```

#### 复现

1. 新成员在程序启动后主动加入机器人所在群
2. 新成员发送任意消息（文字或图片）
3. 此时终端中会报错
#### 版本
mirai: ` 1.2.2`

**Comment by mzdluo123** [comment]
请问是任何加群方式都这样吗？该问题出现的概率有多少？出现问题的加群方式是什么？

**Comment by Him188** [comment]
同步好友消息的那个包也附带一些入群请求。我判断是 sync 错误。

**Comment by xszqxszq** [comment]
1. 邀请入群无报错（有提示Event: MemberJoinEvent.Active(member=***)），群允许直接加入时也无报错，但若群设置了“需要正确回答验证问题”或“需要回答问题并由管理员审核”则会出现。抱歉刚刚没有发现。
2. 今天才发现此情况，刚刚多次尝试中约一半出现该问题
3. 均为主动加群，在测试的两个群中分别设置了“需要正确回答验证问题”或“需要回答问题并由管理员审核”。

**Comment by Him188** [comment]
已确认, 此问题有非常大的概率是由  `MessageSvcPbGetMsg` sync 问题引起
