### ISSUE TITLE
登录强制要求“请使用QQ一键登录（通过手机QQ授权登录）”应该如何解决？

### ISSUE THREAD

**Issue by VonXXGhost** [mamoe/mirai#570]
之前两个月没更新，今天更新到1.2.2后进行测试，发现登录都登录不上去。无论在手机qq上是否打开了登录设备验证都报以下同样的错误，登录时也没有弹出验证窗口啥的。

相关代码：
```
val bot = Bot(qqId, password) {
        botLoggerSupplier = { SkgBotLogger("skgBotMirai") }
        networkLoggerSupplier = { SkgBotLogger("skgBotMiraiNet") }
        protocol = BotConfiguration.MiraiProtocol.ANDROID_PHONE
        deviceInfo =
            {
                File("device.json")
                    .loadAsDeviceInfo(Json { prettyPrint = true })
            }
        loginSolver = NotifyLoginSolver()
    }.alsoLogin()
```

日志：
```
[INFO ] [2020-09-03 23:41:03][skgBotMirai]: Logging in...
[INFO ] [2020-09-03 23:41:03][skgBotMiraiNet]: Connected to server msfwifi.3g.qq.com:8080
[TRACE] [2020-09-03 23:41:03][skgBotMiraiNet]: Send: wtlogin.login
[TRACE] [2020-09-03 23:41:04][skgBotMiraiNet]: Recv: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)
Exception in thread "main" net.mamoe.mirai.network.WrongPasswordException: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        ……
```

**Comment by mzdluo123** [comment]
请检查你的账号安全设置或是使用平板协议

**Comment by kasuganosoras** [comment]
我登录也是这个错误，最终研究出了解决方法，就是先用平板QQ协议登录，登录后再切换为手机QQ协议即可，希望能帮到有同样问题的人。
