### ISSUE TITLE
今天重启发现报了3个错误，想请问下是为是自身网络原因

### ISSUE THREAD

**Issue by HHeyJ** [mamoe/mirai#583]
- 我已经对照 CHANGELOG ，相关问题未在近期更新中解决
  - 我已经搜索了已有的 Issues 列表中有没相关的信息
  - 我已经阅读了 Mirai 的相关文档

2020-09-10 10:45:07 I/Bot 3625889100: Cannot reconnect.
2020-09-10 10:45:07 W/Bot 3625889100: net.mamoe.mirai.network.NoServerAvailableException: no server available
net.mamoe.mirai.network.NoServerAvailableException: no server available
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.relogin$suspendImpl(QQAndroidBot.common.kt:915)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase$relogin$1.invokeSuspend(QQAndroidBot.common.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Caused by: java.lang.IllegalStateException: network is dead therefore can't send any packet
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:629)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.sendAndExpect$default(QQAndroidBotNetworkHandler.kt:624)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:150)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        ... 6 more

2020-09-10 10:45:07 I/Bot 3625889100: Retrying in 3s...
2020-09-10 10:45:10 I/Net 3625889100: Connected to server 42.81.169.46:8080
2020-09-10 10:45:10 I/Net 3625889100: Connected to server msfwifi.3g.qq.com:8080
2020-09-10 10:45:10 V/Net 3625889100: Send: wtlogin.login
2020-09-10 10:45:10 V/Net 3625889100: Send: wtlogin.login
2020-09-10 10:45:11 V/Net 3625889100: Recv: LoginPacketResponse.Captcha.Picture
2020-09-10 10:45:11 I/Bot 3625889100: 需要图片验证码登录, 验证码为 4 字母
2020-09-10 10:45:11 I/Bot 3625889100: 将会显示字符图片. 若看不清字符图片, 请查看文件 /tmp/tmp16544549477533190208.png
2020-09-10 10:45:11 I/Bot 3625889100: 无法创建字符图片. 请查看文件
2020-09-10 10:45:11 I/Bot 3625889100: 请输入 4 位字母验证码. 若要更换验证码, 请直接回车
2020-09-10 10:45:11 W/Bot 3625889100: java.io.IOException: 错误的文件描述符
java.io.IOException: 错误的文件描述符
        at java.base/java.io.FileInputStream.readBytes(Native Method)
        at java.base/java.io.FileInputStream.read(FileInputStream.java:272)
        at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
        at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:263)
        at kotlin.io.ConsoleKt.readLine(Console.kt:162)
        at kotlin.io.ConsoleKt.readLine(Console.kt:153)
        at net.mamoe.mirai.utils.LoginSolver$Companion$Default$1.invokeSuspend(LoginSolver.jvm.kt:149)
        at net.mamoe.mirai.utils.LoginSolver$Companion$Default$1.invoke(LoginSolver.jvm.kt)
        at net.mamoe.mirai.utils.StandardCharImageLoginSolver$input$1$1.invokeSuspend(LoginSolver.jvm.kt:78)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)

2020-09-10 10:45:11 I/Net 3625889100: Connected to server 114.221.144.215:80
2020-09-10 10:45:11 V/Net 3625889100: Send: wtlogin.login
2020-09-10 10:45:11 E/Net 3625889100: Exception in NetworkHandler
kotlin.UninitializedPropertyAccessException: lateinit property wLoginSigInfo has not been initialized
        at net.mamoe.mirai.qqandroid.network.QQAndroidClient.getWLoginSigInfo(QQAndroidClient.kt:262)
        at net.mamoe.mirai.qqandroid.network.QQAndroidClient$keys$2.invoke(QQAndroidClient.kt:87)
        at net.mamoe.mirai.qqandroid.network.QQAndroidClient$keys$2.invoke(QQAndroidClient.kt:71)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at net.mamoe.mirai.qqandroid.network.QQAndroidClient.getKeys(QQAndroidClient.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:439)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:465)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:460)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:449)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)

相关版本：1.1-EA

**Comment by Him188** [comment]
是很罕见的启动时遇到的网络问题, 重启即可解决
