### ISSUE TITLE
频繁出现Connection dropped by server or lost, retrying login

### ISSUE THREAD

**Issue by Lin-XCC** [mamoe/mirai#589]
正常登录mirai后，出现Connection dropped by server or lost, retrying login
然后由miria重连，重连成功后，还是会出现Connection dropped by server or lost, retrying login。间隔在一分钟以内。
mirai版本为1.2.2 
使用协议为安卓平板协议

详细网络日志
2020-09-11 12:08:34 I/Bot : Logging in...
2020-09-11 12:08:34 I/Net : Connected to server msfwifi.3g.qq.com:8080
2020-09-11 12:08:34 V/Net : Send: wtlogin.login
2020-09-11 12:08:34 V/Net : Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
2020-09-11 12:08:34 V/Net : Send: wtlogin.login
2020-09-11 12:08:34 V/Net : Recv: LoginPacketResponse.Success
2020-09-11 12:08:34 I/Net : Login successful
2020-09-11 12:08:34 V/Net : Send: StatSvc.register
2020-09-11 12:08:34 V/Net : Cannot decode ConfigPushSvc.PushReq, this can often be ignored.
2020-09-11 12:08:34 V/Net : Recv: Response(StatSvc.register)
2020-09-11 12:08:34 I/Net : 开始加载好友信息
2020-09-11 12:08:34 I/Net : 开始加载群组列表与群成员列表
2020-09-11 12:08:34 V/Net : Send: friendlist.getFriendGroupList
2020-09-11 12:08:34 V/Net : Send: friendlist.GetTroopListReqV2
2020-09-11 12:08:34 V/Net : Recv: FriendList.GetFriendGroupList.Response
2020-09-11 12:08:34 V/Net : 正在加载好友列表 3/3
2020-09-11 12:08:34 I/Net : 好友列表加载完成, 共 3个
2020-09-11 12:08:34 V/Net : Recv: FriendList.GetFriendGroupList.Response
2020-09-11 12:08:34 V/Net : Send: OidbSvc.0x88d_7
2020-09-11 12:08:34 V/Net : Send: OidbSvc.0x88d_7
2020-09-11 12:08:34 V/Net : Send: OidbSvc.0x88d_7
2020-09-11 12:08:34 V/Net : Send: OidbSvc.0x88d_7
2020-09-11 12:08:34 V/Net : Send: OidbSvc.0x88d_7
2020-09-11 12:08:34 V/Net : Send: OidbSvc.0x88d_7
2020-09-11 12:08:34 V/Net : Send: OidbSvc.0x88d_7
2020-09-11 12:08:34 V/Net : Send: OidbSvc.0x88d_7
2020-09-11 12:08:34 V/Net : Send: friendlist.GetTroopMemberListReq
2020-09-11 12:08:34 V/Net : Send: friendlist.GetTroopMemberListReq
2020-09-11 12:08:34 V/Net : Send: friendlist.GetTroopMemberListReq
2020-09-11 12:08:34 V/Net : Send: friendlist.GetTroopMemberListReq
2020-09-11 12:08:34 V/Net : Send: friendlist.GetTroopMemberListReq
2020-09-11 12:08:34 V/Net : Send: friendlist.GetTroopMemberListReq
2020-09-11 12:08:34 V/Net : Send: friendlist.GetTroopMemberListReq
2020-09-11 12:08:34 V/Net : Send: friendlist.GetTroopMemberListReq
2020-09-11 12:08:35 V/Net : Recv: FriendList.GetTroopMemberList.Response
2020-09-11 12:08:35 V/Net : Recv: FriendList.GetTroopMemberList.Response
2020-09-11 12:08:35 V/Net : Recv: FriendList.GetTroopMemberList.Response
2020-09-11 12:08:35 V/Net : Recv: FriendList.GetTroopMemberList.Response
2020-09-11 12:08:35 V/Net : Recv: FriendList.GetTroopMemberList.Response
2020-09-11 12:08:35 V/Net : Recv: FriendList.GetTroopMemberList.Response
2020-09-11 12:08:35 V/Net : Recv: FriendList.GetTroopMemberList.Response
2020-09-11 12:08:35 V/Net : Send: friendlist.GetTroopMemberListReq
2020-09-11 12:08:35 V/Net : Recv: FriendList.GetTroopMemberList.Response
2020-09-11 12:08:35 V/Net : Recv: FriendList.GetTroopMemberList.Response
2020-09-11 12:08:35 I/Net : 群组列表与群成员加载完成, 共 8个
2020-09-11 12:08:35 I/Net : Awaiting ConfigPushSvc.PushReq
2020-09-11 12:08:35 I/Net : Syncing friend message history...
2020-09-11 12:08:35 V/Net : Send: MessageSvc.PbGetMsg
2020-09-11 12:08:35 V/Net : Send: MessageSvc.PbDeleteMsg
2020-09-11 12:08:35 V/Bot : Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>))
2020-09-11 12:08:35 V/Net : Send: MessageSvc.PbGetMsg
2020-09-11 12:08:35 V/Net : Send: MessageSvc.PbDeleteMsg
2020-09-11 12:08:35 V/Bot : Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>))
2020-09-11 12:08:35 V/Net : Send: MessageSvc.PbGetMsg
2020-09-11 12:08:35 V/Net : Send: MessageSvc.PbDeleteMsg
2020-09-11 12:08:35 V/Bot : Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>))
2020-09-11 12:08:35 V/Net : Send: MessageSvc.PbGetMsg
2020-09-11 12:08:35 V/Net : Send: MessageSvc.PbDeleteMsg
2020-09-11 12:08:35 V/Bot : Event: MessageSvcPbGetMsg.Response(syncFlagFromServer=CONTINUE, messages=<Iterable>))
2020-09-11 12:08:35 V/Net : Send: MessageSvc.PbGetMsg
2020-09-11 12:08:35 V/Net : Send: MessageSvc.PbDeleteMsg
2020-09-11 12:08:35 I/Net : Syncing friend message history: Success
2020-09-11 12:08:35 I/Bot : Login successful
2020-09-11 12:08:45 I/Net : Missing ConfigPushSvc.PushReq.
2020-09-11 12:08:52 I/Bot : Connection dropped by server or lost, retrying login
2020-09-11 12:08:52 I/Net : Connected to server msfwifi.3g.qq.com:8080
2020-09-11 12:08:52 V/Net : Send: wtlogin.login
2020-09-11 12:08:52 V/Net : Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
2020-09-11 12:08:52 V/Net : Send: wtlogin.login
2020-09-11 12:08:52 V/Net : Recv: LoginPacketResponse.Success
2020-09-11 12:08:52 I/Net : Login successful
2020-09-11 12:08:52 V/Net : Send: StatSvc.register
2020-09-11 12:08:52 V/Net : Cannot decode ConfigPushSvc.PushReq, this can often be ignored.
2020-09-11 12:08:53 V/Net : Recv: Response(StatSvc.register)
2020-09-11 12:08:53 I/Net : Syncing friend message history...
2020-09-11 12:08:53 V/Net : Send: MessageSvc.PbGetMsg
2020-09-11 12:08:53 I/Bot : Reconnected successfully in 0.338s
2020-09-11 12:08:53 V/Net : Send: MessageSvc.PbDeleteMsg
2020-09-11 12:08:53 I/Net : Syncing friend message history: Success
2020-09-11 12:09:08 I/Bot : Connection dropped by server or lost, retrying login
2020-09-11 12:09:08 I/Net : Connected to server msfwifi.3g.qq.com:8080
2020-09-11 12:09:08 V/Net : Send: wtlogin.login
2020-09-11 12:09:08 V/Net : Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
2020-09-11 12:09:08 V/Net : Send: wtlogin.login
2020-09-11 12:09:09 V/Net : Recv: LoginPacketResponse.Success
2020-09-11 12:09:09 I/Net : Login successful
2020-09-11 12:09:09 V/Net : Send: StatSvc.register
2020-09-11 12:09:09 V/Net : Cannot decode ConfigPushSvc.PushReq, this can often be ignored.
2020-09-11 12:09:09 V/Net : Recv: Response(StatSvc.register)
2020-09-11 12:09:09 I/Bot : Reconnected successfully in 0.37s
2020-09-11 12:09:09 I/Net : Syncing friend message history...
2020-09-11 12:09:09 V/Net : Send: MessageSvc.PbGetMsg
2020-09-11 12:09:09 V/Net : Send: MessageSvc.PbDeleteMsg
2020-09-11 12:09:09 I/Net : Syncing friend message history: Success
2020-09-11 12:09:25 I/Bot : Connection dropped by server or lost, retrying login
2020-09-11 12:09:25 I/Net : Connected to server msfwifi.3g.qq.com:8080
2020-09-11 12:09:25 V/Net : Send: wtlogin.login
2020-09-11 12:09:25 V/Net : Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
2020-09-11 12:09:25 V/Net : Send: wtlogin.login
2020-09-11 12:09:25 V/Net : Recv: LoginPacketResponse.Success
2020-09-11 12:09:25 I/Net : Login successful
2020-09-11 12:09:25 V/Net : Send: StatSvc.register
2020-09-11 12:09:25 V/Net : Cannot decode ConfigPushSvc.PushReq, this can often be ignored.
2020-09-11 12:09:26 V/Net : Recv: Response(StatSvc.register)
2020-09-11 12:09:26 I/Bot : Reconnected successfully in 0.301s
2020-09-11 12:09:26 I/Net : Syncing friend message history...
2020-09-11 12:09:26 V/Net : Send: MessageSvc.PbGetMsg
2020-09-11 12:09:26 V/Net : Send: MessageSvc.PbDeleteMsg
2020-09-11 12:09:26 I/Net : Syncing friend message history: Success
2020-09-11 12:09:42 I/Bot : Connection dropped by server or lost, retrying login
2020-09-11 12:09:42 I/Net : Connected to server msfwifi.3g.qq.com:8080
2020-09-11 12:09:42 V/Net : Send: wtlogin.login
2020-09-11 12:09:42 V/Net : Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
2020-09-11 12:09:42 V/Net : Send: wtlogin.login
2020-09-11 12:09:42 V/Net : Recv: LoginPacketResponse.Success
2020-09-11 12:09:42 I/Net : Login successful

**Comment by mzdluo123** [comment]
请问是刚刚出现的吗，刚刚我似乎也遇到了这个问题

**Comment by Lin-XCC** [comment]
> 请问是刚刚出现的吗，刚刚我似乎也遇到了这个问题

今天才发现的问题，之前好像并没有出现。

**Comment by Karlatemp** [comment]
是的，似乎是最近才出现的问题，我登录了Windows, Android, ANDRIOD_PAD(mirai)和手表(mirai), 开始频繁出现此问题

**Comment by Karlatemp** [comment]
翻看我机器日志发现似乎是今天早上6点的时候就开始这样了

**Comment by NekoSola** [comment]
我也出现了这个问题

**Comment by NekoSola** [comment]
2020-09-11 13:15:56 I/Net 2180718017: Login successful
2020-09-11 13:16:01 V/Net 2180718017: Send: StatSvc.register
2020-09-11 13:16:01 V/Net 2180718017: Cannot decode ConfigPushSvc.PushReq, this can often be ignored.
2020-09-11 13:16:01 V/Net 2180718017: Recv: Response(StatSvc.register)
2020-09-11 13:16:01 I/Bot 2180718017: Reconnected successfully in 5.584s
2020-09-11 13:16:01 I/Net 2180718017: Syncing friend message history...
2020-09-11 13:16:01 V/Net 2180718017: Send: MessageSvc.PbGetMsg
2020-09-11 13:16:09 E/Net 2180718017: Exception in NetworkHandler
java.lang.IllegalStateException: timeout syncing friend message history
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.syncMessageSvc(QQAndroidBotNetworkHandler.kt:419)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$syncMessageSvc$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-09-11 13:16:17 I/Bot 2180718017: Connection dropped by server or lost, retrying login
2020-09-11 13:16:17 I/Net 2180718017: Connected to server msfwifi.3g.qq.com:8080
2020-09-11 13:16:17 V/Net 2180718017: Send: wtlogin.login
2020-09-11 13:16:17 V/Net 2180718017: Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
2020-09-11 13:16:18 V/Net 2180718017: Send: wtlogin.login
2020-09-11 13:16:18 V/Net 2180718017: Recv: LoginPacketResponse.Success
2020-09-11 13:16:18 I/Net 2180718017: Login successful
2020-09-11 13:16:23 V/Net 2180718017: Send: StatSvc.register
2020-09-11 13:16:23 V/Net 2180718017: Cannot decode ConfigPushSvc.PushReq, this can often be ignored.
2020-09-11 13:16:23 V/Net 2180718017: Recv: Response(StatSvc.register)
2020-09-11 13:16:23 I/Bot 2180718017: Reconnected successfully in 5.559s
2020-09-11 13:16:23 I/Net 2180718017: Syncing friend message history...
2020-09-11 13:16:23 V/Net 2180718017: Send: MessageSvc.PbGetMsg
2020-09-11 13:16:31 E/Net 2180718017: Exception in NetworkHandler
java.lang.IllegalStateException: timeout syncing friend message history
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.syncMessageSvc(QQAndroidBotNetworkHandler.kt:419)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$syncMessageSvc$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:55)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-09-11 13:16:40 I/Bot 2180718017: Connection dropped by server or lost, retrying login
2020-09-11 13:16:40 I/Net 2180718017: Connected to server msfwifi.3g.qq.com:8080
2020-09-11 13:16:40 V/Net 2180718017: Send: wtlogin.login
2020-09-11 13:16:40 V/Net 2180718017: Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin
2020-09-11 13:16:40 V/Net 2180718017: Send: wtlogin.login
2020-09-11 13:16:40 V/Net 2180718017: Recv: LoginPacketResponse.Success
2020-09-11 13:16:40 I/Net 2180718017: Login successful
2020-09-11 13:16:41 V/Net 2317318781: Send: Heartbeat.Alive
2020-09-11 13:16:41 V/Net 2317318781: Recv: Heartbeat.Alive.Response
2020-09-11 13:16:45 V/Net 2180718017: Send: StatSvc.register
2020-09-11 13:16:45 V/Net 2180718017: Cannot decode ConfigPushSvc.PushReq, this can often be ignored.
2020-09-11 13:16:46 V/Net 2180718017: Recv: Response(StatSvc.register)
2020-09-11 13:16:46 I/Bot 2180718017: Reconnected successfully in 5.534s
2020-09-11 13:16:46 I/Net 2180718017: Syncing friend message history...
2020-09-11 13:16:46 V/Net 2180718017: Send: MessageSvc.PbGetMsg

**Comment by wmxzqq** [comment]
包括腾讯云hk轻量在内的境外节点：（以下选一个即可）
203.205.255.220 msfwifi.3g.qq.com
203.205.255.221 msfwifi.3g.qq.com
境内节点：
42.81.172.22 msfwifi.3g.qq.com
不断drop属于腾讯问题，可自行修改host解决

**Comment by Lin-XCC** [comment]
> 包括腾讯云hk轻量在内的境外节点：（以下选一个即可）
> 203.205.255.220 msfwifi.3g.qq.com
> 203.205.255.221 msfwifi.3g.qq.com
> 境内节点：
> 42.81.172.22 msfwifi.3g.qq.com
> 不断drop属于腾讯问题，可自行修改host解决

感谢回复，将host文件添加境内节点后问题解决了。
如果可行的话，希望开发者可以考虑从代码方面尝试解决。

**Comment by cxy654849388** [comment]
> > 包括腾讯云hk轻量在内的境外节点：（以下选一个即可）
> > 203.205.255.220 msfwifi.3g.qq.com
> > 203.205.255.221 msfwifi.3g.qq.com
> > 境内节点：
> > 42.81.172.22 msfwifi.3g.qq.com
> > 不断drop属于腾讯问题，可自行修改host解决
> 
> 感谢回复，将host文件添加境内节点后问题解决了。
> 如果可行的话，希望开发者可以考虑从代码方面尝试解决。

我加了hosts文件好像还是不行，贴截图
![image](https://user-images.githubusercontent.com/36003572/92885072-027eb300-f445-11ea-9370-2c813ec5936e.png)

**Comment by Lin-XCC** [comment]
> > > 包括腾讯云hk轻量在内的境外节点：（以下选一个即可）
> > > 203.205.255.220 msfwifi.3g.qq.com
> > > 203.205.255.221 msfwifi.3g.qq.com
> > > 境内节点：
> > > 42.81.172.22 msfwifi.3g.qq.com
> > > 不断drop属于腾讯问题，可自行修改host解决
> > 
> > 
> > 感谢回复，将host文件添加境内节点后问题解决了。
> > 如果可行的话，希望开发者可以考虑从代码方面尝试解决。
> 
> 我加了hosts文件好像还是不行，贴截图
> ![image](https://user-images.githubusercontent.com/36003572/92885072-027eb300-f445-11ea-9370-2c813ec5936e.png)

添加一条即可，我是添加了42.81.172.22。

**Comment by CHMingXY** [comment]
> > > > 包括腾讯云hk轻量在内的境外节点：（以下选一个即可）
> > > > 203.205.255.220 msfwifi.3g.qq.com
> > > > 203.205.255.221 msfwifi.3g.qq.com
> > > > 境内节点：
> > > > 42.81.172.22 msfwifi.3g.qq.com
> > > > 不断drop属于腾讯问题，可自行修改host解决
> > > 
> > > 
> > > 感谢回复，将host文件添加境内节点后问题解决了。
> > > 如果可行的话，希望开发者可以考虑从代码方面尝试解决。
> > 
> > 
> > 我加了hosts文件好像还是不行，贴截图
> > ![image](https://user-images.githubusercontent.com/36003572/92885072-027eb300-f445-11ea-9370-2c813ec5936e.png)
> 
> 添加一条即可，我是添加了42.81.172.22。

还是没有解决，可能跟网络环境有关吧

**Comment by Karlatemp** [comment]
我现在已经没有这个情况了, 估计是tx在更新server导致

**Comment by Him188** [comment]
这应该就是服务器主动拒绝的连接. mirai 也没有办法.
登录之后服务器会提供目前可用的其他服务器列表, mirai 会动态更新重连的候选服务器, 因此不大可能出现无法连接的问题

**Comment by Him188** [comment]
发现此问题仍然存在, 可能是mirai在掉线后未切换服务器
