### ISSUE TITLE
一个很奇特的异常提示

### ISSUE THREAD

**Issue by Moredistant** [mamoe/mirai#601]
服务器上正常挂机，中午上去看的时候发现了一个很怪异的异常，在XXX群未找到XXX，问题是我根本没进这个群呀，而且也搜不到这个群

```

[0m2020-09-14 09:52:36 V/Net 123456: Recv: net.mamoe.mirai.qqandroid.network.protocol.data.jce.RequestPushNotify@16ddc42
[0m2020-09-14 09:52:36 V/Net 123456: Send: MessageSvc.PbGetMsg
[0m2020-09-14 09:52:36 V/Net 123456: Send: MessageSvc.PbDeleteMsg
[31m2020-09-14 09:52:36 E/Net 123456: Exception in NetworkHandler
java.util.NoSuchElementException: member 3621507478 not found in group 2194767631
        at net.mamoe.mirai.qqandroid.contact.GroupImpl.get(GroupImpl.kt:277)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.receive.OnlinePushPbPushGroupMsg.decode(OnlinePush.PbPushGroupMsg.kt:80)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:501)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:237)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:485)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:480)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:463)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


```

#### 复现

未知

#### 版本
mirai: ` ` 

1.2.3

**Comment by sandtechnology** [comment]
登录机器人帐号有同步到这个QQ号的聊天记录吗，怀疑是强制临时会话

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by Moredistant** [comment]
QQ我一直登着，日志这个时间点没有人给我发消息



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sandtechnology"<notifications@github.com&gt;; 
发送时间: 2020年9月14日(星期一) 下午3:00
收件人: "mamoe/mirai"<mirai@noreply.github.com&gt;; 
抄送: "Fade"<963206600@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mamoe/mirai] 一个很奇特的异常提示 (#601)





 登录机器人帐号有同步到这个QQ号的聊天记录吗，怀疑是强制临时会话 
 
 Sent from Outlook Mobile<" rel="noopener" target="_blank">https://aka.ms/blhgte&gt;; 
 
 ________________________________

**Comment by Him188** [comment]
属于sync问题
