### ISSUE TITLE
登录时提示手机qq版本过低

### ISSUE THREAD

**Issue by redXpanda** [mamoe/mirai#621]
登录时console提示手机qq版本过低

```
[92m2020-09-18 23:19:49 I/Bot 123456: Logging in...[0m
[92m2020-09-18 23:19:49 I/Net 123456: Connected to server 42.81.169.46:8080[0m
[0m2020-09-18 23:19:49 V/Net 123456: Send: wtlogin.login[0m
[0m2020-09-18 23:19:49 V/Net 123456: Recv: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )[0m
Exception in thread "main" net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低， 请先升级到手机QQ最新版本。, errorInfo= )
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.BotJavaFriendlyAPI$DefaultImpls.login(BotJavaFriendlyAPI.kt:209)
        at net.mamoe.mirai.Bot.login(Bot.kt:53)
        at cn.whitepanda.qbotmirai.App.main(App.java:53)


```

#### 复现

百分之百复现。密码是正确的，如果密码错误，会返回密码错误。

#### 版本
mirai: ` ` 
1.3.0

**Comment by Karlatemp** [comment]
`Net 123456` ?

**Comment by sandtechnology** [comment]
你使用的是默认的账号密码，请使用正确的账号和密码

**Comment by Lin-XCC** [comment]
我也出现了这个问题，一次掉线后重连失败，重新启动程序后提示版本过低。

**Comment by kasuganosoras** [comment]
2020-09-24 遇到了同样的问题，账号密码是正确的，登录提示这个
```
2020-09-24 05:14:44 W/Mirai: 未指定设备信息, 已使用随机设备信息. 请查看 BotConfiguration.deviceInfo 以获取更多信息.
2020-09-24 05:14:44 W/Mirai: Device info isn't specified. Please refer to BotConfiguration.deviceInfo for more information
2020-09-24 05:14:45 I/Bot (机器人QQ号): Logging in...
2020-09-24 05:14:45 I/Net (机器人QQ号): Connected to server 42.81.169.46:8080
2020-09-24 05:14:45 V/Net (机器人QQ号): Send: wtlogin.login
2020-09-24 05:14:45 V/Net (机器人QQ号): Recv: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )
Exception in thread "main" net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:250)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:123)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:308)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:318)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1411)
	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853)
	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:803)
	at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:93)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$PacketListener.complete(QQAndroidBotNetworkHandler.kt)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.handlePacket(QQAndroidBotNetworkHandler.kt:505)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:476)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseOicqResponse(PacketFactory.kt:419)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:283)
	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:235)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:467)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:462)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:445)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by daofeng2015** [comment]
> 2020-09-24 遇到了同样的问题，账号密码是正确的，登录提示下面的错误
> 即使是错误的密码也是返回同样的信息，换了另一个 QQ 号也是这个问题
> 使用的是 [Mirai Guide](https://github.com/mamoe/mirai/blob/1.3.1/docs/guide_getting_started.md) 里提供的示例代码
> 
> ```
> 2020-09-24 05:14:44 W/Mirai: 未指定设备信息, 已使用随机设备信息. 请查看 BotConfiguration.deviceInfo 以获取更多信息.
> 2020-09-24 05:14:44 W/Mirai: Device info isn't specified. Please refer to BotConfiguration.deviceInfo for more information
> 2020-09-24 05:14:45 I/Bot (机器人QQ号): Logging in...
> 2020-09-24 05:14:45 I/Net (机器人QQ号): Connected to server 42.81.169.46:8080
> 2020-09-24 05:14:45 V/Net (机器人QQ号): Send: wtlogin.login
> 2020-09-24 05:14:45 V/Net (机器人QQ号): Recv: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )
> Exception in thread "main" net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
> 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
> 	at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:250)
> 	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:123)
> 	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111)
> 	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:308)
> 	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:318)
> 	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
> 	at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1411)
> 	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
> 	at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
> 	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853)
> 	at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:803)
> 	at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:93)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$PacketListener.complete(QQAndroidBotNetworkHandler.kt)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.handlePacket(QQAndroidBotNetworkHandler.kt:505)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:476)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
> 	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseOicqResponse(PacketFactory.kt:419)
> 	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:283)
> 	at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:235)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:467)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:462)
> 	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:445)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> ```

把代码发出来看看.这边测试最新版没有问题

**Comment by kasuganosoras** [comment]
已解决，确实是账号密码的问题，改了新密码就好了……

**Comment by qq3261823009** [comment]
前天开始出现报版本过低升级的情况，不过是偶尔出现，昨天开始基本就登不上了，已经遇到四五个和我一个情况的人了，QQ可以正常登陆，密码也改过了还是不行
![image](https://user-images.githubusercontent.com/33348491/102426634-a4b4c500-404a-11eb-824d-918ea48a250e.png)

**Comment by Him188** [comment]
> 前天开始出现报版本过低升级的情况，不过是偶尔出现，昨天开始基本就登不上了，已经遇到四五个和我一个情况的人了，QQ可以正常登陆，密码也改过了还是不行
> ![image](https://user-images.githubusercontent.com/33348491/102426634-a4b4c500-404a-11eb-824d-918ea48a250e.png)

mirai-core 2.0-M1 有改善这个问题, 今日会发布

**Comment by ASTPoseidon** [comment]
问题复发

**Comment by UlyssesZh** [comment]
问题复发
