### ISSUE TITLE
图片转发失败

### ISSUE THREAD

**Issue by wqy0916** [mamoe/mirai#640]
描述这个Bug
天枢群管家违禁字图片文字检测撤回转发图片给管理员的时候出现的这个问题
![@T 0%I(4UBL RLHDSB6TC4E](https://user-images.githubusercontent.com/38550132/95019908-9c5a0a00-0657-11eb-97c7-49020241be66.png)

2020-10-04 22:16:16 E/MiraiNative: Exception in coroutine Plugin MiraiNative of MiraiNative
java.lang.IllegalStateException: Send friend message failed: MessageSvcPbSendMsg.Response.Failed(resultType=32, errorCode=0, errorMessage=)
at net.mamoe.mirai.qqandroid.contact.UtilKt.sendMessageImpl(util.kt:64)
at net.mamoe.mirai.qqandroid.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

操作系统：Windows 10 1903
mirai core 版本：mirai-core-all-1.3.1
mirai console 版本：mirai-console-terminal-1.0-RC-dev-29
mirai native 版本：mirai-native-1.9.3
Java 运行时版本：11版本 8版本都这样

**Comment by Karlatemp** [comment]
#307
