### ISSUE TITLE
无法监听加群申请event

### ISSUE THREAD

**Issue by jiangdashao** [mamoe/mirai#651]
被bot踢出群后再申请加群，就会出现这个错误，MemberJoinRequestEvent没有被触发.

```
[21:06:15 ERROR]: Exception in NetworkHandler
java.lang.IllegalStateException: 在 解析 NewContact.SystemMsgNewGroup, subType=5 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai. 并描述此时机器人是否被踢出群等 调试信息: SystemMsg#2109657849 {
            actionUin=0x00000000355671F3(894857715)
            actionUinNick=Loyisa
            actionUinQqNick=Loyisa
            actorUin=0x0000000000000000(0)
            cloneUin=0x0000000000000000(0)
            discussUin=0x0000000000000000(0)
            eimGroupId=0x0000000000000000(0)
            groupCode=0x000000003E0A836F(1040876399)
            groupExtFlag=0x40250440(1076167744)
            groupFlagext3=0x00000080(128)
            groupInfo=GroupInfo#384692516 {
                    appPrivilegeFlag=0x040800C0(67633344)
            }
            groupMsgType=0x00000003(3)
            groupName=test
            groupOwnerUin=0x0000000000000000(0)
            msgActorDescribe=处理人：%action_uin%
            msgDescribe=将你设置为管理员
            msgTitle=管理员设置
            reqUinAge=0x00000078(120)
            reqUinFaceid=0x00002202(8706)
            reqUinGender=0x00000001(1)
            reqUinNick=玉藻前 ? Lily
            subType=0x00000005(5)
    }
        at net.mamoe.mirai.qqandroid.message.ConversionsKt.contextualBugReportException(conversions.kt:494)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.chat.NewContact$SystemMsgNewGroup.decode(NewContact.kt:206)        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:498)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:235)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:467)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:462)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:445)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

#### 复现

不管是被bot踢出还是自己退群，都不会触发event
并且错误只会在**启动后首次加群申请**时出现，后续加群申请完全无反应

#### 版本
mirai: ` ` 
```
        <dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-qqandroid</artifactId>
            <version>1.3.2</version>
            <scope>compile</scope>
        </dependency>
```

**Comment by sandtechnology** [comment]
请仔细描述你的问题：
怎么邀请的？
与bot的关系？
在群内的身份？（管理员？群主？成员）
群的邀请设置？

**Comment by Him188** [comment]
> msgDescribe=将你设置为管理员

看起来这只是个消息同步, 这个权限变更已经有解析 `BotGroupPermissionChangeEvent`

**Comment by Him188** [comment]
我直接忽略 groupMsgType=3

**Comment by Him188** [comment]
最近还有一些在加群请求解析方面的修修, 有可能这个问题已经被修复了
