### ISSUE TITLE
bot挂载一段时间后就会无法发送消息

### ISSUE THREAD

**Issue by ZegWe** [mamoe/mirai#661]
报错如下：

```
2020-10-27 15:39:43 E/main: Exception in coroutine Mirai Bot
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.remove(ArrayList.java:496)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invokeSuspend(BotImpl.kt:94)
        at net.mamoe.mirai.qqandroid.BotImpl$offlineListener$1.invoke(BotImpl.kt)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invokeSuspend(subscriber.kt:271)
        at net.mamoe.mirai.event.SubscriberKt__SubscriberKt$subscribeAlways$1.invoke(subscriber.kt)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.internal.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.event.internal.Handler.onEvent(InternalEventListeners.kt:89)
        at net.mamoe.mirai.event.EventKt.broadcast(Event.kt:242)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$startHeartbeatJobOrKill$1$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:110)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 版本
mirai: ` 1.0-M4`

**Comment by Him188** [comment]
版本太旧
