### ISSUE TITLE
mirai登录失败

### ISSUE THREAD

**Issue by Moon-Haze** [mamoe/mirai#663]
我使用Ubuntu云服务器时，登录出现登录网络问题

```
Recv: Error(title=禁止登录, message=当 前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)
[15:22:47.226][ERROR]Robot error net.mamoe.mirai.network.WrongPasswordException: Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设 备上登录或稍后再试。, errorInfo=)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186) ~[AudioBot-1.0.jar:?]        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt) ~[AudioBot-1.0.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[AudioBot-1.0.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32) ~[AudioBot-1.0.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113) ~[AudioBot-1.0.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[AudioBot-1.0.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) ~[AudioBot-1.0.jar:?]
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274) ~[AudioBot-1.0.jar:?]
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84) ~[AudioBot-1.0.jar:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[AudioBot-1.0.jar:?]
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[AudioBot-1.0.jar:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[AudioBot-1.0.jar:?]
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[AudioBot-1.0.jar:?]
        at net.mamoe.mirai.BotJavaFriendlyAPI$DefaultImpls.login(BotJavaFriendlyAPI.kt:209) ~[AudioBot-1.0.jar:?]
        at net.mamoe.mirai.Bot.login(Bot.kt:53) ~[AudioBot-1.0.jar:?]
        at com.moon.core.BotStart.main(BotStart.java:80) [AudioBot-1.0.jar:?]
```

#### 版本
mirai: ` ` 

1.3.1

**Comment by Him188** [comment]
这样的登录问题很少发生，请尝试使用官方客户端登录一次，再重试登录。
