### ISSUE TITLE
miral-core-qqandroid 登录失败

### ISSUE THREAD

**Issue by poly000** [mamoe/mirai#668]
```
Login failed: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=)
2020-11-02 02:01:47 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo=)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Him188** [comment]
切换 ANDROID_PHONE 协议
