### ISSUE TITLE
验证码不显示？

### ISSUE THREAD

**Issue by zjy6622** [mamoe/mirai#677]
2020-11-10 10:17:46 I/Bot 1736475102: Logging in...
2020-11-10 10:17:46 W/Bot 1736475102: javax.imageio.IIOException: Can't create cache file!
javax.imageio.IIOException: Can't create cache file!
        at javax.imageio.ImageIO.createImageInputStream(Unknown Source)
        at javax.imageio.ImageIO.read(Unknown Source)
        at net.mamoe.mirai.utils.SwingSolver$onSolvePicCaptcha$2.invoke(LoginSolver.swing.jvm.kt:27)
        at net.mamoe.mirai.utils.SwingSolver$onSolvePicCaptcha$2.invoke(LoginSolver.swing.jvm.kt:24)
        at net.mamoe.mirai.utils.WindowInitialzier.init$mirai_core(WindowHelperJvm.kt:50)
        at net.mamoe.mirai.utils.WindowHelperJvmKt.openWindow(WindowHelperJvm.kt:79)
        at net.mamoe.mirai.utils.WindowHelperJvmKt.openWindow(WindowHelperJvm.kt:55)
        at net.mamoe.mirai.utils.SwingSolver.onSolvePicCaptcha(LoginSolver.swing.jvm.kt:26)
        at net.mamoe.mirai.utils.DefaultLoginSolver.onSolvePicCaptcha(LoginSolver.jvm.kt:52)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:166)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:198)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:184)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon(MiraiConsolePureLoader.kt:150)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon$default(MiraiConsolePureLoader.kt:149)
        at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt:46)
Caused by: java.nio.file.AccessDeniedException: C:\WINDOWS\imageio5605268933449838781.tmp
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.createFile(Unknown Source)
        at java.nio.file.TempFileHelper.create(Unknown Source)
        at java.nio.file.TempFileHelper.createTempFile(Unknown Source)
        at java.nio.file.Files.createTempFile(Unknown Source)
        at javax.imageio.stream.FileCacheImageInputStream.<init>(Unknown Source)
        at com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(Unknown Source)
        ... 27 more
2020-11-10 10:17:46 I/Bot 1736475102: Connection lost, retrying login

**Comment by Karlatemp** [comment]
请确认程序的运行账户拥有对临时文件目录的读写操作权限

**Comment by Karlatemp** [comment]
不属于mirai问题，可能输入运行时问题，可能是jre错误
可能是环境变量 TEMP 错误

**Comment by Karlatemp** [comment]
`@see` https://github.com/project-mirai/mirai-api-http/issues/212#issuecomment-743216244
