### ISSUE TITLE
消息发送异常

### ISSUE THREAD

**Issue by linzhihao0826** [mamoe/mirai#678]
当我监听到在群里有用户发送reply之后，进行sendMessage的时候出错
在这之前有一个Missing ConfigPushSvc.PushReq. 的Info

```
2020-11-10 16:42:09 E/Bot 2300586068: An exception was thrown under a coroutine of Bot
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.mamoe.mirai.event.Events$registerEvent$12$1.invokeSuspend(JvmMethodListeners.kt:330)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)


```

#### 版本
mirai: `1.0.4 `

**Comment by Karlatemp** [comment]
请提供版本号

**Comment by linzhihao0826** [comment]
1.0.4

> 请提供版本号

版本号为1.0.4

**Comment by Karlatemp** [comment]
版本过旧，请更新
