### ISSUE TITLE
mirai 手机登录跟 真机登录结果不同

### ISSUE THREAD

**Issue by mazehao** [mamoe/mirai#683]
mirai 登录qq 号 提示 “为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）“，在手机上登录 就会直接进入验证页面。 pad版同样不行。
mirai 的登录协议 跟手机登录有什么不同吗？ 问什么同样 8.3.0 的版本 登录返回结果完全不同？有没有什么方法可以让 协议可以像手机一样登录？

**Comment by ryoii** [comment]
复制日志中出现的验证地址，在浏览器中自行进行手机验证再进行后续操作。验证操作一般只进行一次，留意备份 `device.json` 文件

**Comment by ryoii** [comment]
如果没有出现验证地址，检查账号是否开启了设备锁

**Comment by mazehao** [comment]
> 如果没有出现验证地址，检查账号是否开启了设备锁

感谢回复，没有设备锁，日志也没有验证链接。直接报错。
![image](https://user-images.githubusercontent.com/21210371/99650639-9fd31480-2a90-11eb-8a6c-b0fdda5c2906.png)

**Comment by mazehao** [comment]
2020-11-19 17:52:26 V/Net 332468304: Recv: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)
Exception in thread "main" net.mamoe.mirai.network.WrongPasswordException: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:204)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)

**Comment by ryoii** [comment]
检查密码

**Comment by mazehao** [comment]
> 检查密码

账号密码都没有问题， 同样的账号，同样的网络，在手机上登录同样的版本 ，没有问题。我在想是不是登录协议有些许差别。

**Comment by ryoii** [comment]
不要说密码没有问题，请先认证。建议你把密码写到记事本里，同时复制到客户端和 `mirai` 进行验证。搜索相关issue，90%全是填错密码

**Comment by ryoii** [comment]
#672

**Comment by mazehao** [comment]
> #672

这个我看过，问题相似吧，但是我想问的还是不太一样。我登录的也是异地账号。密码验证过的没错，手机登录使用的adb输入，跟登录平台的密码无差别。但是手机却可以正常登录。理论上讲协议应该返回一个需要扫码或者资料验证的链接。

**Comment by Him188** [comment]
QQ 服务器就是有安全机制才这样返回，mirai 无法绕过服务器检测。

**Comment by mazehao** [comment]
> QQ 服务器就是有安全机制才这样返回，mirai 无法绕过服务器检测。

谢答，但是手机登录的是可以的。mirai 协议不是根据手机android QQ 来的吗。我现在打算对比，现有的登录协议，看看跟手机有什么区别。
不过有些时候比如同一个device ，频繁切换 pad 和phone 登录方式 偶尔可以 弹出验证信息，缺不能稳定复现。现在我不知道是哪里出了问题，很是难受。

**Comment by Tgo-zzz** [comment]
咳咳，不知该问具体情况。
我碰到的也是无法登录。

错误提示只有 `Recv: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)`。 
更换至PAD或WATCH登录方式后，错误换成 _网络不安全,禁止登陆..._

使用的是 mirai-console 1.1.0，本来应当出现验证的链接，但没有，没有任何进一步处理的提示。

参考类似问题回答之后，下载了 `mirai-demo`，启动起了其中的java版本（kotlin版不知为何报错，没有深究），成功出现验证链接，验证成功后，保存`device.json`到 mirai-console目录下。

再次启动 mirai-console，**问题解决**。
