### ISSUE TITLE
机器人发的消息我看不见 其他人能看见

### ISSUE THREAD

**Issue by awesomehhhhh** [mamoe/mirai#688]
reply(一个string)，控制台显示成功发送
但是在我的qq电脑端看不见qq机器人发的这条消息，同时如果我第一条看不见后面多少条我也看不见
包括sendAsImage()图片也看不见
群里面的其他人能看见
不像是风控，要不然怎么会只有我看不见群里其他人能看见
尝试过重启电脑，重启qq电脑端，使用qq手机端，qq手机极速版，重启qq机器人均无作用还是看不见
暂不知道什么时候恢复，但是过一会就恢复正常
撤回此消息出现以下错误
```
2020-11-29 12:25:17 E/Bot **qq号**: An exception was thrown under a coroutine of Bot
java.lang.IllegalStateException: Failed to recall message #-1: Failed(result=1001, errorMessage=No message meets the requirements)
	at net.mamoe.mirai.qqandroid.QQAndroidBotBase.recall$suspendImpl(QQAndroidBot.common.kt:505)
	at net.mamoe.mirai.qqandroid.QQAndroidBotBase$recall$1.invokeSuspend(QQAndroidBot.common.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
#### 复现

暂不清楚如何复现，但出现次数不低
#### 版本
mirai: 1.3.3

我之前试过其他版本也有这个问题

**Comment by dengfan** [comment]
我也碰到过一样的问题，PC端会有漏消息，但打开PC端的消息记录里面却又有那些消息。

手机端很正常，没有幺蛾子。

**Comment by dengfan** [comment]
我用过113和133，这两个版本都有PC端卡消息的问题

**Comment by Him188** [comment]
估计是没有 Svc unregister 的问题

**Comment by Him188** [comment]
2.4-M1 改善了很多, 只要正常调用 Bot.close 就可以
