### ISSUE TITLE
登录失败后协程没有正常结束

### ISSUE THREAD

**Issue by Lappand233** [mamoe/mirai#695]
即使在try-catch中抛出了LoginFailedException异常，协程仍然会卡住
此时如果在`catch`块中使用`Bot.close()`或`Bot.closeandjoin()`只能得到报错，并不能退出这个协程
挂起的协程无法恢复导致线程被卡住

```kotlin
lateinit var kyaruBot: Bot

suspend fun login(account: Long, passwd: String) {
    try {
        kyaruBot = Bot(/*账号*/, /*故意输错的密码*/) {
            fileBasedDeviceInfo("device.json")
        }.alsoLogin()
    } catch (e: LoginFailedException) {
        kyaruBot.close()  //报错处
    }

    kyaruBot.messageDSL()
    kyaruBot.Join()
}
//然后就是下面那样了...
```
```
kotlin.UninitializedPropertyAccessException: lateinit property kyaruBot has not been initialized
	at net.mamoe.mirai.kyaru.KyaruBot$Companion.login(KyaruBot.kt:25)
	at net.mamoe.mirai.kyaru.KyaruBot$Companion$login$1.invokeSuspend(KyaruBot.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 复现

1.故意输错账号密码即可复现

#### 版本
mirai: `1.3.3 `

**Comment by Karlatemp** [comment]
非mirai问题, 只是一个语法错误
```kotlin
lateinit var kyaruBot: Bot

suspend fun login(account: Long, passwd: String) {
    try {
        kyaruBot = Bot(/*账号*/, /*故意输错的密码*/) {
            fileBasedDeviceInfo("device.json")
        }.alsoLogin()
    } catch (e: LoginFailedException) {
        // 发生报错, kyaruBot 没有赋值. 于是initialize错误
        kyaruBot.close()  //报错处
    }

    kyaruBot.messageDSL()
    kyaruBot.Join()
}
```

正确代码
```kotlin
lateinit var kyaruBot: Bot

suspend fun login(account: Long, passwd: String) {
    try {
         Bot(/*账号*/, /*故意输错的密码*/) {
            fileBasedDeviceInfo("device.json")
        }.also { kyaruBot = it }.login()
    } catch (e: LoginFailedException) {
        kyaruBot.close()
    }

    kyaruBot.messageDSL()
    kyaruBot.Join()
}
```
