### ISSUE TITLE
BotFactory.INSTANCE.newBot 报错

### ISSUE THREAD

**Issue by notbucai** [mamoe/mirai#733]
```
Exception in thread "main" java.lang.ClassNotFoundException: net.mamoe.mirai.internal.MiraiImpl
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18)
	at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt:35)
	at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at net.mamoe.mirai.Mirai.getInstance(IMirai.kt)
	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:74)
	at Main.main(Main.java:80)

```
![image](https://user-images.githubusercontent.com/32786133/102682029-28b0ad80-4201-11eb-8b39-a7b5313c5ebb.png)

![image](https://user-images.githubusercontent.com/32786133/102682022-1b93be80-4201-11eb-9d22-b0db138676d9.png)

**Comment by Karlatemp** [comment]
runtime运行时缺少 `mirai-core(-jvm)`

**Comment by Him188** [comment]
请为运行时添加  `net.mamoe:mirai-core` 的依赖，版本号与 `-api` 模块的相同。
若使用 maven, 添加 `net.mamoe:mirai-core-jvm`
