### ISSUE TITLE
使用shadow打包，启动后出现错误

### ISSUE THREAD

**Issue by Coloryr** [mamoe/mirai#734]
具体日志
```
java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
at javax.crypto.JceSecurity.getInstance(JceSecurity.java:105)
at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:230)
at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:81)
at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion$1$1.invoke(ECDHJvmDesktop.kt:49)
at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
at net.mamoe.mirai.internal.utils.crypto.ECDHJvmDesktopKt.ECDH(ECDHJvmDesktop.kt:34)
at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:75)
at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:48)
at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:30)
at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:74)
at Color_yr.ColorMirai.Robot.BotStart.Start(BotStart.java:51)
at Color_yr.ColorMirai.Start.main(Start.java:30)
```
[错误代码位置](https://github.com/Coloryr/ColorMirai/blob/master/src/main/java/Color_yr/ColorMirai/Robot/BotStart.java)

**Comment by Karlatemp** [comment]
换jdk就能解决

**Comment by Coloryr** [comment]
1.3.3的版本没有这个问题，我用的是JAVA8构建，JAVA14启动

**Comment by Coloryr** [comment]
无论是JAVA8还是JAVA11启动，都会有这个错误

**Comment by Karlatemp** [comment]
更换openjdk

**Comment by Coloryr** [comment]
我试试

**Comment by Coloryr** [comment]
可以了
