### ISSUE TITLE
Recv: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )

### ISSUE THREAD

**Issue by Sabirjan** [mamoe/mirai#737]
最新版: 
![image](https://user-images.githubusercontent.com/7404699/102686829-30824900-4225-11eb-95d9-017d323e19e5.png)

Recv: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )

**Comment by Enaium** [comment]
这个bug已经修复了

**Comment by anaivebird** [comment]
没修复，2.0-M1还是没法登陆
![image](https://user-images.githubusercontent.com/29398611/102689071-5e23be00-4236-11eb-9e83-296fb56c9ee7.png)

PAD、PHONE、WATCH都不行

**Comment by anaivebird** [comment]
是个协议的bug，建议参照MiraiGo修复一下吧（MiraiGo能登录），现在大家用2.0-M1都没法登陆[https://github.com/Mrs4s/MiraiGo/commit/3a65d05f33782f6e6d3d00234f44ffd7660bea64](url)

**Comment by Sabirjan** [comment]
@Enaium 你是什么时候下的？
我下午下载不行

**Comment by meaningtree** [comment]
我也尝试换了一个账号登录，使用了M1版本依然不行。
2020-12-19 21:00:44 I/main: Backend: version 2.0-M1, built on 2020-12-19 00:45:02.
2020-12-19 21:00:44 I/main: Frontend Terminal: version 2.0-M1, provided by Mamoe Technologies
2020-12-19 21:00:45 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2020-12-19 21:00:45 I/main: 0 plugin(s) enabled.
2020-12-19 21:00:45 I/main: mirai-console started successfully.
> login －－－－－－－－－－－
2020-12-19 21:00:58 I/Bot.22750727200: Logging in...
Login failed: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)
2020-12-19 21:00:58 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(title=禁止登录, message=为了您的帐号安全，请使用QQ一键登录（通过手机QQ授权登录）。, errorInfo=)
at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:185)
at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by notbucai** [comment]
我也是这个问题

**Comment by meaningtree** [comment]
还有关于device.json有必要使用bytearray进行存储吗，这样修改起来十分过于麻烦了
