### ISSUE TITLE
java.lang.NoClassDefFoundError: net/mamoe/mirai/internal/network/protocol/data/jce/shareData$$serializer (wrong name: net/mamoe/mirai/internal/network/protocol/data/jce/ShareData$$serializer)

### ISSUE THREAD

**Issue by Visvaria** [mamoe/mirai#763]
当收到消息时
2020-12-24 22:46:37 E/Net 3462334217: Exception in NetworkHandler
java.lang.NoClassDefFoundError: net/mamoe/mirai/internal/network/protocol/data/jce/shareData$$serializer (wrong name: net/mamoe/mirai/internal/network/protocol/data/jce/ShareData$$serializer)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo$$serializer.deserialize(PushNotifyPack.kt)
	at net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo$$serializer.deserialize(PushNotifyPack.kt:42)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:234)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:165)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:191)
	at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:265)
	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:273)
	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:264)
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestPushNotify$$serializer.deserialize(PushNotifyPack.kt)
	at net.mamoe.mirai.internal.network.protocol.data.jce.RequestPushNotify$$serializer.deserialize(PushNotifyPack.kt:20)
	at kotlinx.serialization.encoding.Decoder$DefaultImpls.decodeSerializableValue(Decoding.kt:234)
	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableValue(Tagged.kt:165)
	at net.mamoe.mirai.internal.utils.io.serialization.tars.Tars.load(Tars.kt:40)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readJceStruct(utils.kt:50)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readJceStruct(utils.kt:1)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt:63)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt$readUniPacket$1.invoke(utils.kt)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.decodeUniRequestPacketAndDeserialize$SerializationUtils__UtilsKt(utils.kt:92)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket(utils.kt:60)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readUniPacket(utils.kt:1)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.readUniPacket$default(utils.kt:58)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.readUniPacket$default(utils.kt:1)
	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPushNotify.decode(MessageSvc.PushNotify.kt:29)
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:511)
	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:235)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:506)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:501)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:484)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Him188** [comment]
是因为同时存在 `shareData` 和 `ShareData`，Windows 上文件名冲突导致的
