### ISSUE TITLE
无法登录bot

### ISSUE THREAD

**Issue by 2659494057** [mamoe/mirai#769]
在使用2.0-M2-dev-4时一直报错:
Login failed: Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制 要求滑块验证, 请更换协议后重试
2020-12-25 22:31:40 E/console: net.mamoe.mirai.network.UnsupportedSliderCaptchaException: Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制要求滑块验证, 请更换协议后重试
net.mamoe.mirai.network.UnsupportedSliderCaptchaException: Mirai  无法完成滑块验证. 使用协议 ANDROID_PHONE 强制要求滑块验证, 请更换 协议后重试
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:200)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

在使用2.0-M1-1时，一直报错:
Login failed: Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)
2020-12-25 22:41:00 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(title=禁止登录, message=当前上网环境异常，请更 换网络环境或在常用设备上登录或稍后再试。, errorInfo=)             net.mamoe.mirai.network.WrongPasswordException: Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:185)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                           at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)                                                             at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)                                                        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)                                           at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)                                                                     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)                                            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)                                   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)                                     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Him188** [comment]
已解决，稍后会给出方案

**Comment by Karlatemp** [comment]
在 `mirai-console`>`config/Console/AutoLogin.yml` 中, 添加一个账号 并切换 `ANDROID_PAD` 协议, 待验证通过之后再切换至 `ANDROID_PHONE`

For mamoe: 在 `mirai-console` 的 `/login` 命令中支持选择登录协议
For iTXTech/mirai-console-loader: 在 Windows 系统中并且 Chrome 已安装的情况下下载 https://github.com/project-mirai/mirai-login-solver-selenium 并加载

**Comment by 2659494057** [comment]
> 在 `mirai-console`>`config/Console/AutoLogin.yml` 中, 添加一个账号 并切换 `ANDROID_PAD` 协议, 待验证通过之后再切换至 `ANDROID_PHONE`
> 
> For mamoe: 在 `mirai-console` 的 `/login` 命令中支持选择登录协议
> For iTXTech/mirai-console-loader: 在 Windows 系统中并且 Chrome 已安装的情况下下载 https://github.com/project-mirai/mirai-login-solver-selenium 并加载

在AutoLogin.yml中切换了ANDROID_PAD，登陆时依旧无法完成滑块验证

**Comment by Him188** [comment]
> 在 `mirai-console`>`config/Console/AutoLogin.yml` 中, 添加一个账号 并切换 `ANDROID_PAD` 协议, 待验证通过之后再切换至 `ANDROID_PHONE`
> 
> For mamoe: 在 `mirai-console` 的 `/login` 命令中支持选择登录协议
> For iTXTech/mirai-console-loader: 在 Windows 系统中并且 Chrome 已安装的情况下下载 https://github.com/project-mirai/mirai-login-solver-selenium 并加载

@PeratX

**Comment by Karlatemp** [comment]
> 在AutoLogin.yml中切换了ANDROID_PAD，登陆时依旧无法完成滑块验证

确认是在 console 关闭的情况下修改并且修改正确, 出现 `当前上网环境异常` 时请删除 `device.json` 后重试

**Comment by 2659494057** [comment]
> > 在AutoLogin.yml中切换了ANDROID_PAD，登陆时依旧无法完成滑块验证
> 
> 确认是在 console 关闭的情况下修改并且修改正确, 出现 `当前上网环境异常` 时请删除 `device.json` 后重试

在关闭console的情况下，多次修改为ANDROID_PAD，登陆时依旧报错
Login failed: Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制 要求滑块验证, 请更换协议后重试

**Comment by Karlatemp** [comment]
> 在关闭console的情况下，多次修改为ANDROID_PAD，登陆时依旧报错
> Login failed: Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制 要求滑块验证, 请更换协议后重试

请确认 `AutoLogin.yml` 是否正确

**Comment by 2659494057** [comment]
> > 在关闭console的情况下，多次修改为ANDROID_PAD，登陆时依旧报错
> > Login failed: Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制 要求滑块验证, 请更换协议后重试
> 
> 请确认 `AutoLogin.yml` 是否正确

accounts: 
  - # 账号, 现只支持 QQ 数字账号
    account: 123456
    password: 
      # 密码种类, 可选 PLAIN 或 MD5
      kind: PLAIN
      # 密码内容, PLAIN 时为密码文本, MD5 时为 16 进制
      value: pwd
    # 账号配置. 可用配置列表 (注意大小写):
    # "protocol": "ANDROID_PHONE" / "ANDROID_PAD" / "ANDROID_WATCH"
    configuration: 
      protocol: ANDROID_PAD

**Comment by Karlatemp** [comment]
**account: 123456**

**Comment by 2659494057** [comment]
> **account: 123456**

验证过后依旧会提示环境异常或者版本过低

**Comment by lliioollcn** [comment]
#772

**Comment by Him188** [comment]
关注 #745 获取后续修复进度

**Comment by AsrielDreemurr888** [comment]
无法登录，就三个文件，有什么解决办法？

**Comment by AsrielDreemurr888** [comment]
无法登录，就三个文件，有什么解决办法？

**Comment by Purewhitemilk** [comment]
给钱



---原始邮件---
发件人: "Asriel ***@***.***&gt;
发送时间: 2021年7月18日(周日) 下午4:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [mamoe/mirai] 无法登录bot (#769)




 
无法登录，就三个文件，有什么解决办法？
