### ISSUE TITLE
发送图片不显示

### ISSUE THREAD

**Issue by lliioollcn** [mamoe/mirai#775]
![QQ20201227-113817](https://user-images.githubusercontent.com/44719954/103163366-2e794500-4838-11eb-8018-71dd2d89082d.png)
上面是控制台日志
![QQ20201227-113831](https://user-images.githubusercontent.com/44719954/103163371-3802ad00-4838-11eb-9e46-d5738e1f4f1f.png)
上面为我的代码
发送之后在我号上看不到图片
mirai版本 2.0-M2-dev-5

**Comment by lliioollcn** [comment]
2.0-M2-dev-9登陆时候的报错:


2020-12-27 11:52:36 I/Net 3557265016: Connected to server 125.94.60.146:80
2020-12-27 11:52:36 V/Net 3557265016: Send: wtlogin.login
Exception in thread "DefaultDispatcher-worker-2" java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:29)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:189)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: java.lang.NoSuchMethodError: net.mamoe.mirai.utils.Utils.withSwitch(Lnet/mamoe/mirai/utils/MiraiLogger;Z)Lnet/mamoe/mirai/utils/MiraiLoggerWithSwitch;
		at net.mamoe.mirai.internal.network.protocol.packet.PacketFactoryKt$PacketLogger$2.invoke(PacketFactory.kt:118)
		at net.mamoe.mirai.internal.network.protocol.packet.PacketFactoryKt$PacketLogger$2.invoke(PacketFactory.kt)
		at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
		at net.mamoe.mirai.internal.network.protocol.packet.PacketFactoryKt.getPacketLogger(PacketFactory.kt)
		at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:190)
		at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:520)
		at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:515)
		at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:498)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		... 5 more
Caused by: java.lang.NoSuchMethodError: net.mamoe.mirai.utils.Utils.getStackTraceString(Ljava/lang/Throwable;)Ljava/lang/String;
	at net.mamoe.mirai.utils.PlatformLogger.error0(PlatformLogger.jvm.kt:98)
	at net.mamoe.mirai.utils.MiraiLoggerPlatformBase.error(MiraiLogger.kt:470)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$$special$$inlined$CoroutineExceptionHandler$1.handleException(CoroutineExceptionHandler.kt:111)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:25)
	... 12 more
2020-12-27 11:52:41 V/Net 3557265016: Send: wtlogin.login
Exception in thread "DefaultDispatcher-worker-2" java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:29)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:189)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: java.lang.NoSuchMethodError: net.mamoe.mirai.utils.Utils.withSwitch(Lnet/mamoe/mirai/utils/MiraiLogger;Z)Lnet/mamoe/mirai/utils/MiraiLoggerWithSwitch;
		at net.mamoe.mirai.internal.network.protocol.packet.PacketFactoryKt$PacketLogger$2.invoke(PacketFactory.kt:118)
		at net.mamoe.mirai.internal.network.protocol.packet.PacketFactoryKt$PacketLogger$2.invoke(PacketFactory.kt)
		at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
		at net.mamoe.mirai.internal.network.protocol.packet.PacketFactoryKt.getPacketLogger(PacketFactory.kt)
		at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:190)
		at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:520)
		at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:515)
		at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:498)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		... 5 more
Caused by: java.lang.NoSuchMethodError: net.mamoe.mirai.utils.Utils.getStackTraceString(Ljava/lang/Throwable;)Ljava/lang/String;
	at net.mamoe.mirai.utils.PlatformLogger.error0(PlatformLogger.jvm.kt:98)
	at net.mamoe.mirai.utils.MiraiLoggerPlatformBase.error(MiraiLogger.kt:470)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$$special$$inlined$CoroutineExceptionHandler$1.handleException(CoroutineExceptionHandler.kt:111)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:25)
	... 12 more
2020-12-27 11:52:46 V/Net 3557265016: Send: wtlogin.login
Exception in thread "DefaultDispatcher-worker-2" java.lang.RuntimeException: Exception while trying to handle coroutine exception
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handlerException(CoroutineExceptionHandler.kt:38)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:29)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:189)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:229)
	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:903)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:860)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:825)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
	Suppressed: java.lang.NoSuchMethodError: net.mamoe.mirai.utils.Utils.withSwitch(Lnet/mamoe/mirai/utils/MiraiLogger;Z)Lnet/mamoe/mirai/utils/MiraiLoggerWithSwitch;
		at net.mamoe.mirai.internal.network.protocol.packet.PacketFactoryKt$PacketLogger$2.invoke(PacketFactory.kt:118)
		at net.mamoe.mirai.internal.network.protocol.packet.PacketFactoryKt$PacketLogger$2.invoke(PacketFactory.kt)
		at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
		at net.mamoe.mirai.internal.network.protocol.packet.PacketFactoryKt.getPacketLogger(PacketFactory.kt)
		at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:190)
		at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:520)
		at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:515)
		at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:498)
		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
		... 5 more
Caused by: java.lang.NoSuchMethodError: net.mamoe.mirai.utils.Utils.getStackTraceString(Ljava/lang/Throwable;)Ljava/lang/String;
	at net.mamoe.mirai.utils.PlatformLogger.error0(PlatformLogger.jvm.kt:98)
	at net.mamoe.mirai.utils.MiraiLoggerPlatformBase.error(MiraiLogger.kt:470)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$$special$$inlined$CoroutineExceptionHandler$1.handleException(CoroutineExceptionHandler.kt:111)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:25)
	... 12 more
Exception in thread "CommandThread" java.util.NoSuchElementException: No line found
	at java.util.Scanner.nextLine(Scanner.java:1540)
	at cn.lliiooll.lbot.LBot.lambda$main$0(LBot.java:51)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Him188** [comment]
ExternalResource 在 dev5 有问题，在 dev9 修复。
dev9 有一个 Kotlin 编译器问题，待会发布 dev10

**Comment by lliioollcn** [comment]
换dev10一样，看不到图片

**Comment by Him188** [comment]
是图片损坏还是消息看不到

**Comment by tianhan1998** [comment]
我也出现了这个问题，用的2.0M1，上传完发送图片自己看和别人看都是裂开的
![图片](https://user-images.githubusercontent.com/34915174/103400704-0c0d6180-4b81-11eb-8ea7-ca623a44fba0.png)

**Comment by tianhan1998** [comment]
> 
> 
> 我也出现了这个问题，用的2.0M1，上传完发送图片自己看和别人看都是裂开的
> ![图片](https://user-images.githubusercontent.com/34915174/103400704-0c0d6180-4b81-11eb-8ea7-ca623a44fba0.png)
把图片缩小到20kb左右不会出现这个问题，不过100kb都上传不上去是不是有点小？

**Comment by zeylei** [comment]
我也遇到了这个问题 我最大可以发80k的图 更大的图就裂了
