### ISSUE TITLE
更新2.0-M2后mirai-api-http插件无法使用

### ISSUE THREAD

**Issue by Sknp1006** [mamoe/mirai#785]
启动器版本: mcl-1.0.3
libs: 
    mirai-console-2.0-M2.jar
    mirai-console-terminal-2.0-M2.jar
    mirai-core-all-2.0-M2.jar
    mirai-core-qqandroid-1.3.3.jar
plugins: 
    mirai-api-http-v1.9.0.jar

表现为：浏览器输入`http://localhost:4859//about`，无法打开

除此之外暂未发现其他问题，望指教

报错信息:
 21:31:21 [INFO] Mirai Console Loader version 1.0.3-6e34f43
 21:31:21 [INFO] https://github.com/iTXTech/mirai-console-loader
 21:31:21 [INFO] This program is licensed under GNU AGPL v3
 21:31:21 [DEBUG] Loading script: boot.js
 21:31:22 [DEBUG] Loading script: config.js
 21:31:22 [DEBUG] Loading script: repo.js
 21:31:22 [DEBUG] Loading script: updater.js
 21:31:22 [INFO] Verifying "net.mamoe:mirai-console" version 2.0-M2
 21:31:23 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.0-M2
 21:31:23 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.0-M2
2020-12-28 21:31:25 I/main: Starting mirai-console...
2020-12-28 21:31:25 I/main: Backend: version 2.0-M2, built on 2020-12-28 18:39:29.
2020-12-28 21:31:25 I/main: Frontend Terminal: version 2.0-M2, provided by Mamoe Technologies
2020-12-28 21:31:25 I/plugin: Successfully loaded plugin MiraiApiHttp
2020-12-28 21:31:26 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2020-12-28 21:31:26 I/MiraiApiHttp: Starting Mirai HTTP Server in 0.0.0.0:4859
2020-12-28 21:31:26 E/MiraiApiHttp: java.lang.NoSuchMethodError: net.mamoe.mirai.utils.Utils.getDefaultLogger()Lkotlin/jvm/functions/Function1;
java.lang.NoSuchMethodError: net.mamoe.mirai.utils.Utils.getDefaultLogger()Lkotlin/jvm/functions/Function1;
        at net.mamoe.mirai.api.http.MiraiHttpAPIServer.<clinit>(MiraiHttpAPIServer.kt:32)
        at net.mamoe.mirai.api.http.HttpApiPluginBase.onEnable(HttpApiPluginBase.kt:48)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:205)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:128)
        at org.itxtech.mcl.Loader.main(Loader.java:53)

2020-12-28 21:31:26 I/main: 1 plugin(s) enabled.
2020-12-28 21:31:26 I/main: mirai-console started successfully.

**Comment by Him188** [comment]
仔细看 2.0 更新说明，兼容的 mirai-api-http 还没有发布
