### ISSUE TITLE
windows+mcl登录报错,mirai-http-api+graia接收不到消息

### ISSUE THREAD

**Issue by RiotGamesU** [mamoe/mirai#786]
windows server 2019 datacenter + mcl1.3.3
用mcl默认的配置文件运行时报错,改为下面的config.json之后不报错:
{
  "js_optimization_level": -1,
  "mirai_repo": "https://gitee.com/peratx/mirai-repo/raw/master",
  "maven_repo": "https://maven.aliyun.com/repository/public",
  "packages": [
    {
      "id": "net.mamoe:mirai-console",
      "channel": "nightly",
      "version": "2.0-M2",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-console-terminal",
      "channel": "nightly",
      "version": "2.0-M2",
      "type": "libs"
    },
    {
      "id": "net.mamoe:mirai-core-all",
      "channel": "nightly",
      "version": "2.0-M2",
      "type": "libs"
    }
  ],
  "disabled_scripts": [],
  "proxy": "",
  "log_level": 0,
  "script_props": {}
}

但是登陆时报错:
```
2020-12-29 10:40:20 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2020-12-29 10:40:20 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2020-12-29 10:40:23 W/stderr: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
2020-12-29 10:40:23 W/stderr:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:133)
2020-12-29 10:40:23 W/stderr:   at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:238)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:81)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion$1$1.invoke(ECDHJvmDesktop.kt:49)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.internal.utils.crypto.ECDHJvmDesktopKt.ECDH(ECDHJvmDesktop.kt:34)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:75)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:56)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:30)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:116)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:161)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:125)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot$default(MiraiConsole.kt:124)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:158)
2020-12-29 10:40:23 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2020-12-29 10:40:23 W/stderr:   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2020-12-29 10:40:23 W/stderr:   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2020-12-29 10:40:23 W/stderr:   at java.base/java.lang.reflect.Method.invoke(Method.java:564)
2020-12-29 10:40:23 W/stderr:   at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
2020-12-29 10:40:23 W/stderr:   at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
2020-12-29 10:40:23 W/stderr:   at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
2020-12-29 10:40:23 W/stderr:   at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
2020-12-29 10:40:23 W/stderr:   at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:283)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:161)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:129)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
2020-12-29 10:40:23 W/stderr:   at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:183)
2020-12-29 10:40:23 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2020-12-29 10:40:23 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2020-12-29 10:40:23 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2020-12-29 10:40:23 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
2020-12-29 10:40:23 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2020-12-29 10:40:23 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-12-29 10:40:23 W/stderr: Caused by: java.util.jar.JarException: file:/C:/Users/Administrator/Desktop/mcl-1.0.3/libs/mirai-core-all-2.0-M2.jar has unsigned entries - net/mamoe/mirai/internal/AbstractBot$2.class
2020-12-29 10:40:23 W/stderr:   at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:459)
2020-12-29 10:40:23 W/stderr:   at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:314)
2020-12-29 10:40:23 W/stderr:   at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:257)
2020-12-29 10:40:23 W/stderr:   at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
2020-12-29 10:40:23 W/stderr:   at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:192)
2020-12-29 10:40:23 W/stderr:   at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:220)
2020-12-29 10:40:23 W/stderr:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:130)
2020-12-29 10:40:23 W/stderr:   ... 36 more
2020-12-29 10:40:23 I/Bot.xxxx: Logging in...
2020-12-29 10:40:23 I/Bot.xxxx: Online OtherClients:
2020-12-29 10:40:28 I/Bot.xxxx: Login successful
```

**一直在用的device.json不小心删了**

#### 复现

1.运行mcl.bat
2.登录账号

#### 版本
mirai: ` ` 
console,terminal,core-all:2.0-M2

我是用的mirai-http-api + python,现在这种情况,控制台可以打印出来接收到的消息,但是我用的python sdk,graia接收不到消息
graia:https://github.com/GraiaProject/Application

**Comment by Karlatemp** [comment]
使用openjdk

**Comment by RiotGamesU** [comment]
> 使用openjdk

谢谢,登陆的时候不报错了,但是mirai-http-api + graia依旧接收不到消息...graia输出的信息如下:
[2020-12-29 13:17:08,489][INFO]: initializing app...
[2020-12-29 13:17:09,030][INFO]: detecting remote's version...
[2020-12-29 13:17:09,070][INFO]: detected remote's version: 1.9.2
[2020-12-29 13:17:09,107][INFO]: using pure websocket to receive event
[2020-12-29 13:17:09,107][INFO]: event receive method checked.
[2020-12-29 13:17:09,107][INFO]: this application's initialization has been completed.
[2020-12-29 13:17:09,107][INFO]: --- setting start ---
[2020-12-29 13:17:09,107][INFO]: broadcast using: <graia.broadcast.Broadcast object at 0x000001CFD51D4160>
[2020-12-29 13:17:09,107][INFO]: enable log of chat: yes
[2020-12-29 13:17:09,107][INFO]: debug: no
[2020-12-29 13:17:09,107][INFO]: version(remote): 1.9.2
[2020-12-29 13:17:09,107][INFO]: --- setting end ---
[2020-12-29 13:17:09,107][INFO]: application has been initialized, used 0.618s
[2020-12-29 13:17:09,107][INFO]: websocket daemon: websocket connection starting...
[2020-12-29 13:17:09,155][INFO]: websocket: connected

说明连上了,但是收不到信息

**Comment by Him188** [comment]
读文档，看Discussion

**Comment by Him188** [comment]
只要mirai能收到消息（有日志），就不是mirai问题（我们也无法解决），请向 graia 框架反馈

**Comment by RiotGamesU** [comment]
> 读文档，看Discussion

稳定运行了几个月了,现在突然这样的

**Comment by RiotGamesU** [comment]
> 只要mirai能收到消息（有日志），就不是mirai问题（我们也无法解决），请向 graia 框架反馈

好的,谢谢

**Comment by redjs** [comment]
这个问题我也遇到了，java分Oracle版和openjdk版，我换成openjdk13就行了，下载地址 http://jdk.java.net/java-se-ri/13

**Comment by ryoii** [comment]
尝试升级mah到1.9.4，可能py那边解析json的时候没做空处理或限制严格。1.9.3版本的mah因为kts升级导致一些默认值没有序列化成功

**Comment by RiotGamesU** [comment]
> 这个问题我也遇到了，java分Oracle版和openjdk版，我换成openjdk13就行了，下载地址 http://jdk.java.net/java-se-ri/13

谢谢,我用openjdk不报错了

**Comment by RiotGamesU** [comment]
> 尝试升级mah到1.9.4，可能py那边解析json的时候没做空处理或限制严格。1.9.3版本的mah因为kts升级导致一些默认值没有序列化成功

谢谢,mah1.9.4对mirai版本什么要求呢,我昨天用mcl,console,terminal和core-all的2.0-M1-1版本 + mah1.9.3可以正常接收消息了,刚才用mah1.9.4会报错,以及用mah1.9.3截至目前发现的另外两个问题,获取不到被at的人的昵称,at别人时不发at只发昵称,不知道是mah还是graia的问题,我刚才在graia的issues那边一个解决昨天的报错的解决方法,用console和terminal的1.0.0版本和core-all的1.3.3版本 + mah1.9.0也可以正常接收消息,而且可以成功发送at消息

**Comment by ryoii** [comment]
`websocket` 库可能 bug 了，我得先看看官方 `issue`
