### ISSUE TITLE
无法登录(和之前issue都不一样)

### ISSUE THREAD

**Issue by lvyitian** [mamoe/mirai#798]
Login failed: Error(title=温馨提示, message=当前版本过低，请先升级到手机QQ最新版本。, errorInfo= )

`net.mamoe.mirai.network.WrongPasswordException: Error(title=��ܰ��ʾ, message=��ǰ�汾���ͣ������������ֻ�QQ���°汾��, errorInfo= )
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:250)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:123)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:111)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:308)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:318)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:250)
        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1411)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318)
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:853)
        at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:803)
        at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:93)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$PacketListener.complete(QQAndroidBotNetworkHandler.kt)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.handlePacket(QQAndroidBotNetworkHandler.kt:505)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invokeSuspend(QQAndroidBotNetworkHandler.kt:476)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$generifiedParsePacket$2.invoke(QQAndroidBotNetworkHandler.kt)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseOicqResponse(PacketFactory.kt:419)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core_qqandroid(PacketFactory.kt:283)
        at net.mamoe.mirai.qqandroid.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:235)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:467)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:462)
        at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:445)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

#### 复现
直接用/login登录即可
（某些地区会出现此问题而某些地区又不会）

#### 版本
mirai-core: `2.0-M2` 
mirai-core-qqandroid: `1.3.3`
mirai-console: `1.0-M4`
mirai-console-pure: `1.0-M4`

账号是常用账号，电脑和手机qq登录都无验证之类，设备锁已关闭，10天前可用，用旧版console是因为用新版console会出现: `
java.lang.NoClassDefFoundError: net.mamoe.mirai.console.MiraiConsole (initialization failure)
at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:218)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
Caused by: java.lang.NoSuchMethodError: net/mamoe/mirai/utils/MiraiLogger$Companion.setDefaultLoggerCreator(Lkotlin/jvm/functions/Function1;)V (loaded from file:/C:/Users/%e5%90%95%e6%98%93%e5%a4%a9/Downloads/Compressed/tmp/libs/mirai-core-all-1.3.3.jar by sun.misc.Launcher$AppClassLoader@106549e5) called from class net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge (loaded from file:/C:/Users/%e5%90%95%e6%98%93%e5%a4%a9/Downloads/Compressed/tmp/libs/mirai-console-2.0-M2-1-dev-1.jar by sun.misc.Launcher$AppClassLoader@106549e5).
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.<clinit>(MiraiConsoleImplementationBridge.kt:99)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        ... 3 more
`

**Comment by Him188** [comment]
依赖有误，请先仔细阅读文档

**Comment by Him188** [comment]
你使用的是 1.3.3，请更换 2.0-M2

**Comment by lvyitian** [comment]
> 你使用的是 1.3.3，请更换 2.0-M2

协议库在maven仓库最新就只有1.3.3

**Comment by lvyitian** [comment]
> 依赖有误，请先仔细阅读文档

直接使用官方wrapper 1.0.3就会出现NoSuchMethod

**Comment by lvyitian** [comment]
> 你使用的是 1.3.3，请更换 2.0-M2

别的人使用我这个版本甚至更旧都可以登录

**Comment by Him188** [comment]
> > 你使用的是 1.3.3，请更换 2.0-M2
> 
> 协议库在maven仓库最新就只有1.3.3

所有版本都有，看文档

**Comment by Him188** [comment]
> > 你使用的是 1.3.3，请更换 2.0-M2
> 
> 别的人使用我这个版本甚至更旧都可以登录

别人能等与你无关，你被风控，那你为什么不升级
