### ISSUE TITLE
无法重连，确定无网络异常

### ISSUE THREAD

**Issue by clhaaaa** [mamoe/mirai#824]
无法重连，但是服务器上有用cqhttp挂着另外一个机器人，完全没有掉线情况。
服务器网络不是idc而是家宽，应该不存在腾讯风控。
添加过host 42.81.172.22 msfwifi.3g.qq.com，依然出现这种掉线无法重连的现象。
而且dmp文件为0kb

```
2021-01-07 08:41:33 W/Bot.botqq号: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
        at java.lang.Thread.run(Thread.java:823)

2021-01-07 08:41:48 W/Bot.botqq号: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
        at java.lang.Thread.run(Thread.java:823)

2021-01-07 08:41:48 I/Bot.botqq号: Cannot reconnect.
2021-01-07 08:41:48 W/Bot.botqq号: net.mamoe.mirai.network.NoServerAvailableException: no server available
net.mamoe.mirai.network.NoServerAvailableException: no server available
        at net.mamoe.mirai.internal.QQAndroidBot.relogin(QQAndroidBot.kt:197)
        at net.mamoe.mirai.internal.QQAndroidBot$relogin$1.invokeSuspend(QQAndroidBot.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
        at java.lang.Thread.run(Thread.java:823)

2021-01-07 08:41:48 I/Bot.botqq号: Retrying in 3s...
> JVMDUMP039I 正在处理转储事件“systhrow”，详细信息“java/lang/OutOfMemoryError”，位于 2021/01/07 08:41:52 - 请稍候。
JVMDUMP032I JVM 使用“D:\mirai-console-2.0-M2-2+native-1.9.6+mirai-login-solver-selenium-1.0-dev-12\mirai-console-2.0-M2-2+native-1.9.6+mirai-login-solver-selenium-1.0-dev-12\core.20210107.084152.6704.0001.dmp”来请求 System 转储以响应事件


```

#### 复现

每隔几个小时发生

#### 版本
mirai: ` ` 

2.0-M2-2

**Comment by clhaaaa** [comment]
日志系统内日志如下
[92m2021-01-07 08:37:26 I/Net botqq号: Connected to server 42.81.172.22:80[0m
[0m2021-01-07 08:37:26 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:37:31 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:37:36 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:37:44 I/Net botqq号: Connected to server msfwifi.3g.qq.com:8080[0m
[0m2021-01-07 08:37:44 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:37:49 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:37:54 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:37:59 I/Net botqq号: Connected to server 42.81.172.147:443[0m
[0m2021-01-07 08:37:59 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:38:04 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:38:09 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:38:14 I/Net botqq号: Connected to server 42.81.172.81:80[0m
[0m2021-01-07 08:38:14 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:38:19 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:38:24 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:38:30 I/Net botqq号: Connected to server 42.81.169.46:8080[0m
[0m2021-01-07 08:38:30 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:38:35 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:38:40 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:38:45 I/Net botqq号: Connected to server 125.94.60.146:80[0m
[0m2021-01-07 08:38:45 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:38:50 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:38:55 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:39:00 I/Net botqq号: Connected to server 114.221.148.59:14000[0m
[0m2021-01-07 08:39:00 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:39:05 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:39:10 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:39:15 I/Net botqq号: Connected to server 114.221.144.215:80[0m
[0m2021-01-07 08:39:15 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:39:20 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:39:25 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:39:30 I/Net botqq号: Connected to server 42.81.172.22:80[0m
[0m2021-01-07 08:39:30 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:39:35 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:39:40 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:39:48 I/Net botqq号: Connected to server msfwifi.3g.qq.com:8080[0m
[0m2021-01-07 08:39:48 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:39:53 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:39:58 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:40:03 I/Net botqq号: Connected to server 42.81.172.147:443[0m
[0m2021-01-07 08:40:03 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:40:08 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:40:13 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:40:18 I/Net botqq号: Connected to server 42.81.172.81:80[0m
[0m2021-01-07 08:40:18 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:40:23 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:40:28 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:40:33 I/Net botqq号: Connected to server 42.81.169.46:8080[0m
[0m2021-01-07 08:40:33 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:40:38 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:40:43 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:40:48 I/Net botqq号: Connected to server 125.94.60.146:80[0m
[0m2021-01-07 08:40:48 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:40:53 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:40:58 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:41:03 I/Net botqq号: Connected to server 114.221.148.59:14000[0m
[0m2021-01-07 08:41:03 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:41:08 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:41:13 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:41:18 I/Net botqq号: Connected to server 114.221.144.215:80[0m
[0m2021-01-07 08:41:18 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:41:23 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:41:28 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:41:33 I/Net botqq号: Connected to server 42.81.172.22:80[0m
[0m2021-01-07 08:41:33 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:41:38 V/Net botqq号: Send: wtlogin.login[0m
[0m2021-01-07 08:41:43 V/Net botqq号: Send: wtlogin.login[0m
[92m2021-01-07 08:41:51 I/Net botqq号: Connected to server msfwifi.3g.qq.com:8080[0m
[0m2021-01-07 08:41:51 V/Net botqq号: Send: wtlogin.login[0m

**Comment by Karlatemp** [comment]
出现 OutOfMemoryError字样 , 请添加 jvm 参数&nbsp;

-XX:+HeapDumpOnOutOfMemoryError


并上传报告


see also #818

**Comment by sandtechnology** [comment]
怀疑是OutOfMemoryError被吞掉导致的频繁重连进而导致线程死掉
