### ISSUE TITLE
在处理 QuoteReply 的时候会死循环造成 java.lang.StackOverflowError

### ISSUE THREAD

**Issue by Karlatemp** [mamoe/mirai#829]
```txt
java.lang.StackOverflowError
	// 与死循环无关......
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:135)
	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
	// 死循环片段
	at net.mamoe.mirai.internal.message.OfflineSourceImplKt.OfflineMessageSourceImplData(offlineSourceImpl.kt:151)
	at net.mamoe.mirai.internal.message.ConversionsKt.toMessageChain(conversions.kt:351)
	at net.mamoe.mirai.internal.message.OfflineSourceImplKt.OfflineMessageSourceImplData(offlineSourceImpl.kt:154)
	at net.mamoe.mirai.internal.message.ConversionsKt.toMessageChain(conversions.kt:351)
	at net.mamoe.mirai.internal.message.OfflineSourceImplKt.OfflineMessageSourceImplData(offlineSourceImpl.kt:154)
	at net.mamoe.mirai.internal.message.ConversionsKt.toMessageChain(conversions.kt:351)
	at net.mamoe.mirai.internal.message.OfflineSourceImplKt.OfflineMessageSourceImplData(offlineSourceImpl.kt:154)
	at net.mamoe.mirai.internal.message.ConversionsKt.toMessageChain(conversions.kt:351)
	at net.mamoe.mirai.internal.message.OfflineSourceImplKt.OfflineMessageSourceImplData(offlineSourceImpl.kt:154)
	// .......
```

-----------

在处理 `QuoteReply` 时, 需要构建 `OfflineMessageSource`, 然后源消息再次 `toMessageChain`, 里面存在原来的 `QuoteReply`, 然后需要构建 `OfflineMessageSource` .... 并陷入死循环, 直到 `java.lang.StackOverflowError` 触发

复现: 发送一条带回复的信息

需要确定修正方式

- 添加 `lazy` 
- 在处理 `incoming` 时 `QuoteReply` 使用的 `OfflineMessageSource` 的 `originMessage` 换用 `lateinit var`

**Comment by Him188** [comment]
我觉得lazy

**Comment by Karlatemp** [comment]
发现同时牵扯到序列化，序列化可能会因为 `QuoteReply` 陷入无限死循环中
