### ISSUE TITLE
Idea使用maven集成方式，启动报错

### ISSUE THREAD

**Issue by baihuagongshlei** [mamoe/mirai#831]
<dependency>
            <groupId>net.mamoe</groupId>
            <artifactId>mirai-core-jvm</artifactId>
            <version>2.0-M2-2</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlin.version}</version>
        </dependency>

这样集成之后，编译时没问题，启动后报找不到类：
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.internal.MiraiImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18)
	at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt:35)
	at net.mamoe.mirai.Mirai$Mirai$2.invoke(IMirai.kt)

请问是怎么回事？maven仓库里删除了jar重新下载过也不行；

**Comment by Karlatemp** [comment]
try remove `<type>pom</type>`

**Comment by baihuagongshlei** [comment]
Thank you，It's right;
