### ISSUE TITLE
新人加群聊事件无法触发

### ISSUE THREAD

**Issue by mcdoeswhat** [mamoe/mirai#856]
新人进群聊天无法触发群聊事件,经过测试小群没问题,1900多人的群就有这个问题(出现三次)
版本为2.0-RC 退回1.1.3版本后没有这个问题

```

```

#### 版本
- mirai-core: `2.0-RC-all`

**Comment by sandtechnology** [comment]
请附上网络日志？

**Comment by mcdoeswhat** [comment]
没开日志,不过刚刚开了日志复现了
报错这样
`[18:13:00 INFO]: 2021-01-13 18:13:00 E/Net 1406951836: Exception in NetworkHandler
[18:13:00 INFO]: java.lang.NullPointerException: null cannot be cast to non-null type net.mamoe.mirai.internal.contact.NormalMemberImpl
[18:13:00 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.OnlinePushPbPushGroupMsg.decode(OnlinePush.PbPushGroupMsg.kt:104)
[18:13:00 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:508)
[18:13:00 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:237)
[18:13:00 INFO]:        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:562)
[18:13:00 INFO]:        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:557)
[18:13:00 INFO]:        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:540)
[18:13:00 INFO]:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[18:13:00 INFO]:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[18:13:00 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[18:13:00 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
[18:13:00 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[18:13:00 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[18:13:00 INFO]:`

**Comment by mcdoeswhat** [comment]
> 没开日志,不过刚刚开了日志复现了
> 报错这样
> `[18:13:00 INFO]: 2021-01-13 18:13:00 E/Net 1406951836: Exception in NetworkHandler [18:13:00 INFO]: java.lang.NullPointerException: null cannot be cast to non-null type net.mamoe.mirai.internal.contact.NormalMemberImpl [18:13:00 INFO]: at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.OnlinePushPbPushGroupMsg.decode(OnlinePush.PbPushGroupMsg.kt:104) [18:13:00 INFO]: at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:508) [18:13:00 INFO]: at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:237) [18:13:00 INFO]: at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:562) [18:13:00 INFO]: at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:557) [18:13:00 INFO]: at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:540) [18:13:00 INFO]: at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [18:13:00 INFO]: at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [18:13:00 INFO]: at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [18:13:00 INFO]: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) [18:13:00 INFO]: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [18:13:00 INFO]: at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [18:13:00 INFO]:`

这个是新人进群发消息的时候出现的,发一次出现一次

**Comment by sandtechnology** [comment]
请提供进群前到第一次发言的网络日志
另外是如何入群的？

**Comment by mcdoeswhat** [comment]
直接加群
加群时候显示的日志:
`[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Send: MessageSvc.PbGetMsg
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Send: MessageSvc.PbDeleteMsg
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Send: friendlist.GetTroopListReqV2
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Recv: FriendList.GetFriendGroupList.Response
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Send: friendlist.GetTroopMemberListReq
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Recv: FriendList.GetTroopMemberList.Response
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Send: friendlist.GetTroopMemberListReq
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Recv: FriendList.GetTroopMemberList.Response
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Send: friendlist.GetTroopMemberListReq
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Recv: FriendList.GetTroopMemberList.Response
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Send: friendlist.GetTroopMemberListReq
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Recv: FriendList.GetTroopMemberList.Response
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Send: friendlist.GetTroopMemberListReq
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Recv: FriendList.GetTroopMemberList.Response
[18:12:37 INFO]: 2021-01-13 18:12:37 V/Net 1406951836: Send: friendlist.GetTroopMemberListReq
[18:12:38 INFO]: 2021-01-13 18:12:38 V/Net 1406951836: Recv: FriendList.GetTroopMemberList.Response
[18:12:38 INFO]: 2021-01-13 18:12:38 V/Net 1406951836: Send: friendlist.GetTroopMemberListReq
[18:12:38 INFO]: 2021-01-13 18:12:38 V/Net 1406951836: Recv: FriendList.GetTroopMemberList.Response
[18:12:38 INFO]: 2021-01-13 18:12:38 V/Net 1406951836: Send: friendlist.GetTroopMemberListReq
[18:12:38 INFO]: 2021-01-13 18:12:38 V/Net 1406951836: Recv: FriendList.GetTroopMemberList.Response`

一发言就显示这个报错,不会显示聊天的内容什么的
`[18:12:54 INFO]: 2021-01-13 18:12:54 E/Net 1406951836: Exception in NetworkHandler
[18:12:54 INFO]: java.lang.NullPointerException: null cannot be cast to non-null type net.mamoe.mirai.internal.contact.NormalMemberImpl
[18:12:54 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.OnlinePushPbPushGroupMsg.decode(OnlinePush.PbPushGroupMsg.kt:104)
[18:12:54 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:508)
[18:12:54 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:237)
[18:12:54 INFO]:        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:562)
[18:12:54 INFO]:        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:557)
[18:12:54 INFO]:        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:540)
[18:12:54 INFO]:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[18:12:54 INFO]:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[18:12:54 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[18:12:54 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
[18:12:54 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[18:12:54 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[18:12:54 INFO]:`

另外还出现了另一个报错,(再这个之前,好像和这个没啥关系,不知道啥事件触发的)
`[18:09:46 INFO]: 2021-01-13 18:09:46 E/Net 1406951836: Exception in NetworkHandler
[18:09:46 INFO]: java.lang.IllegalStateException: 在 SvcRequestPushStatus (OtherClient online) 时遇到了意料之中的问题. 请完整复制此日志提交给 mirai. Failed to find corresponding instanceInfo. 调试信息: RequestPushStatus#2043465411 {
[18:09:46 INFO]:             dataLine=0x01(1)
[18:09:46 INFO]:             nClientType=0x0000000000010101(65793)
[18:09:46 INFO]:             nInstanceId=0x0000000000000001(1)
[18:09:46 INFO]:             nPCVer=0x000000000000169F(5791)
[18:09:46 INFO]:             printable=0x01(1)
[18:09:46 INFO]:             status=0x01(1)
[18:09:46 INFO]:             uin=0x0000000053DC619C(1406951836)
[18:09:46 INFO]:             vecInstanceList=[InstanceInfo(iAppId=1, tablet=0, iPlatform=0, iProductType=0, iClientType=65793)]
[18:09:46 INFO]:             viewFile=0x01(1)
[18:09:46 INFO]:     }
[18:09:46 INFO]:        at net.mamoe.mirai.internal.message.ConversionsKt.contextualBugReportException(conversions.kt:635)
[18:09:46 INFO]:        at net.mamoe.mirai.internal.message.ConversionsKt.contextualBugReportException$default(conversions.kt:633)
[18:09:46 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcRequestPushStatus.decode(MessageSvc.RequestPushStatus.kt:32)
[18:09:46 INFO]:        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcRequestPushStatus$decode$1.invokeSuspend(MessageSvc.RequestPushStatus.kt)
[18:09:46 INFO]:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[18:09:46 INFO]:        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
[18:09:46 INFO]:        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
[18:09:46 INFO]:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
[18:09:46 INFO]:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[18:09:46 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[18:09:46 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
[18:09:46 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[18:09:46 INFO]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[18:09:46 INFO]:`

**Comment by sandtechnology** [comment]
因为缺乏复现环境 已使用QQ账号向机器人账号发起添加好友请求 请问能否将此账号拉到此群后再进行复现？

**Comment by mcdoeswhat** [comment]
> 因为缺乏复现环境 已使用QQ账号向机器人账号发起添加好友请求 请问能否将此账号拉到此群后再进行复现？

群号159176987

**Comment by sandtechnology** [comment]
几次尝试之后发现是我写错了（
已经发送PR，但是如果是这种错误理应也会打印相应Event，请问是否在粘贴过程中出现了遗漏？
如果在含有这个修复的版本仍可重现，欢迎重新打开issue

**Comment by mcdoeswhat** [comment]
> 几次尝试之后发现是我写错了（
> 已经发送PR，但是如果是这种错误理应也会打印相应Event，请问是否在粘贴过程中出现了遗漏？
> 如果在含有这个修复的版本仍可重现，欢迎重新打开issue
没有遗漏,而且事件没触发,我写了监听的,把机器人事件加到mc的bukkit事件里面了,mc的插件没有监听到,无反应

```: [0m2021-01-13 18:12:57 V/Bot 1406951836: [Minecraft永恒1.16.4(159176987)] 傻逼甜甜(1139298297) -> [mirai:source:[177144],[2117952440]]这傻B[0m
[18:13:00] [DefaultDispatcher-worker-5/INFO]: [31m2021-01-13 18:13:00 E/Net 1406951836: Exception in NetworkHandler
[18:13:00] [DefaultDispatcher-worker-5/INFO]: java.lang.NullPointerException: null cannot be cast to non-null type net.mamoe.mirai.internal.contact.NormalMemberImpl
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.OnlinePushPbPushGroupMsg.decode(OnlinePush.PbPushGroupMsg.kt:104)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:508)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:237)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:562)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:557)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:540)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[18:13:00] [DefaultDispatcher-worker-5/INFO]: [0m
[18:13:03] [DefaultDispatcher-worker-5/INFO]: [0m2021-01-13 18:13:03 V/Bot 1406951836: [Minecraft永恒1.16.4(159176987)] 傻逼甜甜(1139298297) -> [mirai:source:[177146],[127299263]]干的这傻逼事[0m```

可以看到上面是其他群员骂人的话== 然后是报错

**Comment by sandtechnology** [comment]
这边显示修复后的代码正常显示了Event 如果在含有这个修复的版本仍可重现，欢迎重新打开issue

**Comment by Him188** [comment]
现在可以使用 2.0.0-dev-2
