### ISSUE TITLE
回复带有图片的好友消息时失败

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai#892]
通过添加QuoteReply对好友消息进行回复时，如果消息中带有图片会发送失败
如果不是回复消息，即消息链中不包含QuoteReply时可以正常发送，消息并没有过大

```
[mirai:image:{6238CCCD-F034-AC1F-A6EF-5B925A9376EA}.jpg]`g command `[mirai:source:[15662],[-741623402]]搜索
java.lang.IllegalStateException: Send friend message failed: MessageSvcPbSendMsg.Response.MessageTooLarge
        at net.mamoe.mirai.internal.contact.UtilKt.sendMessageImpl(util.kt:69)
        at net.mamoe.mirai.internal.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 版本
- mirai-core: `2.0.0`

**Comment by Him188** [comment]
目前好友长消息实现为分片发送, 可能这种方式最大长度限制没群图片那样通过 highway 走的高? consulting @Karlatemp

**Comment by Karlatemp** [comment]
此错误并非是发送错误，而是mirai发送前检查长度导致, 请提供完整原发送信息

for mamoe: 检查 MessageChain.verityLength

**Comment by Karlatemp** [comment]
> 如果消息中带有图片

请问是发送的信息中带有图片, 还是尝试回复的信息中带有图片

**Comment by cssxsh** [comment]
> 如果消息中带有图片
尝试回复的信息

**Comment by cssxsh** [comment]
> > 如果消息中带有图片
> 
> 请问是发送的信息中带有图片, 还是尝试回复的信息中带有图片



> > 如果消息中带有图片
> 
> 请问是发送的信息中带有图片, 还是尝试回复的信息中带有图片

尝试回复的信息

**Comment by cssxsh** [comment]
> > 如果消息中带有图片
> 
> 请问是发送的信息中带有图片, 还是尝试回复的信息中带有图片

尝试回复的信息

**Comment by Karlatemp** [comment]
好友消息 未能成功复现, 但是群聊消息能复现此情况

**Comment by Karlatemp** [comment]
好友信息无法复现请提供错误样本
![Screenshot_2021-01-23-14-38-11-96](https://user-images.githubusercontent.com/30070303/105571161-ba738380-5d88-11eb-93dc-ca07fc03b3fb.png)

**Comment by cssxsh** [comment]
> 好友消息 未能成功复现, 但是群聊消息能复现此情况

测试代码
```
fun MiraiConsole.test(): Unit = GlobalEventChannel.parentScope(this).run {
    subscribeFriendMessages {
        has<Image>().quoteReply("test")
    }
}
```
图片

![01](https://user-images.githubusercontent.com/32539286/105637479-b048a680-5ea8-11eb-8b72-077e0ab15aec.jpg)

日志
```
2021-01-25 00:57:48 V/Bot.3337342367: 1748(1438159989) -> [mirai:source:[7501],[-1178142762]][mirai:image:{099E3212-70EE-BCDC-D4CA-DC4EEF472D33}.jpg]
2021-01-25 00:57:48 E/main: Exception in coroutine <unnamed>
java.lang.IllegalStateException: Send friend message failed: MessageSvcPbSendMsg.Response.MessageTooLarge
        at net.mamoe.mirai.internal.contact.UtilKt.sendMessageImpl(util.kt:69)
        at net.mamoe.mirai.internal.contact.UtilKt$sendMessageImpl$1.invokeSuspend(util.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
