### ISSUE TITLE
2.1版本 登录JAVA报错 NoSuchMethodError: kotlinx/coroutines/JobKt.getJob

### ISSUE THREAD

**Issue by RrrrLin** [mamoe/mirai#896]
由2.0版本更新到2.1版本后，登录过程中时候出现java报错。
2.0版本则无此问题。

```
2021-01-24 09:19:21 I/Bot : Logging in...
Exception in thread "main" java.lang.NoSuchMethodError: kotlinx/coroutines/JobKt.getJob(Lkotlin/coroutines/CoroutineContext;)Lkotlinx/coroutines/Job; (loaded from file:/C:/Users/XU/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core/1.3.3/kotlinx-coroutines-core-1.3.3.jar by sun.misc.Launcher$AppClassLoader@81a7da1a) called from class kotlinx.coroutines.InterruptibleKt (loaded from file:/C:/Users/XU/.m2/repository/org/jetbrains/kotlinx/kotlinx-coroutines-core-jvm/1.4.1/kotlinx-coroutines-core-jvm-1.4.1.jar by sun.misc.Launcher$AppClassLoader@81a7da1a).
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:43)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
```

#### 版本
- mirai-core: `2.1.0` 

#### 补充信息

jdk openjdk1.8

**Comment by Him188** [comment]
使用了错误的依赖，通常 Maven 会有这个问题（无法正确处理间接依赖）。可以显式添加依赖 
groupId        org.jetbrains.kotlinx  
artifactId     kotlinx-coroutines-core
version        1.4.0

**Comment by Him188** [comment]
但我也不知道为什么2.0没有问题

**Comment by Him188** [comment]
如何通过上述添加依赖仍无法解决问题，请尝试更换依赖的 mirai `mirai-core-jvm` 为 `mirai-core` （去除`-jvm`后缀）。

实在不行可以使用 Gradle。

**Comment by Lin-XCC** [comment]
> 使用了错误的依赖，通常 Maven 会有这个问题（无法正确处理间接依赖）。可以显式添加依赖
> groupId org.jetbrains.kotlinx
> artifactId kotlinx-coroutines-core
> version 1.4.0

在使用maven进行显示依赖时
Could not find artifact org.jetbrains.kotlin:kotlin-coroutines-core:pom:1.4.0 in jcenter (https://jcenter.bintray.com/)

**Comment by RrrrLin** [comment]
> 使用了错误的依赖，通常 Maven 会有这个问题（无法正确处理间接依赖）。可以显式添加依赖
> groupId org.jetbrains.kotlinx
> artifactId kotlinx-coroutines-core
> version 1.4.0

感谢，显式添加依赖以后正常运行了。
