### ISSUE TITLE
2.1.0掉线后无法登录

### ISSUE THREAD

**Issue by VoyagerII** [mamoe/mirai#907]
```
[0m2021-01-25 18:58:47 V/Net 23737*****: Recv: ConfigPushSvc.PushReq.PushReqResponse.Success[0m
[96m2021-01-25 18:58:47 D/Net 23737*****: Received unknown commandName: ConfigPushSvc.PushDomain[0m
[0m2021-01-25 18:58:47 V/Net 23737*****: Send: ConfigPushSvc.PushResp[0m
[92m2021-01-25 18:58:47 I/Net 23737*****: Connected to server 42.81.172.81:80[0m
[0m2021-01-25 18:58:47 V/Net 23737*****: Send: wtlogin.login[0m
[0m2021-01-25 18:58:47 V/Net 4676*****: Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Send: wtlogin.login[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Recv: LoginPacketResponse.Success[0m
[92m2021-01-25 18:58:48 I/Net 4676*****: Login successful[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Send: StatSvc.register[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Recv: Response(StatSvc.register)[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Send: StatSvc.GetDevLoginInfo[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=1)[0m
[92m2021-01-25 18:58:48 I/Bot 4676*****: Online OtherClients: [0m
[92m2021-01-25 18:58:48 I/Bot 4676*****: Login successful[0m
[92m2021-01-25 18:58:48 I/Bot 4676*****: Reconnected successfully in 3min 41.343s[0m
[92m2021-01-25 18:58:48 I/Bot 4676*****: Connection lost, retrying login[0m
[92m2021-01-25 18:58:48 I/Net 23737*****: Syncing friend message history...[0m
[92m2021-01-25 18:58:48 I/Net 4676*****: Syncing friend message history...[0m
[0m2021-01-25 18:58:48 V/Net 23737*****: Send: MessageSvc.PbGetMsg[0m
[92m2021-01-25 18:58:48 I/Bot 4676*****: Logging in...[0m
[31m2021-01-25 18:58:48 E/Net 4676*****: Exception in NetworkHandler
java.lang.IllegalStateException: network is dead therefore can't send any packet
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:748)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect$default(QQAndroidBotNetworkHandler.kt:743)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invokeSuspend(QQAndroidBotNetworkHandler.kt:510)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invoke(QQAndroidBotNetworkHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
        at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
        at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:104)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.syncMessageSvc(QQAndroidBotNetworkHandler.kt:508)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$listener$1$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:501)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
[92m2021-01-25 18:58:48 I/Net 23737*****: Syncing friend message history...[0m
[0m2021-01-25 18:58:48 V/Net 23737*****: Send: MessageSvc.PbGetMsg[0m
[92m2021-01-25 18:58:48 I/Net 4676*****: Connected to server 42.81.172.81:80[0m
[91m2021-01-25 18:58:48 W/Net 23737*****: Network force offline: returnCode = -10008[0m
[91m2021-01-25 18:58:48 W/Net 23737*****: Network force offline: returnCode = -10008[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Send: wtlogin.login[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Send: wtlogin.login[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Recv: LoginPacketResponse.Success[0m
[92m2021-01-25 18:58:48 I/Net 4676*****: Login successful[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Send: StatSvc.register[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Recv: Response(StatSvc.register)[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Send: StatSvc.GetDevLoginInfo[0m
[0m2021-01-25 18:58:48 V/Net 4676*****: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=1)[0m
[92m2021-01-25 18:58:48 I/Bot 4676*****: Online OtherClients: [0m
[92m2021-01-25 18:58:48 I/Bot 4676*****: Login successful[0m
[92m2021-01-25 18:58:48 I/Bot 4676*****: Reconnected successfully in 0.586s[0m
[92m2021-01-25 18:58:48 I/Bot 23737*****: Connection lost, retrying login[0m
[92m2021-01-25 18:58:48 I/Net 23737*****: Syncing friend message history...[0m
[92m2021-01-25 18:58:48 I/Net 4676*****: Syncing friend message history...[0m
[0m2021-01-25 18:58:48 V/Net 23737*****: Send: MessageSvc.PbGetMsg[0m
[92m2021-01-25 18:58:48 I/Bot 4676*****: Logging in...[0m
[31m2021-01-25 18:58:48 E/Net 4676*****: Exception in NetworkHandler
java.lang.IllegalStateException: network is dead therefore can't send any packet
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:748)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect$default(QQAndroidBotNetworkHandler.kt:743)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invokeSuspend(QQAndroidBotNetworkHandler.kt:510)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invoke(QQAndroidBotNetworkHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
        at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
        at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:104)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.syncMessageSvc(QQAndroidBotNetworkHandler.kt:508)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$listener$1$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:501)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m


版本：2.1.0


补充：

[0m2021-01-25 21:51:54 V/Net 23737*****: Send: StatSvc.GetDevLoginInfo[0m
[0m2021-01-25 21:51:54 V/Net 23737*****: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=2)[0m
[0m2021-01-25 21:51:54 V/Bot 23737*****: Event: OtherClientOnlineEvent(client=OtherClient(bot=23737*****,deviceName=DESKTOP-FO0TRRP,platform=WINDOWS), kind=MOBILE_PC_QQ)[0m
[0m2021-01-25 21:51:58 V/Net 4676*****: Send: OnlinePush.RespPush[0m
[0m2021-01-25 21:52:00 V/Net 4676*****: Recv: RequestPushNotify(uin=4676*****, ctype=1, strService=MessageSvc, strCmd=PushNotify, usMsgType=33, stMsgInfo=net.mamoe.mirai.internal.network.protocol.data.jce.MsgInfo@5c499723)[0m
[0m2021-01-25 21:52:00 V/Net 4676*****: Send: MessageSvc.PbGetMsg[0m
[31m2021-01-25 21:52:00 E/Net 4676*****: Exception in NetworkHandler
java.lang.NullPointerException: null cannot be cast to non-null type net.mamoe.mirai.internal.contact.NormalMemberImpl
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.OnlinePushPbPushGroupMsg.decode(OnlinePush.PbPushGroupMsg.kt:109)
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.handleIncomingPacket$mirai_core(PacketFactory.kt:513)
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:242)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:578)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:573)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:556)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
[0m2021-01-25 21:52:00 V/Net 4676*****: Send: MessageSvc.PbDeleteMsg[0m
[0m2021-01-25 21:52:00 V/Bot 4676*****: Event: MemberJoinEvent.Active(member=32463*****)[0m
[0m2021-01-25 21:52:00 V/Net 4676*****: Send: MessageSvc.PbGetMsg[0m
[0m2021-01-25 21:52:00 V/Net 4676*****: Send: MessageSvc.PbDeleteMsg[0m











[0m2021-01-25 21:53:53 V/Bot 4676*****: [*****团(9287*****)] 樱(21404*****) -> .rd[0m
.rd=88
[0m2021-01-25 21:53:53 V/Net 4676*****: Send: MessageSvc.PbSendMsg[0m
[91m2021-01-25 21:53:53 W/Net 4676*****: Network force offline: returnCode = -10008[0m
[92m2021-01-25 21:53:53 I/Bot 4676*****: Connection lost, retrying login[0m
[92m2021-01-25 21:53:53 I/Bot 4676*****: Connection lost, retrying login[0m
[0m2021-01-25 21:53:53 V/Bot 4676*****: Group(9287*****) <- [mirai:at:21404*****].rd=88[0m
[92m2021-01-25 21:53:53 I/Bot 4676*****: Logging in...[0m
[92m2021-01-25 21:53:53 I/Bot 23737*****: Logging in...[0m
[92m2021-01-25 21:53:53 I/Net 23737*****: Syncing friend message history...[0m
[92m2021-01-25 21:53:53 I/Net 23737*****: Connected to server 114.221.144.215:80[0m
[0m2021-01-25 21:53:53 V/Net 23737*****: Send: MessageSvc.PbGetMsg[0m
[92m2021-01-25 21:53:53 I/Net 4676*****: Connected to server 42.81.172.81:80[0m
[0m2021-01-25 21:53:53 V/Net 4676*****: Send: wtlogin.login[0m
[0m2021-01-25 21:53:53 V/Net 23737*****: Send: wtlogin.login[0m
[91m2021-01-25 21:53:53 W/Net 23737*****: Network force offline: returnCode = -10008[0m
[31m2021-01-25 21:53:53 E/Net 4676*****: Exception in NetworkHandler
net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$14$1.invoke(JvmMethodListenersInternal.kt:147)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$14$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor152.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$14$1.invoke(JvmMethodListenersInternal.kt:140)
        ... 7 more
Caused by: java.util.concurrent.CancellationException: NetworkHandler closed
        at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
        at net.mamoe.mirai.internal.network.BotNetworkHandler.close(BotNetworkHandler.kt:110)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.close(QQAndroidBotNetworkHandler.kt:803)
        at net.mamoe.mirai.internal.AbstractBot$Reconnect.reconnect(AbstractBot.kt:176)
        at net.mamoe.mirai.internal.AbstractBot$offlineListener$1.invokeSuspend(AbstractBot.kt:154)
        at net.mamoe.mirai.internal.AbstractBot$offlineListener$1.invoke(AbstractBot.kt)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invokeSuspend(EventChannel.kt:393)
        at net.mamoe.mirai.event.EventChannel$subscribeAlways$1.invoke(EventChannel.kt)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invokeSuspend(InternalEventListeners.kt:49)
        at net.mamoe.mirai.internal.event.Handler$onEvent$2.invoke(InternalEventListeners.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.internal.event.Handler.onEvent(InternalEventListeners.kt:49)
        at net.mamoe.mirai.internal.event.InternalEventListenersKt$callAndRemoveIfRequired$3$invokeSuspend$$inlined$forEach0$lambda$1.invokeSuspend(InternalEventListeners.kt:142)
        ... 6 more
Caused by: net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories$PacketFactoryIllegalStateException: returnCode = -10008
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseSsoFrame(PacketFactory.kt:325)
        at net.mamoe.mirai.internal.network.protocol.packet.KnownPacketFactories.parseIncomingPacket(PacketFactory.kt:228)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.generifiedParsePacket(QQAndroidBotNetworkHandler.kt:578)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.parsePacket(QQAndroidBotNetworkHandler.kt:573)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$parsePacketAsync$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:556)
        ... 6 more
[0m
[0m2021-01-25 21:53:53 V/Net 23737*****: Recv: LoginPacketResponse.Success[0m
[92m2021-01-25 21:53:53 I/Net 23737*****: Login successful[0m
[0m2021-01-25 21:53:53 V/Net 23737*****: Send: StatSvc.register[0m
[0m2021-01-25 21:53:54 V/Net 23737*****: Recv: Response(StatSvc.register)[0m
[0m2021-01-25 21:53:54 V/Net 23737*****: Send: StatSvc.GetDevLoginInfo[0m
[0m2021-01-25 21:53:54 V/Net 23737*****: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=2)[0m
[92m2021-01-25 21:53:54 I/Bot 23737*****: Online OtherClients: DESKTOP-FO0TRRP(WINDOWS)[0m
[92m2021-01-25 21:53:54 I/Bot 23737*****: Login successful[0m
[92m2021-01-25 21:53:54 I/Bot 23737*****: Reconnected successfully in 0.613s[0m
[92m2021-01-25 21:53:54 I/Net 4676*****: Syncing friend message history...[0m
[92m2021-01-25 21:53:54 I/Bot 23737*****: Connection lost, retrying login[0m
[91m2021-01-25 21:53:54 W/Net 4676*****: Network force offline: returnCode = -10008[0m
[0m2021-01-25 21:53:54 V/Net 4676*****: Send: MessageSvc.PbGetMsg[0m
[92m2021-01-25 21:53:54 I/Net 23737*****: Syncing friend message history...[0m
[31m2021-01-25 21:53:54 E/Net 23737*****: Exception in NetworkHandler
java.lang.IllegalStateException: network is dead therefore can't send any packet
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:748)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect$default(QQAndroidBotNetworkHandler.kt:743)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invokeSuspend(QQAndroidBotNetworkHandler.kt:510)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invoke(QQAndroidBotNetworkHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
        at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
        at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:104)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.syncMessageSvc(QQAndroidBotNetworkHandler.kt:508)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$listener$1$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:501)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
[92m2021-01-25 21:53:54 I/Bot 23737*****: Logging in...[0m
[92m2021-01-25 21:53:54 I/Net 4676*****: Syncing friend message history...[0m
[0m2021-01-25 21:53:54 V/Net 4676*****: Send: MessageSvc.PbGetMsg[0m
[91m2021-01-25 21:53:54 W/Net 4676*****: Network force offline: returnCode = -10008[0m
[92m2021-01-25 21:53:54 I/Net 23737*****: Connected to server 42.81.172.147:443[0m
[0m2021-01-25 21:53:54 V/Net 23737*****: Send: wtlogin.login[0m
[0m2021-01-25 21:53:54 V/Net 23737*****: Recv: LoginPacketResponse.Success[0m
[92m2021-01-25 21:53:54 I/Net 23737*****: Login successful[0m
[0m2021-01-25 21:53:54 V/Net 23737*****: Send: StatSvc.register[0m
[0m2021-01-25 21:53:54 V/Net 23737*****: Recv: Response(StatSvc.register)[0m
[0m2021-01-25 21:53:54 V/Net 23737*****: Send: StatSvc.GetDevLoginInfo[0m
[0m2021-01-25 21:53:54 V/Net 23737*****: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=2)[0m
[92m2021-01-25 21:53:54 I/Bot 23737*****: Online OtherClients: DESKTOP-FO0TRRP(WINDOWS)[0m
[92m2021-01-25 21:53:54 I/Bot 23737*****: Login successful[0m
[92m2021-01-25 21:53:54 I/Bot 23737*****: Reconnected successfully in 0.601s[0m
[92m2021-01-25 21:53:54 I/Net 23737*****: Syncing friend message history...[0m
[92m2021-01-25 21:53:54 I/Bot 23737*****: Connection lost, retrying login[0m
[92m2021-01-25 21:53:54 I/Net 4676*****: Syncing friend message history...[0m
[92m2021-01-25 21:53:54 I/Bot 23737*****: Logging in...[0m
[0m2021-01-25 21:53:54 V/Net 23737*****: Send: MessageSvc.PbGetMsg[0m
[92m2021-01-25 21:53:54 I/Net 4676*****: Syncing friend message history...[0m
[0m2021-01-25 21:53:54 V/Net 4676*****: Send: MessageSvc.PbGetMsg[0m
[0m2021-01-25 21:53:54 V/Net 4676*****: Send: MessageSvc.PbGetMsg[0m
[91m2021-01-25 21:53:54 W/Net 4676*****: Network force offline: returnCode = -10008[0m
[91m2021-01-25 21:53:54 W/Net 4676*****: Network force offline: returnCode = -10008[0m
[92m2021-01-25 21:53:54 I/Net 23737*****: Connected to server 42.81.172.81:80[0m
[0m2021-01-25 21:53:54 V/Net 23737*****: Send: wtlogin.login[0m
[0m2021-01-25 21:53:55 V/Net 23737*****: Recv: LoginPacketResponse.Success[0m
[92m2021-01-25 21:53:55 I/Net 23737*****: Login successful[0m
[0m2021-01-25 21:53:55 V/Net 23737*****: Send: StatSvc.register[0m
```

在发生群员变动时会抛出异常。

**Comment by Him188** [comment]
将合并到 #900 处理
