### ISSUE TITLE
尝试发送群组音乐分享时报错 imagent service_error:. group deleted

### ISSUE THREAD

**Issue by yyuueexxiinngg** [mamoe/mirai#918]
如题, 尝试发送群组音乐分享时报错`Send group music share failed. result=901507, errorMsg=imagent service_error:. group deleted`

```
2021-01-26 19:08:41 E/OneBot: java.lang.IllegalStateException: Send group music share failed. result=901507, errorMsg=imagent service_error:. group deleted
java.lang.IllegalStateException: Send group music share failed. result=901507, errorMsg=imagent service_error:. group deleted
	at net.mamoe.mirai.internal.network.protocol.data.proto.OidbSso$OIDBSSOPkg.checkSuccess(OIDB.kt:968)
	at net.mamoe.mirai.internal.contact.GroupSendMessageImplKt.sendMessagePacket(GroupSendMessageImpl.kt:160)
	at net.mamoe.mirai.internal.contact.GroupSendMessageImplKt$sendMessagePacket$1.invokeSuspend(GroupSendMessageImpl.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 复现

仅在某些群组中发送失败, 测试数据
`GroupMessagePreSendEvent(target=Group(****), message=MusicShare(kind=NeteaseCloudMusic, title=ファッション, summary=rinahamu/Yunomi, jumpUrl=http://music.163.com/song/1338728297/?userid=324076307, pictureUrl=http://p2.music.126.net/y19E5SadGUmSR8SZxkrNtw==/109951163785855539.jpg, musicUrl=http://music.163.com/song/media/outer/url?id=1338728297&userid=324076307, brief=[分享] ファッション))`

#### 版本
- mirai-core: `2.1.0`

**Comment by Him188** [comment]
猜测是 code 和 uin 问题
