### ISSUE TITLE
一段时间后会掉线，重连超时

### ISSUE THREAD

**Issue by TopYjj** [mamoe/mirai#924]
```
2021-01-27 19:20:27 I/Net 111111111: Connected to server 42.81.172.147:443
2021-01-27 19:20:27 V/Net 111111111: Send: wtlogin.login
2021-01-27 19:20:32 W/Bot 111111111: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:158)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:128)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:68)
	at java.lang.Thread.run(Thread.java:748)

```

#### 复现

登录后一切正常，包括我自己写的各种功能。过了6~8小时左右会掉线，服务器是阿里云centos7.3

#### 版本
- mirai-core-jvm: `2.1.0`

**Comment by Him188** [comment]
尝试 2.2.0-dev-4

**Comment by Him188** [comment]
如果使用 2.2.0+ 后仍有问题，请 reopen issue
