### ISSUE TITLE
将一个正常运行的机器人挤下线之后，所有机器人无法发送消息

### ISSUE THREAD

**Issue by eli-zhai** [mamoe/mirai#925]
将一个正常运行的机器人踢下线之后，所有机器人无法发送消息

详细代码：
Bot bot = null;
                try {
                    bot = Bot.getInstance(qqRedirect.getFromRobot());
                } catch (NoSuchElementException e) {
                    HttpUtils.handleResponse(httpExchange, 400, e.getMessage() + "：未登录");
                    return;
                }
                Friend friend = bot.getFriend(qqRedirect.getToQQ());

```
java.lang.IllegalStateException: network is dead therefore can't send any packet
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:758)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect$default(QQAndroidBotNetworkHandler.kt:753)
	at net.mamoe.mirai.internal.contact.UtilKt.sendMessageImpl(util.kt:70)
	at net.mamoe.mirai.internal.contact.FriendImpl.sendMessage(FriendImpl.kt:86)
	at net.mamoe.mirai.contact.Friend$$sendMessage$$bb$mZUD0Vk.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at net.mamoe.kjbb.internal.RunBlockingKt.$runSuspend$(RunBlocking.kt:18)
	at net.mamoe.mirai.contact.Friend.sendMessage(Friend.kt)
	at cn.linann.Robot.http.handler.utils.MessageO.sendMsg(MessageO.java:54)
	at cn.linann.Robot.http.handler.sendPrivateMsgHandler.handle(sendPrivateMsgHandler.java:42)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

#### 复现

1. 登录全部机器人；
2. 挤掉任意一个机器人
3. 用任意一个机器人发送请求，报错 network is dead therefore can't send any packet

#### 版本
- mirai-core: `2.1.1` 

#### 补充信息

日志输出

[0m2021-01-27 21:12:50 V/Net 2941767580: Event: Force(bot=Bot(2941767580), title=下线通知, message=你的帐号于21:12在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。)
[0m

[92m2021-01-27 21:12:50 I/Net 2941767580: Connection occupied by another android device: 你的帐号于21:12在另一台Android手机登录了QQ。如非本人操作，则密码可能已泄露，建议前往http://aq.qq.com/修改密码或紧急冻结帐号。[0m

**Comment by xszqxszq** [comment]
请问这个问题怎么解决的，我只能通过删device.json改新设备强行登上

**Comment by Him188** [comment]
换最新版
