### ISSUE TITLE
一个机器人close后，其他机器人也会被close

### ISSUE THREAD

**Issue by eli-zhai** [mamoe/mirai#926]
当一个机器人被挤掉之后，其他机器人发消息会报错 ：java.lang.IllegalStateException: network is dead therefore can't send any packet

当一个机器人close之后，同样会报错 java.lang.IllegalStateException: network is dead therefore can't send any packet

当一个机器人冻结（改密码之后），会报错 kotlin.UninitializedPropertyAccessException: lateinit property wLoginSigInfo has not been initialized

```
java.lang.IllegalStateException: network is dead therefore can't send any packet
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:758)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect$default(QQAndroidBotNetworkHandler.kt:753)
	at net.mamoe.mirai.internal.contact.GroupSendMessageImplKt.sendMessagePacket(GroupSendMessageImpl.kt:126)
	at net.mamoe.mirai.internal.contact.GroupSendMessageImplKt.sendMessageImpl(GroupSendMessageImpl.kt:54)
	at net.mamoe.mirai.internal.contact.GroupImpl.sendMessage(GroupImpl.kt:119)
	at net.mamoe.mirai.contact.Group$$sendMessage$$bb$mZUD0Vk.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at net.mamoe.kjbb.internal.RunBlockingKt.$runSuspend$(RunBlocking.kt:18)
	at net.mamoe.mirai.contact.Group.sendMessage(Group.kt)
	at cn.linann.Robot.http.handler.utils.MessageO.sendMsg(MessageO.java:54)
	at cn.linann.Robot.http.handler.sendGroupMsgHandler.handle(sendGroupMsgHandler.java:42)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


kotlin.UninitializedPropertyAccessException: lateinit property wLoginSigInfo has not been initialized
	at net.mamoe.mirai.internal.network.QQAndroidClient.getWLoginSigInfo(QQAndroidClient.kt:320)
	at net.mamoe.mirai.internal.contact.GroupSendMessageImplKt.sendMessagePacket(GroupSendMessageImpl.kt:331)
	at net.mamoe.mirai.internal.contact.GroupSendMessageImplKt.sendMessageImpl(GroupSendMessageImpl.kt:54)
	at net.mamoe.mirai.internal.contact.GroupImpl.sendMessage(GroupImpl.kt:119)
	at net.mamoe.mirai.contact.Group$$sendMessage$$bb$mZUD0Vk.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at net.mamoe.kjbb.internal.RunBlockingKt.$runSuspend$(RunBlocking.kt:18)
	at net.mamoe.mirai.contact.Group.sendMessage(Group.kt)
	at cn.linann.Robot.http.handler.utils.MessageO.sendMsg(MessageO.java:54)
	at cn.linann.Robot.http.handler.sendGroupMsgHandler.handle(sendGroupMsgHandler.java:42)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

#### 版本
- mirai-core: `2.1.1`

**Comment by Him188** [comment]
Bot 之间不会有影响, 检查 `BotConfiguration.parentCoroutineContext`

**Comment by Him188** [comment]
Bot 之间不会有影响, 检查 `BotConfiguration.parentCoroutineContext`

**Comment by linann-zhai** [comment]
全部都是，EmptyCoroutineContext

**Comment by linann-zhai** [comment]
我使用这个方法生成的bot，请问是我使用错了嘛
Bot bot = BotFactory.INSTANCE.newBot

**Comment by linann-zhai** [comment]
我用Java进行开发的

**Comment by sandtechnology** [comment]
请确保BotConfiguration的实例不被共享

**Comment by linann-zhai** [comment]
Bot bot = BotFactory.INSTANCE.newBot(qq.getQq(), qq.getPassword(), new BotConfiguration() {{
                fileBasedDeviceInfo("device.json"); // 使用 device.json 存储设备信息
                setProtocol(finalMiraiProtocol); // 切换协议
                String s = "log/" + qq.getQq() + ".log";
                autoReconnectOnForceOffline();
                redirectNetworkLogToFile(new File(s));
                redirectBotLogToFile(new File(s));
            }});

我每次都是new的BotConfiguration

**Comment by eli-zhai** [comment]
> 请确保BotConfiguration的实例不被共享

Bot bot = BotFactory.INSTANCE.newBot(qq.getQq(), qq.getPassword(), new BotConfiguration() {{
fileBasedDeviceInfo("device.json"); // 使用 device.json 存储设备信息
setProtocol(finalMiraiProtocol); // 切换协议
String s = "log/" + qq.getQq() + ".log";
autoReconnectOnForceOffline();
redirectNetworkLogToFile(new File(s));
redirectBotLogToFile(new File(s));
}});

我每次都是new的BotConfiguration

**Comment by eli-zhai** [comment]
> Bot 之间不会有影响, 检查 `BotConfiguration.parentCoroutineContext`

我用Java进行开发的，全部都是，EmptyCoroutineContext，我使用这个方法生成的bot，请问是我使用错了嘛
Bot bot = BotFactory.INSTANCE.newBot

**Comment by sandtechnology** [comment]
没有问题 请确认发送的bot不是掉线的bot

**Comment by eli-zhai** [comment]
> 没有问题 请确认发送的bot不是掉线的bot

确认，尝试过多次

**Comment by eli-zhai** [comment]
kotlin.UninitializedPropertyAccessException: lateinit property wLoginSigInfo has not been initialized
如果修改密码之后，所有机器人都报错，获取存活的机器人时，已经因修改密码下线的机器人依旧能获取
sendMessage时报的错
at net.mamoe.mirai.contact.Group.sendMessage(Group.kt)

**Comment by Him188** [comment]
所以问题实际上是 bot 掉线后仍然能通过 Bot.getInstances() 获取到？

**Comment by eli-zhai** [comment]
> 所以问题实际上是 bot 掉线后仍然能通过 Bot.getInstances() 获取到？

都有吧，反正一个机器人挂了，其他机器人也无法使用，报错就是上面那些

**Comment by eli-zhai** [comment]
> Bot 之间不会有影响, 检查 `BotConfiguration.parentCoroutineContext`

我今天使用kotlin试了试，输出还是EmptyCoroutineContext，
这是我的代码：
```kotlin
suspend fun main() {

    val bot = BotFactory.newBot(qq, pwd) {
        fileBasedDeviceInfo("device.json") // 使用 device.json 存储设备信息
        protocol = BotConfiguration.MiraiProtocol.ANDROID_PAD // 切换协议
        autoReconnectOnForceOffline()
        redirectNetworkLogToFile()
//        redirectBotLogToFile()
    }.alsoLogin()
    val bot2 = BotFactory.newBot(qq, pwd) {
        fileBasedDeviceInfo("device.json") // 使用 device.json 存储设备信息
        protocol = BotConfiguration.MiraiProtocol.ANDROID_PAD // 切换协议
//        val s = "log/" + 2765887760 + ".log"
        autoReconnectOnForceOffline()
        redirectNetworkLogToFile()
//        redirectBotLogToFile()
    }.alsoLogin()
//    bot.join()
    println(bot.configuration.parentCoroutineContext)
    println(bot2.configuration.parentCoroutineContext)
    var friend = bot.getFriend(qq)
    friend?.sendMessage("1231")
}
```

**Comment by sulinwork** [comment]
1.我使用的是2.2.2版本 也现在了这个问题 执行了某一个bot的close() 方法  其他的bot的事件通道也会close
2021-02-01 14:01:35 V/Net 1527938786: Channel closed.
*******BotOfflineEvent*********
Active(bot=Bot(1527938786), cause=null)
2021-02-01 14:01:35 V/Net 1278981219: Channel closed.

2.从Bot.getInstances()返回的实例中 close的bot就会删除  另一个则存在但是isOnline会变成false
3.BotConfiguration.parentCoroutineContext 两个的hashcode完全一致

**Comment by Him188** [comment]
已经找到原因, 将在 #953 继续处理

**Comment by eli-zhai** [comment]
一个机器人close后，其他机器人也会被
