### ISSUE TITLE
当图片的Image的id格式为[mirai:image:0BADBADBAD1652429311]转发消息抛出异常。

### ISSUE THREAD

**Issue by BBplux** [mamoe/mirai#933]
当图片的Image的id为下面格式时，无法发送该图片。
[mirai:image:0BADBADBAD1652429311]

```
2021-01-29 22:14:19 V/Bot 3315863382: [机器人测试(282049110)] 喜欢笑ya(517822568) -> 4.饿了吗外卖红包 WX扫码 \n最近外卖红包都比之前大\n互不冲突 都领下 用最大的 [mirai:image:0BADBADBAD1652429311]
java.lang.IllegalStateException: illegal imageId: 0BADBADBAD1652429311. ImageId must match Regex `/[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}`, `/[0-9]*-[0-9]*-[0-9a-fA-F]{32}` or `\{[0-9a-fA-F]{8}-([0-9a-fA-F]{4}-){3}[0-9a-fA-F]{12}\}\..{3,5}`
	at net.mamoe.mirai.message.data.MessageUtils__ImplKt.calculateImageMd5ByImageId(impl.kt:255)
	at net.mamoe.mirai.message.data.MessageUtils.calculateImageMd5ByImageId(Unknown Source)
	at net.mamoe.mirai.message.data.MessageUtils__ImageKt.calculateImageMd5(Image.kt:213)
	at net.mamoe.mirai.message.data.MessageUtils.calculateImageMd5(Unknown Source)
	at net.mamoe.mirai.internal.contact.GroupSendMessageImplKt.updateFriendImageForGroupMessage(GroupSendMessageImpl.kt:244)
	at net.mamoe.mirai.internal.contact.GroupSendMessageImplKt.sendMessageImpl(GroupSendMessageImpl.kt:50)
	at net.mamoe.mirai.internal.contact.GroupImpl.sendMessage(GroupImpl.kt:119)
	at net.mamoe.mirai.contact.Group$$sendMessage$$bb$mZUD0Vk.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at net.mamoe.kjbb.internal.RunBlockingKt.$runSuspend$(RunBlocking.kt:18)

```

#### 复现

监控其他群的消息时，直接使用bot.getGroup(id).sendMessage(event.getMessage());方法转发给其他群时会出现这个问题。

#### 版本
- mirai-core: `2.1.1`

**Comment by Nambers** [comment]
嗯？据我所知,，miraiCode的image不应该是`[mirai:image:{xxx}.ext]`吗？

**Comment by Nambers** [comment]
```
图片的 id.
图片 id 不一定会长时间保存, 也可能在将来改变格式, 因此不建议使用 id 发送图片.
格式
所有图片的 id 都满足正则表达式 IMAGE_ID_REGEX. 示例: {01E9451B-70ED-EAE3-B37C-101F1EEBF5B5}.ext (ext 为文件后缀, 如 png)
```
见`net.mamoe.mirai.message.data.Image`

**Comment by Karlatemp** [comment]
请提供复现步骤

**Comment by Him188** [comment]
OnlineGroupImageImpl
```kotlin
    override val imageId: String = generateImageId(
        delegate.picMd5,
        delegate.filePath.substringAfterLast('.').toLowerCase().let { ext ->
            if (ext == "null") {
                // official clients might send `null`
                getImageType(delegate.imageType)
            } else ext
        }
    ).takeIf {
        IMAGE_ID_REGEX.matches(it)
    } ?: generateImageId(delegate.picMd5)
```

OnlineFriendImageImpl
```kotlin
 override val imageId: String =
        generateImageIdFromResourceId(delegate.resId, getImageType(delegate.imgType)) ?: delegate.resId
```



OfflineFriendImage
contact/AbstractUser.kt:73
```kotlin
            is LongConn.OffPicUp.Response.FileExists -> OfflineFriendImage(
                imageId = generateImageIdFromResourceId(
                    resourceId = resp.resourceId,
```

**Comment by Him188** [comment]
可能出问题的是 `?: delegate.resId`, ` ?: resp.resourceId`

- [x] OnlineFriendImageImpl
```kotlin
 override val imageId: String =
        generateImageIdFromResourceId(delegate.resId, getImageType(delegate.imgType)) ?: delegate.resId
```

- [x] OfflineFriendImage
contact/AbstractUser.kt:73
```kotlin
is LongConn.OffPicUp.Response.FileExists -> OfflineFriendImage(
    imageId = generateImageIdFromResourceId(
        resourceId = resp.resourceId,
        format = getImageType(resp.imageInfo.fileType).takeIf { it != ExternalResource.DEFAULT_FORMAT_NAME }
            ?: resource.formatName
    ) ?: resp.resourceId
).also {
    ImageUploadEvent.Succeed(this, resource, it).broadcast()
}
```

要添加检查
