### ISSUE TITLE
Bot掉线重连报错

### ISSUE THREAD

**Issue by Itsusinn** [mamoe/mirai#935]
运行一段时间后（数小时，也有刚启动就产生此类错误的情况）
Bot掉线，尝试重连，重连失败

```
2021-01-30 20:17:09 I/Net ***5636716: Syncing friend message history...
2021-01-30 20:17:09 V/Net ***5636716: Send: MessageSvc.PbGetMsg
2021-01-30 20:17:09 V/Net ***5636716: Recv: StatSvc.GetDevLoginInfo.Response(deviceList.size=0)
2021-01-30 20:17:09 I/Net ***9312013: Syncing friend message history...
2021-01-30 20:17:09 E/Net ***9312013: Exception in NetworkHandler
java.lang.IllegalStateException: network channel is closed
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:749)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect$default(QQAndroidBotNetworkHandler.kt:743)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invokeSuspend(QQAndroidBotNetworkHandler.kt:510)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invoke(QQAndroidBotNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:104)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.syncMessageSvc(QQAndroidBotNetworkHandler.kt:508)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$listener$1$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:501)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-01-30 20:17:09 I/Net ***5636716: Syncing friend message history...
2021-01-30 20:17:09 E/Net ***5636716: Exception in NetworkHandler
java.net.SocketException: Socket closed
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at net.mamoe.mirai.internal.utils.PlatformSocket$send$2.invoke(PlatformSocket.kt:57)
	at net.mamoe.mirai.internal.utils.PlatformSocket$send$2.invoke(PlatformSocket.kt:30)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:46)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2021-01-30 20:17:09 I/Net ***9312013: Syncing friend message history...
2021-01-30 20:17:09 E/Net ***9312013: Exception in NetworkHandler
java.lang.IllegalStateException: network channel is closed
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect(QQAndroidBotNetworkHandler.kt:749)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.sendAndExpect$default(QQAndroidBotNetworkHandler.kt:743)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invokeSuspend(QQAndroidBotNetworkHandler.kt:510)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invoke(QQAndroidBotNetworkHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
	at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:104)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.syncMessageSvc(QQAndroidBotNetworkHandler.kt:508)
	at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$listener$1$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:501)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
（附完整日志）
[log.tar.gz](https://github.com/mamoe/mirai/files/5898063/log.tar.gz)

#### 复现

**推测可能**是登录两个Bot导致的问题，因为以前单Bot未遇到此类问题

#### 版本
- mirai-core: `2.2.2` 
- mirai-console: `2.2.2`

Booted by MCL

**Comment by Him188** [comment]
请使用 2.2.1 再观察是否还有这个情况

**Comment by Itsusinn** [comment]
[https://github.com/mamoe/mirai/issues/936#issuecomment-770332527](url)
推测有某些关联，观察中

**Comment by Itsusinn** [comment]
此问题依旧，不过异常输出稍有不同
日志文件：
[2021-02-01.log](https://github.com/mamoe/mirai/files/5901833/2021-02-01.log)

**Comment by sandtechnology** [comment]
> 2021-02-01 11:23:24 I/Net ***9312013: Connected to server 113.96.13.125:8080
> 2021-02-01 11:23:24 I/Net ***9312013: Connected to server 114.221.148.179:14000
> 2021-02-01 11:23:24 I/Net ***9312013: Connected to server 42.81.192.226:443
> 2021-02-01 11:23:24 I/Net ***9312013: Connected to server msfwifi.3g.qq.com:8080
> 2021-02-01 11:23:24 I/Net ***9312013: Connected to server 42.81.172.207:443
> 2021-02-01 11:23:24 I/Net ***9312013: Connected to server 125.94.60.148:14000
> 2021-02-01 11:23:24 I/Net ***9312013: Connected to server 42.81.172.22:80
> 2021-02-01 11:23:24 I/Net ***9312013: Connected to server 114.221.148.233:8080
> 2021-02-01 11:23:24 I/Net ***9312013: Connected to server 114.221.144.89:80

貌似又是网络层的问题 在同一时间连接N个服务器很明显是没有锁或者协程未正确关闭
