### ISSUE TITLE
Bot登录缓慢

### ISSUE THREAD

**Issue by Itsusinn** [mamoe/mirai#936]
Bot登录时间很长,然后登录成功，接着瞬间掉线

```
2021-01-30 23:28:45 I/main: Starting mirai-console...
2021-01-30 23:28:45 I/main: Backend: version 2.2.1, built on 2021-01-30 22:09:47.
2021-01-30 23:28:45 I/main: Frontend Terminal: version 2.2.1, provided by Mamoe Technologies
2021-01-30 23:28:45 V/main: Loading configurations...
2021-01-30 23:28:45 V/main: Loading JVM plugins...
2021-01-30 23:28:45 I/plugin: Successfully loaded plugin ForwardPlugin
2021-01-30 23:28:45 I/plugin: Successfully loaded plugin Chat Command
2021-01-30 23:28:45 V/main: 0 external PluginLoader(s) found. 
2021-01-30 23:28:45 V/main: 2 plugin(s) loaded.
2021-01-30 23:28:45 V/main: Loading PermissionService...
2021-01-30 23:28:45 V/main: Reloaded PermissionService settings.
2021-01-30 23:28:45 V/main: Loading built-in commands...
2021-01-30 23:28:46 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2021-01-30 23:28:46 V/main: Enabling plugins...
2021-01-30 23:28:46 I/ForwardPlugin: Plugin enabled
2021-01-30 23:28:46 I/main: 2 plugin(s) enabled.
2021-01-30 23:28:46 I/main: Auto-login ***312013
2021-01-30 23:31:48 I/Bot.***312013: Logging in...
//请注意这里的时间差
2021-01-30 23:35:05 I/Bot.***312013: No OtherClient online.
2021-01-30 23:35:05 V/Bot.***9312013: [[Pc/Pe]SMG生存服(105537)] bili-沫絮(35794) ->[mirai:at:1775751834] 有意思  真的很有意思
2021-01-30 23:35:06 I/Bot.***312013: Login successful
2021-01-30 23:35:06 I/main: mirai-console started successfully.
2021-01-30 23:35:07 I/Bot.***312013: Server requires reconnect.
2021-01-30 23:35:07 I/Bot.***312013: Server list: 157.255.13.60:14000, 109.244.154.52:14000, 14.22.3.51:8080, 42.81.192.211:80, 114.221.148.14:14000, 120.232.22.65:443, 163.177.30.104:80, msfwifi.3g.qq.com:8080.
2021-01-30 23:35:07 I/Bot.***312013: Connection lost, retrying login (RequireReconnect(bot=Bot(***9312013)))
2021-01-30 23:35:07 I/Bot.***312013: Logging in...
//这里无法接到消息
```

#### 复现

桌面开发环境下正常，CentOS下可能产生
（不排除是我学生机的网络问题

#### 版本
- mirai-core: `2.2.1` 
- mirai-console: `2.2.1`

**Comment by mzdluo123** [comment]
请提供网络日志以便于我们确定问题

**Comment by Itsusinn** [comment]
> 请提供网络日志以便于我们确定问题

我已经开启网络日志，它只是没有任何输出。
稍后我将提供jstack生成的thread dump(如果它有用的话

**Comment by Itsusinn** [comment]
当前状况：只是登录很慢，可以正常登录

**Comment by Itsusinn** [comment]
```
"main" #1 prio=5 os_prio=0 cpu=2745.71ms elapsed=56.22s tid=0x00007f2ec4014800 nid=0x2494 runnable  [0x00007f2ecde32000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileInputStream.readBytes(java.base@11.0.9.1/Native Method)
	at java.io.FileInputStream.read(java.base@11.0.9.1/FileInputStream.java:279)
	at java.io.FilterInputStream.read(java.base@11.0.9.1/FilterInputStream.java:133)
	at sun.security.provider.NativePRNG$RandomIO.readFully(java.base@11.0.9.1/NativePRNG.java:424)
	at sun.security.provider.NativePRNG$RandomIO.implGenerateSeed(java.base@11.0.9.1/NativePRNG.java:441)
	- locked <0x00000000ed00c680> (a java.lang.Object)
	at sun.security.provider.NativePRNG.engineGenerateSeed(java.base@11.0.9.1/NativePRNG.java:226)
	at java.security.SecureRandom.generateSeed(java.base@11.0.9.1/SecureRandom.java:857)
	at java.security.SecureRandom.getSeed(java.base@11.0.9.1/SecureRandom.java:840)
	at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin15Kt.get_mpasswd(WtLogin15.kt:136)
	at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:268)
	at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:72)
	at net.mamoe.mirai.internal.QQAndroidBot.initClient(QQAndroidBot.kt:62)
	at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:59)
	at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:34)
	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:115)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:163)
	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:125)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge$doStart$11$1.invokeSuspend(MiraiConsoleImplementationBridge.kt:241)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:214)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)

   Locked ownable synchronizers:
	- <0x00000000ed5cf040> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)

```
完整的thread dump
[dump.log](https://github.com/mamoe/mirai/files/5899240/dump.log)

**Comment by Itsusinn** [comment]
已确认是linux或jdk的bug
```
sun.security.provider.NativePRNG$RandomIO
```
https://bugs.openjdk.java.net/browse/JDK-8098581
看起来linux生成随机数十分的缓慢，有可能是熵池资源被随机数生成耗尽

https://major.io/2007/07/01/check-available-entropy-in-linux/
```
<< cat /proc/sys/kernel/random/entropy_avail
>> 47
```

**Comment by Itsusinn** [comment]
安装rng-tools自动补充熵池可解决该问题，close?

https://blog.csdn.net/tiantao2012/article/details/78792046

**Comment by Itsusinn** [comment]
经过实验，问题如实解决

**Comment by Him188** [comment]
那就close了, 如有问题可以 reopen

**Comment by Him188** [comment]
可以考虑加个选项去掉随机数, 随机数不是必要的
