### ISSUE TITLE
有时会进入无法上传图片状态，重新登录才恢复

### ISSUE THREAD

**Issue by mcdoeswhat** [mamoe/mirai#944]
机器人有时会进入无法上传图片的状态,
大概1-2天出现一次，期间所有图片无法上传，重新登录后恢复

```
[17:52:17 WARN]: kotlinx.coroutines.TimeoutCancellationException: Timeout waiting for ConfigPushSvc.PushReq
[17:52:17 WARN]:        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$init$2$5.invokeSuspend(QQAndroidBotNetworkHandler.kt:472)
[17:52:17 WARN]:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[17:52:17 WARN]:        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
[17:52:17 WARN]:        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
[17:52:17 WARN]:        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
[17:52:17 WARN]:        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
[17:52:17 WARN]:        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[17:52:17 WARN]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[17:52:17 WARN]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[17:52:17 WARN]:        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

#### 版本
- mirai-core: `2.2.0-all`

**Comment by Karlatemp** [comment]
`AbstractUser` 有各种处理

https://github.com/mamoe/mirai/blob/0b8b26f53f5a89562375d83d0fc8560eebcc2c13/mirai-core/src/commonMain/kotlin/contact/AbstractUser.kt#L100-L177

而 `GroupImpl` 是一次直接发送

https://github.com/mamoe/mirai/blob/0b8b26f53f5a89562375d83d0fc8560eebcc2c13/mirai-core/src/commonMain/kotlin/contact/GroupImpl.kt#L162-L174

因此推测问题应该出现在 `Group`

**Comment by Him188** [comment]
是丢失了 ConfigPush，需要提高超时和增加服务器缓存，也可以考虑在丢失时更换服务器登录
