### ISSUE TITLE
2个账号其中一个被大量举报封号，另一个账号抛出异常。

### ISSUE THREAD

**Issue by VoyagerII** [mamoe/mirai#958]
2个账号其中一个被大量举报封号，另一个账号抛出异常。

```
[92m2021-02-03 20:58:51 I/Bot 46765****: Logging in...[0m
[92m2021-02-03 20:58:51 I/Bot 237379****: Logging in...[0m
[91m2021-02-03 20:58:51 W/Net 46765****: Channel closed.[0m
[92m2021-02-03 20:58:51 I/Net 46765****: Syncing friend message history...[0m
[92m2021-02-03 20:58:51 I/Net 46765****: Connected to server 114.221.144.215:80[0m
[92m2021-02-03 20:58:51 I/Net 237379****: Connected to server 42.81.169.46:8080[0m
[0m2021-02-03 20:58:51 V/Net 237379****: Send: wtlogin.login[0m
[0m2021-02-03 20:58:51 V/Net 46765****: Send: wtlogin.login[0m
[31m2021-02-03 20:58:51 E/Net 46765****: Exception in NetworkHandler
kotlin.UninitializedPropertyAccessException: lateinit property wLoginSigInfo has not been initialized
        at net.mamoe.mirai.internal.network.QQAndroidClient.getWLoginSigInfo(QQAndroidClient.kt:320)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbGetMsg.invoke(MessageSvc.PbGetMsg.kt:632)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invokeSuspend(QQAndroidBotNetworkHandler.kt:512)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$syncMessageSvc$3.invoke(QQAndroidBotNetworkHandler.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
        at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:148)
        at kotlinx.coroutines.TimeoutKt.withTimeoutOrNull(Timeout.kt:104)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.syncMessageSvc(QQAndroidBotNetworkHandler.kt:510)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$listener$1$1.invokeSuspend(QQAndroidBotNetworkHandler.kt:503)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
[0m2021-02-03 20:58:51 V/Net 237379****: Recv: Error(title=安全提醒, message=该帐号因涉嫌传播违法违规信息被暂时冻结，请点击下方按钮了解详情及处理。, errorInfo=)[0m
[92m2021-02-03 20:58:51 I/Bot 237379****: Cannot reconnect.[0m
[0m2021-02-03 20:58:51 V/Net 46765****: Recv: WtLogin.Login.LoginPacketResponse.DeviceLockLogin[0m
[0m2021-02-03 20:58:51 V/Net 46765****: Send: wtlogin.login[0m
[91m2021-02-03 20:58:51 W/Bot 46765****: java.util.concurrent.CancellationException: Cannot reconnect.
java.util.concurrent.CancellationException: Cannot reconnect.
        at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
        at net.mamoe.mirai.internal.AbstractBot$Reconnect.reconnect(AbstractBot.kt:203)
        at net.mamoe.mirai.internal.AbstractBot$Reconnect$reconnect$1.invokeSuspend(AbstractBot.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(title=安全提醒, message=该帐号因涉嫌传播违法违规信息被暂时冻结，请点击下方按钮了解详情及处理。, errorInfo=)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:245)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        ... 9 more
[0m
[91m2021-02-03 20:58:51 W/Bot 46765****: java.util.concurrent.CancellationException: Cannot reconnect.
java.util.concurrent.CancellationException: Cannot reconnect.
        at kotlinx.coroutines.ExceptionsKt.CancellationException(Exceptions.kt:22)
        at net.mamoe.mirai.internal.AbstractBot$Reconnect.reconnect(AbstractBot.kt:203)
        at net.mamoe.mirai.internal.AbstractBot$Reconnect$reconnect$1.invokeSuspend(AbstractBot.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(title=安全提醒, message=该帐号因涉嫌传播违法违规信息被暂时冻结，请点击下方按钮了解详情及处理。, errorInfo=)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:245)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        ... 9 more
[0m

[0m2021-02-03 21:03:38 V/Bot 46765****: Group(*****) <- 【频道4】在安博伦世界之树附近有希尔班龙出没！[0m
kotlin.UninitializedPropertyAccessException: lateinit property wLoginSigInfo has not been initialized
        at net.mamoe.mirai.internal.network.QQAndroidClient.getWLoginSigInfo(QQAndroidClient.kt:320)
        at net.mamoe.mirai.internal.contact.GroupSendMessageImplKt.sendMessagePacket(GroupSendMessageImpl.kt:331)
        at net.mamoe.mirai.internal.contact.GroupSendMessageImplKt.sendMessageImpl(GroupSendMessageImpl.kt:54)
        at net.mamoe.mirai.internal.contact.GroupImpl.sendMessage(GroupImpl.kt:119)
        at net.mamoe.mirai.contact.Group.sendMessage(Group.kt:153)
        at net.mamoe.mirai.contact.Group$$sendMessage$$bb$j8ajOnY.invoke(Unknown Source)
        at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
        at net.mamoe.kjbb.internal.RunBlockingKt.$runSuspend$(RunBlocking.kt:18)
        at net.mamoe.mirai.contact.Group.sendMessage(Group.kt)
        at ******
        at ******
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrap.invoke(StaticMetaMethodSite.java:131)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:89)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
        at ******
        at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
        at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
        at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)




```

#### 复现

1. 可复现

#### 版本
- mirai-core: `2.2.0-dev-1`

**Comment by Him188** [comment]
问题在 2.3.2 修复
