### ISSUE TITLE
登录异常 java.lang.IllegalStateException: Required size 16, but found 8

### ISSUE THREAD

**Issue by yuyuko233** [mamoe/mirai#979]
```
java.lang.IllegalStateException: Required size 16, but found 8
java.lang.IllegalStateException: Required size 16, but found 8
        at net.mamoe.mirai.internal.network.protocol.packet.TlvKt.requireSize(Tlv.kt:846)
        at net.mamoe.mirai.internal.network.protocol.packet.TlvKt.t194(Tlv.kt:688)
        at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin9$invoke$$inlined$buildLoginOutgoingPacket$lambda$2.invoke(WtLogin9.kt:82)
        at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin9$invoke$$inlined$buildLoginOutgoingPacket$lambda$2.invoke(WtLogin9.kt:17)
        at net.mamoe.mirai.internal.network.protocol.packet.EncryptMethodECDH.makeBody(EncryptMethod.kt:123)
        at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketAndroidKt.writeOicqRequestPacket(OutgoingPacketAndroid.kt:286)
        at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLogin9.invoke(WtLogin9.kt:25)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:186)
        at net.mamoe.mirai.internal.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:212)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:129)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
2021-02-05 21:23:21 W/Bot.xxxxx: Login failed. Retrying in 3s... (rootCause=java.lang.IllegalStateException: Required size 16, but found 8)
```

#### 复现

登录时不断的出现此段报错, 

#### 版本
- mirai-core: `2.3.2` 
- mirai-console: `2.3.2`
- mirai-console-terminal: `2.3.2`
- Mirai Console Loader: `1.0.4`

**Comment by Him188** [comment]
这是一个 bug, 会尽快解决

现在可尝试 [更换协议](https://github.com/mamoe/mirai/blob/dev/docs/Bots.md#%E5%88%87%E6%8D%A2%E7%99%BB%E5%BD%95%E5%8D%8F%E8%AE%AE)

**Comment by yuyuko233** [comment]
> 
> 
> 这是一个 bug, 会尽快解决
> 
> 现在可尝试 [更换协议](https://github.com/mamoe/mirai/blob/dev/docs/Bots.md#%E5%88%87%E6%8D%A2%E7%99%BB%E5%BD%95%E5%8D%8F%E8%AE%AE)

好的,谢谢

**Comment by Him188** [comment]
经过检查, 这并不是 bug, 而是 `DeviceInfo` 中的 `imsiMd5` 有误. 请自行检查相关问题

**Comment by Him188** [comment]
不过我会添加一个检查, 在构造 Bot 时就报这个错误
