### ISSUE TITLE
 java.security.NoSuchProviderException: JCE cannot authenticate the provider 

### ISSUE THREAD

**Issue by tiararinne** [mamoe/mirai#982]
[92m2021-02-06 10:16:28 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.[0m
[92m2021-02-06 10:16:28 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.[0m
java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
        at javax.crypto.JceSecurity.getInstance(JceSecurity.java:105)
        at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:230)
        at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:81)
        at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion$1$1.invoke(ECDHJvmDesktop.kt:49)
        at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
        at net.mamoe.mirai.internal.utils.crypto.ECDHJvmDesktopKt.ECDH(ECDHJvmDesktop.kt:34)
        at net.mamoe.mirai.internal.network.QQAndroidClient.<init>(QQAndroidClient.kt:72)
        at net.mamoe.mirai.internal.QQAndroidBot.initClient(QQAndroidBot.kt:63)
        at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:59)
        at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:34)
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:115)
        at com.java.relatev.venti.Venti.main(Venti.java:19)
Caused by: java.util.jar.JarException: file:/F:/CodeSource/Java/NBIDE/Venti/dist/lib/mirai-core-all-2.4.0-dev-1-all.jar has unsigned entries - net/mamoe/mirai/internal/AbstractBot$Reconnect$reconnect$1.class
        at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:502)
        at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:363)
        at javax.crypto.JarVerifier.verify(JarVerifier.java:289)
        at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164)
        at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190)
        at javax.crypto.JceSecurity.getInstance(JceSecurity.java:102)
        ... 11 more

上述为报错原文
复现方式：
使用Mirai作为框架开发，在IDE中执行测试时并不会出现此错误
但构建后使用命令行运行时便会有此错误（不管是在本地还是服务器生产环境上）

不过貌似是无害的，尽管报错，程序依旧可以正常运转

**Comment by Karlatemp** [comment]
#808
